import type { SleepListing } from '../types'

/**
 * SLEEP LISTING DATA TEMPLATE
 * -------------------------------------------------------------
 * {
 *   "id": "city-sleep-XX",
 *   "name": "",
 *   "type": "riad | hotel | villa | hostel | apartment | guesthouse",
 *   "neighborhood": "",
 *   "city": "[city]",
 *   "description": "",
 *   "pricePerNight": 0,
 *   "lifestyle": "lean | balanced | premium",
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2', 'url3']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source
 *   // ═══════════════════════════════════════════════════
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *   bookingRating: [4.x],
 *   bookingReviewCount: [number],
 *   hotelguruRating: [4.x],
 *   hotelguruReviewCount: [number],
 *
 *   // ═══════════════════════════════════════════════════
 *   // BOOLEAN AMENITIES
 *   // ═══════════════════════════════════════════════════
 *   hasPool: true | false,
 *   hasBreakfast: true | false,
 *   hasAC: true | false,
 *   hasHeating: true | false,
 *   hasRooftop: true | false,
 *   hasEnsuite: true | false,
 *   hasRestaurant: true | false,
 *   hasBar: true | false,
 *   hasGym: true | false,
 *   hasElevator: true | false,
 *   hasLaundryService: true | false,
 *   hasRoomService: true | false,
 *   petFriendly: true | false,
 *   isWheelchairAccessible: true | false,
 *   taxesIncluded: true | false,
 *   freeCancellation: true | false,
 *   kidsStayFree: true | false,
 *
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearMosque: true | false,
 *   safetyLevel: 1 | 2 | 3 | 4 | 5,
 *
 *   // ═══════════════════════════════════════════════════
 *   // TRUST SCORES
 *   // ═══════════════════════════════════════════════════
 *   trustScores: {
 *     cleanliness: [1-10],
 *     safety: [1-10],
 *     staff: [1-10],
 *     value: [1-10],
 *     comfort: [1-10],
 *     location: [1-10]
 *   },
 *
 *   amenities: [],
 *   tip: '[Short insider tip]',
 *   vibeTags: [],
 *   locationSummary: '',
 *   availabilityText: '',
 *   googleMapsUrl: '',
 *   address: '',
 *
 *   paymentMethods: ['card', 'cash'],
 *   languagesSpoken: ['Arabic', 'French', 'English'],
 *   groupTypes: [],
 *
 *   customStory: '',
 *   neighborhoodOverview: '',
 *   hiddenFeesNotice: '',
 *   pros: [],
 *   cons: [],
 *
 *   logistics: {
 *     checkIn: '',
 *     checkOut: '',
 *     luggageStorage: '',
 *     parking: '',
 *     contact: ''
 *   },
 *
 *   roomFeatures: [],
 *   roomTypes: [
 *   ],
 *
 *   neighborhoodDistances: [],
 *   cancellationPolicy: '',
 *   childPolicy: '',
 *   officialWebsite: '',
 *   instagramHandle: '',
 *   // googlePlaceId: "PLACE_ID_HERE",
 *
 *   reviewHighlights: {
 *     solo: '',
 *     couples: '',
 *     families: '',
 *     business: '',
 *     nomad: ''
 *   }
 * }
 */

export const alHoceimaSleep: SleepListing[] = [
  {
    id: 'ah-sleep-1',
    name: 'Radisson Blu Resort, Al Hoceima',
    type: 'hotel',
    neighborhood: 'Beachfront',
    city: 'al_hoceima',
    description: 'A magnificent five-star resort situated directly on Sfiha Beach with stunning views of the Mediterranean and Peñón de Alhucemas. It offers a luxurious beach holiday atmosphere with modern amenities and comprehensive leisure facilities.',
    pricePerNight: 260,
    lifestyle: 'premium',
    amenities: ['wifi', 'pool', 'ac', 'spa', 'beach', 'restaurant', 'tennis'],
    googleRating: 4.2,
    googleReviewCount: 850,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 850,
    bookingRating: 4.2,
    bookingReviewCount: 850,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 850,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family', 'friends', 'business-friendly'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Head down to Plage Sfiha early in the morning to enjoy a quiet stroll with views of the historic Spanish island fortress.',
    vibeTags: ['Luxury', 'Beachfront', 'Mediterranean', 'Resort'],
    locationSummary: 'Beachfront',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.2054337,-3.9007352',
    address: 'Sfiha Beach, Al Hoceima 32000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Part of the Radisson Blu collection, this flagship beachfront resort opened to bring luxury to Al Hoceima\'s stunning Mediterranean coastline.',
    neighborhoodOverview: 'Located on the serene Sfiha Beach, offering direct views of the Mediterranean and historic islets.',
    hiddenFeesNotice: 'City tax of 28.60 MAD per person/night not included.',
    pros: ['Direct beach access', 'Stunning sea views', 'Excellent spa and facilities'],
    cons: ['Premium pricing', 'Can feel isolated from town center'],
    trustScores: {
      cleanliness: 8.8,
      safety: 9.1,
      staff: 8.6,
      value: 7.9,
      comfort: 8.9,
      location: 9.5
    },
    logistics: {
      checkIn: '15:00 - 23:00',
      checkOut: 'Before 12:00',
      luggageStorage: 'Free',
      parking: 'Free on-site',
      contact: '+212539844000'
    },
    roomFeatures: ['ac', 'heating', 'sea-view', 'balcony', 'minibar'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Sfiha Beach', distance: 'Direct', time: '1 min walk', icon: 'beach' },
      { label: 'Al Hoceima Center', distance: '7km', time: '12 min drive', icon: 'city' },
      { label: 'Airport', distance: '6km', time: '10 min drive', icon: 'plane' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://www.radissonhotels.com/en-us/hotels/radisson-blu-resort-al-hoceima',
    instagramHandle: '@radissonblualhoceima',
    reviewHighlights: {
      solo: 'Peaceful luxury escape with great spa.',
      couples: 'Romantic beachfront views and dining.',
      families: 'Spacious rooms and kids facilities.',
      business: 'Meeting rooms and reliable WiFi.',
      nomad: 'Good workspace with Mediterranean views.'
    }
  },
  {
    id: 'ah-sleep-2',
    name: 'Mercure Quemado Al-Hoceima Resort',
    type: 'hotel',
    neighborhood: 'near Quemado Beach',
    city: 'al_hoceima',
    description: 'Perched dramatically on a cliffside overlooking Quemado Beach, this popular resort offers direct access to the sand. It features contemporary accommodations with spectacular gulf views and a bustling coastal vibe.',
    pricePerNight: 130,
    lifestyle: 'balanced',
    amenities: ['wifi', 'pool', 'ac', 'spa', 'beach', 'restaurant'],
    googleRating: 4.2,
    googleReviewCount: 1600,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 700,
    bookingRating: 4.1,
    bookingReviewCount: 1200,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 100,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family', 'friends', 'business-friendly'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Ask for a room on the higher floors of the Quemado complex to enjoy the most sweeping views of Quemado Beach and the surrounding bay.',
    vibeTags: ['Cliffside', 'Beachfront', 'Views', 'Family'],
    locationSummary: 'Cliffside Beachfront',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.24416,-3.927838',
    address: 'Quemado Beach, Al Hoceima 32000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'A well-established Accor Mercure property with iconic cliff-top location overlooking the famous Quemado Beach.',
    neighborhoodOverview: 'Cliffside resort overlooking the bay, steps from the beach.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Spectacular beach and bay views', 'Great central location', 'Large pool area'],
    cons: ['Some rooms show age', 'Can get busy'],
    trustScores: {
      cleanliness: 8.5,
      safety: 8.8,
      staff: 8.4,
      value: 8.7,
      comfort: 8.3,
      location: 9.4
    },
    logistics: {
      checkIn: '14:00 - 23:00',
      checkOut: 'Before 12:00',
      luggageStorage: 'Free',
      parking: 'Free',
      contact: '+212539842200'
    },
    roomFeatures: ['ac', 'heating', 'sea-view', 'balcony'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Quemado Beach', distance: 'Direct', time: '2 min walk', icon: 'beach' },
      { label: 'City Center', distance: '500m', time: '6 min walk', icon: 'city' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children stay free using existing bedding.',
    officialWebsite: 'https://all.accor.com/hotel/9676/index.en.shtml',
    instagramHandle: '@mercurequemado',
    reviewHighlights: {
      solo: 'Great views for solo travelers.',
      couples: 'Romantic cliffside sunsets.',
      families: 'Good pool and beach access.',
      business: 'Convenient location.',
      nomad: 'Great views while working.'
    }
  },
  {
    id: 'ah-sleep-3',
    name: 'Radisson Blu Residences, Al Hoceima',
    type: 'hotel',
    neighborhood: 'Beachfront',
    city: 'al_hoceima',
    description: 'An upscale apartment-style property combining self-catering convenience with five-star resort amenities on Sfiha Beach. The residences offer a comfortable home-away-from-home setting with pristine coastal views.',
    pricePerNight: 180,
    lifestyle: 'balanced',
    amenities: ['wifi', 'pool', 'ac', 'kitchen', 'beach'],
    googleRating: 4.0,
    googleReviewCount: 520,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 300,
    bookingRating: 4.0,
    bookingReviewCount: 400,
    hotelguruRating: 4.0,
    hotelguruReviewCount: 50,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family', 'friends', 'business-friendly'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'These apartments are ideal for long-staying families; bring your own groceries to cook in the modern kitchen while enjoying beachfront resort access.',
    vibeTags: ['Apartment', 'Self-Catering', 'Beachfront', 'Family'],
    locationSummary: 'Beachfront',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.203326,-3.886409',
    address: 'Sfiha Beach, Al Hoceima 32000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'The apartment wing of the Radisson Blu complex offering more space and independence.',
    neighborhoodOverview: 'Beachfront area with resort amenities.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Spacious apartments', 'Kitchen facilities', 'Resort amenities'],
    cons: ['Breakfast not always included', 'Some reviews mention maintenance'],
    trustScores: {
      cleanliness: 8.3,
      safety: 8.7,
      staff: 8.0,
      value: 8.2,
      comfort: 8.5,
      location: 9.2
    },
    logistics: {
      checkIn: '16:00 - 23:00',
      checkOut: 'Before 12:00',
      luggageStorage: 'Free',
      parking: 'Free',
      contact: '+212539844400'
    },
    roomFeatures: ['ac', 'heating', 'kitchen', 'sea-view'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Sfiha Beach', distance: 'Direct', time: '1 min', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children welcome; apartments ideal for families.',
    officialWebsite: 'https://www.radissonhotels.com/en-us/hotels/radisson-blu-residences-al-hoceima',
    instagramHandle: '@radissonblualhoceima',
    reviewHighlights: {
      solo: 'Good for longer stays.',
      couples: 'Spacious and comfortable.',
      families: 'Kitchen and extra space.',
      business: 'Self-catering convenience.',
      nomad: 'Kitchen for long stays.'
    }
  },
  {
    id: 'ah-sleep-4',
    name: 'Suites Hotel Mohammed V',
    type: 'hotel',
    neighborhood: 'near Quemado Beach',
    city: 'al_hoceima',
    description: 'A historic, elegant hotel on Mohammed V Place that blends classic Moroccan hospitality with exceptional views over Quemado Beach. It provides a refined, nostalgic seaside charm in a prime downtown cliffside location.',
    pricePerNight: 120,
    lifestyle: 'balanced',
    amenities: ['wifi', 'pool', 'ac', 'beach', 'restaurant', 'views'],
    googleRating: 4.2,
    googleReviewCount: 720,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 300,
    bookingRating: 4.1,
    bookingReviewCount: 500,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 80,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family', 'business-friendly'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Ideal for couples seeking a bit of history and romance; enjoy a dinner at the hotel\'s panoramic restaurant overlooking the bay.',
    vibeTags: ['Historic', 'Views', 'Elegant', 'Central'],
    locationSummary: 'Cliffside - City Center',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.244388,-3.927561',
    address: 'Place Mohammed V, Al Hoceima 32000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'A landmark hotel with long history and prime location overlooking the famous Quemado Beach.',
    neighborhoodOverview: 'Central cliffside location overlooking the bay.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Iconic location', 'Great views', 'Classic charm'],
    cons: ['Pool is shared with sister property', 'Some areas dated'],
    trustScores: {
      cleanliness: 8.4,
      safety: 8.6,
      staff: 8.5,
      value: 8.3,
      comfort: 8.2,
      location: 9.3
    },
    logistics: {
      checkIn: '15:00 - 22:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Free',
      contact: '+212539842000'
    },
    roomFeatures: ['ac', 'heating', 'sea-view', 'historic-charm'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Quemado Beach', distance: '100m', time: '2 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children welcome; suites available.',
    officialWebsite: 'https://www.accor.com',
    instagramHandle: '@suitesmohammedv',
    reviewHighlights: {
      solo: 'Great central base.',
      couples: 'Romantic panoramic dining.',
      families: 'Spacious suites.',
      business: 'Convenient downtown.',
      nomad: 'Historic charm while working.'
    }
  },
  {
    id: 'ah-sleep-5',
    name: 'Casa Paca Alhucemas Guesthouse B&B',
    type: 'guesthouse',
    neighborhood: 'Beachfront',
    city: 'al_hoceima',
    description: 'A charming, family-run guesthouse located on a scenic hill just a short walk from Sfiha Beach. It features beautiful terraces, stunning sea views of the bay, and unparalleled, personalized Moroccan hospitality.',
    pricePerNight: 75,
    lifestyle: 'lean',
    amenities: ['wifi', 'ac', 'breakfast', 'rooftop', 'views'],
    googleRating: 4.7,
    googleReviewCount: 220,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 100,
    bookingRating: 4.8,
    bookingReviewCount: 150,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 30,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Savor a fresh, homemade Moroccan breakfast on the terrace prepared by Joaquin, with breathtaking panoramic views of the bay.',
    vibeTags: ['Authentic', 'Views', 'Boutique', 'Guesthouse'],
    locationSummary: 'Hillside - Near Beach',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.20759,-3.899722',
    address: 'Sfiha Beach, Al Hoceima 32000, Morocco',
    paymentMethods: ['cash', 'card'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'A beloved family-run guesthouse offering warm hospitality and incredible views near Sfiha Beach.',
    neighborhoodOverview: 'Hillside residential area with views of the bay.',
    hiddenFeesNotice: 'None.',
    pros: ['Exceptional hosts', 'Stunning terraces', 'Great value'],
    cons: ['No pool', 'Short walk to beach'],
    trustScores: {
      cleanliness: 9.2,
      safety: 9.0,
      staff: 9.5,
      value: 9.3,
      comfort: 8.8,
      location: 8.7
    },
    logistics: {
      checkIn: '14:00 - 21:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Nearby public',
      contact: '+212673867501'
    },
    roomFeatures: ['ac', 'heating', 'sea-view', 'terrace-access'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Sfiha Beach', distance: '400m', time: '5 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: '',
    instagramHandle: '@casapacaalhucemas',
    reviewHighlights: {
      solo: 'Warm and personal stay.',
      couples: 'Romantic terrace breakfasts.',
      families: 'Cozy and welcoming.',
      business: 'Peaceful retreat.',
      nomad: 'Beautiful terrace workspace.'
    }
  },
  {
    id: 'ah-sleep-6',
    name: 'Hôtel Al Hoceima Bay',
    type: 'hotel',
    neighborhood: 'Beachfront',
    city: 'al_hoceima',
    description: 'A modern, comfortable hotel located close to the shoreline of Al Hoceima Bay. It offers a relaxing seaside atmosphere complete with a spacious pool and friendly hospitality.',
    pricePerNight: 95,
    lifestyle: 'balanced',
    amenities: ['wifi', 'pool', 'ac', 'beach', 'breakfast'],
    googleRating: 4.1,
    googleReviewCount: 300,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 150,
    bookingRating: 4.0,
    bookingReviewCount: 250,
    hotelguruRating: 4.1,
    hotelguruReviewCount: 40,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family', 'business-friendly'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Excellent option if you want to avoid the peak crowds in town; take a short drive to the quieter Tala Youssef Beach nearby.',
    vibeTags: ['Modern', 'Pool', 'Relaxed', 'Beach'],
    locationSummary: 'Near Beach',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.20759,-3.899722',
    address: 'Sfiha Beach, Al Hoceima 32000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'A welcoming mid-range hotel offering easy access to the bay.',
    neighborhoodOverview: 'Coastal area close to the bay and beach.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Good value', 'Nice pool', 'Friendly staff'],
    cons: ['Basic rooms', 'Not directly on beach'],
    trustScores: {
      cleanliness: 8.2,
      safety: 8.5,
      staff: 8.3,
      value: 8.8,
      comfort: 8.0,
      location: 8.6
    },
    logistics: {
      checkIn: '14:00 - 22:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Free',
      contact: '+212539844000'
    },
    roomFeatures: ['ac', 'heating', 'pool-access'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Beach', distance: '300m', time: '4 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: '',
    instagramHandle: '',
    reviewHighlights: {
      solo: 'Good quiet base.',
      couples: 'Relaxed pool time.',
      families: 'Decent facilities.',
      business: 'Practical.',
      nomad: 'Pool break while working.'
    }
  },
  {
    id: 'ah-sleep-7',
    name: 'Hotel Mira Palace Al Hoceima',
    type: 'hotel',
    neighborhood: 'Al Hoceima Center',
    city: 'al_hoceima',
    description: 'A stylish and highly regarded hotel offering comfortable accommodations with views of the Mediterranean coastline and city. It features beautifully manicured gardens, an outdoor pool, and a tranquil, welcoming ambiance.',
    pricePerNight: 110,
    lifestyle: 'balanced',
    amenities: ['wifi', 'pool', 'ac', 'garden', 'breakfast'],
    googleRating: 4.0,
    googleReviewCount: 420,
    tripadvisorRating: 3.5,
    tripadvisorReviewCount: 180,
    bookingRating: 3.9,
    bookingReviewCount: 300,
    hotelguruRating: 4.0,
    hotelguruReviewCount: 60,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family', 'friends', 'business-friendly'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Relax by the beautiful garden pool in the late afternoon to escape the midday coastal heat.',
    vibeTags: ['Garden', 'Pool', 'Tranquil', 'Central'],
    locationSummary: 'City Center - Garden',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.24916,-3.945808',
    address: 'Avenue Tarik Ibn Ziad, Al Hoceima 32000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'A peaceful hotel with lovely gardens in central Al Hoceima.',
    neighborhoodOverview: 'Central area with easy access to town.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Lovely garden and pool', 'Good value', 'Quiet'],
    cons: ['Slightly further from beach', 'Limited dining'],
    trustScores: {
      cleanliness: 8.1,
      safety: 8.4,
      staff: 8.2,
      value: 8.6,
      comfort: 8.0,
      location: 7.9
    },
    logistics: {
      checkIn: '14:00 - 22:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Free',
      contact: '+212539840084'
    },
    roomFeatures: ['ac', 'heating', 'garden-view'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Center', distance: 'Central', time: '0 min', icon: 'city' },
      { label: 'Beach', distance: '1.5km', time: '5 min drive', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: '',
    instagramHandle: '',
    reviewHighlights: {
      solo: 'Peaceful garden setting.',
      couples: 'Romantic evenings.',
      families: 'Space for kids.',
      business: 'Quiet and convenient.',
      nomad: 'Garden workspace.'
    }
  },
  {
    id: 'ah-sleep-8',
    name: 'Appart Hotel Bloom',
    type: 'apartment',
    neighborhood: 'Al Hoceima Center',
    city: 'al_hoceima',
    description: 'Modern, fully-equipped serviced apartments located a short walk from both Al Hoceima Center and the beaches. The vibe is highly independent, comfortable, and perfect for families wanting a self-catering stay.',
    pricePerNight: 78,
    lifestyle: 'lean',
    amenities: ['wifi', 'ac', 'kitchen'],
    googleRating: 4.5,
    googleReviewCount: 28,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 10,
    bookingRating: 4.6,
    bookingReviewCount: 20,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 5,
    hasPool: false,
    hasBreakfast: false,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Its proximity to downtown markets makes it easy to purchase fresh local ingredients and seafood to cook in your private kitchen.',
    vibeTags: ['Apartment', 'Self-Catering', 'Central', 'Modern'],
    locationSummary: 'City Center',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.24708,-3.93184',
    address: 'Rue Palestine, Al Hoceima 32000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Modern serviced apartments ideal for independent travelers.',
    neighborhoodOverview: 'Central neighborhood near markets and shops.',
    hiddenFeesNotice: 'None.',
    pros: ['Kitchen facilities', 'Central location', 'Good value'],
    cons: ['No pool', 'Breakfast not included'],
    trustScores: {
      cleanliness: 8.9,
      safety: 8.7,
      staff: 8.3,
      value: 9.1,
      comfort: 8.6,
      location: 8.8
    },
    logistics: {
      checkIn: '15:00 - 22:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Nearby',
      contact: '+212539840000'
    },
    roomFeatures: ['ac', 'heating', 'kitchen'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Beach', distance: '800m', time: '10 min walk', icon: 'beach' },
      { label: 'Center', distance: '300m', time: '4 min walk', icon: 'city' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children welcome; apartments for families.',
    officialWebsite: '',
    instagramHandle: '',
    reviewHighlights: {
      solo: 'Great for independent stays.',
      couples: 'Comfortable and private.',
      families: 'Kitchen is a big plus.',
      business: 'Practical.',
      nomad: 'Good for long stays.'
    }
  },
  {
    id: 'ah-sleep-9',
    name: 'Royal Rif Alhoceima',
    type: 'apartment',
    neighborhood: 'Beachfront',
    city: 'al_hoceima',
    description: 'A highly-rated aparthotel providing spacious, modern suites within a peaceful residential community near Sfiha Beach. It features exceptional guest service, family suites, and private terraces with mountain and sea backdrops.',
    pricePerNight: 85,
    lifestyle: 'balanced',
    amenities: ['wifi', 'ac', 'kitchenette', 'parking'],
    googleRating: 4.6,
    googleReviewCount: 660,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 300,
    bookingRating: 4.6,
    bookingReviewCount: 400,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 100,
    hasPool: false,
    hasBreakfast: false,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Perfect for travelers seeking a quiet retreat; take a short 5-minute taxi ride to visit the nearby beaches or local historic spots.',
    vibeTags: ['Apartment', 'Quiet', 'Views', 'Family'],
    locationSummary: 'Residential - Near Beach',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.203,-3.886',
    address: 'Sfiha Beach, Al Hoceima 32000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Popular aparthotel in a residential area near the beach.',
    neighborhoodOverview: 'Quiet residential area with sea and mountain views.',
    hiddenFeesNotice: 'None.',
    pros: ['Spacious suites', 'Quiet area', 'Good parking'],
    cons: ['No pool', 'Need transport to main beach'],
    trustScores: {
      cleanliness: 9.0,
      safety: 8.9,
      staff: 8.7,
      value: 9.0,
      comfort: 8.8,
      location: 8.2
    },
    logistics: {
      checkIn: '14:00 - 22:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Free private',
      contact: '+212539840000'
    },
    roomFeatures: ['ac', 'heating', 'terrace', 'kitchenette'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Beach', distance: '1km', time: '5 min drive', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children welcome; spacious suites for families.',
    officialWebsite: '',
    instagramHandle: '',
    reviewHighlights: {
      solo: 'Quiet and comfortable.',
      couples: 'Good value space.',
      families: 'Excellent for families.',
      business: 'Peaceful.',
      nomad: 'Quiet apartment workspace.'
    }
  },
  {
    id: 'ah-sleep-10',
    name: 'Hôtel Souani',
    type: 'hotel',
    neighborhood: 'Beachfront',
    city: 'al_hoceima',
    description: 'An elegant coastal hotel located just steps from Sfiha beach, offering a peaceful, mid-range lodging option. It features cozy, air-conditioned rooms, a large outdoor pool, and scenic Mediterranean vistas.',
    pricePerNight: 90,
    lifestyle: 'balanced',
    amenities: ['wifi', 'pool', 'ac', 'beach', 'breakfast'],
    googleRating: 3.8,
    googleReviewCount: 450,
    tripadvisorRating: 3.5,
    tripadvisorReviewCount: 200,
    bookingRating: 3.7,
    bookingReviewCount: 300,
    hotelguruRating: 3.8,
    hotelguruReviewCount: 50,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family', 'business-friendly'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Stroll along Sfiha beach in the late afternoon to photograph the Peñón de Alhucemas as the sun goes down.',
    vibeTags: ['Pool', 'Beach', 'Relaxed', 'Value'],
    locationSummary: 'Beachfront',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.20759,-3.899722',
    address: 'Sfiha Beach, Al Hoceima 32000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'A solid mid-range hotel with pool close to the beach.',
    neighborhoodOverview: 'Coastal area near Sfiha beach.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Good pool', 'Beach proximity', 'Value'],
    cons: ['Older property', 'Basic rooms'],
    trustScores: {
      cleanliness: 7.8,
      safety: 8.2,
      staff: 7.9,
      value: 8.5,
      comfort: 7.7,
      location: 9.0
    },
    logistics: {
      checkIn: '14:00 - 22:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Free',
      contact: '+212539840000'
    },
    roomFeatures: ['ac', 'heating', 'pool-access'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Sfiha Beach', distance: '150m', time: '2 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: '',
    instagramHandle: '',
    reviewHighlights: {
      solo: 'Simple beach access.',
      couples: 'Pool and beach.',
      families: 'Decent facilities.',
      business: 'Practical.',
      nomad: 'Basic but functional.'
    }
  },
  {
    id: 'ah-sleep-11',
    name: 'Appart Hotel Puerto Marino',
    type: 'apartment',
    neighborhood: 'near Quemado Beach',
    city: 'al_hoceima',
    description: 'A modern condo-hotel offering sleek sea-view apartments with comfortable, fully equipped living spaces. The property is designed around an outdoor pool and offers a welcoming, family-friendly coastal atmosphere.',
    pricePerNight: 110,
    lifestyle: 'balanced',
    amenities: ['wifi', 'pool', 'ac', 'kitchen'],
    googleRating: 4.4,
    googleReviewCount: 150,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 80,
    bookingRating: 4.2,
    bookingReviewCount: 120,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 30,
    hasPool: true,
    hasBreakfast: false,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Take advantage of the apartment\'s smart TV and stable Wi-Fi for quiet, relaxing evenings after swimming.',
    vibeTags: ['Apartment', 'Pool', 'Modern', 'Sea View'],
    locationSummary: 'Near Beach - Pool',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.24416,-3.927838',
    address: 'Near Quemado Beach, Al Hoceima 32000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Modern apartment hotel with pool near the beach.',
    neighborhoodOverview: 'Coastal area near Quemado Beach.',
    hiddenFeesNotice: 'None.',
    pros: ['Modern apartments', 'Pool', 'Views'],
    cons: ['Breakfast not included', 'Can feel small'],
    trustScores: {
      cleanliness: 8.8,
      safety: 8.6,
      staff: 8.4,
      value: 8.5,
      comfort: 8.7,
      location: 9.0
    },
    logistics: {
      checkIn: '15:00 - 22:00',
      checkOut: 'Before 12:00',
      luggageStorage: 'Free',
      parking: 'Free',
      contact: '+212539842000'
    },
    roomFeatures: ['ac', 'heating', 'sea-view', 'kitchen'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Quemado Beach', distance: '300m', time: '4 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: '',
    instagramHandle: '',
    reviewHighlights: {
      solo: 'Comfortable modern stay.',
      couples: 'Nice views and pool.',
      families: 'Good space and kitchen.',
      business: 'Reliable.',
      nomad: 'Modern apartment workspace.'
    }
  },
  {
    id: 'ah-sleep-12',
    name: 'Hôtel La Perla',
    type: 'hotel',
    neighborhood: 'Al Hoceima Center',
    city: 'al_hoceima',
    description: 'A well-known, central hotel providing clean, comfortable lodging at a great value in Al Hoceima. It serves as a reliable base for exploring local restaurants, downtown cafes, and the nearby harbor.',
    pricePerNight: 65,
    lifestyle: 'lean',
    amenities: ['wifi', 'ac', 'breakfast'],
    googleRating: 4.1,
    googleReviewCount: 830,
    tripadvisorRating: 3.5,
    tripadvisorReviewCount: 200,
    bookingRating: 3.8,
    bookingReviewCount: 400,
    hotelguruRating: 4.1,
    hotelguruReviewCount: 50,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family', 'business-friendly'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Perfect for travelers who want to be in the center of the town\'s evening hustle; try the local cafes nearby for authentic mint tea.',
    vibeTags: ['Central', 'Value', 'Clean', 'Budget'],
    locationSummary: 'City Center',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.24708,-3.93184',
    address: 'Rue Palestine, Al Hoceima 32000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Reliable central hotel popular with travelers.',
    neighborhoodOverview: 'Central area within walking distance to everything.',
    hiddenFeesNotice: 'None.',
    pros: ['Great location', 'Clean rooms', 'Good breakfast'],
    cons: ['No pool', 'Basic facilities'],
    trustScores: {
      cleanliness: 8.5,
      safety: 8.4,
      staff: 8.2,
      value: 9.0,
      comfort: 7.9,
      location: 9.2
    },
    logistics: {
      checkIn: '14:00 - 22:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Nearby',
      contact: '+212539840000'
    },
    roomFeatures: ['ac', 'heating'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Center', distance: 'Central', time: '0 min', icon: 'city' },
      { label: 'Beach', distance: '1km', time: '12 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: '',
    instagramHandle: '',
    reviewHighlights: {
      solo: 'Perfect central location.',
      couples: 'Good value.',
      families: 'Convenient.',
      business: 'Walkable to everything.',
      nomad: 'Central base.'
    }
  },
  {
    id: 'ah-sleep-13',
    name: 'Seaview Carabonita',
    type: 'apartment',
    neighborhood: 'Beachfront',
    city: 'al_hoceima',
    description: 'An exceptional beachfront apartment offering a serene getaway right on the shores of Cala Bonita Beach. It boasts private balconies with dramatic cliff views and a highly intimate, restful seaside vibe.',
    pricePerNight: 70,
    lifestyle: 'lean',
    amenities: ['wifi', 'ac', 'kitchen', 'beach'],
    googleRating: 4.9,
    googleReviewCount: 15,
    tripadvisorRating: 5.0,
    tripadvisorReviewCount: 5,
    bookingRating: 4.8,
    bookingReviewCount: 10,
    hotelguruRating: 4.9,
    hotelguruReviewCount: 2,
    hasPool: false,
    hasBreakfast: false,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Wake up early to catch a breathtaking sunrise over Cala Bonita\'s calm waters directly from your balcony.',
    vibeTags: ['Beachfront', 'Cliff', 'Private', 'Sunrise'],
    locationSummary: 'Beachfront - Cala Bonita',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.149185,-4.376614',
    address: 'Cala Bonita Beach, Al Hoceima 32000, Morocco',
    paymentMethods: ['cash', 'card'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Intimate beach apartment on the beautiful Cala Bonita.',
    neighborhoodOverview: 'Remote beach location with stunning cliff views.',
    hiddenFeesNotice: 'None.',
    pros: ['Direct beach access', 'Amazing views', 'Private'],
    cons: ['Very small review base', 'Remote location'],
    trustScores: {
      cleanliness: 9.5,
      safety: 9.0,
      staff: 8.8,
      value: 9.4,
      comfort: 9.2,
      location: 9.6
    },
    logistics: {
      checkIn: '15:00 - 21:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Free',
      contact: '+212661234567'
    },
    roomFeatures: ['ac', 'heating', 'sea-view', 'balcony'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Cala Bonita Beach', distance: 'Direct', time: '1 min', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Best for adults or older children',
    officialWebsite: '',
    instagramHandle: '',
    reviewHighlights: {
      solo: 'Perfect peaceful escape.',
      couples: 'Romantic cliff views.',
      families: 'Intimate for small groups.',
      business: 'Not ideal.',
      nomad: 'Remote work with a view.'
    }
  },
  {
    id: 'ah-sleep-14',
    name: 'New Apartment for Rent in Bades',
    type: 'apartment',
    neighborhood: 'Al Hoceima Center',
    city: 'al_hoceima',
    description: 'A spotless and spacious modern apartment located in the newly developed Bades neighborhood. The environment is remarkably quiet, clean, and safe, providing a great base for families traveling by car.',
    pricePerNight: 68,
    lifestyle: 'lean',
    amenities: ['wifi', 'ac', 'parking'],
    googleRating: 4.6,
    googleReviewCount: 45,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 10,
    bookingRating: 4.7,
    bookingReviewCount: 20,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 5,
    hasPool: false,
    hasBreakfast: false,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'This apartment has excellent, secure parking; it is ideal if you plan to drive out to remote coves in Al Hoceima National Park.',
    vibeTags: ['Modern', 'Quiet', 'Parking', 'Family'],
    locationSummary: 'Residential - Bades',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.24708,-3.93184',
    address: 'Bades Neighborhood, Al Hoceima 32000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'New development apartment in safe quiet area.',
    neighborhoodOverview: 'Newly developed residential area, quiet and safe.',
    hiddenFeesNotice: 'None.',
    pros: ['Modern and clean', 'Secure parking', 'Quiet'],
    cons: ['No pool or breakfast', 'Slightly away from beach'],
    trustScores: {
      cleanliness: 9.1,
      safety: 9.3,
      staff: 8.5,
      value: 9.2,
      comfort: 8.7,
      location: 7.8
    },
    logistics: {
      checkIn: '15:00 - 22:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Free secure',
      contact: '+212539840000'
    },
    roomFeatures: ['ac', 'heating', 'secure-parking'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Center', distance: '1.5km', time: '5 min drive', icon: 'city' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: '',
    instagramHandle: '',
    reviewHighlights: {
      solo: 'Quiet and secure.',
      couples: 'Comfortable base.',
      families: 'Great for car travelers.',
      business: 'Peaceful.',
      nomad: 'Quiet for focused work.'
    }
  },
  {
    id: 'ah-sleep-15',
    name: 'RS Apartments - AL HOCEIMA',
    type: 'apartment',
    neighborhood: 'Al Hoceima Center',
    city: 'al_hoceima',
    description: 'A selection of beautiful, modern apartments featuring stunning panoramic sea views from private balconies. It provides travelers with comfortable, independent living spaces close to central amenities.',
    pricePerNight: 95,
    lifestyle: 'balanced',
    amenities: ['wifi', 'ac', 'kitchen', 'views'],
    googleRating: 4.4,
    googleReviewCount: 65,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 20,
    bookingRating: 4.2,
    bookingReviewCount: 30,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 10,
    hasPool: false,
    hasBreakfast: false,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Book the sea-view units on the upper floors to enjoy sunset over the cliffs of Al Hoceima with your family.',
    vibeTags: ['Views', 'Apartment', 'Modern', 'Panoramic'],
    locationSummary: 'City Center - Sea Views',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.24416,-3.927838',
    address: 'Rue Palestine, Al Hoceima 32000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Modern apartments with excellent sea views.',
    neighborhoodOverview: 'Central area with sea views.',
    hiddenFeesNotice: 'None.',
    pros: ['Panoramic views', 'Modern', 'Central'],
    cons: ['No pool', 'Breakfast not included'],
    trustScores: {
      cleanliness: 8.7,
      safety: 8.5,
      staff: 8.3,
      value: 8.6,
      comfort: 8.8,
      location: 8.9
    },
    logistics: {
      checkIn: '15:00 - 22:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Free',
      contact: '+212539840000'
    },
    roomFeatures: ['ac', 'heating', 'sea-view', 'balcony'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Beach', distance: '800m', time: '10 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: '',
    instagramHandle: '',
    reviewHighlights: {
      solo: 'Great views for solo.',
      couples: 'Sunset balconies.',
      families: 'Spacious and convenient.',
      business: 'Good base.',
      nomad: 'Panoramic views while working.'
    }
  },
  {
    id: 'ah-sleep-16',
    name: 'Hôtel La Marina',
    type: 'hotel',
    neighborhood: 'near Quemado Beach',
    city: 'al_hoceima',
    description: 'A cozy and central hotel situated near the scenic port and Quemado Beach. It features basic but clean and comfortable rooms, presenting a highly convenient base for budget-conscious coastal travelers.',
    pricePerNight: 55,
    lifestyle: 'lean',
    amenities: ['wifi', 'ac', 'breakfast'],
    googleRating: 3.9,
    googleReviewCount: 180,
    tripadvisorRating: 3.5,
    tripadvisorReviewCount: 80,
    bookingRating: 3.7,
    bookingReviewCount: 150,
    hotelguruRating: 3.9,
    hotelguruReviewCount: 20,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Take a short walk down to the port in the evening to buy fresh grilled sardines from local dockside stalls.',
    vibeTags: ['Port', 'Budget', 'Central', 'Harbor'],
    locationSummary: 'Port Area - Near Beach',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.24416,-3.927838',
    address: 'Avenue Tarik Ibn Ziad, Al Hoceima 32000, Morocco',
    paymentMethods: ['cash', 'card'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Budget-friendly hotel near the port and beach.',
    neighborhoodOverview: 'Central port area near beach and restaurants.',
    hiddenFeesNotice: 'None.',
    pros: ['Excellent location', 'Good breakfast', 'Value'],
    cons: ['Basic rooms', 'No pool'],
    trustScores: {
      cleanliness: 7.9,
      safety: 8.1,
      staff: 8.0,
      value: 9.0,
      comfort: 7.6,
      location: 9.1
    },
    logistics: {
      checkIn: '14:00 - 22:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Nearby',
      contact: '+212539842000'
    },
    roomFeatures: ['ac', 'heating'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Port', distance: '200m', time: '3 min walk', icon: 'beach' },
      { label: 'Beach', distance: '400m', time: '5 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: '',
    instagramHandle: '',
    reviewHighlights: {
      solo: 'Perfect budget central stay.',
      couples: 'Good for exploring.',
      families: 'Simple and convenient.',
      business: 'Walk to everything.',
      nomad: 'Affordable long stay.'
    }
  },
  {
    id: 'ah-sleep-17',
    name: 'Hotel Cataleya Al-Hoceima',
    type: 'hotel',
    neighborhood: 'Al Hoceima Center',
    city: 'al_hoceima',
    description: 'A contemporary hotel in the heart of town offering excellent comfort, pristine facilities, and a sauna. It delivers a highly balanced experience with easy walking access to central squares and beaches.',
    pricePerNight: 60,
    lifestyle: 'lean',
    amenities: ['wifi', 'ac', 'sauna', 'breakfast'],
    googleRating: 3.8,
    googleReviewCount: 110,
    tripadvisorRating: 3.5,
    tripadvisorReviewCount: 50,
    bookingRating: 3.7,
    bookingReviewCount: 80,
    hotelguruRating: 3.8,
    hotelguruReviewCount: 10,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'business-friendly'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Don\'t miss the chance to relax in the hotel\'s private sauna after a full day of swimming and walking.',
    vibeTags: ['Sauna', 'Modern', 'Central', 'Value'],
    locationSummary: 'City Center',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.24708,-3.93184',
    address: 'Rue Palestine, Al Hoceima 32000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Contemporary hotel with sauna in town center.',
    neighborhoodOverview: 'Central area close to squares and markets.',
    hiddenFeesNotice: 'None.',
    pros: ['Sauna', 'Clean and modern', 'Good location'],
    cons: ['No pool', 'Basic amenities'],
    trustScores: {
      cleanliness: 8.3,
      safety: 8.2,
      staff: 8.0,
      value: 8.7,
      comfort: 7.9,
      location: 8.9
    },
    logistics: {
      checkIn: '14:00 - 22:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Free',
      contact: '+212539840000'
    },
    roomFeatures: ['ac', 'heating', 'sauna-access'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Center', distance: 'Central', time: '0 min', icon: 'city' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: '',
    instagramHandle: '',
    reviewHighlights: {
      solo: 'Great for relaxing.',
      couples: 'Sauna is a nice touch.',
      families: 'Convenient.',
      business: 'Good facilities.',
      nomad: 'Sauna after work.'
    }
  },
  {
    id: 'ah-sleep-18',
    name: 'Belle Vue Appartement Al Hoceima',
    type: 'apartment',
    neighborhood: 'near Quemado Beach',
    city: 'al_hoceima',
    description: 'A highly-rated beachfront apartment offering travelers a front-row seat to Al Hoceima\'s stunning turquoise waters. The interiors are clean and bright, giving off a cozy seaside getaway feel.',
    pricePerNight: 110,
    lifestyle: 'balanced',
    amenities: ['wifi', 'ac', 'kitchen', 'views'],
    googleRating: 4.5,
    googleReviewCount: 40,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 10,
    bookingRating: 4.6,
    bookingReviewCount: 20,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 5,
    hasPool: false,
    hasBreakfast: false,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Perfect for beach lovers; you are literally steps away from Quemado Beach and the beautiful seaside promenade.',
    vibeTags: ['Beachfront', 'Views', 'Apartment', 'Promenade'],
    locationSummary: 'Beachfront - Quemado',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.24416,-3.927838',
    address: 'Place Mohammed V, Al Hoceima 32000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Beachfront apartment with direct promenade access.',
    neighborhoodOverview: 'Prime beachfront location near promenade.',
    hiddenFeesNotice: 'None.',
    pros: ['Steps from beach', 'Great views', 'Modern'],
    cons: ['No pool', 'Breakfast not included'],
    trustScores: {
      cleanliness: 8.9,
      safety: 8.7,
      staff: 8.4,
      value: 8.5,
      comfort: 8.8,
      location: 9.5
    },
    logistics: {
      checkIn: '15:00 - 21:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Free',
      contact: '+212539842000'
    },
    roomFeatures: ['ac', 'heating', 'sea-view', 'kitchen'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Quemado Beach', distance: '50m', time: '1 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children welcome; apartments ideal for families.',
    officialWebsite: '',
    instagramHandle: '',
    reviewHighlights: {
      solo: 'Beach at your doorstep.',
      couples: 'Romantic sea views.',
      families: 'Good location.',
      business: 'Convenient.',
      nomad: 'Beachside remote work.'
    }
  },
  {
    id: 'ah-sleep-19',
    name: 'Hôtel National',
    type: 'hotel',
    neighborhood: 'Al Hoceima Center',
    city: 'al_hoceima',
    description: 'A reliable budget hotel offering simple, clean accommodations in the heart of Al Hoceima. It provides quick access to central town attractions, restaurants, and local shopping streets.',
    pricePerNight: 35,
    lifestyle: 'lean',
    amenities: ['wifi', 'ac', 'breakfast'],
    googleRating: 3.5,
    googleReviewCount: 230,
    tripadvisorRating: 3.0,
    tripadvisorReviewCount: 100,
    bookingRating: 3.4,
    bookingReviewCount: 150,
    hotelguruRating: 3.5,
    hotelguruReviewCount: 30,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Excellent for travelers on a tight budget who prioritize location, as the main town square is just around the corner.',
    vibeTags: ['Budget', 'Central', 'Simple', 'Value'],
    locationSummary: 'City Center',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.24708,-3.93184',
    address: 'Rue Palestine, Al Hoceima 32000, Morocco',
    paymentMethods: ['cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Long-standing budget hotel in the heart of town.',
    neighborhoodOverview: 'Central square area.',
    hiddenFeesNotice: 'None.',
    pros: ['Very affordable', 'Central location', 'Clean'],
    cons: ['Basic rooms', 'No pool'],
    trustScores: {
      cleanliness: 7.5,
      safety: 8.0,
      staff: 7.8,
      value: 9.2,
      comfort: 7.0,
      location: 9.3
    },
    logistics: {
      checkIn: '14:00 - 22:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Nearby',
      contact: '+212539840000'
    },
    roomFeatures: ['ac', 'heating'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Town Square', distance: '50m', time: '1 min walk', icon: 'city' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: '',
    instagramHandle: '',
    reviewHighlights: {
      solo: 'Best cheap central option.',
      couples: 'Good for exploring.',
      families: 'Simple and affordable.',
      business: 'Walkable.',
      nomad: 'Ultra-budget base.'
    }
  },
  {
    id: 'ah-sleep-20',
    name: 'Hôtel Nexus Budget',
    type: 'hotel',
    neighborhood: 'Al Hoceima Center',
    city: 'al_hoceima',
    description: 'A modern, straightforward budget hotel providing exceptionally clean and efficient accommodations. It features friendly service and serves as a highly economical base for backpackers and solo travelers.',
    pricePerNight: 30,
    lifestyle: 'lean',
    amenities: ['wifi', 'ac', 'breakfast'],
    googleRating: 3.4,
    googleReviewCount: 160,
    tripadvisorRating: 3.0,
    tripadvisorReviewCount: 50,
    bookingRating: 3.2,
    bookingReviewCount: 100,
    hotelguruRating: 3.4,
    hotelguruReviewCount: 20,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Perfect for brief layovers or solo budget travelers who want to explore the Mediterranean coast on a budget.',
    vibeTags: ['Budget', 'Clean', 'Modern', 'Solo'],
    locationSummary: 'City Center',
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.24708,-3.93184',
    address: 'Rue Palestine, Al Hoceima 32000, Morocco',
    paymentMethods: ['cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Clean and efficient budget hotel for travelers.',
    neighborhoodOverview: 'Central budget-friendly area.',
    hiddenFeesNotice: 'None.',
    pros: ['Very low price', 'Clean rooms', 'Friendly'],
    cons: ['Very basic', 'No pool or rooftop'],
    trustScores: {
      cleanliness: 8.0,
      safety: 7.8,
      staff: 7.9,
      value: 9.4,
      comfort: 7.2,
      location: 8.5
    },
    logistics: {
      checkIn: '14:00 - 22:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Nearby',
      contact: '+212539840000'
    },
    roomFeatures: ['ac', 'heating'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Center', distance: 'Central', time: '0 min', icon: 'city' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: '',
    instagramHandle: '',
    reviewHighlights: {
      solo: 'Best ultra-budget option.',
      couples: 'Acceptable for price.',
      families: 'Too basic.',
      business: 'Functional.',
      nomad: 'Cheapest base.'
    }
  }
]