import type { SleepListing } from '../types'

/**
 * SLEEP LISTING DATA TEMPLATE
 * -------------------------------------------------------------
 * {
 *   "id": "city-sleep-XX",
 *   "name": "",
 *   "type": "riad | hotel | villa | hostel | apartment | guesthouse",
 *   "neighborhood": "",
 *   "city": "[city]",
 *   "description": "",
 *   "pricePerNight": 0,
 *   "lifestyle": "lean | balanced | premium",
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2', 'url3']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source
 *   // ═══════════════════════════════════════════════════
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *   bookingRating: [4.x],
 *   bookingReviewCount: [number],
 *   hotelguruRating: [4.x],
 *   hotelguruReviewCount: [number],
 *
 *   // ═══════════════════════════════════════════════════
 *   // BOOLEAN AMENITIES
 *   // ═══════════════════════════════════════════════════
 *   hasPool: true | false,
 *   hasBreakfast: true | false,
 *   hasAC: true | false,
 *   hasHeating: true | false,
 *   hasRooftop: true | false,
 *   hasEnsuite: true | false,
 *   hasRestaurant: true | false,
 *   hasBar: true | false,
 *   hasGym: true | false,
 *   hasElevator: true | false,
 *   hasLaundryService: true | false,
 *   hasRoomService: true | false,
 *   petFriendly: true | false,
 *   isWheelchairAccessible: true | false,
 *   taxesIncluded: true | false,
 *   freeCancellation: true | false,
 *   kidsStayFree: true | false,
 *
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearMosque: true | false,
 *   safetyLevel: 1 | 2 | 3 | 4 | 5,
 *
 *   // ═══════════════════════════════════════════════════
 *   // TRUST SCORES
 *   // ═══════════════════════════════════════════════════
 *   trustScores: {
 *     cleanliness: [1-10],
 *     safety: [1-10],
 *     staff: [1-10],
 *     value: [1-10],
 *     comfort: [1-10],
 *     location: [1-10]
 *   },
 *
 *   amenities: [],
 *   tip: '[Short insider tip]',
 *   vibeTags: [],
 *   locationSummary: '',
 *   availabilityText: '',
 *   googleMapsUrl: '',
 *   address: '',
 *
 *   paymentMethods: ['card', 'cash'],
 *   languagesSpoken: ['Arabic', 'French', 'English'],
 *   groupTypes: [],
 *
 *   customStory: '',
 *   neighborhoodOverview: '',
 *   hiddenFeesNotice: '',
 *   pros: [],
 *   cons: [],
 *
 *   logistics: {
 *     checkIn: '',
 *     checkOut: '',
 *     luggageStorage: '',
 *     parking: '',
 *     contact: ''
 *   },
 *
 *   roomFeatures: [],
 *   roomTypes: [
 *   ],
 *
 *   neighborhoodDistances: [],
 *   cancellationPolicy: '',
 *   childPolicy: '',
 *   officialWebsite: '',
 *   instagramHandle: '',
 *   // googlePlaceId: "PLACE_ID_HERE",
 *
 *   reviewHighlights: {
 *     solo: '',
 *     couples: '',
 *     families: '',
 *     business: '',
 *     nomad: ''
 *   }
 * }
 */

export const asilahSleep: SleepListing[] = [
  {
    id: 'as-sleep-1',
    city: 'asilah',
    name: 'La Fiermontina Océan',
    type: 'hotel',
    neighborhood: 'Sahel Chamali (Near Asilah)',
    description: 'A luxurious eco-resort perched on wild coastal clifftops and sweeping dunes south of Asilah. This tranquil sanctuary merges minimalist Italian design with warm Moroccan hospitality and dramatic Atlantic views.',
    pricePerNight: 380,
    lifestyle: 'premium',
    amenities: ['wifi', 'pool', 'spa', 'restaurant', 'beach', 'breakfast'],
    googleRating: 4.8,
    googleReviewCount: 68,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 68,
    bookingRating: 4.8,
    bookingReviewCount: 68,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 68,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "countryside",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Spend a quiet afternoon in the clifftop hammam, which offers a deep therapeutic experience overlooking the Atlantic.',
    vibeTags: ['Eco-Luxury', 'Secluded', 'Italian-Style', 'Oceanfront'],
    locationSummary: "Wild Atlantic Coast - Khemis Sahel",
    availabilityText: 'Check dates for availability',
    googleMapsUrl: 'https://www.google.com/maps/place/35.405567,-6.112458',
    address: 'Sahel Chamali, Asilah, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Italian', 'Spanish'],
    customStory: 'Designed by Italian owner Giacomo Fiermontino, this eco-retreat was built to preserve the wild beauty of the Sahel Chamali cliffs while offering uncompromised luxury.',
    neighborhoodOverview: 'Secluded and wild, the Sahel Chamali area offers untouched coastal beauty south of Asilah.',
    hiddenFeesNotice: 'Resort fees may apply.',
    pros: ['Stunning infinity pool', 'Breathtaking ocean views', 'Exceptional privacy'],
    cons: ['Remote location requires transport', 'Premium price point'],
    trustScores: {
      cleanliness: 9.7,
      safety: 9.8,
      staff: 9.5,
      value: 8.6,
      comfort: 9.6,
      location: 9.9
    },
    logistics: {
      checkIn: '15:00 - 23:00',
      checkOut: 'Before 12:00',
      luggageStorage: 'Free',
      parking: 'Free secure on-site',
      contact: '+212539414019'
    },
    roomFeatures: ['ac', 'heating', 'infinity-pool', 'ocean-view', 'minibar'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Private Beach', distance: '100m', time: '2 min walk', icon: 'beach' },
      { label: 'Asilah Center', distance: '12km', time: '20 min drive', icon: 'city' }
    ],
    cancellationPolicy: 'Free cancellation up to 5 days before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://lafiermontinaocean.com',
    instagramHandle: '@lafiermontinaocean',
    reviewHighlights: {
      solo: 'A meditative escape with unmatched ocean views.',
      couples: 'The ultimate romantic hideaway in Morocco.',
      families: 'Great for older families seeking quiet luxury.',
      business: 'Excellent retreat venue with reliable satellite Wi-Fi.',
      nomad: 'High-speed satellite internet for remote work.'
    },
    coordinates: {
      lat: 35.443279,
      lng: -6.051271
    },
    tags: ["family-favorite"]
  },
  {
    id: 'as-sleep-2',
    city: 'asilah',
    name: 'PUERTO MARINA ASILAH',
    type: 'apartment',
    neighborhood: 'Corniche',
    description: 'A modern beachfront residence overlooking the ocean and the town\'s seaside promenade. It offers spacious apartments decorated with bright, contemporary coastal touches perfect for groups and families.',
    pricePerNight: 120,
    lifestyle: 'balanced',
    amenities: ['wifi', 'ac', 'kitchen', 'beach'],
    googleRating: 4.7,
    googleReviewCount: 1147,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 500,
    bookingRating: 4.6,
    bookingReviewCount: 800,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 100,
    hasPool: false,
    hasBreakfast: false,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Book an apartment with a sea view to enjoy the sunset directly from your private balcony.',
    vibeTags: ['Coastal', 'Modern', 'Family-Friendly', 'Convenient'],
    locationSummary: "Asilah Marina Waterfront",
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.467432,-6.031245',
    address: 'Avenue Moulay Hassan Ben Mehdi, Asilah 90050, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'A landmark modern residence in Asilah, Puerto Marina was built to bridge the gap between traditional medina stays and modern beachfront living.',
    neighborhoodOverview: 'Beachfront corniche area with promenade access.',
    hiddenFeesNotice: 'None.',
    pros: ['Direct beach access', 'Spacious for families', 'Very clean facilities'],
    cons: ['Can be noisy in high season', 'Wait times for elevators'],
    trustScores: {
      cleanliness: 9.1,
      safety: 9.3,
      staff: 8.7,
      value: 9.0,
      comfort: 8.8,
      location: 9.5
    },
    logistics: {
      checkIn: '14:00 - 22:00',
      checkOut: 'Before 12:00',
      luggageStorage: 'Free',
      parking: 'Available on-site',
      contact: '+212539414414'
    },
    roomFeatures: ['ac', 'heating', 'sea-view', 'kitchen', 'balcony'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Corniche Beach', distance: 'Direct', time: '1 min walk', icon: 'beach' },
      { label: 'Medina Entrance', distance: '800m', time: '10 min walk', icon: 'city' }
    ],
    cancellationPolicy: 'Free cancellation up to 24h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://www.booking.com/hotel/ma/puerto-marina-asilah.en-gb.html',
    instagramHandle: '@puertomarinaasilah',
    reviewHighlights: {
      solo: 'Safe and modern base for long stays.',
      couples: 'Great balcony views for sunset dinners.',
      families: 'The kitchen facilities are a lifesaver with kids.',
      business: 'Good location for local meetings; fast internet.',
      nomad: 'Great for long-term remote stays.'
    },
    coordinates: {
      lat: 35.443279,
      lng: -6.051271
    },
    tags: ["family-favorite"]
  },
  {
    id: 'as-sleep-3',
    city: 'asilah',
    name: 'Riad Oasis d\'Asilah',
    type: 'riad',
    neighborhood: 'Medina (Old Town)',
    description: 'A stunning boutique riad showcasing an exceptional blend of Andalusian elegance and traditional Moroccan architecture. Vibrant plants and a beautiful courtyard pool make the central patio feel like a secret coastal sanctuary.',
    pricePerNight: 110,
    lifestyle: 'balanced',
    amenities: ['wifi', 'pool', 'ac', 'spa', 'breakfast', 'restaurant'],
    googleRating: 4.6,
    googleReviewCount: 558,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 200,
    bookingRating: 4.7,
    bookingReviewCount: 300,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 50,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Head up to the rooftop terrace for breakfast to enjoy a refreshing morning breeze and sweeping sea views.',
    vibeTags: ['Authentic', 'Green', 'Peaceful', 'Boutique'],
    locationSummary: "Asilah Historic Medina",
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.464523,-6.034567',
    address: '7 Rue Ahmed El Mansour, Asilah 90050, Morocco',
    paymentMethods: ['cash', 'card'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Riad Oasis was a former merchant family home, meticulously restored by local artisans using traditional lime-plaster and hand-cut tiles.',
    neighborhoodOverview: 'Central medina location near the ramparts.',
    hiddenFeesNotice: 'None.',
    pros: ['Stunning courtyard pool', 'Exceptional hospitality', 'Lush interior garden'],
    cons: ['Medina location means a bit of walking', 'Pool is small for laps'],
    trustScores: {
      cleanliness: 9.4,
      safety: 9.2,
      staff: 9.6,
      value: 9.1,
      comfort: 8.9,
      location: 9.8
    },
    logistics: {
      checkIn: '14:00 - 21:00',
      checkOut: 'Before 11:30',
      luggageStorage: 'Free',
      parking: 'Nearby public (Gate Bab Kasbah)',
      contact: '+212666414111'
    },
    roomFeatures: ['ac', 'heating', 'courtyard-view', 'traditional-decor'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Ramparts', distance: '200m', time: '3 min walk', icon: 'beach' },
      { label: 'Grand Mosque', distance: '150m', time: '2 min walk', icon: 'city' }
    ],
    cancellationPolicy: 'Free cancellation up to 48h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://riadoasis-asilah.com',
    instagramHandle: '@riadoasisasilah',
    reviewHighlights: {
      solo: 'Extremely welcoming staff made me feel at home.',
      couples: 'The most romantic rooftop in Asilah.',
      families: 'Quiet courtyard is great for kids to relax.',
      business: 'A peaceful retreat after a long day of travel.',
      nomad: 'Good meditaion-style workspace.'
    },
    coordinates: {
      lat: 35.465042,
      lng: -6.038228
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: 'as-sleep-4',
    city: 'asilah',
    name: 'riad casa bahia asilah',
    type: 'riad',
    neighborhood: 'Medina (Old Town)',
    description: 'A beautifully restored, classic riad offering a peaceful oasis right in the heart of the old medina. Combining traditional courtyard masonry with modern white-and-blue accents, the space feels bright, airy, and deeply relaxing.',
    pricePerNight: 90,
    lifestyle: 'balanced',
    amenities: ['wifi', 'ac', 'breakfast', 'restaurant'],
    googleRating: 4.6,
    googleReviewCount: 743,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 300,
    bookingRating: 4.5,
    bookingReviewCount: 400,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 80,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Dine at their newly opened onsite restaurant, which serves exceptional, freshly prepared local seafood tagines.',
    vibeTags: ['White-and-Blue', 'Breezy', 'Artistic', 'Central'],
    locationSummary: "Asilah Historic Medina",
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.465123,-6.035123',
    address: '8 Rue Tijara, Asilah 90050, Morocco',
    paymentMethods: ['cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Casa Bahia celebrates the iconic blue and white colors of Asilah, often hosting local artists who have left their mark on the interior decor.',
    neighborhoodOverview: 'Central medina location near the gates.',
    hiddenFeesNotice: 'None.',
    pros: ['Artistic atmosphere', 'Superb seafood tagines', 'Centrally located'],
    cons: ['No pool', 'Card payments often unavailable'],
    trustScores: {
      cleanliness: 9.2,
      safety: 9.0,
      staff: 9.3,
      value: 8.8,
      comfort: 8.5,
      location: 9.7
    },
    logistics: {
      checkIn: '13:00 - 22:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Nearby public (Bab el-Houmar)',
      contact: '+212539414000'
    },
    roomFeatures: ['ac', 'heating', 'courtyard-view'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Medina Gate', distance: '100m', time: '1 min walk', icon: 'city' }
    ],
    cancellationPolicy: 'Free cancellation up to 48h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://riadcasabahia.com',
    instagramHandle: '@riadcasabahia',
    reviewHighlights: {
      solo: 'Perfect spot for solo travelers to meet fellow creatives.',
      couples: 'The blue and white decor is so refreshing and romantic.',
      families: 'Cozy and safe for a small family stay.',
      business: 'Good Wi-Fi for working on the terrace.',
      nomad: 'Artistic vibe for creative work.'
    },
    coordinates: {
      lat: 35.763453,
      lng: -5.836498
    },
    tags: ["family-favorite"]
  },
  {
    id: 'as-sleep-5',
    city: 'asilah',
    name: 'Dar Manara',
    type: 'riad',
    neighborhood: 'Medina (Old Town)',
    description: 'A gorgeous and elegant riad inspired by classic Arab-Andalusian architecture in a silent street of the old medina. Hand-carved materials and delicate fountain sounds create an exceptionally serene and artistic atmosphere.',
    pricePerNight: 85,
    lifestyle: 'balanced',
    amenities: ['wifi', 'ac', 'breakfast'],
    googleRating: 4.6,
    googleReviewCount: 163,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 100,
    bookingRating: 4.7,
    bookingReviewCount: 120,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 30,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'The rooftop features cozy Moroccan haimas (nomadic tents); spend your evening there over a glass of mint tea.',
    vibeTags: ['Architectural', 'Serene', 'Boutique', 'Chic'],
    locationSummary: "Asilah Historic Medina",
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.464890,-6.034234',
    address: 'Rue de la Kasbah, Asilah 90050, Morocco',
    paymentMethods: ['cash', 'card'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Italian', 'Spanish'],
    customStory: 'Dar Manara was established by an architect-traveler who wanted to create a space that felt like an art gallery you could live in.',
    neighborhoodOverview: 'Quiet medina street near the Kasbah.',
    hiddenFeesNotice: 'None.',
    pros: ['Exquisite architectural details', 'Tranquil atmosphere', 'Highly attentive service'],
    cons: ['Small number of rooms; book early', 'Slightly higher price for size'],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.4,
      staff: 9.7,
      value: 8.9,
      comfort: 9.2,
      location: 9.6
    },
    logistics: {
      checkIn: '14:00 - 21:30',
      checkOut: 'Before 11:30',
      luggageStorage: 'Free',
      parking: 'Nearby public (Bab el-Bahr)',
      contact: '+212539414114'
    },
    roomFeatures: ['ac', 'heating', 'traditional-decor'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Port', distance: '300m', time: '4 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 48h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://asilah-darmanara.com',
    instagramHandle: '@darmanara',
    reviewHighlights: {
      solo: 'Absolute silence in the middle of the medina; perfect for writing.',
      couples: 'The fountain in the courtyard is so relaxing at night.',
      families: 'Great for a small group of adults.',
      business: 'Boutique luxury with good connection speeds.',
      nomad: 'Perfect for focused writing work.'
    },
    coordinates: {
      lat: 35.464288,
      lng: -6.039951
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: 'as-sleep-6',
    city: 'asilah',
    name: 'Asilah 32',
    type: 'apartment',
    neighborhood: 'New Town',
    description: 'A sleek, contemporary seafront aparthotel situated on the coastal promenade just steps from the historic old town. Offering a bright beachside escape, its modern rooms feature subtle Moroccan accents and private kitchenettes.',
    pricePerNight: 160,
    lifestyle: 'balanced',
    amenities: ['wifi', 'ac', 'kitchen', 'breakfast', 'restaurant', 'bar'],
    googleRating: 4.5,
    googleReviewCount: 857,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 300,
    bookingRating: 4.4,
    bookingReviewCount: 500,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 100,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Request an upper-floor apartment with a private balcony to enjoy uninterrupted views of the sunset over the ocean.',
    vibeTags: ['Modern', 'Sleek', 'Ocean-View', 'Apartment'],
    locationSummary: "Asilah Historic Medina",
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.468123,-6.030567',
    address: '32 Avenue Moulay Hassan Ben Mehdi, Asilah 90050, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Asilah 32 was designed to cater to a new generation of travelers who value minimalist aesthetics and the independence of a serviced apartment.',
    neighborhoodOverview: 'Prime seafront promenade location near the medina.',
    hiddenFeesNotice: 'None.',
    pros: ['Modern kitchenettes', 'Prime seafront location', 'Clean minimalist design'],
    cons: ['Breakfast options are limited nearby', 'Parking is on the street'],
    trustScores: {
      cleanliness: 8.9,
      safety: 9.1,
      staff: 8.5,
      value: 8.7,
      comfort: 9.0,
      location: 9.6
    },
    logistics: {
      checkIn: '15:00 - 21:00',
      checkOut: 'Before 11:30',
      luggageStorage: 'Free',
      parking: 'On-street',
      contact: '+212539414432'
    },
    roomFeatures: ['ac', 'heating', 'sea-view', 'kitchen', 'balcony'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Promenade', distance: 'Direct', time: '1 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 48h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://asilah32.com',
    instagramHandle: '@asilah32',
    reviewHighlights: {
      solo: 'Clean and safe with a great view.',
      couples: 'The kitchenettes allowed us to have private breakfasts on the balcony.',
      families: 'A bit tight for large families but great location.',
      business: 'Good workspace and stable fiber internet.',
      nomad: 'Kitchen + sea view = perfect long stay.'
    },
    coordinates: {
      lat: 35.461928,
      lng: -6.036545
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: 'as-sleep-7',
    city: 'asilah',
    name: 'Hotel Al Alba Hammam & Restaurant',
    type: 'hotel',
    neighborhood: 'New Town',
    description: 'A highly charming boutique hotel located only a brief walk from the sandy shores of Asilah Beach. Its elegant architecture combines clean Arabic lines with soothing white-and-blue coastal tones and traditional brick details.',
    pricePerNight: 95,
    lifestyle: 'balanced',
    amenities: ['wifi', 'ac', 'spa', 'breakfast', 'restaurant', 'bar', 'hammam'],
    googleRating: 4.5,
    googleReviewCount: 620,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 250,
    bookingRating: 4.4,
    bookingReviewCount: 350,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 90,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Book their traditional hammam beldi experience in advance to unwind after a day of exploring the medina.',
    vibeTags: ['Boutique', 'Charming', 'Hammam', 'Gourmet'],
    locationSummary: "Asilah Historic Medina",
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.467890,-6.028900',
    address: 'Lot. Nakhla 1, Asilah 90050, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Named after the "Dawn," Al Alba was founded to offer a refined hybrid between a traditional riad and a modern boutique hotel.',
    neighborhoodOverview: 'New town area near the beach and medina.',
    hiddenFeesNotice: 'None.',
    pros: ['Excellent onsite seafood restaurant', 'Beautiful garden', 'Atmospheric hammam'],
    cons: ['Slightly further walk to medina center', 'Street facing rooms can have noise'],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.0,
      staff: 9.5,
      value: 8.8,
      comfort: 9.1,
      location: 8.7
    },
    logistics: {
      checkIn: '14:00 - 22:00',
      checkOut: 'Before 12:00',
      luggageStorage: 'Free',
      parking: 'Private video-monitored',
      contact: '+212539414000'
    },
    roomFeatures: ['ac', 'heating', 'garden-view'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Asilah Beach', distance: '300m', time: '5 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 48h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://hotelalalba.com',
    instagramHandle: '@hotelalalba',
    reviewHighlights: {
      solo: 'The restaurant is fantastic; I didn\'t need to go anywhere else.',
      couples: 'The garden at night is so peaceful and well-lit.',
      families: 'The triple rooms are spacious and well-maintained.',
      business: 'Quiet enough for calls and very helpful staff.',
      nomad: 'Good restaurant and workspace combo.'
    },
    coordinates: {
      lat: 35.470971,
      lng: -6.028359
    },
    tags: ["family-favorite"]
  },
  {
    id: 'as-sleep-8',
    city: 'asilah',
    name: 'Riad Assilah',
    type: 'riad',
    neighborhood: 'Medina (Old Town)',
    description: 'An incredibly popular and authentic medina townhouse combining classic whitewashed walls with colorful zellij tiles. Its warm, social atmosphere and cozy central patio offer a perfect coastal retreat for couples.',
    pricePerNight: 67,
    lifestyle: 'lean',
    amenities: ['wifi', 'ac', 'breakfast'],
    googleRating: 4.5,
    googleReviewCount: 237,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 100,
    bookingRating: 4.4,
    bookingReviewCount: 120,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 40,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'The helpful host, Achraf, is exceptionally knowledgeable; ask him for his favorite secret restaurants in town.',
    vibeTags: ['Warm', 'Authentic', 'Budget-Friendly', 'Hospitable'],
    locationSummary: "Asilah Historic Medina",
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.464123,-6.035567',
    address: '8 Rue Tijara, Asilah 90050, Morocco',
    paymentMethods: ['cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Riad Assilah is a labor of love by its local owners, focuses on the "real" Asilah experience with family-style hospitality.',
    neighborhoodOverview: 'Central medina near the main alleyways.',
    hiddenFeesNotice: 'None.',
    pros: ['Very affordable', 'Authentic medina experience', 'Host is extremely helpful'],
    cons: ['Rooms are simpler than boutique hotels', 'No AC in some units'],
    trustScores: {
      cleanliness: 8.5,
      safety: 8.8,
      staff: 9.8,
      value: 9.6,
      comfort: 8.2,
      location: 9.7
    },
    logistics: {
      checkIn: '13:00 - 21:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Nearby public',
      contact: '+212666000000'
    },
    roomFeatures: ['ac', 'heating', 'traditional-decor'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'North Gate', distance: '150m', time: '2 min walk', icon: 'city' }
    ],
    cancellationPolicy: 'Free cancellation up to 48h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://riadassilah.org',
    instagramHandle: '@riadassilah',
    reviewHighlights: {
      solo: 'Achraf went out of his way to help me with everything.',
      couples: 'The rooftop terrace is basic but has a lovely community feel.',
      families: 'A bit traditional but the kids loved exploring the medina alleys.',
      business: 'Decent Wi-Fi in the common area.',
      nomad: 'Budget-friendly long stay base.'
    },
    coordinates: {
      lat: 35.465042,
      lng: -6.038228
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: 'as-sleep-9',
    city: 'asilah',
    name: 'Dar Dahbia',
    type: 'guesthouse',
    neighborhood: 'New Town',
    description: 'A beautifully appointed town residence that seamlessly blends home comfort with artistic Moroccan design. Guests are welcomed into highly aesthetic apartments decorated with hand-embroidered linens and local crafts.',
    pricePerNight: 60,
    lifestyle: 'lean',
    amenities: ['wifi', 'ac', 'kitchen'],
    googleRating: 4.5,
    googleReviewCount: 235,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 100,
    bookingRating: 4.4,
    bookingReviewCount: 120,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 40,
    hasPool: false,
    hasBreakfast: false,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ['solo', 'couple', 'family'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Use the fully equipped kitchen to cook fresh fish purchased from the nearby local harbor market.',
    vibeTags: ['Artistic', 'Homely', 'Seaview', 'Creative'],
    locationSummary: "Asilah Historic Medina",
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.467123,-6.029876',
    address: 'Rue de la Kasbah, Asilah 90050, Morocco',
    paymentMethods: ['cash', 'card'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Dar Dahbia was once an artist\'s residence, and its thick stone walls still carry the quiet inspiration of the Atlantic.',
    neighborhoodOverview: 'Quiet residential area near the medina.',
    hiddenFeesNotice: 'None.',
    pros: ['Excellent kitchen facilities', 'Quiet neighborhood', 'Beautiful handmade textiles'],
    cons: ['Slightly away from medina center', 'Fewer staff than a hotel'],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.2,
      staff: 9.0,
      value: 9.4,
      comfort: 9.1,
      location: 8.8
    },
    logistics: {
      checkIn: '14:00 - 22:00',
      checkOut: 'Before 12:00',
      luggageStorage: 'Free',
      parking: 'Nearby public',
      contact: '+212539414111'
    },
    roomFeatures: ['ac', 'heating', 'kitchen', 'sea-view'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Harbor Market', distance: '600m', time: '8 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 48h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://www.booking.com/hotel/ma/dar-dahbia.en-gb.html',
    instagramHandle: '@dardahbia',
    reviewHighlights: {
      solo: 'Extremely peaceful and great for a creative retreat.',
      couples: 'We loved buying local fish and cooking our own dinner.',
      families: 'The washing machine was a huge help.',
      business: 'Quiet and comfortable with good internet.',
      nomad: 'Kitchen makes long stays easy.'
    },
    coordinates: {
      lat: 35.464288,
      lng: -6.039951
    },
    tags: ["family-favorite"]
  },
  {
    id: 'as-sleep-10',
    city: 'asilah',
    name: 'Riad Aicha',
    type: 'riad',
    neighborhood: 'Medina (Old Town)',
    description: 'A highly welcoming, beachfront-facing riad nestled deep within the peaceful stone alleys of the old medina. Its simple, cozy rooms are decorated with hand-woven rugs and bright, cheerful coastal textiles.',
    pricePerNight: 55,
    lifestyle: 'lean',
    amenities: ['wifi', 'ac', 'breakfast'],
    googleRating: 4.5,
    googleReviewCount: 629,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 250,
    bookingRating: 4.4,
    bookingReviewCount: 350,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 90,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Wake up early to catch a breathtaking sunrise over the ocean directly from the shared rooftop terrace.',
    vibeTags: ['Vibrant', 'Social', 'Medina-Core', 'Simple'],
    locationSummary: "Asilah Historic Medina",
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.464567,-6.035890',
    address: 'Rue Ahmed El Mansour, Asilah 90050, Morocco',
    paymentMethods: ['cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Riad Aicha is known for its bright colors and its legendary breakfast served on the rooftop by the owners family.',
    neighborhoodOverview: 'Medina location near the rampart walls.',
    hiddenFeesNotice: 'None.',
    pros: ['Incredible medina location', 'Superb rooftop views', 'Very welcoming atmosphere'],
    cons: ['Simple furnishings', 'Can be noisy due to medina calls'],
    trustScores: {
      cleanliness: 8.2,
      safety: 8.5,
      staff: 9.4,
      value: 9.1,
      comfort: 8.0,
      location: 9.8
    },
    logistics: {
      checkIn: '13:00 - 21:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'None (Medina)',
      contact: '+212539414222'
    },
    roomFeatures: ['ac', 'heating', 'rooftop-access'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Rampart Walls', distance: '50m', time: '1 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 48h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://www.booking.com/hotel/ma/riad-aicha-asilah.en-gb.html',
    instagramHandle: '@riadaichaasilah',
    reviewHighlights: {
      solo: 'Authentic and very friendly.',
      couples: 'The sunset from the roof is unforgettable.',
      families: 'Great for a budget family adventure.',
      business: 'Okay for a night, but quite traditional.',
      nomad: 'Budget base for exploring.'
    },
    coordinates: {
      lat: 35.464584,
      lng: -6.039407
    },
    tags: ["family-favorite"]
  },
  {
    id: 'as-sleep-11',
    city: 'asilah',
    name: 'Maison d\'hotes Berbari',
    type: 'guesthouse',
    neighborhood: 'Sahel Chamali (Near Asilah)',
    description: 'A highly unique, eco-friendly rural guest house nestled in the countryside just outside of Asilah. Constructed of natural clay, it offers a peaceful farm setting complete with organic dining and a deeply grounding vibe.',
    pricePerNight: 94,
    lifestyle: 'balanced',
    amenities: ['wifi', 'breakfast', 'restaurant', 'parking'],
    googleRating: 4.5,
    googleReviewCount: 270,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 100,
    bookingRating: 4.7,
    bookingReviewCount: 150,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 50,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ['solo', 'couple', 'family', 'seniors'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'This place is perfect if you want to unwind in nature; it\'s an eco-friendly stay with farm animals just 5 km from the beach.',
    vibeTags: ['Eco-Friendly', 'Rural', 'Sustainable', 'Peaceful'],
    locationSummary: "Asilah Historic Medina",
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.421234,-6.012345',
    address: 'Douar Berbari, Asilah 90050, Morocco',
    paymentMethods: ['cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Built from local earth and straw, Berbari was one of the first eco-guesthouses in the region, promoting a slow-living philosophy.',
    neighborhoodOverview: 'Rural area with farm setting, 5km from coast.',
    hiddenFeesNotice: 'None.',
    pros: ['Truly unique ecological design', 'Incredible organic food', 'Total peace and quiet'],
    cons: ['Needs a car or taxi to reach town', 'No air conditioning (natural cooling only)'],
    trustScores: {
      cleanliness: 9.1,
      safety: 9.3,
      staff: 9.2,
      value: 8.8,
      comfort: 8.4,
      location: 8.0
    },
    logistics: {
      checkIn: '14:00 - 20:00',
      checkOut: 'Before 11:30',
      luggageStorage: 'Free',
      parking: 'Free on-site',
      contact: '+212539414011'
    },
    roomFeatures: ['heating', 'eco-friendly', 'garden-view'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Countryside', distance: 'Direct', time: '0 min', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 48h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://berbari.com',
    instagramHandle: '@berbari_asilah',
    reviewHighlights: {
      solo: 'A perfect place to disconnect from everything.',
      couples: 'Romantic and very grounded. The food was the highlight.',
      families: 'Great for kids to see the farm animals.',
      business: 'Not recommended if you need high-speed internet continuously.',
      nomad: 'Digital detox paradise.'
    },
    coordinates: {
      lat: 35.415891,
      lng: -6.008196
    },
    tags: ["family-favorite"]
  },
  {
    id: 'as-sleep-12',
    city: 'asilah',
    name: 'Dar el Maq - Atlantic view & Sauna',
    type: 'guesthouse',
    neighborhood: 'Medina (Old Town)',
    description: 'An exquisite, luxury townhouse boasting premium materials, warm clay tones, and an exclusive seaside deck. Its artistic design is complemented by spectacular ocean views and an in-house relaxation sauna.',
    pricePerNight: 250,
    lifestyle: 'premium',
    amenities: ['wifi', 'ac', 'sauna', 'kitchen'],
    googleRating: 4.5,
    googleReviewCount: 96,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 50,
    bookingRating: 4.6,
    bookingReviewCount: 80,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 20,
    hasPool: false,
    hasBreakfast: false,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'The property is managed beautifully; reach out to the host to coordinate custom grocery drops before you arrive.',
    vibeTags: ['Luxury', 'Wellness', 'Panoramic', 'Medina-Chic'],
    locationSummary: "Asilah Historic Medina",
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.464890,-6.035567',
    address: 'Rue de la Kasbah, Asilah 90050, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Dar el Maq is a premium private residence opened to travelers who seek the highest level of craftsmanship in the heart of the medina.',
    neighborhoodOverview: 'Medina edge near the sea walls.',
    hiddenFeesNotice: 'None.',
    pros: ['Private Finnish sauna', 'Exceptional Atlantic views', 'High-end Tadelakt finishes'],
    cons: ['Waitlist can be long', 'Steep stairs in the house'],
    trustScores: {
      cleanliness: 9.7,
      safety: 9.5,
      staff: 9.6,
      value: 8.4,
      comfort: 9.5,
      location: 9.9
    },
    logistics: {
      checkIn: '15:00 - 20:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Nearby public (Gate Bab Kasbah)',
      contact: '+212539414112'
    },
    roomFeatures: ['ac', 'heating', 'sea-view', 'sauna', 'tadelakt-finish'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Sea Walls', distance: 'Direct', time: '1 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 48h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://darelmaq.com',
    instagramHandle: '@darelmaq_asilah',
    reviewHighlights: {
      solo: 'Total luxury; the sauna after a beach day is divine.',
      couples: 'The most stunning sunset view I have ever seen from a private deck.',
      families: 'Great for a small high-end family retreat.',
      business: 'Excellent fiber connection and very quiet.',
      nomad: 'Luxury workspace with a view.'
    },
    coordinates: {
      lat: 35.466311,
      lng: -6.037083
    },
    tags: ["family-favorite"]
  },
  {
    id: 'as-sleep-13',
    city: 'asilah',
    name: 'Villa Fares Assilah',
    type: 'villa',
    neighborhood: 'New Town',
    description: 'An ultra-exclusive, modern private villa featuring a stunning indoor pool and beautiful manicured gardens. This luxurious coastal retreat offers high-end family living with traditional Moroccan hammam access.',
    pricePerNight: 310,
    lifestyle: 'premium',
    amenities: ['wifi', 'pool', 'ac', 'hammam', 'garden'],
    googleRating: 4.5,
    googleReviewCount: 12,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 10,
    bookingRating: 4.6,
    bookingReviewCount: 20,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 5,
    hasPool: true,
    hasBreakfast: false,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['family', 'friends'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Ask the helpful host, Abderahmane, to set up the outdoor barbecue and provide charcoal in advance.',
    vibeTags: ['Palatial', 'Private', 'Indoor-Pool', 'Manicured'],
    locationSummary: "Asilah Historic Medina",
    availabilityText: 'Check dates',
    googleMapsUrl: 'https://www.google.com/maps/place/35.462345,-6.028900',
    address: 'Rue de la Kasbah, Asilah 90050, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Villa Fares was designed as a modern family oasis, focusing on indoor-outdoor living with its centerpiece indoor pool.',
    neighborhoodOverview: 'Residential area a short drive from medina.',
    hiddenFeesNotice: 'None.',
    pros: ['Private indoor pool', 'Beautiful gardens', 'Very safe and private'],
    cons: ['Requires a short drive to medina', 'Minimum stay often required'],
    trustScores: {
      cleanliness: 9.5,
      safety: 9.7,
      staff: 9.2,
      value: 8.7,
      comfort: 9.6,
      location: 8.2
    },
    logistics: {
      checkIn: '14:00 - 22:00',
      checkOut: 'Before 12:00',
      luggageStorage: 'Free',
      parking: 'Free private on-site',
      contact: '+212539414113'
    },
    roomFeatures: ['ac', 'heating', 'indoor-pool', 'garden-view'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Beach', distance: '1.2km', time: '15 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 7 days before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://www.booking.com/hotel/ma/villa-fares-assilah.en-gb.html',
    instagramHandle: '@villafaresasilah',
    reviewHighlights: {
      solo: 'Too big for a solo stay, but incredible service.',
      couples: 'Perfect for an ultra-private romantic week.',
      families: 'The kids lived in the indoor pool.',
      business: 'Great for a small team offsite.',
      nomad: 'Best for group retreats.'
    },
    coordinates: {
      lat: 35.465909,
      lng: -6.037641
    },
    tags: ["family-favorite"]
  },
  {
    id: 'as-sleep-14',
    city: 'asilah',
    name: 'Hill Valley Asilah - Luxury Living & Boutique Hotel',
    type: 'hotel',
    neighborhood: 'Sahel Chamali (Near Asilah)',
    description: 'A magnificent boutique hotel set in a quiet, elevated valley offering sweeping views of the Atlantic Ocean. Its premium design pairs natural materials with high-end comforts and a beautiful outdoor infinity pool.',
    pricePerNight: 260,
    lifestyle: 'premium',
    amenities: ['wifi', 'pool', 'ac', 'breakfast', 'restaurant', 'bar'],
    googleRating: 4.4,
    googleReviewCount: 21,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 15,
    bookingRating: 4.6,
    bookingReviewCount: 30,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 10,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family', 'seniors'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Perfect place for complete digital disconnection; the location is serene, quiet, and surrounded by untouched coastal nature.',
    vibeTags: ['Boutique', 'Panoramic', 'Nature', 'Infinity-Pool'],
    locationSummary: "Asilah Historic Medina",
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.408900,-6.102345',
    address: 'Douar El Hanchat, Asilah 90050, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Hill Valley was built to showcase the rolling hills of Asilah that meet the Atlantic, offering a boutique experience outside the city noise.',
    neighborhoodOverview: 'Quiet valley location near the coast.',
    hiddenFeesNotice: 'None.',
    pros: ['Stunning infinity pool', 'Quiet valley location', 'Excellent organic local food'],
    cons: ['Needs a car/taxi for town visits', 'Wi-Fi can be spotty in rooms'],
    trustScores: {
      cleanliness: 9.4,
      safety: 9.6,
      staff: 9.3,
      value: 8.5,
      comfort: 9.1,
      location: 7.8
    },
    logistics: {
      checkIn: '15:00 - 21:00',
      checkOut: 'Before 12:00',
      luggageStorage: 'Free',
      parking: 'Free secure on-site',
      contact: '+212539414114'
    },
    roomFeatures: ['ac', 'heating', 'infinity-pool', 'valley-view'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Wild Coast', distance: '500m', time: '10 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 48h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://www.booking.com/hotel/ma/hill-valley-asilah.en-gb.html',
    instagramHandle: '@hillvalleyasilah',
    reviewHighlights: {
      solo: 'The ultimate spot to clear your head.',
      couples: 'The pool views at sunset are magical.',
      families: 'Great for a quiet family getaway.',
      business: 'Good for deep work retreats.',
      nomad: 'Nature-focused remote work.'
    },
    coordinates: {
      lat: 35.408325,
      lng: -6.020334
    },
    tags: ["family-favorite"]
  },
  {
    id: 'as-sleep-15',
    city: 'asilah',
    name: 'Asilah Luxury - Sea view & Swimming Pools',
    type: 'apartment',
    neighborhood: 'Widadiya Asilah',
    description: 'An exceptionally stylish and modern luxury residence featuring an infinity pool and direct sea views. The spacious, upscale apartments are beautifully decorated to provide a high-end coastal vacation.',
    pricePerNight: 255,
    lifestyle: 'premium',
    amenities: ['wifi', 'pool', 'ac', 'kitchen'],
    googleRating: 4.4,
    googleReviewCount: 16,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 10,
    bookingRating: 4.6,
    bookingReviewCount: 20,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 5,
    hasPool: true,
    hasBreakfast: false,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Take advantage of their paid walking tours and local hiking excursions coordinated by the host.',
    vibeTags: ['Modern-Luxury', 'Infinity-Pool', 'Sporty', 'Upscale'],
    locationSummary: "Asilah Historic Medina",
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.467890,-6.028900',
    address: 'Lotissement Widadiya, Asilah 90050, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Asilah Luxury provides a high-end alternative to medina riads, with a focus on sports, swimming, and modern security.',
    neighborhoodOverview: 'Secure gated community near the beach.',
    hiddenFeesNotice: 'None.',
    pros: ['Onsite tennis courts', 'Beautiful infinity pool', 'Highly secure gated community'],
    cons: ['Can feel a bit less "authentic" than a riad', 'Extra charges for some facilities'],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.8,
      staff: 8.9,
      value: 8.7,
      comfort: 9.4,
      location: 9.1
    },
    logistics: {
      checkIn: '14:00 - 22:00',
      checkOut: 'Before 11:30',
      luggageStorage: 'Free',
      parking: 'Free secure',
      contact: '+212539414115'
    },
    roomFeatures: ['ac', 'heating', 'sea-view', 'pool-access', 'kitchen'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Main Beach', distance: '400m', time: '6 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 48h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://www.booking.com/hotel/ma/asilah-luxury-sea-view.en-gb.html',
    instagramHandle: '@asilahluxury_official',
    reviewHighlights: {
      solo: 'Safe and very comfortable.',
      couples: 'The tennis courts and pool are excellent.',
      families: 'The kids loved the infinity pool and space.',
      business: 'Very professional management and fast internet.',
      nomad: 'Secure and comfortable for long stays.'
    },
    coordinates: {
      lat: 35.747449,
      lng: -5.768112
    },
    tags: ["family-favorite"]
  },
  {
    id: 'as-sleep-16',
    city: 'asilah',
    name: 'Darmimouna',
    type: 'riad',
    neighborhood: 'Medina (Old Town)',
    description: 'A charming and highly historic medina guesthouse that captures the colorful artistic spirit of Asilah. Cozy Moroccan seating, intricate woodwork, and a tranquil atmosphere make it a comforting old-town haven.',
    pricePerNight: 85,
    lifestyle: 'balanced',
    amenities: ['wifi', 'ac', 'breakfast'],
    googleRating: 4.4,
    googleReviewCount: 150,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 60,
    bookingRating: 4.6,
    bookingReviewCount: 100,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 20,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Book the room on the top floor to have the easiest access to the panoramic sunset rooftop.',
    vibeTags: ['Historic', 'Artistic', 'Old-World', 'Intimate'],
    locationSummary: "Asilah Historic Medina",
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.464567,-6.035123',
    address: 'Place Zelaka, Asilah 90050, Morocco',
    paymentMethods: ['cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Darmimouna is a classic medina house that has served as a cultural meeting point for Asilah\'s annual arts festival for decades.',
    neighborhoodOverview: 'Central medina near the festival area.',
    hiddenFeesNotice: 'None.',
    pros: ['Beautiful woodwork', 'Quiet medina retreat', 'Great Moroccan breakfast'],
    cons: ['No elevator', 'Steep traditional stairs'],
    trustScores: {
      cleanliness: 9.1,
      safety: 8.8,
      staff: 9.3,
      value: 9.0,
      comfort: 8.5,
      location: 9.6
    },
    logistics: {
      checkIn: '14:00 - 21:00',
      checkOut: 'Before 11:00',
      luggageStorage: 'Free',
      parking: 'Nearby public (Bab el-Houmar)',
      contact: '+212539414116'
    },
    roomFeatures: ['ac', 'heating', 'traditional-decor', 'woodwork'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Festival Stage', distance: '150m', time: '2 min walk', icon: 'city' }
    ],
    cancellationPolicy: 'Free cancellation up to 48h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://www.agoda.com/darmimouna/hotel/asilah-ma.html',
    instagramHandle: '@darmimouna_asilah',
    reviewHighlights: {
      solo: 'Extremely atmospheric and welcoming.',
      couples: 'The rooftop is small but very romantic.',
      families: 'Simple and authentic, the kids liked the tilework.',
      business: 'Good for a night of peace.',
      nomad: 'Cultural inspiration for creatives.'
    },
    coordinates: {
      lat: 35.467905,
      lng: -6.031041
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: 'as-sleep-17',
    city: 'asilah',
    name: 'Dar Yema',
    type: 'guesthouse',
    neighborhood: 'Medina (Old Town)',
    description: 'A delightful, newly renovated three-story medina house located right at the quiet entrance of the old town. Its cozy balcony and stunning rooftop deck offer incredible panoramic views of the sea and the white-and-blue streets.',
    pricePerNight: 69,
    lifestyle: 'lean',
    amenities: ['wifi', 'ac', 'kitchen'],
    googleRating: 4.3,
    googleReviewCount: 118,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 40,
    bookingRating: 4.4,
    bookingReviewCount: 60,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 15,
    hasPool: false,
    hasBreakfast: false,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'This entire multi-story house can be rented; ideal for small families or groups of friends wanting privacy.',
    vibeTags: ['Social', 'Family-Ready', 'Coastal-Chic', 'Independent'],
    locationSummary: "Asilah Historic Medina",
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.464123,-6.035890',
    address: '8 Rue Ahmed El Mansour, Asilah 90050, Morocco',
    paymentMethods: ['cash', 'card'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Dar Yema was renovated by a family who wanted a bright, Mediterranean-feeling home in the heart of the medina.',
    neighborhoodOverview: 'Quiet medina entrance near the promenade.',
    hiddenFeesNotice: 'None.',
    pros: ['Amazing multi-level rooftop', 'Modern kitchen', 'Bright and airy decor'],
    cons: ['Needs a full house booking for total privacy', 'Many stairs'],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.1,
      staff: 9.0,
      value: 9.2,
      comfort: 9.0,
      location: 9.5
    },
    logistics: {
      checkIn: '15:00 - 20:00',
      checkOut: 'Before 11:30',
      luggageStorage: 'Free',
      parking: 'Nearby public',
      contact: '+212539414117'
    },
    roomFeatures: ['ac', 'heating', 'sea-view', 'kitchen', 'rooftop-access'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Promenade', distance: '100m', time: '1 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 48h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://www.booking.com/hotel/ma/dar-yema.en-gb.html',
    instagramHandle: '@daryema_asilah',
    reviewHighlights: {
      solo: 'A bit big for just me but the rooftop is great.',
      couples: 'The sea views from the roof are the best in the medina.',
      families: 'Great to have a whole kitchen.',
      business: 'Decent internet for a medina house.',
      nomad: 'Kitchen + rooftop = ideal long stay.'
    },
    coordinates: {
      lat: 35.464288,
      lng: -6.039951
    },
    tags: ["family-favorite"]
  },
  {
    id: 'as-sleep-18',
    city: 'asilah',
    name: 'Hotel Zelis',
    type: 'hotel',
    neighborhood: 'New Town',
    description: 'A comfortable, modern hotel located in the town center just a short walk from the old medina and the port. It features classic southern Moroccan-inspired decor, a refreshing outdoor pool, and spacious air-conditioned rooms.',
    pricePerNight: 80,
    lifestyle: 'balanced',
    amenities: ['wifi', 'pool', 'ac', 'breakfast', 'restaurant', 'bar'],
    googleRating: 4.1,
    googleReviewCount: 778,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 150,
    bookingRating: 4.2,
    bookingReviewCount: 300,
    hotelguruRating: 4.1,
    hotelguruReviewCount: 50,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Ask for a room with a private balcony facing the sea to enjoy ocean breezes in the evening.',
    vibeTags: ['Classic-Comfort', 'Reliable', 'Central', 'Poolside'],
    locationSummary: "Asilah Historic Medina",
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.467890,-6.028900',
    address: 'Avenue Moulay Ismail, Asilah 90050, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Hotel Zelis has been a staple of Asilah\'s hospitality since the early 90s, offering a reliable hotel experience with a touch of Southern Moroccan architecture.',
    neighborhoodOverview: 'Central location near medina and port.',
    hiddenFeesNotice: 'None.',
    pros: ['Refreshing outdoor pool', 'Very central location', 'Good onsite restaurant'],
    cons: ['Decor is slightly dated', 'Breakfast can get busy'],
    trustScores: {
      cleanliness: 8.4,
      safety: 9.0,
      staff: 8.6,
      value: 8.7,
      comfort: 8.2,
      location: 9.4
    },
    logistics: {
      checkIn: '14:00 - 22:00',
      checkOut: 'Before 12:00',
      luggageStorage: 'Free',
      parking: 'On-site public parking',
      contact: '+212539414118'
    },
    roomFeatures: ['ac', 'heating', 'pool-access', 'balcony'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Old Town Entrance', distance: '300m', time: '4 min walk', icon: 'city' }
    ],
    cancellationPolicy: 'Free cancellation up to 48h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://www.booking.com/hotel/ma/zelis.en-gb.html',
    instagramHandle: '@hotelzelis_asilah',
    reviewHighlights: {
      solo: 'Reliable and central.',
      couples: 'The pool was great for a midday refresh.',
      families: 'Good sized rooms for families.',
      business: 'Professional staff and decent meeting lobby.',
      nomad: 'Pool + central location.'
    },
    coordinates: {
      lat: 35.467432,
      lng: -6.031591
    },
    tags: ["family-favorite"]
  },
  {
    id: 'as-sleep-19',
    city: 'asilah',
    name: 'Hotel Al Khaima',
    type: 'hotel',
    neighborhood: 'Corniche',
    description: 'A lively and iconic beachfront hotel located on the northern corniche of Asilah. Featuring traditional tent-themed dining and a large pool area, it is historically popular with visiting painters, writers, and families.',
    pricePerNight: 80,
    lifestyle: 'balanced',
    amenities: ['wifi', 'pool', 'ac', 'breakfast', 'restaurant', 'bar', 'beach'],
    googleRating: 4.1,
    googleReviewCount: 646,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 150,
    bookingRating: 4.1,
    bookingReviewCount: 200,
    hotelguruRating: 4.1,
    hotelguruReviewCount: 40,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'You can hear the sea from the rooms; request an ocean-facing unit for a highly atmospheric stay.',
    vibeTags: ['Nostalgic', 'Beachfront', 'Lively', 'Iconic'],
    locationSummary: "Asilah Historic Medina",
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.467123,-6.029876',
    address: 'Route de Tanger, Asilah 90050, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Al Khaima is famous for its tent-style restaurant that once hosted world-renowned writers and painters seeking beachside inspiration.',
    neighborhoodOverview: 'Beachfront corniche area north of the medina.',
    hiddenFeesNotice: 'None.',
    pros: ['Literally steps to the beach', 'Great nostalgic atmosphere', 'Excellent poolside dining'],
    cons: ['Some rooms need renovation', 'Can get loud at night with entertainment'],
    trustScores: {
      cleanliness: 7.8,
      safety: 8.5,
      staff: 8.7,
      value: 8.4,
      comfort: 7.6,
      location: 9.7
    },
    logistics: {
      checkIn: '14:00 - 22:00',
      checkOut: 'Before 12:00',
      luggageStorage: 'Free',
      parking: 'Free secure private',
      contact: '+212539414119'
    },
    roomFeatures: ['ac', 'heating', 'sea-view', 'pool-access'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'North Beach', distance: '50m', time: '1 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Free cancellation up to 48h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://www.booking.com/hotel/ma/al-khaima.en-gb.html',
    instagramHandle: '@alkhaimaasilah',
    reviewHighlights: {
      solo: 'Basic but the beachfront location is unmatched.',
      couples: 'The tent-dining experience is very traditional.',
      families: 'The big pool was perfect for the kids.',
      business: 'Good for a night, but not for quiet business work.',
      nomad: 'Beachfront budget option.'
    },
    coordinates: {
      lat: 35.474373,
      lng: -6.026015
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: 'as-sleep-20',
    city: 'asilah',
    name: 'Patio de la Luna',
    type: 'guesthouse',
    neighborhood: 'Medina (Old Town)',
    description: 'A historic, Spanish-styled guesthouse located directly in front of the medina\'s prominent old rampart gates. Its peaceful central courtyard is filled with lush greenery and evokes a deeply nostalgic, old-world vibe.',
    pricePerNight: 50,
    lifestyle: 'lean',
    amenities: ['wifi', 'breakfast'],
    googleRating: 4.1,
    googleReviewCount: 219,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 100,
    bookingRating: 4.2,
    bookingReviewCount: 150,
    hotelguruRating: 4.1,
    hotelguruReviewCount: 30,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ['solo', 'couple', 'family'],
    // googlePlaceId: "PLACE_ID_HERE",
    tip: 'Order a coffee and enjoy it in the courtyard; it\'s one of the most serene and peaceful spots in Asilah.',
    vibeTags: ['Spanish-Colonial', 'Green', 'Nostalgic', 'Central'],
    locationSummary: "Asilah Historic Medina",
    availabilityText: 'Available tonight',
    googleMapsUrl: 'https://www.google.com/maps/place/35.465890,-6.034567',
    address: 'Place de la Kasbah, Asilah 90050, Morocco',
    paymentMethods: ['cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Patio de la Luna is a historic Spanish-style townhouse that evokes the colonial era of Asilah with its lush, garden patio.',
    neighborhoodOverview: 'Medina entrance near the rampart gates.',
    hiddenFeesNotice: 'None.',
    pros: ['Very peaceful garden patio', 'Prime medina entrance location', 'Great value and clean'],
    cons: ['No AC (thick walls help though)', 'Simple breakfast'],
    trustScores: {
      cleanliness: 8.9,
      safety: 9.0,
      staff: 9.1,
      value: 9.4,
      comfort: 8.2,
      location: 9.8
    },
    logistics: {
      checkIn: '13:00 - 21:00',
      checkOut: 'Before 11:30',
      luggageStorage: 'Free',
      parking: 'Nearby public (Bab Kasbah)',
      contact: '+212539414120'
    },
    roomFeatures: ['heating', 'garden-view', 'courtyard-access'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Rampart Gates', distance: 'Direct', time: '1 min walk', icon: 'city' }
    ],
    cancellationPolicy: 'Free cancellation up to 48h before check-in',
    childPolicy: 'Children welcome',
    officialWebsite: 'https://www.booking.com/hotel/ma/patio-de-la-luna.en-gb.html',
    instagramHandle: '@patiodelaluna_asilah',
    reviewHighlights: {
      solo: 'A very peaceful and affordable spot for a solo walker.',
      couples: 'The old-world charm is very relaxing.',
      families: 'Simple but the garden is great for a quiet evening.',
      business: 'Wi-Fi is better in the patio than the rooms.',
      nomad: 'Ultra-budget medina base.'
    },
    coordinates: {
      lat: 35.46648,
      lng: -6.035642
    },
    tags: ["family-favorite", "heritage"]
  }
]