import type { SleepListing } from '../types'

/**
 * SLEEP LISTING DATA TEMPLATE (Copy this for your search agent)
 * -------------------------------------------------------------
 * {
 *   "id": "city-sleep-XX",
 *   "name": "",
 *   "type": "riad | hotel | villa | hostel | apartment | guesthouse",
 *   "neighborhood": "",
 *   "city": "[city]",
 *   "description": "",
 *   "pricePerNight": 0,
 *   "lifestyle": "lean | balanced | premium",
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2', 'url3']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source (replaces single rating/reviewCount)
 *   // ═══════════════════════════════════════════════════
 *   // Search for real ratings from Google, TripAdvisor, Booking.com, and HotelGuru.
 *   // If you cannot find a rating for a specific source, set it to the same value as
 *   // the closest available one so average calculations don't break.
 *
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *   bookingRating: [4.x],
 *   bookingReviewCount: [number],
 *   hotelguruRating: [4.x],
 *   hotelguruReviewCount: [number],
 *
 *   // ═══════════════════════════════════════════════════
 *   // BOOLEAN AMENITIES
 *   // ═══════════════════════════════════════════════════
 *
 *   hasPool: true | false,
 *   hasBreakfast: true | false,
 *   hasAC: true | false,
 *   hasHeating: true | false,
 *   hasRooftop: true | false,
 *   hasEnsuite: true | false,
 *   hasRestaurant: true | false,
 *   hasBar: true | false,
 *   hasGym: true | false,
 *   hasElevator: true | false,
 *   hasLaundryService: true | false,
 *   hasRoomService: true | false,
 *   petFriendly: true | false,
 *   isWheelchairAccessible: true | false,
 *   taxesIncluded: true | false,
 *   freeCancellation: true | false,
 *   kidsStayFree: true | false,
 *
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearMosque: true | false,
 *   safetyLevel: 1 | 2 | 3 | 4 | 5,
 *
 *   // ═══════════════════════════════════════════════════
 *   // TRUST SCORES
 *   // ═══════════════════════════════════════════════════
 *
 *   trustScores: {
 *     cleanliness: [1-10],
 *     safety: [1-10],
 *     staff: [1-10],
 *     value: [1-10],
 *     comfort: [1-10],
 *     location: [1-10]
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   amenities: ['wifi', 'pool', 'ac', 'breakfast', 'spa', 'restaurant', 'gym', 'kitchenette', 'parking', 'bar', 'laundry', 'elevator', 'room-service'],
 *   tip: '[Short insider tip]',
 *   vibeTags: ['Authentic', 'Quiet', 'Modern'],
 *   locationSummary: 'Beachfront | City Center | Medina | Airport Area | Residential | Tourist Zone',
 *   availabilityText: 'Available tonight | Only 2 rooms left | Available on selected dates',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   address: '[Full street address, City, Postal Code, Morocco]',
 *
 *   paymentMethods: ['card', 'cash'],
 *   languagesSpoken: ['Arabic', 'French', 'English', 'Spanish', 'German'],
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   customStory: 'Brief history, owner background, or architecture notes...',
 *   neighborhoodOverview: 'Description of the local atmosphere, safety, and vibe...',
 *   hiddenFeesNotice: 'City tax of XX MAD per person/night not included...',
 *   pros: ['Pro 1', 'Pro 2'],
 *   cons: ['Con 1'],
 *
 *   // ═══════════════════════════════════════════════════
 *   // LOGISTICS
 *   // ═══════════════════════════════════════════════════
 *
 *   logistics: {
 *     checkIn: '14:00 - 22:00',
 *     checkOut: 'Before 11:00',
 *     luggageStorage: 'Free | Paid | None',
 *     parking: 'Free on-site | Nearby public | Valet',
 *     contact: '+212 XXXXXXXXX'
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *   // ROOM FEATURES & TYPES
 *   // ═══════════════════════════════════════════════════
 *
 *   roomFeatures: ['soundproof', 'workspace', 'private-balcony', 'ac', 'heating', 'balcony', 'shower-ensuite', 'sea-view', 'garden-view', 'pool-view'],
 *   roomTypes: [
 *     {
 *       name: 'Double Room',
 *       price: 500,
 *       beds: '1 Queen',
 *       size: '20m2',
 *     }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *   // NEIGHBORHOOD DISTANCES
 *   // ═══════════════════════════════════════════════════
 *
 *   neighborhoodDistances: [
 *     { label: 'Beach', distance: '500m', time: '5 min walk', icon: 'beach' }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   cancellationPolicy: 'Free cancellation up to 24h before check-in | Flexible | Non-refundable',
 *   childPolicy: 'Children welcome | Free under 6 | Extra bed 200 MAD',
 *   officialWebsite: 'https://...',
 *   instagramHandle: '@...',
 *
 *   // googlePlaceId: "PLACE_ID_HERE",
 *
 *   // ═══════════════════════════════════════════════════
 *   // REVIEW HIGHLIGHTS
 *   // ═══════════════════════════════════════════════════
 *
 *   reviewHighlights: {
 *     solo: 'Great insight for solo...',
 *     couples: 'Great for couples...',
 *     families: 'Kid-friendly details...',
 *     business: 'Wi-Fi test details...',
 *     nomad: 'Remote work specific insight...'
 *   }
 * }
 */

export const casablancaSleep: SleepListing[] = [
  {
    id: 'c-sleep-1',
    city: 'casablanca',
    name: 'Le Casablanca Hotel',
    type: 'hotel',
    neighborhood: 'Anfa',
    description: 'A sophisticated urban oasis featuring Art Deco elegance and a lush garden setting in the prestigious Anfa district. Known for its glamorous pool scene and refined French-Moroccan atmosphere.',
    pricePerNight: 280,
    lifestyle: 'premium',
    amenities: ['Lush Garden Pool', 'Art Deco Lounge', 'Gourmet Restaurant', 'Luxury Spa', 'Wifi', 'AC'],
    googleRating: 4.7,
    googleReviewCount: 850,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 600,
    bookingRating: 4.8,
    bookingReviewCount: 900,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 150,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'seniors', 'business-friendly'],
    tip: 'The garden brunch on Sundays is one of the most stylish events in Casablanca; book a table even if you aren’t staying.',
    vibeTags: ['Art-Deco', 'Glamorous', 'Garden-Oasis', 'Prestigious'],
    locationSummary: "City Center & Gauthier Business District",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Le+Casablanca+Hotel/@33.5912,-7.6445,17z](https://www.google.com/maps/place/Le+Casablanca+Hotel/@33.5912,-7.6445,17z)',
    address: '19 Boulevard Moulay Rachid, Casablanca 20000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Designed to capture the golden age of Casablanca, this hotel feels like a set from a classic film, blending old-world charm with modern luxury.',
    neighborhoodOverview: 'Anfa is the most exclusive neighborhood in Casablanca, home to beautiful villas, high-end boutiques, and the city’s best residential streets.',
    hiddenFeesNotice: 'City tax of 28.60 MAD per person/night not included.',
    pros: ['Stunning Art Deco design', 'Beautifully secluded garden and pool', 'Excellent service'],
    cons: ['Away from the main business center', 'Can be pricey for dining'],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.8,
      staff: 9.5,
      value: 8.4,
      comfort: 9.7,
      location: 9.3
    },
    logistics: {
      checkIn: '15:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Free valet',
      contact: '+212 522 649 797'
    },
    roomFeatures: ['garden-views', 'high-ceilings', 'premium-bedding', 'ac'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Anfa Place Mall', distance: '1.5km', time: '5 min drive', icon: 'shopping' },
      { label: 'Corniche', distance: '2km', time: '7 min drive', icon: 'beach' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children of all ages welcome; baby cots free on request.',
    officialWebsite: '[https://www.lecasablanca-hotel.com](https://www.lecasablanca-hotel.com)',
    instagramHandle: '@lecasablancahotel',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'Extremely safe and elegant for a solo traveler.',
      couples: 'The most romantic garden setting in the city.',
      families: 'Quiet and upscale, better for couples.',
      business: 'Prestigious for high-level meetings.',
      nomad: 'Fast internet and inspiring garden corners to work.'
    },
    coordinates: {
      lat: 33.58683,
      lng: -7.621331
    },
    tags: []
  },
  {
    id: 'c-sleep-2',
    city: 'casablanca',
    name: 'Gauthier Art Deco Hotel',
    type: 'hotel',
    neighborhood: 'Gauthier',
    description: 'A stylish boutique hotel located in the trendy Gauthier district. It captures the city’s architectural heritage with its clean Art Deco lines and offers a sophisticated, quiet retreat just steps away from Casablanca’s best art galleries and restaurants.',
    pricePerNight: 110,
    lifestyle: 'balanced',
    amenities: ['Art Deco Design', 'Boutique Lounge', 'Gourmet Breakfast', 'Personalized Service', 'Wifi', 'AC'],
    googleRating: 4.5,
    googleReviewCount: 220,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 180,
    bookingRating: 4.6,
    bookingReviewCount: 300,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 50,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'seniors'],
    tip: 'Take a short walk to the "Villa des Arts" nearby—it’s one of the best cultural spots in the city for contemporary Moroccan art.',
    vibeTags: ['Boutique', 'Art-Deco', 'Sophisticated', 'Local'],
    locationSummary: "City Center & Gauthier Business District",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Gauthier+Art+Deco+Hotel/@33.5875,-7.6245,17z](https://www.google.com/maps/place/Gauthier+Art+Deco+Hotel/@33.5875,-7.6245,17z)',
    address: "4 Rue de l'Aisne, Casablanca 20000, Morocco",
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Housed in a meticulously restored 1930s building, this hotel was designed to celebrate Casablanca’s unique position as a world capital of Art Deco architecture.',
    neighborhoodOverview: 'Gauthier is the "Soho" of Casablanca—vibrant, safe, and filled with the city’s most interesting creative professionals and hidden cafes.',
    hiddenFeesNotice: 'City tax of 28.60 MAD per person/night not included.',
    pros: ['Excellent location for dining and art', 'Authentic Art Deco atmosphere', 'Very quiet and safe'],
    cons: ['No swimming pool', 'Small fitness area'],
    trustScores: {
      cleanliness: 9.7,
      safety: 9.9,
      staff: 9.6,
      value: 9.2,
      comfort: 9.4,
      location: 9.8
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Limited street parking',
      contact: '+212 522 223 344'
    },
    roomFeatures: ['deco-furniture', 'quiet-street-view', 'premium-linens', 'ac'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Villa des Arts', distance: '300m', time: '4 min walk', icon: 'art' },
      { label: 'Twin Center', distance: '800m', time: '10 min walk', icon: 'building' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Adults-focused but children welcome; family-suites available.',
    officialWebsite: '[https://gauthier-art-deco.com](https://gauthier-art-deco.com)',
    instagramHandle: '@gauthierartdeco',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A safe and incredibly stylish haven for a solo traveler.',
      couples: 'The neighborhood is perfect for romantic evening walks and dinners.',
      families: 'Better suited for couples or business travelers.',
      business: 'Quiet and central with reliable WiFi.',
      nomad: 'The lounge is a great spot for afternoon work sessions.'
    },
    coordinates: {
      lat: 33.587944,
      lng: -7.627771
    },
    tags: ["heritage"]
  },
  {
    id: 'c-sleep-3',
    city: 'casablanca',
    name: 'Four Seasons Hotel Casablanca',
    type: 'hotel',
    neighborhood: 'Anfa Place',
    description: 'A contemporary oceanfront masterpiece perched above the Atlantic. This resort-style hotel offers unparalleled sunset views, a world-class spa, and the highest standard of luxury service in the city.',
    pricePerNight: 450,
    lifestyle: 'premium',
    amenities: ['Outdoor Resort Pool', 'Guerlain Spa', 'Ocean-View Terraces', 'Fitness Center', 'Wifi', 'AC'],
    googleRating: 4.8,
    googleReviewCount: 1500,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 1200,
    bookingRating: 4.7,
    bookingReviewCount: 1800,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 400,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['couple', 'family', 'business-friendly', 'seniors'],
    tip: 'The "Mint" terrace is the best place in the city for sunset tea; arrive 30 minutes before sunset to secure a front-row seat.',
    vibeTags: ['Oceanfront', 'Modern-Luxury', 'Resort-Style', 'Sunset-Views'],
    locationSummary: "Ain Diab Corniche & Anfa",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Four+Seasons+Hotel+Casablanca/@33.5978,-7.6645,17z](https://www.google.com/maps/place/Four+Seasons+Hotel+Casablanca/@33.5978,-7.6645,17z)',
    address: 'Boulevard de la Corniche, Casablanca 20050, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Built as part of the prestigious Anfa Place development, this Four Seasons property redefined the Casablanca waterfront with its minimalist, light-filled architecture.',
    neighborhoodOverview: 'Located on the Corniche, adjacent to the high-end Anfa Place Mall, offering a mix of luxury living and vibrant coastal energy.',
    hiddenFeesNotice: 'City tax of 28.60 MAD per person/night not included.',
    pros: ['Unmatched ocean views', 'Stunning modern design', 'Top-tier service quality'],
    cons: ['Higher price than city center hotels', 'Can be windy on the terraces'],
    trustScores: {
      cleanliness: 9.8,
      safety: 9.9,
      staff: 9.8,
      value: 8.2,
      comfort: 9.8,
      location: 9.7
    },
    logistics: {
      checkIn: '15:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Free valet',
      contact: '+212 529 073 700'
    },
    roomFeatures: ['floor-to-ceiling-windows', 'ocean-view-balcony', 'marble-bathrooms', 'ac'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Anfa Place Mall', distance: '100m', time: '1 min walk', icon: 'shopping' },
      { label: 'Hassan II Mosque', distance: '4km', time: '10 min drive', icon: 'mosque' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children stay free; special kids menu and activities.',
    officialWebsite: '[https://www.fourseasons.com/casablanca/](https://www.fourseasons.com/casablanca/)',
    instagramHandle: '@fscasablanca',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'Incredibly secure and world-class service.',
      couples: 'The most romantic oceanfront escape in Casa.',
      families: 'Great kids amenities and spacious suites.',
      business: 'Exceptional business facilities and networking spots.',
      nomad: 'High-speed fiber and multiple quiet spots with ocean views.'
    },
    coordinates: {
      lat: 33.599545,
      lng: -7.663758
    },
    tags: ["family-favorite"]
  },
  {
    id: 'c-sleep-4',
    city: 'casablanca',
    name: 'Medina Hostel Casablanca',
    type: 'hostel',
    neighborhood: 'Old Medina',
    description: 'A vibrant and authentic hostel located right inside the historic walls of the old medina. It offers a rare chance to experience the unpolished, real heart of Casablanca with a budget-friendly price and a spectacular rooftop view of the Hassan II Mosque.',
    pricePerNight: 25,
    lifestyle: 'lean',
    amenities: ['Social Rooftop Terrace', 'Shared Kitchen', 'Cultural Workshops', 'Wifi', 'Locker storage'],
    googleRating: 4.2,
    googleReviewCount: 380,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 150,
    bookingRating: 4.1,
    bookingReviewCount: 200,
    hotelguruRating: 4.0,
    hotelguruReviewCount: 20,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: false,
    hasRooftop: true,
    hasEnsuite: false,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 3,
    groupTypes: ['solo', 'friends'],
    tip: "Casablanca's old medina is a real working neighborhood. It's gritty and authentic—be respectful and stay on the main paths after dark.",
    vibeTags: ['Authentic', 'Social', 'Gritty', 'Budget-Friendly'],
    locationSummary: "Ancienne Médina",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Medina+Hostel+Casablanca/@33.5975,-7.6185,17z](https://www.google.com/maps/place/Medina+Hostel+Casablanca/@33.5975,-7.6185,17z)',
    address: '50 Place Ahmed el Bidaoui, Casablanca 20000, Morocco',
    paymentMethods: ['cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Founded by local young travelers, this hostel aims to show visitors the "other side" of Casablanca—the vibrant, living history of the medina that most tourists miss.',
    neighborhoodOverview: 'The Old Medina of Casablanca is much smaller and more unpolished than those in Fes or Marrakech, providing a fascinating glimpse into local life.',
    hiddenFeesNotice: 'City tax of 15 MAD per person/night not included.',
    pros: ['Unbeatable price point', 'Incredible rooftop view', 'Deeply authentic location'],
    cons: ['Medina can be confusing to navigate at night', 'Shared facilities only'],
    trustScores: {
      cleanliness: 8.2,
      safety: 7.8,
      staff: 9.4,
      value: 9.8,
      comfort: 7.5,
      location: 9.1
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '11:00',
      luggageStorage: 'Free',
      parking: 'Public parking outside the medina walls',
      contact: '+212 522 334 455'
    },
    roomFeatures: ['bunk-beds', 'shared-bathrooms', 'medina-views', 'lockers'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Rick’s Café', distance: '400m', time: '5 min walk', icon: 'utensils' },
      { label: 'Hassan II Mosque', distance: '1.5km', time: '15 min walk', icon: 'mosque' }
    ],
    cancellationPolicy: 'Flexible 24h',
    childPolicy: 'Not recommended for children; age restriction for dorms (18+).',
    officialWebsite: '[https://medinahostelcasa.com](https://medinahostelcasa.com)',
    instagramHandle: '@medinahostelcasa',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A bit intimidating at first, but the community inside is wonderful and safe.',
      couples: 'Great for adventurous couples on a tight budget.',
      families: 'Not recommended for families with young children.',
      business: 'Good for a quick overnight if you are on a budget.',
      nomad: 'The rooftop view is incredible, but WiFi can be spotty in the alleys.'
    },
    coordinates: {
      lat: 33.600342,
      lng: -7.617355
    },
    tags: ["dorm", "heritage"]
  },
  {
    id: 'c-sleep-5',
    city: 'casablanca',
    name: 'Radisson Blu Hotel, Casablanca City Center',
    type: 'hotel',
    neighborhood: 'City Center',
    description: 'A stylish and contemporary urban escape in the heart of Casablanca. This high-design hotel features an indoor pool, a sophisticated spa, and a stunning rooftop bar with views over the Art Deco district and the Atlantic.',
    pricePerNight: 135,
    lifestyle: 'premium',
    amenities: ['Indoor Swimming Pool', 'Rooftop Bar & Grill', 'Full-Service Spa', 'Fitness Center', 'Wifi', 'AC'],
    googleRating: 4.5,
    googleReviewCount: 780,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 500,
    bookingRating: 4.4,
    bookingReviewCount: 1200,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 200,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['business-friendly', 'couple', 'solo'],
    tip: 'The rooftop bar is one of the best spots in the city for a sunset cocktail with a modern vibe.',
    vibeTags: ['Modern', 'Chic', 'Urban', 'Sophisticated'],
    locationSummary: "City Center & Gauthier Business District",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Radisson+Blu+Hotel,+Casablanca+City+Center/@33.5925,-7.6125,17z](https://www.google.com/maps/place/Radisson+Blu+Hotel,+Casablanca+City+Center/@33.5925,-7.6125,17z)',
    address: '02 Boulevard Mohamed V, Casablanca 20000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Designed to reflect the dynamic energy of modern Casablanca, this hotel stands as a beacon of contemporary luxury in the historic city center.',
    neighborhoodOverview: 'Located on the iconic Boulevard Mohamed V, surrounded by Casablanca’s famous Art Deco architecture and just steps from the business district.',
    hiddenFeesNotice: 'City tax of 28.60 MAD per person/night not included.',
    pros: ['Stunning modern design', 'Excellent rooftop and pool facilities', 'Very central for business'],
    cons: ['Traffic in the area can be heavy during rush hour'],
    trustScores: {
      cleanliness: 9.7,
      safety: 9.8,
      staff: 9.6,
      value: 9.1,
      comfort: 9.7,
      location: 9.7
    },
    logistics: {
      checkIn: '15:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Secure on-site parking',
      contact: '+212 522 667 700'
    },
    roomFeatures: ['floor-to-ceiling-windows', 'nespresso-machine', 'modern-art', 'ac'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Casablanca Port Station', distance: '800m', time: '10 min walk', icon: 'train' },
      { label: 'Central Market', distance: '500m', time: '6 min walk', icon: 'shopping' }
    ],
    cancellationPolicy: 'Moderate 24h',
    childPolicy: 'Children stay free using existing bedding.',
    officialWebsite: '[https://radissonhotels.com](https://radissonhotels.com)',
    instagramHandle: '@radissonblucasablanca',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A safe, modern, and very comfortable base in the city center.',
      couples: 'The rooftop bar and the spa made our city break perfect.',
      families: 'Good facilities, though better suited for business or couples.',
      business: 'Excellent business center and the WiFi was flawless.',
      nomad: 'The rooftop is a great place to work with a view.'
    },
    coordinates: {
      lat: 33.587944,
      lng: -7.627771
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: 'c-sleep-6',
    city: 'casablanca',
    name: 'Hyatt Regency Casablanca',
    type: 'hotel',
    neighborhood: 'Centre-Ville',
    description: 'Iconic luxury hotel located in the heart of the city, perfectly situated for business and leisure. Known for its historical significance and elegant service.',
    pricePerNight: 200,
    lifestyle: 'premium',
    amenities: ['pool', 'spa', 'bar', 'gym', 'business-center', 'wifi'],
    googleRating: 4.6,
    googleReviewCount: 3000,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 2200,
    bookingRating: 4.6,
    bookingReviewCount: 3500,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 800,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['couple', 'solo', 'business-friendly'],
    tip: 'Grab a drink at the Dar Beida lounge featuring live music on weekends.',
    vibeTags: ['Iconic', 'Business', 'Central', 'Classic'],
    locationSummary: "City Center & Gauthier Business District",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Hyatt+Regency+Casablanca/@33.5951,-7.6186,17z](https://www.google.com/maps/place/Hyatt+Regency+Casablanca/@33.5951,-7.6186,17z)',
    address: 'Place des Nations Unies, Casablanca 20000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'A cornerstone of Casablanca’s modern history, this hotel has hosted countless international summits and celebrities since its opening.',
    neighborhoodOverview: 'Located right at the Place des Nations Unies, the intersection of the modern city and the historic old medina.',
    hiddenFeesNotice: 'City tax of 39.60 MAD per person/night not included.',
    pros: ['Prime central location', 'Excellent business facilities', 'Historic character'],
    cons: ['Can be busy with corporate events', 'Traditional rooms feel a bit classic'],
    trustScores: {
      cleanliness: 9.5,
      safety: 9.6,
      staff: 9.5,
      value: 8.8,
      comfort: 9.4,
      location: 9.9
    },
    logistics: {
      checkIn: '15:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Free secure on-site',
      contact: '+212 522 431 234'
    },
    roomFeatures: ['soundproof', 'workspace', 'large-windows', 'ac'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Old Medina', distance: '200m', time: '3 min walk', icon: 'city' },
      { label: 'Casa Port Station', distance: '500m', time: '7 min walk', icon: 'train' }
    ],
    cancellationPolicy: 'Flexible 24h',
    childPolicy: 'Up to 2 children under 12 stay free with parents.',
    officialWebsite: '[https://www.hyatt.com/en-US/hotel/morocco/hyatt-regency-casablanca/casab](https://www.hyatt.com/en-US/hotel/morocco/hyatt-regency-casablanca/casab)',
    instagramHandle: '@hyattregencycasablanca',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'Perfect business base with very helpful staff.',
      couples: 'The central location is unbeatable for exploring.',
      families: 'A bit corporate but safe and central.',
      business: 'Top-tier executive lounge and meeting spaces.',
      nomad: 'Reliable fast internet in the business lounge.'
    },
    coordinates: {
      lat: 33.596087,
      lng: -7.618828
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: 'c-sleep-7',
    city: 'casablanca',
    name: 'Sofitel Casablanca Tour Blanche',
    type: 'hotel',
    neighborhood: 'Centre-Ville',
    description: 'A striking skyscraper hotel where French "art de vivre" meets Moroccan hospitality. Located opposite the Medina, it offers breathtaking views of the city and the Hassan II Mosque from its contemporary rooms and its famous penthouse bar.',
    pricePerNight: 220,
    lifestyle: 'premium',
    amenities: ['Panoramic Penthouse Bar', 'Luxury So SPA', 'Gourmet French-Moroccan Dining', 'Indoor Heated Pool', 'Wifi', 'AC'],
    googleRating: 4.7,
    googleReviewCount: 2100,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 1500,
    bookingRating: 4.7,
    bookingReviewCount: 2500,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 600,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['couple', 'solo', 'seniors', 'business-friendly'],
    tip: 'The "Bar Casart" on the top floor offers the best sunset view of the Hassan II Mosque in the entire city.',
    vibeTags: ['Chic', 'Contemporary', 'Panoramic', 'Vibrant'],
    locationSummary: "City Center & Gauthier Business District",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Sofitel+Casablanca+Tour+Blanche/@33.5955,-7.6165,17z](https://www.google.com/maps/place/Sofitel+Casablanca+Tour+Blanche/@33.5955,-7.6165,17z)',
    address: 'Rue Sidi Belyout, Casablanca 20000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Designed to be a "lighthouse" of modern Casablanca, the Tour Blanche reflects the city’s ambition and its deep French colonial architectural roots.',
    neighborhoodOverview: 'Situated at the edge of the business district and the historic old medina, providing perfect access for both work and exploration.',
    hiddenFeesNotice: 'City tax of 39.60 MAD per person/night not included.',
    pros: ['Incredible panoramic views', 'Exceptional spa and wellness facilities', 'Very central and highly secure'],
    cons: ['Can be busy during business summits', 'Premium price for dining'],
    trustScores: {
      cleanliness: 9.8,
      safety: 9.9,
      staff: 9.7,
      value: 8.9,
      comfort: 9.6,
      location: 9.8
    },
    logistics: {
      checkIn: '15:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Secure valet parking',
      contact: '+212 522 456 200'
    },
    roomFeatures: ['floor-to-ceiling-windows', 'luxury-bedding', 'hermes-bath-products', 'ac'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Old Medina Entrance', distance: '100m', time: '2 min walk', icon: 'city' },
      { label: 'Casa Port Station', distance: '300m', time: '4 min walk', icon: 'train' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children stay free using existing bedding; special kids amenities.',
    officialWebsite: '[https://all.accor.com/hotel/6811/index.en.shtml](https://all.accor.com/hotel/6811/index.en.shtml)',
    instagramHandle: '@sofitelcasablanca',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'Extremely safe and central for a solo business stay.',
      couples: 'The view from the room was the most romantic part of our trip.',
      families: 'Great suites and very accommodating staff.',
      business: 'The best executive lounge and meeting facilities in Casa.',
      nomad: 'Fast internet and incredible views to keep you inspired while working.'
    },
    coordinates: {
      lat: 33.598617,
      lng: -7.613284
    },
    tags: ["family-favorite"]
  },
  {
    id: 'c-sleep-8',
    city: 'casablanca',
    name: 'Kenzi Tower Hotel',
    type: 'hotel',
    neighborhood: 'Maarif',
    description: 'Located in one of the iconic Twin Center towers, this hotel defines the Casablanca skyline. It offers spacious, modern rooms with 360-degree views of the city and the ocean, featuring high-end business facilities and one of the city’s most famous panoramic restaurants.',
    pricePerNight: 160,
    lifestyle: 'balanced',
    amenities: ['Sky-High Panoramic Restaurant', 'Luxury O-SPA', 'Fitness Center', 'Executive Lounge', 'Wifi', 'AC'],
    googleRating: 4.3,
    googleReviewCount: 4500,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 3200,
    bookingRating: 4.2,
    bookingReviewCount: 5000,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 1200,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['couple', 'friends', 'solo', 'business-friendly'],
    tip: 'Book a "Sky View" room on a floor above the 20th for a truly unforgettable perspective of Casablanca’s sprawling urban landscape.',
    vibeTags: ['Iconic', 'Urban', 'Panoramic', 'Business'],
    locationSummary: "City Center & Gauthier Business District",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Kenzi+Tower+Hotel/@33.5855,-7.6325,17z](https://www.google.com/maps/place/Kenzi+Tower+Hotel/@33.5855,-7.6325,17z)',
    address: 'Twin Center, Boulevard Mohamed Zerktouni, Casablanca 20000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'As the tallest hotel in North Africa for years, Kenzi Tower is a symbol of Casablanca’s modern economic power and its vibrant, skyscraper-filled future.',
    neighborhoodOverview: 'Maarif is the heart of Casablanca’s shopping and business life, home to the Twin Center and the most famous fashion boulevards.',
    hiddenFeesNotice: 'City tax of 39.60 MAD per person/night not included.',
    pros: ['Unrivaled 360-degree city views', 'Huge rooms for a city center hotel', 'In the middle of the best shopping district'],
    cons: ['Elevators can be slow during peak hours', 'Some areas feel a bit corporate'],
    trustScores: {
      cleanliness: 9.4,
      safety: 9.9,
      staff: 9.2,
      value: 8.8,
      comfort: 9.5,
      location: 9.8
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Secure underground parking',
      contact: '+212 522 978 000'
    },
    roomFeatures: ['panoramic-windows', 'workspace', 'separate-seating-area', 'ac'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Twin Center Shopping', distance: '0m', time: 'In-house', icon: 'shopping' },
      { label: 'Arab League Park', distance: '1.2km', time: '15 min walk', icon: 'park' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children stay free using existing bedding; family suites available.',
    officialWebsite: '[https://www.kenzi-hotels.com/kenzi-tower/](https://www.kenzi-hotels.com/kenzi-tower/)',
    instagramHandle: '@kenzitowerhotel',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A very safe and efficient base for a business trip.',
      couples: 'The dinner at the sky restaurant is a must for a romantic night.',
      families: 'Great central location and huge rooms for the price.',
      business: 'Excellent facilities and very well known for meetings.',
      nomad: 'The business lounge has the best views and decent WiFi.'
    },
    coordinates: {
      lat: 33.586587,
      lng: -7.632085
    },
    tags: ["family-favorite"]
  },
  {
    id: 'c-sleep-9',
    city: 'casablanca',
    name: 'Barceló Anfa Casablanca',
    type: 'hotel',
    neighborhood: 'Anfa',
    description: 'A contemporary 5-star hotel that pays homage to Casablanca’s Art Deco heritage. Located in the bustling Anfa district, it features a magnificent rooftop pool deck, a state-of-the-art wellness center, and sleek, futuristic room designs that offer a high-tech stay in the heart of the city.',
    pricePerNight: 130,
    lifestyle: 'balanced',
    amenities: ['Rooftop Swimming Pool', 'Modern Fitness Center', 'B-Room Concept', 'Gourmet Tapas Bar', 'Wifi', 'AC'],
    googleRating: 4.5,
    googleReviewCount: 1800,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 1200,
    bookingRating: 4.4,
    bookingReviewCount: 2000,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 400,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['couple', 'solo', 'business-friendly'],
    tip: 'The rooftop terrace "B-Heaven" is one of the most vibrant spots in the city for an evening cocktail with a view.',
    vibeTags: ['Modern', 'High-Tech', 'Vibrant', 'Central'],
    locationSummary: "Ain Diab Corniche & Anfa",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Barcel%C3%B3+Anfa+Casablanca/@33.5885,-7.6285,17z](https://www.google.com/maps/place/Barcel%C3%B3+Anfa+Casablanca/@33.5885,-7.6285,17z)',
    address: '44 Boulevard d’Anfa, Casablanca 20000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Designed to be the ultimate urban lifestyle hotel, Barceló Anfa merges the historical elegance of Casablanca’s white city with the digital needs of today’s traveler.',
    neighborhoodOverview: 'The Anfa district is the center of Casablanca’s modern business and social life, home to the best restaurants and the city’s wide Art Deco boulevards.',
    hiddenFeesNotice: 'City tax of 28.60 MAD per person/night not included.',
    pros: ['Excellent rooftop pool and bar', 'Very modern and high-tech rooms', 'Safe and central business location'],
    cons: ['Can be noisy due to its central boulevard location', 'Service can be a bit corporate'],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.9,
      staff: 9.4,
      value: 9.1,
      comfort: 9.5,
      location: 9.8
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Secure underground parking',
      contact: '+212 522 956 900'
    },
    roomFeatures: ['smart-lighting', 'rain-shower', 'work-desk', 'ac'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Twin Center', distance: '1.2km', time: '15 min walk', icon: 'building' },
      { label: 'Arab League Park', distance: '1.5km', time: '18 min walk', icon: 'park' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children stay free using existing bedding; family suites available.',
    officialWebsite: '[https://www.barcelo.com/en-gb/barcelo-anfa-casablanca/](https://www.barcelo.com/en-gb/barcelo-anfa-casablanca/)',
    instagramHandle: '@barceloanfa',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A very safe and modern base for a solo work trip.',
      couples: 'The rooftop pool area is perfect for a romantic afternoon.',
      families: 'Modern and safe, but better suited for business or couples.',
      business: 'Excellent WiFi and very modern meeting spaces.',
      nomad: 'High-speed internet and the rooftop bar is a great place to work.'
    },
    coordinates: {
      lat: 33.591096,
      lng: -7.635382
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: 'c-sleep-10',
    city: 'casablanca',
    name: 'Melliber Appart Hotel',
    type: 'hotel',
    neighborhood: 'Bourgone',
    description: 'A stylish and practical apartment-hotel located just steps away from the iconic Hassan II Mosque. It offers spacious, self-catering studios and apartments with modern amenities, making it the perfect choice for families or long-stay travelers who want to be near the city’s greatest landmark.',
    pricePerNight: 85,
    lifestyle: 'balanced',
    amenities: ['Fully Equipped Kitchenettes', 'Panoramic Rooftop Terrace', 'Fitness Center', 'On-Site Restaurant', 'Wifi', 'AC'],
    googleRating: 4.2,
    googleReviewCount: 3200,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 1800,
    bookingRating: 4.1,
    bookingReviewCount: 4000,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 600,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ['family', 'friends', 'solo', 'business-friendly'],
    tip: 'Request a "Mosque View" studio on the higher floors—the view of the minaret lit up at night is absolutely magical.',
    vibeTags: ['Practical', 'Spacious', 'Scenic', 'Convenient'],
    locationSummary: "City Center & Gauthier Business District",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Melliber+Appart+Hotel/@33.6015,-7.6245,17z](https://www.google.com/maps/place/Melliber+Appart+Hotel/@33.6015,-7.6245,17z)',
    address: '138 Boulevard Moulay Youssef, Casablanca 20000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Created to bridge the gap between a luxury hotel and a private home, Melliber focuses on providing independence and comfort for travelers visiting the spiritual heart of Casablanca.',
    neighborhoodOverview: 'Bourgone is a vibrant residential district that stretches towards the ocean, offering local markets and a direct connection to the coastal Corniche.',
    hiddenFeesNotice: 'City tax of 28.60 MAD per person/night not included.',
    pros: ['Unbeatable proximity to Hassan II Mosque', 'Self-catering facilities are great for families', 'Excellent value for the space provided'],
    cons: ['Away from the main shopping and business districts', 'Service is more low-key than a full-scale hotel'],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.4,
      staff: 9.1,
      value: 9.6,
      comfort: 9.2,
      location: 9.8
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Secure on-site parking',
      contact: '+212 522 222 333'
    },
    roomFeatures: ['kitchenette', 'fridge', 'workspace', 'ac'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Hassan II Mosque', distance: '200m', time: '3 min walk', icon: 'mosque' },
      { label: 'Corniche', distance: '800m', time: '10 min walk', icon: 'beach' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome; apartments equipped with kitchens for families.',
    officialWebsite: '[https://melliber.com](https://melliber.com)',
    instagramHandle: '@melliberapparthotel',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'Very safe and convenient for visiting the mosque.',
      couples: 'The rooftop view at night is very romantic.',
      families: 'The kitchen was a lifesaver for our trip with children.',
      business: 'A quiet and practical alternative to standard hotels.',
      nomad: 'Good WiFi and the extra space is great for a long stay.'
    },
    coordinates: {
      lat: 33.604304,
      lng: -7.632784
    },
    tags: ["family-favorite"]
  },
  {
    id: 'c-sleep-11',
    city: 'casablanca',
    name: 'Ibis Casablanca City Center',
    type: 'hotel',
    neighborhood: 'Centre-Ville',
    description: 'A reliable, modern, and practical choice located right next to the Casa Port train station. It offers the signature Ibis "Sweet Bed" comfort and a perfect location for travelers in transit or those who want easy access to the business district and the old medina.',
    pricePerNight: 65,
    lifestyle: 'lean',
    amenities: ['Sweet Bed by Ibis', 'Modern Bistro Restaurant', 'Vibrant Bar', 'Business Corner', 'Wifi', 'AC'],
    googleRating: 4.0,
    googleReviewCount: 5000,
    tripadvisorRating: 3.5,
    tripadvisorReviewCount: 1200,
    bookingRating: 3.8,
    bookingReviewCount: 3000,
    hotelguruRating: 4.0,
    hotelguruReviewCount: 150,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ['solo', 'friends', 'business-friendly'],
    tip: 'Ideal for those arriving by the Al-Boraq high-speed train; you can walk from the platform to your room in less than 5 minutes.',
    vibeTags: ['Practical', 'Efficient', 'Modern', 'Central'],
    locationSummary: "City Center & Gauthier Business District",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Ibis+Casablanca+City+Center/@33.5985,-7.6145,17z](https://www.google.com/maps/place/Ibis+Casablanca+City+Center/@33.5985,-7.6145,17z)',
    address: 'Angle Zaid ou Hmad, Rue Sidi Belyout, Casablanca 20190, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Designed for the modern urban traveler, this Ibis property focuses on the essentials: a great night’s sleep and a perfect location in the heart of the "White City."',
    neighborhoodOverview: 'Located at the gateway to the business district, the area is bustling during the day and provides easy access to the medina and the port.',
    hiddenFeesNotice: 'City tax of 17.60 MAD per person/night not included.',
    pros: ['Unbeatable location for train travelers', 'Consistent and reliable international standards', 'Great value for a city center stay'],
    cons: ['Rooms are compact and functional', 'Can be very busy during train arrivals'],
    trustScores: {
      cleanliness: 9.2,
      safety: 9.4,
      staff: 9.1,
      value: 9.7,
      comfort: 9.0,
      location: 9.9
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Nearby public parking',
      contact: '+212 522 439 400'
    },
    roomFeatures: ['sweet-bed', 'workspace', 'soundproof-windows', 'ac'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Casa Port Station', distance: '50m', time: '1 min walk', icon: 'train' },
      { label: 'Old Medina', distance: '300m', time: '4 min walk', icon: 'city' }
    ],
    cancellationPolicy: 'Flexible 24h',
    childPolicy: 'Children welcome; baby cots available on request.',
    officialWebsite: '[https://all.accor.com/hotel/7041/index.en.shtml](https://all.accor.com/hotel/7041/index.en.shtml)',
    instagramHandle: '@ibiscasablanca',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'Extremely safe and convenient for a solo business traveler.',
      couples: 'Great for a quick and budget-friendly city stay.',
      families: 'A bit small for families, but very central.',
      business: 'The best choice for those using the high-speed train.',
      nomad: 'Good WiFi in the lobby and very central for exploring.'
    },
    coordinates: {
      lat: 33.598617,
      lng: -7.613284
    },
    tags: ["family-favorite"]
  },
  {
    id: 'c-sleep-12',
    city: 'casablanca',
    name: 'Riad Jnane Sherazade',
    type: 'riad',
    neighborhood: 'Habous',
    description: 'One of the few authentic riad experiences in Casablanca, nestled in the charming and traditional Habous quarter. It offers a peaceful courtyard, traditional Moroccan decor, and a sense of history that is rare in this modern metropolis.',
    pricePerNight: 95,
    lifestyle: 'balanced',
    amenities: ['Traditional Central Patio', 'Homemade Moroccan Breakfast', 'Historic Quarter Location', 'Personalized Service', 'Wifi', 'AC'],
    googleRating: 4.5,
    googleReviewCount: 600,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 200,
    bookingRating: 4.6,
    bookingReviewCount: 400,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 80,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ['couple', 'solo', 'seniors'],
    tip: 'Habous is famous for its bakeries—ask the riad staff where to find the best "Corne de Gazelle" cookies nearby.',
    vibeTags: ['Authentic', 'Quiet', 'Historic', 'Charming'],
    locationSummary: "City Center & Gauthier Business District",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Riad+Jnane+Sherazade/@33.5785,-7.6045,17z](https://www.google.com/maps/place/Riad+Jnane+Sherazade/@33.5785,-7.6045,17z)',
    address: '8 Rue de la Mosquée, Habous, Casablanca 20000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Built to provide a true Moroccan sanctuary within the modern architecture of the city, this riad preserves the craftsmanship and hospitality of a bygone era.',
    neighborhoodOverview: 'Habous (The New Medina) was built in the early 20th century to look like an ancient Moroccan city, filled with arcades, bookshops, and olive markets.',
    hiddenFeesNotice: 'City tax of 28.60 MAD per person/night not included.',
    pros: ['Truly authentic and quiet atmosphere', 'Located in the most beautiful district of Casablanca', 'Exceptional local breakfast'],
    cons: ['Away from the business center and beach', 'No pool on-site'],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.5,
      staff: 9.8,
      value: 9.4,
      comfort: 9.2,
      location: 9.7
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '11:00',
      luggageStorage: 'Free',
      parking: 'Nearby public parking',
      contact: '+212 522 334 455'
    },
    roomFeatures: ['traditional-zellige', 'cedar-wood', 'quiet-location', 'ac'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Habous Olive Market', distance: '200m', time: '3 min walk', icon: 'shopping' },
      { label: 'Royal Palace', distance: '500m', time: '7 min walk', icon: 'castle' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome but best suited for families with older kids.',
    officialWebsite: '[https://riadjnanesherazade.com](https://riadjnanesherazade.com)',
    instagramHandle: '@riadjnanesherazade',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A safe and incredibly authentic home base for a solo history lover.',
      couples: 'The history and the quiet courtyard made it very special for us.',
      families: 'Better suited for older children who will appreciate the history.',
      business: 'A refreshing and quiet alternative to corporate hotels.',
      nomad: 'The courtyard is an inspiring and quiet place for remote work.'
    },
    coordinates: {
      lat: 33.698302,
      lng: -7.388962
    },
    tags: ["heritage"]
  },
  {
    id: 'c-sleep-13',
    city: 'casablanca',
    name: 'Riad 21',
    type: 'riad',
    neighborhood: 'Oasis',
    description: 'A cozy traditional guesthouse offering an intimate escape from the bustling city center. Located in the quiet, green Oasis district, it features a lush garden and a warm, family-like atmosphere that feels miles away from the urban noise.',
    pricePerNight: 105,
    lifestyle: 'balanced',
    amenities: ['Lush Private Garden', 'Traditional Moroccan Restaurant', 'Quiet Residential Setting', 'Wifi', 'AC'],
    googleRating: 4.3,
    googleReviewCount: 350,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 120,
    bookingRating: 4.2,
    bookingReviewCount: 200,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 40,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['couple', 'seniors', 'solo'],
    tip: 'Enjoy a slow dinner in their garden—it’s one of the quietest and most relaxing dining spots in the entire city.',
    vibeTags: ['Intimate', 'Green', 'Quiet', 'Homey'],
    locationSummary: "City Center & Gauthier Business District",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Riad+21/@33.5685,-7.6345,17z](https://www.google.com/maps/place/Riad+21/@33.5685,-7.6345,17z)',
    address: '21 Rue de la Meuse, Oasis, Casablanca 20000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Designed as a family home that opens its doors to the world, Riad 21 emphasizes the simple pleasures of Moroccan hospitality and domestic life.',
    neighborhoodOverview: 'Oasis is one of Casablanca’s most peaceful residential districts, known for its greenery and its direct connection to the tramway line.',
    hiddenFeesNotice: 'City tax of 28.60 MAD per person/night not included.',
    pros: ['Very quiet and green environment', 'Warm and personalized service', 'Great value for a high-quality stay'],
    cons: ['Requires a taxi or tram to reach the city center', 'No swimming pool'],
    trustScores: {
      cleanliness: 9.5,
      safety: 9.9,
      staff: 9.8,
      value: 9.4,
      comfort: 9.3,
      location: 8.5
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '11:00',
      luggageStorage: 'Free',
      parking: 'Secure street parking',
      contact: '+212 522 223 344'
    },
    roomFeatures: ['garden-views', 'traditional-carpets', 'quiet-location', 'ac'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Tramway Station Oasis', distance: '400m', time: '5 min walk', icon: 'train' },
      { label: 'Technopark', distance: '1.5km', time: '5 min drive', icon: 'business' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome; family rooms available.',
    officialWebsite: '[https://riad21.com](https://riad21.com)',
    instagramHandle: '@riad21casablanca',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A very safe and quiet sanctuary for a solo traveler.',
      couples: 'The garden dinners are very romantic and peaceful.',
      families: 'Great for families who want a quiet home-base.',
      business: 'A refreshing and quiet alternative to business hotels.',
      nomad: 'The garden is a dream for quiet afternoon work.'
    },
    coordinates: {
      lat: 33.551677,
      lng: -7.610422
    },
    tags: []
  },
  {
    id: 'c-sleep-14',
    city: 'casablanca',
    name: 'Pestana Casablanca',
    type: 'hotel',
    neighborhood: 'Ain Diab',
    description: 'A modern all-suite hotel located within the prestigious Anfa Place development. It offers spacious apartments with kitchenettes and direct access to the beachfront promenade, combining the luxury of a 4-star hotel with the independence of private living.',
    pricePerNight: 140,
    lifestyle: 'premium',
    amenities: ['Direct Beach Access', 'Outdoor Swimming Pool', 'Fully Equipped Kitchenettes', 'Adjacent Luxury Mall', 'Wifi', 'AC'],
    googleRating: 4.2,
    googleReviewCount: 1900,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 800,
    bookingRating: 4.1,
    bookingReviewCount: 1500,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 120,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['family', 'couple', 'business-friendly'],
    tip: 'The direct access to Anfa Place Mall means you have dozens of dining and shopping options literally at your doorstep.',
    vibeTags: ['Beachfront', 'Spacious', 'Convenient', 'Modern'],
    locationSummary: "City Center & Gauthier Business District",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Pestana+Casablanca/@33.5985,-7.6622,17z](https://www.google.com/maps/place/Pestana+Casablanca/@33.5985,-7.6622,17z)',
    address: 'Anfa Place, Boulevard de la Corniche, Casablanca 20000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Portuguese'],
    customStory: 'As part of the Portuguese Pestana group, this hotel brings a relaxed Atlantic resort vibe to the heart of Morocco’s largest city.',
    neighborhoodOverview: 'Ain Diab is Casablanca’s premier entertainment and coastal district, famous for its beach clubs, restaurants, and the scenic promenade.',
    hiddenFeesNotice: 'City tax of 28.60 MAD per person/night not included.',
    pros: ['Excellent beachfront location', 'Large suites with kitchens', 'Great for families and long stays'],
    cons: ['Can be busy and loud on weekends', 'Service can feel a bit decentralized'],
    trustScores: {
      cleanliness: 9.4,
      safety: 9.8,
      staff: 9.1,
      value: 8.9,
      comfort: 9.5,
      location: 9.7
    },
    logistics: {
      checkIn: '15:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Secure on-site parking',
      contact: '+212 522 797 010'
    },
    roomFeatures: ['kitchenette', 'ocean-side-balcony', 'separate-living-area', 'ac'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Anfa Place Mall', distance: '50m', time: '1 min walk', icon: 'shopping' },
      { label: 'Corniche', distance: '0m', time: 'In-front', icon: 'beach' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children stay free using existing bedding.',
    officialWebsite: '[https://www.pestana.com/en/hotel/pestana-casablanca](https://www.pestana.com/en/hotel/pestana-casablanca)',
    instagramHandle: '@pestanacasablanca',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'Very safe and spacious for a solo work trip.',
      couples: 'The beach access and the pool made it a great getaway.',
      families: 'The best choice for families in Casablanca—lots of space and easy food.',
      business: 'Excellent WiFi and practical for long-term business stays.',
      nomad: 'The extra space and proximity to the mall make it a perfect "workation" spot.'
    },
    coordinates: {
      lat: 33.597788,
      lng: -7.666643
    },
    tags: ["family-favorite"]
  },
  {
    id: 'c-sleep-15',
    city: 'casablanca',
    name: 'JM Suites Hotel',
    type: 'hotel',
    neighborhood: 'Gauthier',
    description: 'An eco-friendly boutique hotel combining modern luxury with a commitment to sustainability. Located in the heart of the artistic Gauthier district, it offers spacious suites with contemporary design, organic spa treatments, and one of the best rooftop bars for the city’s creative crowd.',
    pricePerNight: 115,
    lifestyle: 'balanced',
    amenities: ['Eco-Certified Luxury Spa', 'Artistic Rooftop Bar', 'Organic Gourmet Restaurant', 'Fitness Center', 'Wifi', 'AC'],
    googleRating: 4.4,
    googleReviewCount: 850,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 400,
    bookingRating: 4.3,
    bookingReviewCount: 600,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 100,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['couple', 'solo', 'business-friendly'],
    tip: 'The "La Bodega" bar downstairs is a Casablanca institution for live music and a vibrant local atmosphere.',
    vibeTags: ['Eco-Luxe', 'Artistic', 'Modern', 'Social'],
    locationSummary: "City Center & Gauthier Business District",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/JM+Suites+Hotel/@33.5875,-7.6225,17z](https://www.google.com/maps/place/JM+Suites+Hotel/@33.5875,-7.6225,17z)',
    address: '161 Angle Boulevard Rachidi & Moulay Hassan I, Casablanca 20070, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Built with a vision of "responsible luxury," JM Suites was one of the first hotels in Casablanca to integrate sustainable practices without compromising on style.',
    neighborhoodOverview: 'Gauthier is the center of Casablanca’s creative life, filled with art galleries, boutique shops, and the city’s most interesting international restaurants.',
    hiddenFeesNotice: 'City tax of 28.60 MAD per person/night not included.',
    pros: ['Excellent eco-friendly philosophy', 'One of the best rooftop atmospheres in the city', 'Spacious and very well-designed suites'],
    cons: ['No swimming pool', 'Can be lively and loud at night due to the bar'],
    trustScores: {
      cleanliness: 9.7,
      safety: 9.8,
      staff: 9.6,
      value: 9.2,
      comfort: 9.4,
      location: 9.9
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Secure valet parking',
      contact: '+212 522 222 222'
    },
    roomFeatures: ['eco-friendly-materials', 'separate-seating', 'workspace', 'ac'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Villa des Arts', distance: '400m', time: '5 min walk', icon: 'art' },
      { label: 'Twin Center', distance: '700m', time: '9 min walk', icon: 'building' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome; extra beds available in suites for a fee.',
    officialWebsite: '[https://jmsuiteshotel.com](https://jmsuiteshotel.com)',
    instagramHandle: '@jmsuiteshotel',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A safe and incredibly stylish haven in the best part of the city.',
      couples: 'The rooftop bar is perfect for a romantic evening.',
      families: 'The suites are spacious and great for older children.',
      business: 'Excellent location and very reliable service.',
      nomad: 'Fast internet and great social vibes at the rooftop bar.'
    },
    coordinates: {
      lat: 33.592352,
      lng: -7.625553
    },
    tags: []
  },
  {
    id: 'c-sleep-16',
    city: 'casablanca',
    name: 'Odyssee Boutique Hotel',
    type: 'hotel',
    neighborhood: 'Centre-Ville',
    description: 'A chic and artistic boutique hotel that offers a creative alternative to Casablanca’s larger corporate hotels. It features eclectic interior design, a beautiful library lounge, and a refined atmosphere in the heart of the city.',
    pricePerNight: 95,
    lifestyle: 'balanced',
    amenities: ['Artistic Library Lounge', 'Gourmet Bistro', 'Boutique Design', 'Personalized Concierge', 'Wifi', 'AC'],
    googleRating: 4.6,
    googleReviewCount: 1100,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 600,
    bookingRating: 4.5,
    bookingReviewCount: 1500,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 200,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ['couple', 'solo'],
    tip: 'Spend an hour in the library lounge—it’s one of the quietest and most inspiring spots in downtown Casablanca.',
    vibeTags: ['Artistic', 'Chic', 'Intimate', 'Central'],
    locationSummary: "City Center & Gauthier Business District",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Odyssee+Boutique+Hotel/@33.5955,-7.6145,17z](https://www.google.com/maps/place/Odyssee+Boutique+Hotel/@33.5955,-7.6145,17z)',
    address: 'Angle Rue Kamal Mohamed, Rue de l’Aisne, Casablanca 20000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Conceived as an "urban journey," Odyssee was designed to provide travelers with a sense of discovery and creative inspiration through its unique decor.',
    neighborhoodOverview: 'Located in the historic center, the hotel is perfectly positioned between the corporate towers and the artisan alleys of the old medina.',
    hiddenFeesNotice: 'City tax of 28.60 MAD per person/night not included.',
    pros: ['Exceptional and unique design', 'Quiet and personalized service', 'Perfect central location'],
    cons: ['No swimming pool', 'Rooms are stylish but not oversized'],
    trustScores: {
      cleanliness: 9.7,
      safety: 9.6,
      staff: 9.8,
      value: 9.4,
      comfort: 9.3,
      location: 9.8
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Nearby public parking',
      contact: '+212 522 456 100'
    },
    roomFeatures: ['artistic-decor', 'premium-linens', 'quiet-location', 'ac'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Casa Port Station', distance: '400m', time: '5 min walk', icon: 'train' },
      { label: 'Old Medina', distance: '300m', time: '4 min walk', icon: 'city' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome; baby cots available.',
    officialWebsite: '[https://odyssee-boutique-hotel.com](https://odyssee-boutique-hotel.com)',
    instagramHandle: '@odysseecasablanca',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A safe and incredibly stylish haven for a solo traveler.',
      couples: 'The decor and the library lounge were very romantic.',
      families: 'Better suited for couples or solo travelers.',
      business: 'A refreshing and quiet alternative to corporate hotels.',
      nomad: 'The library is a dream for quiet work sessions.'
    },
    coordinates: {
      lat: 33.593196,
      lng: -7.640998
    },
    tags: []
  },
  {
    id: 'c-sleep-17',
    city: 'casablanca',
    name: 'Oum Palace Hotel & Spa',
    type: 'hotel',
    neighborhood: 'Centre-Ville',
    description: 'A traditional 4-star hotel conveniently situated right by the ancient medina walls and the Casa Port train station. It offers a blend of classic Moroccan hospitality and modern comforts, featuring an extensive spa and a restaurant known for its authentic Fassi and international cuisine.',
    pricePerNight: 75,
    lifestyle: 'balanced',
    amenities: ['Traditional Moroccan Spa', 'Authentic Fassi Restaurant', 'Central Business Location', 'Wifi', 'AC'],
    googleRating: 4.0,
    googleReviewCount: 2200,
    tripadvisorRating: 3.5,
    tripadvisorReviewCount: 1000,
    bookingRating: 3.8,
    bookingReviewCount: 3000,
    hotelguruRating: 4.0,
    hotelguruReviewCount: 300,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ['solo', 'couple', 'business-friendly'],
    tip: 'Perfect for those who want to be within walking distance of both the modern business district and the artisan markets of the old medina.',
    vibeTags: ['Classic', 'Central', 'Traditional', 'Convenient'],
    locationSummary: "City Center & Gauthier Business District",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Oum+Palace+Hotel+%26+Spa/@33.5955,-7.6145,17z](https://www.google.com/maps/place/Oum+Palace+Hotel+%26+Spa/@33.5955,-7.6145,17z)',
    address: '12 Rue Sidi Belyout, Casablanca 20000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Built to offer a "palace-like" experience for the everyday traveler, Oum Palace emphasizes the richness of Moroccan heritage in a practical city center setting.',
    neighborhoodOverview: 'The area is a melting pot of old and new, where the bustling commercial life of Casablanca meets the timeless traditions of the medina.',
    hiddenFeesNotice: 'City tax of 17.60 MAD per person/night not included.',
    pros: ['Excellent value for a central 4-star stay', 'Great proximity to the medina and train station', 'Authentic and warm Moroccan service'],
    cons: ['Interior decor is more traditional than modern', 'Can be noisy during peak business hours'],
    trustScores: {
      cleanliness: 9.1,
      safety: 9.3,
      staff: 9.4,
      value: 9.5,
      comfort: 8.9,
      location: 9.8
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Secure on-site parking',
      contact: '+212 522 201 100'
    },
    roomFeatures: ['traditional-decor', 'workspace', 'satellite-tv', 'ac'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Old Medina', distance: '100m', time: '2 min walk', icon: 'city' },
      { label: 'Casa Port Station', distance: '400m', time: '5 min walk', icon: 'train' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children stay free using existing bedding.',
    officialWebsite: '[https://oumpalace.com](https://oumpalace.com)',
    instagramHandle: '@oumpalacehotel',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A safe and very central home base for exploring the city.',
      couples: 'The spa was a great addition to our city break.',
      families: 'Good central location and very helpful staff.',
      business: 'A practical and well-located choice for work trips.',
      nomad: 'Good WiFi and the central location makes it easy to work and explore.'
    },
    coordinates: {
      lat: 33.596253,
      lng: -7.614328
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: 'c-sleep-18',
    city: 'casablanca',
    name: 'Suite Hotel Casa Diamond',
    type: 'hotel',
    neighborhood: 'Gauthier',
    description: 'A luxurious all-suite hotel overlooking the lush Parc de la Ligue Arabe. It offers some of the most spacious and modern accommodations in the city, with a focus on high-end business services and a quiet, prestigious atmosphere.',
    pricePerNight: 125,
    lifestyle: 'premium',
    amenities: ['Panoramic Fitness Center', 'Executive Dining Room', 'Lush Park Views', 'Luxury Spa Treatments', 'Wifi', 'AC'],
    googleRating: 4.7,
    googleReviewCount: 1500,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 900,
    bookingRating: 4.6,
    bookingReviewCount: 2000,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 400,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['couple', 'family', 'business-friendly'],
    tip: 'Take a morning stroll in the Arab League Park right across the street—it’s the most beautiful green space in Casablanca.',
    vibeTags: ['Prestigious', 'Spacious', 'Modern', 'Quiet'],
    locationSummary: "City Center & Gauthier Business District",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Suite+Hotel+Casa+Diamond/@33.5875,-7.6245,17z](https://www.google.com/maps/place/Suite+Hotel+Casa+Diamond/@33.5875,-7.6245,17z)',
    address: 'Angle Avenue Hassan II et Rue Osmane Ben Affane, Casablanca 20000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Named for its sparkling glass architecture, Casa Diamond was built to be a modern gem in the heart of Casablanca’s residential and business districts.',
    neighborhoodOverview: 'Located in the upscale Gauthier district, providing a quiet and prestigious atmosphere with easy access to the city’s best boulevards.',
    hiddenFeesNotice: 'City tax of 28.60 MAD per person/night not included.',
    pros: ['Enormous and beautifully designed suites', 'Stunning views over the Arab League Park', 'Exceptional service and security'],
    cons: ['No swimming pool', 'Away from the coastal corniche'],
    trustScores: {
      cleanliness: 9.8,
      safety: 9.9,
      staff: 9.7,
      value: 9.1,
      comfort: 9.6,
      location: 9.8
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Secure valet parking',
      contact: '+212 522 222 333'
    },
    roomFeatures: ['floor-to-ceiling-windows', 'separate-living-area', 'luxury-bathrooms', 'ac'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Arab League Park', distance: '100m', time: '1 min walk', icon: 'park' },
      { label: 'Twin Center', distance: '800m', time: '10 min walk', icon: 'building' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children stay free; extra beds available in suites.',
    officialWebsite: '[https://casadiamond.com](https://casadiamond.com)',
    instagramHandle: '@casadiamond',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'Extremely safe and spacious for a solo business traveler.',
      couples: 'The park view and the suites are very romantic.',
      families: 'The extra space and the park nearby are perfect for kids.',
      business: 'The best business suites in Casablanca.',
      nomad: 'Fast internet and incredible views to work from.'
    },
    coordinates: {
      lat: 33.585698,
      lng: -7.622651
    },
    tags: ["family-favorite"]
  },
  {
    id: 'c-sleep-19',
    city: 'casablanca',
    name: 'Down Town Hotel By BLH',
    type: 'hotel',
    neighborhood: 'Maarif',
    description: 'A vibrant and modern boutique experience in the shopping heart of Casablanca. It features stylish apartments with kitchenettes, sleek contemporary design, and a prime location for those who want to be in the middle of the city’s best fashion and dining scene.',
    pricePerNight: 115,
    lifestyle: 'balanced',
    amenities: ['Stylish Kitchenettes', 'Modern Fitness Center', 'Maarif Shopping Access', 'High-Speed Wifi', 'AC'],
    googleRating: 4.6,
    googleReviewCount: 900,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 500,
    bookingRating: 4.5,
    bookingReviewCount: 1200,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 150,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['couple', 'friends', 'solo', 'business-friendly'],
    tip: 'The surrounding Maarif streets are filled with the best local boutiques and cafes—perfect for an afternoon of exploring and people-watching.',
    vibeTags: ['Vibrant', 'Modern', 'Social', 'Central'],
    locationSummary: "City Center & Gauthier Business District",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Down+Town+Hotel+By+Business+%26+Leisure+Hotels/@33.5855,-7.6325,17z](https://www.google.com/maps/place/Down+Town+Hotel+By+Business+%26+Leisure+Hotels/@33.5855,-7.6325,17z)',
    address: '14 Rue El Kadi Iass, Maarif, Casablanca 20100, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Created to cater to the "urban nomad," Down Town Hotel focuses on the intersection of style, convenience, and the vibrant energy of Casablanca’s commercial heart.',
    neighborhoodOverview: 'Maarif is the fashion and shopping capital of Casablanca, home to the Twin Center and a high-energy mix of international and local brands.',
    hiddenFeesNotice: 'City tax of 28.60 MAD per person/night not included.',
    pros: ['Excellent location for shopping and dining', 'Very modern and well-designed apartments', 'High-speed internet and great for remote work'],
    cons: ['No swimming pool', 'Can be lively and loud due to the busy neighborhood'],
    trustScores: {
      cleanliness: 9.7,
      safety: 9.9,
      staff: 9.6,
      value: 9.2,
      comfort: 9.4,
      location: 9.9
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Nearby public parking',
      contact: '+212 522 987 654'
    },
    roomFeatures: ['modern-kitchenette', 'balcony', 'high-speed-wifi', 'ac'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Twin Center', distance: '300m', time: '4 min walk', icon: 'building' },
      { label: 'Maarif Market', distance: '500m', time: '6 min walk', icon: 'shopping' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children stay free using existing bedding.',
    officialWebsite: '[https://blh-hotels.com/down-town-hotel/](https://blh-hotels.com/down-town-hotel/)',
    instagramHandle: '@downtownhotelcasa',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A safe and incredibly vibrant home base for a solo shopping trip.',
      couples: 'The neighborhood energy and the modern rooms were perfect.',
      families: 'Great for families who want a modern and central base.',
      business: 'Excellent WiFi and very practical for work trips.',
      nomad: 'The best spot in Casa for a "workation"—fast internet and great cafes nearby.'
    },
    coordinates: {
      lat: 33.586168,
      lng: -7.636068
    },
    tags: ["family-favorite"]
  },
  {
    id: 'c-sleep-20',
    city: 'casablanca',
    name: 'Auberge de Jeunesse Casablanca',
    type: 'hostel',
    neighborhood: 'Old Medina',
    description: 'A bustling hub for backpackers and young travelers, located near the Casa Port station and the medina entrance. It features colorful murals, a vibrant communal rooftop terrace, and a friendly atmosphere that makes it the perfect starting point for exploring Morocco.',
    pricePerNight: 18,
    lifestyle: 'lean',
    amenities: ['Vibrant Rooftop Terrace', 'Shared Communal Kitchen', 'Cultural Workshops', 'Wifi', 'Locker storage'],
    googleRating: 4.1,
    googleReviewCount: 450,
    tripadvisorRating: 3.5,
    tripadvisorReviewCount: 200,
    bookingRating: 3.8,
    bookingReviewCount: 800,
    hotelguruRating: 4.1,
    hotelguruReviewCount: 50,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: false,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 3,
    groupTypes: ['solo', 'friends'],
    tip: 'A great place to meet fellow travelers before heading out to the desert or Marrakech; check the community board for shared taxi offers.',
    vibeTags: ['Social', 'Budget-Friendly', 'Central', 'Vibrant'],
    locationSummary: "City Center & Gauthier Business District",
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Auberge+de+Jeunesse+Casablanca/@33.5975,-7.6165,17z](https://www.google.com/maps/place/Auberge+de+Jeunesse+Casablanca/@33.5975,-7.6165,17z)',
    address: '6 Place Ahmed el Bidaoui, Old Medina, Casablanca 20000, Morocco',
    paymentMethods: ['cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Part of the International Youth Hostel Federation, this hostel has been a cornerstone of Casablanca’s budget travel scene for decades.',
    neighborhoodOverview: 'Located at the edge of the historic medina, providing an easy entry into the local way of life while being close to the main transport hubs.',
    hiddenFeesNotice: 'City tax of 15 MAD per person/night not included.',
    pros: ['Very affordable and social', 'Excellent central location', 'Great rooftop for meeting people'],
    cons: ['Basic facilities', 'Medina entrance can be busy at night'],
    trustScores: {
      cleanliness: 8.0,
      safety: 8.2,
      staff: 9.3,
      value: 9.8,
      comfort: 7.2,
      location: 9.6
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '11:00',
      luggageStorage: 'Free',
      parking: 'Nearby public parking',
      contact: '+212 522 220 551'
    },
    roomFeatures: ['bunk-beds', 'shared-bathrooms', 'communal-space', 'lockers'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Casa Port Station', distance: '300m', time: '4 min walk', icon: 'train' },
      { label: 'Hassan II Mosque', distance: '1.8km', time: '20 min walk', icon: 'mosque' }
    ],
    cancellationPolicy: 'Flexible 24h',
    childPolicy: 'Children stay free using existing bedding; age restrictions in dorms.',
    officialWebsite: '[https://moroccanhostels.com/hostels/casablanca](https://moroccanhostels.com/hostels/casablanca)',
    instagramHandle: '@casahostel',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'Extremely easy to meet people and felt very safe.',
      couples: 'Good for a quick and very cheap city stay.',
      families: 'Not recommended for families.',
      business: 'Only for the very budget-conscious business traveler.',
      nomad: 'Good social vibes, but the WiFi can be busy in the evenings.'
    },
    coordinates: {
      lat: 33.582028,
      lng: -7.619518
    },
    tags: ["dorm"]
  }
]
