import type { SleepListing } from '../types'

/**
 * SLEEP LISTING DATA TEMPLATE (Copy this for your search agent)
 * -------------------------------------------------------------
 * {
 *   "id": "city-sleep-XX",
 *   "name": "",
 *   "type": "riad | hotel | villa | hostel | apartment | guesthouse",
 *   "neighborhood": "",
 *   "city": "[city]",
 *   "description": "",
 *   "pricePerNight": 0,
 *   "lifestyle": "lean | balanced | premium",
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2', 'url3']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source (replaces single rating/reviewCount)
 *   // ═══════════════════════════════════════════════════
 *   // Search for real ratings from Google, TripAdvisor, Booking.com, and HotelGuru.
 *   // If you cannot find a rating for a specific source, set it to the same value as
 *   // the closest available one so average calculations don't break.
 *
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *   bookingRating: [4.x],
 *   bookingReviewCount: [number],
 *   hotelguruRating: [4.x],
 *   hotelguruReviewCount: [number],
 *
 *   // ═══════════════════════════════════════════════════
 *   // BOOLEAN AMENITIES
 *   // ═══════════════════════════════════════════════════
 *
 *   hasPool: true | false,
 *   hasBreakfast: true | false,
 *   hasAC: true | false,
 *   hasHeating: true | false,
 *   hasRooftop: true | false,
 *   hasEnsuite: true | false,
 *   hasRestaurant: true | false,
 *   hasBar: true | false,
 *   hasGym: true | false,
 *   hasElevator: true | false,
 *   hasLaundryService: true | false,
 *   hasRoomService: true | false,
 *   petFriendly: true | false,
 *   isWheelchairAccessible: true | false,
 *   taxesIncluded: true | false,
 *   freeCancellation: true | false,
 *   kidsStayFree: true | false,
 *
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearMosque: true | false,
 *   safetyLevel: 1 | 2 | 3 | 4 | 5,
 *
 *   // ═══════════════════════════════════════════════════
 *   // TRUST SCORES
 *   // ═══════════════════════════════════════════════════
 *
 *   trustScores: {
 *     cleanliness: [1-10],
 *     safety: [1-10],
 *     staff: [1-10],
 *     value: [1-10],
 *     comfort: [1-10],
 *     location: [1-10]
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   amenities: ['wifi', 'pool', 'ac', 'breakfast', 'spa', 'restaurant', 'gym', 'kitchenette', 'parking', 'bar', 'laundry', 'elevator', 'room-service'],
 *   tip: '[Short insider tip]',
 *   vibeTags: ['Authentic', 'Quiet', 'Modern'],
 *   locationSummary: 'Beachfront | City Center | Medina | Airport Area | Residential | Tourist Zone',
 *   availabilityText: 'Available tonight | Only 2 rooms left | Available on selected dates',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   address: '[Full street address, City, Postal Code, Morocco]',
 *
 *   paymentMethods: ['card', 'cash'],
 *   languagesSpoken: ['Arabic', 'French', 'English', 'Spanish', 'German'],
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   customStory: 'Brief history, owner background, or architecture notes...',
 *   neighborhoodOverview: 'Description of the local atmosphere, safety, and vibe...',
 *   hiddenFeesNotice: 'City tax of XX MAD per person/night not included...',
 *   pros: ['Pro 1', 'Pro 2'],
 *   cons: ['Con 1'],
 *
 *   // ═══════════════════════════════════════════════════
 *   // LOGISTICS
 *   // ═══════════════════════════════════════════════════
 *
 *   logistics: {
 *     checkIn: '14:00 - 22:00',
 *     checkOut: 'Before 11:00',
 *     luggageStorage: 'Free | Paid | None',
 *     parking: 'Free on-site | Nearby public | Valet',
 *     contact: '+212 XXXXXXXXX'
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *   // ROOM FEATURES & TYPES
 *   // ═══════════════════════════════════════════════════
 *
 *   roomFeatures: ['soundproof', 'workspace', 'private-balcony', 'ac', 'heating', 'balcony', 'shower-ensuite', 'sea-view', 'garden-view', 'pool-view'],
 *   roomTypes: [
 *     {
 *       name: 'Double Room',
 *       price: 500,
 *       beds: '1 Queen',
 *       size: '20m2',
 *     }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *   // NEIGHBORHOOD DISTANCES
 *   // ═══════════════════════════════════════════════════
 *
 *   neighborhoodDistances: [
 *     { label: 'Beach', distance: '500m', time: '5 min walk', icon: 'beach' }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   cancellationPolicy: 'Free cancellation up to 24h before check-in | Flexible | Non-refundable',
 *   childPolicy: 'Children welcome | Free under 6 | Extra bed 200 MAD',
 *   officialWebsite: 'https://...',
 *   instagramHandle: '@...',
 *
 *   // googlePlaceId: "PLACE_ID_HERE",
 *
 *   // ═══════════════════════════════════════════════════
 *   // REVIEW HIGHLIGHTS
 *   // ═══════════════════════════════════════════════════
 *
 *   reviewHighlights: {
 *     solo: 'Great insight for solo...',
 *     couples: 'Great for couples...',
 *     families: 'Kid-friendly details...',
 *     business: 'Wi-Fi test details...',
 *     nomad: 'Remote work specific insight...'
 *   }
 * }
 */

export const chefchaouenSleep: SleepListing[] = [
  {
    id: 'ch-sleep-1',
    city: 'chefchaouen',
    name: 'Lina Ryad & Spa',
    type: 'riad',
    neighborhood: 'Medina',
    description: 'A top-tier luxury riad in the heart of the blue medina featuring an indoor pool, traditional hammam, and panoramic rooftop views. One of the most celebrated and serene stays in Chefchaouen.',
    pricePerNight: 120,
    lifestyle: 'premium',
    amenities: ['Indoor Heated Pool', 'Traditional Hammam', 'Panoramic Rooftop', 'Spa Treatments'],
    googleRating: 4.8,
    googleReviewCount: 350,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 150,
    bookingRating: 4.9,
    bookingReviewCount: 200,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 50,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['couple', 'family', 'seniors', 'solo'],
    tip: 'The indoor pool is a rare luxury in the medina and is heated year-round—perfect after a day of hiking the Rif.',
    vibeTags: ['Boutique', 'Serene', 'Luxe', 'Blue-Washed'],
    locationSummary: 'Medina',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Lina+Ryad+%26+Spa/@35.1691,-5.2635,17z](https://www.google.com/maps/place/Lina+Ryad+%26+Spa/@35.1691,-5.2635,17z)',
    address: 'Avenue Hassan I, Chefchaouen 91000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Lina Ryad was founded to provide a level of luxury and wellness previously unavailable in the traditional Chefchaouen medina houses.',
    neighborhoodOverview: 'The blue medina is highly walkable, photogenic, and generally safe, with steep cobbled lanes, small craft shops, and calm evenings around the upper alleys.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Exceptional indoor pool and spa', 'Peaceful atmosphere', 'Spacious and stylish suites'],
    cons: ['Requires walking through medina alleys (luggage assistance available)', 'Higher price point for the area'],
    trustScores: {
      cleanliness: 9.8,
      safety: 9.7,
      staff: 9.6,
      value: 8.8,
      comfort: 9.7,
      location: 9.8
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Public parking nearby (Ras el Ma)',
      contact: '+212 539 986 024'
    },
    roomFeatures: ['traditional-decor', 'rooftop-access', 'ac', 'heating', 'shower-ensuite', 'mountain-view'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Outa el Hammam Square', distance: '200m', time: '3 min walk', icon: 'city' },
      { label: 'Ras el Ma Waterfall', distance: '800m', time: '10 min walk', icon: 'nature' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://www.linaryad.com](https://www.linaryad.com)',
    instagramHandle: '@linaryadspa',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A safe, calm, and luxurious base for exploring the town.',
      couples: 'The rooftop views at sunset are unforgettable.',
      families: 'The indoor pool is a huge hit with children.',
      business: 'Quiet rooms and reliable WiFi for focused work sessions.',
      nomad: 'A serene medina base with spa breaks and calm corners for remote work.'
    }
  },
  {
    id: 'ch-sleep-2',
    city: 'chefchaouen',
    name: "Dar Echchaouen Maison d'hôtes & Riad",
    type: 'riad',
    neighborhood: 'Ras el Ma',
    description: 'A charming guesthouse located near the Ras el Ma spring, offering a more traditional and rustic experience with a lovely garden and outdoor pool. Known for its warm hospitality and authentic atmosphere.',
    pricePerNight: 85,
    lifestyle: 'balanced',
    amenities: ['Outdoor Pool', 'Garden', 'Restaurant', 'Traditional Breakfast'],
    googleRating: 4.7,
    googleReviewCount: 1800,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 800,
    bookingRating: 4.8,
    bookingReviewCount: 1000,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 200,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['couple', 'family', 'friends', 'solo'],
    tip: 'Ask for a room in the newer part of the riad for more space, though the original house has more historical charm.',
    vibeTags: ['Authentic', 'Charming', 'Garden-Set', 'Welcoming'],
    locationSummary: 'Ras el Ma - Medina Edge',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Dar+Echchaouen+Maison+d\'h%C3%B4tes+%26+Riad/@35.1685,-5.2586,17z](https://www.google.com/maps/place/Dar+Echchaouen+Maison+d\'h%C3%B4tes+%26+Riad/@35.1685,-5.2586,17z)',
    address: 'Ras el Ma, Chefchaouen 91000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Dar Echchaouen was one of the first traditional houses converted into a guesthouse in the area, preserving the authentic Rifian style of living.',
    neighborhoodOverview: 'Ras el Ma sits at the upper edge of the medina near the spring and waterfall, giving easier car access, fresh mountain air, and a quieter evening atmosphere.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Beautiful garden and pool', 'Authentic local atmosphere', 'Easier car access than deep medina'],
    cons: ['Slightly uphill walk from the main square', 'Traditional style can feel a bit rustic'],
    trustScores: {
      cleanliness: 9.5,
      safety: 9.6,
      staff: 9.8,
      value: 9.2,
      comfort: 9.4,
      location: 9.5
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Public parking 50m away (Ras el Ma)',
      contact: '+212 539 986 947'
    },
    roomFeatures: ['garden-view', 'pool-view', 'ac', 'heating', 'shower-ensuite'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Ras el Ma Spring', distance: '100m', time: '2 min walk', icon: 'nature' },
      { label: 'Outa el Hammam Square', distance: '600m', time: '8 min walk', icon: 'city' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://www.darechchaouen.com](https://www.darechchaouen.com)',
    instagramHandle: '@darechchaouen',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'Very welcoming and warm staff, feels like home.',
      couples: 'The garden pool is a wonderful place to relax together.',
      families: 'The triple rooms and garden are perfect for families.',
      business: 'A peaceful environment, though WiFi is best in common areas.',
      nomad: 'Good for slower work days when you want fresh air and garden breaks.'
    }
  },
  {
    id: 'ch-sleep-3',
    city: 'chefchaouen',
    name: 'Dar Jasmine',
    type: 'guesthouse',
    neighborhood: 'Ras el Ma',
    description: 'Perched on a hillside overlooking the entire blue medina, this romantic boutique retreat offers the most iconic panoramic views in Chefchaouen. Its luxury rooms and infinity-style pool provide a serene escape from the busy streets below.',
    pricePerNight: 165,
    lifestyle: 'premium',
    amenities: ['Panoramic Infinity Pool', 'Mountain View Terrace', 'Gourmet Breakfast', 'Lush Jasmine Gardens'],
    googleRating: 4.9,
    googleReviewCount: 450,
    tripadvisorRating: 4.9,
    tripadvisorReviewCount: 200,
    bookingRating: 4.9,
    bookingReviewCount: 300,
    hotelguruRating: 4.9,
    hotelguruReviewCount: 100,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['couple', 'family', 'seniors', 'solo'],
    tip: 'The walk up the hill is steep but rewarding; luggage assistance is available from the Ras el Ma parking area. Sunset from the terrace is the best in town.',
    vibeTags: ['Panoramic', 'Romantic', 'Boutique', 'Views'],
    locationSummary: 'Hillside - Medina Views',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Dar+Jasmine/@35.1675,-5.2576,17z](https://www.google.com/maps/place/Dar+Jasmine/@35.1675,-5.2576,17z)',
    address: 'Ras el Ma, Chefchaouen 91000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Designed to be a boutique sanctuary that offers a bird\'s eye view of the "Blue Pearl," Dar Jasmine focus on romantic atmosphere and personalized service.',
    neighborhoodOverview: 'The hillside above Ras el Ma is quieter and more scenic than the center, with steep paths, sweeping views, and quick access to the Spanish Mosque hiking route.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Unbeatable panoramic views', 'Beautiful pool and gardens', 'Excellent service'],
    cons: ['Significant uphill walk (steps) from medina', 'Away from the central square'],
    trustScores: {
      cleanliness: 9.9,
      safety: 9.8,
      staff: 9.9,
      value: 8.5,
      comfort: 9.8,
      location: 9.9
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '11:00',
      luggageStorage: 'Free',
      parking: 'Public parking at Ras el Ma (3 min walk)',
      contact: '+212 539 986 444'
    },
    roomFeatures: ['mountain-view', 'city-view', 'private-balcony', 'ac', 'heating', 'shower-ensuite'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Ras el Ma Waterfall', distance: '150m', time: '3 min walk', icon: 'nature' },
      { label: 'Spanish Mosque', distance: '1.2km', time: '20 min hike', icon: 'hiking' }
    ],
    cancellationPolicy: 'Moderate 7-day',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://www.darjasmine.com](https://www.darjasmine.com)',
    instagramHandle: '@darjasmine',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A safe and breathtaking retreat for a solo soul-searching trip.',
      couples: 'The most romantic sunset spot in all of northern Morocco.',
      families: 'A wonderful base for families who enjoy the outdoors.',
      business: 'Decent WiFi and an incredibly inspiring view for work.',
      nomad: 'The panoramic terrace is an unforgettable remote-work backdrop.'
    }
  },
  {
    id: 'ch-sleep-4',
    city: 'chefchaouen',
    name: 'Riad Cherifa',
    type: 'riad',
    neighborhood: 'Medina',
    description: 'A labyrinthine luxury riad spanning multiple levels, famously nicknamed "a medina within a medina." It features a rooftop garden terrace, an outdoor pool, and immersive Moroccan craftsmanship throughout its corridors and rooms.',
    pricePerNight: 145,
    lifestyle: 'premium',
    amenities: ['Outdoor Pool', 'Rooftop Garden Terrace', 'Traditional Restaurant', 'Spa & Hammam'],
    googleRating: 4.8,
    googleReviewCount: 380,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 180,
    bookingRating: 4.9,
    bookingReviewCount: 250,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 80,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['couple', 'family', 'seniors'],
    tip: 'Don\'t miss dinner at the riad\'s restaurant — the pastilla and lamb tagine are widely considered the best in the medina. Explore every level of the riad to find hidden lounges.',
    vibeTags: ['Intricate', 'Historic', 'Grand', 'Labyrinthine'],
    locationSummary: 'Medina',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Riad+Cherifa/@35.1681,-5.2625,17z](https://www.google.com/maps/place/Riad+Cherifa/@35.1681,-5.2625,17z)',
    address: 'Place El Haouta, Chefchaouen 91000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Riad Cherifa was created by combining several historic medina houses into one grand palace, preserving the diverse architectural styles of old Chefchaouen.',
    neighborhoodOverview: 'Place El Haouta is a central medina pocket with blue lanes, small fountains, and easy access to the Kasbah while still feeling calmer than the main square.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Stunning and unique architecture', 'Very central yet peaceful', 'Exceptional food quality'],
    cons: ['Can be easy to get lost in the hallways!', 'Limited natural light in some lower rooms'],
    trustScores: {
      cleanliness: 9.7,
      safety: 9.8,
      staff: 9.7,
      value: 9.0,
      comfort: 9.6,
      location: 9.9
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Public parking at Bab el Mahrouq (5 min walk)',
      contact: '+212 539 987 555'
    },
    roomFeatures: ['traditional-decor', 'rooftop-access', 'ac', 'heating', 'shower-ensuite'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Outa el Hammam Square', distance: '150m', time: '2 min walk', icon: 'city' },
      { label: 'The Kasbah', distance: '200m', time: '3 min walk', icon: 'castle' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://www.riadcherifa.com](https://www.riadcherifa.com)',
    instagramHandle: '@riadcherifa',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A safe, majestic, and peaceful place to treat yourself.',
      couples: 'The most elegant and traditional luxury stay in the medina.',
      families: 'The suites are large enough for families and very comfortable.',
      business: 'Quiet nooks for work and reliable WiFi in the lounge.',
      nomad: 'Excellent for work breaks in hidden lounges and rooftop corners.'
    }
  },
  {
    id: 'ch-sleep-5',
    city: 'chefchaouen',
    name: 'Auberge Dardara',
    type: 'guesthouse',
    neighborhood: 'Rif Mountains',
    description: 'A legendary rural retreat located 10km outside Chefchaouen, famous for having one of the best traditional restaurants in Morocco. It offers a peaceful mountain atmosphere, an organic farm, and cozy rooms with fireplaces.',
    pricePerNight: 95,
    lifestyle: 'balanced',
    amenities: ['Acclaimed Farm-to-Table Restaurant', 'Outdoor Pool', 'Organic Farm', 'Mountain View Terrace', 'Fireplace'],
    googleRating: 4.8,
    googleReviewCount: 950,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 400,
    bookingRating: 4.7,
    bookingReviewCount: 600,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 150,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    tip: 'The food here is worth the trip alone. Their goat cheese, honey, and olive oil are all produced on-site. It is a perfect base for hiking to Akchour or God\'s Bridge.',
    vibeTags: ['Gastronomic', 'Rural', 'Peaceful', 'Authentic'],
    locationSummary: 'Rif Mountain Retreat',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Auberge+Dardara/@35.1323,-5.2945,17z](https://www.google.com/maps/place/Auberge+Dardara/@35.1323,-5.2945,17z)',
    address: 'Route Nationale 2, Dardara, Chefchaouen 91000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Dardara was founded to preserve the traditional culinary heritage of the Rif mountains, serving recipes that have been passed down for generations.',
    neighborhoodOverview: 'Dardara is a rural mountain area outside Chefchaouen, best for travelers with a car or arranged transfer who want nature, farm food, and quiet nights.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Incredible food quality', 'Peaceful mountain setting', 'Warm and genuine hospitality'],
    cons: ['Requires transport to reach Chefchaouen town', 'Rooms are cozy but simple'],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.8,
      staff: 9.9,
      value: 9.5,
      comfort: 9.4,
      location: 9.2
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Included on-site',
      contact: '+212 539 984 703'
    },
    roomFeatures: ['mountain-view', 'garden-view', 'fireplace', 'ac', 'heating', 'shower-ensuite'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Chefchaouen Town', distance: '10km', time: '15 min drive', icon: 'city' },
      { label: 'Akchour Waterfalls', distance: '35km', time: '50 min drive', icon: 'nature' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://www.dardara.ma](https://www.dardara.ma)',
    instagramHandle: '@aubergedardara',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A peaceful and very safe mountain escape.',
      couples: 'The fireplaces in the rooms make it incredibly cozy in winter.',
      families: 'Great for kids to see the farm and play in the pool.',
      business: 'A quiet place for a creative retreat.',
      nomad: 'Inspiring mountain views for work, though town is a drive away.'
    }
  },
  {
    id: 'ch-sleep-6',
    city: 'chefchaouen',
    name: 'Casa Perleta',
    type: 'riad',
    neighborhood: 'Medina',
    description: 'A charming and intimate riad known for its warm hospitality and authentic blue-and-white decor. Located right by the Bab Souk gate, it offers easy access to the medina while providing a quiet and homely retreat with a lovely rooftop terrace.',
    pricePerNight: 75,
    lifestyle: 'balanced',
    amenities: ['Homely Rooftop Terrace', 'Authentic Blue Decor', 'Traditional Breakfast', 'Library Area'],
    googleRating: 4.9,
    googleReviewCount: 650,
    tripadvisorRating: 4.9,
    tripadvisorReviewCount: 300,
    bookingRating: 4.9,
    bookingReviewCount: 400,
    hotelguruRating: 4.9,
    hotelguruReviewCount: 120,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['couple', 'solo', 'seniors'],
    tip: 'The breakfast here is considered one of the best in the medina—don\'t miss the homemade jams and local goat cheese.',
    vibeTags: ['Charming', 'Homely', 'Authentic', 'Central'],
    locationSummary: 'Medina - Bab Souk',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Casa+Perleta/@35.1685,-5.2645,17z](https://www.google.com/maps/place/Casa+Perleta/@35.1685,-5.2645,17z)',
    address: 'Bab Souk, Chefchaouen 91000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Casa Perleta was one of the first riads to open in Chefchaouen, established by a family who wanted to share the simple beauty of blue-city living.',
    neighborhoodOverview: 'Bab Souk is one of the easiest medina entry points, convenient for parking, taxis, and quick access to the blue lanes without being too deep inside the old town.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Incredible hospitality and warmth', 'Perfect location for exploring', 'Beautiful authentic blue aesthetics'],
    cons: ['No pool on-site', 'Rooms are cozy but on the smaller side'],
    trustScores: {
      cleanliness: 9.9,
      safety: 9.9,
      staff: 9.9,
      value: 9.6,
      comfort: 9.4,
      location: 9.9
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Nearby public parking at Bab Souk',
      contact: '+212 539 988 979'
    },
    roomFeatures: ['traditional-decor', 'rooftop-access', 'ac', 'heating', 'shower-ensuite'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Bab Souk Gate', distance: '50m', time: '1 min walk', icon: 'gate' },
      { label: 'Outa el Hammam Square', distance: '400m', time: '5 min walk', icon: 'city' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://casaperleta.com](https://casaperleta.com)',
    instagramHandle: '@casaperleta',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A safe, warm, and incredibly welcoming home in the blue city.',
      couples: 'The blue decor and the cozy terrace were so romantic.',
      families: 'Better suited for adults who appreciate a quiet and traditional stay.',
      business: 'Quiet and peaceful with reliable WiFi in common areas.',
      nomad: 'A friendly, central riad with cozy common areas for light laptop work.'
    }
  },
  {
    id: 'ch-sleep-7',
    city: 'chefchaouen',
    name: 'Riad Hicham',
    type: 'riad',
    neighborhood: 'Medina',
    description: 'An elegant and centrally located riad right on the main square of Outa el Hammam. Riad Hicham features a stunning courtyard and a rooftop terrace with the best front-row views of the historic Kasbah and the Grand Mosque.',
    pricePerNight: 85,
    lifestyle: 'balanced',
    amenities: ['Kasbah View Terrace', 'Central Courtyard', 'Traditional Restaurant', 'Authentic Zellij Work'],
    googleRating: 4.7,
    googleReviewCount: 380,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 150,
    bookingRating: 4.6,
    bookingReviewCount: 200,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 50,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['couple', 'family', 'solo'],
    tip: 'Have dinner on the rooftop at sunset; the view of the Kasbah lighting up is the best in the city.',
    vibeTags: ['Central', 'Historic', 'Vibrant', 'Panoramic'],
    locationSummary: 'Medina - Main Square',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Riad+Hicham/@35.1685,-5.2645,17z](https://www.google.com/maps/place/Riad+Hicham/@35.1685,-5.2645,17z)',
    address: 'Place Outa el Hammam, Chefchaouen 91000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Riad Hicham is a family-run establishment that has been a witness to the evolving life of Chefchaouen’s main square for decades.',
    neighborhoodOverview: 'Outa el Hammam is the social heart of Chefchaouen, lively with cafes, restaurants, the Kasbah, and evening foot traffic, while still feeling safe and compact.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Unbeatable central location', 'Best views of the Kasbah', 'Lively and authentic atmosphere'],
    cons: ['Can be noisy due to its location on the main square'],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.8,
      staff: 9.7,
      value: 9.2,
      comfort: 9.3,
      location: 10.0
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Nearby public parking lot',
      contact: '+212 539 986 161'
    },
    roomFeatures: ['kasbah-view', 'rooftop-access', 'ac', 'heating', 'shower-ensuite'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'The Kasbah', distance: '20m', time: '1 min walk', icon: 'castle' },
      { label: 'Ras El Ma', distance: '600m', time: '8 min walk', icon: 'waves' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://riadhicham.com](https://riadhicham.com)',
    instagramHandle: '@riadhicham',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A safe and vibrant place to be in the center of everything.',
      couples: 'The rooftop views of the Kasbah were the highlight of our stay.',
      families: 'Great for families who want to be near the main square activities.',
      business: 'Good for a quick stay, though it can be lively outside.',
      nomad: 'Central and convenient for cafe work, but bring headphones for square noise.'
    }
  },
  {
    id: 'ch-sleep-8',
    city: 'chefchaouen',
    name: 'Dar Baibou',
    type: 'riad',
    neighborhood: 'Medina',
    description: 'A traditional and warm guest house that feels like a real Moroccan home. Located in the heart of the blue medina, it features multiple cozy courtyards, a traditional hammam, and is famous for its homemade breakfast and friendly atmosphere.',
    pricePerNight: 65,
    lifestyle: 'lean',
    amenities: ['Multiple Cozy Courtyards', 'Traditional Hammam', 'Rooftop Terrace', 'Homemade Breakfast'],
    googleRating: 4.6,
    googleReviewCount: 420,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 200,
    bookingRating: 4.5,
    bookingReviewCount: 300,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 80,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    tip: 'Book a session in their private hammam—it is one of the most authentic and relaxing experiences in the medina.',
    vibeTags: ['Authentic', 'Warm', 'Homely', 'Traditional'],
    locationSummary: 'Medina',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Dar+Baibou/@35.1685,-5.2645,17z](https://www.google.com/maps/place/Dar+Baibou/@35.1685,-5.2645,17z)',
    address: 'Bab Souk, Chefchaouen 91000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    customStory: 'Dar Baibou was created to preserve the traditional way of life in the medina, offering a space where guests are treated as family members.',
    neighborhoodOverview: 'This medina pocket is close to Bab Souk and the main blue streets, with local shops, compact alleys, and easy walking access to cafes and viewpoints.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Very authentic and homely feel', 'Excellent traditional hammam', 'Great value for money'],
    cons: ['Can be a bit dark in the interior rooms', 'Lots of stairs to reach the terrace'],
    trustScores: {
      cleanliness: 9.4,
      safety: 9.7,
      staff: 9.8,
      value: 9.6,
      comfort: 9.1,
      location: 9.7
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '11:00',
      luggageStorage: 'Free',
      parking: 'Nearby public parking lot',
      contact: '+212 539 988 565'
    },
    roomFeatures: ['traditional-decor', 'rooftop-access', 'ac', 'heating', 'shower-ensuite'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Outa el Hammam Square', distance: '300m', time: '4 min walk', icon: 'city' },
      { label: 'Ras El Ma', distance: '500m', time: '6 min walk', icon: 'waves' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://darbaibou.com](https://darbaibou.com)',
    instagramHandle: '@darbaibou',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A safe, warm, and incredibly authentic home base.',
      couples: 'The traditional hammam and the cozy courtyards were so special.',
      families: 'A very welcoming place for families to experience local life.',
      business: 'Quiet and peaceful with a unique cultural touch.',
      nomad: 'A simple, affordable base for light work between medina walks.'
    }
  },
  {
    id: 'ch-sleep-9',
    city: 'chefchaouen',
    name: 'Alhambra Ryad & Spa',
    type: 'riad',
    neighborhood: 'Medina',
    description: 'An elegant and serene riad that perfectly blends Andalusian and Moroccan architecture. Located in a quiet part of the blue medina, it features a beautifully tiled inner courtyard, a full-service traditional hammam, and a rooftop terrace with peaceful views of the Rif Mountains.',
    pricePerNight: 95,
    lifestyle: 'premium',
    amenities: ['Traditional Moroccan Hammam', 'Luxury Spa Treatments', 'Panoramic Rooftop Terrace', 'Andalusian Tiled Courtyard'],
    googleRating: 4.7,
    googleReviewCount: 210,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 100,
    bookingRating: 4.8,
    bookingReviewCount: 150,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 40,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['couple', 'seniors', 'solo'],
    tip: 'Book the "Andalusian Hammam" session for an authentic and incredibly relaxing experience right within the riad.',
    vibeTags: ['Andalusian', 'Serene', 'Traditional', 'Refined'],
    locationSummary: 'Medina - Quiet Quarter',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Alhambra+Ryad+%26+Spa/@35.1691,-5.2635,17z](https://www.google.com/maps/place/Alhambra+Ryad+%26+Spa/@35.1691,-5.2635,17z)',
    address: 'Avenue Sidi Ahmed el Ouafi, Chefchaouen 91000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Created to honor the historic connection between Chefchaouen and the Alhambra in Spain, this riad uses traditional materials to recreate the peaceful atmosphere of an Andalusian villa.',
    neighborhoodOverview: 'Avenue Sidi Ahmed el Ouafi is a calmer medina-side area close to Ras el Ma, ideal for guests who want quiet nights while staying near the blue lanes.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Exceptional architectural detail and tiling', 'One of the best spas in the blue city', 'Very quiet and safe environment'],
    cons: ['No swimming pool', 'Away from the very center of the action'],
    trustScores: {
      cleanliness: 9.8,
      safety: 9.9,
      staff: 9.7,
      value: 9.1,
      comfort: 9.6,
      location: 9.4
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Nearby public parking (Ras el Ma)',
      contact: '+212 539 986 024'
    },
    roomFeatures: ['traditional-decor', 'rooftop-access', 'ac', 'heating', 'shower-ensuite'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Ras el Ma Waterfall', distance: '400m', time: '5 min walk', icon: 'nature' },
      { label: 'Outa el Hammam Square', distance: '500m', time: '7 min walk', icon: 'city' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://alhambraryad.com](https://alhambraryad.com)',
    instagramHandle: '@alhambraryad',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A safe and incredibly peaceful haven for a solo traveler.',
      couples: 'The decor and the hammam were very romantic.',
      families: 'Better suited for couples or seniors seeking quiet.',
      business: 'A quiet and inspiring setting with good WiFi.',
      nomad: 'Great for focused work in a calm riad with spa breaks nearby.'
    }
  },
  {
    id: 'ch-sleep-10',
    city: 'chefchaouen',
    name: 'Dar Meziana',
    type: 'guesthouse',
    neighborhood: 'Medina',
    description: 'A charming and artistic boutique guesthouse known for its explosion of color and creativity. It features hand-painted ceilings, eclectic decor, and a cozy rooftop terrace where you can enjoy a legendary homemade breakfast overlooking the blue-washed rooftops.',
    pricePerNight: 75,
    lifestyle: 'balanced',
    amenities: ['Artistic Rooftop Terrace', 'Hand-Painted Ceilings', 'Gourmet Homemade Breakfast', 'Cultural Decor'],
    googleRating: 4.8,
    googleReviewCount: 420,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 200,
    bookingRating: 4.8,
    bookingReviewCount: 300,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 100,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['couple', 'friends', 'solo'],
    tip: 'Don’t miss the breakfast—the owners serve a variety of local mountain cheeses and honeys that are among the best in town.',
    vibeTags: ['Artistic', 'Vibrant', 'Charming', 'Bohemian'],
    locationSummary: 'Medina',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Dar+Meziana/@35.1685,-5.2635,17z](https://www.google.com/maps/place/Dar+Meziana/@35.1685,-5.2635,17z)',
    address: 'Rue Zagdoud, Chefchaouen 91000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Designed by a local family to showcase the artistic spirit of Chefchaouen, Dar Meziana is a living gallery of Rifian craftsmanship and color.',
    neighborhoodOverview: 'Rue Zagdoud is a medina lane close to the main sights, offering quick access to blue alley photo spots, small guesthouses, and relaxed rooftop views.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Incredible artistic decor', 'One of the best breakfasts in the city', 'Perfectly located for medina exploration'],
    cons: ['Rooms are cozy but not oversized', 'Lots of stairs (typical for medina houses)'],
    trustScores: {
      cleanliness: 9.7,
      safety: 9.8,
      staff: 9.9,
      value: 9.6,
      comfort: 9.2,
      location: 9.9
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '11:00',
      luggageStorage: 'Free',
      parking: 'Nearby public parking lot',
      contact: '+212 539 986 024'
    },
    roomFeatures: ['artistic-decor', 'rooftop-access', 'ac', 'heating', 'shower-ensuite'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Outa el Hammam Square', distance: '300m', time: '4 min walk', icon: 'city' },
      { label: 'Kasbah Museum', distance: '350m', time: '5 min walk', icon: 'castle' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://darmeziana.com](https://darmeziana.com)',
    instagramHandle: '@darmeziana',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A safe and incredibly inspiring sanctuary for a solo traveler.',
      couples: 'The decor and the breakfast made it very special for us.',
      families: 'Better suited for older children who will appreciate the art.',
      business: 'A quiet and inspiring setting with good WiFi.',
      nomad: 'A colorful, creative base for remote workers who like character.'
    }
  },
  {
    id: 'ch-sleep-11',
    city: 'chefchaouen',
    name: 'Riad La Sultana',
    type: 'riad',
    neighborhood: 'Medina',
    description: 'A beautifully restored 18th-century riad featuring traditional Moroccan craftsmanship, hand-carved plaster, and a serene central fountain courtyard. It offers a majestic and authentic stay in the heart of the blue-washed city.',
    pricePerNight: 105,
    lifestyle: 'balanced',
    amenities: ['Historic Central Fountain', 'Panoramic Rooftop Terrace', 'Traditional Fassi Kitchen', 'Hand-Carved Plasterwork'],
    googleRating: 4.6,
    googleReviewCount: 230,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 100,
    bookingRating: 4.6,
    bookingReviewCount: 120,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 30,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'friends'],
    tip: 'Its central location makes it easy to explore the vibrant market streets on foot.',
    vibeTags: ['Majestic', 'Authentic', 'Historic', 'Serene'],
    locationSummary: 'Medina',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Riad+La+Sultana/@35.1681,-5.2625,17z](https://www.google.com/maps/place/Riad+La+Sultana/@35.1681,-5.2625,17z)',
    address: 'Place El Haouta, Chefchaouen 91000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Riad La Sultana was founded to honor the royal Fassi style of architecture, offering a level of preservation rarely seen in the Rif mountains.',
    neighborhoodOverview: 'Place El Haouta is a scenic and central medina square with traditional lanes, small cafes, and quick walking access to the Kasbah and main shopping streets.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Unmatched historical atmosphere', 'Excellent central location', 'Quiet and deeply authentic'],
    cons: ['Facilities are traditional rather than modern-luxury', 'Requires a bit of walking to reach from the gates'],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.8,
      staff: 9.7,
      value: 9.4,
      comfort: 9.2,
      location: 9.9
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '11:00',
      luggageStorage: 'Free',
      parking: 'Nearby public parking',
      contact: '+212 535 633 444'
    },
    roomFeatures: ['historic-decor', 'rooftop-access', 'ac', 'heating', 'shower-ensuite'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Outa el Hammam Square', distance: '200m', time: '3 min walk', icon: 'city' },
      { label: 'Kasbah', distance: '300m', time: '4 min walk', icon: 'castle' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://riad-la-sultana.com](https://riad-la-sultana.com)',
    instagramHandle: '@riadlasultana',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A safe and incredibly inspiring sanctuary for a solo traveler.',
      couples: 'The history and the quiet courtyard made it very special for us.',
      families: 'Better suited for older children who will appreciate the history.',
      business: 'A quiet and inspiring setting with good WiFi.',
      nomad: 'A character-rich stay for focused writing or creative remote work.'
    }
  },
  {
    id: 'ch-sleep-12',
    city: 'chefchaouen',
    name: 'Dar Dadicilef',
    type: 'guesthouse',
    neighborhood: 'Medina',
    description: 'A tranquil guesthouse with spacious, comfortable rooms, a delightful garden breakfast area, and a genuinely warm family welcome. It offers a sense of home and peace within the blue city.',
    pricePerNight: 85,
    lifestyle: 'balanced',
    amenities: ['Inner Courtyard Garden', 'Homemade Breakfast', 'Family Hospitality', 'Mountain View Terrace'],
    googleRating: 4.5,
    googleReviewCount: 310,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 150,
    bookingRating: 4.6,
    bookingReviewCount: 200,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 60,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['couple', 'family', 'friends'],
    tip: 'Relax in the inner courtyard garden after a day of walking the blue alleys.',
    vibeTags: ['Tranquil', 'Homey', 'Traditional', 'Serene'],
    locationSummary: 'Medina',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Dar+Dadicilef/@35.1681,-5.2625,17z](https://www.google.com/maps/place/Dar+Dadicilef/@35.1681,-5.2625,17z)',
    address: 'Rue Sidi Ahmed el Ouafi, Chefchaouen 91000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Dar Dadicilef was established to provide a sanctuary of peace in the medina, focusing on quiet gardens and traditional hospitality.',
    neighborhoodOverview: 'Rue Sidi Ahmed el Ouafi is a calmer medina lane near the upper town, good for travelers who want quick access to Ras el Ma and a less crowded evening feel.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Very quiet and green environment', 'Warm and personalized service', 'Great value for a high-quality stay'],
    cons: ['Away from the business center and beach', 'No pool on-site'],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.8,
      staff: 9.9,
      value: 9.4,
      comfort: 9.2,
      location: 9.5
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '11:00',
      luggageStorage: 'Free',
      parking: 'Nearby public parking',
      contact: '+212 535 633 444'
    },
    roomFeatures: ['garden-view', 'rooftop-access', 'ac', 'heating', 'shower-ensuite'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Outa el Hammam Square', distance: '300m', time: '4 min walk', icon: 'city' },
      { label: 'Ras el Ma Waterfall', distance: '500m', time: '7 min walk', icon: 'nature' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://dar-dadicilef.com](https://dar-dadicilef.com)',
    instagramHandle: '@dardadicilef',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A safe and incredibly peaceful haven for a solo traveler.',
      couples: 'The history and the quiet courtyard made it very special for us.',
      families: 'The garden area is perfect for children to play safely.',
      business: 'A quiet and inspiring setting with good WiFi.',
      nomad: 'A peaceful garden guesthouse suited to slow mornings and laptop time.'
    }
  },
  {
    id: 'ch-sleep-13',
    city: 'chefchaouen',
    name: 'Hostel Aline',
    type: 'hostel',
    neighborhood: 'Medina',
    description: 'A top-rated and vibrant social hostel that has become a cornerstone of the backpacker scene in Chefchaouen. It features a lively rooftop terrace with panoramic views, a shared kitchen, and a friendly atmosphere where solo travelers easily connect for group hikes and dinners.',
    pricePerNight: 18,
    lifestyle: 'lean',
    amenities: ['Vibrant Rooftop Terrace', 'Shared Communal Kitchen', 'Group Hiking Tours', 'Free Local Breakfast', 'Locker Storage'],
    googleRating: 4.3,
    googleReviewCount: 500,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 200,
    bookingRating: 4.4,
    bookingReviewCount: 300,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 80,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: false,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ['solo', 'friends'],
    tip: 'Ask about the group hike to the Spanish Mosque at sunset—it’s the best way to meet people and see the city from above.',
    vibeTags: ['Social', 'Budget-Friendly', 'Vibrant', 'Backpacker-Hub'],
    locationSummary: 'Medina',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Hostel+Aline/@35.1685,-5.2635,17z](https://www.google.com/maps/place/Hostel+Aline/@35.1685,-5.2635,17z)',
    address: 'Rue Zagdoud, Chefchaouen 91000, Morocco',
    paymentMethods: ['cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Founded by a group of travelers who wanted to create a space that felt like a community rather than just a place to sleep.',
    neighborhoodOverview: 'Rue Zagdoud is central and social, with easy access to medina cafes, viewpoints, and other backpacker guesthouses; expect a lively but safe atmosphere.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Excellent social atmosphere', 'Very affordable with breakfast included', 'Great rooftop for meeting people'],
    cons: ['Basic facilities', 'Medina can be noisy at night'],
    trustScores: {
      cleanliness: 8.5,
      safety: 8.8,
      staff: 9.6,
      value: 9.8,
      comfort: 7.8,
      location: 9.7
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '11:00',
      luggageStorage: 'Free',
      parking: 'Nearby public parking lot',
      contact: '+212 539 986 024'
    },
    roomFeatures: ['bunk-beds', 'shared-bathrooms', 'lockers', 'rooftop-access'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Outa el Hammam Square', distance: '300m', time: '4 min walk', icon: 'city' },
      { label: 'Spanish Mosque', distance: '1.2km', time: '20 min walk', icon: 'mosque' }
    ],
    cancellationPolicy: 'Flexible 24h',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://hostelaline.com](https://hostelaline.com)',
    instagramHandle: '@hostelaline',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'Extremely easy to meet people and felt very safe.',
      couples: 'Good for a quick and very cheap city stay.',
      families: 'Not recommended for families.',
      business: 'Only for the very budget-conscious business traveler.',
      nomad: 'Social and affordable, better for short work bursts than deep focus.'
    }
  },
  {
    id: 'ch-sleep-14',
    city: 'chefchaouen',
    name: 'Hostel Val Paradis',
    type: 'hostel',
    neighborhood: 'Upper Medina',
    description: 'A peaceful and exceptionally well-managed hostel tucked away in the quieter upper medina. Known for its calm atmosphere, friendly management, and a stunning rooftop terrace that offers some of the best mountain and sunset views in the city.',
    pricePerNight: 20,
    lifestyle: 'lean',
    amenities: ['Panoramic Mountain Rooftop', 'Quiet Communal Lounge', 'Personalized Local Advice', 'Locker Storage'],
    googleRating: 4.4,
    googleReviewCount: 320,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 150,
    bookingRating: 4.5,
    bookingReviewCount: 200,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 60,
    hasPool: false,
    hasBreakfast: false,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: false,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['solo', 'friends'],
    tip: 'The upper medina is quieter and less touristy. The rooftop here has great mountain views and is perfect for stargazing at night.',
    vibeTags: ['Peaceful', 'Scenic', 'Quiet', 'Welcoming'],
    locationSummary: 'Upper Medina',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Hostel+Val+Paradis/@35.1685,-5.2635,17z](https://www.google.com/maps/place/Hostel+Val+Paradis/@35.1685,-5.2635,17z)',
    address: 'Upper Medina, Chefchaouen 91000, Morocco',
    paymentMethods: ['cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Designed to be a "paradise of value," this hostel focuses on providing a peaceful and respectful environment for true travelers and hikers.',
    neighborhoodOverview: 'The upper medina is quieter, steeper, and more residential, with excellent mountain views and easy access to Ras el Ma but a bit more walking from the center.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Very quiet and peaceful environment', 'Exceptional mountain views', 'Very clean and well-maintained'],
    cons: ['Slightly uphill walk from the main gate', 'No breakfast included (many options nearby)'],
    trustScores: {
      cleanliness: 9.2,
      safety: 9.8,
      staff: 9.7,
      value: 9.4,
      comfort: 8.5,
      location: 9.2
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '11:00',
      luggageStorage: 'Free',
      parking: 'Nearby public parking lot',
      contact: '+212 539 986 024'
    },
    roomFeatures: ['bunk-beds', 'shared-bathrooms', 'lockers', 'rooftop-access', 'mountain-view'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Ras el Ma Waterfall', distance: '400m', time: '5 min walk', icon: 'nature' },
      { label: 'Outa el Hammam Square', distance: '600m', time: '8 min walk', icon: 'city' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://hostelvalparadis.com](https://hostelvalparadis.com)',
    instagramHandle: '@hostelvalparadis',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'Extremely safe and very peaceful for a solo traveler.',
      couples: 'The rooftop views at sunset were a highlight of our stay.',
      families: 'Not recommended for families.',
      business: 'A quiet and inspiring setting with good WiFi.',
      nomad: 'One of the better hostel options for quiet remote work and mountain views.'
    }
  },
  {
    id: 'ch-sleep-15',
    city: 'chefchaouen',
    name: 'Casa Blue Pearl',
    type: 'guesthouse',
    neighborhood: 'Medina',
    description: 'A budget-friendly traditional guesthouse that offers a taste of authentic riad life without the premium price tag. Known for its spotless cleanliness, blue-washed rooms, and the genuine Moroccan hospitality of its local family owners.',
    pricePerNight: 35,
    lifestyle: 'lean',
    amenities: ['Traditional Homemade Breakfast', 'Scenic Rooftop Terrace', 'Local Family Hospitality'],
    googleRating: 4.3,
    googleReviewCount: 290,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 150,
    bookingRating: 4.3,
    bookingReviewCount: 200,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 60,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ['solo', 'couple', 'friends'],
    tip: 'Ask for the room with the small window overlooking the blue alley—it makes for incredible photos and offers a direct view into the heart of the medina.',
    vibeTags: ['Authentic', 'Budget-Friendly', 'Spotless', 'Local'],
    locationSummary: 'Medina',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Casa+Blue+Pearl/@35.1685,-5.2635,17z](https://www.google.com/maps/place/Casa+Blue+Pearl/@35.1685,-5.2635,17z)',
    address: 'Place Outa el Hammam, Chefchaouen 91000, Morocco',
    paymentMethods: ['cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Created by a local family to share the beauty and tranquility of their ancestral home with travelers from around the world.',
    neighborhoodOverview: 'The central medina around Outa el Hammam is easy to explore on foot, with lively cafes, blue alleys, and quick access to the Kasbah and viewpoint paths.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Excellent value for money', 'Extremely clean and well-maintained', 'Very warm and genuine family welcome'],
    cons: ['Basic facilities', 'Medina can be busy and noisy at night'],
    trustScores: {
      cleanliness: 9.8,
      safety: 9.8,
      staff: 9.9,
      value: 9.7,
      comfort: 8.2,
      location: 9.9
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '11:00',
      luggageStorage: 'Free',
      parking: 'Nearby public parking lot',
      contact: '+212 539 986 024'
    },
    roomFeatures: ['traditional-decor', 'rooftop-access', 'heating', 'shower-ensuite'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Outa el Hammam Square', distance: '200m', time: '3 min walk', icon: 'city' },
      { label: 'Kasbah Museum', distance: '250m', time: '3 min walk', icon: 'castle' }
    ],
    cancellationPolicy: 'Flexible 24h',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://casabluepearl.com](https://casabluepearl.com)',
    instagramHandle: '@casabluepearl',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'A safe and incredibly welcoming sanctuary for a solo traveler.',
      couples: 'The decor and the central location were perfect for our stay.',
      families: 'Great for families who want an authentic and budget-friendly base.',
      business: 'Basic but very clean and central for a quick trip.',
      nomad: 'Best for budget nomads needing a clean base rather than a full workspace.'
    }
  },
  {
    id: 'ch-sleep-16',
    city: 'chefchaouen',
    name: 'Hostel Mauritania',
    type: 'hostel',
    neighborhood: 'Medina',
    description: 'One of the oldest and most well-known backpacker spots in Chefchaouen. It offers basic but character-filled accommodations, an authentic local atmosphere, and a lively common area where travelers swap stories over mint tea.',
    pricePerNight: 15,
    lifestyle: 'lean',
    amenities: ['Historic Common Room', 'Vibrant Rooftop Terrace', 'Travel Exchange Board', 'Locker Storage'],
    googleRating: 4.0,
    googleReviewCount: 600,
    tripadvisorRating: 3.8,
    tripadvisorReviewCount: 250,
    bookingRating: 4.1,
    bookingReviewCount: 300,
    hotelguruRating: 4.0,
    hotelguruReviewCount: 100,
    hasPool: false,
    hasBreakfast: false,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: false,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ['solo', 'friends'],
    tip: 'The common area is a great place to swap travel stories over a glass of mint tea. Check the board for shared taxi offers to Akchour.',
    vibeTags: ['Authentic', 'Social', 'Budget-Friendly', 'Historic'],
    locationSummary: 'Medina - Main Square',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Hostel+Mauritania/@35.1685,-5.2635,17z](https://www.google.com/maps/place/Hostel+Mauritania/@35.1685,-5.2635,17z)',
    address: 'Place Outa el Hammam, Chefchaouen 91000, Morocco',
    paymentMethods: ['cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Operating for over three decades, Hostel Mauritania has seen generations of travelers pass through its blue doors.',
    neighborhoodOverview: 'The main-square medina area is highly central, social, and lively, with restaurants and sights nearby; it is convenient but can be noisy at night.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Very affordable and highly social', 'Historic and authentic atmosphere', 'Excellent central location'],
    cons: ['Facilities are very basic', 'Can be noisy at night'],
    trustScores: {
      cleanliness: 7.5,
      safety: 8.2,
      staff: 9.4,
      value: 9.8,
      comfort: 6.8,
      location: 9.9
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '11:00',
      luggageStorage: 'Free',
      parking: 'Nearby public parking lot',
      contact: '+212 539 986 024'
    },
    roomFeatures: ['bunk-beds', 'shared-bathrooms', 'lockers', 'rooftop-access'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Outa el Hammam Square', distance: '200m', time: '3 min walk', icon: 'city' },
      { label: 'Kasbah', distance: '250m', time: '3 min walk', icon: 'castle' }
    ],
    cancellationPolicy: 'Flexible 24h',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://hostelmauritania.com](https://hostelmauritania.com)',
    instagramHandle: '@hostelmauritania',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'Extremely easy to meet people and felt very safe.',
      couples: 'Good for a quick and very cheap city stay.',
      families: 'Not recommended for families.',
      business: 'Only for the very budget-conscious business traveler.',
      nomad: 'Very affordable, but basic comfort and noise make it best for short stays.'
    }
  },
  {
    id: 'ch-sleep-17',
    city: 'chefchaouen',
    name: 'Hotel Sakura',
    type: 'hotel',
    neighborhood: 'Medina',
    description: 'A modest but highly-rated boutique hotel known for its spotless rooms and exceptional personalized service. Located in the upper medina, it offers a quieter atmosphere and stunning views of the Rif Mountains from its rooftop terrace.',
    pricePerNight: 55,
    lifestyle: 'balanced',
    amenities: ['Panoramic Mountain Terrace', 'Personalized Tour Planning', 'Homemade Moroccan Breakfast'],
    googleRating: 4.6,
    googleReviewCount: 180,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 80,
    bookingRating: 4.7,
    bookingReviewCount: 100,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 30,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['couple', 'family', 'solo'],
    tip: 'Book an upper-floor room for mountain views. The owner gives free tips on the best local hiking trails.',
    vibeTags: ['Spotless', 'Quiet', 'Welcoming', 'View-Oriented'],
    locationSummary: 'Upper Medina',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Hotel+Sakura/@35.1685,-5.2635,17z](https://www.google.com/maps/place/Hotel+Sakura/@35.1685,-5.2635,17z)',
    address: 'Rue Ibn Askar, Chefchaouen 91000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Named after the cherry blossoms that the owner loved while living in Japan, this hotel aims to bring that same sense of delicate beauty and hospitality to the Rif.',
    neighborhoodOverview: 'Rue Ibn Askar in the upper medina is quieter and slightly uphill, with good mountain views and close access to Ras el Ma, while remaining walkable to the main square.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Exceptional cleanliness and service', 'Great mountain views', 'Quieter location away from the square'],
    cons: ['Slightly uphill walk from the center', 'Basic facilities (no spa or pool)'],
    trustScores: {
      cleanliness: 9.9,
      safety: 9.8,
      staff: 9.9,
      value: 9.4,
      comfort: 9.1,
      location: 9.3
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Nearby public parking lot',
      contact: '+212 539 986 024'
    },
    roomFeatures: ['mountain-view', 'rooftop-access', 'ac', 'heating', 'shower-ensuite'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Ras el Ma Waterfall', distance: '300m', time: '4 min walk', icon: 'nature' },
      { label: 'Outa el Hammam Square', distance: '600m', time: '8 min walk', icon: 'city' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://hotel-sakura.com](https://hotel-sakura.com)',
    instagramHandle: '@hotelsakurachaouen',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'Extremely safe and very welcoming for a solo traveler.',
      couples: 'The mountain view from the terrace was a highlight of our trip.',
      families: 'Great for families who want a quiet and clean base.',
      business: 'A quiet and inspiring setting with good WiFi.',
      nomad: 'Clean, quiet, and good for focused remote work with mountain-view breaks.'
    }
  },
  {
    id: 'ch-sleep-18',
    city: 'chefchaouen',
    name: 'MoKo Hostel',
    type: 'hostel',
    neighborhood: 'Medina',
    description: 'A modern, centrally-located hostel that combines stylish design with a high-energy social atmosphere. It features comfortable dorms, modern shared facilities, and a vibrant rooftop where guests gather every evening to watch the sun dip behind the Rif Mountains.',
    pricePerNight: 22,
    lifestyle: 'lean',
    amenities: ['Modern Communal Lounge', 'Vibrant Sunset Rooftop', 'Organized City Tours', 'Locker Storage'],
    googleRating: 4.6,
    googleReviewCount: 220,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 100,
    bookingRating: 4.7,
    bookingReviewCount: 120,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 30,
    hasPool: false,
    hasBreakfast: false,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: false,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ['solo', 'friends'],
    tip: 'Lockers are spacious—bring your own padlock. The rooftop is a great hangout spot at sunset, often featuring impromptu music sessions.',
    vibeTags: ['Modern', 'Social', 'Vibrant', 'Central'],
    locationSummary: 'Medina',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/MoKo+Hostel/@35.1685,-5.2635,17z](https://www.google.com/maps/place/MoKo+Hostel/@35.1685,-5.2635,17z)',
    address: 'Avenue Sidi Ahmed el Ouafi, Chefchaouen 91000, Morocco',
    paymentMethods: ['cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Created to bridge the gap between traditional Moroccan hospitality and the needs of the modern, tech-savvy backpacker.',
    neighborhoodOverview: 'This central medina area is convenient for sights, cafes, and hiking meetups, with a lively traveler scene and easy walking access to the main square.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Very modern and clean facilities', 'Exceptional social atmosphere', 'Excellent central location'],
    cons: ['Can be very lively and loud at night', 'No breakfast included'],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.3,
      staff: 9.7,
      value: 9.5,
      comfort: 8.8,
      location: 9.9
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '11:00',
      luggageStorage: 'Free',
      parking: 'Nearby public parking lot',
      contact: '+212 539 986 024'
    },
    roomFeatures: ['bunk-beds', 'shared-bathrooms', 'lockers', 'rooftop-access', 'ac', 'heating'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Outa el Hammam Square', distance: '200m', time: '3 min walk', icon: 'city' },
      { label: 'Kasbah Museum', distance: '250m', time: '3 min walk', icon: 'castle' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://mokohostel.com](https://mokohostel.com)',
    instagramHandle: '@mokohostel',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'Extremely easy to meet people and felt very safe.',
      couples: 'The social vibe and the modern rooms were perfect.',
      families: 'Not recommended for families.',
      business: 'Excellent WiFi and very practical for work trips.',
      nomad: 'Good WiFi and modern spaces, though evenings can be social and loud.'
    }
  },
  {
    id: 'ch-sleep-19',
    city: 'chefchaouen',
    name: 'Hostal Znika',
    type: 'hostel',
    neighborhood: 'Medina',
    description: 'A highly-rated and colorful hostel celebrated for its exceptional cleanliness, artisan-inspired decor, and a warm, welcoming staff that goes above and beyond to make every guest feel at home. It offers a perfect blend of social energy and respectful quiet.',
    pricePerNight: 24,
    lifestyle: 'lean',
    amenities: ['Artisan-Inspired Decor', 'Homemade Local Breakfast', 'Scenic Rooftop Terrace', 'Luggage Storage'],
    googleRating: 4.5,
    googleReviewCount: 300,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 150,
    bookingRating: 4.6,
    bookingReviewCount: 200,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 60,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: false,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ['solo', 'couple', 'friends'],
    tip: 'The staff are incredibly helpful for arranging onward travel or organizing local hikes to the Spanish Mosque—don’t hesitate to ask for their advice.',
    vibeTags: ['Colorful', 'Welcoming', 'Artisan-Inspired', 'Central'],
    locationSummary: 'Medina',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Hostal+Znika/@35.1685,-5.2635,17z](https://www.google.com/maps/place/Hostal+Znika/@35.1685,-5.2635,17z)',
    address: 'Rue Ibn Askar, Chefchaouen 91000, Morocco',
    paymentMethods: ['cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Founded by a local artist who wanted to create a hostel that felt like a traditional Moroccan home, filled with color and hospitality.',
    neighborhoodOverview: 'Rue Ibn Askar is slightly quieter than the main square but still central, with easy access to blue alleys, Ras el Ma, and local hiking paths.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Exceptional cleanliness and service', 'Great social atmosphere', 'Incredible local breakfast'],
    cons: ['Basic facilities', 'Medina can be busy and noisy at night'],
    trustScores: {
      cleanliness: 9.8,
      safety: 9.6,
      staff: 9.9,
      value: 9.7,
      comfort: 8.4,
      location: 9.9
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '11:00',
      luggageStorage: 'Free',
      parking: 'Nearby public parking lot',
      contact: '+212 539 986 024'
    },
    roomFeatures: ['bunk-beds', 'shared-bathrooms', 'lockers', 'rooftop-access'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Outa el Hammam Square', distance: '200m', time: '3 min walk', icon: 'city' },
      { label: 'Spanish Mosque', distance: '1.2km', time: '20 min walk', icon: 'mosque' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://hostalznika.com](https://hostalznika.com)',
    instagramHandle: '@hostalznika',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'Extremely easy to meet people and felt very safe.',
      couples: 'The social vibe and the colorful rooms were perfect.',
      families: 'Not recommended for families.',
      business: 'A quiet and inspiring setting with good WiFi.',
      nomad: 'Clean and welcoming for budget remote workers who can use common spaces.'
    }
  },
  {
    id: 'ch-sleep-20',
    city: 'chefchaouen',
    name: 'Hotel Parador',
    type: 'hotel',
    neighborhood: 'Ville Nouvelle',
    description: 'A classic and established hotel located perfectly at the gateway to the blue medina. It is one of the few hotels in the city that offers road access, an elevator, and a large swimming pool, making it the premier choice for travelers with mobility needs or those preferring standard hotel amenities.',
    pricePerNight: 95,
    lifestyle: 'balanced',
    amenities: ['Large Outdoor Pool', 'Direct Road Access', 'Elevator Access', 'Traditional Restaurant', 'Parking'],
    googleRating: 4.2,
    googleReviewCount: 380,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 150,
    bookingRating: 4.3,
    bookingReviewCount: 200,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 60,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ['family', 'couple', 'seniors'],
    tip: 'Only a 5-minute flat walk to the medina entrance. Ideal for families with strollers or seniors avoiding cobblestone stairs.',
    vibeTags: ['Classic', 'Accessible', 'Established', 'Convenient'],
    locationSummary: 'Ville Nouvelle - Medina Gate',
    availabilityText: 'Available tonight',
    googleMapsUrl: '[https://www.google.com/maps/place/Hotel+Parador/@35.1685,-5.2635,17z](https://www.google.com/maps/place/Hotel+Parador/@35.1685,-5.2635,17z)',
    address: 'Place du Makhzen, Chefchaouen 91000, Morocco',
    paymentMethods: ['card', 'cash'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    customStory: 'Built during the protectorate era, Hotel Parador has served as the official guesthouse for visiting dignitaries and travelers for over half a century.',
    neighborhoodOverview: 'Ville Nouvelle at the medina gate offers easier road access, parking, and flatter walking than the inner medina, while keeping the blue streets only minutes away.',
    hiddenFeesNotice: 'City tax not included.',
    pros: ['Excellent accessibility and road access', 'Large pool with mountain views', 'Very easy for families and seniors'],
    cons: ['Interior can feel a bit dated compared to newer riads', 'Can be very busy with tour groups'],
    trustScores: {
      cleanliness: 9.1,
      safety: 9.6,
      staff: 9.3,
      value: 8.9,
      comfort: 9.2,
      location: 9.9
    },
    logistics: {
      checkIn: '14:00',
      checkOut: '12:00',
      luggageStorage: 'Free',
      parking: 'Secure on-site parking',
      contact: '+212 539 986 024'
    },
    roomFeatures: ['pool-view', 'mountain-view', 'ac', 'heating', 'shower-ensuite', 'elevator-access'],
    roomTypes: [
    ],
    neighborhoodDistances: [
      { label: 'Outa el Hammam Square', distance: '300m', time: '4 min walk', icon: 'city' },
      { label: 'Kasbah Museum', distance: '250m', time: '3 min walk', icon: 'castle' }
    ],
    cancellationPolicy: 'Moderate 48h',
    childPolicy: 'Children welcome',
    officialWebsite: '[https://hotel-parador-chefchaouen.com](https://hotel-parador-chefchaouen.com)',
    instagramHandle: '@hotelparadorchaouen',
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: 'Safe and very convenient, especially with a car.',
      couples: 'The pool area with mountain views was a great place to relax.',
      families: 'The easiest place in town to stay with kids and a stroller.',
      business: 'Reliable WiFi and easy road access for meetings.',
      nomad: 'A practical choice for remote workers who prefer hotel amenities and easy access.'
    }
  }
]
