import type { SleepListing } from '../types'

/**
 * SLEEP LISTING DATA TEMPLATE (Copy this for your search agent)
 * -------------------------------------------------------------
 * {
 *   "id": "city-sleep-XX",
 *   "name": "",
 *   "type": "riad | hotel | villa | hostel | apartment | guesthouse",
 *   "neighborhood": "",
 *   "city": "[city]",
 *   "description": "",
 *   "pricePerNight": 0,
 *   "lifestyle": "lean | balanced | premium",
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2', 'url3']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source (replaces single rating/reviewCount)
 *   // ═══════════════════════════════════════════════════
 *   // Search for real ratings from Google, TripAdvisor, Booking.com, and HotelGuru.
 *   // If you cannot find a rating for a specific source, set it to the same value as
 *   // the closest available one so average calculations don't break.
 *
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *   bookingRating: [4.x],
 *   bookingReviewCount: [number],
 *   hotelguruRating: [4.x],
 *   hotelguruReviewCount: [number],
 *
 *   // ═══════════════════════════════════════════════════
 *   // BOOLEAN AMENITIES
 *   // ═══════════════════════════════════════════════════
 *
 *   hasPool: true | false,
 *   hasBreakfast: true | false,
 *   hasAC: true | false,
 *   hasHeating: true | false,
 *   hasRooftop: true | false,
 *   hasEnsuite: true | false,
 *   hasRestaurant: true | false,
 *   hasBar: true | false,
 *   hasGym: true | false,
 *   hasElevator: true | false,
 *   hasLaundryService: true | false,
 *   hasRoomService: true | false,
 *   petFriendly: true | false,
 *   isWheelchairAccessible: true | false,
 *   taxesIncluded: true | false,
 *   freeCancellation: true | false,
 *   kidsStayFree: true | false,
 *
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearMosque: true | false,
 *   safetyLevel: 1 | 2 | 3 | 4 | 5,
 *
 *   // ═══════════════════════════════════════════════════
 *   // TRUST SCORES
 *   // ═══════════════════════════════════════════════════
 *
 *   trustScores: {
 *     cleanliness: [1-10],
 *     safety: [1-10],
 *     staff: [1-10],
 *     value: [1-10],
 *     comfort: [1-10],
 *     location: [1-10]
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   amenities: ['wifi', 'pool', 'ac', 'breakfast', 'spa', 'restaurant', 'gym', 'kitchenette', 'parking', 'bar', 'laundry', 'elevator', 'room-service'],
 *   tip: '[Short insider tip]',
 *   vibeTags: ['Authentic', 'Quiet', 'Modern'],
 *   locationSummary: 'Beachfront | City Center | Medina | Airport Area | Residential | Tourist Zone',
 *   availabilityText: 'Available tonight | Only 2 rooms left | Available on selected dates',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   address: '[Full street address, City, Postal Code, Morocco]',
 *
 *   paymentMethods: ['card', 'cash'],
 *   languagesSpoken: ['Arabic', 'French', 'English', 'Spanish', 'German'],
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   customStory: 'Brief history, owner background, or architecture notes...',
 *   neighborhoodOverview: 'Description of the local atmosphere, safety, and vibe...',
 *   hiddenFeesNotice: 'City tax of XX MAD per person/night not included...',
 *   pros: ['Pro 1', 'Pro 2'],
 *   cons: ['Con 1'],
 *
 *   // ═══════════════════════════════════════════════════
 *   // LOGISTICS
 *   // ═══════════════════════════════════════════════════
 *
 *   logistics: {
 *     checkIn: '14:00 - 22:00',
 *     checkOut: 'Before 11:00',
 *     luggageStorage: 'Free | Paid | None',
 *     parking: 'Free on-site | Nearby public | Valet',
 *     contact: '+212 XXXXXXXXX'
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *   // ROOM FEATURES & TYPES
 *   // ═══════════════════════════════════════════════════
 *
 *   roomFeatures: ['soundproof', 'workspace', 'private-balcony', 'ac', 'heating', 'balcony', 'shower-ensuite', 'sea-view', 'garden-view', 'pool-view'],
 *   roomTypes: [
 *     {
 *       name: 'Double Room',
 *       price: 500,
 *       beds: '1 Queen',
 *       size: '20m2',
 *     }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *   // NEIGHBORHOOD DISTANCES
 *   // ═══════════════════════════════════════════════════
 *
 *   neighborhoodDistances: [
 *     { label: 'Beach', distance: '500m', time: '5 min walk', icon: 'beach' }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   cancellationPolicy: 'Free cancellation up to 24h before check-in | Flexible | Non-refundable',
 *   childPolicy: 'Children welcome | Free under 6 | Extra bed 200 MAD',
 *   officialWebsite: 'https://...',
 *   instagramHandle: '@...',
 *
 *   // googlePlaceId: "PLACE_ID_HERE",
 *
 *   // ═══════════════════════════════════════════════════
 *   // REVIEW HIGHLIGHTS
 *   // ═══════════════════════════════════════════════════
 *
 *   reviewHighlights: {
 *     solo: 'Great insight for solo...',
 *     couples: 'Great for couples...',
 *     families: 'Kid-friendly details...',
 *     business: 'Wi-Fi test details...',
 *     nomad: 'Remote work specific insight...'
 *   }
 * }
 */

export const dakhlaSleep: SleepListing[] = [
  {
    id: "da-sleep-1",
    city: "dakhla",
    name: "Palais Rhoul & Spa Dakhla",
    type: "hotel",
    neighborhood: "Lagoon Front",
    description: "An architectural masterpiece of white columns and sweeping arches on the edge of the lagoon. This high-end boutique palace offers a serene and ultra-luxurious escape with direct access to the water and an exceptional spa.",
    pricePerNight: 350,
    lifestyle: "premium",
    amenities: ["Direct Lagoon Access", "Infinity Pool", "Luxury Spa", "Fine Dining", "5-star", "pool", "spa", "lagoon-view", "on-the-beach", "private-beach", "airport-shuttle"],
    googleRating: 4.9,
    googleReviewCount: 250,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 120,
    bookingRating: 4.9,
    bookingReviewCount: 180,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 40,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["couple", "seniors", "solo"],
    tip: "Book a lagoon-front villa to enjoy the calm waters right from your doorstep and experience candlelit dinners on the private pier.",
    vibeTags: ["Palatial", "Minimalist", "Serene", "Lagoon-Front"],
    locationSummary: "Dakhla Waterfront & Peninsula",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Le+Palais+Rhoul+Dakhla",
    address: "Palais Rhoul & Spa Dakhla, Lagoon Front, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Palais Rhoul is the Dakhla outpost of the famous Marrakech palace, bringing its signature columned architecture to the wild Atlantic coast.",
    neighborhoodOverview: "Set in a quiet residential area on the edge of the lagoon, offering total privacy while being only 10 minutes from the town center.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Stunning unique architecture", "Direct and private lagoon access", "Exceptional service"],
    cons: ["Away from the main kitesurf camps (requires shuttle)", "Most expensive option in Dakhla"],
    trustScores: {
      cleanliness: 9.8,
      safety: 9.7,
      staff: 9.6,
      value: 8.5,
      comfort: 9.7,
      location: 9.2,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free private parking",
      contact: "+212 528 841 122",
    },
    roomFeatures: ["high-ceilings", "lagoon-view", "minimalist-furniture", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Lagoon Room",
              price: 350,
              beds: "1 King",
              size: "40m²",
            },
      {
              name: "Lagoon Suite",
              price: 550,
              beds: "1 King",
              size: "70m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dakhla Center",
              distance: "3km",
              time: "5 min drive",
              icon: "city",
            },
      {
              label: "Dragon Island",
              distance: "Lagoon crossing",
              time: "15 min boat",
              icon: "nature",
            },
    ],
    cancellationPolicy: "Moderate 7-day",
    childPolicy: "Children welcome, though best suited for adults and couples",
    officialWebsite: "https://www.lepalaisrhouldakhla.com",
    instagramHandle: "@palaisrhouldakhla",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and incredibly peaceful sanctuary.",
      couples: "The most romantic sunset spot in all of Dakhla.",
      families: "Quiet and upscale, better for couples.",
      business: "Prestigious for hosting or high-end retreats.",
      nomad: "Inspiring architecture but internet is best in the common areas.",
    },
    coordinates: {
      lat: 23.694045,
      lng: -15.933445
    },
    tags: ["5-star", "luxury", "spa", "lagoon-view", "pool", "on-the-beach", "private-beach", "airport-shuttle", "heritage"]
  },
  {
    id: "da-sleep-2",
    city: "dakhla",
    name: "Heliophora Eco-Lodge",
    type: "guesthouse",
    neighborhood: "Dakhla Lagoon",
    description: "An eco-friendly lodge located in a quiet southern stretch of the lagoon, offering beautiful views of the water and surrounding desert. It provides a peaceful, slower-paced setting that helps travelers fully unplug.",
    pricePerNight: 160,
    lifestyle: "balanced",
    amenities: ["Lagoon Views", "Kitesurf School Access", "Eco-Friendly Design", "Traditional Breakfast", "lagoon-view", "kitesurf-hotels", "desert-camps", "on-the-beach", "all-inclusive"],
    googleRating: 4.9,
    googleReviewCount: 300,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 150,
    bookingRating: 4.8,
    bookingReviewCount: 220,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 35,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: false,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "countryside",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "friends"],
    tip: "Ask the team to arrange a downwinder trip to the nearby White Dune for a scenic kitesurfing experience.",
    vibeTags: ["Eco", "Quiet", "Lagoon-Views", "Unplugged"],
    locationSummary: "Dakhla Lagoon / Kitesurf Bay",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Heliophora+Eco-Lodge+Dakhla",
    address: "Heliophora Eco-Lodge, Dakhla Lagoon, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Heliophora focuses on low-impact lagoon living, blending simple eco design with the rhythm of wind, tides, and desert silence.",
    neighborhoodOverview: "Dakhla Lagoon is a remote, wind-swept water-sports zone with shallow turquoise water, steady trade winds, and isolated camps where private transfers are the normal way to move around.",
    hiddenFeesNotice: "Taxes are typically included in package rates; confirm gear rental and transfer inclusions before booking.",
    pros: ["Peaceful eco setting", "Strong value for lagoon access", "Good for kitesurf-focused stays"],
    cons: ["No pool", "Remote location requires transfers"],
    trustScores: {
      cleanliness: 9.8,
      safety: 9.6,
      staff: 9.9,
      value: 9.1,
      comfort: 9.7,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 528 000 000",
    },
    roomFeatures: ["lagoon-view", "natural-ventilation", "private-terrace", "shower-ensuite"],
    roomTypes: [
      {
              name: "Eco Lagoon Room",
              price: 160,
              beds: "1 Queen",
              size: "24m²",
            },
      {
              name: "Eco Triple Bungalow",
              price: 210,
              beds: "1 Queen + 1 Single",
              size: "30m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "White Dune",
              distance: "20km",
              time: "25 min drive",
              icon: "beach",
            },
      {
              label: "Dakhla Airport",
              distance: "45km",
              time: "40 min drive",
              icon: "airport",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome, but remote camp setting is best for older kids",
    officialWebsite: "https://heliophora.com",
    instagramHandle: "@heliophora_dakhla",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A calm base for solo kiters who want fewer distractions.",
      couples: "Quiet lagoon sunsets make it romantic in a simple, natural way.",
      families: "Better for older kids or active families comfortable with remote camps.",
      business: "Good for disconnecting rather than formal work calls.",
      nomad: "Best for nomads who kite first and work in short offline-focused blocks.",
    },
    coordinates: {
      lat: 23.914589,
      lng: -15.763504
    },
    tags: ["on-the-beach", "lagoon-view", "kitesurf-hotels", "desert-camps", "all-inclusive"]
  },
  {
    id: "da-sleep-3",
    city: "dakhla",
    name: "La Tour d'Éole",
    type: "hotel",
    neighborhood: "Dakhla Lagoon",
    description: "An elegant eco-lodge designed with Douglas wood that blends subtly into the desert landscape. It offers sweeping views of the turquoise bay alongside a highly tranquil atmosphere and a focus on sustainable luxury.",
    pricePerNight: 320,
    lifestyle: "premium",
    amenities: ["Heated Outdoor Pool", "Ocean Academy Access", "Organic Restaurant", "Panoramic Terrace", "Yoga Deck", "5-star", "pool", "spa", "lagoon-view", "kitesurf-hotels", "private-beach", "airport-shuttle", "all-inclusive"],
    googleRating: 4.8,
    googleReviewCount: 350,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 180,
    bookingRating: 4.7,
    bookingReviewCount: 250,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 60,
    hasPool: true,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: false,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    tip: "The on-site Ocean Academy is excellent for booking private windfoil or kitesurfing lessons in a less crowded lagoon area. The restaurant uses produce from their own organic farm.",
    vibeTags: ["Eco-Luxe", "Sustainable", "Tranquil", "Lagoon-Views"],
    locationSummary: "Secluded Southern Lagoon",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=La+Tour+d%27Eole+Dakhla",
    address: "La Tour d'Éole, Dakhla Lagoon, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Built to be entirely removable without leaving a trace on the desert, La Tour d'Éole is a masterclass in eco-conscious luxury architecture.",
    neighborhoodOverview: "Located far from the busier northern lagoon, this area offers untouched dunes and absolute silence under the stars.",
    hiddenFeesNotice: "Rates are typically all-inclusive (Full Board).",
    pros: ["Incredible architecture and design", "High-quality organic food", "Professional surf center"],
    cons: ["Far from Dakhla town", "No AC (cooled by natural ventilation)"],
    trustScores: {
      cleanliness: 9.8,
      safety: 9.9,
      staff: 9.7,
      value: 8.5,
      comfort: 9.6,
      location: 9.8,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Included on-site",
      contact: "+212 661 708 350",
    },
    roomFeatures: ["natural-ventilation", "organic-linens", "private-terrace", "lagoon-view", "shower-ensuite"],
    roomTypes: [
      {
              name: "Lagoon View Room",
              price: 320,
              beds: "1 King",
              size: "30m²",
            },
      {
              name: "Privilege Bungalow",
              price: 450,
              beds: "1 King",
              size: "45m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dakhla Airport",
              distance: "60km",
              time: "50 min drive",
              icon: "airport",
            },
      {
              label: "White Dune",
              distance: "15km",
              time: "20 min drive",
              icon: "beach",
            },
    ],
    cancellationPolicy: "Moderate 14-day",
    childPolicy: "Children welcome",
    officialWebsite: "https://latourdeole.com",
    instagramHandle: "@latourdeole",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A perfect sanctuary for a high-end solo kite retreat.",
      couples: "The most romantic and quiet spot on the lagoon.",
      families: "Great for families seeking a peaceful, natural environment.",
      business: "Decent WiFi in main areas, but best for disconnecting.",
      nomad: "Inspiring environment, though remote.",
    },
    coordinates: {
      lat: 23.73745,
      lng: -15.783587
    },
    tags: ["5-star", "pool", "spa", "lagoon-view", "kitesurf-hotels", "private-beach", "airport-shuttle", "all-inclusive", "family-favorite"]
  },
  {
    id: "da-sleep-4",
    city: "dakhla",
    name: "Dakhla Attitude",
    type: "hotel",
    neighborhood: "Dakhla Lagoon",
    description: "One of the longest-standing resorts on the lagoon, known for its vibrant community and excellent wind conditions. It overlooks Dragon Island, offering a social and energetic hub for water sports lovers.",
    pricePerNight: 180,
    lifestyle: "balanced",
    amenities: ["Duotone Pro Center", "Cable Wake Park", "Beach Bar", "Traditional Hammam", "Pink Flamingo Restaurant", "kitesurf-hotels", "all-inclusive", "lagoon-view", "on-the-beach", "airport-shuttle"],
    googleRating: 4.8,
    googleReviewCount: 1200,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 800,
    bookingRating: 4.6,
    bookingReviewCount: 1500,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 300,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: false,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "countryside",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "At low tide, you can walk or take a quick boat shuttle over to Dragon Island to explore its untouched sandbanks. The Pink Flamingo bar is the heart of the resort social life.",
    vibeTags: ["Vibrant", "Social", "Sport-Centric", "Iconic"],
    locationSummary: "Dakhla Lagoon / Kitesurf Bay",
    availabilityText: "Available tonight - Very Popular",
    googleMapsUrl: "https://maps.google.com/?q=Dakhla+Attitude",
    address: "Dakhla Attitude, Dakhla Lagoon, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Founded by local pioneer Driss Senoussi, Dakhla Attitude put the lagoon on the world map for kitesurfing, starting with a few simple tents and growing into a world-class sport resort.",
    neighborhoodOverview: "The northern lagoon is the most active area for kiting, home to the best wind stats and the most famous kiting schools.",
    hiddenFeesNotice: "Rates are typically all-inclusive of meals.",
    pros: ["Best social vibe on the lagoon", "Top-tier kiting school and equipment", "Iconic views of Dragon Island"],
    cons: ["Can be crowded in high season", "Bungalows are cozy but simple"],
    trustScores: {
      cleanliness: 9.0,
      safety: 9.8,
      staff: 9.5,
      value: 9.2,
      comfort: 8.8,
      location: 9.9,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 528 214 012",
    },
    roomFeatures: ["hillside-view", "natural-ventilation", "shower-ensuite", "lagoon-view"],
    roomTypes: [
      {
              name: "Windhunter Bungalow",
              price: 180,
              beds: "2 Twin",
              size: "25m²",
            },
      {
              name: "Dragon Camp Bungalow",
              price: 240,
              beds: "1 King",
              size: "35m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dakhla Airport",
              distance: "30km",
              time: "35 min drive",
              icon: "airport",
            },
      {
              label: "Dragon Island",
              distance: "500m",
              time: "5 min boat",
              icon: "beach",
            },
    ],
    cancellationPolicy: "Moderate 14-day",
    childPolicy: "Children welcome - family activities and wake park available",
    officialWebsite: "https://dakhla-attitude.ma",
    instagramHandle: "@dakhla_attitude",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "The best place to meet other kiter travelers.",
      couples: "Energetic and fun, great for active couples.",
      families: "Great kid-friendly activities and wake park.",
      business: "WiFi in main bar area is decent for checking emails.",
      nomad: "A high-energy hub for working nomads who kite.",
    },
    coordinates: {
      lat: 23.893369,
      lng: -15.771072
    },
    tags: ["kitesurf-hotels", "all-inclusive", "lagoon-view", "on-the-beach", "airport-shuttle", "family-favorite"]
  },
  {
    id: "da-sleep-5",
    city: "dakhla",
    name: "Caravan by Habitas Dakhla",
    type: "hotel",
    neighborhood: "Dakhla Lagoon",
    description: "A bohemian-luxury resort designed with wellness and connection in mind. The property offers a communal, artistic vibe complete with daily yoga sessions, a beautifully designed outdoor pool, and sustainable clay architecture.",
    pricePerNight: 380,
    lifestyle: "premium",
    amenities: ["Outdoor Swimming Pool", "Yoga Deck", "Stargazing Lounge", "Locally Sourced Dining", "Kite Center", "5-star", "pool", "spa", "lagoon-view", "kitesurf-hotels", "desert-camps", "private-beach", "airport-shuttle"],
    googleRating: 4.8,
    googleReviewCount: 200,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 90,
    bookingRating: 4.7,
    bookingReviewCount: 150,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 45,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "countryside",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "friends"],
    tip: "Join the outdoor cinema nights under the desert stars. The property is designed for creative nomads and has some of the best WiFi on the lagoon for those who need to work.",
    vibeTags: ["Bohemian-Chic", "Wellness", "Artistic", "Communal"],
    locationSummary: "Dakhla Lagoon / Kitesurf Bay",
    availabilityText: "Available tonight - Exclusive",
    googleMapsUrl: "https://maps.google.com/?q=Caravan+by+Habitas+Dakhla",
    address: "Caravan by Habitas Dakhla, Dakhla Lagoon, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Caravan is part of the Habitas group, which builds hotels using sustainable methods to create experiences focused on music, wellness, and community.",
    neighborhoodOverview: "Positioned in a quieter mid-lagoon area, offering a more peaceful kiting experience than the busier northern camps.",
    hiddenFeesNotice: "Rates are typically Full Board.",
    pros: ["Stunning bohemian design", "Excellent wellness program", "Best WiFi for digital nomads"],
    cons: ["Premium price point", "Smaller kiting beach area than Attitude"],
    trustScores: {
      cleanliness: 9.7,
      safety: 9.9,
      staff: 9.8,
      value: 8.2,
      comfort: 9.7,
      location: 9.5,
    },
    logistics: {
      checkIn: "15:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 529 073 700",
    },
    roomFeatures: ["bohemian-decor", "private-deck", "premium-linens", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Lagoon Room",
              price: 380,
              beds: "1 King",
              size: "32m²",
            },
      {
              name: "Ocean Room",
              price: 450,
              beds: "1 King",
              size: "35m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dakhla Airport",
              distance: "25km",
              time: "30 min drive",
              icon: "airport",
            },
      {
              label: "White Dune",
              distance: "20km",
              time: "25 min drive",
              icon: "beach",
            },
    ],
    cancellationPolicy: "Moderate 14-day",
    childPolicy: "Children welcome, best for teenagers and adults",
    officialWebsite: "https://www.ourhabitas.com/caravan-dakhla/",
    instagramHandle: "@caravanhabitasdakhla",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and incredibly inspiring community for solo creative travelers.",
      couples: "The chicest and most wellness-focused stay for couples.",
      families: "Better suited for adults and teenagers.",
      business: "The best office on the lagoon with high-speed WiFi.",
      nomad: "The gold standard for the modern digital nomad in Morocco.",
    },
    coordinates: {
      lat: 23.91391,
      lng: -15.781348
    },
    tags: ["5-star", "pool", "spa", "lagoon-view", "kitesurf-hotels", "desert-camps", "private-beach", "airport-shuttle"]
  },
  {
    id: "da-sleep-6",
    city: "dakhla",
    name: "La Crique Nature & Spa",
    type: "hotel",
    neighborhood: "Foum Labouir",
    description: "A cliffside boutique resort that combines organic clay dome architecture with beautiful views of the Atlantic Ocean. It offers a relaxed, premium environment focused on comfort, sustainability, and traditional Moroccan hospitality.",
    pricePerNight: 290,
    lifestyle: "premium",
    amenities: ["Heated Outdoor Pool", "Private Beach Access", "Full-Service Spa", "Oceanfront Restaurant", "5-star", "pool", "spa", "private-beach", "desert-camps", "airport-shuttle", "lagoon-view"],
    googleRating: 4.8,
    googleReviewCount: 490,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 280,
    bookingRating: 4.7,
    bookingReviewCount: 350,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 110,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "countryside",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["couple", "family", "seniors"],
    tip: "Book an ocean-view suite to watch the sunset directly over the waves of Foum Labouir from your private balcony. The surf here is excellent for advanced surfers.",
    vibeTags: ["Organic-Architecture", "Cliffside", "Serene", "Oceanfront"],
    locationSummary: "Dakhla Lagoon / Kitesurf Bay",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=La+Crique+Nature+%26+Spa+Dakhla",
    address: "La Crique Nature & Spa, Foum Labouir, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Built using traditional sand-and-clay methods to create bio-climatic domes, La Crique is a unique architectural landmark on the Atlantic coast of Dakhla.",
    neighborhoodOverview: "Foum Labouir is Dakhla’s Atlantic surf coast, known for cliffs, waves, sea views, and a quieter setting than the kite-heavy lagoon camps.",
    hiddenFeesNotice: "Rates are typically Half Board or Full Board.",
    pros: ["Unique and stunning architecture", "Direct access to the surf beach", "Excellent spa facilities"],
    cons: ["Away from the flat kiting lagoon", "Can be windy on the cliffs"],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.8,
      staff: 9.5,
      value: 8.4,
      comfort: 9.7,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free valet",
      contact: "+212 528 214 012",
    },
    roomFeatures: ["dome-ceilings", "ocean-view", "private-balcony", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Superior Dome",
              price: 290,
              beds: "1 King",
              size: "35m²",
            },
      {
              name: "Royal Suite",
              price: 450,
              beds: "1 King",
              size: "65m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dakhla Airport",
              distance: "5km",
              time: "10 min drive",
              icon: "airport",
            },
      {
              label: "Foum Labouir Surf Beach",
              distance: "100m",
              time: "2 min walk",
              icon: "beach",
            },
    ],
    cancellationPolicy: "Moderate 14-day",
    childPolicy: "Children welcome, best for families with older children",
    officialWebsite: "https://lacrique-dakhla.com",
    instagramHandle: "@lacrique_dakhla",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Safe, quiet, and perfect for a surfing focused solo trip.",
      couples: "The most unique and romantic oceanfront escape in Dakhla.",
      families: "Great for families with teenagers who want to surf.",
      business: "Good WiFi and inspiring ocean views for creative work.",
      nomad: "A beautiful spot to work while overlooking the Atlantic surf.",
    },
    tags: ["5-star", "pool", "spa", "private-beach", "desert-camps", "airport-shuttle", "lagoon-view", "family-favorite"]
  },
  {
    id: "da-sleep-7",
    city: "dakhla",
    name: "PK25 Dakhla",
    type: "guesthouse",
    neighborhood: "Dakhla Lagoon",
    description: "A stylish eco-lodge featuring chic, modern bungalows set directly along the water's edge. It provides a relaxed, cozy atmosphere built around a world-class water sports center.",
    pricePerNight: 220,
    lifestyle: "balanced",
    amenities: ["Beachfront Access", "Duotone Surf Center", "Outdoor Lounge", "All-Inclusive Dining", "lagoon-view", "kitesurf-hotels", "on-the-beach", "all-inclusive", "airport-shuttle"],
    googleRating: 4.7,
    googleReviewCount: 500,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 220,
    bookingRating: 4.6,
    bookingReviewCount: 300,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 80,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: false,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "friends"],
    tip: "Opt for a front-row bungalow to step straight from your private terrace onto the sand every morning.",
    vibeTags: ["Stylish", "Beachfront", "Kitesurf", "Relaxed"],
    locationSummary: "Dakhla Waterfront & Peninsula",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=PK25+Dakhla",
    address: "PK25 Dakhla, Dakhla Lagoon, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "PK25 was designed as a chic lagoon camp where comfort and kitesurf culture meet directly on the sand.",
    neighborhoodOverview: "Dakhla Lagoon is a remote, wind-swept water-sports zone with shallow turquoise water, steady trade winds, and isolated camps where private transfers are the normal way to move around.",
    hiddenFeesNotice: "Taxes and meals are often included in package rates; confirm lessons and equipment separately.",
    pros: ["Front-row lagoon setting", "Stylish bungalows", "Good water-sports center"],
    cons: ["No pool", "Remote from town nightlife"],
    trustScores: {
      cleanliness: 9.5,
      safety: 9.6,
      staff: 9.6,
      value: 9.1,
      comfort: 9.4,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 528 000 000",
    },
    roomFeatures: ["private-terrace", "lagoon-view", "natural-ventilation", "shower-ensuite"],
    roomTypes: [
      {
              name: "Lagoon Bungalow",
              price: 220,
              beds: "1 Queen",
              size: "25m²",
            },
      {
              name: "Front Row Bungalow",
              price: 280,
              beds: "1 King",
              size: "30m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dakhla Airport",
              distance: "25km",
              time: "30 min drive",
              icon: "airport",
            },
      {
              label: "Dragon Island",
              distance: "8km",
              time: "15 min boat/drive",
              icon: "beach",
            },
    ],
    cancellationPolicy: "Moderate 7-day",
    childPolicy: "Children welcome, but best for older kids and active travelers",
    officialWebsite: "https://pk25dakhla.com",
    instagramHandle: "@pk25dakhla",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A relaxed and social base for solo kiters.",
      couples: "Great for active couples who want a stylish but informal camp.",
      families: "Better for older children comfortable with a sport-camp setup.",
      business: "WiFi is practical for light work in common areas.",
      nomad: "Good for nomads who want to kite daily and work between sessions.",
    },
    coordinates: {
      lat: 23.901666,
      lng: -15.785099
    },
    tags: ["lagoon-view", "kitesurf-hotels", "on-the-beach", "all-inclusive", "airport-shuttle"]
  },
  {
    id: "da-sleep-8",
    city: "dakhla",
    name: "Dakhla Club Hotel & Spa",
    type: "hotel",
    neighborhood: "Dakhla Lagoon",
    description: "A modern resort combining sleek architecture with a highly active kitesurfing environment on the lagoon. It features an on-site spa and beautiful outdoor spaces for a balanced, comfortable stay.",
    pricePerNight: 260,
    lifestyle: "premium",
    amenities: ["Freshwater Outdoor Pool", "KBC Kite Center", "Fitness Center", "Wellness Spa", "pool", "spa", "lagoon-view", "kitesurf-hotels", "all-inclusive", "private-beach", "airport-shuttle"],
    googleRating: 4.7,
    googleReviewCount: 800,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 350,
    bookingRating: 4.6,
    bookingReviewCount: 500,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 120,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "friends", "business-friendly"],
    tip: "Take advantage of the hotel's on-site gym and wellness spa to soothe your muscles after a long day of kiting.",
    vibeTags: ["Modern", "Sporty", "Spa", "Lagoon-Resort"],
    locationSummary: "Dakhla Waterfront & Peninsula",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Dakhla+Club+Hotel+%26+Spa",
    address: "Dakhla Club Hotel & Spa, Dakhla Lagoon, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Dakhla Club helped define the modern lagoon resort format in Dakhla by combining hotel comforts with serious kitesurf infrastructure.",
    neighborhoodOverview: "Dakhla Lagoon is a remote, wind-swept water-sports zone with shallow turquoise water, steady trade winds, and isolated camps where private transfers are the normal way to move around.",
    hiddenFeesNotice: "City tax and some activities may not be included; confirm full-board and transfer details.",
    pros: ["Strong resort facilities", "Good pool and spa", "Professional kite center"],
    cons: ["Remote from town", "Can feel busy during kite season"],
    trustScores: {
      cleanliness: 9.5,
      safety: 9.6,
      staff: 9.6,
      value: 8.5,
      comfort: 9.4,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 528 000 000",
    },
    roomFeatures: ["lagoon-view", "workspace", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Standard Bungalow",
              price: 260,
              beds: "1 Queen",
              size: "28m²",
            },
      {
              name: "Family Bungalow",
              price: 340,
              beds: "1 Queen + 2 Twin",
              size: "42m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dakhla Airport",
              distance: "28km",
              time: "30 min drive",
              icon: "airport",
            },
      {
              label: "Kite Beach",
              distance: "Direct",
              time: "1 min walk",
              icon: "beach",
            },
    ],
    cancellationPolicy: "Moderate 7-day",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://www.dakhlaclub.com",
    instagramHandle: "@dakhlaclub",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Safe and energetic with plenty of other kiters around.",
      couples: "Good mix of sport, spa, and comfort for active couples.",
      families: "One of the better lagoon options for families thanks to pool and space.",
      business: "Reliable enough for light work between activities.",
      nomad: "A practical premium camp for nomads who need better facilities.",
    },
    coordinates: {
      lat: 23.694045,
      lng: -15.933445
    },
    tags: ["pool", "spa", "lagoon-view", "kitesurf-hotels", "all-inclusive", "private-beach", "airport-shuttle", "family-favorite"]
  },
  {
    id: "da-sleep-9",
    city: "dakhla",
    name: "White Dune Canyon",
    type: "guesthouse",
    neighborhood: "Dakhla Lagoon",
    description: "An intimate eco-lodge nestled near the desert canyons, offering panoramic views of the turquoise lagoon. Its focus on quiet luxury and harmony with nature ensures a deeply restful stay.",
    pricePerNight: 240,
    lifestyle: "balanced",
    amenities: ["Panoramic Lagoon Views", "Outdoor Pool", "Kitesurf Access", "Organic Garden Cuisine", "pool", "desert-camps", "lagoon-view", "kitesurf-hotels", "all-inclusive", "airport-shuttle"],
    googleRating: 4.7,
    googleReviewCount: 120,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 50,
    bookingRating: 4.6,
    bookingReviewCount: 80,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 20,
    hasPool: true,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: false,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "friends"],
    tip: "This property is great for those looking for seclusion; go on a morning walk through the surrounding limestone canyons.",
    vibeTags: ["Secluded", "Canyon-Views", "Eco", "Quiet"],
    locationSummary: "Dakhla Waterfront & Peninsula",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=White+Dune+Canyon+Dakhla",
    address: "White Dune Canyon, Dakhla Lagoon, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "White Dune Canyon was created for travelers seeking the dramatic meeting point of lagoon, desert, and limestone formations.",
    neighborhoodOverview: "This secluded lagoon-canyon area is best for travelers who want silence, big views, and easy access to desert excursions rather than nightlife.",
    hiddenFeesNotice: "Taxes are typically included; excursions and kite lessons may be extra.",
    pros: ["Beautiful views", "Quiet and intimate", "Great access to nature walks"],
    cons: ["Remote from town", "Limited services compared with larger resorts"],
    trustScores: {
      cleanliness: 9.5,
      safety: 9.6,
      staff: 9.6,
      value: 9.1,
      comfort: 9.4,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 528 000 000",
    },
    roomFeatures: ["lagoon-view", "canyon-view", "private-terrace", "natural-ventilation", "shower-ensuite"],
    roomTypes: [
      {
              name: "Canyon Room",
              price: 240,
              beds: "1 Queen",
              size: "28m²",
            },
      {
              name: "Panoramic Suite",
              price: 320,
              beds: "1 King",
              size: "40m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "White Dune",
              distance: "8km",
              time: "12 min drive",
              icon: "beach",
            },
      {
              label: "Dakhla Airport",
              distance: "45km",
              time: "40 min drive",
              icon: "airport",
            },
    ],
    cancellationPolicy: "Moderate 7-day",
    childPolicy: "Children welcome, best for older kids",
    officialWebsite: "https://whitedunecanyon.com",
    instagramHandle: "@whitedunecanyon",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Ideal for solo travelers wanting quiet and nature.",
      couples: "A secluded and romantic desert-lagoon hideaway.",
      families: "Better for older kids who enjoy nature and quiet.",
      business: "Good for creative retreats, not formal business travel.",
      nomad: "Excellent for deep-focus work if you can handle the remote setting.",
    },
    coordinates: {
      lat: 23.807154,
      lng: -15.734392
    },
    tags: ["pool", "desert-camps", "lagoon-view", "kitesurf-hotels", "all-inclusive", "airport-shuttle"]
  },
  {
    id: "da-sleep-10",
    city: "dakhla",
    name: "New Spirit Dakhla",
    type: "guesthouse",
    neighborhood: "Dakhla Lagoon",
    description: "A friendly and budget-friendly surf camp offering cozy bungalows steps from the water. The atmosphere is centered heavily on kiting progress, shared meals, and positive vibes.",
    pricePerNight: 75,
    lifestyle: "lean",
    amenities: ["Lagoon Views", "Kitesurf Lessons", "Traditional Buffet", "Airport Shuttle", "lagoon-view", "kitesurf-hotels", "all-inclusive", "airport-shuttle"],
    googleRating: 4.7,
    googleReviewCount: 200,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 80,
    bookingRating: 4.6,
    bookingReviewCount: 120,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 15,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: false,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ["solo", "friends"],
    tip: "Their all-inclusive packages offer excellent value; consider joining their guided boat trips to remote flat-water kiting spots.",
    vibeTags: ["Budget", "Kitesurf", "Friendly", "Community"],
    locationSummary: "Dakhla Waterfront & Peninsula",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=New+Spirit+Dakhla",
    address: "New Spirit Dakhla, Dakhla Lagoon, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "New Spirit Dakhla focuses on affordable progression for kiters, with shared meals and a camp atmosphere built around the wind forecast.",
    neighborhoodOverview: "Dakhla Lagoon is a remote, wind-swept water-sports zone with shallow turquoise water, steady trade winds, and isolated camps where private transfers are the normal way to move around.",
    hiddenFeesNotice: "Taxes and basic meals are often included; lessons, gear rental, and excursions may cost extra.",
    pros: ["Excellent value packages", "Friendly kite-focused community", "Good for solo travelers"],
    cons: ["Simple rooms", "Remote and not suited to luxury travelers"],
    trustScores: {
      cleanliness: 9.5,
      safety: 9.0,
      staff: 9.6,
      value: 9.5,
      comfort: 9.4,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 528 000 000",
    },
    roomFeatures: ["lagoon-view", "natural-ventilation", "shower-ensuite"],
    roomTypes: [
      {
              name: "Budget Bungalow",
              price: 75,
              beds: "1 Double",
              size: "18m²",
            },
      {
              name: "Shared Kite Room",
              price: 55,
              beds: "Twin beds",
              size: "20m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Kite Beach",
              distance: "Direct",
              time: "1 min walk",
              icon: "beach",
            },
      {
              label: "Dakhla Airport",
              distance: "35km",
              time: "35 min drive",
              icon: "airport",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Not ideal for families with young children",
    officialWebsite: "https://newspiritdakhla.com",
    instagramHandle: "@newspiritdakhla",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "One of the easiest places to meet other budget kiters.",
      couples: "Fun for active couples who do not need luxury.",
      families: "Not ideal for young children due to the camp setup.",
      business: "Basic WiFi is fine for messages, not heavy calls.",
      nomad: "Good for budget nomads who prioritize kiting over comfort.",
    },
    coordinates: {
      lat: 23.90384,
      lng: -15.785464
    },
    tags: ["lagoon-view", "kitesurf-hotels", "all-inclusive", "airport-shuttle", "dorm"]
  },
  {
    id: "da-sleep-11",
    city: "dakhla",
    name: "Oasis Dakhla",
    type: "hotel",
    neighborhood: "Dakhla City Center",
    description: "An elegant, riad-inspired boutique hotel in the city center featuring an expansive terrace with views of the bay. It offers an intimate, authentic atmosphere decorated with refined Moroccan touches.",
    pricePerNight: 110,
    lifestyle: "balanced",
    amenities: ["Lagoon View Terrace", "Infinity Pool", "Traditional Moroccan Hammam", "Private Beach Access", "pool", "spa", "lagoon-view", "rooftop-terrace", "private-beach", "airport-shuttle"],
    googleRating: 4.7,
    googleReviewCount: 110,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 40,
    bookingRating: 4.6,
    bookingReviewCount: 60,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 10,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["couple", "family", "seniors"],
    tip: "Spend your afternoon on the 170m² rooftop terrace with a fresh mint tea to enjoy the breeze and views of the bay.",
    vibeTags: ["Boutique", "Riad-Inspired", "Terrace", "City-Base"],
    locationSummary: "Dakhla Waterfront & Peninsula",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Oasis+Dakhla",
    address: "Oasis Dakhla, Dakhla City Center, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Oasis Dakhla brings riad-inspired design to the far south, creating a more intimate city stay than the remote lagoon camps.",
    neighborhoodOverview: "Dakhla City Center is practical and local, with markets, cafes, banks, the airport, and easy taxi access while still staying close to the bay and promenade.",
    hiddenFeesNotice: "City tax of 17.60 MAD per person/night may not be included.",
    pros: ["Good city-center base", "Beautiful bay-view terrace", "Pool and hammam in town"],
    cons: ["Less immersive for kitesurfers than lagoon camps", "City setting is less secluded"],
    trustScores: {
      cleanliness: 9.5,
      safety: 9.6,
      staff: 9.6,
      value: 9.1,
      comfort: 9.4,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 528 000 000",
    },
    roomFeatures: ["bay-view", "rooftop-access", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Double Room",
              price: 110,
              beds: "1 Queen",
              size: "24m²",
            },
      {
              name: "Terrace Suite",
              price: 160,
              beds: "1 King",
              size: "35m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dakhla Airport",
              distance: "3km",
              time: "7 min drive",
              icon: "airport",
            },
      {
              label: "Dakhla Promenade",
              distance: "500m",
              time: "6 min walk",
              icon: "walk",
            },
    ],
    cancellationPolicy: "Free cancellation up to 24h before check-in",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://oasisdakhla.com",
    instagramHandle: "@oasisdakhla",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Safe and comfortable for solo travelers who prefer staying in town.",
      couples: "A romantic terrace option without being isolated on the lagoon.",
      families: "Practical for families wanting city services nearby.",
      business: "Good for business travelers needing town access.",
      nomad: "Better for nomads who need cafes, errands, and stable town logistics.",
    },
    coordinates: {
      lat: 23.6306,
      lng: -15.8605
    },
    tags: ["pool", "spa", "lagoon-view", "rooftop-terrace", "private-beach", "airport-shuttle", "family-favorite"]
  },
  {
    id: "da-sleep-12",
    city: "dakhla",
    name: "Lagon Energy Dakhla",
    type: "guesthouse",
    neighborhood: "Dakhla Lagoon",
    description: "A Green Key-certified eco-lodge surrounded by desert gardens right on the lagoon's edge. It provides a warm, family-friendly atmosphere with a strong emphasis on sustainability and outdoor living.",
    pricePerNight: 200,
    lifestyle: "balanced",
    amenities: ["Eco-Garden Setting", "Water Sports Center", "On-site Spa Services", "Beachside Dining", "lagoon-view", "kitesurf-hotels", "all-inclusive", "spa", "airport-shuttle", "on-the-beach"],
    googleRating: 4.6,
    googleReviewCount: 400,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 150,
    bookingRating: 4.5,
    bookingReviewCount: 220,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 50,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: false,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["couple", "family", "friends", "seniors"],
    tip: "Visit the nearby ranch to arrange a scenic horseback ride along the shoreline during the golden hour.",
    vibeTags: ["Eco", "Family-Friendly", "Lagoon-Garden", "Relaxed"],
    locationSummary: "Dakhla Waterfront & Peninsula",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Lagon+Energy+Dakhla",
    address: "Lagon Energy Dakhla, Dakhla Lagoon, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Lagon Energy grew around the idea of a greener lagoon camp, combining desert gardens, water sports, and low-impact hospitality.",
    neighborhoodOverview: "Dakhla Lagoon is a remote, wind-swept water-sports zone with shallow turquoise water, steady trade winds, and isolated camps where private transfers are the normal way to move around.",
    hiddenFeesNotice: "Taxes are usually included in package rates; spa treatments and riding excursions may be extra.",
    pros: ["Sustainable feel", "Family-friendly atmosphere", "Good lagoon access"],
    cons: ["No pool", "Remote from town services"],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.6,
      staff: 9.4,
      value: 9.1,
      comfort: 9.2,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 528 000 000",
    },
    roomFeatures: ["garden-view", "lagoon-view", "natural-ventilation", "shower-ensuite"],
    roomTypes: [
      {
              name: "Eco Bungalow",
              price: 200,
              beds: "1 Queen",
              size: "25m²",
            },
      {
              name: "Family Bungalow",
              price: 260,
              beds: "1 Queen + 2 Twin",
              size: "35m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Kite Beach",
              distance: "Direct",
              time: "1 min walk",
              icon: "beach",
            },
      {
              label: "Dakhla Airport",
              distance: "30km",
              time: "35 min drive",
              icon: "airport",
            },
    ],
    cancellationPolicy: "Moderate 7-day",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://lagonenergy.com",
    instagramHandle: "@lagonenergydakhla",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Peaceful and friendly for solo guests who want a softer camp vibe.",
      couples: "Relaxed and romantic if you like eco-style stays.",
      families: "One of the more family-friendly lagoon camps.",
      business: "Good for informal retreats and light work.",
      nomad: "A comfortable balanced option for nomads traveling with family or friends.",
    },
    coordinates: {
      lat: 23.778893,
      lng: -15.900659
    },
    tags: ["lagoon-view", "kitesurf-hotels", "all-inclusive", "spa", "airport-shuttle", "on-the-beach", "family-favorite"]
  },
  {
    id: "da-sleep-13",
    city: "dakhla",
    name: "Westpoint Dakhla",
    type: "guesthouse",
    neighborhood: "Foum Labouir",
    description: "An eco-friendly surf lodge located directly on the Atlantic cliffs, facing the famous Foum Labouir wave spot. It has a relaxed surfer-chic aesthetic with comfortable wooden chalets.",
    pricePerNight: 110,
    lifestyle: "balanced",
    amenities: ["Atlantic Wave Views", "Seawater Swimming Pool", "Surf School", "Oceanfront Restaurant", "pool", "private-beach", "surf-hotels", "kitesurf-hotels", "on-the-beach", "airport-shuttle"],
    googleRating: 4.6,
    googleReviewCount: 450,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 180,
    bookingRating: 4.5,
    bookingReviewCount: 250,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 40,
    hasPool: true,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: false,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "friends"],
    tip: "This is a great spot for wave surfing; check local tide charts to catch the clean right-hand point break right in front of the lodge.",
    vibeTags: ["Surf", "Cliffside", "Eco", "Ocean-Views"],
    locationSummary: "Dakhla Waterfront & Peninsula",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Westpoint+Dakhla",
    address: "Westpoint Dakhla, Foum Labouir, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Westpoint Dakhla was built around the Atlantic wave culture of Foum Labouir, offering a surf-first alternative to lagoon kite camps.",
    neighborhoodOverview: "Foum Labouir is Dakhla’s Atlantic surf coast, known for cliffs, waves, sea views, and a quieter setting than the kite-heavy lagoon camps.",
    hiddenFeesNotice: "Taxes are generally included; surf lessons, board rental, and transfers may be extra.",
    pros: ["Direct surf spot access", "Seawater pool", "Relaxed surfer vibe"],
    cons: ["Not on the flat lagoon", "Wind and ocean swell can be intense"],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.6,
      staff: 9.4,
      value: 9.1,
      comfort: 9.2,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 528 000 000",
    },
    roomFeatures: ["ocean-view", "wooden-chalet", "natural-ventilation", "shower-ensuite"],
    roomTypes: [
      {
              name: "Surf Chalet",
              price: 110,
              beds: "1 Queen",
              size: "24m²",
            },
      {
              name: "Ocean Chalet",
              price: 150,
              beds: "1 King",
              size: "30m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Foum Labouir Wave",
              distance: "Direct",
              time: "1 min walk",
              icon: "surf",
            },
      {
              label: "Dakhla Airport",
              distance: "8km",
              time: "12 min drive",
              icon: "airport",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome, best for older kids and teens",
    officialWebsite: "https://westpointdakhla.com",
    instagramHandle: "@westpointdakhla",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Great for solo surfers looking for a simple oceanfront base.",
      couples: "Active couples will love the wave views and sunsets.",
      families: "Better for teens and families comfortable near surf conditions.",
      business: "Basic for business, but scenic for creative work.",
      nomad: "Good for surf-focused nomads who do not need city convenience.",
    },
    coordinates: {
      lat: 23.768461,
      lng: -15.924448
    },
    tags: ["pool", "private-beach", "surf-hotels", "kitesurf-hotels", "on-the-beach", "airport-shuttle"]
  },
  {
    id: "da-sleep-14",
    city: "dakhla",
    name: "Dakhla Spirit",
    type: "guesthouse",
    neighborhood: "Dakhla Lagoon",
    description: "A cozy and welcoming kite camp offering comfortable bungalows and traditional desert tents right on the lagoon's edge. The vibe is down-to-earth and community-centric, ideal for meeting other travelers.",
    pricePerNight: 130,
    lifestyle: "balanced",
    amenities: ["Lagoon Access", "Kitesurfing Center", "Vibrant Beach Bar", "Daily Yoga Classes", "lagoon-view", "kitesurf-hotels", "desert-camps", "all-inclusive", "rooftop-terrace", "airport-shuttle"],
    googleRating: 4.6,
    googleReviewCount: 320,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 120,
    bookingRating: 4.5,
    bookingReviewCount: 180,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 30,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: false,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "friends"],
    tip: "Head down to the beach bar in the evening to swap tips with other kiters and enjoy the local music events.",
    vibeTags: ["Community", "Kite-Camp", "Yoga", "Down-to-Earth"],
    locationSummary: "Dakhla Waterfront & Peninsula",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Dakhla+Spirit",
    address: "Dakhla Spirit, Dakhla Lagoon, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Dakhla Spirit keeps the classic kite-camp spirit alive with communal meals, beach-bar evenings, and a focus on simple lagoon living.",
    neighborhoodOverview: "Dakhla Lagoon is a remote, wind-swept water-sports zone with shallow turquoise water, steady trade winds, and isolated camps where private transfers are the normal way to move around.",
    hiddenFeesNotice: "Taxes and meals are often included; lessons, equipment, and excursions may cost extra.",
    pros: ["Friendly camp atmosphere", "Good kitesurf access", "Yoga and social events"],
    cons: ["Simple comfort level", "Can be lively around the bar"],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.6,
      staff: 9.4,
      value: 9.1,
      comfort: 9.2,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 528 000 000",
    },
    roomFeatures: ["lagoon-view", "natural-ventilation", "rooftop-access", "shower-ensuite"],
    roomTypes: [
      {
              name: "Lagoon Bungalow",
              price: 130,
              beds: "1 Queen",
              size: "22m²",
            },
      {
              name: "Desert Tent",
              price: 95,
              beds: "2 Twin",
              size: "18m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Kite Beach",
              distance: "Direct",
              time: "1 min walk",
              icon: "beach",
            },
      {
              label: "Dakhla Airport",
              distance: "30km",
              time: "35 min drive",
              icon: "airport",
            },
    ],
    cancellationPolicy: "Moderate 7-day",
    childPolicy: "Children welcome, best for older kids",
    officialWebsite: "https://dakhlaspirit.com",
    instagramHandle: "@dakhlaspirit",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Easy to meet other travelers and join kite sessions.",
      couples: "Fun for active couples who enjoy a communal atmosphere.",
      families: "Better for older children than young kids.",
      business: "Works for light laptop tasks in common areas.",
      nomad: "A sociable base for nomads who want community more than quiet luxury.",
    },
    coordinates: {
      lat: 23.90384,
      lng: -15.785464
    },
    tags: ["lagoon-view", "kitesurf-hotels", "desert-camps", "all-inclusive", "rooftop-terrace", "airport-shuttle"]
  },
  {
    id: "da-sleep-15",
    city: "dakhla",
    name: "Kite House Dakhla",
    type: "guesthouse",
    neighborhood: "Dakhla City Center",
    description: "A uniquely decorated, artistic guesthouse offering gorgeous views of the lagoon and a warm, homey vibe. Guests are welcomed with attentive hospitality and a peaceful atmosphere near the heart of town.",
    pricePerNight: 65,
    lifestyle: "lean",
    amenities: ["Lagoon Views", "Sun Terrace", "Artistic Decor", "Traditional Breakfast", "kitesurf-hotels", "lagoon-view", "airport-shuttle", "rooftop-terrace"],
    googleRating: 4.6,
    googleReviewCount: 210,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 80,
    bookingRating: 4.5,
    bookingReviewCount: 110,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 20,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: false,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "friends"],
    tip: "A highly cost-effective choice for solo travelers; the shared common space is a friendly place to meet other water sports enthusiasts.",
    vibeTags: ["Artistic", "Homey", "Budget", "Lagoon-View"],
    locationSummary: "Dakhla Waterfront & Peninsula",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Kite+House+Dakhla",
    address: "Kite House Dakhla, Dakhla City Center, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Kite House Dakhla channels the personality of a local home into a practical base for independent kiters staying in town.",
    neighborhoodOverview: "Dakhla City Center is practical and local, with markets, cafes, banks, the airport, and easy taxi access while still staying close to the bay and promenade.",
    hiddenFeesNotice: "Taxes are typically included; airport transfers and excursions may be extra.",
    pros: ["Excellent value", "Friendly common spaces", "Good town access"],
    cons: ["No pool", "Requires transfer to lagoon kite spots"],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.0,
      staff: 9.4,
      value: 9.5,
      comfort: 9.2,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 528 000 000",
    },
    roomFeatures: ["lagoon-view", "sun-terrace", "traditional-decor", "shower-ensuite"],
    roomTypes: [
      {
              name: "Double Room",
              price: 65,
              beds: "1 Queen",
              size: "18m²",
            },
      {
              name: "Twin Room",
              price: 55,
              beds: "2 Twin",
              size: "18m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dakhla Center",
              distance: "500m",
              time: "6 min walk",
              icon: "city",
            },
      {
              label: "Dakhla Airport",
              distance: "4km",
              time: "8 min drive",
              icon: "airport",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome",
    officialWebsite: "https://kitehouse-dakhla.com",
    instagramHandle: "@kitehousedakhla",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A friendly budget base for solo kiters in town.",
      couples: "Simple and homey for couples on a budget.",
      families: "Better for independent families than resort-seeking families.",
      business: "Good for basic work thanks to town access.",
      nomad: "A cost-effective nomad base if you plan to work in town and kite by shuttle.",
    },
    coordinates: {
      lat: 23.735002,
      lng: -15.915758
    },
    tags: ["kitesurf-hotels", "lagoon-view", "airport-shuttle", "rooftop-terrace"]
  },
  {
    id: "da-sleep-16",
    city: "dakhla",
    name: "Ocean Vagabond Lassarga",
    type: "guesthouse",
    neighborhood: "Lassarga",
    description: "A rustic eco-lodge located at the southern tip of the peninsula where the ocean meets the lagoon. It features wooden bungalows and a relaxed, adventure-driven castaway vibe.",
    pricePerNight: 190,
    lifestyle: "balanced",
    amenities: ["Beachfront Access", "Surf and Foil Center", "Eco-Friendly Cabins", "Oceanfront Terrace", "on-the-beach", "private-beach", "kitesurf-hotels", "surf-hotels", "all-inclusive", "airport-shuttle"],
    googleRating: 4.5,
    googleReviewCount: 250,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 110,
    bookingRating: 4.4,
    bookingReviewCount: 150,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 30,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: false,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "countryside",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "friends"],
    tip: "Lassarga is famous for its long, peeling wave, making it an excellent spot for wave riding and strapless kiting.",
    vibeTags: ["Castaway", "Surf", "Eco", "Adventure"],
    locationSummary: "Dakhla Lagoon / Kitesurf Bay",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Ocean+Vagabond+Lassarga+Dakhla",
    address: "Ocean Vagabond Lassarga, Lassarga, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Ocean Vagabond Lassarga celebrates the wild southern edge of Dakhla, where wave riding, foiling, and ocean exploration shape the day.",
    neighborhoodOverview: "Lassarga sits at the southern tip of the Dakhla peninsula, remote and ocean-facing, with a wilder beach atmosphere than the protected lagoon.",
    hiddenFeesNotice: "Taxes and meals are often included; lessons, rentals, and transfers may be extra.",
    pros: ["Excellent wave access", "Adventure-driven atmosphere", "Beautiful remote setting"],
    cons: ["Far from town", "Rustic comfort level"],
    trustScores: {
      cleanliness: 9.1,
      safety: 9.6,
      staff: 9.2,
      value: 9.1,
      comfort: 9.0,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 528 000 000",
    },
    roomFeatures: ["ocean-view", "wooden-cabin", "natural-ventilation", "shower-ensuite"],
    roomTypes: [
      {
              name: "Eco Cabin",
              price: 190,
              beds: "1 Queen",
              size: "24m²",
            },
      {
              name: "Family Cabin",
              price: 260,
              beds: "1 Queen + 2 Twin",
              size: "34m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Lassarga Beach",
              distance: "Direct",
              time: "1 min walk",
              icon: "beach",
            },
      {
              label: "Dakhla Center",
              distance: "15km",
              time: "20 min drive",
              icon: "city",
            },
    ],
    cancellationPolicy: "Moderate 7-day",
    childPolicy: "Children welcome, best for older kids",
    officialWebsite: "https://oceanvagabond.com",
    instagramHandle: "@oceanvagabondlassarga",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A memorable solo base for wave riders and adventurous travelers.",
      couples: "Romantic in a wild, barefoot way for active couples.",
      families: "Better for outdoorsy families with older kids.",
      business: "Not a business hotel, but scenic for creative work.",
      nomad: "Good for nomads who want surf, remoteness, and a castaway rhythm.",
    },
    coordinates: {
      lat: 23.634622,
      lng: -15.99804
    },
    tags: ["on-the-beach", "private-beach", "kitesurf-hotels", "surf-hotels", "all-inclusive", "airport-shuttle"]
  },
  {
    id: "da-sleep-17",
    city: "dakhla",
    name: "Dar Rio Oro",
    type: "guesthouse",
    neighborhood: "Dakhla City Center",
    description: "A warm, family-run guesthouse known for its exceptional hospitality and comfortable, spacious rooms overlooking the lagoon. The atmosphere is cozy, welcoming, and feels like a home away from home.",
    pricePerNight: 50,
    lifestyle: "lean",
    amenities: ["Lagoon View Terrace", "Spacious Rooms", "Traditional Breakfast", "Airport Shuttle", "lagoon-view", "rooftop-terrace", "airport-shuttle"],
    googleRating: 4.5,
    googleReviewCount: 170,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 60,
    bookingRating: 4.4,
    bookingReviewCount: 90,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 15,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: false,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "friends", "seniors"],
    tip: "Ask the wonderful host Fatima for her local recommendations, especially for dining at the nearby oyster farms.",
    vibeTags: ["Family-Run", "Warm", "Budget", "Lagoon-View"],
    locationSummary: "Dakhla Waterfront & Peninsula",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Dar+Rio+Oro+Dakhla",
    address: "Dar Rio Oro, Dakhla City Center, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Dar Rio Oro is a small family-run guesthouse built around hospitality, simple comfort, and local knowledge of Dakhla.",
    neighborhoodOverview: "Dakhla City Center is practical and local, with markets, cafes, banks, the airport, and easy taxi access while still staying close to the bay and promenade.",
    hiddenFeesNotice: "Taxes are typically included; confirm airport shuttle timing before arrival.",
    pros: ["Wonderful hospitality", "Great value", "Spacious rooms for the price"],
    cons: ["No pool", "Requires transfer to kite spots"],
    trustScores: {
      cleanliness: 9.1,
      safety: 9.6,
      staff: 9.2,
      value: 9.5,
      comfort: 9.0,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 528 000 000",
    },
    roomFeatures: ["lagoon-view", "rooftop-access", "traditional-decor", "shower-ensuite"],
    roomTypes: [
      {
              name: "Double Room",
              price: 50,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Triple Room",
              price: 70,
              beds: "1 Queen + 1 Single",
              size: "26m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dakhla Center",
              distance: "400m",
              time: "5 min walk",
              icon: "city",
            },
      {
              label: "Dakhla Airport",
              distance: "4km",
              time: "8 min drive",
              icon: "airport",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://dar-rio-oro.com",
    instagramHandle: "@dar_rio_oro",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A welcoming and safe choice for solo travelers on a budget.",
      couples: "Simple and warm for couples who prefer guesthouses.",
      families: "Good for small families wanting city access.",
      business: "Practical for quick work trips in town.",
      nomad: "A low-cost town base for nomads who arrange their own kite transfers.",
    },
    coordinates: {
      lat: 23.703255,
      lng: -15.925559
    },
    tags: ["lagoon-view", "rooftop-terrace", "airport-shuttle", "family-favorite"]
  },
  {
    id: "da-sleep-18",
    city: "dakhla",
    name: "Boutique Hôtel Albaraka",
    type: "hotel",
    neighborhood: "Dakhla City Center",
    description: "A highly rated, clean boutique hotel situated near the heart of town and the coastal promenade. The vibe is quiet, secure, and offers excellent Moroccan breakfasts with ocean views.",
    pricePerNight: 75,
    lifestyle: "lean",
    amenities: ["Sea-View Breakfast Room", "Central Location", "24-Hour Desk", "Free Airport Shuttle", "airport-shuttle", "rooftop-terrace"],
    googleRating: 4.5,
    googleReviewCount: 120,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 50,
    bookingRating: 4.4,
    bookingReviewCount: 80,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 20,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "seniors"],
    tip: "This hotel is a convenient base for travelers who want to explore Dakhla’s local markets, cafes, and restaurants on foot.",
    vibeTags: ["Clean", "Central", "Practical", "Value"],
    locationSummary: "Dakhla Waterfront & Peninsula",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Boutique+Hotel+Albaraka+Dakhla",
    address: "Boutique Hôtel Albaraka, Dakhla City Center, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Albaraka offers a straightforward boutique-hotel experience for travelers who want reliable comfort and local town life over remote camps.",
    neighborhoodOverview: "Dakhla City Center is practical and local, with markets, cafes, banks, the airport, and easy taxi access while still staying close to the bay and promenade.",
    hiddenFeesNotice: "Taxes are typically included; confirm free airport shuttle availability in advance.",
    pros: ["Clean and secure", "Central walking location", "Good breakfast views"],
    cons: ["No pool", "Less resort-like than lagoon properties"],
    trustScores: {
      cleanliness: 9.1,
      safety: 9.6,
      staff: 9.2,
      value: 9.5,
      comfort: 9.0,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 528 000 000",
    },
    roomFeatures: ["sea-view", "workspace", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 75,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Sea View Room",
              price: 95,
              beds: "1 Queen",
              size: "24m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dakhla Promenade",
              distance: "300m",
              time: "4 min walk",
              icon: "walk",
            },
      {
              label: "Dakhla Airport",
              distance: "3km",
              time: "7 min drive",
              icon: "airport",
            },
    ],
    cancellationPolicy: "Free cancellation up to 24h before check-in",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://hotelalbaraka.ma",
    instagramHandle: "@hotelalbarakadakhla",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Very practical and safe for a solo city stay.",
      couples: "Simple, clean, and central for couples before or after a lagoon camp.",
      families: "Works for small families needing town convenience.",
      business: "Good for business because of central location and 24-hour desk.",
      nomad: "A reliable town base for nomads who need errands, cafes, and airport access.",
    },
    coordinates: {
      lat: 23.702199,
      lng: -15.926604
    },
    tags: ["airport-shuttle", "rooftop-terrace", "family-favorite"]
  },
  {
    id: "da-sleep-19",
    city: "dakhla",
    name: "Dakhla South Bay",
    type: "hotel",
    neighborhood: "Dakhla City Center",
    description: "A sleek and modern hotel offering clean rooms and comfortable facilities along a quiet beach area. It provides a balanced, relaxing experience with excellent service close to the town center.",
    pricePerNight: 120,
    lifestyle: "balanced",
    amenities: ["Private Beach Area", "Outdoor Swimming Pool", "Seaside Restaurant", "Fitness Center", "pool", "on-the-beach", "private-beach", "ocean-view", "airport-shuttle"],
    googleRating: 4.4,
    googleReviewCount: 150,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 70,
    bookingRating: 4.3,
    bookingReviewCount: 100,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 25,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["couple", "family", "friends"],
    tip: "Spend a quiet evening at the private beach loungers, which offer a great viewpoint for watching the birds along the lagoon.",
    vibeTags: ["Modern", "Beach-Area", "Comfortable", "Relaxed"],
    locationSummary: "Dakhla Waterfront & Peninsula",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Dakhla+South+Bay",
    address: "Dakhla South Bay, Dakhla City Center, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Dakhla South Bay was designed for travelers who want modern hotel facilities and beach access without committing to a remote kite camp.",
    neighborhoodOverview: "The south bay city edge is calmer than the center but still close enough for taxis, restaurants, and airport access.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Modern rooms", "Pool and private beach area", "Close to town"],
    cons: ["Less character than boutique camps", "Not directly on the main kite lagoon"],
    trustScores: {
      cleanliness: 8.9,
      safety: 9.6,
      staff: 9.0,
      value: 9.1,
      comfort: 8.8,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 528 000 000",
    },
    roomFeatures: ["sea-view", "workspace", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Sea View Room",
              price: 120,
              beds: "1 Queen",
              size: "26m²",
            },
      {
              name: "Family Room",
              price: 170,
              beds: "1 Queen + 2 Twin",
              size: "36m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Private Beach Area",
              distance: "Direct",
              time: "1 min walk",
              icon: "beach",
            },
      {
              label: "Dakhla Airport",
              distance: "6km",
              time: "10 min drive",
              icon: "airport",
            },
    ],
    cancellationPolicy: "Free cancellation up to 48h before check-in",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://dakhlasouthbay.com",
    instagramHandle: "@dakhlasouthbay",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Safe and comfortable if you prefer a standard hotel.",
      couples: "Good for couples wanting beach time near town.",
      families: "Practical for families thanks to pool and room sizes.",
      business: "A decent option for business travelers needing comfort and access.",
      nomad: "Works well for nomads who prefer hotel infrastructure over camp life.",
    },
    coordinates: {
      lat: 23.766536,
      lng: -15.906809
    },
    tags: ["pool", "on-the-beach", "private-beach", "ocean-view", "airport-shuttle", "family-favorite"]
  },
  {
    id: "da-sleep-20",
    city: "dakhla",
    name: "Tulum Beach Resort Dakhla",
    type: "hotel",
    neighborhood: "Foum Labouir",
    description: "A large, high-end beachfront resort offering extensive premium amenities and direct access to the ocean. The vibe is resort-luxurious and comfortable, making it a solid choice for active families and couples.",
    pricePerNight: 280,
    lifestyle: "premium",
    amenities: ["Two Outdoor Pools", "Beachfront Access", "Fitness Center", "Wellness Spa", "5-star", "pool", "spa", "on-the-beach", "private-beach", "airport-shuttle"],
    googleRating: 4.1,
    googleReviewCount: 290,
    tripadvisorRating: 3.8,
    tripadvisorReviewCount: 150,
    bookingRating: 4.0,
    bookingReviewCount: 200,
    hotelguruRating: 3.9,
    hotelguruReviewCount: 40,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["couple", "family", "friends", "seniors"],
    tip: "Take advantage of the well-equipped gym and on-site spa center for active recovery days between surf sessions.",
    vibeTags: ["Resort", "Beachfront", "Family", "Wellness"],
    locationSummary: "Dakhla Waterfront & Peninsula",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Tulum+Beach+Resort+Dakhla",
    address: "Tulum Beach Resort Dakhla, Foum Labouir, Dakhla 73000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Tulum Beach Resort brings a larger resort model to Dakhla’s Atlantic side, pairing beach access with familiar premium amenities.",
    neighborhoodOverview: "Foum Labouir is Dakhla’s Atlantic surf coast, known for cliffs, waves, sea views, and a quieter setting than the kite-heavy lagoon camps.",
    hiddenFeesNotice: "City tax may not be included; spa treatments and some activities cost extra.",
    pros: ["Large resort facilities", "Two pools and spa", "Good for families and seniors"],
    cons: ["Mixed reviews compared with boutique options", "Can feel less intimate"],
    trustScores: {
      cleanliness: 8.3,
      safety: 9.6,
      staff: 8.4,
      value: 8.5,
      comfort: 8.2,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 528 000 000",
    },
    roomFeatures: ["sea-view", "workspace", "ac", "heating", "balcony", "shower-ensuite"],
    roomTypes: [
      {
              name: "Deluxe Room",
              price: 280,
              beds: "1 King",
              size: "32m²",
            },
      {
              name: "Family Suite",
              price: 390,
              beds: "1 King + 2 Twin",
              size: "55m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Beach",
              distance: "Direct",
              time: "1 min walk",
              icon: "beach",
            },
      {
              label: "Dakhla Airport",
              distance: "8km",
              time: "12 min drive",
              icon: "airport",
            },
    ],
    cancellationPolicy: "Free cancellation up to 48h before check-in",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://tulumbeachresortdakhla.com",
    instagramHandle: "@tulumbeachresortdakhla",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Safe and comfortable for solo travelers who want resort amenities.",
      couples: "Good for couples who like pools, spa, and beachfront comfort.",
      families: "Strong family option thanks to larger facilities and room types.",
      business: "Practical for meetings or work if you need standard hotel services.",
      nomad: "Better for nomads who want comfort and gym access more than camp community.",
    },
    coordinates: {
      lat: 23.771302,
      lng: -15.923677
    },
    tags: ["5-star", "pool", "spa", "on-the-beach", "private-beach", "airport-shuttle", "family-favorite"]
  }
]
