import type { SleepListing } from '../types'

/**
 * SLEEP LISTING DATA TEMPLATE (Copy this for your search agent)
 * -------------------------------------------------------------
 * {
 *   "id": "city-sleep-XX",
 *   "name": "",
 *   "type": "riad | hotel | villa | hostel | apartment | guesthouse",
 *   "neighborhood": "",
 *   "city": "[city]",
 *   "description": "",
 *   "pricePerNight": 0,
 *   "lifestyle": "lean | balanced | premium",
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2', 'url3']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source (replaces single rating/reviewCount)
 *   // ═══════════════════════════════════════════════════
 *   // Search for real ratings from Google, TripAdvisor, Booking.com, and HotelGuru.
 *   // If you cannot find a rating for a specific source, set it to the same value as
 *   // the closest available one so average calculations don't break.
 *
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *   bookingRating: [4.x],
 *   bookingReviewCount: [number],
 *   hotelguruRating: [4.x],
 *   hotelguruReviewCount: [number],
 *
 *   // ═══════════════════════════════════════════════════
 *   // BOOLEAN AMENITIES
 *   // ═══════════════════════════════════════════════════
 *
 *   hasPool: true | false,
 *   hasBreakfast: true | false,
 *   hasAC: true | false,
 *   hasHeating: true | false,
 *   hasRooftop: true | false,
 *   hasEnsuite: true | false,
 *   hasRestaurant: true | false,
 *   hasBar: true | false,
 *   hasGym: true | false,
 *   hasElevator: true | false,
 *   hasLaundryService: true | false,
 *   hasRoomService: true | false,
 *   petFriendly: true | false,
 *   isWheelchairAccessible: true | false,
 *   taxesIncluded: true | false,
 *   freeCancellation: true | false,
 *   kidsStayFree: true | false,
 *
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearMosque: true | false,
 *   safetyLevel: 1 | 2 | 3 | 4 | 5,
 *
 *   // ═══════════════════════════════════════════════════
 *   // TRUST SCORES
 *   // ═══════════════════════════════════════════════════
 *
 *   trustScores: {
 *     cleanliness: [1-10],
 *     safety: [1-10],
 *     staff: [1-10],
 *     value: [1-10],
 *     comfort: [1-10],
 *     location: [1-10]
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   amenities: ['wifi', 'pool', 'ac', 'breakfast', 'spa', 'restaurant', 'gym', 'kitchenette', 'parking', 'bar', 'laundry', 'elevator', 'room-service'],
 *   tip: '[Short insider tip]',
 *   vibeTags: ['Authentic', 'Quiet', 'Modern'],
 *   locationSummary: 'Beachfront | City Center | Medina | Airport Area | Residential | Tourist Zone',
 *   availabilityText: 'Available tonight | Only 2 rooms left | Available on selected dates',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   address: '[Full street address, City, Postal Code, Morocco]',
 *
 *   paymentMethods: ['card', 'cash'],
 *   languagesSpoken: ['Arabic', 'French', 'English', 'Spanish', 'German'],
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   customStory: 'Brief history, owner background, or architecture notes...',
 *   neighborhoodOverview: 'Description of the local atmosphere, safety, and vibe...',
 *   hiddenFeesNotice: 'City tax of XX MAD per person/night not included...',
 *   pros: ['Pro 1', 'Pro 2'],
 *   cons: ['Con 1'],
 *
 *   // ═══════════════════════════════════════════════════
 *   // LOGISTICS
 *   // ═══════════════════════════════════════════════════
 *
 *   logistics: {
 *     checkIn: '14:00 - 22:00',
 *     checkOut: 'Before 11:00',
 *     luggageStorage: 'Free | Paid | None',
 *     parking: 'Free on-site | Nearby public | Valet',
 *     contact: '+212 XXXXXXXXX'
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *   // ROOM FEATURES & TYPES
 *   // ═══════════════════════════════════════════════════
 *
 *   roomFeatures: ['soundproof', 'workspace', 'private-balcony', 'ac', 'heating', 'balcony', 'shower-ensuite', 'sea-view', 'garden-view', 'pool-view'],
 *   roomTypes: [
 *     {
 *       name: 'Double Room',
 *       price: 500,
 *       beds: '1 Queen',
 *       size: '20m2',
 *     }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *   // NEIGHBORHOOD DISTANCES
 *   // ═══════════════════════════════════════════════════
 *
 *   neighborhoodDistances: [
 *     { label: 'Beach', distance: '500m', time: '5 min walk', icon: 'beach' }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   cancellationPolicy: 'Free cancellation up to 24h before check-in | Flexible | Non-refundable',
 *   childPolicy: 'Children welcome | Free under 6 | Extra bed 200 MAD',
 *   officialWebsite: 'https://...',
 *   instagramHandle: '@...',
 *
 *   // googlePlaceId: "PLACE_ID_HERE",
 *
 *   // ═══════════════════════════════════════════════════
 *   // REVIEW HIGHLIGHTS
 *   // ═══════════════════════════════════════════════════
 *
 *   reviewHighlights: {
 *     solo: 'Great insight for solo...',
 *     couples: 'Great for couples...',
 *     families: 'Kid-friendly details...',
 *     business: 'Wi-Fi test details...',
 *     nomad: 'Remote work specific insight...'
 *   }
 * }
 */

export const el_jadidaSleep: SleepListing[] = [
  {
    id: "ej-sleep-1",
    city: "el_jadida",
    name: "Mazagan Beach & Golf Resort",
    type: "hotel",
    neighborhood: "Beachfront",
    description: "A legendary five-star luxury oasis that features breathtaking Atlantic views, sprawling gardens, and world-class leisure facilities. It boasts an 18-hole links golf course, a vibrant casino, a spa, and exceptional fine dining.",
    pricePerNight: 320,
    lifestyle: "premium",
    amenities: ["Links Golf Course", "Direct Beach Access", "Grand Casino", "Heated Swimming Pool"],
    googleRating: 4.6,
    googleReviewCount: 3800,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 1500,
    bookingRating: 4.7,
    bookingReviewCount: 2000,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 500,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "countryside",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "friends", "seniors", "business-friendly"],
    tip: "Walk down to the private beachfront at sunset, or book a round of golf at Morocco's longest links course designed by Gary Player.",
    vibeTags: ["Luxury", "Golf", "Beachfront", "Resort"],
    locationSummary: "Haouzia Coastal Golf Resort",
    availabilityText: "Available tonight - Popular weekends",
    googleMapsUrl: "https://maps.google.com/?q=Mazagan+Beach+Golf+Resort+El+Jadida",
    address: "Mazagan Beach & Golf Resort, Route de Casablanca, El Jadida 24000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Mazagan was built as a flagship Atlantic resort destination, combining Moroccan coastal architecture with a major golf, casino, and family leisure complex.",
    neighborhoodOverview: "El Jadida’s beachfront zone is relaxed and family-friendly, with Atlantic views, beach cafes, easy taxi access, and a calmer resort feel outside the historic ramparts.",
    hiddenFeesNotice: "City tax of 39.60 MAD per person/night not included.",
    pros: ["World-class resort facilities", "Direct beach and golf access", "Excellent for families and events"],
    cons: ["Located outside the historic center", "Premium prices for dining and activities"],
    trustScores: {
      cleanliness: 9.4,
      safety: 9.6,
      staff: 9.2,
      value: 8.2,
      comfort: 9.5,
      location: 9.2,
    },
    logistics: {
      checkIn: "15:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 523 388 000",
    },
    roomFeatures: ["sea-view", "private-balcony", "ac", "heating", "workspace", "soundproof"],
    roomTypes: [
      {
              name: "Deluxe Room",
              price: 320,
              beds: "1 King",
              size: "42m²",
            },
      {
              name: "Family Suite",
              price: 480,
              beds: "1 King + 2 Twin",
              size: "82m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Private Beach",
              distance: "Direct",
              time: "1 min walk",
              icon: "beach",
            },
      {
              label: "Cité Portugaise",
              distance: "12km",
              time: "15 min drive",
              icon: "castle",
            },
      {
              label: "Golf Course",
              distance: "On-site",
              time: "2 min walk",
              icon: "golf",
            },
    ],
    cancellationPolicy: "Free cancellation up to 48h before check-in",
    childPolicy: "Children welcome - kids club and family facilities available",
    officialWebsite: "https://www.mazaganbeachresort.com",
    instagramHandle: "@mazaganbeachresort",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Very secure and comfortable for a solo luxury escape.",
      couples: "A polished romantic resort with sunsets, spa, and fine dining.",
      families: "One of the strongest family resorts on the Atlantic coast.",
      business: "Excellent meeting, event, and retreat facilities.",
      nomad: "Good for premium workations if you want resort infrastructure and quiet rooms.",
    },
    coordinates: {
      lat: 33.281921,
      lng: -8.384253
    },
    tags: ["family-favorite"]
  },
  {
    id: "ej-sleep-2",
    city: "el_jadida",
    name: "Riad Dar El Malaika",
    type: "riad",
    neighborhood: "Cité Portugaise",
    description: "An opulent, former governor's palace built around a spectacular central courtyard garden with a peaceful pond. It provides guests with an exclusive, royal-feeling sanctuary steeped in rich Portuguese and Moroccan history.",
    pricePerNight: 280,
    lifestyle: "premium",
    amenities: ["Stunning Central Garden", "Traditional Fountains", "Plentiful Fresh Breakfast", "Historic Architecture"],
    googleRating: 4.9,
    googleReviewCount: 150,
    tripadvisorRating: 5.0,
    tripadvisorReviewCount: 50,
    bookingRating: 4.9,
    bookingReviewCount: 80,
    hotelguruRating: 4.9,
    hotelguruReviewCount: 20,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "seniors"],
    tip: "Perfect for a romantic retreat; enjoy a candlelit dinner in the magical central courtyard surrounded by classical music.",
    vibeTags: ["Palatial", "Historic", "Romantic", "Garden"],
    locationSummary: "Cité Portugaise (Mazagan)",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Dar+El+Malaika+El+Jadida",
    address: "26 Rue du Docteur Blanc, Cité Portugaise, El Jadida 24010, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Dar El Malaika is set in a former notable residence, preserving the grandeur of El Jadida’s Portuguese-Moroccan heritage through gardens, fountains, and carved details.",
    neighborhoodOverview: "The Cité Portugaise is the UNESCO-listed historic core of El Jadida, known for fortress walls, sea-facing ramparts, the Portuguese Cistern, and atmospheric lanes that are best explored on foot.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Extraordinary courtyard garden", "Highly romantic atmosphere", "Exceptional personal service"],
    cons: ["No pool", "Historic layout has stairs and limited accessibility"],
    trustScores: {
      cleanliness: 9.8,
      safety: 9.8,
      staff: 9.9,
      value: 8.6,
      comfort: 9.7,
      location: 9.7,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 523 344 444",
    },
    roomFeatures: ["traditional-decor", "garden-view", "ac", "heating", "shower-ensuite", "rooftop-access"],
    roomTypes: [
      {
              name: "Garden Suite",
              price: 280,
              beds: "1 King",
              size: "45m²",
            },
      {
              name: "Royal Suite",
              price: 380,
              beds: "1 King",
              size: "65m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Portuguese Cistern",
              distance: "250m",
              time: "3 min walk",
              icon: "monument",
            },
      {
              label: "Ramparts",
              distance: "300m",
              time: "4 min walk",
              icon: "castle",
            },
    ],
    cancellationPolicy: "Moderate 7-day",
    childPolicy: "Children welcome, though atmosphere is best suited for adults",
    officialWebsite: "https://dar-el-malaika.com",
    instagramHandle: "@darelmalaika",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A peaceful and very safe historic sanctuary for solo travelers.",
      couples: "One of the most romantic stays in the city.",
      families: "Better for couples and adults than young families.",
      business: "Quiet enough for focused work, but more of a leisure retreat.",
      nomad: "A beautiful base for slow creative work in a historic setting.",
    },
    coordinates: {
      lat: 33.257073,
      lng: -8.502065
    },
    tags: ["heritage"]
  },
  {
    id: "ej-sleep-3",
    city: "el_jadida",
    name: "Pullman Mazagan Royal Golf & Spa",
    type: "hotel",
    neighborhood: "Beachfront",
    description: "An elegant coastal resort situated directly along a pristine bay just outside the city center. It offers a deeply relaxing atmosphere complete with an 18-hole golf course, a modern spa, and a magnificent pool.",
    pricePerNight: 160,
    lifestyle: "balanced",
    amenities: ["18-Hole Golf Course", "Full-Service Wellness Spa", "Direct Beach Proximity", "Outdoor Swimming Pool"],
    googleRating: 4.1,
    googleReviewCount: 4200,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 1000,
    bookingRating: 4.2,
    bookingReviewCount: 1500,
    hotelguruRating: 4.1,
    hotelguruReviewCount: 300,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "countryside",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "seniors", "business-friendly"],
    tip: "Opt for a sea-view room to enjoy beautiful ocean vistas and try a fresh seafood lunch at their poolside grill restaurant.",
    vibeTags: ["Golf", "Spa", "Beachfront", "Classic"],
    locationSummary: "Haouzia Coastal Golf Resort",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Pullman+Mazagan+Royal+Golf+Spa+El+Jadida",
    address: "Route de Casablanca, El Jadida 24000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "This long-running coastal resort blends golf tradition with classic Moroccan Atlantic hospitality, appealing to travelers who want space and resort amenities.",
    neighborhoodOverview: "El Jadida’s beachfront zone is relaxed and family-friendly, with Atlantic views, beach cafes, easy taxi access, and a calmer resort feel outside the historic ramparts.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Good value for a golf resort", "Large pool and spa", "Quiet coastal setting"],
    cons: ["Some areas may feel dated", "Outside the old town"],
    trustScores: {
      cleanliness: 8.7,
      safety: 9.3,
      staff: 8.8,
      value: 8.6,
      comfort: 8.8,
      location: 8.9,
    },
    logistics: {
      checkIn: "15:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 523 379 100",
    },
    roomFeatures: ["sea-view", "balcony", "workspace", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Classic Room",
              price: 160,
              beds: "1 Queen",
              size: "30m²",
            },
      {
              name: "Sea View Room",
              price: 210,
              beds: "1 King",
              size: "34m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Beach",
              distance: "Direct",
              time: "1 min walk",
              icon: "beach",
            },
      {
              label: "El Jadida Center",
              distance: "7km",
              time: "10 min drive",
              icon: "city",
            },
      {
              label: "Golf Course",
              distance: "On-site",
              time: "2 min walk",
              icon: "golf",
            },
    ],
    cancellationPolicy: "Free cancellation up to 48h before check-in",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://all.accor.com/hotel/2960/index.en.shtml",
    instagramHandle: "@pullmanmazagan",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Comfortable and secure for a solo golf or spa break.",
      couples: "Sea-view rooms and spa make it easy for couples.",
      families: "Good for families who want beach and pool space.",
      business: "Useful for conferences and business stays outside the city.",
      nomad: "A practical resort work base if you want quiet and space.",
    },
    coordinates: {
      lat: 33.25934,
      lng: -8.422949
    },
    tags: ["family-favorite"]
  },
  {
    id: "ej-sleep-4",
    city: "el_jadida",
    name: "Hotel L'Iglesia",
    type: "hotel",
    neighborhood: "Cité Portugaise",
    description: "A uniquely historic hotel housed in a beautifully restored 19th-century Spanish church next to the port. It blends vintage 1930s-1950s decor with majestic maritime and old-town views.",
    pricePerNight: 180,
    lifestyle: "balanced",
    amenities: ["Rooftop Ocean Terrace", "Restored Church Architecture", "Massage & Spa Room", "Retro Designer Lounge"],
    googleRating: 4.4,
    googleReviewCount: 200,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 80,
    bookingRating: 4.5,
    bookingReviewCount: 100,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 40,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "friends"],
    tip: "Head up to the rooftop terrace with a fresh drink to watch the fishing boats enter the historic port below.",
    vibeTags: ["Historic", "Church-Conversion", "Ocean-View", "Retro"],
    locationSummary: "Cité Portugaise - Port View",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Hotel+L%27Iglesia+El+Jadida",
    address: "Cité Portugaise, El Jadida 24010, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "L’Iglesia reimagines a former church as a design-forward heritage hotel, turning maritime history and vintage interiors into a memorable stay.",
    neighborhoodOverview: "The Cité Portugaise is the UNESCO-listed historic core of El Jadida, known for fortress walls, sea-facing ramparts, the Portuguese Cistern, and atmospheric lanes that are best explored on foot.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Unique historic architecture", "Excellent rooftop views", "Memorable vintage design"],
    cons: ["No pool", "Some rooms may feel quirky rather than standard hotel-style"],
    trustScores: {
      cleanliness: 9.0,
      safety: 9.6,
      staff: 9.1,
      value: 9.0,
      comfort: 8.9,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 523 373 777",
    },
    roomFeatures: ["historic-decor", "sea-view", "rooftop-access", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Church Room",
              price: 180,
              beds: "1 Queen",
              size: "28m²",
            },
      {
              name: "Ocean View Suite",
              price: 260,
              beds: "1 King",
              size: "42m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ramparts",
              distance: "100m",
              time: "1 min walk",
              icon: "castle",
            },
      {
              label: "Portuguese Cistern",
              distance: "300m",
              time: "4 min walk",
              icon: "monument",
            },
      {
              label: "Port",
              distance: "200m",
              time: "3 min walk",
              icon: "harbor",
            },
    ],
    cancellationPolicy: "Free cancellation up to 48h before check-in",
    childPolicy: "Children welcome, best for older kids",
    officialWebsite: "https://hotel-liglesia.com",
    instagramHandle: "@hotelliglesia",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Safe, atmospheric, and excellent for solo history lovers.",
      couples: "Very romantic if you enjoy unusual heritage hotels.",
      families: "Better for older children than toddlers due to historic layout.",
      business: "Quiet rooms and central location suit creative work.",
      nomad: "A characterful remote-work base with inspiring rooftop breaks.",
    },
    coordinates: {
      lat: 33.256988,
      lng: -8.501786
    },
    tags: ["heritage"]
  },
  {
    id: "ej-sleep-5",
    city: "el_jadida",
    name: "Riad Soleil d'Orient",
    type: "riad",
    neighborhood: "Cité Portugaise",
    description: "A certified green eco-responsible riad situated just minutes away from the famous Portuguese Cistern. It treats guests to a vibrant central courtyard, refined French-Moroccan cuisine, and peaceful sun loungers.",
    pricePerNight: 95,
    lifestyle: "balanced",
    amenities: ["Portuguese Cistern Proximity", "Eco-Friendly Certification", "Traditional Moroccan Hammam", "Panoramic Solarium Terrace"],
    googleRating: 4.5,
    googleReviewCount: 150,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 60,
    bookingRating: 4.6,
    bookingReviewCount: 80,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 30,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "seniors"],
    tip: "The riad is incredibly close to the legendary Portuguese Cistern; go first thing in the morning to capture the best lighting reflection.",
    vibeTags: ["Eco", "Riad", "Quiet", "Historic"],
    locationSummary: "Cité Portugaise - Near Cistern",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Soleil+d%27Orient+El+Jadida",
    address: "Cité Portugaise, El Jadida 24010, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Soleil d’Orient was designed as an intimate eco-conscious riad, pairing traditional hospitality with greener operations inside the historic city.",
    neighborhoodOverview: "The Cité Portugaise is the UNESCO-listed historic core of El Jadida, known for fortress walls, sea-facing ramparts, the Portuguese Cistern, and atmospheric lanes that are best explored on foot.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Excellent location near the cistern", "Peaceful terrace and hammam", "Eco-minded approach"],
    cons: ["No pool", "Limited accessibility due to riad layout"],
    trustScores: {
      cleanliness: 9.2,
      safety: 9.6,
      staff: 9.3,
      value: 9.0,
      comfort: 9.1,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 523 000 000",
    },
    roomFeatures: ["traditional-decor", "rooftop-access", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Comfort Room",
              price: 95,
              beds: "1 Queen",
              size: "22m²",
            },
      {
              name: "Superior Room",
              price: 125,
              beds: "1 King",
              size: "30m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Portuguese Cistern",
              distance: "250m",
              time: "3 min walk",
              icon: "monument",
            },
      {
              label: "Ramparts",
              distance: "500m",
              time: "6 min walk",
              icon: "castle",
            },
    ],
    cancellationPolicy: "Free cancellation up to 48h before check-in",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riadsoleildorient.com",
    instagramHandle: "@riadsoleildorient",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A calm and safe riad for solo exploration.",
      couples: "Great for couples who want history and quiet.",
      families: "Good for small families, though stairs are typical.",
      business: "Quiet enough for laptop work between sightseeing.",
      nomad: "A balanced riad for nomads who prefer historic atmosphere over hotel amenities.",
    },
    coordinates: {
      lat: 33.256758,
      lng: -8.509275
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "ej-sleep-6",
    city: "el_jadida",
    name: "Zephyr Mazagan",
    type: "hotel",
    neighborhood: "Beachfront",
    description: "A modern 4-star hotel and apartment complex designed across three hectares of lush, manicured gardens. It provides a fantastic beachfront getaway with premium fitness equipment, pristine pools, and stunning ocean views.",
    pricePerNight: 120,
    lifestyle: "balanced",
    amenities: ["Direct Beach Access", "Three Outdoor Swimming Pools", "Narjisse Fitness Club", "Wellness Spa & Hammam"],
    googleRating: 4.2,
    googleReviewCount: 2500,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 800,
    bookingRating: 4.3,
    bookingReviewCount: 1200,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 300,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "countryside",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["couple", "family", "friends", "seniors"],
    tip: "This resort is known for its quiet family vibe; take advantage of the direct pathways that lead straight from the rooms to the beach.",
    vibeTags: ["Modern", "Family", "Beachfront", "Garden"],
    locationSummary: "Haouzia Coastal Golf Resort",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Zephyr+Mazagan+El+Jadida",
    address: "Route de Casablanca, El Jadida 24000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Zephyr Mazagan was built as a modern seaside complex, mixing hotel rooms, apartments, gardens, pools, and wellness facilities for longer Atlantic stays.",
    neighborhoodOverview: "El Jadida’s beachfront zone is relaxed and family-friendly, with Atlantic views, beach cafes, easy taxi access, and a calmer resort feel outside the historic ramparts.",
    hiddenFeesNotice: "City tax of 17.60 MAD per person/night not included.",
    pros: ["Multiple pools", "Direct beach access", "Good for families and longer stays"],
    cons: ["Outside the historic center", "Can feel like an apartment complex rather than a boutique hotel"],
    trustScores: {
      cleanliness: 8.6,
      safety: 9.6,
      staff: 8.7,
      value: 9.0,
      comfort: 8.5,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 523 000 000",
    },
    roomFeatures: ["garden-view", "sea-view", "balcony", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 120,
              beds: "1 Queen",
              size: "28m²",
            },
      {
              name: "Family Apartment",
              price: 180,
              beds: "1 Queen + Sofa",
              size: "55m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Beach",
              distance: "Direct",
              time: "1 min walk",
              icon: "beach",
            },
      {
              label: "Cité Portugaise",
              distance: "8km",
              time: "12 min drive",
              icon: "castle",
            },
    ],
    cancellationPolicy: "Free cancellation up to 48h before check-in",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://zephyr-hotels.com/mazagan",
    instagramHandle: "@zephyrmazagan",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Safe and easy for solo travelers wanting modern comfort.",
      couples: "Good for couples wanting beach and pool time.",
      families: "Strong option for families due to apartments and pools.",
      business: "Useful for longer business stays with parking and space.",
      nomad: "Good for nomads who want apartment-style rooms and gym access.",
    },
    coordinates: {
      lat: 33.254204,
      lng: -8.436855
    },
    tags: ["family-favorite"]
  },
  {
    id: "ej-sleep-7",
    city: "el_jadida",
    name: "Riad Siham",
    type: "riad",
    neighborhood: "Cité Portugaise",
    description: "A beautifully restored traditional riad known for its warm, family-like hospitality and exceptional attention to detail. It provides a cozy, quiet retreat with gorgeous classic decorations and fabulous home-cooked breakfasts.",
    pricePerNight: 75,
    lifestyle: "lean",
    amenities: ["Outstanding Fresh Breakfast", "Cozy Solarium Terrace", "Car Rental Services", "Classic Moroccan Decor"],
    googleRating: 4.7,
    googleReviewCount: 150,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 50,
    bookingRating: 4.8,
    bookingReviewCount: 80,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 20,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "friends"],
    tip: "Ask the helpful host for local dining spots in the old town; she provides excellent recommendations.",
    vibeTags: ["Warm", "Traditional", "Value", "Quiet"],
    locationSummary: "Cité Portugaise (Mazagan)",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Siham+El+Jadida",
    address: "Cité Portugaise, El Jadida 24010, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad Siham is a small hospitality-focused riad, built around personal hosting, traditional details, and a home-style breakfast experience.",
    neighborhoodOverview: "The Cité Portugaise is the UNESCO-listed historic core of El Jadida, known for fortress walls, sea-facing ramparts, the Portuguese Cistern, and atmospheric lanes that are best explored on foot.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Excellent host recommendations", "Great breakfast", "Strong value in the historic zone"],
    cons: ["No pool", "Limited services compared with hotels"],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.6,
      staff: 9.7,
      value: 9.4,
      comfort: 9.5,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 523 000 000",
    },
    roomFeatures: ["traditional-decor", "rooftop-access", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Standard Double",
              price: 75,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Triple Room",
              price: 95,
              beds: "1 Queen + 1 Single",
              size: "26m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Portuguese Cistern",
              distance: "300m",
              time: "4 min walk",
              icon: "monument",
            },
      {
              label: "Ramparts",
              distance: "400m",
              time: "5 min walk",
              icon: "castle",
            },
    ],
    cancellationPolicy: "Free cancellation up to 24h before check-in",
    childPolicy: "Children welcome",
    officialWebsite: "https://riadsiham.com",
    instagramHandle: "@riadsiham",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A friendly and safe choice for solo travelers.",
      couples: "Cozy and personal for couples on a modest budget.",
      families: "Works for small families who like guesthouse stays.",
      business: "Quiet enough for basic laptop work.",
      nomad: "A good-value historic base for slow travel and light remote work.",
    },
    coordinates: {
      lat: 33.190796,
      lng: -8.443665
    },
    tags: []
  },
  {
    id: "ej-sleep-8",
    city: "el_jadida",
    name: "Oceana Mazagan Suites Hotel",
    type: "hotel",
    neighborhood: "Beachfront",
    description: "A modern beachfront hotel offering incredibly spacious suites with separate comfortable living rooms. It features stunning ocean views, a delightful courtyard pool, and exceptional hospitality.",
    pricePerNight: 95,
    lifestyle: "balanced",
    amenities: ["Courtyard Swimming Pool", "Beachfront Location", "Spacious Family Suites", "Halal Moroccan Restaurant"],
    googleRating: 4.4,
    googleReviewCount: 140,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 40,
    bookingRating: 4.5,
    bookingReviewCount: 80,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 20,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "countryside",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["couple", "family", "friends"],
    tip: "Book a sea-view suite to wake up to the sound of breaking waves and look out over the bay.",
    vibeTags: ["Spacious", "Beachfront", "Family", "Modern"],
    locationSummary: "Haouzia Coastal Golf Resort",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Oceana+Mazagan+Suites+Hotel+El+Jadida",
    address: "Boulevard de Suez, El Jadida 24000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Oceana Mazagan focuses on spacious suite-style stays, making the beachfront more practical for families and longer visits.",
    neighborhoodOverview: "El Jadida’s beachfront zone is relaxed and family-friendly, with Atlantic views, beach cafes, easy taxi access, and a calmer resort feel outside the historic ramparts.",
    hiddenFeesNotice: "City tax of 17.60 MAD per person/night not included.",
    pros: ["Very spacious suites", "Beachfront location", "Good family value"],
    cons: ["Limited boutique character", "Pool area is smaller than large resorts"],
    trustScores: {
      cleanliness: 9.0,
      safety: 9.6,
      staff: 9.1,
      value: 9.0,
      comfort: 8.9,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 523 000 000",
    },
    roomFeatures: ["sea-view", "separate-living-area", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Junior Suite",
              price: 95,
              beds: "1 Queen",
              size: "38m²",
            },
      {
              name: "Family Suite",
              price: 145,
              beds: "1 Queen + Sofa",
              size: "60m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Beach",
              distance: "Direct",
              time: "1 min walk",
              icon: "beach",
            },
      {
              label: "Cité Portugaise",
              distance: "2km",
              time: "6 min drive",
              icon: "castle",
            },
    ],
    cancellationPolicy: "Free cancellation up to 48h before check-in",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://oceanamazagan.com",
    instagramHandle: "@oceanamazagan",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Safe and spacious for a solo traveler who wants beachfront value.",
      couples: "Sea-view suites are pleasant for couples.",
      families: "Excellent layout for families needing extra room.",
      business: "Suite space works well for informal work stays.",
      nomad: "A practical option for nomads who want more room and beach access.",
    },
    coordinates: {
      lat: 33.243795,
      lng: -8.4833
    },
    tags: ["family-favorite"]
  },
  {
    id: "ej-sleep-9",
    city: "el_jadida",
    name: "Mia Mazagan Bay",
    type: "hotel",
    neighborhood: "Beachfront",
    description: "A sleek, modern hotel located right next to the municipal beach of El Jadida. It features cozy contemporary rooms, beautiful garden pathways, and a highly welcoming atmosphere.",
    pricePerNight: 95,
    lifestyle: "balanced",
    amenities: ["Beachfront Access", "Outdoor Swimming Pool", "Modern Garden Area", "Excellent On-site Cafe"],
    googleRating: 4.3,
    googleReviewCount: 300,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 100,
    bookingRating: 4.4,
    bookingReviewCount: 150,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 50,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "countryside",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Enjoy a morning jog along the beachfront promenade directly outside the hotel gates.",
    vibeTags: ["Modern", "Beachfront", "Garden", "Casual"],
    locationSummary: "Haouzia Coastal Golf Resort",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Mia+Mazagan+Bay+El+Jadida",
    address: "Boulevard Mohammed VI, El Jadida 24000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Mia Mazagan Bay brings a contemporary, casual hotel style to the municipal beachfront, focusing on easy beach access and friendly service.",
    neighborhoodOverview: "El Jadida’s beachfront zone is relaxed and family-friendly, with Atlantic views, beach cafes, easy taxi access, and a calmer resort feel outside the historic ramparts.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Easy beach access", "Modern rooms", "Welcoming atmosphere"],
    cons: ["Can be busy around the public beach", "Rooms are cozy rather than large"],
    trustScores: {
      cleanliness: 8.8,
      safety: 9.6,
      staff: 8.9,
      value: 9.0,
      comfort: 8.7,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 523 000 000",
    },
    roomFeatures: ["garden-view", "ac", "heating", "workspace", "shower-ensuite"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 95,
              beds: "1 Queen",
              size: "22m²",
            },
      {
              name: "Garden View Room",
              price: 115,
              beds: "1 King",
              size: "26m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Municipal Beach",
              distance: "Direct",
              time: "1 min walk",
              icon: "beach",
            },
      {
              label: "Cité Portugaise",
              distance: "2km",
              time: "6 min drive",
              icon: "castle",
            },
    ],
    cancellationPolicy: "Free cancellation up to 48h before check-in",
    childPolicy: "Children welcome",
    officialWebsite: "https://miamazaganbay.com",
    instagramHandle: "@miamazaganbay",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and easy beachfront base for solo travelers.",
      couples: "Good for casual couples who want beach walks.",
      families: "Works for families wanting beach proximity.",
      business: "Fine for short work trips with town access.",
      nomad: "A simple beachside base for remote workers who prefer modern rooms.",
    },
    coordinates: {
      lat: 33.244428,
      lng: -8.48919
    },
    tags: ["family-favorite"]
  },
  {
    id: "ej-sleep-10",
    city: "el_jadida",
    name: "ibis El Jadida",
    type: "hotel",
    neighborhood: "City Center",
    description: "A reliable and clean beachfront hotel that combines comfort with exceptional cost-effectiveness. It features a lively bar, a lovely sun terrace with a pool, and is just a short walk to local dining places.",
    pricePerNight: 55,
    lifestyle: "lean",
    amenities: ["Outdoor Swimming Pool", "Sun Terrace", "Lively Bar & Lounge", "Central Location Access"],
    googleRating: 4.0,
    googleReviewCount: 1200,
    tripadvisorRating: 3.5,
    tripadvisorReviewCount: 400,
    bookingRating: 3.8,
    bookingReviewCount: 600,
    hotelguruRating: 4.0,
    hotelguruReviewCount: 150,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "friends", "business-friendly"],
    tip: "An excellent pet-friendly choice if you are traveling with a dog and want easy walking access to the beach and town.",
    vibeTags: ["Reliable", "Budget", "Pet-Friendly", "Central"],
    locationSummary: "Cité Portugaise (Mazagan)",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=ibis+El+Jadida",
    address: "Place Nour El Kamar, Route de Casablanca, El Jadida 24000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "ibis El Jadida provides the dependable Accor budget-hotel formula in a practical beach-and-city location.",
    neighborhoodOverview: "El Jadida City Center is practical and local, with cafes, shops, transport, and quick taxi access to both the beach promenade and the Portuguese City.",
    hiddenFeesNotice: "City tax of 17.60 MAD per person/night not included.",
    pros: ["Reliable budget choice", "Pool for the price", "Pet-friendly and practical"],
    cons: ["Compact rooms", "Basic service level compared with riads and resorts"],
    trustScores: {
      cleanliness: 8.2,
      safety: 9.6,
      staff: 8.3,
      value: 9.4,
      comfort: 8.1,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 523 379 500",
    },
    roomFeatures: ["workspace", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 55,
              beds: "1 Double",
              size: "18m²",
            },
      {
              name: "Twin Room",
              price: 60,
              beds: "2 Twin",
              size: "18m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Beach",
              distance: "300m",
              time: "4 min walk",
              icon: "beach",
            },
      {
              label: "Cité Portugaise",
              distance: "1.5km",
              time: "5 min drive",
              icon: "castle",
            },
    ],
    cancellationPolicy: "Free cancellation up to 24h before check-in",
    childPolicy: "Children welcome",
    officialWebsite: "https://all.accor.com/hotel/2032/index.en.shtml",
    instagramHandle: "@ibiseljadida",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Practical and safe for a solo budget stop.",
      couples: "Good for couples needing a simple overnight near the beach.",
      families: "Rooms are compact, better for short family stays.",
      business: "Reliable for business travelers on a budget.",
      nomad: "A predictable budget base with usable WiFi and easy town access.",
    },
    coordinates: {
      lat: 33.244359,
      lng: -8.488484
    },
    tags: []
  },
  {
    id: "ej-sleep-11",
    city: "el_jadida",
    name: "A Casa da mare",
    type: "hotel",
    neighborhood: "Cité Portugaise",
    description: "A recently renovated seaside guest house situated inside the historical fortress walls of El Jadida. It provides a cozy, maritime atmosphere with unmatched harbor views from its panoramic shared lounge.",
    pricePerNight: 50,
    lifestyle: "lean",
    amenities: ["Spectacular Harbor Views", "Portuguese Fortress Location", "Cozy Shared Lounge", "Central Solarium Terrace"],
    googleRating: 4.5,
    googleReviewCount: 800,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 300,
    bookingRating: 4.6,
    bookingReviewCount: 450,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 100,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "friends"],
    tip: "This stay is located directly on the historical walls; enjoy a sunset view over the fishing port from the terrace.",
    vibeTags: ["Maritime", "Historic", "Budget", "Harbor-Views"],
    locationSummary: "Cité Portugaise (Mazagan)",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=A+Casa+da+mare+El+Jadida",
    address: "Cité Portugaise, El Jadida 24010, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "A Casa da mare embraces the seaside identity of the old fortress, offering simple renovated rooms and shared spaces oriented toward the harbor.",
    neighborhoodOverview: "The Cité Portugaise is the UNESCO-listed historic core of El Jadida, known for fortress walls, sea-facing ramparts, the Portuguese Cistern, and atmospheric lanes that are best explored on foot.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Fantastic harbor views", "Excellent value", "Inside the historic walls"],
    cons: ["No pool", "Simple facilities"],
    trustScores: {
      cleanliness: 9.2,
      safety: 9.6,
      staff: 9.3,
      value: 9.4,
      comfort: 9.1,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 523 000 000",
    },
    roomFeatures: ["harbor-view", "rooftop-access", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Double Room",
              price: 50,
              beds: "1 Queen",
              size: "18m²",
            },
      {
              name: "Harbor View Room",
              price: 65,
              beds: "1 Queen",
              size: "22m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ramparts",
              distance: "50m",
              time: "1 min walk",
              icon: "castle",
            },
      {
              label: "Port",
              distance: "200m",
              time: "3 min walk",
              icon: "harbor",
            },
    ],
    cancellationPolicy: "Free cancellation up to 24h before check-in",
    childPolicy: "Children welcome, best for older kids",
    officialWebsite: "https://acasadamare-eljadida.com",
    instagramHandle: "@acasadamare_eljadida",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe, scenic, and affordable base for solo travelers.",
      couples: "Simple but romantic thanks to harbor sunsets.",
      families: "Better for older kids due to historic stairs and compact rooms.",
      business: "Good for light work in the shared lounge.",
      nomad: "A budget-friendly old-town base with inspiring sea views.",
    },
    coordinates: {
      lat: 33.25771,
      lng: -8.501486
    },
    tags: ["heritage"]
  },
  {
    id: "ej-sleep-12",
    city: "el_jadida",
    name: "Riad Zahrat Al Fajr",
    type: "riad",
    neighborhood: "Cité Portugaise",
    description: "A beautifully clean, traditionally designed riad offering spacious guest suites inside the old-town ramparts. Guests will love the peaceful inner courtyard, fresh breakfasts, and deeply hospitable staff.",
    pricePerNight: 55,
    lifestyle: "lean",
    amenities: ["Scenic Old-Town Terrace", "Courtyard Garden Setting", "Plentiful Fresh Breakfast", "Classic Moroccan Tiling"],
    googleRating: 4.5,
    googleReviewCount: 100,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 40,
    bookingRating: 4.6,
    bookingReviewCount: 60,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 20,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Savor their freshly made mint tea on the rooftop during late afternoon for a peaceful view of the Medina roofs.",
    vibeTags: ["Clean", "Traditional", "Rooftop", "Value"],
    locationSummary: "Cité Portugaise (Mazagan)",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Zahrat+Al+Fajr+El+Jadida",
    address: "Cité Portugaise, El Jadida 24010, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad Zahrat Al Fajr keeps the traditional old-town guesthouse experience simple, clean, and focused on hospitality.",
    neighborhoodOverview: "The Cité Portugaise is the UNESCO-listed historic core of El Jadida, known for fortress walls, sea-facing ramparts, the Portuguese Cistern, and atmospheric lanes that are best explored on foot.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Very clean", "Good breakfast", "Great value in the historic zone"],
    cons: ["No pool", "Limited hotel-style amenities"],
    trustScores: {
      cleanliness: 9.2,
      safety: 9.6,
      staff: 9.3,
      value: 9.4,
      comfort: 9.1,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 523 000 000",
    },
    roomFeatures: ["traditional-decor", "rooftop-access", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Traditional Double",
              price: 55,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Family Suite",
              price: 85,
              beds: "1 Queen + 2 Twin",
              size: "35m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Portuguese Cistern",
              distance: "300m",
              time: "4 min walk",
              icon: "monument",
            },
      {
              label: "Ramparts",
              distance: "400m",
              time: "5 min walk",
              icon: "castle",
            },
    ],
    cancellationPolicy: "Free cancellation up to 24h before check-in",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riadzahratalfajr.com",
    instagramHandle: "@riadzahratalfajr",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A clean and safe riad for solo budget travelers.",
      couples: "Simple and peaceful for couples.",
      families: "Good value for families who want a traditional suite.",
      business: "Works for basic work tasks in a quiet setting.",
      nomad: "A budget-friendly riad for slow travelers who work lightly.",
    },
    coordinates: {
      lat: 33.256797,
      lng: -8.502332
    },
    tags: ["family-favorite"]
  },
  {
    id: "ej-sleep-13",
    city: "el_jadida",
    name: "Art Suites El Jadida",
    type: "hotel",
    neighborhood: "City Center",
    description: "A chic boutique hotel presenting beautifully designed rooms that showcase modern art and sleek lines. It sits near the municipal theater, offering a very sophisticated and quiet urban vibe.",
    pricePerNight: 90,
    lifestyle: "balanced",
    amenities: ["Artistic Interior Design", "Panoramic Town Views", "City Center Proximity", "Excellent Business Centre"],
    googleRating: 4.3,
    googleReviewCount: 250,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 80,
    bookingRating: 4.4,
    bookingReviewCount: 120,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 40,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "business-friendly"],
    tip: "An excellent choice for art and design enthusiasts; enjoy the galleries and historic theater just a 5-minute walk away.",
    vibeTags: ["Artistic", "Boutique", "Business", "Central"],
    locationSummary: "Cité Portugaise (Mazagan)",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Art+Suites+El+Jadida",
    address: "20 Bis Avenue Ibn Khaldoun, El Jadida 24000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Art Suites was conceived as a design-led city hotel, using modern artwork and clean lines to stand apart from the old-town riads.",
    neighborhoodOverview: "El Jadida City Center is practical and local, with cafes, shops, transport, and quick taxi access to both the beach promenade and the Portuguese City.",
    hiddenFeesNotice: "City tax of 17.60 MAD per person/night not included.",
    pros: ["Stylish rooms", "Good business facilities", "Central location"],
    cons: ["No pool", "Less atmospheric than the Cité Portugaise"],
    trustScores: {
      cleanliness: 8.8,
      safety: 9.6,
      staff: 8.9,
      value: 9.0,
      comfort: 8.7,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 523 000 000",
    },
    roomFeatures: ["artistic-decor", "workspace", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Art Room",
              price: 90,
              beds: "1 Queen",
              size: "26m²",
            },
      {
              name: "Junior Suite",
              price: 125,
              beds: "1 King",
              size: "38m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Municipal Theatre",
              distance: "300m",
              time: "4 min walk",
              icon: "art",
            },
      {
              label: "Cité Portugaise",
              distance: "1km",
              time: "12 min walk",
              icon: "castle",
            },
    ],
    cancellationPolicy: "Free cancellation up to 48h before check-in",
    childPolicy: "Children welcome, though best suited for adults and business travelers",
    officialWebsite: "https://artsuiteseljadida.com",
    instagramHandle: "@artsuiteseljadida",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Safe, central, and stylish for solo city stays.",
      couples: "Good for couples who like modern boutique design.",
      families: "Better for couples and business guests than young families.",
      business: "One of the more practical city-center business options.",
      nomad: "A solid nomad base with workspace, central errands, and artful interiors.",
    },
    coordinates: {
      lat: 33.250667,
      lng: -8.502677
    },
    tags: []
  },
  {
    id: "ej-sleep-14",
    city: "el_jadida",
    name: "Maison d'hôtes Cité Portugaise",
    type: "riad",
    neighborhood: "Cité Portugaise",
    description: "A charming, authentic guest house featuring traditional stone walls and spectacular rooftop views of the historic ramparts. It is highly prized for its cozy, budget-friendly rooms and highly welcoming hosts.",
    pricePerNight: 40,
    lifestyle: "lean",
    amenities: ["Historic Fortress Walls", "Rooftop Sea View", "Homemade Traditional Breakfast", "Cozy Berber Carpets"],
    googleRating: 4.2,
    googleReviewCount: 300,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 100,
    bookingRating: 4.3,
    bookingReviewCount: 150,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 50,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "friends"],
    tip: "Take a 2-minute walk to the rampart walls in the morning to watch the waves crash against the medieval stone bastions.",
    vibeTags: ["Authentic", "Budget", "Ramparts", "Sea-View"],
    locationSummary: "Cité Portugaise - Ramparts",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Maison+d%27hotes+Cit%C3%A9+Portugaise+El+Jadida",
    address: "Cité Portugaise, El Jadida 24010, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "This guesthouse preserves a humble stone-wall atmosphere inside the old fortress, making it a classic low-cost stay for history-focused travelers.",
    neighborhoodOverview: "The Cité Portugaise is the UNESCO-listed historic core of El Jadida, known for fortress walls, sea-facing ramparts, the Portuguese Cistern, and atmospheric lanes that are best explored on foot.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Very affordable", "Authentic historic setting", "Rooftop sea views"],
    cons: ["Basic rooms", "No elevator or pool"],
    trustScores: {
      cleanliness: 8.6,
      safety: 9.6,
      staff: 8.7,
      value: 9.4,
      comfort: 8.5,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 523 000 000",
    },
    roomFeatures: ["stone-walls", "rooftop-access", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Budget Double",
              price: 40,
              beds: "1 Double",
              size: "16m²",
            },
      {
              name: "Sea View Room",
              price: 55,
              beds: "1 Queen",
              size: "20m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ramparts",
              distance: "100m",
              time: "2 min walk",
              icon: "castle",
            },
      {
              label: "Portuguese Cistern",
              distance: "350m",
              time: "5 min walk",
              icon: "monument",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome, but best for older kids",
    officialWebsite: "https://maisonhotesciteportugaise.com",
    instagramHandle: "@maisonciteportugaise",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and atmospheric budget option for solo travelers.",
      couples: "Simple and authentic for couples who value location over luxury.",
      families: "Not ideal for young children due to stairs and basic facilities.",
      business: "Good for a short budget work stop.",
      nomad: "A low-cost old-town base for light remote work and sightseeing.",
    },
    coordinates: {
      lat: 33.256134,
      lng: -8.502007
    },
    tags: ["heritage"]
  },
  {
    id: "ej-sleep-15",
    city: "el_jadida",
    name: "Zerad",
    type: "riad",
    neighborhood: "City Center",
    description: "An oasis of tranquility located in a peaceful residential pocket of El Jadida. This stylish property features a private swimming pool, lush gardens, and cozy Moroccan decorations.",
    pricePerNight: 85,
    lifestyle: "balanced",
    amenities: ["Private Outdoor Pool", "Lush Manicured Gardens", "Cozy Central Lounge", "Traditional Moroccan Breakfast"],
    googleRating: 4.3,
    googleReviewCount: 150,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 50,
    bookingRating: 4.4,
    bookingReviewCount: 80,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 20,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family"],
    tip: "Ideal for travelers wanting peaceful poolside afternoons away from the busier public beaches.",
    vibeTags: ["Garden", "Pool", "Quiet", "Residential"],
    locationSummary: "Cité Portugaise (Mazagan)",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Zerad+El+Jadida",
    address: "El Jadida 24000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Zerad offers a private guesthouse-style retreat for travelers who prefer gardens and pool time over the bustle of the beach promenade.",
    neighborhoodOverview: "El Jadida City Center is practical and local, with cafes, shops, transport, and quick taxi access to both the beach promenade and the Portuguese City.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Peaceful pool setting", "Good value for a private retreat", "Quiet residential atmosphere"],
    cons: ["Not walking-distance to all sights", "Limited dining on-site"],
    trustScores: {
      cleanliness: 8.8,
      safety: 9.6,
      staff: 8.9,
      value: 9.0,
      comfort: 8.7,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 523 000 000",
    },
    roomFeatures: ["garden-view", "pool-view", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Garden Room",
              price: 85,
              beds: "1 Queen",
              size: "22m²",
            },
      {
              name: "Family Room",
              price: 120,
              beds: "1 Queen + 2 Twin",
              size: "34m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "City Center",
              distance: "2km",
              time: "5 min drive",
              icon: "city",
            },
      {
              label: "Beach",
              distance: "3km",
              time: "8 min drive",
              icon: "beach",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://zerad-eljadida.com",
    instagramHandle: "@zerad_eljadida",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Quiet and secure for solo travelers who want rest.",
      couples: "Peaceful and intimate for couples.",
      families: "Good for families who want a pool and garden.",
      business: "Works for quiet focused work away from traffic.",
      nomad: "A calm guesthouse base for nomads who value outdoor space.",
    },
    coordinates: {
      lat: 33.243331,
      lng: -8.49884
    },
    tags: ["family-favorite"]
  },
  {
    id: "ej-sleep-16",
    city: "el_jadida",
    name: "Riad La Citadelle El Jadida",
    type: "riad",
    neighborhood: "Cité Portugaise",
    description: "A spacious and wonderfully atmospheric riad located within the historic ramparts of the fortress. It features private stone arches, comfortable traditional suites, and a beautiful sea-view terrace.",
    pricePerNight: 75,
    lifestyle: "lean",
    amenities: ["Historic Stone Arches", "Rooftop Ocean Views", "Spacious Family Rooms", "Traditional Courtyard Lounge"],
    googleRating: 4.4,
    googleReviewCount: 80,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 20,
    bookingRating: 4.5,
    bookingReviewCount: 40,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 10,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Take a slow afternoon walk on the ramparts directly adjacent to the riad to experience the sea breeze.",
    vibeTags: ["Historic", "Stone-Arches", "Sea-View", "Family"],
    locationSummary: "Cité Portugaise (Mazagan)",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+La+Citadelle+El+Jadida",
    address: "Cité Portugaise, El Jadida 24010, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad La Citadelle highlights the fortress atmosphere of El Jadida, with stone arches and rooftop views that connect guests directly to the ramparts.",
    neighborhoodOverview: "The Cité Portugaise is the UNESCO-listed historic core of El Jadida, known for fortress walls, sea-facing ramparts, the Portuguese Cistern, and atmospheric lanes that are best explored on foot.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Atmospheric historic setting", "Good family room sizes", "Rooftop ocean views"],
    cons: ["No pool", "Historic stairs and limited accessibility"],
    trustScores: {
      cleanliness: 9.0,
      safety: 9.6,
      staff: 9.1,
      value: 9.4,
      comfort: 8.9,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 523 000 000",
    },
    roomFeatures: ["stone-arches", "sea-view", "rooftop-access", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Traditional Suite",
              price: 75,
              beds: "1 Queen",
              size: "28m²",
            },
      {
              name: "Family Suite",
              price: 110,
              beds: "1 Queen + 2 Twin",
              size: "42m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ramparts",
              distance: "50m",
              time: "1 min walk",
              icon: "castle",
            },
      {
              label: "Portuguese Cistern",
              distance: "300m",
              time: "4 min walk",
              icon: "monument",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riadlacitadelle.com",
    instagramHandle: "@riadlacitadelle",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and memorable solo stay for history lovers.",
      couples: "Romantic if you like old stone and sea air.",
      families: "Good for families needing larger traditional rooms.",
      business: "Fine for quiet laptop work in common spaces.",
      nomad: "An atmospheric base for creative nomads who enjoy historic surroundings.",
    },
    coordinates: {
      lat: 33.253448,
      lng: -8.505156
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "ej-sleep-17",
    city: "el_jadida",
    name: "Amwaj Hotel",
    type: "hotel",
    neighborhood: "Beachfront",
    description: "A comfortable oceanfront hotel offering clean, simple accommodations overlooking the Atlantic beach. It provides easy access to coastal cafes, beachfront sands, and local family entertainment spots.",
    pricePerNight: 60,
    lifestyle: "lean",
    amenities: ["Direct Beach Access", "Stunning Ocean Views", "Beachfront Cafe & Terrace", "On-site Free Parking"],
    googleRating: 3.8,
    googleReviewCount: 350,
    tripadvisorRating: 3.5,
    tripadvisorReviewCount: 150,
    bookingRating: 3.9,
    bookingReviewCount: 200,
    hotelguruRating: 3.8,
    hotelguruReviewCount: 50,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "The municipal beach is right across the street; rent a beach umbrella and enjoy the popular local seaside scene.",
    vibeTags: ["Beachfront", "Budget", "Simple", "Local"],
    locationSummary: "Cité Portugaise (Mazagan)",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Amwaj+Hotel+El+Jadida",
    address: "Boulevard Mohammed VI, El Jadida 24000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Amwaj Hotel serves the classic local beachfront market: simple rooms, ocean views, and quick access to public beach life.",
    neighborhoodOverview: "El Jadida’s beachfront zone is relaxed and family-friendly, with Atlantic views, beach cafes, easy taxi access, and a calmer resort feel outside the historic ramparts.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Affordable beach access", "Ocean views", "Free parking"],
    cons: ["Basic facilities", "Lower ratings than boutique options"],
    trustScores: {
      cleanliness: 7.8,
      safety: 8.9,
      staff: 8.0,
      value: 9.4,
      comfort: 7.7,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 523 000 000",
    },
    roomFeatures: ["ocean-view", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 60,
              beds: "1 Double",
              size: "18m²",
            },
      {
              name: "Ocean View Room",
              price: 80,
              beds: "1 Queen",
              size: "22m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Municipal Beach",
              distance: "Direct",
              time: "1 min walk",
              icon: "beach",
            },
      {
              label: "Cité Portugaise",
              distance: "2km",
              time: "6 min drive",
              icon: "castle",
            },
    ],
    cancellationPolicy: "Free cancellation up to 24h before check-in",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://amwajhotel-eljadida.com",
    instagramHandle: "@amwajhotel",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A simple and safe budget choice by the beach.",
      couples: "Good for couples who mainly need a beach base.",
      families: "Practical for families wanting low-cost beach access.",
      business: "Basic but usable for short work stays.",
      nomad: "A budget beach base for nomads who do not need luxury.",
    },
    coordinates: {
      lat: 33.243963,
      lng: -8.478969
    },
    tags: ["family-favorite"]
  },
  {
    id: "ej-sleep-18",
    city: "el_jadida",
    name: "Riad Ksar El Jadida",
    type: "riad",
    neighborhood: "Cité Portugaise",
    description: "A charming, family-run riad showing off classic Zellij tiles and authentic Moroccan design. It is highly appreciated for its warm hospitality, peaceful central lounge, and delicious local food.",
    pricePerNight: 65,
    lifestyle: "lean",
    amenities: ["Traditional Zellij Tiling", "Cozy Fireplace Lounge", "Terrace with Town Views", "Authentic Moroccan Dining"],
    googleRating: 4.1,
    googleReviewCount: 120,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 40,
    bookingRating: 4.2,
    bookingReviewCount: 60,
    hotelguruRating: 4.1,
    hotelguruReviewCount: 20,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Don't hesitate to request their traditional tagine for dinner, which is slow-cooked over charcoal on the rooftop.",
    vibeTags: ["Zellij", "Family-Run", "Traditional", "Value"],
    locationSummary: "Cité Portugaise (Mazagan)",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Ksar+El+Jadida",
    address: "Cité Portugaise, El Jadida 24010, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad Ksar El Jadida is a classic family-run riad where traditional tilework, a fireplace lounge, and home cooking create a local feel.",
    neighborhoodOverview: "The Cité Portugaise is the UNESCO-listed historic core of El Jadida, known for fortress walls, sea-facing ramparts, the Portuguese Cistern, and atmospheric lanes that are best explored on foot.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Warm family hospitality", "Authentic Moroccan meals", "Good value"],
    cons: ["No pool", "Traditional rooms are simple"],
    trustScores: {
      cleanliness: 8.4,
      safety: 9.6,
      staff: 8.5,
      value: 9.4,
      comfort: 8.3,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 523 000 000",
    },
    roomFeatures: ["zellij-tiles", "fireplace-lounge", "rooftop-access", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 65,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Family Room",
              price: 90,
              beds: "1 Queen + 1 Single",
              size: "28m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Portuguese Cistern",
              distance: "350m",
              time: "5 min walk",
              icon: "monument",
            },
      {
              label: "Ramparts",
              distance: "400m",
              time: "5 min walk",
              icon: "castle",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riadksareljadida.com",
    instagramHandle: "@riadksareljadida",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Safe and welcoming for solo travelers.",
      couples: "Simple and cozy for couples who like traditional riads.",
      families: "Good for families wanting home-cooked meals.",
      business: "Quiet enough for light work outside meal times.",
      nomad: "A modest, authentic base for slow-travel nomads.",
    },
    coordinates: {
      lat: 33.256078,
      lng: -8.501974
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "ej-sleep-19",
    city: "el_jadida",
    name: "Appartement 32 ensoleillé à 5 min de la plage",
    type: "apartment",
    neighborhood: "Beachfront",
    description: "A bright and beautifully kept modern apartment located just minutes from the main beach. It offers travelers complete privacy, fully equipped kitchen facilities, and a highly secure environment.",
    pricePerNight: 65,
    lifestyle: "lean",
    amenities: ["Fully Equipped Kitchen", "Close to the Beach", "High-Speed Wi-Fi", "Spacious Family Layout"],
    googleRating: 4.5,
    googleReviewCount: 70,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 20,
    bookingRating: 4.6,
    bookingReviewCount: 40,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 10,
    hasPool: false,
    hasBreakfast: false,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Perfect for self-catering families; walk to the nearby local market to buy fresh produce and seafood to prepare at home.",
    vibeTags: ["Apartment", "Self-Catering", "Bright", "Family"],
    locationSummary: "Cité Portugaise (Mazagan)",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Appartement+32+ensoleille+5+min+plage+El+Jadida",
    address: "Beach area, El Jadida 24000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "This apartment caters to independent travelers who prefer privacy, a kitchen, and beach proximity over hotel services.",
    neighborhoodOverview: "El Jadida’s beachfront zone is relaxed and family-friendly, with Atlantic views, beach cafes, easy taxi access, and a calmer resort feel outside the historic ramparts.",
    hiddenFeesNotice: "Cleaning fee or city tax may be charged separately depending on platform.",
    pros: ["Fully equipped kitchen", "Good family privacy", "Close to beach"],
    cons: ["No breakfast or reception", "Host check-in required"],
    trustScores: {
      cleanliness: 9.2,
      safety: 9.6,
      staff: 9.3,
      value: 9.4,
      comfort: 9.1,
      location: 9.0,
    },
    logistics: {
      checkIn: "15:00",
      checkOut: "11:00",
      luggageStorage: "None",
      parking: "Nearby public parking",
      contact: "+212 600 000 000",
    },
    roomFeatures: ["kitchen", "workspace", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Entire Apartment",
              price: 65,
              beds: "1 Queen + Sofa",
              size: "55m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Beach",
              distance: "500m",
              time: "5 min walk",
              icon: "beach",
            },
      {
              label: "Local Market",
              distance: "700m",
              time: "8 min walk",
              icon: "market",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "",
    instagramHandle: "@appartement32eljadida",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A private and secure choice for solo travelers wanting independence.",
      couples: "Good for couples who like self-catering stays.",
      families: "Excellent for families needing kitchen and space.",
      business: "High-speed WiFi and a table make it practical for work.",
      nomad: "One of the better budget nomad choices if you want privacy and a kitchen.",
    },
    coordinates: {
      lat: 33.241208,
      lng: -8.485129
    },
    tags: ["family-favorite"]
  },
  {
    id: "ej-sleep-20",
    city: "el_jadida",
    name: "Apprt Ennakhil 3",
    type: "apartment",
    neighborhood: "City Center",
    description: "A pristine, secure apartment in a central residential district of El Jadida. It offers full-day security, a quiet and highly comfortable living environment, and extremely responsive host support.",
    pricePerNight: 60,
    lifestyle: "lean",
    amenities: ["Elevator Access", "Full-Day Property Security", "Modern Kitchen Facilities", "Spacious Living Area"],
    googleRating: 4.6,
    googleReviewCount: 150,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 50,
    bookingRating: 4.7,
    bookingReviewCount: 80,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 20,
    hasPool: false,
    hasBreakfast: false,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "business-friendly"],
    tip: "This modern building features private parking and secure elevators, making it a reliable base if you are traveling with heavy luggage.",
    vibeTags: ["Apartment", "Secure", "Modern", "Central"],
    locationSummary: "Cité Portugaise (Mazagan)",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Apprt+Ennakhil+3+El+Jadida",
    address: "Résidence Ennakhil, El Jadida 24000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Apprt Ennakhil 3 is built for practical independent stays, with modern apartment comforts, secure access, and responsive hosting.",
    neighborhoodOverview: "El Jadida City Center is practical and local, with cafes, shops, transport, and quick taxi access to both the beach promenade and the Portuguese City.",
    hiddenFeesNotice: "Cleaning fee or city tax may be charged separately depending on platform.",
    pros: ["Secure building", "Elevator access", "Good value for families or work stays"],
    cons: ["No hotel services", "Not directly on the beach"],
    trustScores: {
      cleanliness: 9.4,
      safety: 9.6,
      staff: 9.5,
      value: 9.4,
      comfort: 9.3,
      location: 9.0,
    },
    logistics: {
      checkIn: "15:00",
      checkOut: "11:00",
      luggageStorage: "None",
      parking: "Private or nearby parking",
      contact: "+212 600 000 000",
    },
    roomFeatures: ["kitchen", "workspace", "elevator-access", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Entire Apartment",
              price: 60,
              beds: "1 Queen + Sofa",
              size: "60m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "City Center",
              distance: "800m",
              time: "10 min walk",
              icon: "city",
            },
      {
              label: "Beach",
              distance: "2km",
              time: "6 min drive",
              icon: "beach",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "",
    instagramHandle: "@apprtennakhil3",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A secure and private base for solo travelers.",
      couples: "Practical for couples who want an apartment instead of a hotel.",
      families: "Strong budget option for families thanks to kitchen and space.",
      business: "Excellent for work stays with privacy and secure access.",
      nomad: "A practical apartment for nomads needing kitchen, workspace, and quiet.",
    },
    coordinates: {
      lat: 33.243011,
      lng: -8.497185
    },
    tags: ["family-favorite"]
  }
]
