import type { SleepListing } from '../types'

/**
 * SLEEP LISTING DATA TEMPLATE (Copy this for your search agent)
 * -------------------------------------------------------------
 * {
 *   "id": "city-sleep-XX",
 *   "name": "",
 *   "type": "riad | hotel | villa | hostel | apartment | guesthouse",
 *   "neighborhood": "",
 *   "city": "[city]",
 *   "description": "",
 *   "pricePerNight": 0,
 *   "lifestyle": "lean | balanced | premium",
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2', 'url3']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source (replaces single rating/reviewCount)
 *   // ═══════════════════════════════════════════════════
 *   // Search for real ratings from Google, TripAdvisor, Booking.com, and HotelGuru.
 *   // If you cannot find a rating for a specific source, set it to the same value as
 *   // the closest available one so average calculations don't break.
 *
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *   bookingRating: [4.x],
 *   bookingReviewCount: [number],
 *   hotelguruRating: [4.x],
 *   hotelguruReviewCount: [number],
 *
 *   // ═══════════════════════════════════════════════════
 *   // BOOLEAN AMENITIES
 *   // ═══════════════════════════════════════════════════
 *
 *   hasPool: true | false,
 *   hasBreakfast: true | false,
 *   hasAC: true | false,
 *   hasHeating: true | false,
 *   hasRooftop: true | false,
 *   hasEnsuite: true | false,
 *   hasRestaurant: true | false,
 *   hasBar: true | false,
 *   hasGym: true | false,
 *   hasElevator: true | false,
 *   hasLaundryService: true | false,
 *   hasRoomService: true | false,
 *   petFriendly: true | false,
 *   isWheelchairAccessible: true | false,
 *   taxesIncluded: true | false,
 *   freeCancellation: true | false,
 *   kidsStayFree: true | false,
 *
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearMosque: true | false,
 *   safetyLevel: 1 | 2 | 3 | 4 | 5,
 *
 *   // ═══════════════════════════════════════════════════
 *   // TRUST SCORES
 *   // ═══════════════════════════════════════════════════
 *
 *   trustScores: {
 *     cleanliness: [1-10],
 *     safety: [1-10],
 *     staff: [1-10],
 *     value: [1-10],
 *     comfort: [1-10],
 *     location: [1-10]
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   amenities: ['wifi', 'pool', 'ac', 'breakfast', 'spa', 'restaurant', 'gym', 'kitchenette', 'parking', 'bar', 'laundry', 'elevator', 'room-service'],
 *   tip: '[Short insider tip]',
 *   vibeTags: ['Authentic', 'Quiet', 'Modern'],
 *   locationSummary: 'Beachfront | City Center | Medina | Airport Area | Residential | Tourist Zone',
 *   availabilityText: 'Available tonight | Only 2 rooms left | Available on selected dates',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   address: '[Full street address, City, Postal Code, Morocco]',
 *
 *   paymentMethods: ['card', 'cash'],
 *   languagesSpoken: ['Arabic', 'French', 'English', 'Spanish', 'German'],
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   customStory: 'Brief history, owner background, or architecture notes...',
 *   neighborhoodOverview: 'Description of the local atmosphere, safety, and vibe...',
 *   hiddenFeesNotice: 'City tax of XX MAD per person/night not included...',
 *   pros: ['Pro 1', 'Pro 2'],
 *   cons: ['Con 1'],
 *
 *   // ═══════════════════════════════════════════════════
 *   // LOGISTICS
 *   // ═══════════════════════════════════════════════════
 *
 *   logistics: {
 *     checkIn: '14:00 - 22:00',
 *     checkOut: 'Before 11:00',
 *     luggageStorage: 'Free | Paid | None',
 *     parking: 'Free on-site | Nearby public | Valet',
 *     contact: '+212 XXXXXXXXX'
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *   // ROOM FEATURES & TYPES
 *   // ═══════════════════════════════════════════════════
 *
 *   roomFeatures: ['soundproof', 'workspace', 'private-balcony', 'ac', 'heating', 'balcony', 'shower-ensuite', 'sea-view', 'garden-view', 'pool-view'],
 *   roomTypes: [
 *     {
 *       name: 'Double Room',
 *       price: 500,
 *       beds: '1 Queen',
 *       size: '20m2',
 *     }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *   // NEIGHBORHOOD DISTANCES
 *   // ═══════════════════════════════════════════════════
 *
 *   neighborhoodDistances: [
 *     { label: 'Beach', distance: '500m', time: '5 min walk', icon: 'beach' }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   cancellationPolicy: 'Free cancellation up to 24h before check-in | Flexible | Non-refundable',
 *   childPolicy: 'Children welcome | Free under 6 | Extra bed 200 MAD',
 *   officialWebsite: 'https://...',
 *   instagramHandle: '@...',
 *
 *   // googlePlaceId: "PLACE_ID_HERE",
 *
 *   // ═══════════════════════════════════════════════════
 *   // REVIEW HIGHLIGHTS
 *   // ═══════════════════════════════════════════════════
 *
 *   reviewHighlights: {
 *     solo: 'Great insight for solo...',
 *     couples: 'Great for couples...',
 *     families: 'Kid-friendly details...',
 *     business: 'Wi-Fi test details...',
 *     nomad: 'Remote work specific insight...'
 *   }
 * }
 */

export const ifrane_azrouSleep: SleepListing[] = [
  {
    id: "ia-sleep-1",
    city: "ifrane_azrou",
    name: "Michlifen Resort & Golf",
    type: "hotel",
    neighborhood: "Ifrane Center",
    description: "An ultra-luxurious alpine-style resort set amidst the cedar forests of the Middle Atlas. It blends the warmth of a Savoyard chalet with Moroccan palace design, offering heated indoor pools and a Jack Nicklaus golf course.",
    pricePerNight: 450,
    lifestyle: "premium",
    amenities: ["Indoor & Outdoor Pools", "Luxury Spa", "Jack Nicklaus Golf Course", "Bowling Alley", "Kids Club", "Wifi", "AC"],
    googleRating: 4.9,
    googleReviewCount: 2000,
    tripadvisorRating: 5.0,
    tripadvisorReviewCount: 800,
    bookingRating: 4.8,
    bookingReviewCount: 1200,
    hotelguruRating: 4.9,
    hotelguruReviewCount: 300,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "countryside",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["couple", "family", "seniors", "solo", "business-friendly"],
    tip: "The indoor pool is one of the most beautiful in Africa; visit in winter to watch snow fall through the glass while swimming in heated water.",
    vibeTags: ["Alpine-Chic", "Palatial", "Cozy", "Elite"],
    locationSummary: "Middle Atlas Cedar Forest & Hills",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Michlifen+Resort+Golf+Ifrane",
    address: "Avenue Hassan II, Ifrane 53000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Created to be a royal-standard mountain retreat, Michlifen is the symbol of Ifrane’s unique identity as a world-class winter destination.",
    neighborhoodOverview: "Ifrane is Morocco’s alpine-style mountain town, known for clean streets, red-roofed villas, cedar air, winter snow, Al Akhawayn University, and easy access to Middle Atlas forests.",
    hiddenFeesNotice: "City tax of 39.60 MAD per person/night not included.",
    pros: ["Stunning Alpine architecture", "World-class indoor pool and spa", "Access to the best golf in the Atlas"],
    cons: ["Very high price point", "Can be crowded during snow season"],
    trustScores: {
      cleanliness: 9.9,
      safety: 9.9,
      staff: 9.7,
      value: 8.1,
      comfort: 9.9,
      location: 9.8,
    },
    logistics: {
      checkIn: "15:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free valet",
      contact: "+212 535 864 000",
    },
    roomFeatures: ["noble-wood-interiors", "fireplace-available", "mountain-view", "ac", "heating", "soundproof"],
    roomTypes: [
      {
              name: "Deluxe Room",
              price: 450,
              beds: "1 King",
              size: "45m²",
            },
      {
              name: "Royal Suite",
              price: 1500,
              beds: "1 King",
              size: "120m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Lion of Ifrane",
              distance: "1km",
              time: "15 min walk",
              icon: "monument",
            },
      {
              label: "Azrou Cedar Forest",
              distance: "18km",
              time: "20 min drive",
              icon: "nature",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - kids club available",
    officialWebsite: "https://www.michlifen.com",
    instagramHandle: "@michlifenresort",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and incredibly cozy mountain escape.",
      couples: "The ultimate romantic winter retreat in Morocco.",
      families: "The kids club and bowling alley are fantastic.",
      business: "Prestigious venue for top-tier corporate retreats.",
      nomad: "Great WiFi and many cozy corners to work by the fire.",
    },
    coordinates: {
      lat: 33.411416,
      lng: -5.078405
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "ia-sleep-2",
    city: "ifrane_azrou",
    name: "Le Palais des Cerisiers",
    type: "hotel",
    neighborhood: "near the Cedar Forest",
    description: "A warm and peaceful four-star hotel nestled in the Middle Atlas near Azrou, with alpine-inspired architecture and sweeping views of cedar forest and peaks.",
    pricePerNight: 120,
    lifestyle: "balanced",
    amenities: ["Panoramic Forest Views", "Heated Outdoor Pool", "On-site Wellness Spa", "Traditional Moroccan Restaurant"],
    googleRating: 4.4,
    googleReviewCount: 550,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 200,
    bookingRating: 4.3,
    bookingReviewCount: 150,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 40,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "countryside",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["couple", "family", "seniors", "solo"],
    tip: "The hotel sits right by the entrance to the cedar forest; take an early morning walk to spot Barbary macaques when active.",
    vibeTags: ["Forest-View", "Alpine", "Peaceful", "Wellness"],
    locationSummary: "Middle Atlas Cedar Forest & Hills",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Le+Palais+des+Cerisiers+Azrou",
    address: "Route d’Ifrane, Azrou 53100, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Le Palais des Cerisiers was designed as a mountain retreat where Azrou’s cedar landscape meets comfortable resort-style hospitality.",
    neighborhoodOverview: "The cedar-forest belt between Ifrane and Azrou is quiet, car-oriented, and nature-focused, with hiking, macaque encounters, cool weather, and limited public transport.",
    hiddenFeesNotice: "City tax of 17.60 MAD per person/night not included.",
    pros: ["Close to cedar forest", "Heated pool and spa", "Peaceful mountain setting"],
    cons: ["Requires car or taxi for town access", "No elevator"],
    trustScores: {
      cleanliness: 8.9,
      safety: 9.5,
      staff: 9.0,
      value: 9.0,
      comfort: 8.8,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 535 000 001",
    },
    roomFeatures: ["forest-view", "mountain-view", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Forest View Room",
              price: 120,
              beds: "1 Queen",
              size: "28m²",
            },
      {
              name: "Family Suite",
              price: 170,
              beds: "1 Queen + 2 Twin",
              size: "45m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Cedar Forest",
              distance: "500m",
              time: "6 min walk",
              icon: "nature",
            },
      {
              label: "Azrou Center",
              distance: "5km",
              time: "8 min drive",
              icon: "city",
            },
    ],
    cancellationPolicy: "Free cancellation up to 48h before check-in",
    childPolicy: "Children welcome",
    officialWebsite: "https://palaisdescerisiers.com",
    instagramHandle: "@palaisdescerisiers",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A peaceful and safe forest-side base for solo travelers.",
      couples: "Cozy and romantic for couples who want mountain quiet.",
      families: "Good for families thanks to pool and easy forest walks.",
      business: "Quiet enough for focused work between hikes.",
      nomad: "A balanced remote-work base if you have a car.",
    },
    coordinates: {
      lat: 33.443967,
      lng: -5.180024
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "ia-sleep-3",
    city: "ifrane_azrou",
    name: "Maurice Bonjean",
    type: "guesthouse",
    neighborhood: "near the Cedar Forest",
    description: "A charming eco-friendly stone guesthouse offering a cozy and private mountain retreat with rustic wooden interiors and a warm fireplace.",
    pricePerNight: 85,
    lifestyle: "balanced",
    amenities: ["Seasonal Outdoor Pool", "Cozy Stone Fireplace", "Organic Homemade Meals", "Mountain View Garden"],
    googleRating: 4.7,
    googleReviewCount: 350,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 100,
    bookingRating: 4.8,
    bookingReviewCount: 120,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 30,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["couple", "solo", "family", "friends"],
    tip: "Speak with the manager, Ismail, for the best local hiking path recommendations directly behind the property.",
    vibeTags: ["Rustic", "Eco-Friendly", "Cozy", "Private"],
    locationSummary: "Ifrane Alpine Town Center",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Maurice+Bonjean+Azrou",
    address: "Cedar Forest Road, Azrou 53100, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Maurice Bonjean channels classic mountain-lodge hospitality, with stone, wood, fireplaces, and a focus on slow countryside living.",
    neighborhoodOverview: "The cedar-forest belt between Ifrane and Azrou is quiet, car-oriented, and nature-focused, with hiking, macaque encounters, cool weather, and limited public transport.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Cozy fireplace atmosphere", "Helpful local hiking advice", "Great value for a private retreat"],
    cons: ["Limited hotel-style services", "Best reached by car"],
    trustScores: {
      cleanliness: 9.5,
      safety: 9.5,
      staff: 9.7,
      value: 9.1,
      comfort: 9.4,
      location: 9.2,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 535 000 002",
    },
    roomFeatures: ["stone-walls", "wooden-interiors", "fireplace", "garden-view", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Stone Double Room",
              price: 85,
              beds: "1 Queen",
              size: "24m²",
            },
      {
              name: "Family Room",
              price: 120,
              beds: "1 Queen + 1 Single",
              size: "32m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Cedar Forest Trails",
              distance: "200m",
              time: "3 min walk",
              icon: "nature",
            },
      {
              label: "Azrou Center",
              distance: "6km",
              time: "10 min drive",
              icon: "city",
            },
    ],
    cancellationPolicy: "Free cancellation up to 48h before check-in",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://mauricebonjean.com",
    instagramHandle: "@mauricebonjean",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Safe, warm, and ideal for a solo hiking retreat.",
      couples: "A cozy fireplace makes it romantic in winter.",
      families: "Family rooms and garden space work well for children.",
      business: "Quiet enough for creative work, but remote.",
      nomad: "Good for nomads wanting nature, silence, and simple comfort.",
    },
    tags: ["family-favorite"]
  },
  {
    id: "ia-sleep-4",
    city: "ifrane_azrou",
    name: "Le Gîte du Barrage",
    type: "guesthouse",
    neighborhood: "near the Cedar Forest",
    description: "A tranquil mountain guesthouse steps from the Ben Smim source and pine valleys, with hearty Atlas dinners and genuine Berber family hospitality.",
    pricePerNight: 65,
    lifestyle: "lean",
    amenities: ["Ben Smim Forest Access", "Outdoor Children's Pool", "Cozy Fireplace Lounge", "Terrace with Mountain Views"],
    googleRating: 4.6,
    googleReviewCount: 410,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 150,
    bookingRating: 4.5,
    bookingReviewCount: 100,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 40,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "countryside",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Don’t miss their slow-cooked beef tagine with local plums, cooked on hot coals in the fireplace.",
    vibeTags: ["Berber", "Mountain", "Fireplace", "Value"],
    locationSummary: "Middle Atlas Cedar Forest & Hills",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Le+Gite+du+Barrage+Ben+Smim",
    address: "Ben Smim, Azrou 53100, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Le Gîte du Barrage grew from family hospitality around the Ben Smim springs, focusing on simple mountain food and warm local hosting.",
    neighborhoodOverview: "The cedar-forest belt between Ifrane and Azrou is quiet, car-oriented, and nature-focused, with hiking, macaque encounters, cool weather, and limited public transport.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Great traditional dinners", "Peaceful forest access", "Strong value for families"],
    cons: ["Basic rooms", "Needs car or taxi for sightseeing"],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.5,
      staff: 9.4,
      value: 9.4,
      comfort: 9.2,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 535 000 003",
    },
    roomFeatures: ["mountain-view", "fireplace-lounge", "terrace", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 65,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Family Room",
              price: 90,
              beds: "1 Queen + 2 Twin",
              size: "34m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ben Smim Source",
              distance: "500m",
              time: "6 min walk",
              icon: "nature",
            },
      {
              label: "Ifrane Center",
              distance: "12km",
              time: "15 min drive",
              icon: "city",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://gitedubarrage.com",
    instagramHandle: "@gitedubarrage",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and simple mountain base for solo hikers.",
      couples: "Cozy dinners by the fire feel very romantic.",
      families: "A good family-value option with space and nature nearby.",
      business: "Basic but quiet for light work.",
      nomad: "Best for offline-focused nomads who want mountain calm.",
    },
    coordinates: {
      lat: 33.4747,
      lng: -5.247636
    },
    tags: ["family-favorite"]
  },
  {
    id: "ia-sleep-5",
    city: "ifrane_azrou",
    name: "Ferme D'hôte La Vallée",
    type: "guesthouse",
    neighborhood: "Azrou Center",
    description: "A delightful family-run farm stay in a picturesque mountain valley near Azrou, with fireplaces, a small river nearby, animals, and Atlas views.",
    pricePerNight: 55,
    lifestyle: "lean",
    amenities: ["Rustic Farmhouse Decor", "Eco-friendly Valley Trails", "Homemade Berber Breakfast", "Animal Farm Interaction"],
    googleRating: 4.6,
    googleReviewCount: 420,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 120,
    bookingRating: 4.7,
    bookingReviewCount: 150,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 40,
    hasPool: true,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Stroll along the small river to spot freshwater turtles basking in the midday sun.",
    vibeTags: ["Farmstay", "Rustic", "Family", "Nature"],
    locationSummary: "Azrou Valley Farmstay",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Ferme+d%27hote+La+Vallee+Azrou",
    address: "Azrou Valley, Azrou 53100, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "La Vallée was created as a family farm stay, offering travelers a softer Berber countryside experience with animals, gardens, and homemade meals.",
    neighborhoodOverview: "Azrou is a practical Berber market town at the edge of the cedar forests, with local craft shops, rug cooperatives, mountain taxis, and quick access to macaque-viewing areas.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Excellent for children and animal lovers", "Homemade breakfast", "Peaceful valley setting"],
    cons: ["Rustic comfort level", "Requires transport for forest sights"],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.5,
      staff: 9.4,
      value: 9.4,
      comfort: 9.2,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public or on-site parking",
      contact: "+212 535 000 004",
    },
    roomFeatures: ["farm-view", "fireplace", "river-nearby", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Farm Double Room",
              price: 55,
              beds: "1 Queen",
              size: "18m²",
            },
      {
              name: "Family Farm Room",
              price: 80,
              beds: "1 Queen + 2 Twin",
              size: "32m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Azrou Center",
              distance: "3km",
              time: "6 min drive",
              icon: "city",
            },
      {
              label: "Cedar Forest",
              distance: "8km",
              time: "12 min drive",
              icon: "nature",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://fermelavalleeazrou.com",
    instagramHandle: "@fermelavallee",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A welcoming and peaceful farm stay for solo travelers.",
      couples: "Rustic and romantic if you love countryside stays.",
      families: "Great for families with animals and outdoor space.",
      business: "Not a business hotel, but calm for writing or planning.",
      nomad: "A budget nature base for nomads who can work with simple facilities.",
    },
    coordinates: {
      lat: 33.450729,
      lng: -5.229569
    },
    tags: ["family-favorite"]
  },
  {
    id: "ia-sleep-6",
    city: "ifrane_azrou",
    name: "ZEPHYR Ifrane",
    type: "hotel",
    neighborhood: "Ifrane Center",
    description: "A modern four-star hotel over six hectares of gardens, with clean alpine-style architecture and chalet apartments with private mountain-facing terraces.",
    pricePerNight: 95,
    lifestyle: "balanced",
    amenities: ["Two Outdoor Pools", "Stunning Mountain Gardens", "Chalet Apartments", "Modern Fitness Center"],
    googleRating: 4.3,
    googleReviewCount: 450,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 150,
    bookingRating: 4.4,
    bookingReviewCount: 200,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 50,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["couple", "family", "friends", "business-friendly"],
    tip: "The property has vast manicured flower gardens; grab tea and enjoy a peaceful stroll at sunset.",
    vibeTags: ["Modern", "Garden", "Alpine", "Family-Friendly"],
    locationSummary: "Ifrane Alpine Town Center",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=ZEPHYR+Ifrane",
    address: "Avenue Mohammed VI, Ifrane 53000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "ZEPHYR Ifrane was built as a modern mountain hotel-apartment complex for families and longer stays in Morocco’s alpine town.",
    neighborhoodOverview: "Ifrane is Morocco’s alpine-style mountain town, known for clean streets, red-roofed villas, cedar air, winter snow, Al Akhawayn University, and easy access to Middle Atlas forests.",
    hiddenFeesNotice: "City tax of 17.60 MAD per person/night not included.",
    pros: ["Large garden grounds", "Apartment-style room options", "Good family facilities"],
    cons: ["Less intimate than guesthouses", "Can be busy during school holidays"],
    trustScores: {
      cleanliness: 8.7,
      safety: 9.5,
      staff: 8.8,
      value: 9.0,
      comfort: 8.6,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 535 000 005",
    },
    roomFeatures: ["private-terrace", "garden-view", "mountain-view", "ac", "heating", "workspace"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 95,
              beds: "1 Queen",
              size: "25m²",
            },
      {
              name: "Chalet Apartment",
              price: 150,
              beds: "1 Queen + Sofa",
              size: "55m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ifrane Center",
              distance: "1km",
              time: "12 min walk",
              icon: "city",
            },
      {
              label: "Lion of Ifrane",
              distance: "1.5km",
              time: "5 min drive",
              icon: "monument",
            },
    ],
    cancellationPolicy: "Free cancellation up to 48h before check-in",
    childPolicy: "Children welcome",
    officialWebsite: "https://zephyr-hotels.com/ifrane",
    instagramHandle: "@zephyrifrane",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Safe and practical for solo travelers wanting modern comfort.",
      couples: "Good for couples who prefer gardens and quiet.",
      families: "Strong family option thanks to space and pools.",
      business: "Useful for business stays with parking and modern rooms.",
      nomad: "Good for nomads who want apartment-style comfort and garden breaks.",
    },
    coordinates: {
      lat: 33.50583,
      lng: -5.154719
    },
    tags: ["family-favorite"]
  },
  {
    id: "ia-sleep-7",
    city: "ifrane_azrou",
    name: "Le Chêne d'Azrou",
    type: "guesthouse",
    neighborhood: "near the Cedar Forest",
    description: "A high-altitude mountain lodge offering traditional Moroccan hospitality in a peaceful garden surrounded by oak and cedar trees.",
    pricePerNight: 80,
    lifestyle: "balanced",
    amenities: ["Forest Trail Access", "Mountain View Garden", "Traditional Berber Dining", "Cozy Lounge Fireplace"],
    googleRating: 4.9,
    googleReviewCount: 94,
    tripadvisorRating: 5.0,
    tripadvisorReviewCount: 40,
    bookingRating: 4.8,
    bookingReviewCount: 30,
    hotelguruRating: 4.9,
    hotelguruReviewCount: 10,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "seniors"],
    tip: "This guesthouse sits near scenic trailheads; ask hosts to arrange horseback riding lessons through ancient oak forests.",
    vibeTags: ["Forest", "Warm", "Traditional", "Scenic"],
    locationSummary: "Oak and Cedar Forest Edge",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Le+Chene+d%27Azrou",
    address: "Cedar Forest Road, Azrou 53100, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Le Chêne d’Azrou is built around classic mountain hospitality, connecting guests to oak forests, Berber meals, and slow evenings by the fireplace.",
    neighborhoodOverview: "The cedar-forest belt between Ifrane and Azrou is quiet, car-oriented, and nature-focused, with hiking, macaque encounters, cool weather, and limited public transport.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Outstanding hospitality", "Excellent trail access", "Peaceful garden atmosphere"],
    cons: ["No pool", "Remote without a car"],
    trustScores: {
      cleanliness: 9.9,
      safety: 9.7,
      staff: 9.9,
      value: 9.2,
      comfort: 9.7,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 535 000 006",
    },
    roomFeatures: ["forest-view", "garden-view", "fireplace-lounge", "heating", "shower-ensuite", "rooftop-access"],
    roomTypes: [
      {
              name: "Forest Double Room",
              price: 80,
              beds: "1 Queen",
              size: "22m²",
            },
      {
              name: "Family Room",
              price: 110,
              beds: "1 Queen + 1 Single",
              size: "30m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Cedar Forest Trails",
              distance: "100m",
              time: "2 min walk",
              icon: "nature",
            },
      {
              label: "Azrou Center",
              distance: "6km",
              time: "10 min drive",
              icon: "city",
            },
    ],
    cancellationPolicy: "Free cancellation up to 48h before check-in",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://lecheneazrou.com",
    instagramHandle: "@lecheneazrou",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and peaceful base for solo nature travelers.",
      couples: "A warm fireplace and forest setting make it romantic.",
      families: "Good for families who enjoy hikes and quiet gardens.",
      business: "Quiet enough for focused reading or work.",
      nomad: "Ideal for nature-first nomads with a car.",
    },
    coordinates: {
      lat: 33.440752,
      lng: -5.225613
    },
    tags: ["family-favorite"]
  },
  {
    id: "ia-sleep-8",
    city: "ifrane_azrou",
    name: "Le Gîte Dayet Aoua",
    type: "guesthouse",
    neighborhood: "near Dayet Aoua",
    description: "An authentic mountain escape near peaceful Dayet Aoua lake, surrounded by pine woods with peacocks, farm animals, and cozy mountain views.",
    pricePerNight: 75,
    lifestyle: "lean",
    amenities: ["Lakeside Access", "Seasonal Swimming Pool", "Farm Animal Garden", "Cozy Berber Breakfast"],
    googleRating: 4.7,
    googleReviewCount: 63,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 20,
    bookingRating: 4.6,
    bookingReviewCount: 25,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 5,
    hasPool: true,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Rent a local bicycle and complete the 8-kilometer loop around Dayet Aoua lake and surrounding forest.",
    vibeTags: ["Lakeside", "Rustic", "Farm", "Peaceful"],
    locationSummary: "Ifrane Alpine Town Center",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Le+Gite+Dayet+Aoua",
    address: "Dayet Aoua, Ifrane 53000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Le Gîte Dayet Aoua is a rustic farm-lodge experience built around lake air, animals, and quiet rural hospitality.",
    neighborhoodOverview: "Dayet Aoua is a peaceful lake-and-forest area outside Ifrane, best reached by car and ideal for birdwatching, cycling, picnics, and quiet rural stays.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Close to Dayet Aoua lake", "Great for families and animal lovers", "Peaceful rural setting"],
    cons: ["Rustic rooms", "Car needed for Ifrane or Azrou"],
    trustScores: {
      cleanliness: 9.5,
      safety: 9.5,
      staff: 9.6,
      value: 9.4,
      comfort: 9.4,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 535 000 007",
    },
    roomFeatures: ["lake-nearby", "farm-garden", "heating", "shower-ensuite", "mountain-view"],
    roomTypes: [
      {
              name: "Lake Area Double",
              price: 75,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Family Room",
              price: 105,
              beds: "1 Queen + 2 Twin",
              size: "34m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dayet Aoua Lake",
              distance: "800m",
              time: "10 min walk",
              icon: "lake",
            },
      {
              label: "Ifrane Center",
              distance: "17km",
              time: "20 min drive",
              icon: "city",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://gitedayetaoua.com",
    instagramHandle: "@gitedayetaoua",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A peaceful and safe rural base for solo travelers.",
      couples: "Quiet and charming for couples who like simple nature stays.",
      families: "Farm animals and open space make it great for children.",
      business: "Not suited to formal business, but calm for planning.",
      nomad: "Best for nomads seeking lake walks and simple offline time.",
    },
    coordinates: {
      lat: 33.653362,
      lng: -5.011236
    },
    tags: ["family-favorite"]
  },
  {
    id: "ia-sleep-9",
    city: "ifrane_azrou",
    name: "Riad Azrou",
    type: "riad",
    neighborhood: "Azrou Center",
    description: "A traditionally decorated riad near the heart of Azrou’s local markets, with cozy rooms and a rooftop terrace overlooking town and green hills.",
    pricePerNight: 45,
    lifestyle: "lean",
    amenities: ["Rooftop Panoramic Terrace", "Authentic Zellij Decor", "Local Marketplace Proximity", "Traditional Moroccan Breakfast"],
    googleRating: 4.2,
    googleReviewCount: 376,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 150,
    bookingRating: 4.3,
    bookingReviewCount: 120,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 40,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "countryside",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Excellent for exploring town on foot; walk to see Ennour Mosque and local Berber rug weavers.",
    vibeTags: ["Traditional", "Budget", "Town-Center", "Rooftop"],
    locationSummary: "Middle Atlas Cedar Forest & Hills",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Azrou",
    address: "Azrou Center, Azrou 53100, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad Azrou gives budget travelers a traditional townhouse stay close to markets, crafts, and onward transport into the Middle Atlas.",
    neighborhoodOverview: "Azrou is a practical Berber market town at the edge of the cedar forests, with local craft shops, rug cooperatives, mountain taxis, and quick access to macaque-viewing areas.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Excellent value", "Walkable to Azrou markets", "Good rooftop views"],
    cons: ["No pool", "More town-based than forest retreat"],
    trustScores: {
      cleanliness: 8.5,
      safety: 8.8,
      staff: 8.6,
      value: 9.4,
      comfort: 8.4,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public or on-site parking",
      contact: "+212 535 000 008",
    },
    roomFeatures: ["zellij-decor", "rooftop-access", "town-view", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 45,
              beds: "1 Queen",
              size: "18m²",
            },
      {
              name: "Triple Room",
              price: 65,
              beds: "1 Queen + 1 Single",
              size: "24m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Azrou Market",
              distance: "300m",
              time: "4 min walk",
              icon: "market",
            },
      {
              label: "Cedar Forest",
              distance: "7km",
              time: "12 min drive",
              icon: "nature",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riadazrou.com",
    instagramHandle: "@riadazrou",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and affordable base for solo travelers in Azrou.",
      couples: "Simple and authentic for couples on a budget.",
      families: "Good for families needing a central low-cost base.",
      business: "Basic but workable for short laptop sessions.",
      nomad: "A budget town base for nomads arranging forest day trips.",
    },
    coordinates: {
      lat: 33.434868,
      lng: -5.220344
    },
    tags: ["family-favorite"]
  },
  {
    id: "ia-sleep-10",
    city: "ifrane_azrou",
    name: "Auberge Jomana Park",
    type: "guesthouse",
    neighborhood: "near the Cedar Forest",
    description: "A charming mountain lodge combining alpine chalet features with peaceful nature surroundings, clean wood-paneled rooms, and direct paths into cedar forest.",
    pricePerNight: 50,
    lifestyle: "lean",
    amenities: ["Seasonal Outdoor Pool", "Cedar Forest Trails", "Cozy Alpine Lounge", "Moroccan Restaurant"],
    googleRating: 4.5,
    googleReviewCount: 158,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 50,
    bookingRating: 4.4,
    bookingReviewCount: 60,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 15,
    hasPool: true,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ["solo", "friends", "couple", "family"],
    tip: "A great budget base for mountain bikers looking to tackle the rugged Middle Atlas forest trails.",
    vibeTags: ["Budget", "Alpine", "Forest", "Adventure"],
    locationSummary: "Ifrane Alpine Town Center",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Auberge+Jomana+Park+Azrou",
    address: "Cedar Forest Road, Azrou 53100, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Auberge Jomana Park caters to hikers and bikers looking for a straightforward forest lodge with chalet touches and Moroccan meals.",
    neighborhoodOverview: "The cedar-forest belt between Ifrane and Azrou is quiet, car-oriented, and nature-focused, with hiking, macaque encounters, cool weather, and limited public transport.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Affordable forest access", "Good for mountain bikers", "Cozy wood-paneled rooms"],
    cons: ["Simple facilities", "Seasonal pool only"],
    trustScores: {
      cleanliness: 9.1,
      safety: 8.8,
      staff: 9.2,
      value: 9.4,
      comfort: 9.0,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 535 000 009",
    },
    roomFeatures: ["wood-paneling", "forest-view", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Chalet Double",
              price: 50,
              beds: "1 Double",
              size: "18m²",
            },
      {
              name: "Family Chalet",
              price: 80,
              beds: "1 Double + 2 Twin",
              size: "30m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Cedar Forest Trails",
              distance: "Direct",
              time: "1 min walk",
              icon: "nature",
            },
      {
              label: "Azrou Center",
              distance: "8km",
              time: "12 min drive",
              icon: "city",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://aubergejomanapark.com",
    instagramHandle: "@jomanapark",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A practical and safe base for solo bikers or hikers.",
      couples: "Simple but cozy for active couples.",
      families: "Good value for families who spend days outdoors.",
      business: "Not ideal for business, but quiet for basic work.",
      nomad: "A budget-friendly forest base for outdoorsy nomads.",
    },
    tags: ["family-favorite"]
  },
  {
    id: "ia-sleep-11",
    city: "ifrane_azrou",
    name: "Riad Gold",
    type: "riad",
    neighborhood: "Azrou Center",
    description: "A tranquil modern riad in central Azrou with an elegant courtyard, cozy wood-burning fireplaces, pool, and mountain views.",
    pricePerNight: 95,
    lifestyle: "balanced",
    amenities: ["Outdoor Swimming Pool", "Warm Central Courtyard", "Cozy Fireplace", "Mountain View Rooms"],
    googleRating: 4.1,
    googleReviewCount: 135,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 40,
    bookingRating: 4.2,
    bookingReviewCount: 50,
    hotelguruRating: 4.1,
    hotelguruReviewCount: 10,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Great for pet lovers; this riad is pet-friendly, so you can travel with dogs into the surrounding woods.",
    vibeTags: ["Modern-Riad", "Pet-Friendly", "Pool", "Mountain-View"],
    locationSummary: "Ifrane Alpine Town Center",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Gold+Azrou",
    address: "Azrou Center, Azrou 53100, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad Gold combines modern riad comfort with Azrou’s mountain-town rhythm, giving guests a warm base before forest excursions.",
    neighborhoodOverview: "Azrou is a practical Berber market town at the edge of the cedar forests, with local craft shops, rug cooperatives, mountain taxis, and quick access to macaque-viewing areas.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Pet-friendly policy", "Pool and fireplace atmosphere", "Quiet central location"],
    cons: ["Service can be simple", "Not deep in the forest"],
    trustScores: {
      cleanliness: 8.3,
      safety: 9.5,
      staff: 8.4,
      value: 9.0,
      comfort: 8.2,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public or on-site parking",
      contact: "+212 535 000 010",
    },
    roomFeatures: ["mountain-view", "fireplace", "courtyard-view", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Gold Room",
              price: 95,
              beds: "1 Queen",
              size: "24m²",
            },
      {
              name: "Family Suite",
              price: 135,
              beds: "1 Queen + 2 Twin",
              size: "38m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Azrou Center",
              distance: "500m",
              time: "6 min walk",
              icon: "city",
            },
      {
              label: "Cedar Forest",
              distance: "7km",
              time: "12 min drive",
              icon: "nature",
            },
    ],
    cancellationPolicy: "Free cancellation up to 48h before check-in",
    childPolicy: "Children welcome",
    officialWebsite: "https://riadgoldazrou.com",
    instagramHandle: "@riadgoldazrou",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A calm and safe base for solo travelers in Azrou.",
      couples: "Cozy fireplaces and mountain views are romantic.",
      families: "Good for families who want town access and a pool.",
      business: "Quiet enough for light work and planning.",
      nomad: "A balanced town base for nomads traveling with pets.",
    },
    coordinates: {
      lat: 33.434868,
      lng: -5.220344
    },
    tags: ["family-favorite"]
  },
  {
    id: "ia-sleep-12",
    city: "ifrane_azrou",
    name: "Rise In Valley",
    type: "guesthouse",
    neighborhood: "near the Cedar Forest",
    description: "A modern mountain lodge with brick-and-wood alpine aesthetics in a serene valley, offering cozy family suites and hiking trails.",
    pricePerNight: 60,
    lifestyle: "lean",
    amenities: ["Seasonal Outdoor Pool", "Cozy Wood Stoves", "Lush Valley Garden", "Daily Berber Breakfast"],
    googleRating: 4.2,
    googleReviewCount: 337,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 100,
    bookingRating: 4.3,
    bookingReviewCount: 150,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 30,
    hasPool: true,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Ask the staff to help book a local quad-biking tour across the rocky Atlas plateaus.",
    vibeTags: ["Valley", "Adventure", "Family", "Rustic-Modern"],
    locationSummary: "Ifrane Alpine Town Center",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Rise+In+Valley+Azrou",
    address: "Middle Atlas Valley, Azrou 53100, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Rise In Valley was built for active mountain travelers who want valley scenery, simple comfort, and access to local adventure activities.",
    neighborhoodOverview: "The cedar-forest belt between Ifrane and Azrou is quiet, car-oriented, and nature-focused, with hiking, macaque encounters, cool weather, and limited public transport.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Good value for families", "Adventure tours nearby", "Peaceful valley garden"],
    cons: ["Simple comfort level", "Requires car or taxi"],
    trustScores: {
      cleanliness: 8.5,
      safety: 9.5,
      staff: 8.6,
      value: 9.4,
      comfort: 8.4,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 535 000 011",
    },
    roomFeatures: ["wood-stove", "valley-view", "garden-view", "heating", "shower-ensuite", "rooftop-access"],
    roomTypes: [
      {
              name: "Valley Double",
              price: 60,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Family Suite",
              price: 95,
              beds: "1 Queen + 2 Twin",
              size: "36m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Cedar Forest",
              distance: "4km",
              time: "8 min drive",
              icon: "nature",
            },
      {
              label: "Azrou Center",
              distance: "7km",
              time: "12 min drive",
              icon: "city",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riseinvalley.com",
    instagramHandle: "@riseinvalley",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe simple base for solo adventure travelers.",
      couples: "A quiet valley stay for couples who like rustic comfort.",
      families: "Family suites and outdoor space make it practical for kids.",
      business: "Not business-focused, but calm for light remote tasks.",
      nomad: "A good base for nomads who mix work with hiking or quad rides.",
    },
    tags: ["family-favorite"]
  },
  {
    id: "ia-sleep-13",
    city: "ifrane_azrou",
    name: "Hotel Tamanoucht",
    type: "hotel",
    neighborhood: "near the Cedar Forest",
    description: "A serene traditional mountain inn surrounded by green pine valleys, with classic stone design and tranquil mountain settings for a refreshing escape.",
    pricePerNight: 55,
    lifestyle: "lean",
    amenities: ["Mountain Panoramic Terrace", "Spacious Family Suites", "Atlas Hiking Guide Access", "Traditional Berber Breakfast"],
    googleRating: 4.4,
    googleReviewCount: 100,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 30,
    bookingRating: 4.3,
    bookingReviewCount: 40,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 10,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "seniors"],
    tip: "Perfect for quiet recovery; take a relaxing dawn walk along the nearby pine trails.",
    vibeTags: ["Stone-Inn", "Quiet", "Mountain", "Restorative"],
    locationSummary: "Ifrane Alpine Town Center",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Hotel+Tamanoucht+Azrou",
    address: "Pine Valley Road, Azrou 53100, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Hotel Tamanoucht reflects the old mountain-inn tradition of the Middle Atlas, offering simple hospitality and quiet air near pine trails.",
    neighborhoodOverview: "The cedar-forest belt between Ifrane and Azrou is quiet, car-oriented, and nature-focused, with hiking, macaque encounters, cool weather, and limited public transport.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Very peaceful setting", "Spacious family suites", "Good access to hiking guides"],
    cons: ["No pool", "Traditional and simple facilities"],
    trustScores: {
      cleanliness: 8.9,
      safety: 8.8,
      staff: 9.0,
      value: 9.4,
      comfort: 8.8,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 535 000 012",
    },
    roomFeatures: ["stone-design", "mountain-view", "family-suite", "heating", "shower-ensuite", "rooftop-access"],
    roomTypes: [
      {
              name: "Mountain Room",
              price: 55,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Family Suite",
              price: 85,
              beds: "1 Queen + 2 Twin",
              size: "35m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Pine Trails",
              distance: "200m",
              time: "3 min walk",
              icon: "nature",
            },
      {
              label: "Azrou Center",
              distance: "8km",
              time: "12 min drive",
              icon: "city",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://hoteltamanoucht.com",
    instagramHandle: "@hoteltamanoucht",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A quiet and safe mountain rest stop for solo travelers.",
      couples: "Peaceful and restorative for couples.",
      families: "Good for families needing simple spacious rooms.",
      business: "Not business-oriented, but calm for writing or reading.",
      nomad: "Best for nomads seeking quiet recovery and nature walks.",
    },
    coordinates: {
      lat: 33.433476,
      lng: -5.2262
    },
    tags: ["family-favorite"]
  },
  {
    id: "ia-sleep-14",
    city: "ifrane_azrou",
    name: "L'empreinte D'ifrane",
    type: "hotel",
    neighborhood: "Ifrane Center",
    description: "A stylish three-star hotel decorated in classic alpine chalet style with wood paneling, warm lights, and a cozy central location in Ifrane.",
    pricePerNight: 90,
    lifestyle: "balanced",
    amenities: ["Chalet-Style Boiseries", "Panoramic Rooftop Terrace", "Gourmet Moroccan Restaurant", "City Center Proximity"],
    googleRating: 4.3,
    googleReviewCount: 680,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 200,
    bookingRating: 4.4,
    bookingReviewCount: 300,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 80,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "business-friendly"],
    tip: "Their restaurant serves wood-fired pizzas and local trout; book a terrace table for evening views.",
    vibeTags: ["Chalet", "Central", "Cozy", "Restaurant"],
    locationSummary: "Ifrane Center",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=L%27empreinte+D%27ifrane",
    address: "Ifrane Center, Ifrane 53000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "L’empreinte D’Ifrane celebrates the town’s alpine identity through warm wood interiors, chalet design, and a central restaurant-focused stay.",
    neighborhoodOverview: "Ifrane is Morocco’s alpine-style mountain town, known for clean streets, red-roofed villas, cedar air, winter snow, Al Akhawayn University, and easy access to Middle Atlas forests.",
    hiddenFeesNotice: "City tax of 17.60 MAD per person/night not included.",
    pros: ["Cozy chalet design", "Central Ifrane location", "Good restaurant and terrace"],
    cons: ["No pool", "Can be busy in peak winter weekends"],
    trustScores: {
      cleanliness: 8.7,
      safety: 9.5,
      staff: 8.8,
      value: 9.0,
      comfort: 8.6,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 535 000 013",
    },
    roomFeatures: ["wood-paneling", "city-view", "rooftop-access", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 90,
              beds: "1 Queen",
              size: "22m²",
            },
      {
              name: "Superior Room",
              price: 120,
              beds: "1 King",
              size: "28m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ifrane Center",
              distance: "200m",
              time: "3 min walk",
              icon: "city",
            },
      {
              label: "Lion of Ifrane",
              distance: "700m",
              time: "9 min walk",
              icon: "monument",
            },
    ],
    cancellationPolicy: "Free cancellation up to 48h before check-in",
    childPolicy: "Children welcome",
    officialWebsite: "https://lempreinteifrane.com",
    instagramHandle: "@lempreinteifrane",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and central base for solo travelers.",
      couples: "Cozy chalet rooms suit couples on a mountain weekend.",
      families: "Good for families who want a walkable Ifrane base.",
      business: "Central and practical for meetings or university visits.",
      nomad: "A comfortable town base with decent work corners.",
    },
    coordinates: {
      lat: 33.529342,
      lng: -5.107502
    },
    tags: ["family-favorite"]
  },
  {
    id: "ia-sleep-15",
    city: "ifrane_azrou",
    name: "Hôtel Relais Ras El Maa",
    type: "hotel",
    neighborhood: "Ifrane Center",
    description: "A charming three-star hotel near Ifrane center and Vittel Spring water park, with pine surroundings, gardens, bicycle rental, and a peaceful natural feel.",
    pricePerNight: 70,
    lifestyle: "lean",
    amenities: ["Vittel Spring Proximity", "Bicycle Rental Services", "Lush Pine Garden", "On-site Meeting Space"],
    googleRating: 4.2,
    googleReviewCount: 320,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 100,
    bookingRating: 4.1,
    bookingReviewCount: 150,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 30,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "business-friendly"],
    tip: "Rent one of their bicycles to explore the pristine forest roads leading toward Ras El Maa waterfalls.",
    vibeTags: ["Pine-Garden", "Cycling", "Quiet", "Value"],
    locationSummary: "Ifrane Alpine Town Center",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Hotel+Relais+Ras+El+Maa+Ifrane",
    address: "Route de Ras El Maa, Ifrane 53000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Relais Ras El Maa is a classic Ifrane nature hotel, connecting guests to pine gardens, cycling roads, and the town’s spring-water landscapes.",
    neighborhoodOverview: "Ifrane is Morocco’s alpine-style mountain town, known for clean streets, red-roofed villas, cedar air, winter snow, Al Akhawayn University, and easy access to Middle Atlas forests.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Close to Vittel Spring", "Bicycle rentals", "Peaceful pine garden"],
    cons: ["No pool", "Simple rooms"],
    trustScores: {
      cleanliness: 8.5,
      safety: 9.5,
      staff: 8.6,
      value: 9.4,
      comfort: 8.4,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 535 000 014",
    },
    roomFeatures: ["pine-garden-view", "bicycle-access", "heating", "shower-ensuite", "rooftop-access"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 70,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Family Room",
              price: 95,
              beds: "1 Queen + 1 Single",
              size: "28m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Vittel Spring",
              distance: "1km",
              time: "15 min walk",
              icon: "nature",
            },
      {
              label: "Ifrane Center",
              distance: "2km",
              time: "5 min drive",
              icon: "city",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://relaisraselmaa.com",
    instagramHandle: "@relaisraselmaa",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and quiet value base for solo nature walks.",
      couples: "Good for couples who prefer gardens over busy streets.",
      families: "Practical for families who want bikes and outdoor time.",
      business: "Meeting space makes it useful for small work trips.",
      nomad: "A simple, calm base for nomads who enjoy cycling breaks.",
    },
    coordinates: {
      lat: 33.464258,
      lng: -5.148528
    },
    tags: ["family-favorite"]
  },
  {
    id: "ia-sleep-16",
    city: "ifrane_azrou",
    name: "Hotel Perce Neige",
    type: "hotel",
    neighborhood: "Ifrane Center",
    description: "A cozy centrally located three-star hotel with alpine aesthetics, clean heated rooms, warm boiseries, and a traditional restaurant.",
    pricePerNight: 65,
    lifestyle: "lean",
    amenities: ["Central Location", "Traditional Restaurant", "Heated Cozy Rooms", "Warm Lounge Fireplace"],
    googleRating: 4.1,
    googleReviewCount: 337,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 100,
    bookingRating: 4.0,
    bookingReviewCount: 150,
    hotelguruRating: 4.1,
    hotelguruReviewCount: 30,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "business-friendly"],
    tip: "Walk to nearby Al Akhawayn University to admire its pristine European-style architecture.",
    vibeTags: ["Central", "Alpine", "Cozy", "Value"],
    locationSummary: "Ifrane Alpine Town Center",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Hotel+Perce+Neige+Ifrane",
    address: "Ifrane Center, Ifrane 53000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Hotel Perce Neige is a classic central Ifrane stay, offering the town’s alpine mood at a practical price point.",
    neighborhoodOverview: "Ifrane is Morocco’s alpine-style mountain town, known for clean streets, red-roofed villas, cedar air, winter snow, Al Akhawayn University, and easy access to Middle Atlas forests.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Walkable central location", "Warm heated rooms", "Good value in Ifrane"],
    cons: ["Basic three-star comfort", "Can be busy in snow season"],
    trustScores: {
      cleanliness: 8.3,
      safety: 9.5,
      staff: 8.4,
      value: 9.4,
      comfort: 8.2,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 535 000 015",
    },
    roomFeatures: ["wood-paneling", "heated-room", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 65,
              beds: "1 Double",
              size: "18m²",
            },
      {
              name: "Triple Room",
              price: 85,
              beds: "1 Double + 1 Single",
              size: "24m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Al Akhawayn University",
              distance: "800m",
              time: "10 min walk",
              icon: "university",
            },
      {
              label: "Lion of Ifrane",
              distance: "600m",
              time: "8 min walk",
              icon: "monument",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://hotelperceneige.com",
    instagramHandle: "@hotelperceneige",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Safe and practical for solo travelers in the center.",
      couples: "Simple and cozy for a budget couple stay.",
      families: "Good for families needing central heated rooms.",
      business: "Convenient for university or town meetings.",
      nomad: "A practical budget town base for light remote work.",
    },
    coordinates: {
      lat: 33.518382,
      lng: -5.133075
    },
    tags: ["family-favorite"]
  },
  {
    id: "ia-sleep-17",
    city: "ifrane_azrou",
    name: "Le Chamonix",
    type: "hotel",
    neighborhood: "Ifrane Center",
    description: "An alpine-themed classic hotel in central Ifrane, with brick facade, stone fireplaces, wooden paneling, and the nostalgic feel of a French ski resort.",
    pricePerNight: 60,
    lifestyle: "lean",
    amenities: ["Cozy Stone Fireplace", "Central Location", "Moroccan & French Dining", "Mountain View Balconies"],
    googleRating: 3.8,
    googleReviewCount: 363,
    tripadvisorRating: 3.5,
    tripadvisorReviewCount: 150,
    bookingRating: 3.7,
    bookingReviewCount: 120,
    hotelguruRating: 3.8,
    hotelguruReviewCount: 40,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Request a room overlooking Parc la Prairie for sunrise views of pine trees.",
    vibeTags: ["Classic", "Alpine", "Central", "Budget"],
    locationSummary: "Ifrane Alpine Town Center",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Le+Chamonix+Ifrane",
    address: "Ifrane Center, Ifrane 53000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Le Chamonix preserves an older ski-resort feel in the heart of Ifrane, with fireplaces, balconies, and a nostalgic mountain-town atmosphere.",
    neighborhoodOverview: "Ifrane is Morocco’s alpine-style mountain town, known for clean streets, red-roofed villas, cedar air, winter snow, Al Akhawayn University, and easy access to Middle Atlas forests.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Central location", "Cozy fireplace atmosphere", "Good for budget snow-season stays"],
    cons: ["Older property", "Lower ratings than newer hotels"],
    trustScores: {
      cleanliness: 7.7,
      safety: 9.5,
      staff: 8.0,
      value: 9.4,
      comfort: 7.6,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 535 000 016",
    },
    roomFeatures: ["mountain-view-balcony", "stone-fireplace", "wood-paneling", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 60,
              beds: "1 Double",
              size: "18m²",
            },
      {
              name: "Balcony Room",
              price: 75,
              beds: "1 Queen",
              size: "22m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Parc la Prairie",
              distance: "100m",
              time: "2 min walk",
              icon: "park",
            },
      {
              label: "Lion of Ifrane",
              distance: "500m",
              time: "6 min walk",
              icon: "monument",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://lechamonixifrane.com",
    instagramHandle: "@lechamonixifrane",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A central and safe budget base for solo travelers.",
      couples: "A nostalgic alpine-style option for couples.",
      families: "Works for families who need simple central rooms.",
      business: "Basic but central for quick work or meetings.",
      nomad: "A budget Ifrane base for nomads who value location over polish.",
    },
    coordinates: {
      lat: 33.528516,
      lng: -5.106531
    },
    tags: ["family-favorite"]
  },
  {
    id: "ia-sleep-18",
    city: "ifrane_azrou",
    name: "Maison Duffal",
    type: "guesthouse",
    neighborhood: "Azrou Center",
    description: "A tranquil family guesthouse on a peaceful hillside overlooking Azrou and the surrounding hills, known for cleanliness and warm host touches.",
    pricePerNight: 45,
    lifestyle: "lean",
    amenities: ["Hillside Town Views", "Quiet Mountain Garden", "Homemade Moroccan Breakfast", "BBQ Facilities"],
    googleRating: 4.0,
    googleReviewCount: 112,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 40,
    bookingRating: 4.1,
    bookingReviewCount: 50,
    hotelguruRating: 4.0,
    hotelguruReviewCount: 10,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Walk up the hill behind the guesthouse in late afternoon for a peaceful sunset over the valley of Azrou.",
    vibeTags: ["Hillside", "Homey", "Budget", "Quiet"],
    locationSummary: "Ifrane Alpine Town Center",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Maison+Duffal+Azrou",
    address: "Azrou Hillside, Azrou 53100, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Maison Duffal is a family-run hillside guesthouse, focused on cleanliness, views, and a quiet home-like atmosphere.",
    neighborhoodOverview: "Azrou is a practical Berber market town at the edge of the cedar forests, with local craft shops, rug cooperatives, mountain taxis, and quick access to macaque-viewing areas.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Very affordable", "Peaceful hillside views", "Warm family hospitality"],
    cons: ["No restaurant beyond breakfast", "Requires uphill walking or taxi"],
    trustScores: {
      cleanliness: 8.1,
      safety: 8.8,
      staff: 8.2,
      value: 9.4,
      comfort: 8.0,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public or on-site parking",
      contact: "+212 535 000 017",
    },
    roomFeatures: ["hillside-view", "garden-view", "bbq-access", "heating", "shower-ensuite", "rooftop-access"],
    roomTypes: [
      {
              name: "Double Room",
              price: 45,
              beds: "1 Queen",
              size: "18m²",
            },
      {
              name: "Family Room",
              price: 65,
              beds: "1 Queen + 1 Single",
              size: "24m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Azrou Center",
              distance: "1km",
              time: "12 min walk",
              icon: "city",
            },
      {
              label: "Cedar Forest",
              distance: "8km",
              time: "12 min drive",
              icon: "nature",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://maisonduffal.com",
    instagramHandle: "@maisonduffal",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A quiet and safe guesthouse for solo travelers on a budget.",
      couples: "Simple and peaceful for couples.",
      families: "Good for families who like guesthouse stays.",
      business: "A calm place for light work with views.",
      nomad: "A low-cost nomad base if you do not mind being outside the center.",
    },
    coordinates: {
      lat: 33.43652,
      lng: -5.214161
    },
    tags: ["family-favorite"]
  },
  {
    id: "ia-sleep-19",
    city: "ifrane_azrou",
    name: "Hotel School Ersat Azrou",
    type: "hotel",
    neighborhood: "Azrou Center",
    description: "A unique hospitality-school hotel offering clean spacious accommodation, enthusiastic student service, and outstanding breakfasts.",
    pricePerNight: 30,
    lifestyle: "lean",
    amenities: ["Enthusiastic Student Service", "Clean Modern Bedrooms", "Outstanding Moroccan Breakfast", "Bicycle Rentals Available"],
    googleRating: 4.2,
    googleReviewCount: 245,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 80,
    bookingRating: 4.3,
    bookingReviewCount: 100,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 20,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "countryside",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "business-friendly"],
    tip: "The training restaurant is highly recommended; order a fresh Moroccan tagine prepared by culinary students.",
    vibeTags: ["Student-Run", "Budget", "Clean", "Educational"],
    locationSummary: "Middle Atlas Cedar Forest & Hills",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Hotel+School+Ersat+Azrou",
    address: "Azrou Center, Azrou 53100, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Hotel School Ersat Azrou gives hospitality students practical experience while offering travelers a surprisingly clean and caring budget stay.",
    neighborhoodOverview: "Azrou is a practical Berber market town at the edge of the cedar forests, with local craft shops, rug cooperatives, mountain taxis, and quick access to macaque-viewing areas.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Excellent value", "Very caring student service", "Great breakfast"],
    cons: ["School-hotel service can vary", "Limited luxury amenities"],
    trustScores: {
      cleanliness: 8.5,
      safety: 8.8,
      staff: 8.6,
      value: 9.4,
      comfort: 8.4,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 535 000 018",
    },
    roomFeatures: ["modern-room", "student-service", "workspace", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Student Hotel Room",
              price: 30,
              beds: "1 Double",
              size: "18m²",
            },
      {
              name: "Twin Room",
              price: 40,
              beds: "2 Twin",
              size: "20m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Azrou Center",
              distance: "800m",
              time: "10 min walk",
              icon: "city",
            },
      {
              label: "Cedar Forest",
              distance: "8km",
              time: "12 min drive",
              icon: "nature",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://hotelschoolersatazrou.com",
    instagramHandle: "@ersatazrou",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and interesting budget stay for solo travelers.",
      couples: "Simple and clean for couples on a tight budget.",
      families: "Good for families who value cleanliness over luxury.",
      business: "Surprisingly practical for budget work trips.",
      nomad: "A very affordable base for nomads who need clean basics.",
    },
    coordinates: {
      lat: 33.438661,
      lng: -5.231223
    },
    tags: ["family-favorite"]
  },
  {
    id: "ia-sleep-20",
    city: "ifrane_azrou",
    name: "Farah Inn Ifrane",
    type: "hotel",
    neighborhood: "Ifrane Center",
    description: "A large vacation complex with chalets and equipped apartments on a pine-covered hillside, offering pools, tennis courts, and an alpine village feel.",
    pricePerNight: 45,
    lifestyle: "lean",
    amenities: ["Three Swimming Pools", "Chalet Kitchenettes", "Sports Courts Access", "Pine Forest Surroundings"],
    googleRating: 3.4,
    googleReviewCount: 1800,
    tripadvisorRating: 3.0,
    tripadvisorReviewCount: 500,
    bookingRating: 3.5,
    bookingReviewCount: 1000,
    hotelguruRating: 3.4,
    hotelguruReviewCount: 200,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["family", "friends", "couple", "large-groups"],
    tip: "A great budget choice for large families; book a detached stone chalet for a private garden entrance.",
    vibeTags: ["Budget", "Chalet-Complex", "Family", "Pine-Forest"],
    locationSummary: "Ifrane Alpine Town Center",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Farah+Inn+Ifrane",
    address: "Station Biladi, Ifrane 53000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Farah Inn Ifrane was designed as an affordable alpine holiday village with chalets, apartments, pools, and sports courts for families.",
    neighborhoodOverview: "Ifrane is Morocco’s alpine-style mountain town, known for clean streets, red-roofed villas, cedar air, winter snow, Al Akhawayn University, and easy access to Middle Atlas forests.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Excellent for large families", "Kitchenettes in chalets", "Pools and sports courts"],
    cons: ["Mixed reviews and older facilities", "Large complex can feel impersonal"],
    trustScores: {
      cleanliness: 7.4,
      safety: 9.2,
      staff: 8.0,
      value: 8.8,
      comfort: 7.2,
      location: 8.5,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site",
      contact: "+212 535 000 019",
    },
    roomFeatures: ["kitchenette", "pine-view", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Studio Apartment",
              price: 45,
              beds: "1 Double",
              size: "28m²",
            },
      {
              name: "Family Chalet",
              price: 90,
              beds: "1 Double + 2 Twin",
              size: "60m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ifrane Center",
              distance: "3km",
              time: "6 min drive",
              icon: "city",
            },
      {
              label: "Al Akhawayn University",
              distance: "2km",
              time: "5 min drive",
              icon: "university",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://farahinnifrane.com",
    instagramHandle: "@farahinnifrane",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe low-cost base if you prefer resort-style space.",
      couples: "Good for couples who need a cheap self-catering chalet.",
      families: "Best for large families and groups on a budget.",
      business: "Not ideal for business except longer practical stays.",
      nomad: "Useful for budget nomads who want kitchenette space and do not need polish.",
    },
    coordinates: {
      lat: 33.518382,
      lng: -5.133075
    },
    tags: ["family-favorite"]
  }
]
