import type { SleepListing } from '../types'

/**
 * SLEEP LISTING DATA TEMPLATE (Copy this for your search agent)
 * -------------------------------------------------------------
 * {
 *   "id": "city-sleep-XX",
 *   "name": "",
 *   "type": "riad | hotel | villa | hostel | apartment | guesthouse",
 *   "neighborhood": "",
 *   "city": "[city]",
 *   "description": "",
 *   "pricePerNight": 0,
 *   "lifestyle": "lean | balanced | premium",
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2', 'url3']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source (replaces single rating/reviewCount)
 *   // ═══════════════════════════════════════════════════
 *   // Search for real ratings from Google, TripAdvisor, Booking.com, and HotelGuru.
 *   // If you cannot find a rating for a specific source, set it to the same value as
 *   // the closest available one so average calculations don't break.
 *
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *   bookingRating: [4.x],
 *   bookingReviewCount: [number],
 *   hotelguruRating: [4.x],
 *   hotelguruReviewCount: [number],
 *
 *   // ═══════════════════════════════════════════════════
 *   // BOOLEAN AMENITIES
 *   // ═══════════════════════════════════════════════════
 *
 *   hasPool: true | false,
 *   hasBreakfast: true | false,
 *   hasAC: true | false,
 *   hasHeating: true | false,
 *   hasRooftop: true | false,
 *   hasEnsuite: true | false,
 *   hasRestaurant: true | false,
 *   hasBar: true | false,
 *   hasGym: true | false,
 *   hasElevator: true | false,
 *   hasLaundryService: true | false,
 *   hasRoomService: true | false,
 *   petFriendly: true | false,
 *   isWheelchairAccessible: true | false,
 *   taxesIncluded: true | false,
 *   freeCancellation: true | false,
 *   kidsStayFree: true | false,
 *
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearMosque: true | false,
 *   safetyLevel: 1 | 2 | 3 | 4 | 5,
 *
 *   // ═══════════════════════════════════════════════════
 *   // TRUST SCORES
 *   // ═══════════════════════════════════════════════════
 *
 *   trustScores: {
 *     cleanliness: [1-10],
 *     safety: [1-10],
 *     staff: [1-10],
 *     value: [1-10],
 *     comfort: [1-10],
 *     location: [1-10]
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   amenities: ['wifi', 'pool', 'ac', 'breakfast', 'spa', 'restaurant', 'gym', 'kitchenette', 'parking', 'bar', 'laundry', 'elevator', 'room-service'],
 *   tip: '[Short insider tip]',
 *   vibeTags: ['Authentic', 'Quiet', 'Modern'],
 *   locationSummary: 'Beachfront | City Center | Medina | Airport Area | Residential | Tourist Zone',
 *   availabilityText: 'Available tonight | Only 2 rooms left | Available on selected dates',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   address: '[Full street address, City, Postal Code, Morocco]',
 *
 *   paymentMethods: ['card', 'cash'],
 *   languagesSpoken: ['Arabic', 'French', 'English', 'Spanish', 'German'],
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   customStory: 'Brief history, owner background, or architecture notes...',
 *   neighborhoodOverview: 'Description of the local atmosphere, safety, and vibe...',
 *   hiddenFeesNotice: 'City tax of XX MAD per person/night not included...',
 *   pros: ['Pro 1', 'Pro 2'],
 *   cons: ['Con 1'],
 *
 *   // ═══════════════════════════════════════════════════
 *   // LOGISTICS
 *   // ═══════════════════════════════════════════════════
 *
 *   logistics: {
 *     checkIn: '14:00 - 22:00',
 *     checkOut: 'Before 11:00',
 *     luggageStorage: 'Free | Paid | None',
 *     parking: 'Free on-site | Nearby public | Valet',
 *     contact: '+212 XXXXXXXXX'
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *   // ROOM FEATURES & TYPES
 *   // ═══════════════════════════════════════════════════
 *
 *   roomFeatures: ['soundproof', 'workspace', 'private-balcony', 'ac', 'heating', 'balcony', 'shower-ensuite', 'sea-view', 'garden-view', 'pool-view'],
 *   roomTypes: [
 *     {
 *       name: 'Double Room',
 *       price: 500,
 *       beds: '1 Queen',
 *       size: '20m2',
 *     }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *   // NEIGHBORHOOD DISTANCES
 *   // ═══════════════════════════════════════════════════
 *
 *   neighborhoodDistances: [
 *     { label: 'Beach', distance: '500m', time: '5 min walk', icon: 'beach' }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   cancellationPolicy: 'Free cancellation up to 24h before check-in | Flexible | Non-refundable',
 *   childPolicy: 'Children welcome | Free under 6 | Extra bed 200 MAD',
 *   officialWebsite: 'https://...',
 *   instagramHandle: '@...',
 *
 *   // googlePlaceId: "PLACE_ID_HERE",
 *
 *   // ═══════════════════════════════════════════════════
 *   // REVIEW HIGHLIGHTS
 *   // ═══════════════════════════════════════════════════
 *
 *   reviewHighlights: {
 *     solo: 'Great insight for solo...',
 *     couples: 'Great for couples...',
 *     families: 'Kid-friendly details...',
 *     business: 'Wi-Fi test details...',
 *     nomad: 'Remote work specific insight...'
 *   }
 * }
 */

export const meknesSleep: SleepListing[] = [
  {
    id: "mk-sleep-1",
    city: "meknes",
    name: "Riad Dar Meknes Tresor",
    type: "riad",
    neighborhood: "Medina",
    description: "An exceptionally cozy, family-run guesthouse beautifully restored to showcase its traditional masonry and woodwork. Large, spacious rooms are furnished with very comfortable beds and colorful Moroccan accents.",
    pricePerNight: 95,
    lifestyle: "balanced",
    amenities: ["Panoramic Rooftop Terrace", "Traditional Home-Cooked Meals", "Hammam Services", "Library", "Wifi", "AC"],
    googleRating: 4.8,
    googleReviewCount: 450,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 120,
    bookingRating: 4.7,
    bookingReviewCount: 200,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 40,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family"],
    tip: "Ask the hosts for a rooftop orientation; they can point out the historic gates and minarets of the imperial city.",
    vibeTags: ["Authentic", "Family-Run", "Historic", "Panoramic"],
    locationSummary: "Historic Medina & Place El-Hedim",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Dar+Meknes+Tresor",
    address: "Riad Dar Meknes Tresor, Meknes Medina, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "This riad was a family home for generations before opening to guests with the goal of sharing authentic imperial Meknes hospitality.",
    neighborhoodOverview: "Meknes Medina is calmer and less touristy than Fes or Marrakech, with historic gates, traditional markets, relaxed lanes, and easy walks to Bab Mansour, Lahdim Square, and imperial monuments.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Incredible rooftop views", "Genuine local hospitality", "Peaceful atmosphere"],
    cons: ["Difficult to find without guidance first time", "No on-site pool"],
    trustScores: {
      cleanliness: 9.7,
      safety: 9.8,
      staff: 9.9,
      value: 9.5,
      comfort: 9.4,
      location: 9.6,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Nearby public (Bab Mansour)",
      contact: "+212 535 531 354",
    },
    roomFeatures: ["traditional-decor", "high-ceilings", "ensuite-bathroom", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Standard Double",
              price: 95,
              beds: "1 Queen",
              size: "22m²",
            },
      {
              name: "Family Suite",
              price: 150,
              beds: "1 King + 2 Single",
              size: "45m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Bab Mansour",
              distance: "400m",
              time: "5 min walk",
              icon: "gate",
            },
      {
              label: "Bou Inania Madrasa",
              distance: "300m",
              time: "4 min walk",
              icon: "mosque",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://www.darmeknestresor.com",
    instagramHandle: "@riaddarmeknestresor",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Extremely welcoming and safe for solo travelers.",
      couples: "A quiet, authentic retreat in the heart of the city.",
      families: "The family suite is spacious and very comfortable.",
      business: "Good WiFi in the courtyard and rooftop.",
      nomad: "A peaceful spot to work with a view of the city.",
    },
    coordinates: {
      lat: 33.89523,
      lng: -5.566176
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "mk-sleep-2",
    city: "meknes",
    name: "Riad Yamcha",
    type: "riad",
    neighborhood: "Medina",
    description: "A charming and highly curated medina house showcasing soothing grey-and-white tones with oversized rooms. It blends antique Moroccan artifacts with modern minimalist architecture.",
    pricePerNight: 110,
    lifestyle: "balanced",
    amenities: ["Designer Courtyard", "Rooftop Sun Terrace", "Gourmet Breakfast", "Art Gallery Vibe", "Wifi", "AC"],
    googleRating: 4.8,
    googleReviewCount: 320,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 100,
    bookingRating: 4.7,
    bookingReviewCount: 150,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 30,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "friends"],
    tip: "The breakfast is considered one of the best in Meknes, with homemade jams and local pastries.",
    vibeTags: ["Chic", "Artistic", "Modern-Moroccan", "Intimate"],
    locationSummary: "Historic Medina & Place El-Hedim",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Yamcha+Meknes",
    address: "Riad Yamcha, Meknes Medina, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Italian"],
    customStory: "Created by an Italian-Moroccan couple, Yamcha was designed as a bridge between traditional heritage and modern artistic expression.",
    neighborhoodOverview: "Meknes Medina is calmer and less touristy than Fes or Marrakech, with historic gates, traditional markets, relaxed lanes, and easy walks to Bab Mansour, Lahdim Square, and imperial monuments.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Stylish clean design", "Excellent food quality", "Friendly artistic hosts"],
    cons: ["No pool for summer days", "Can be hard to find"],
    trustScores: {
      cleanliness: 9.8,
      safety: 9.6,
      staff: 9.8,
      value: 9.2,
      comfort: 9.5,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public (Lahdim)",
      contact: "+212 535 555 400",
    },
    roomFeatures: ["modern-minimalist", "designer-lighting", "premium-linens", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Double Room",
              price: 85,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Superior Double",
              price: 110,
              beds: "1 Queen",
              size: "26m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dar Jamai Museum",
              distance: "200m",
              time: "3 min walk",
              icon: "museum",
            },
      {
              label: "Bab Mansour",
              distance: "600m",
              time: "8 min walk",
              icon: "gate",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome, but best suited for adults and older children",
    officialWebsite: "https://www.riadyamcha.com",
    instagramHandle: "@riadyamcha",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe, chic, and inspiring place for a solo stay.",
      couples: "Perfectly intimate and stylish for couples.",
      families: "Better suited for couples or friends.",
      business: "Fast WiFi and comfortable communal areas.",
      nomad: "A great aesthetic spot for digital work.",
    },
    coordinates: {
      lat: 33.895925,
      lng: -5.568195
    },
    tags: ["heritage"]
  },
  {
    id: "mk-sleep-3",
    city: "meknes",
    name: "Riad Yacout",
    type: "riad",
    neighborhood: "Medina",
    description: "Dating back to 1830, this restored riad features refined zellij, heavy velvet drapery, and a classic Andalusian courtyard with a central pond beside Bab Mansour.",
    pricePerNight: 270,
    lifestyle: "premium",
    amenities: ["Central Andalusian Courtyard", "Traditional Hammam Spa", "Rooftop Overlooking Golf Greens", "Gourmet Restaurant", "Wifi", "AC"],
    googleRating: 4.7,
    googleReviewCount: 1100,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 300,
    bookingRating: 4.6,
    bookingReviewCount: 500,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 100,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "seniors", "friends"],
    tip: "Book the Senior Suite for a private lounge in imperial style; the rooftop has rare views toward the royal golf course.",
    vibeTags: ["Imperial", "Historic", "Opulent", "Central"],
    locationSummary: "Historic Medina & Place El-Hedim",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Yacout+Meknes",
    address: "22 Place Lalla Aouda, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Built during the era of Sultan Moulay Ismail, this noble residence was restored into a boutique hotel preserving imperial grandeur.",
    neighborhoodOverview: "The Bab Mansour and Lahdim Square area is the sightseeing heart of Meknes, lively by day and evening, with easy access to museums, souks, taxis, and the imperial city walls.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Authentic imperial architecture", "Prime sightseeing location", "Excellent rooftop views"],
    cons: ["Parking can be difficult nearby", "Some rooms are smaller due to historic layout"],
    trustScores: {
      cleanliness: 9.4,
      safety: 9.3,
      staff: 9.5,
      value: 8.6,
      comfort: 9.2,
      location: 9.8,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Nearby public (Bab Mansour)",
      contact: "+212 535 550 400",
    },
    roomFeatures: ["imperial-decor", "high-ceilings", "traditional-rugs", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Patio Room",
              price: 270,
              beds: "1 Queen",
              size: "28m²",
            },
      {
              name: "Senior Suite",
              price: 450,
              beds: "1 King",
              size: "55m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Bab Mansour",
              distance: "100m",
              time: "2 min walk",
              icon: "gate",
            },
      {
              label: "Lahdim Square",
              distance: "150m",
              time: "2 min walk",
              icon: "city",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome",
    officialWebsite: "https://www.riad-yacout-meknes.com",
    instagramHandle: "@riadyacoutmeknes",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Extremely safe and regal base in the Medina.",
      couples: "The ultimate historic romantic escape in Meknes.",
      families: "Connecting rooms available for families.",
      business: "Quiet enough for meetings with reliable WiFi.",
      nomad: "Inspiring imperial atmosphere for focused work.",
    },
    coordinates: {
      lat: 33.893641,
      lng: -5.562787
    },
    tags: ["heritage"]
  },
  {
    id: "mk-sleep-4",
    city: "meknes",
    name: "Maison Olga",
    type: "guesthouse",
    neighborhood: "Medina",
    description: "A cozy welcoming bed and breakfast known for incredible hospitality and a personal vibe. Simple, clean rooms are decorated with rugs, embroidered fabrics, and local art.",
    pricePerNight: 45,
    lifestyle: "lean",
    amenities: ["Cozy shared Moroccan lounge", "Sun-soaked panoramic rooftop terrace", "Homemade traditional daily breakfast", "Personalized guided excursion planning"],
    googleRating: 4.7,
    googleReviewCount: 290,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 80,
    bookingRating: 4.6,
    bookingReviewCount: 100,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 20,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: false,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "friends"],
    tip: "The owner is a wonderful source of local history; chat over tea for hidden gems.",
    vibeTags: ["Cozy", "Personal", "Budget", "Local"],
    locationSummary: "Historic Medina & Place El-Hedim",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Maison+Olga+Meknes",
    address: "Maison Olga, Meknes Medina, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Maison Olga was shaped as a home-style guesthouse where personal hosting and local storytelling matter as much as the room itself.",
    neighborhoodOverview: "Meknes Medina is calmer and less touristy than Fes or Marrakech, with historic gates, traditional markets, relaxed lanes, and easy walks to Bab Mansour, Lahdim Square, and imperial monuments.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Warm personal hospitality", "Very good value", "Rooftop and local advice"],
    cons: ["Shared bathrooms in some rooms", "Simple facilities"],
    trustScores: {
      cleanliness: 9.5,
      safety: 8.9,
      staff: 9.6,
      value: 9.4,
      comfort: 9.3,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 535 000 004",
    },
    roomFeatures: ["traditional-fabrics", "shared-lounge", "rooftop-access", "heating", "shared-bathroom"],
    roomTypes: [
      {
              name: "Budget Double",
              price: 45,
              beds: "1 Double",
              size: "16m²",
            },
      {
              name: "Triple Room",
              price: 65,
              beds: "1 Double + 1 Single",
              size: "22m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Bab Mansour",
              distance: "700m",
              time: "9 min walk",
              icon: "gate",
            },
      {
              label: "Medina Souks",
              distance: "300m",
              time: "4 min walk",
              icon: "shopping",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://maisonolga.com",
    instagramHandle: "@maisonolgameknes",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and very welcoming budget choice for solo travelers.",
      couples: "Simple and cozy for couples who like guesthouses.",
      families: "Best for families comfortable with basic facilities.",
      business: "Good enough for emails and planning routes.",
      nomad: "A low-cost medina base for light remote work.",
    },
    coordinates: {
      lat: 33.89403,
      lng: -5.567542
    },
    tags: ["family-favorite"]
  },
  {
    id: "mk-sleep-5",
    city: "meknes",
    name: "Riad Zyna",
    type: "riad",
    neighborhood: "Medina",
    description: "A restored, sun-kissed riad steps from Bab Mansour. Its white courtyard is lit by a glass skyway and decorated with classic zellij floors.",
    pricePerNight: 120,
    lifestyle: "balanced",
    amenities: ["Central glass-ceiling atrium", "Refreshing courtyard plunge pool", "Furnished panoramic rooftop deck", "Authentic zellij tile flooring"],
    googleRating: 4.7,
    googleReviewCount: 250,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 60,
    bookingRating: 4.6,
    bookingReviewCount: 80,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 20,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Request an upper-level room to be closer to the peaceful rooftop breakfast area.",
    vibeTags: ["Bright", "Restored", "Zellij", "Central"],
    locationSummary: "Historic Medina & Place El-Hedim",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Zyna+Meknes",
    address: "Riad Zyna, Meknes Medina, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad Zyna was restored to emphasize light, white plaster, glass-roofed volume, and the classic geometry of Meknes zellij floors.",
    neighborhoodOverview: "The Bab Mansour and Lahdim Square area is the sightseeing heart of Meknes, lively by day and evening, with easy access to museums, souks, taxis, and the imperial city walls.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Bright atrium courtyard", "Small plunge pool", "Excellent central location"],
    cons: ["Limited room count", "Parking outside medina"],
    trustScores: {
      cleanliness: 9.5,
      safety: 8.9,
      staff: 9.6,
      value: 9.0,
      comfort: 9.3,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public (Bab Mansour)",
      contact: "+212 535 000 005",
    },
    roomFeatures: ["glass-ceiling-atrium", "zellij-flooring", "rooftop-access", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Upper Room",
              price: 120,
              beds: "1 Queen",
              size: "24m²",
            },
      {
              name: "Family Suite",
              price: 160,
              beds: "1 Queen + 2 Twin",
              size: "38m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Bab Mansour",
              distance: "200m",
              time: "3 min walk",
              icon: "gate",
            },
      {
              label: "Lahdim Square",
              distance: "250m",
              time: "3 min walk",
              icon: "city",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riadzyna.com",
    instagramHandle: "@riadzyna",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A bright and safe choice for solo medina stays.",
      couples: "Intimate and clean for couples.",
      families: "Good central family base with a plunge pool.",
      business: "Quiet rooftop is good for light laptop work.",
      nomad: "A balanced riad for nomads who want central access and calm mornings.",
    },
    coordinates: {
      lat: 33.888592,
      lng: -5.57312
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "mk-sleep-6",
    city: "meknes",
    name: "Château Roslane Boutique Hôtel & Spa",
    type: "hotel",
    neighborhood: "El Hajeb (Région de Meknès)",
    description: "A luxurious Relais & Châteaux boutique property set within a 39-hectare vineyard, surrounded by olive groves, gardens, and Middle Atlas views.",
    pricePerNight: 350,
    lifestyle: "premium",
    amenities: ["World-class wellness spa", "Outdoor infinity swimming pool", "Guided vineyard tour & tasting", "Fine dining restaurant L'Oliveraie"],
    googleRating: 4.7,
    googleReviewCount: 216,
    tripadvisorRating: 5.0,
    tripadvisorReviewCount: 50,
    bookingRating: 4.8,
    bookingReviewCount: 100,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 20,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["couple", "solo", "seniors", "business-friendly"],
    tip: "Take a guided tour of the historical wine cellars and enjoy a sunset tasting on the terrace.",
    vibeTags: ["Vineyard", "Relais-Châteaux", "Spa", "Countryside-Luxe"],
    locationSummary: "Hamria - Ville Nouvelle",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Chateau+Roslane+Boutique+Hotel+Spa+Meknes",
    address: "Domaine Roslane, El Hajeb Road, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Château Roslane is part of the celebrated Meknes wine region, turning a vineyard estate into a refined countryside hotel and spa.",
    neighborhoodOverview: "The El Hajeb and Meknes vineyard area is rural and car-oriented, known for vineyards, olive groves, Middle Atlas views, and quiet estate-style stays away from the city center.",
    hiddenFeesNotice: "City tax of 39.60 MAD per person/night not included; tastings and spa treatments may be extra.",
    pros: ["Unique vineyard setting", "Excellent spa and pool", "Fine dining and wine experiences"],
    cons: ["Requires car or transfer", "Away from medina sightseeing"],
    trustScores: {
      cleanliness: 9.7,
      safety: 9.8,
      staff: 9.6,
      value: 8.4,
      comfort: 9.6,
      location: 8.8,
    },
    logistics: {
      checkIn: "15:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free secure on-site parking",
      contact: "+212 535 000 006",
    },
    roomFeatures: ["vineyard-view", "private-terrace", "spa-products", "ac", "heating", "soundproof"],
    roomTypes: [
      {
              name: "Vineyard Room",
              price: 350,
              beds: "1 King",
              size: "35m²",
            },
      {
              name: "Estate Suite",
              price: 520,
              beds: "1 King",
              size: "60m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Meknes Medina",
              distance: "18km",
              time: "25 min drive",
              icon: "city",
            },
      {
              label: "Volubilis",
              distance: "45km",
              time: "50 min drive",
              icon: "history",
            },
    ],
    cancellationPolicy: "Moderate 7-day",
    childPolicy: "Children welcome, though best suited for adults",
    officialWebsite: "https://chateaurislane.com",
    instagramHandle: "@chateauroslane",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and luxurious solo countryside escape.",
      couples: "Very romantic for wine, spa, and sunset lovers.",
      families: "Better for adults than young children.",
      business: "Excellent for executive retreats and quiet meetings.",
      nomad: "A serene workation base if you want countryside calm.",
    },
    coordinates: {
      lat: 33.758701,
      lng: -5.438871
    },
    tags: []
  },
  {
    id: "mk-sleep-7",
    city: "meknes",
    name: "Riad d'Or Meknès",
    type: "riad",
    neighborhood: "Medina",
    description: "An authentic palace built in 1791 with towering archways, stucco carvings, open-sky courtyard, brass lamps, cedar furnishings, and colorful zellij.",
    pricePerNight: 255,
    lifestyle: "premium",
    amenities: ["Expansive courtyard swimming pool", "Panoramic rooftop sunset terrace", "Traditional on-site clay hammam", "Artisanal Moroccan dining options"],
    googleRating: 4.6,
    googleReviewCount: 850,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 200,
    bookingRating: 4.7,
    bookingReviewCount: 300,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 100,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["couple", "family", "friends", "seniors"],
    tip: "Unwind by the rooftop plunge pool during the afternoon when the medina sun is at its peak.",
    vibeTags: ["Palace", "Historic", "Pool", "Zellij"],
    locationSummary: "Medina - Historic Palace Riad",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+d%27Or+Meknes",
    address: "17 Derb Zemouri, Meknes Medina, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Built as an 18th-century palace residence, Riad d’Or preserves high arches, zellij mosaics, and the scale of an imperial Meknes home.",
    neighborhoodOverview: "Meknes Medina is calmer and less touristy than Fes or Marrakech, with historic gates, traditional markets, relaxed lanes, and easy walks to Bab Mansour, Lahdim Square, and imperial monuments.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Historic palace atmosphere", "Pool and rooftop terrace", "Good traditional dining"],
    cons: ["Can feel busy in peak periods", "Some rooms vary due to historic layout"],
    trustScores: {
      cleanliness: 9.3,
      safety: 8.9,
      staff: 9.4,
      value: 8.4,
      comfort: 9.1,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 535 000 007",
    },
    roomFeatures: ["cedar-furnishings", "zellij-mosaics", "rooftop-access", "ac", "heating", "courtyard-view"],
    roomTypes: [
      {
              name: "Double Room",
              price: 255,
              beds: "1 Queen",
              size: "28m²",
            },
      {
              name: "Palace Suite",
              price: 380,
              beds: "1 King",
              size: "50m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Bab Mansour",
              distance: "500m",
              time: "7 min walk",
              icon: "gate",
            },
      {
              label: "Lahdim Square",
              distance: "550m",
              time: "8 min walk",
              icon: "city",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome",
    officialWebsite: "https://riaddormeknes.com",
    instagramHandle: "@riaddormeknes",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and atmospheric palace-style solo base.",
      couples: "Historic courtyards make it romantic for couples.",
      families: "Good for families wanting a pool and large rooms.",
      business: "Reliable WiFi and quiet corners for work.",
      nomad: "A scenic riad base for focused work and rooftop breaks.",
    },
    coordinates: {
      lat: 33.852355,
      lng: -5.57884
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "mk-sleep-8",
    city: "meknes",
    name: "Riad Bab Berdaine",
    type: "riad",
    neighborhood: "Medina",
    description: "A highly rated budget riad near Bab Berdaine, with a bright central patio lined with traditional tiles and lush hanging plants.",
    pricePerNight: 52,
    lifestyle: "lean",
    amenities: ["Lush interior courtyard gardens", "Panoramic high-altitude rooftop view", "Airport transfer shuttle services", "Authentic zellij-covered walls"],
    googleRating: 4.6,
    googleReviewCount: 680,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 150,
    bookingRating: 4.4,
    bookingReviewCount: 200,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 50,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Enjoy morning mint tea on the rooftop to watch the neighborhood come to life.",
    vibeTags: ["Budget", "Courtyard", "Rooftop", "Local"],
    locationSummary: "Historic Medina & Place El-Hedim",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Bab+Berdaine+Meknes",
    address: "7 Derb Moussa, Bab Berdaine, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad Bab Berdaine offers classic medina hospitality at a friendly price, with a plant-filled patio and broad rooftop views.",
    neighborhoodOverview: "Meknes Medina is calmer and less touristy than Fes or Marrakech, with historic gates, traditional markets, relaxed lanes, and easy walks to Bab Mansour, Lahdim Square, and imperial monuments.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Excellent value", "Friendly rooftop views", "Authentic zellij patio"],
    cons: ["No pool", "A little away from Bab Mansour"],
    trustScores: {
      cleanliness: 9.3,
      safety: 8.9,
      staff: 9.4,
      value: 9.4,
      comfort: 9.1,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 535 000 008",
    },
    roomFeatures: ["zellij-walls", "courtyard-garden", "rooftop-access", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 52,
              beds: "1 Double",
              size: "18m²",
            },
      {
              name: "Family Room",
              price: 75,
              beds: "1 Queen + 1 Single",
              size: "26m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Bab Berdaine",
              distance: "100m",
              time: "2 min walk",
              icon: "gate",
            },
      {
              label: "Bab Mansour",
              distance: "1.2km",
              time: "15 min walk",
              icon: "gate",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riadbabberdaine.com",
    instagramHandle: "@riadbabberdaine",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and affordable choice for solo travelers.",
      couples: "Simple and authentic for budget couples.",
      families: "Good for families wanting value and a traditional setting.",
      business: "Rooftop works for light work sessions.",
      nomad: "A low-cost medina base for nomads on a budget.",
    },
    coordinates: {
      lat: 33.899413,
      lng: -5.567292
    },
    tags: ["family-favorite"]
  },
  {
    id: "mk-sleep-9",
    city: "meknes",
    name: "Riad Ryad Bahia",
    type: "riad",
    neighborhood: "Medina",
    description: "An authentic 18th-century residence with a central courtyard of colorful tiles and citrus trees, creating a calm sanctuary after sightseeing.",
    pricePerNight: 100,
    lifestyle: "balanced",
    amenities: ["Citrus tree-lined central courtyard", "Panoramic old town sunset rooftop", "Traditional mint tea reception", "Homemade local dinner service"],
    googleRating: 4.6,
    googleReviewCount: 450,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 120,
    bookingRating: 4.4,
    bookingReviewCount: 180,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 40,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "seniors"],
    tip: "Relax on the rooftop with fresh mint tea for sweeping views of the historic ramparts.",
    vibeTags: ["Citrus-Courtyard", "Historic", "Calm", "Traditional"],
    locationSummary: "Historic Medina & Place El-Hedim",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Ryad+Bahia+Meknes",
    address: "N13 Tiberbarine, Meknes Medina, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Ryad Bahia preserves the atmosphere of an 18th-century Meknes home, with citrus trees, tilework, and slow local dinners.",
    neighborhoodOverview: "Meknes Medina is calmer and less touristy than Fes or Marrakech, with historic gates, traditional markets, relaxed lanes, and easy walks to Bab Mansour, Lahdim Square, and imperial monuments.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night may not be included.",
    pros: ["Peaceful citrus courtyard", "Homemade dinners", "Good rooftop views"],
    cons: ["No pool", "Traditional rooms rather than modern-luxury"],
    trustScores: {
      cleanliness: 9.3,
      safety: 8.9,
      staff: 9.4,
      value: 9.0,
      comfort: 9.1,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 535 000 009",
    },
    roomFeatures: ["citrus-courtyard", "traditional-tiles", "rooftop-access", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Traditional Double",
              price: 100,
              beds: "1 Queen",
              size: "22m²",
            },
      {
              name: "Family Suite",
              price: 145,
              beds: "1 Queen + 2 Twin",
              size: "36m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Bab Mansour",
              distance: "600m",
              time: "8 min walk",
              icon: "gate",
            },
      {
              label: "Dar Jamai Museum",
              distance: "400m",
              time: "5 min walk",
              icon: "museum",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://ryadbahia.com",
    instagramHandle: "@ryadbahia",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A calm and safe riad for solo travelers.",
      couples: "Quiet and traditional for couples.",
      families: "Good family suites and a peaceful courtyard.",
      business: "Common areas are quiet enough for focused work.",
      nomad: "A balanced medina base for slow remote work.",
    },
    coordinates: {
      lat: 33.8943,
      lng: -5.56623
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "mk-sleep-10",
    city: "meknes",
    name: "Riad Dar Zidane",
    type: "riad",
    neighborhood: "Medina",
    description: "A quiet intimate riad with high-vaulted ceilings, stone arches, deep-toned wood furnishings, textured carpets, and Moroccan lighting.",
    pricePerNight: 82,
    lifestyle: "balanced",
    amenities: ["Cozy fireplace central lounge", "Furnished quiet rooftop deck", "High-speed complimentary Wi-Fi", "Daily traditional Moroccan breakfast"],
    googleRating: 4.6,
    googleReviewCount: 180,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 40,
    bookingRating: 4.4,
    bookingReviewCount: 60,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 10,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "friends"],
    tip: "The riad is located on a very quiet side alley, making it perfect for guests sensitive to street noise.",
    vibeTags: ["Quiet", "Cozy", "Stone-Arches", "Private"],
    locationSummary: "Historic Medina & Place El-Hedim",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Dar+Zidane+Meknes",
    address: "Riad Dar Zidane, Meknes Medina, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Dar Zidane was restored as a small, quiet riad focused on privacy, vaulted spaces, and warm traditional interiors.",
    neighborhoodOverview: "Meknes Medina is calmer and less touristy than Fes or Marrakech, with historic gates, traditional markets, relaxed lanes, and easy walks to Bab Mansour, Lahdim Square, and imperial monuments.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Very quiet location", "Cozy fireplace lounge", "Good WiFi for the medina"],
    cons: ["No pool", "Limited room count"],
    trustScores: {
      cleanliness: 9.3,
      safety: 8.9,
      staff: 9.4,
      value: 9.0,
      comfort: 9.1,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 535 000 010",
    },
    roomFeatures: ["vaulted-ceilings", "stone-arches", "fireplace-lounge", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Quiet Double",
              price: 82,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Superior Room",
              price: 110,
              beds: "1 King",
              size: "28m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Bab Mansour",
              distance: "800m",
              time: "10 min walk",
              icon: "gate",
            },
      {
              label: "Medina Souks",
              distance: "300m",
              time: "4 min walk",
              icon: "shopping",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riaddarzidane.com",
    instagramHandle: "@riaddarzidane",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and peaceful solo stay away from noise.",
      couples: "Cozy and intimate for couples.",
      families: "Best for older children and quiet travelers.",
      business: "High-speed WiFi and quiet corners support remote work.",
      nomad: "A calm, private base for focused nomad days.",
    },
    coordinates: {
      lat: 33.899413,
      lng: -5.567292
    },
    tags: ["family-favorite"]
  },
  {
    id: "mk-sleep-11",
    city: "meknes",
    name: "Riad Palais Didi",
    type: "riad",
    neighborhood: "Medina",
    description: "An awe-inspiring 17th-century palace restored with grand Moorish arches and carved cedar ceilings, once linked to a descendant of Sultan Moulay Sulaiman.",
    pricePerNight: 260,
    lifestyle: "premium",
    amenities: ["Grand central fountain courtyard", "Rooftop directly facing Royal Golf", "Traditional hand-crafted clay hammam", "Fine dining patio restaurant"],
    googleRating: 4.5,
    googleReviewCount: 480,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 150,
    bookingRating: 4.6,
    bookingReviewCount: 200,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 50,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["couple", "family", "seniors", "solo"],
    tip: "Spend time on the rooftop terrace, which directly overlooks the Royal Golf Course.",
    vibeTags: ["Palatial", "Moorish", "Historic", "Royal-Views"],
    locationSummary: "Historic Medina & Place El-Hedim",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Palais+Didi+Meknes",
    address: "7 Dar Lakbira, Meknes Medina, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Palais Didi preserves a grand aristocratic Meknes residence with cedar ceilings, Moorish arches, and views toward the royal golf grounds.",
    neighborhoodOverview: "Meknes Medina is calmer and less touristy than Fes or Marrakech, with historic gates, traditional markets, relaxed lanes, and easy walks to Bab Mansour, Lahdim Square, and imperial monuments.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Grand palace architecture", "Rooftop views toward Royal Golf", "Historic atmosphere"],
    cons: ["No pool", "Formal palace feel may not suit everyone"],
    trustScores: {
      cleanliness: 9.1,
      safety: 8.9,
      staff: 9.2,
      value: 8.4,
      comfort: 8.9,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 535 000 011",
    },
    roomFeatures: ["cedarwood-ceilings", "moorish-arches", "rooftop-access", "ac", "heating", "courtyard-view"],
    roomTypes: [
      {
              name: "Palace Room",
              price: 260,
              beds: "1 Queen",
              size: "30m²",
            },
      {
              name: "Royal Suite",
              price: 390,
              beds: "1 King",
              size: "55m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Royal Golf",
              distance: "View/nearby",
              time: "5 min walk",
              icon: "golf",
            },
      {
              label: "Bab Mansour",
              distance: "700m",
              time: "9 min walk",
              icon: "gate",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riadpalaisdidi.com",
    instagramHandle: "@riadpalaisdidi",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and grand choice for solo history lovers.",
      couples: "Romantic for couples who love historic architecture.",
      families: "Spacious rooms work well for families.",
      business: "Quiet palace corners support business calls and laptop time.",
      nomad: "A regal medina base for creative remote work.",
    },
    coordinates: {
      lat: 33.89058,
      lng: -5.561973
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "mk-sleep-12",
    city: "meknes",
    name: "Riad Menthe Et Citron",
    type: "riad",
    neighborhood: "Medina",
    description: "A delightful family-run boutique riad with intricate plaster carvings, bright colors, citrus scents, and cheerful shared spaces.",
    pricePerNight: 95,
    lifestyle: "balanced",
    amenities: ["Charming citrus tree-lined patio", "Rooftop overlooking old ramparts", "Customized day trips to Volubilis", "Freshly baked Moroccan pastries daily"],
    googleRating: 4.5,
    googleReviewCount: 340,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 80,
    bookingRating: 4.6,
    bookingReviewCount: 100,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 20,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family"],
    tip: "The host can arrange highly informative custom day trips to the Roman ruins of Volubilis.",
    vibeTags: ["Cheerful", "Family-Run", "Citrus", "Boutique"],
    locationSummary: "Historic Medina & Place El-Hedim",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Menthe+Et+Citron+Meknes",
    address: "Riad Menthe Et Citron, Meknes Medina, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Menthe Et Citron was created as a bright family riad where fresh pastries, citrus scents, and local excursions set the tone.",
    neighborhoodOverview: "Meknes Medina is calmer and less touristy than Fes or Marrakech, with historic gates, traditional markets, relaxed lanes, and easy walks to Bab Mansour, Lahdim Square, and imperial monuments.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Warm family welcome", "Good Volubilis trip planning", "Cheerful patio atmosphere"],
    cons: ["No pool", "Can be hard to find first arrival"],
    trustScores: {
      cleanliness: 9.1,
      safety: 8.9,
      staff: 9.2,
      value: 9.0,
      comfort: 8.9,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 535 000 012",
    },
    roomFeatures: ["citrus-patio", "plaster-carvings", "rooftop-access", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Double Room",
              price: 95,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Family Room",
              price: 135,
              beds: "1 Queen + 2 Twin",
              size: "34m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Bab Mansour",
              distance: "700m",
              time: "9 min walk",
              icon: "gate",
            },
      {
              label: "Volubilis",
              distance: "30km",
              time: "35 min drive",
              icon: "history",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riadmentheetcitron.com",
    instagramHandle: "@riadmentheetcitron",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and cheerful home base for solo travelers.",
      couples: "Warm and intimate for couples.",
      families: "Good for families who want tours and friendly hosts.",
      business: "Quiet enough for light work in common spaces.",
      nomad: "A friendly medina base for slow travel and day-trip planning.",
    },
    coordinates: {
      lat: 33.895611,
      lng: -5.56333
    },
    tags: ["family-favorite"]
  },
  {
    id: "mk-sleep-13",
    city: "meknes",
    name: "Riad Atika Mek",
    type: "riad",
    neighborhood: "Medina",
    description: "A traditional riad with cedarwood balconies and red-and-white zellij mosaics, highlighted by a trickling fountain in the central patio.",
    pricePerNight: 90,
    lifestyle: "balanced",
    amenities: ["Intricate hand-carved cedarwood balconies", "Spacious family suites with fireplaces", "Panoramic rooftop breakfast deck", "Airport transfer booking service"],
    googleRating: 4.4,
    googleReviewCount: 510,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 150,
    bookingRating: 4.3,
    bookingReviewCount: 200,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 50,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["couple", "family", "solo"],
    tip: "Perfect for couples; the master suite offers a cozy private fireplace.",
    vibeTags: ["Traditional", "Cedarwood", "Romantic", "Rooftop"],
    locationSummary: "Historic Medina & Place El-Hedim",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Atika+Mek+Meknes",
    address: "Riad Atika Mek, Meknes Medina, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad Atika Mek keeps the decorative language of Meknes alive through cedar balconies, zellij mosaics, and a calm fountain patio.",
    neighborhoodOverview: "Meknes Medina is calmer and less touristy than Fes or Marrakech, with historic gates, traditional markets, relaxed lanes, and easy walks to Bab Mansour, Lahdim Square, and imperial monuments.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Romantic fireplace suites", "Traditional cedar and zellij details", "Good rooftop breakfast"],
    cons: ["No pool", "Some rooms are traditional rather than modern"],
    trustScores: {
      cleanliness: 8.9,
      safety: 8.9,
      staff: 9.0,
      value: 9.0,
      comfort: 8.7,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 535 000 013",
    },
    roomFeatures: ["cedarwood-balconies", "fireplace-available", "zellij-mosaics", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 90,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Master Suite",
              price: 140,
              beds: "1 King",
              size: "35m²",
            },
      {
              name: "Family Suite",
              price: 160,
              beds: "1 Queen + 2 Twin",
              size: "40m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Bab Mansour",
              distance: "650m",
              time: "8 min walk",
              icon: "gate",
            },
      {
              label: "Lahdim Square",
              distance: "700m",
              time: "9 min walk",
              icon: "city",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riadatikamek.com",
    instagramHandle: "@riadatikamek",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and traditional base for solo medina wandering.",
      couples: "The fireplace suite is especially romantic.",
      families: "Spacious family suites make it practical for families.",
      business: "Rooftop and courtyard are good for light laptop work.",
      nomad: "A traditional setting for slow, focused remote work.",
    },
    coordinates: {
      lat: 33.89477,
      lng: -5.566406
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "mk-sleep-14",
    city: "meknes",
    name: "Riad Ritaj",
    type: "riad",
    neighborhood: "Medina",
    description: "A preserved historic merchant house with a warm family-run atmosphere, zellij-covered walls, rich drapery, and a welcoming central lounge.",
    pricePerNight: 95,
    lifestyle: "balanced",
    amenities: ["Colorful authentic zellij mosaics", "Tranquil central water fountain", "Furnished sunset rooftop deck", "Airport shuttle & tour services"],
    googleRating: 4.4,
    googleReviewCount: 420,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 100,
    bookingRating: 4.3,
    bookingReviewCount: 150,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 30,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Go up to the high rooftop terrace in the evening for views of the old town minarets.",
    vibeTags: ["Family-Run", "Zellij", "Merchant-House", "Warm"],
    locationSummary: "Historic Medina & Place El-Hedim",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Ritaj+Meknes",
    address: "Riad Ritaj, Meknes Medina, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad Ritaj reflects the atmosphere of an old merchant home, with colorful zellij, drapery, and a family-run sense of welcome.",
    neighborhoodOverview: "Meknes Medina is calmer and less touristy than Fes or Marrakech, with historic gates, traditional markets, relaxed lanes, and easy walks to Bab Mansour, Lahdim Square, and imperial monuments.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Warm family atmosphere", "Colorful zellij interiors", "Good rooftop views"],
    cons: ["No pool", "Traditional decor can feel busy"],
    trustScores: {
      cleanliness: 8.9,
      safety: 8.9,
      staff: 9.0,
      value: 9.0,
      comfort: 8.7,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 535 000 014",
    },
    roomFeatures: ["zellij-mosaics", "central-fountain", "rooftop-access", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Double Room",
              price: 95,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Family Room",
              price: 130,
              beds: "1 Queen + 1 Single",
              size: "30m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Bab Mansour",
              distance: "600m",
              time: "8 min walk",
              icon: "gate",
            },
      {
              label: "Medina Souks",
              distance: "300m",
              time: "4 min walk",
              icon: "shopping",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riadritaj.com",
    instagramHandle: "@riadritaj",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and warm choice for solo travelers.",
      couples: "Traditional and cozy for couples.",
      families: "Good for families seeking an authentic medina stay.",
      business: "Quiet lounge spaces work for emails and planning.",
      nomad: "A friendly riad for light remote work and medina life.",
    },
    coordinates: {
      lat: 33.89387,
      lng: -5.565986
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "mk-sleep-15",
    city: "meknes",
    name: "Barceló Meknès",
    type: "hotel",
    neighborhood: "Ville Nouvelle",
    description: "A sleek contemporary hotel in modern Meknes with business-oriented amenities, spacious rooms, European flair, and panoramic city views.",
    pricePerNight: 120,
    lifestyle: "balanced",
    amenities: ["Outdoor sun-deck swimming pool", "Modern fitness center & gym", "Trendy cocktail & piano lounge", "Equipped business meeting spaces"],
    googleRating: 4.3,
    googleReviewCount: 1800,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 500,
    bookingRating: 4.4,
    bookingReviewCount: 800,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 200,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "business-friendly", "family"],
    tip: "Enjoy a relaxed evening at the on-site lounge, which often features live piano music on weekends.",
    vibeTags: ["Modern", "Business", "City-Views", "Convenient"],
    locationSummary: "Hamria - Ville Nouvelle",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Barcelo+Meknes",
    address: "2 Rue d’Accra, Ville Nouvelle, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Barceló Meknès brings contemporary chain-hotel comfort to the imperial city, focused on business travel, meetings, and easy modern-city access.",
    neighborhoodOverview: "Ville Nouvelle is modern Meknes, offering wider streets, train access, business services, parking, and practical hotels a short taxi ride from the historic medina.",
    hiddenFeesNotice: "City tax of 17.60 MAD per person/night not included.",
    pros: ["Good business facilities", "Modern rooms and city views", "Pool and fitness center"],
    cons: ["Lacks riad atmosphere", "Taxi needed for deeper medina sights"],
    trustScores: {
      cleanliness: 9.2,
      safety: 9.6,
      staff: 9.0,
      value: 8.8,
      comfort: 9.1,
      location: 9.0,
    },
    logistics: {
      checkIn: "15:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free on-site or secure nearby parking",
      contact: "+212 535 000 015",
    },
    roomFeatures: ["city-view", "workspace", "ac", "heating", "soundproof", "elevator-access"],
    roomTypes: [
      {
              name: "Superior Room",
              price: 120,
              beds: "1 Queen",
              size: "26m²",
            },
      {
              name: "Junior Suite",
              price: 180,
              beds: "1 King",
              size: "42m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Meknes Train Station",
              distance: "1km",
              time: "12 min walk",
              icon: "train",
            },
      {
              label: "Bab Mansour",
              distance: "2.5km",
              time: "8 min drive",
              icon: "gate",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - family rooms available",
    officialWebsite: "https://www.barcelo.com/en-gb/barcelo-meknes/",
    instagramHandle: "@barcelomeknes",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and practical solo business choice.",
      couples: "Comfortable and modern for couples who prefer hotels.",
      families: "Good for families needing elevator and parking access.",
      business: "Strong meeting spaces and reliable WiFi.",
      nomad: "A practical nomad base with workspace and modern services.",
    },
    coordinates: {
      lat: 33.865135,
      lng: -5.576339
    },
    tags: ["family-favorite"]
  },
  {
    id: "mk-sleep-16",
    city: "meknes",
    name: "Riad Zahraa Al Ismailia",
    type: "riad",
    neighborhood: "Medina",
    description: "A charming budget-friendly riad decorated with vibrant blue-and-white zellij, cozy lounge alcoves, and a central fountain.",
    pricePerNight: 48,
    lifestyle: "lean",
    amenities: ["Classic blue zellij courtyard", "Comfortable shared lounge alcoves", "Panoramic sunset rooftop deck", "Traditional mint tea reception"],
    googleRating: 4.3,
    googleReviewCount: 390,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 100,
    bookingRating: 4.4,
    bookingReviewCount: 150,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 30,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "This riad is exceptionally easy to locate compared to others hidden deep in the medina.",
    vibeTags: ["Budget", "Blue-Zellij", "Easy-Access", "Traditional"],
    locationSummary: "Historic Medina & Place El-Hedim",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Zahraa+Al+Ismailia+Meknes",
    address: "Riad Zahraa Al Ismailia, Meknes Medina, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad Zahraa Al Ismailia focuses on classic blue zellij, a practical medina location, and a welcoming budget stay.",
    neighborhoodOverview: "Meknes Medina is calmer and less touristy than Fes or Marrakech, with historic gates, traditional markets, relaxed lanes, and easy walks to Bab Mansour, Lahdim Square, and imperial monuments.",
    hiddenFeesNotice: "City tax may not be included in the base rate.",
    pros: ["Easy to locate", "Great budget value", "Charming blue courtyard"],
    cons: ["No pool", "Simple room amenities"],
    trustScores: {
      cleanliness: 8.7,
      safety: 8.9,
      staff: 8.8,
      value: 9.4,
      comfort: 8.5,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 535 000 016",
    },
    roomFeatures: ["blue-zellij", "shared-lounge", "rooftop-access", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Budget Double",
              price: 48,
              beds: "1 Double",
              size: "16m²",
            },
      {
              name: "Family Room",
              price: 70,
              beds: "1 Queen + 1 Single",
              size: "24m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Bab Mansour",
              distance: "700m",
              time: "9 min walk",
              icon: "gate",
            },
      {
              label: "Medina Market",
              distance: "300m",
              time: "4 min walk",
              icon: "market",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riadzahraa.com",
    instagramHandle: "@riadzahraaismailia",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and easy budget stay for solo travelers.",
      couples: "Simple and traditional for couples on a budget.",
      families: "Good for families needing affordable rooms.",
      business: "Rooftop is usable for light work.",
      nomad: "A low-cost medina base for practical remote work.",
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "mk-sleep-17",
    city: "meknes",
    name: "Zaki Suites Hôtel & Spa",
    type: "hotel",
    neighborhood: "Ville Nouvelle",
    description: "A sprawling modern 4-star hotel in traditional style with landscaped gardens, high above the ramparts and overlooking Oued Boufekrane Valley.",
    pricePerNight: 280,
    lifestyle: "premium",
    amenities: ["Sizable outdoor swimming pool", "Lush tropical manicured gardens", "Traditional Moroccan wellness spa", "Secure complimentary private parking"],
    googleRating: 4.2,
    googleReviewCount: 1000,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 300,
    bookingRating: 4.3,
    bookingReviewCount: 400,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 100,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "business-friendly"],
    tip: "Opt for a suite with private balcony facing the interior gardens for a quieter stay.",
    vibeTags: ["Garden-Hotel", "Spa", "Valley-View", "Business"],
    locationSummary: "Hamria - Ville Nouvelle",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Zaki+Suites+Hotel+Spa+Meknes",
    address: "Boulevard Al Massira, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Zaki Suites was built as a large garden hotel for travelers who want city access, parking, pool time, and a more resort-like feel than the medina.",
    neighborhoodOverview: "Ville Nouvelle is modern Meknes, offering wider streets, train access, business services, parking, and practical hotels a short taxi ride from the historic medina.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Large gardens and pool", "Secure parking", "Good for business and families"],
    cons: ["Less historic character", "Higher price than many city hotels"],
    trustScores: {
      cleanliness: 8.5,
      safety: 9.6,
      staff: 8.6,
      value: 8.4,
      comfort: 8.3,
      location: 8.8,
    },
    logistics: {
      checkIn: "15:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free on-site or secure nearby parking",
      contact: "+212 535 000 017",
    },
    roomFeatures: ["garden-view", "private-balcony", "workspace", "ac", "heating", "elevator-access"],
    roomTypes: [
      {
              name: "Superior Room",
              price: 280,
              beds: "1 Queen",
              size: "30m²",
            },
      {
              name: "Garden Suite",
              price: 390,
              beds: "1 King",
              size: "55m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Meknes Center",
              distance: "3km",
              time: "8 min drive",
              icon: "city",
            },
      {
              label: "Bab Mansour",
              distance: "4km",
              time: "10 min drive",
              icon: "gate",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - family rooms available",
    officialWebsite: "https://zakisuiteshotel.com",
    instagramHandle: "@zakisuites",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and spacious base for solo travelers wanting hotel comforts.",
      couples: "Garden suites are peaceful for couples.",
      families: "Good pool and gardens for families.",
      business: "Strong parking and meeting comfort for business travelers.",
      nomad: "A practical workation base with pool and garden breaks.",
    },
    coordinates: {
      lat: 33.881045,
      lng: -5.533418
    },
    tags: ["family-favorite"]
  },
  {
    id: "mk-sleep-18",
    city: "meknes",
    name: "Hotel Menzeh Dalia",
    type: "hotel",
    neighborhood: "Ville Nouvelle",
    description: "A comfortable modern 4-star hotel with large outdoor pool and gardens, blending European design with traditional Moroccan accents.",
    pricePerNight: 85,
    lifestyle: "balanced",
    amenities: ["Expansive garden swimming pool", "Traditional lounge & nightclub", "Secure enclosed private parking", "On-site family buffet restaurant"],
    googleRating: 4.1,
    googleReviewCount: 750,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 200,
    bookingRating: 4.2,
    bookingReviewCount: 300,
    hotelguruRating: 4.1,
    hotelguruReviewCount: 80,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Strong choice with a rental car thanks to secure on-site parking.",
    vibeTags: ["Modern", "Garden-Pool", "Parking", "Family"],
    locationSummary: "Hamria - Ville Nouvelle",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Hotel+Menzeh+Dalia+Meknes",
    address: "Domaine Izmar, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Menzeh Dalia provides a practical garden-hotel experience for travelers who prefer pool, parking, and easy road access over medina lanes.",
    neighborhoodOverview: "Ville Nouvelle is modern Meknes, offering wider streets, train access, business services, parking, and practical hotels a short taxi ride from the historic medina.",
    hiddenFeesNotice: "City tax of 17.60 MAD per person/night not included.",
    pros: ["Secure parking", "Large pool and gardens", "Good value for families"],
    cons: ["Outside historic medina", "Nightclub may add noise at times"],
    trustScores: {
      cleanliness: 8.3,
      safety: 9.6,
      staff: 8.4,
      value: 9.0,
      comfort: 8.1,
      location: 8.8,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Free on-site or secure nearby parking",
      contact: "+212 535 000 018",
    },
    roomFeatures: ["garden-view", "pool-view", "ac", "heating", "workspace", "elevator-access"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 85,
              beds: "1 Queen",
              size: "24m²",
            },
      {
              name: "Family Room",
              price: 120,
              beds: "1 Queen + 2 Twin",
              size: "34m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Meknes Center",
              distance: "4km",
              time: "10 min drive",
              icon: "city",
            },
      {
              label: "Bab Mansour",
              distance: "5km",
              time: "12 min drive",
              icon: "gate",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://hotelmenzehdalia.com",
    instagramHandle: "@menzehdalia",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Safe and practical for solo travelers with a car.",
      couples: "Comfortable for couples who want a pool and parking.",
      families: "Good for families thanks to pool and buffet.",
      business: "Works well for business drivers and meetings.",
      nomad: "A practical hotel base for nomads needing parking and pool downtime.",
    },
    coordinates: {
      lat: 33.857595,
      lng: -5.585847
    },
    tags: ["family-favorite"]
  },
  {
    id: "mk-sleep-19",
    city: "meknes",
    name: "Hotel Transatlantique",
    type: "hotel",
    neighborhood: "Ville Nouvelle",
    description: "A legendary grand mid-century hotel set in a vast park with views over the old city walls, preserving classical style with wood paneling, vintage bars, and balconies.",
    pricePerNight: 110,
    lifestyle: "balanced",
    amenities: ["Two large outdoor pools", "Expansive 3-acre palm gardens", "Historic wood-paneled piano bar", "Private balconies with city views"],
    googleRating: 4.1,
    googleReviewCount: 1600,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 400,
    bookingRating: 4.2,
    bookingReviewCount: 800,
    hotelguruRating: 4.1,
    hotelguruReviewCount: 200,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "seniors", "business-friendly"],
    tip: "Take an evening stroll through the gardens to watch sunset over the medina.",
    vibeTags: ["Historic-Hotel", "Mid-Century", "Gardens", "City-Views"],
    locationSummary: "Hamria - Ville Nouvelle",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Hotel+Transatlantique+Meknes",
    address: "Avenue des FAR, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Hotel Transatlantique is a classic Meknes institution, preserving the atmosphere of grand mid-century travel with gardens, views, and vintage lounges.",
    neighborhoodOverview: "Ville Nouvelle is modern Meknes, offering wider streets, train access, business services, parking, and practical hotels a short taxi ride from the historic medina.",
    hiddenFeesNotice: "City tax of 17.60 MAD per person/night not included.",
    pros: ["Historic character", "Large gardens and two pools", "Great city-wall views"],
    cons: ["Some areas feel dated", "Not inside the medina"],
    trustScores: {
      cleanliness: 8.3,
      safety: 9.6,
      staff: 8.4,
      value: 9.0,
      comfort: 8.1,
      location: 8.8,
    },
    logistics: {
      checkIn: "15:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free on-site or secure nearby parking",
      contact: "+212 535 000 019",
    },
    roomFeatures: ["private-balcony", "city-view", "classic-decor", "ac", "heating", "elevator-access"],
    roomTypes: [
      {
              name: "Classic Room",
              price: 110,
              beds: "1 Queen",
              size: "24m²",
            },
      {
              name: "City View Room",
              price: 135,
              beds: "1 King",
              size: "28m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Meknes Medina",
              distance: "2km",
              time: "5 min drive",
              icon: "city",
            },
      {
              label: "Meknes Train Station",
              distance: "2.5km",
              time: "8 min drive",
              icon: "train",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome",
    officialWebsite: "https://hoteltransatlantiquemeknes.com",
    instagramHandle: "@hoteltransatlantique",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and scenic classic hotel for solo travelers.",
      couples: "Gardens and vintage bar make it romantic for old-world couples.",
      families: "Good for families thanks to pools and park-like grounds.",
      business: "Quiet lounges and parking suit business travel.",
      nomad: "A classic hotel base for work with garden breaks.",
    },
    coordinates: {
      lat: 33.903402,
      lng: -5.560149
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "mk-sleep-20",
    city: "meknes",
    name: "ibis Meknes Hotel",
    type: "hotel",
    neighborhood: "Ville Nouvelle",
    description: "A reliable practical chain hotel in the modern center near the train station, with clean minimalist rooms, modern conveniences, and a tranquil courtyard garden.",
    pricePerNight: 65,
    lifestyle: "lean",
    amenities: ["Tranquil courtyard swimming pool", "Modern minimalist restaurant & bar", "Proximity to central train station", "Pet-friendly accommodation policy"],
    googleRating: 4.0,
    googleReviewCount: 4000,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 1000,
    bookingRating: 4.1,
    bookingReviewCount: 1500,
    hotelguruRating: 4.0,
    hotelguruReviewCount: 500,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "friends", "business-friendly"],
    tip: "Its proximity to Meknes-Al Amir Abdelkader train station makes it highly convenient for train travelers.",
    vibeTags: ["Reliable", "Budget", "Chain-Hotel", "Transit-Friendly"],
    locationSummary: "Hamria - Ville Nouvelle",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=ibis+Meknes+Hotel",
    address: "Avenue des FAR, Meknes 50000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "ibis Meknes delivers the familiar Accor budget formula for travelers who want clean rooms, train access, and easy taxis over medina atmosphere.",
    neighborhoodOverview: "Ville Nouvelle is modern Meknes, offering wider streets, train access, business services, parking, and practical hotels a short taxi ride from the historic medina.",
    hiddenFeesNotice: "City tax of 17.60 MAD per person/night not included.",
    pros: ["Reliable and affordable", "Near train station", "Pet-friendly and practical"],
    cons: ["Compact rooms", "Limited local character"],
    trustScores: {
      cleanliness: 8.1,
      safety: 9.6,
      staff: 8.2,
      value: 9.4,
      comfort: 7.9,
      location: 8.8,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free on-site or secure nearby parking",
      contact: "+212 535 000 020",
    },
    roomFeatures: ["minimalist-room", "workspace", "ac", "heating", "elevator-access", "shower-ensuite"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 65,
              beds: "1 Double",
              size: "18m²",
            },
      {
              name: "Twin Room",
              price: 70,
              beds: "2 Twin",
              size: "18m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Meknes Train Station",
              distance: "500m",
              time: "6 min walk",
              icon: "train",
            },
      {
              label: "Bab Mansour",
              distance: "2km",
              time: "6 min drive",
              icon: "gate",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://all.accor.com/hotel/2033/index.en.shtml",
    instagramHandle: "@ibismeknes",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and practical budget option for solo travelers.",
      couples: "Simple and reliable for couples in transit.",
      families: "Compact but workable for short family stays.",
      business: "Good for business travelers who need train access.",
      nomad: "A reliable budget base with workspace and easy transport.",
    },
    coordinates: {
      lat: 33.894666,
      lng: -5.549977
    },
    tags: ["family-favorite"]
  }
]
