import type { SleepListing } from '../types'

/**
 * SLEEP LISTING DATA TEMPLATE (Copy this for your search agent)
 * -------------------------------------------------------------
 * {
 *   "id": "city-sleep-XX",
 *   "name": "",
 *   "type": "riad | hotel | villa | hostel | apartment | guesthouse",
 *   "neighborhood": "",
 *   "city": "[city]",
 *   "description": "",
 *   "pricePerNight": 0,
 *   "lifestyle": "lean | balanced | premium",
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2', 'url3']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source (replaces single rating/reviewCount)
 *   // ═══════════════════════════════════════════════════
 *   // Search for real ratings from Google, TripAdvisor, Booking.com, and HotelGuru.
 *   // If you cannot find a rating for a specific source, set it to the same value as
 *   // the closest available one so average calculations don't break.
 *
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *   bookingRating: [4.x],
 *   bookingReviewCount: [number],
 *   hotelguruRating: [4.x],
 *   hotelguruReviewCount: [number],
 *
 *   // ═══════════════════════════════════════════════════
 *   // BOOLEAN AMENITIES
 *   // ═══════════════════════════════════════════════════
 *
 *   hasPool: true | false,
 *   hasBreakfast: true | false,
 *   hasAC: true | false,
 *   hasHeating: true | false,
 *   hasRooftop: true | false,
 *   hasEnsuite: true | false,
 *   hasRestaurant: true | false,
 *   hasBar: true | false,
 *   hasGym: true | false,
 *   hasElevator: true | false,
 *   hasLaundryService: true | false,
 *   hasRoomService: true | false,
 *   petFriendly: true | false,
 *   isWheelchairAccessible: true | false,
 *   taxesIncluded: true | false,
 *   freeCancellation: true | false,
 *   kidsStayFree: true | false,
 *
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearMosque: true | false,
 *   safetyLevel: 1 | 2 | 3 | 4 | 5,
 *
 *   // ═══════════════════════════════════════════════════
 *   // TRUST SCORES
 *   // ═══════════════════════════════════════════════════
 *
 *   trustScores: {
 *     cleanliness: [1-10],
 *     safety: [1-10],
 *     staff: [1-10],
 *     value: [1-10],
 *     comfort: [1-10],
 *     location: [1-10]
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   amenities: ['wifi', 'pool', 'ac', 'breakfast', 'spa', 'restaurant', 'gym', 'kitchenette', 'parking', 'bar', 'laundry', 'elevator', 'room-service'],
 *   tip: '[Short insider tip]',
 *   vibeTags: ['Authentic', 'Quiet', 'Modern'],
 *   locationSummary: 'Beachfront | City Center | Medina | Airport Area | Residential | Tourist Zone',
 *   availabilityText: 'Available tonight | Only 2 rooms left | Available on selected dates',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   address: '[Full street address, City, Postal Code, Morocco]',
 *
 *   paymentMethods: ['card', 'cash'],
 *   languagesSpoken: ['Arabic', 'French', 'English', 'Spanish', 'German'],
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   customStory: 'Brief history, owner background, or architecture notes...',
 *   neighborhoodOverview: 'Description of the local atmosphere, safety, and vibe...',
 *   hiddenFeesNotice: 'City tax of XX MAD per person/night not included...',
 *   pros: ['Pro 1', 'Pro 2'],
 *   cons: ['Con 1'],
 *
 *   // ═══════════════════════════════════════════════════
 *   // LOGISTICS
 *   // ═══════════════════════════════════════════════════
 *
 *   logistics: {
 *     checkIn: '14:00 - 22:00',
 *     checkOut: 'Before 11:00',
 *     luggageStorage: 'Free | Paid | None',
 *     parking: 'Free on-site | Nearby public | Valet',
 *     contact: '+212 XXXXXXXXX'
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *   // ROOM FEATURES & TYPES
 *   // ═══════════════════════════════════════════════════
 *
 *   roomFeatures: ['soundproof', 'workspace', 'private-balcony', 'ac', 'heating', 'balcony', 'shower-ensuite', 'sea-view', 'garden-view', 'pool-view'],
 *   roomTypes: [
 *     {
 *       name: 'Double Room',
 *       price: 500,
 *       beds: '1 Queen',
 *       size: '20m2',
 *     }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *   // NEIGHBORHOOD DISTANCES
 *   // ═══════════════════════════════════════════════════
 *
 *   neighborhoodDistances: [
 *     { label: 'Beach', distance: '500m', time: '5 min walk', icon: 'beach' }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   cancellationPolicy: 'Free cancellation up to 24h before check-in | Flexible | Non-refundable',
 *   childPolicy: 'Children welcome | Free under 6 | Extra bed 200 MAD',
 *   officialWebsite: 'https://...',
 *   instagramHandle: '@...',
 *
 *   // googlePlaceId: "PLACE_ID_HERE",
 *
 *   // ═══════════════════════════════════════════════════
 *   // REVIEW HIGHLIGHTS
 *   // ═══════════════════════════════════════════════════
 *
 *   reviewHighlights: {
 *     solo: 'Great insight for solo...',
 *     couples: 'Great for couples...',
 *     families: 'Kid-friendly details...',
 *     business: 'Wi-Fi test details...',
 *     nomad: 'Remote work specific insight...'
 *   }
 * }
 */

export const ouzoudSleep: SleepListing[] = [
  {
    id: "oz-sleep-1",
    city: "ouzoud",
    name: "Kasbah Bab Ourika",
    type: "hotel",
    neighborhood: "Aghbalou",
    description: "Its authentic pisé clay walls, central square courtyard, and panoramic stargazing roof terrace deliver a serene, magical atmosphere.",
    pricePerNight: 250,
    lifestyle: "premium",
    amenities: ["Panoramic Rooftop Sun Deck", "Two Authentic Onsite Restaurants", "Air Conditioning", "Traditional Moroccan Breakfast"],
    googleRating: 4.8,
    googleReviewCount: 660,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 150,
    bookingRating: 4.7,
    bookingReviewCount: 200,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 50,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: false,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Book the deluxe family master suite to enjoy a massive private terrace overlooking the canyon walls.",
    vibeTags: ["Pisé", "Rooftop", "Canyon-Views", "Serene"],
    locationSummary: "Aghbalou - Canyon View Kasbah",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Kasbah+Bab+Ourika+Ouzoud",
    address: "Aghbalou, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "This kasbah-style stay focuses on clay architecture, rooftop stargazing, and quiet canyon-facing terraces in the Ouzoud region.",
    neighborhoodOverview: "Aghbalou is a quieter rural area with canyon and mountain views, best suited to travelers with a car or arranged transfer who want distance from the busiest cascade crowds.",
    hiddenFeesNotice: "Taxes included; private transfers and excursions may be extra.",
    pros: ["Panoramic rooftop terrace", "Authentic clay architecture", "Family suite with large terrace"],
    cons: ["No pool", "Cancellation can be strict"],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.2,
      staff: 9.6,
      value: 8.4,
      comfort: 9.4,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Secure on-site parking",
      contact: "+212 523 000 001",
    },
    roomFeatures: ["pise-clay-walls", "private-terrace-available", "canyon-view", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Deluxe Room",
              price: 250,
              beds: "1 Queen",
              size: "28m²",
            },
      {
              name: "Family Master Suite",
              price: 360,
              beds: "1 King + 2 Single",
              size: "55m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ouzoud Waterfalls",
              distance: "8km",
              time: "15 min drive",
              icon: "waterfall",
            },
      {
              label: "Canyon Viewpoint",
              distance: "500m",
              time: "7 min walk",
              icon: "viewpoint",
            },
    ],
    cancellationPolicy: "Strict 7-day",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://kasbahbabourika-ouzoud.com",
    instagramHandle: "@kasbahbabourikaouzoud",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and quiet base for solo travelers seeking views.",
      couples: "Serene rooftop sunsets make it romantic for couples.",
      families: "The large terrace suite is practical for families.",
      business: "Quiet enough for light work and writing.",
      nomad: "A peaceful rural base for nomads with a car.",
    },
  },
  {
    id: "oz-sleep-2",
    city: "ouzoud",
    name: "Le Domaine M",
    type: "guesthouse",
    neighborhood: "Ait Taguella",
    description: "An exceptional high-end luxury guesthouse located a six-minute walk from the waterfalls, surrounded by tranquility with rooms featuring spring-water bathtubs and private yards.",
    pricePerNight: 280,
    lifestyle: "premium",
    amenities: ["Spring-Water Bathtubs", "Outdoor Swimming Pool", "Beautiful Private Yards", "Complimentary Guest Parking"],
    googleRating: 4.8,
    googleReviewCount: 210,
    tripadvisorRating: 5.0,
    tripadvisorReviewCount: 50,
    bookingRating: 4.7,
    bookingReviewCount: 80,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 20,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "seniors"],
    tip: "Take advantage of early morning pool access; the water is refreshing before midday sun peaks.",
    vibeTags: ["Luxury-Guesthouse", "Pool", "Private-Yards", "Waterfall-Walk"],
    locationSummary: "Ait Taguella - 6 min from Falls",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Le+Domaine+M+Ouzoud",
    address: "Ait Taguella, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Le Domaine M was created as a polished waterfall-area retreat, combining quiet gardens, private yards, and elevated comfort close to the cascades.",
    neighborhoodOverview: "Ait Taguella sits just outside the busiest waterfall path, offering quieter stays, private gardens, pools, and quick access to Ouzoud’s main viewpoints.",
    hiddenFeesNotice: "Taxes included; spa-style extras or private transfers may be extra.",
    pros: ["Walkable to waterfalls", "Spring-water bathtubs", "Pool and private yards"],
    cons: ["Premium pricing for Ouzoud", "Limited nightlife nearby"],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.7,
      staff: 9.5,
      value: 8.5,
      comfort: 9.6,
      location: 9.7,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public or on-site parking",
      contact: "+212 523 000 002",
    },
    roomFeatures: ["spring-water-bathtub", "private-yard", "pool-view", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Private Yard Room",
              price: 280,
              beds: "1 King",
              size: "32m²",
            },
      {
              name: "Family Suite",
              price: 380,
              beds: "1 King + 2 Single",
              size: "55m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ouzoud Waterfalls",
              distance: "500m",
              time: "6 min walk",
              icon: "waterfall",
            },
      {
              label: "Ait Taguella Village",
              distance: "300m",
              time: "4 min walk",
              icon: "village",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://ledomainemouzoud.com",
    instagramHandle: "@ledomainem",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and tranquil upscale base for solo travelers.",
      couples: "Private yards and bathtubs are very romantic.",
      families: "Great for families thanks to pool and easy falls access.",
      business: "Quiet gardens work well for focused remote work.",
      nomad: "A premium waterfall base for calm workation days.",
    },
  },
  {
    id: "oz-sleep-3",
    city: "ouzoud",
    name: "Kasbah Ntifa",
    type: "hotel",
    neighborhood: "Ouzoud Center",
    description: "A spectacular country resort in the quiet outskirts of Ouzoud, offering an outdoor pool, mountain views, and a spacious basecamp after exploring the falls.",
    pricePerNight: 255,
    lifestyle: "premium",
    amenities: ["Large Outdoor Swimming Pool", "Scenic Mountain Views", "Onsite Spa & Hammam", "Shared Garden Lounge"],
    googleRating: 4.8,
    googleReviewCount: 125,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 30,
    bookingRating: 4.7,
    bookingReviewCount: 50,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 10,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Request a family villa package when traveling in a group to enjoy a private garden terrace.",
    vibeTags: ["Country-Resort", "Mountain-Views", "Spa", "Family-Villa"],
    locationSummary: "Ouzoud Outskirts - Mountain Resort",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Kasbah+Ntifa+Ouzoud",
    address: "Ouzoud Center, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Kasbah Ntifa was designed as a country-resort base for travelers who want pool, spa, and garden space near the cascades.",
    neighborhoodOverview: "Ouzoud Center is practical for restaurants, transport, shops, and walking access to the falls, with guesthouses and small hotels spread across the village lanes.",
    hiddenFeesNotice: "Taxes included; spa and private villa package extras may be charged separately.",
    pros: ["Large pool and mountain views", "Spa and hammam", "Family villa options"],
    cons: ["Outside the main waterfall path", "Requires short transfer or walk"],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.6,
      staff: 9.8,
      value: 8.4,
      comfort: 9.4,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Secure on-site parking",
      contact: "+212 523 000 003",
    },
    roomFeatures: ["mountain-view", "private-garden-terrace", "spa-access", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Mountain Room",
              price: 255,
              beds: "1 Queen",
              size: "30m²",
            },
      {
              name: "Family Villa",
              price: 420,
              beds: "1 King + 2 Twin",
              size: "75m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ouzoud Waterfalls",
              distance: "2km",
              time: "5 min drive",
              icon: "waterfall",
            },
      {
              label: "Ouzoud Center",
              distance: "1km",
              time: "12 min walk",
              icon: "village",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://kasbahntifa.com",
    instagramHandle: "@kasbahntifa",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and spacious resort-style base for solo travelers.",
      couples: "Mountain views and spa are romantic for couples.",
      families: "Excellent for families and groups needing space.",
      business: "Quiet garden lounge suits work and planning.",
      nomad: "A comfortable work base if you prefer a resort feel.",
    },
  },
  {
    id: "oz-sleep-4",
    city: "ouzoud",
    name: "Camping Auberge Zebra",
    type: "guesthouse",
    neighborhood: "near the Waterfalls",
    description: "A unique, exceptionally clean auberge-style campground a short walk from the falls, with modern family rooms, private bathrooms, infinity pool, and social fireplace.",
    pricePerNight: 85,
    lifestyle: "balanced",
    amenities: ["Infinity Swimming Pool", "Outdoor Fireplace Hearth", "Family-Friendly Restaurant", "Full-Day Security Patrol"],
    googleRating: 4.7,
    googleReviewCount: 89,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 20,
    bookingRating: 4.6,
    bookingReviewCount: 40,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 5,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Sit by the outdoor fireplace at night to meet travelers and share hiking tips.",
    vibeTags: ["Auberge", "Campground", "Social", "Infinity-Pool"],
    locationSummary: "Near Waterfalls - Clean Auberge Camp",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Camping+Auberge+Zebra+Ouzoud",
    address: "Near Ouzoud Waterfalls, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Camping Auberge Zebra blends clean campground spirit with family auberge comfort and a sociable evening fireplace.",
    neighborhoodOverview: "The waterfall-edge area gives quick foot access to the cascades and gorge paths, ideal for early morning hikes before tour groups arrive, but daytime foot traffic can be busy.",
    hiddenFeesNotice: "Taxes included; camping or activity extras may vary by booking.",
    pros: ["Very clean and social", "Infinity pool", "Family-friendly restaurant"],
    cons: ["Campground atmosphere is not for everyone", "Some noise from social areas"],
    trustScores: {
      cleanliness: 9.4,
      safety: 8.9,
      staff: 9.6,
      value: 9.0,
      comfort: 9.2,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public or on-site parking",
      contact: "+212 523 000 004",
    },
    roomFeatures: ["private-bathroom", "outdoor-fireplace", "pool-view", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Double Room",
              price: 85,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Family Room",
              price: 120,
              beds: "1 Queen + 2 Twin",
              size: "34m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ouzoud Waterfalls",
              distance: "800m",
              time: "10 min walk",
              icon: "waterfall",
            },
      {
              label: "Olive Grove Paths",
              distance: "300m",
              time: "4 min walk",
              icon: "hiking",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://aubergezebra.com",
    instagramHandle: "@aubergezebra",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and sociable base for solo travelers.",
      couples: "Friendly and relaxed for outdoorsy couples.",
      families: "Very good for families thanks to pool and rooms.",
      business: "Common areas are fine for trip planning and emails.",
      nomad: "A balanced social base for nomads hiking the falls.",
    },
  },
  {
    id: "oz-sleep-5",
    city: "ouzoud",
    name: "Palais d'Ouzoud",
    type: "hotel",
    neighborhood: "Ouzoud Center",
    description: "A stately castle-like hotel with views of canyon landscapes and olive groves, tadelakt arches, lush gardens, pool, and rooftop dining.",
    pricePerNight: 265,
    lifestyle: "premium",
    amenities: ["Traditional Arched Architecture", "Large Outdoor Pool", "Beautiful Botanical Gardens", "Panoramic Dining Rooftop"],
    googleRating: 4.6,
    googleReviewCount: 260,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 60,
    bookingRating: 4.5,
    bookingReviewCount: 100,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 20,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["couple", "family", "seniors", "friends"],
    tip: "Order the slow-cooked lamb tagine, prepared in a traditional wood-fired earth oven.",
    vibeTags: ["Palatial", "Garden", "Canyon-Views", "Rooftop-Dining"],
    locationSummary: "Ouzoud Center - Garden Palace",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Palais+d%27Ouzoud",
    address: "Ouzoud Center, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Palais d’Ouzoud was built as a grand garden hotel, using arches, tadelakt, and canyon views to create a palace-like waterfall retreat.",
    neighborhoodOverview: "Ouzoud Center is practical for restaurants, transport, shops, and walking access to the falls, with guesthouses and small hotels spread across the village lanes.",
    hiddenFeesNotice: "Taxes included; special dinners and transfers may be extra.",
    pros: ["Large pool and gardens", "Panoramic dining rooftop", "Good family comfort"],
    cons: ["Higher price point", "No elevator"],
    trustScores: {
      cleanliness: 9.2,
      safety: 9.6,
      staff: 9.4,
      value: 8.4,
      comfort: 9.0,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Secure on-site parking",
      contact: "+212 523 000 005",
    },
    roomFeatures: ["tadelakt-arches", "garden-view", "canyon-view", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Garden Room",
              price: 265,
              beds: "1 Queen",
              size: "30m²",
            },
      {
              name: "Palace Suite",
              price: 390,
              beds: "1 King",
              size: "50m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ouzoud Waterfalls",
              distance: "1km",
              time: "12 min walk",
              icon: "waterfall",
            },
      {
              label: "Village Restaurants",
              distance: "300m",
              time: "4 min walk",
              icon: "restaurant",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://palaisdouzoud.com",
    instagramHandle: "@palaisdouzoud",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and comfortable upscale base for solo travelers.",
      couples: "Rooftop dinner and gardens feel romantic.",
      families: "Good for families who want pool and space.",
      business: "Quiet areas are useful for light business tasks.",
      nomad: "A polished base for work breaks and waterfall walks.",
    },
  },
  {
    id: "oz-sleep-6",
    city: "ouzoud",
    name: "Borj Des Cascades & Spa",
    type: "hotel",
    neighborhood: "near the Waterfalls",
    description: "A magnificent 5-star luxury palace directly above the Oued Ouzoud gorges, with tiered gardens, infinity pool, and premium spa facilities.",
    pricePerNight: 260,
    lifestyle: "premium",
    amenities: ["Rooftop Sunset Platform", "Sizable Outdoor Infinity Pool", "Traditional Hammam & Spa", "Lush Tiered Gardens"],
    googleRating: 4.6,
    googleReviewCount: 480,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 100,
    bookingRating: 4.5,
    bookingReviewCount: 150,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 30,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "seniors"],
    tip: "Enjoy sunset drinks on the highest terrace as the valley turns orange.",
    vibeTags: ["Luxury", "Gorge-Views", "Spa", "Infinity-Pool"],
    locationSummary: "Above Ouzoud Gorge - Waterfall Luxury",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Borj+Des+Cascades+Spa+Ouzoud",
    address: "Above Oued Ouzoud Gorge, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Borj Des Cascades & Spa was designed as the high-comfort waterfall hotel, with tiered gardens and dramatic valley views.",
    neighborhoodOverview: "The waterfall-edge area gives quick foot access to the cascades and gorge paths, ideal for early morning hikes before tour groups arrive, but daytime foot traffic can be busy.",
    hiddenFeesNotice: "Taxes included; spa treatments may be extra.",
    pros: ["Best luxury facilities by the falls", "Infinity pool and spa", "Exceptional valley terraces"],
    cons: ["Premium price", "Can be busy during high season"],
    trustScores: {
      cleanliness: 9.2,
      safety: 9.6,
      staff: 9.4,
      value: 8.4,
      comfort: 9.0,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Secure on-site parking",
      contact: "+212 523 000 006",
    },
    roomFeatures: ["gorge-view", "infinity-pool-view", "spa-products", "ac", "heating", "elevator-access"],
    roomTypes: [
      {
              name: "Gorge View Room",
              price: 260,
              beds: "1 King",
              size: "32m²",
            },
      {
              name: "Panorama Suite",
              price: 420,
              beds: "1 King",
              size: "60m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ouzoud Waterfalls",
              distance: "300m",
              time: "4 min walk",
              icon: "waterfall",
            },
      {
              label: "Boat Viewpoint",
              distance: "600m",
              time: "8 min walk",
              icon: "viewpoint",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://borjdescascades.com",
    instagramHandle: "@borjdescascades",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and scenic luxury base for solo travelers.",
      couples: "Sunset terraces are deeply romantic.",
      families: "Good for families wanting comfort and easy waterfall access.",
      business: "Excellent for relaxed work with spa breaks.",
      nomad: "A premium waterfall workation base with views.",
    },
  },
  {
    id: "oz-sleep-7",
    city: "ouzoud",
    name: "La Kasbah d'Ouzoud",
    type: "guesthouse",
    neighborhood: "near the Waterfalls",
    description: "A classic mountain lodge built with traditional red stone and terracotta tiles, offering a warm Berber vibe, pool, and immediate hiking access.",
    pricePerNight: 98,
    lifestyle: "balanced",
    amenities: ["Traditional Red Stone Architecture", "Outdoor Swimming Pool", "Panoramic Garden Terrace", "Guided Hiking Assistance"],
    googleRating: 4.5,
    googleReviewCount: 965,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 200,
    bookingRating: 4.4,
    bookingReviewCount: 400,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 80,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Ask the front desk to coordinate a local guide for olive grove paths where you can feed the monkeys.",
    vibeTags: ["Berber", "Red-Stone", "Hiker-Friendly", "Pool"],
    locationSummary: "Near Waterfalls - Red Stone Kasbah",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=La+Kasbah+d%27Ouzoud",
    address: "Near Ouzoud Waterfalls, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "La Kasbah d’Ouzoud is one of the classic waterfall lodges, combining red-stone architecture, pool time, and guided hiking access.",
    neighborhoodOverview: "The waterfall-edge area gives quick foot access to the cascades and gorge paths, ideal for early morning hikes before tour groups arrive, but daytime foot traffic can be busy.",
    hiddenFeesNotice: "Taxes included; local guides may be extra.",
    pros: ["Immediate hiking access", "Classic Berber atmosphere", "Pool and garden terrace"],
    cons: ["No elevator", "Can be busy with hikers"],
    trustScores: {
      cleanliness: 9.0,
      safety: 8.9,
      staff: 9.2,
      value: 9.0,
      comfort: 8.8,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public or on-site parking",
      contact: "+212 523 000 007",
    },
    roomFeatures: ["red-stone-walls", "terracotta-tiles", "garden-terrace", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 98,
              beds: "1 Queen",
              size: "22m²",
            },
      {
              name: "Family Room",
              price: 135,
              beds: "1 Queen + 2 Twin",
              size: "34m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ouzoud Waterfalls",
              distance: "700m",
              time: "8 min walk",
              icon: "waterfall",
            },
      {
              label: "Olive Grove Monkey Paths",
              distance: "300m",
              time: "4 min walk",
              icon: "hiking",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://kasbahdouzoud.com",
    instagramHandle: "@lakasbahdouzoud",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and practical base for solo hikers.",
      couples: "Warm lodge atmosphere works well for couples.",
      families: "Good for families thanks to pool and guided walks.",
      business: "Quiet garden areas help with light work.",
      nomad: "A balanced waterfall base for active nomads.",
    },
  },
  {
    id: "oz-sleep-8",
    city: "ouzoud",
    name: "riad lala fatima",
    type: "riad",
    neighborhood: "Ouzoud Center",
    description: "A cozy authentic guesthouse with colorful Moroccan carpets, carved wood accents, sun-soaked balconies, and hill-and-olive-orchard views.",
    pricePerNight: 81,
    lifestyle: "balanced",
    amenities: ["Mountain-facing Balconies", "Shared Berber Lounge", "Traditional Clay Hammam", "Fresh Local Dining"],
    googleRating: 4.5,
    googleReviewCount: 180,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 40,
    bookingRating: 4.4,
    bookingReviewCount: 80,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 15,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "The host, Ismael, is incredibly welcoming; ask him for the best local path down into the gorge.",
    vibeTags: ["Cozy", "Authentic", "Balconies", "Local-Host"],
    locationSummary: "Ouzoud Center - Hill View Riad",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Lala+Fatima+Ouzoud",
    address: "Ouzoud Center, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad Lala Fatima offers a personal Ouzoud stay with carpets, carved wood, and host-led route advice for the gorge.",
    neighborhoodOverview: "Ouzoud Center is practical for restaurants, transport, shops, and walking access to the falls, with guesthouses and small hotels spread across the village lanes.",
    hiddenFeesNotice: "Taxes included; hammam and dinners may be extra.",
    pros: ["Welcoming host", "Mountain balconies", "Good local dining"],
    cons: ["No pool", "Simple guesthouse scale"],
    trustScores: {
      cleanliness: 9.0,
      safety: 8.9,
      staff: 9.2,
      value: 9.0,
      comfort: 8.8,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 523 000 008",
    },
    roomFeatures: ["mountain-facing-balcony", "berber-lounge", "carved-wood", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Balcony Room",
              price: 81,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Family Room",
              price: 115,
              beds: "1 Queen + 2 Twin",
              size: "32m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ouzoud Waterfalls",
              distance: "1km",
              time: "12 min walk",
              icon: "waterfall",
            },
      {
              label: "Gorge Path",
              distance: "600m",
              time: "8 min walk",
              icon: "hiking",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riadlalafatima.com",
    instagramHandle: "@riadlalafatima",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and welcoming base for solo travelers.",
      couples: "Cozy and authentic for couples.",
      families: "Good for families who want a local host and space.",
      business: "Quiet enough for light laptop work.",
      nomad: "A friendly village base for nomads exploring the gorge.",
    },
  },
  {
    id: "oz-sleep-9",
    city: "ouzoud",
    name: "Riad Dar Ouzoud",
    type: "riad",
    neighborhood: "near the Waterfalls",
    description: "A welcoming boutique riad on the main path to the waterfalls, with wood-painted doors, shared terraces, courtyard spaces, and garden views.",
    pricePerNight: 90,
    lifestyle: "balanced",
    amenities: ["Shared Sunset Terrace", "In-house Tagine Restaurant", "Airport Transfer Shuttle", "Cozy Central Courtyard"],
    googleRating: 4.5,
    googleReviewCount: 120,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 25,
    bookingRating: 4.4,
    bookingReviewCount: 50,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 10,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Step onto the main path after breakfast to explore the falls before day-trippers arrive.",
    vibeTags: ["Boutique", "Waterfall-Path", "Courtyard", "Terrace"],
    locationSummary: "Main Waterfall Path",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Dar+Ouzoud",
    address: "Near Ouzoud Waterfalls, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad Dar Ouzoud was built around its prized position on the falls path, giving guests early access before the crowds.",
    neighborhoodOverview: "The waterfall-edge area gives quick foot access to the cascades and gorge paths, ideal for early morning hikes before tour groups arrive, but daytime foot traffic can be busy.",
    hiddenFeesNotice: "Taxes included; airport transfer and guides cost extra.",
    pros: ["Excellent falls access", "Cozy courtyard", "Good tagine restaurant"],
    cons: ["Can get foot traffic nearby", "No pool"],
    trustScores: {
      cleanliness: 9.0,
      safety: 8.9,
      staff: 9.2,
      value: 9.0,
      comfort: 8.8,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public or on-site parking",
      contact: "+212 523 000 009",
    },
    roomFeatures: ["wood-painted-doors", "garden-view", "shared-terrace", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Garden Room",
              price: 90,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Family Room",
              price: 125,
              beds: "1 Queen + 2 Twin",
              size: "32m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ouzoud Waterfalls",
              distance: "300m",
              time: "4 min walk",
              icon: "waterfall",
            },
      {
              label: "Main Viewpoint",
              distance: "500m",
              time: "7 min walk",
              icon: "viewpoint",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riaddarouzoud.com",
    instagramHandle: "@riaddarouzoud",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and convenient stay for solo waterfall explorers.",
      couples: "Terraces and early walks are romantic for couples.",
      families: "Good for families wanting quick falls access.",
      business: "Terrace spaces work for light work before/after hikes.",
      nomad: "A practical waterfall base for nomads who wake early.",
    },
  },
  {
    id: "oz-sleep-10",
    city: "ouzoud",
    name: "Dar Diafa Kaltom",
    type: "guesthouse",
    neighborhood: "Ouzoud Center",
    description: "A charming family-run country house with large comfortable rooms and a pristine garden area, offering views of High Atlas foothills and the upper falls.",
    pricePerNight: 88,
    lifestyle: "balanced",
    amenities: ["Large Landscaped Garden", "Upper Falls Vantage Point", "Shared Mountain Lounge", "Secure On-Site Parking"],
    googleRating: 4.5,
    googleReviewCount: 108,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 20,
    bookingRating: 4.4,
    bookingReviewCount: 40,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 10,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Request the first-floor corner room for the best morning mist view over the upper falls.",
    vibeTags: ["Family-Run", "Garden", "Falls-View", "Parking"],
    locationSummary: "Ouzoud Center - Upper Falls View",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Dar+Diafa+Kaltom+Ouzoud",
    address: "Ouzoud Center, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Dar Diafa Kaltom is a family country house designed for comfortable rooms, garden calm, and a quiet vantage over the upper falls.",
    neighborhoodOverview: "Ouzoud Center is practical for restaurants, transport, shops, and walking access to the falls, with guesthouses and small hotels spread across the village lanes.",
    hiddenFeesNotice: "Taxes included; private parking included subject to availability.",
    pros: ["Large clean rooms", "Secure parking", "Upper falls vantage"],
    cons: ["No pool", "Simple countryside style"],
    trustScores: {
      cleanliness: 9.0,
      safety: 8.9,
      staff: 9.2,
      value: 9.0,
      comfort: 8.8,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Secure on-site parking",
      contact: "+212 523 000 010",
    },
    roomFeatures: ["upper-falls-view", "garden-view", "mountain-lounge", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Corner Room",
              price: 88,
              beds: "1 Queen",
              size: "22m²",
            },
      {
              name: "Family Room",
              price: 120,
              beds: "1 Queen + 2 Twin",
              size: "34m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Upper Falls Viewpoint",
              distance: "400m",
              time: "5 min walk",
              icon: "waterfall",
            },
      {
              label: "Ouzoud Center",
              distance: "500m",
              time: "6 min walk",
              icon: "village",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://dardiafakaltom.com",
    instagramHandle: "@dardiafakaltom",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and welcoming family-run stay for solo travelers.",
      couples: "Quiet garden views suit couples well.",
      families: "Excellent for families with car and luggage.",
      business: "Good WiFi and quiet lounge for planning.",
      nomad: "A practical base for nomads wanting parking and calm.",
    },
  },
  {
    id: "oz-sleep-11",
    city: "ouzoud",
    name: "Hotel France Ouzoud",
    type: "hotel",
    neighborhood: "Ouzoud Center",
    description: "An iconic large-scale town hotel in Ouzoud center with simple spacious rooms, central pool, and a functional basecamp feel for families and trekking groups.",
    pricePerNight: 90,
    lifestyle: "balanced",
    amenities: ["Large Central Pool", "Terraced Sun Deck", "Daily Buffet Breakfast", "Trek Gear Storage"],
    googleRating: 4.4,
    googleReviewCount: 1233,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 300,
    bookingRating: 4.3,
    bookingReviewCount: 500,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 100,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "large-groups"],
    tip: "Perfect with a rental vehicle, thanks to some of the most spacious secure parking in town.",
    vibeTags: ["Classic-Hotel", "Pool", "Groups", "Central"],
    locationSummary: "Ouzoud Center - Large Basecamp Hotel",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Hotel+France+Ouzoud",
    address: "Ouzoud Center, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Hotel France Ouzoud is a long-standing central hotel for trekking groups, road-trippers, and families needing pool, parking, and straightforward rooms.",
    neighborhoodOverview: "Ouzoud Center is practical for restaurants, transport, shops, and walking access to the falls, with guesthouses and small hotels spread across the village lanes.",
    hiddenFeesNotice: "Taxes included; buffet breakfast may vary by rate.",
    pros: ["Large pool and sun deck", "Great for groups", "Secure parking"],
    cons: ["Simple rooms", "Can feel busy in high season"],
    trustScores: {
      cleanliness: 8.8,
      safety: 9.6,
      staff: 9.0,
      value: 9.0,
      comfort: 8.6,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Secure on-site parking",
      contact: "+212 523 000 011",
    },
    roomFeatures: ["trek-gear-storage", "pool-view", "ac", "heating", "elevator-access", "shower-ensuite"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 90,
              beds: "1 Queen",
              size: "22m²",
            },
      {
              name: "Group/Family Room",
              price: 135,
              beds: "1 Queen + 2 Twin",
              size: "36m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ouzoud Waterfalls",
              distance: "900m",
              time: "10 min walk",
              icon: "waterfall",
            },
      {
              label: "Taxi Drop-off",
              distance: "300m",
              time: "4 min walk",
              icon: "transport",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://hotelfranceouzoud.com",
    instagramHandle: "@hotelfranceouzoud",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and practical central base for solo travelers.",
      couples: "Simple but convenient for couples.",
      families: "Good for families and groups needing pool and parking.",
      business: "Functional for work trips and logistics.",
      nomad: "A practical base for nomads with a car and gear.",
    },
  },
  {
    id: "oz-sleep-12",
    city: "ouzoud",
    name: "hotel DIJON ouzoud",
    type: "hotel",
    neighborhood: "Ouzoud Center",
    description: "A practical, highly rated 3-star hotel with simple clean rooms and pleasant dining terrace near the village entrance.",
    pricePerNight: 48,
    lifestyle: "lean",
    amenities: ["Furnished Dining Terrace", "In-house Restaurant", "Complimentary Wi-Fi", "Daily Simple Breakfast"],
    googleRating: 4.4,
    googleReviewCount: 150,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 30,
    bookingRating: 4.2,
    bookingReviewCount: 50,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 10,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "friends", "solo"],
    tip: "Perfect if traveling by bus, as it sits close to the main local taxi drop-off point.",
    vibeTags: ["Budget", "Practical", "Taxi-Access", "Terrace"],
    locationSummary: "Ouzoud Center - Village Entrance",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Hotel+Dijon+Ouzoud",
    address: "Ouzoud Center, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Hotel Dijon Ouzoud focuses on clean practical lodging for budget travelers arriving by taxi or bus to visit the cascades.",
    neighborhoodOverview: "Ouzoud Center is practical for restaurants, transport, shops, and walking access to the falls, with guesthouses and small hotels spread across the village lanes.",
    hiddenFeesNotice: "Taxes included; meals may vary by rate.",
    pros: ["Good value", "Close to transport drop-off", "Clean simple rooms"],
    cons: ["No pool", "Basic comfort level"],
    trustScores: {
      cleanliness: 8.8,
      safety: 8.9,
      staff: 9.0,
      value: 9.4,
      comfort: 8.6,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 523 000 012",
    },
    roomFeatures: ["dining-terrace", "ac", "heating", "elevator-access", "shower-ensuite"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 48,
              beds: "1 Double",
              size: "18m²",
            },
      {
              name: "Twin Room",
              price: 55,
              beds: "2 Twin",
              size: "18m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Taxi Drop-off",
              distance: "100m",
              time: "2 min walk",
              icon: "transport",
            },
      {
              label: "Ouzoud Waterfalls",
              distance: "1km",
              time: "12 min walk",
              icon: "waterfall",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://hoteldijonouzoud.com",
    instagramHandle: "@hoteldijonouzoud",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and budget-friendly base for solo travelers.",
      couples: "Simple and practical for couples.",
      families: "Best for low-maintenance travelers and older kids.",
      business: "Good WiFi for basic work and planning.",
      nomad: "A no-frills base for nomads in transit.",
    },
  },
  {
    id: "oz-sleep-13",
    city: "ouzoud",
    name: "Hôtel Ajil Cascades D'ouzoud",
    type: "hotel",
    neighborhood: "Ouzoud Center",
    description: "A popular hotel with lush green lawns, a gorgeous outdoor pool, Moroccan decor, and an inviting courtyard restaurant.",
    pricePerNight: 82,
    lifestyle: "balanced",
    amenities: ["Outdoor Swimming Pool", "Lush Green Grass Lawns", "Traditional Moroccan Decor", "Shared Kitchen Access"],
    googleRating: 4.3,
    googleReviewCount: 320,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 60,
    bookingRating: 4.2,
    bookingReviewCount: 100,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 20,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Enjoy traditional Moroccan harira soup in the garden restaurant on cool mountain evenings.",
    vibeTags: ["Garden-Lawns", "Pool", "Family-Friendly", "Moroccan-Decor"],
    locationSummary: "Ouzoud Center - Garden Pool Hotel",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Hotel+Ajil+Cascades+d%27Ouzoud",
    address: "Ouzoud Center, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Hôtel Ajil Cascades d’Ouzoud offers a family-friendly pool-and-lawn setting for visitors wanting easy village access and Moroccan decor.",
    neighborhoodOverview: "Ouzoud Center is practical for restaurants, transport, shops, and walking access to the falls, with guesthouses and small hotels spread across the village lanes.",
    hiddenFeesNotice: "Taxes included; shared kitchen availability may vary.",
    pros: ["Pool and lawns", "Good family atmosphere", "Garden restaurant"],
    cons: ["No elevator", "Can be busy during local holidays"],
    trustScores: {
      cleanliness: 8.6,
      safety: 8.9,
      staff: 8.8,
      value: 9.0,
      comfort: 8.4,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 523 000 013",
    },
    roomFeatures: ["green-lawns", "pool-view", "shared-kitchen-access", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 82,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Family Room",
              price: 115,
              beds: "1 Queen + 2 Twin",
              size: "32m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ouzoud Waterfalls",
              distance: "1km",
              time: "12 min walk",
              icon: "waterfall",
            },
      {
              label: "Village Center",
              distance: "300m",
              time: "4 min walk",
              icon: "village",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://hotelajilouzoud.com",
    instagramHandle: "@hotelajilouzoud",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and relaxed central base for solo travelers.",
      couples: "Garden restaurant makes it pleasant for couples.",
      families: "Great for families who want lawns and a pool.",
      business: "Shared spaces are fine for light work.",
      nomad: "A balanced village base for nomads wanting pool breaks.",
    },
  },
  {
    id: "oz-sleep-14",
    city: "ouzoud",
    name: "Kasba Oum Hani d'Ouzoud",
    type: "guesthouse",
    neighborhood: "Ouzoud Center",
    description: "A welcoming guesthouse with comfortable rooms and secure private parking, set in a quiet corner of the village for a peaceful family-friendly stay.",
    pricePerNight: 80,
    lifestyle: "balanced",
    amenities: ["Mountain View Balconies", "Secure Private Parking", "Family-Friendly Suites", "Daily Moroccan Breakfast"],
    googleRating: 4.3,
    googleReviewCount: 140,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 30,
    bookingRating: 4.2,
    bookingReviewCount: 50,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 10,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Ask for an upper-level room for the clearest sunrise view over the limestone canyon.",
    vibeTags: ["Quiet", "Family-Friendly", "Balconies", "Parking"],
    locationSummary: "Ouzoud Center - Quiet Village Corner",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Kasba+Oum+Hani+Ouzoud",
    address: "Ouzoud Center, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Kasba Oum Hani d’Ouzoud was created as a calm family guesthouse with practical parking and balcony views away from the busiest paths.",
    neighborhoodOverview: "Ouzoud Center is practical for restaurants, transport, shops, and walking access to the falls, with guesthouses and small hotels spread across the village lanes.",
    hiddenFeesNotice: "Taxes included; private excursions may be extra.",
    pros: ["Secure private parking", "Quiet village setting", "Family suites"],
    cons: ["No pool", "Simple service level"],
    trustScores: {
      cleanliness: 8.6,
      safety: 8.9,
      staff: 8.8,
      value: 9.0,
      comfort: 8.4,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Secure private parking",
      contact: "+212 523 000 014",
    },
    roomFeatures: ["mountain-view-balcony", "family-suite", "ac", "heating", "rooftop-access", "shower-ensuite"],
    roomTypes: [
      {
              name: "Balcony Room",
              price: 80,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Family Suite",
              price: 115,
              beds: "1 Queen + 2 Twin",
              size: "34m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ouzoud Waterfalls",
              distance: "1.2km",
              time: "15 min walk",
              icon: "waterfall",
            },
      {
              label: "Limestone Canyon View",
              distance: "500m",
              time: "6 min walk",
              icon: "viewpoint",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://kasbaoumhani.com",
    instagramHandle: "@kasbaoumhani",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and quiet option for solo travelers with a car.",
      couples: "Peaceful balcony views work well for couples.",
      families: "Good for families thanks to secure parking and suites.",
      business: "Quiet enough for light work and planning.",
      nomad: "A practical base for nomads wanting parking and calm.",
    },
  },
  {
    id: "oz-sleep-15",
    city: "ouzoud",
    name: "Hôtel Chellal d'Ouzoud",
    type: "hotel",
    neighborhood: "near the Waterfalls",
    description: "Set on leafy grounds a short three-minute stroll from the cascades, with rustic Berber decor, private garden lounges, and a relaxed mountaineering vibe.",
    pricePerNight: 85,
    lifestyle: "balanced",
    amenities: ["Lush Garden Lounge", "Waterfall Path Proximity", "Colorful Berber Decor", "Tour/Trek Guide Booking"],
    googleRating: 4.2,
    googleReviewCount: 996,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 200,
    bookingRating: 4.1,
    bookingReviewCount: 300,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 50,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "The hotel sits right on the path; walk down to the river banks at dusk after tour buses depart.",
    vibeTags: ["Rustic", "Waterfall-Path", "Berber-Decor", "Garden"],
    locationSummary: "Near Waterfalls - 3 min Walk",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Hotel+Chellal+d%27Ouzoud",
    address: "Near Ouzoud Waterfalls, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Hôtel Chellal d’Ouzoud is a classic waterfall-path hotel, known for leafy gardens, rustic decor, and immediate access to the cascades.",
    neighborhoodOverview: "The waterfall-edge area gives quick foot access to the cascades and gorge paths, ideal for early morning hikes before tour groups arrive, but daytime foot traffic can be busy.",
    hiddenFeesNotice: "Taxes included; guides and tours may be extra.",
    pros: ["Very close to waterfalls", "Leafy garden lounge", "Helpful guide booking"],
    cons: ["No pool", "Can be busy due to location"],
    trustScores: {
      cleanliness: 8.4,
      safety: 8.9,
      staff: 8.6,
      value: 9.0,
      comfort: 8.2,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public or on-site parking",
      contact: "+212 523 000 015",
    },
    roomFeatures: ["berber-decor", "garden-lounge", "waterfall-path-access", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Garden Room",
              price: 85,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Family Room",
              price: 120,
              beds: "1 Queen + 2 Twin",
              size: "32m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ouzoud Waterfalls",
              distance: "250m",
              time: "3 min walk",
              icon: "waterfall",
            },
      {
              label: "River Banks",
              distance: "500m",
              time: "7 min walk",
              icon: "river",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://hotelchellalouzoud.com",
    instagramHandle: "@hotelchellalouzoud",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and convenient base for solo waterfall hikers.",
      couples: "Garden lounges and dusk walks are pleasant for couples.",
      families: "Good for families who want fast waterfall access.",
      business: "Basic but usable for emails and planning.",
      nomad: "A practical waterfall base for nomads who hike early.",
    },
  },
  {
    id: "oz-sleep-16",
    city: "ouzoud",
    name: "Ouzoud le Panorama",
    type: "guesthouse",
    neighborhood: "Ouzoud Center",
    description: "A simple budget-friendly mountain guesthouse with panoramic views of the red sandstone canyon, warm atmosphere, and garden patio.",
    pricePerNight: 45,
    lifestyle: "lean",
    amenities: ["Panoramic Canyon Views", "Cozy Garden Patio", "Mountain-facing Balconies", "Traditional Berber Breakfast"],
    googleRating: 4.2,
    googleReviewCount: 228,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 40,
    bookingRating: 4.1,
    bookingReviewCount: 80,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 20,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "friends", "solo"],
    tip: "Sit on the terrace at sunset as the red sandstone cliffs glow copper.",
    vibeTags: ["Budget", "Canyon-Views", "Terrace", "Authentic"],
    locationSummary: "Ouzoud Center - Canyon Panorama",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Ouzoud+le+Panorama",
    address: "Ouzoud Center, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Ouzoud le Panorama is a simple guesthouse centered on terrace views, Berber breakfasts, and budget access to the canyon.",
    neighborhoodOverview: "Ouzoud Center is practical for restaurants, transport, shops, and walking access to the falls, with guesthouses and small hotels spread across the village lanes.",
    hiddenFeesNotice: "Taxes included; dinner and excursions may be extra.",
    pros: ["Excellent canyon views", "Affordable price", "Warm atmosphere"],
    cons: ["No AC", "Simple facilities"],
    trustScores: {
      cleanliness: 8.4,
      safety: 8.9,
      staff: 8.6,
      value: 9.4,
      comfort: 8.2,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 523 000 016",
    },
    roomFeatures: ["canyon-view", "garden-patio", "mountain-balcony", "heating", "rooftop-access", "shower-ensuite"],
    roomTypes: [
      {
              name: "Panorama Room",
              price: 45,
              beds: "1 Double",
              size: "16m²",
            },
      {
              name: "Triple Room",
              price: 65,
              beds: "1 Double + 1 Single",
              size: "22m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Canyon Viewpoint",
              distance: "300m",
              time: "4 min walk",
              icon: "viewpoint",
            },
      {
              label: "Ouzoud Waterfalls",
              distance: "1km",
              time: "12 min walk",
              icon: "waterfall",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://ouzoudlepanorama.com",
    instagramHandle: "@ouzoudlepanorama",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and affordable base for solo travelers.",
      couples: "Terrace sunsets are romantic in a simple way.",
      families: "Best for older children and budget families.",
      business: "Good for basic work with views.",
      nomad: "A low-cost scenic base for nomads.",
    },
  },
  {
    id: "oz-sleep-17",
    city: "ouzoud",
    name: "Riad Heermans",
    type: "riad",
    neighborhood: "Ouzoud Center",
    description: "A quaint budget-friendly riad with cozy shared spaces, Moroccan textiles, and a quiet plant-filled central patio away from busy trails.",
    pricePerNight: 40,
    lifestyle: "lean",
    amenities: ["Quiet Courtyard Patio", "Shared Mountain Lounge", "Traditional Clay Hammam", "Guided Waterfall Tours"],
    googleRating: 4.2,
    googleReviewCount: 110,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 20,
    bookingRating: 4.1,
    bookingReviewCount: 40,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 10,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "friends", "solo"],
    tip: "Request extra heavy blankets in winter, as nights in the Atlas foothills get cool.",
    vibeTags: ["Budget", "Quiet-Patio", "Traditional", "Waterfall-Tours"],
    locationSummary: "Ouzoud Center - Quiet Patio Riad",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Heermans+Ouzoud",
    address: "Ouzoud Center, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad Heermans offers an affordable riad-style pause with textiles, patio plants, hammam, and guided waterfall tours.",
    neighborhoodOverview: "Ouzoud Center is practical for restaurants, transport, shops, and walking access to the falls, with guesthouses and small hotels spread across the village lanes.",
    hiddenFeesNotice: "Taxes included; hammam and guided tours may be extra.",
    pros: ["Quiet courtyard", "Budget-friendly", "Guided waterfall tours"],
    cons: ["No pool", "Simple comfort level"],
    trustScores: {
      cleanliness: 8.4,
      safety: 8.9,
      staff: 8.6,
      value: 9.4,
      comfort: 8.2,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 523 000 017",
    },
    roomFeatures: ["courtyard-patio", "moroccan-textiles", "mountain-lounge", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Budget Room",
              price: 40,
              beds: "1 Double",
              size: "16m²",
            },
      {
              name: "Twin Room",
              price: 50,
              beds: "2 Twin",
              size: "18m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ouzoud Waterfalls",
              distance: "1km",
              time: "12 min walk",
              icon: "waterfall",
            },
      {
              label: "Village Center",
              distance: "300m",
              time: "4 min walk",
              icon: "village",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riadheermans.com",
    instagramHandle: "@riadheermans",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and quiet budget base for solo travelers.",
      couples: "Simple and peaceful for couples.",
      families: "Best for budget travelers and older kids.",
      business: "Quiet patio can work for light remote tasks.",
      nomad: "A basic but calm base for nomads on a budget.",
    },
  },
  {
    id: "oz-sleep-18",
    city: "ouzoud",
    name: "Maison Touria",
    type: "guesthouse",
    neighborhood: "Ouzoud Center",
    description: "A simple, welcoming family home on the quiet borders of Ouzoud village with comfortable rooms and a common lounge for home-cooked Berber tagines.",
    pricePerNight: 42,
    lifestyle: "lean",
    amenities: ["Common Berber Lounge", "Sunset Rooftop Deck", "Airport Transfer Shuttle", "Moroccan Mint Tea Service"],
    googleRating: 4.1,
    googleReviewCount: 130,
    tripadvisorRating: 3.5,
    tripadvisorReviewCount: 20,
    bookingRating: 4.0,
    bookingReviewCount: 40,
    hotelguruRating: 4.1,
    hotelguruReviewCount: 10,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "The hosts are helpful; ask for the best local paths for private unguided walks.",
    vibeTags: ["Family-Home", "Budget", "Berber-Lounge", "Quiet"],
    locationSummary: "Ouzoud Village Edge - Family Guesthouse",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Maison+Touria+Ouzoud",
    address: "Ouzoud Center, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Maison Touria is a family home-style guesthouse offering simple comfort, Berber meals, and helpful walking advice on the village edge.",
    neighborhoodOverview: "Ouzoud Center is practical for restaurants, transport, shops, and walking access to the falls, with guesthouses and small hotels spread across the village lanes.",
    hiddenFeesNotice: "Taxes included; transfers and dinners may be extra.",
    pros: ["Warm family hospitality", "Good homemade tagines", "Quiet village-edge location"],
    cons: ["No pool", "Basic facilities"],
    trustScores: {
      cleanliness: 8.2,
      safety: 8.9,
      staff: 8.4,
      value: 9.4,
      comfort: 8.0,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 523 000 018",
    },
    roomFeatures: ["berber-lounge", "sunset-rooftop", "traditional-decor", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Simple Double",
              price: 42,
              beds: "1 Double",
              size: "16m²",
            },
      {
              name: "Family Room",
              price: 60,
              beds: "1 Double + 1 Single",
              size: "22m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ouzoud Center",
              distance: "500m",
              time: "6 min walk",
              icon: "village",
            },
      {
              label: "Ouzoud Waterfalls",
              distance: "1.2km",
              time: "15 min walk",
              icon: "waterfall",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://maisontouria.com",
    instagramHandle: "@maisontouria",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and very affordable family-style stay for solo travelers.",
      couples: "Simple and welcoming for couples.",
      families: "Good for families who like home-style guesthouses.",
      business: "Basic but quiet for route planning.",
      nomad: "A low-cost base for nomads who value local guidance.",
    },
  },
  {
    id: "oz-sleep-19",
    city: "ouzoud",
    name: "Maison d'hôte la source",
    type: "guesthouse",
    neighborhood: "near the Waterfalls",
    description: "A rustic mountain lodge near the refreshing springs that feed Ouzoud waterfalls, offering an authentic unplugged retreat for backpackers and nature-loving solo travelers.",
    pricePerNight: 38,
    lifestyle: "lean",
    amenities: ["Immediate Spring Access", "Scenic Canyon Rooftop", "Shared Mountain Kitchen", "Excursion Tour Booking"],
    googleRating: 4.1,
    googleReviewCount: 95,
    tripadvisorRating: 3.5,
    tripadvisorReviewCount: 15,
    bookingRating: 4.0,
    bookingReviewCount: 30,
    hotelguruRating: 4.1,
    hotelguruReviewCount: 5,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ["solo", "friends", "friends", "solo"],
    tip: "Walk to the waterfall source at sunrise for birdsong and roaring water before daily crowds arrive.",
    vibeTags: ["Rustic", "Spring-Access", "Backpacker", "Unplugged"],
    locationSummary: "Near Waterfalls - Spring Source Lodge",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Maison+d%27hote+la+source+Ouzoud",
    address: "Near Ouzoud Waterfalls, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Maison d’hôte la source was created as a rustic spring-side base for hikers who want simple lodging and immediate access to the water source.",
    neighborhoodOverview: "The waterfall-edge area gives quick foot access to the cascades and gorge paths, ideal for early morning hikes before tour groups arrive, but daytime foot traffic can be busy.",
    hiddenFeesNotice: "Taxes included; excursions may be extra.",
    pros: ["Immediate spring access", "Very budget-friendly", "Good for nature lovers"],
    cons: ["Rustic and basic", "Limited modern comforts"],
    trustScores: {
      cleanliness: 8.2,
      safety: 8.9,
      staff: 8.4,
      value: 9.4,
      comfort: 8.0,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public or on-site parking",
      contact: "+212 523 000 019",
    },
    roomFeatures: ["spring-access", "canyon-rooftop", "shared-kitchen", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Rustic Double",
              price: 38,
              beds: "1 Double",
              size: "14m²",
            },
      {
              name: "Shared Hiker Room",
              price: 25,
              beds: "Single beds",
              size: "18m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Waterfall Source",
              distance: "200m",
              time: "3 min walk",
              icon: "spring",
            },
      {
              label: "Ouzoud Waterfalls",
              distance: "500m",
              time: "7 min walk",
              icon: "waterfall",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://maisondhotelasaourceouzoud.com",
    instagramHandle: "@maisondhotelasource",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe, basic base for solo nature travelers.",
      couples: "Best for adventurous couples who like rustic places.",
      families: "Not ideal for comfort-focused families.",
      business: "Not suitable for business travel.",
      nomad: "A true unplugged base for budget nomads and hikers.",
    },
  },
  {
    id: "oz-sleep-20",
    city: "ouzoud",
    name: "Dar Marwa",
    type: "guesthouse",
    neighborhood: "Ouzoud Center",
    description: "A cozy, welcoming guesthouse known for immaculate cleanliness and exceptional hospitality, with a shared mountain-view lounge and quiet terrace.",
    pricePerNight: 82,
    lifestyle: "balanced",
    amenities: ["Immaculate Mountain Lounge", "Rooftop Sunset Terrace", "Traditional Garden Space", "Halal Berber Breakfast"],
    googleRating: 4.0,
    googleReviewCount: 379,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 80,
    bookingRating: 4.1,
    bookingReviewCount: 150,
    hotelguruRating: 4.0,
    hotelguruReviewCount: 30,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Enjoy the freshly made local breads at breakfast; they are baked by the host family daily.",
    vibeTags: ["Clean", "Hospitality", "Mountain-Lounge", "Terrace"],
    locationSummary: "Ouzoud Center - Clean Guesthouse",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Dar+Marwa+Ouzoud",
    address: "Ouzoud Center, Ouzoud 22576, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Dar Marwa focuses on immaculate cleanliness, family hospitality, and simple terrace relaxation after waterfall walks.",
    neighborhoodOverview: "Ouzoud Center is practical for restaurants, transport, shops, and walking access to the falls, with guesthouses and small hotels spread across the village lanes.",
    hiddenFeesNotice: "Taxes included; dinner and transfers may be extra.",
    pros: ["Very clean", "Warm host hospitality", "Good terrace and lounge"],
    cons: ["No pool", "Lower frills than boutique hotels"],
    trustScores: {
      cleanliness: 8.0,
      safety: 8.9,
      staff: 8.2,
      value: 9.0,
      comfort: 7.8,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 523 000 020",
    },
    roomFeatures: ["mountain-view-lounge", "rooftop-terrace", "garden-space", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Double Room",
              price: 82,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Family Room",
              price: 115,
              beds: "1 Queen + 2 Twin",
              size: "32m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ouzoud Waterfalls",
              distance: "1km",
              time: "12 min walk",
              icon: "waterfall",
            },
      {
              label: "Village Center",
              distance: "300m",
              time: "4 min walk",
              icon: "village",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://darmarwaouzoud.com",
    instagramHandle: "@darmarwaouzoud",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and clean guesthouse for solo travelers.",
      couples: "Quiet terrace and warm breakfast suit couples.",
      families: "Good for families wanting cleanliness and hospitality.",
      business: "Lounge spaces are fine for light work.",
      nomad: "A calm, clean base for nomads staying near the falls.",
    },
  }
]
