import type { SleepListing } from '../types'

/**
 * SLEEP LISTING DATA TEMPLATE (Copy this for your search agent)
 * -------------------------------------------------------------
 * {
 *   "id": "city-sleep-XX",
 *   "name": "",
 *   "type": "riad | hotel | villa | hostel | apartment | guesthouse",
 *   "neighborhood": "",
 *   "city": "[city]",
 *   "description": "",
 *   "pricePerNight": 0,
 *   "lifestyle": "lean | balanced | premium",
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2', 'url3']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source (replaces single rating/reviewCount)
 *   // ═══════════════════════════════════════════════════
 *   // Search for real ratings from Google, TripAdvisor, Booking.com, and HotelGuru.
 *   // If you cannot find a rating for a specific source, set it to the same value as
 *   // the closest available one so average calculations don't break.
 *
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *   bookingRating: [4.x],
 *   bookingReviewCount: [number],
 *   hotelguruRating: [4.x],
 *   hotelguruReviewCount: [number],
 *
 *   // ═══════════════════════════════════════════════════
 *   // BOOLEAN AMENITIES
 *   // ═══════════════════════════════════════════════════
 *
 *   hasPool: true | false,
 *   hasBreakfast: true | false,
 *   hasAC: true | false,
 *   hasHeating: true | false,
 *   hasRooftop: true | false,
 *   hasEnsuite: true | false,
 *   hasRestaurant: true | false,
 *   hasBar: true | false,
 *   hasGym: true | false,
 *   hasElevator: true | false,
 *   hasLaundryService: true | false,
 *   hasRoomService: true | false,
 *   petFriendly: true | false,
 *   isWheelchairAccessible: true | false,
 *   taxesIncluded: true | false,
 *   freeCancellation: true | false,
 *   kidsStayFree: true | false,
 *
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearMosque: true | false,
 *   safetyLevel: 1 | 2 | 3 | 4 | 5,
 *
 *   // ═══════════════════════════════════════════════════
 *   // TRUST SCORES
 *   // ═══════════════════════════════════════════════════
 *
 *   trustScores: {
 *     cleanliness: [1-10],
 *     safety: [1-10],
 *     staff: [1-10],
 *     value: [1-10],
 *     comfort: [1-10],
 *     location: [1-10]
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   amenities: ['wifi', 'pool', 'ac', 'breakfast', 'spa', 'restaurant', 'gym', 'kitchenette', 'parking', 'bar', 'laundry', 'elevator', 'room-service'],
 *   tip: '[Short insider tip]',
 *   vibeTags: ['Authentic', 'Quiet', 'Modern'],
 *   locationSummary: 'Beachfront | City Center | Medina | Airport Area | Residential | Tourist Zone',
 *   availabilityText: 'Available tonight | Only 2 rooms left | Available on selected dates',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   address: '[Full street address, City, Postal Code, Morocco]',
 *
 *   paymentMethods: ['card', 'cash'],
 *   languagesSpoken: ['Arabic', 'French', 'English', 'Spanish', 'German'],
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   customStory: 'Brief history, owner background, or architecture notes...',
 *   neighborhoodOverview: 'Description of the local atmosphere, safety, and vibe...',
 *   hiddenFeesNotice: 'City tax of XX MAD per person/night not included...',
 *   pros: ['Pro 1', 'Pro 2'],
 *   cons: ['Con 1'],
 *
 *   // ═══════════════════════════════════════════════════
 *   // LOGISTICS
 *   // ═══════════════════════════════════════════════════
 *
 *   logistics: {
 *     checkIn: '14:00 - 22:00',
 *     checkOut: 'Before 11:00',
 *     luggageStorage: 'Free | Paid | None',
 *     parking: 'Free on-site | Nearby public | Valet',
 *     contact: '+212 XXXXXXXXX'
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *   // ROOM FEATURES & TYPES
 *   // ═══════════════════════════════════════════════════
 *
 *   roomFeatures: ['soundproof', 'workspace', 'private-balcony', 'ac', 'heating', 'balcony', 'shower-ensuite', 'sea-view', 'garden-view', 'pool-view'],
 *   roomTypes: [
 *     {
 *       name: 'Double Room',
 *       price: 500,
 *       beds: '1 Queen',
 *       size: '20m2',
 *     }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *   // NEIGHBORHOOD DISTANCES
 *   // ═══════════════════════════════════════════════════
 *
 *   neighborhoodDistances: [
 *     { label: 'Beach', distance: '500m', time: '5 min walk', icon: 'beach' }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   cancellationPolicy: 'Free cancellation up to 24h before check-in | Flexible | Non-refundable',
 *   childPolicy: 'Children welcome | Free under 6 | Extra bed 200 MAD',
 *   officialWebsite: 'https://...',
 *   instagramHandle: '@...',
 *
 *   // googlePlaceId: "PLACE_ID_HERE",
 *
 *   // ═══════════════════════════════════════════════════
 *   // REVIEW HIGHLIGHTS
 *   // ═══════════════════════════════════════════════════
 *
 *   reviewHighlights: {
 *     solo: 'Great insight for solo...',
 *     couples: 'Great for couples...',
 *     families: 'Kid-friendly details...',
 *     business: 'Wi-Fi test details...',
 *     nomad: 'Remote work specific insight...'
 *   }
 * }
 */

export const rabatSleep: SleepListing[] = [
  {
    id: "r-sleep-1",
    city: "rabat",
    name: "The Ritz-Carlton Rabat, Dar Es Salam",
    type: "hotel",
    neighborhood: "Souissi",
    description: "A majestic retreat surrounded by ancient oak forests and the pristine greens of Royal Golf Dar Es Salam, blending Andalusian grandeur with modern Art Deco sophistication.",
    pricePerNight: 540,
    lifestyle: "premium",
    amenities: ["Luxury Spa", "Indoor & Outdoor Pools", "Royal Golf Course Access", "Fine Dining Restaurants", "Butler Service", "Wifi", "AC"],
    googleRating: 4.8,
    googleReviewCount: 650,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 650,
    bookingRating: 4.8,
    bookingReviewCount: 650,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 650,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "countryside",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "seniors", "business-friendly"],
    tip: "Book a garden-facing terrace suite to enjoy tranquil morning bird calls from the adjacent forest.",
    vibeTags: ["Palatial", "Secluded", "Golf-Luxe", "Sophisticated"],
    locationSummary: "Dar Es Salam Royal Golf Estate",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=The+Ritz-Carlton+Rabat+Dar+Es+Salam",
    address: "Royal Golf Dar Es Salam, Souissi, Rabat 10100, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Built to complement the prestigious Dar Es Salam estate, this hotel bridges Rabat’s wild oak forests and modern diplomatic life.",
    neighborhoodOverview: "Souissi is Rabat’s elite diplomatic and residential district, known for embassies, villas, secure leafy streets, golf access, and a car-oriented luxury lifestyle.",
    hiddenFeesNotice: "City tax of 39.60 MAD per person/night not included.",
    pros: ["Access to world-class golf", "Unmatched privacy and security", "Beautiful forest surroundings"],
    cons: ["Away from city center", "Most expensive stay in Rabat"],
    trustScores: {
      cleanliness: 9.9,
      safety: 9.9,
      staff: 9.8,
      value: 8.2,
      comfort: 9.9,
      location: 9.1,
    },
    logistics: {
      checkIn: "15:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free secure parking",
      contact: "+212 537 202 020",
    },
    roomFeatures: ["soundproof", "private-balcony", "marble-bathroom", "ac", "heating", "garden-view"],
    roomTypes: [
      {
              name: "Deluxe Room",
              price: 540,
              beds: "1 King",
              size: "50m²",
            },
      {
              name: "Executive Suite",
              price: 850,
              beds: "1 King",
              size: "85m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Royal Golf Dar Es Salam",
              distance: "100m",
              time: "2 min walk",
              icon: "nature",
            },
      {
              label: "Hassan Tower",
              distance: "12km",
              time: "20 min drive",
              icon: "monument",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - family rooms and outdoor space available",
    officialWebsite: "https://www.ritzcarlton.com/en/hotels/rbarz-the-ritz-carlton-rabat-dar-es-salam/overview/",
    instagramHandle: "@ritzcarltonrabat",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and regal sanctuary for the high-end solo traveler.",
      couples: "The forest walks and spa make it incredibly romantic.",
      families: "Wonderful grounds for children to explore safely.",
      business: "Discreet and prestigious for top-level diplomacy.",
      nomad: "Fast WiFi in the lobby, with quieter work pockets around the gardens.",
    },
    coordinates: {
      lat: 33.920364,
      lng: -6.840915
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "r-sleep-2",
    city: "rabat",
    name: "The View Rabat",
    type: "hotel",
    neighborhood: "Hay Riad",
    description: "A sleek high-rise hotel in the prestigious Hay Riad business district, with avant-garde design and panoramic windows overlooking the capital.",
    pricePerNight: 250,
    lifestyle: "premium",
    amenities: ["Sky Lounge", "Panoramic Fitness Center", "Indoor Heated Pool", "Luxury Spa", "Fine Dining", "Wifi", "AC"],
    googleRating: 4.8,
    googleReviewCount: 950,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 950,
    bookingRating: 4.8,
    bookingReviewCount: 950,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 950,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "friends", "business-friendly"],
    tip: "Request a high-floor room for spectacular night views of city lights and the distant Atlantic.",
    vibeTags: ["Urban-Chic", "Panoramic", "Modern", "Sleek"],
    locationSummary: "Souissi / Hassan Modern District",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=The+View+Rabat",
    address: "Avenue Annakhil, Hay Riad, Rabat 10100, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Designed as a modern beacon of Rabat’s business skyline, The View looks toward the capital’s future.",
    neighborhoodOverview: "Hay Riad is Rabat’s modern business district, with corporate headquarters, Mahaj Riad shopping, wide boulevards, cafés, and strong taxi access.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Best panoramic views in Rabat", "State-of-the-art wellness facilities", "Prime for business travelers"],
    cons: ["Away from historic medina", "More business-like than cultural"],
    trustScores: {
      cleanliness: 9.8,
      safety: 9.9,
      staff: 9.5,
      value: 8.6,
      comfort: 9.7,
      location: 9.4,
    },
    logistics: {
      checkIn: "15:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Secure private parking",
      contact: "+212 537 569 569",
    },
    roomFeatures: ["floor-to-ceiling-windows", "smart-lighting", "rain-shower", "ac", "heating", "workspace"],
    roomTypes: [
      {
              name: "Superior Room",
              price: 250,
              beds: "1 Queen",
              size: "32m²",
            },
      {
              name: "Sky Suite",
              price: 480,
              beds: "1 King",
              size: "65m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Mahaj Riad",
              distance: "400m",
              time: "5 min walk",
              icon: "shopping",
            },
      {
              label: "Hassan Tower",
              distance: "10km",
              time: "15 min drive",
              icon: "monument",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome, though best suited for business travelers and couples",
    officialWebsite: "https://theviewhotels.com/rabat/",
    instagramHandle: "@theviewrabat",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and modern hub for solo travelers in the city.",
      couples: "The sky lounge at night is very romantic.",
      families: "Modern and spacious, though more popular with business travelers.",
      business: "The best business facilities and location in the capital.",
      nomad: "Fastest WiFi in Rabat and strong lounge work vibes.",
    },
    coordinates: {
      lat: 33.955018,
      lng: -6.867267
    },
    tags: []
  },
  {
    id: "r-sleep-3",
    city: "rabat",
    name: "Euphoriad",
    type: "riad",
    neighborhood: "Medina",
    description: "A luxurious riad blending traditional zellij with ultra-modern architecture. A glass-ceiling courtyard creates an airy atmosphere, while the rooftop pool offers a rare medina escape.",
    pricePerNight: 210,
    lifestyle: "premium",
    amenities: ["Rooftop Plunge Pool", "Traditional Hammam & Spa", "Glass-Ceiling Courtyard", "Gourmet Restaurant", "Wifi", "AC"],
    googleRating: 4.8,
    googleReviewCount: 320,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 320,
    bookingRating: 4.8,
    bookingReviewCount: 320,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 320,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["couple", "solo", "seniors"],
    tip: "Book a private underground hammam session—it is one of the most beautifully designed in Rabat.",
    vibeTags: ["Modern-Riad", "Luminous", "Sophisticated", "Boutique"],
    locationSummary: "Historic Medina & Kasbah des Oudayas",
    availabilityText: "Only 1 room left",
    googleMapsUrl: "https://maps.google.com/?q=Euphoriad+Rabat",
    address: "7-9 Impasse Caïd Bargach, Rabat Medina, Rabat 10030, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Euphoriad was created by an architect who wanted to bring light and modern comfort to the traditional riad structure.",
    neighborhoodOverview: "Rabat Medina is calmer and more orderly than many Moroccan old towns, with blue-and-white lanes, traditional souks, nearby tram/taxi access, and easy walks to the Kasbah of the Udayas and Atlantic edge.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Exceptional modern-Moroccan design", "Rare rooftop pool in medina", "High service standards"],
    cons: ["Small number of rooms", "Steep stairs to some suites"],
    trustScores: {
      cleanliness: 9.9,
      safety: 9.6,
      staff: 9.8,
      value: 8.8,
      comfort: 9.5,
      location: 9.7,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Nearby public lot (Bab El Had)",
      contact: "+212 537 734 222",
    },
    roomFeatures: ["underfloor-heating", "minimalist-artisanal-decor", "balcony-available", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Superior Room",
              price: 210,
              beds: "1 Queen",
              size: "24m²",
            },
      {
              name: "Suite Euphoria",
              price: 340,
              beds: "1 King",
              size: "48m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Bab El Had",
              distance: "300m",
              time: "4 min walk",
              icon: "gate",
            },
      {
              label: "Kasbah of Udayas",
              distance: "1.2km",
              time: "15 min walk",
              icon: "history",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome, but best for adults and older children",
    officialWebsite: "https://euphoriad.com",
    instagramHandle: "@euphoriadrabat",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and bright sanctuary for a solo design lover.",
      couples: "The rooftop pool and modern design made it romantic.",
      families: "Better suited for couples or solo travelers due to quiet atmosphere.",
      business: "A refreshing quiet alternative to corporate hotels.",
      nomad: "The courtyard is a beautiful quiet space to work from.",
    },
    coordinates: {
      lat: 34.027441,
      lng: -6.839085
    },
    tags: ["heritage"]
  },
  {
    id: "r-sleep-4",
    city: "rabat",
    name: "Villa Mandarine",
    type: "hotel",
    neighborhood: "Souissi",
    description: "A grand family home turned boutique hotel in a three-acre orange grove, with high ceilings, Moroccan textiles, shaded gardens, and a country vibe in the city.",
    pricePerNight: 200,
    lifestyle: "premium",
    amenities: ["Heated Outdoor Pool", "Orange Grove Gardens", "Fine Dining Patio", "Boutique Spa", "Wifi", "AC"],
    googleRating: 4.7,
    googleReviewCount: 1400,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 1400,
    bookingRating: 4.7,
    bookingReviewCount: 1400,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 1400,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "seniors"],
    tip: "Enjoy morning coffee in the courtyard to take in the citrus aromas.",
    vibeTags: ["Boutique", "Serene", "Garden-Oasis", "Charming"],
    locationSummary: "Souissi / Hassan Modern District",
    availabilityText: "Only 2 rooms left",
    googleMapsUrl: "https://maps.google.com/?q=Villa+Mandarine+Rabat",
    address: "19 Rue Ouled Bousbaa, Souissi, Rabat 10000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Originally a private home built in the 1970s, it was transformed to share the art of living in a Moroccan garden.",
    neighborhoodOverview: "Souissi is Rabat’s elite diplomatic and residential district, known for embassies, villas, secure leafy streets, golf access, and a car-oriented luxury lifestyle.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Beautiful citrus groves", "Intimate boutique feel", "Heated pool year-round"],
    cons: ["Taxi required for medina", "Limited rooms book early"],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.8,
      staff: 9.7,
      value: 8.9,
      comfort: 9.6,
      location: 9.2,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free secure parking",
      contact: "+212 537 752 019",
    },
    roomFeatures: ["private-terrace", "garden-view", "local-textiles", "ac", "heating", "heated-pool-access"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 200,
              beds: "1 Queen",
              size: "28m²",
            },
      {
              name: "Suite Garden",
              price: 320,
              beds: "1 King",
              size: "45m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Mega Mall",
              distance: "1.5km",
              time: "5 min drive",
              icon: "shopping",
            },
      {
              label: "Hassan Tower",
              distance: "8km",
              time: "15 min drive",
              icon: "monument",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - gardens and pool suit families",
    officialWebsite: "https://www.villamandarine.com",
    instagramHandle: "@villamandarine",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A peaceful and safe retreat for independent travelers.",
      couples: "The most romantic garden stay in the capital.",
      families: "Great for families who want a quiet pool and safe gardens.",
      business: "A refreshing alternative to corporate hotels.",
      nomad: "Working from the shaded terrace is a dream.",
    },
    coordinates: {
      lat: 33.964868,
      lng: -6.847702
    },
    tags: ["family-favorite"]
  },
  {
    id: "r-sleep-5",
    city: "rabat",
    name: "Riad Amaris",
    type: "riad",
    neighborhood: "Medina",
    description: "A welcoming family-run boutique riad with cozy spaces, a peaceful fountain patio under a glass ceiling, and warm Moroccan hospitality.",
    pricePerNight: 130,
    lifestyle: "balanced",
    amenities: ["Lush Courtyard with Fountain", "Furnished Rooftop Terrace", "Daily Traditional Breakfast", "Personalized Tour Services", "Wifi", "AC"],
    googleRating: 4.7,
    googleReviewCount: 1140,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 1140,
    bookingRating: 4.7,
    bookingReviewCount: 1140,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 1140,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family"],
    tip: "Ask the hosts to map out the best local street-food stalls hidden in nearby souks.",
    vibeTags: ["Family-Run", "Luminous", "Cozy", "Authentic"],
    locationSummary: "Historic Medina & Kasbah des Oudayas",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Amaris+Rabat",
    address: "10 Rue Lalla Hannou, Rabat Medina, Rabat 10030, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad Amaris was restored as a living house where guests experience the warmth of a Moroccan home in the capital.",
    neighborhoodOverview: "Rabat Medina is calmer and more orderly than many Moroccan old towns, with blue-and-white lanes, traditional souks, nearby tram/taxi access, and easy walks to the Kasbah of the Udayas and Atlantic edge.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Bright airy courtyard", "Exceptional family hospitality", "Great central medina location"],
    cons: ["No pool", "Hard to find first time"],
    trustScores: {
      cleanliness: 9.7,
      safety: 9.6,
      staff: 9.9,
      value: 9.2,
      comfort: 9.4,
      location: 9.6,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 537 721 111",
    },
    roomFeatures: ["traditional-decor", "natural-light", "premium-bedding", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Double Room",
              price: 130,
              beds: "1 Queen",
              size: "22m²",
            },
      {
              name: "Junior Suite",
              price: 180,
              beds: "1 King",
              size: "32m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Central Market",
              distance: "300m",
              time: "5 min walk",
              icon: "shopping",
            },
      {
              label: "Rabat Ville Station",
              distance: "1.2km",
              time: "15 min walk",
              icon: "train",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - family-friendly staff and suites available",
    officialWebsite: "https://riadamaris.com",
    instagramHandle: "@riadamaris",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and warm home base for solo travelers.",
      couples: "The bright courtyard and rooftop breakfast are romantic.",
      families: "Staff go out of their way for children.",
      business: "A quiet bright alternative to corporate hotels with great WiFi.",
      nomad: "The rooftop terrace is a peaceful sunny work spot.",
    },
    coordinates: {
      lat: 34.02511,
      lng: -6.840177
    },
    tags: ["family-favorite"]
  },
  {
    id: "r-sleep-6",
    city: "rabat",
    name: "L'Alcazar",
    type: "riad",
    neighborhood: "Medina",
    description: "A hidden gem in Rabat medina, L'Alcazar is an elegantly restored riad with a spacious patio and beautifully decorated rooms, combining historic charm with modern comfort.",
    pricePerNight: 145,
    lifestyle: "balanced",
    amenities: ["Spacious Central Patio", "Traditional Hammam & Spa", "Rooftop Solarium", "Gourmet Moroccan Cuisine", "Wifi", "AC"],
    googleRating: 4.8,
    googleReviewCount: 240,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 240,
    bookingRating: 4.8,
    bookingReviewCount: 240,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 240,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family"],
    tip: "The rooftop terrace has wonderful medina roof views—perfect for quiet afternoon tea.",
    vibeTags: ["Elegant", "Quiet", "Historic", "Authentic"],
    locationSummary: "Medina - Central and Safe",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=L%27Alcazar+Rabat",
    address: "4 Impasse Benabdallah, Rabat Medina, Rabat 10030, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Spanish"],
    customStory: "L’Alcazar was restored by artisans over several years to preserve the woodwork and plasterwork of this historic medina home.",
    neighborhoodOverview: "Rabat Medina is calmer and more orderly than many Moroccan old towns, with blue-and-white lanes, traditional souks, nearby tram/taxi access, and easy walks to the Kasbah of the Udayas and Atlantic edge.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night.",
    pros: ["Beautiful restored architecture", "Personalized service", "Peaceful atmosphere"],
    cons: ["No pool", "Short medina walk from gate"],
    trustScores: {
      cleanliness: 9.8,
      safety: 9.7,
      staff: 9.9,
      value: 9.3,
      comfort: 9.6,
      location: 9.7,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 537 202 245",
    },
    roomFeatures: ["traditional-tadelakt", "carved-ceilings", "luxury-bathrooms", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Deluxe Room",
              price: 145,
              beds: "1 Queen",
              size: "28m²",
            },
      {
              name: "Patio Suite",
              price: 210,
              beds: "1 King",
              size: "40m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Hassan Tower",
              distance: "1.5km",
              time: "15 min walk",
              icon: "monument",
            },
      {
              label: "Kasbah of the Udayas",
              distance: "800m",
              time: "10 min walk",
              icon: "castle",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome, but atmosphere is best for adults and older children",
    officialWebsite: "https://lalcazar-rabat.com",
    instagramHandle: "@lalcazarrabat",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and refined escape in the medina.",
      couples: "Traditional charm and quiet atmosphere are romantic.",
      families: "Better suited for adults and older children who appreciate quiet.",
      business: "A quiet and unique setting with reliable WiFi.",
      nomad: "The rooftop is an inspiring place to work with medina views.",
    },
    coordinates: {
      lat: 34.027159,
      lng: -6.840476
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "r-sleep-7",
    city: "rabat",
    name: "STORY Rabat",
    type: "hotel",
    neighborhood: "Souissi",
    description: "An intimate boutique oasis in Rabat's diplomatic Souissi quarter, designed like an Andalusian palace with lush gardens and a secluded pool.",
    pricePerNight: 260,
    lifestyle: "premium",
    amenities: ["Secluded Swimming Pool", "Tranquil Moroccan Spa", "Gourmet Patio Dining", "Private Boutique Gym", "Wifi", "AC"],
    googleRating: 4.7,
    googleReviewCount: 365,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 365,
    bookingRating: 4.7,
    bookingReviewCount: 365,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 365,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "seniors"],
    tip: "Request a ground-floor courtyard room for direct garden access and a villa feel.",
    vibeTags: ["Boutique-Oasis", "Andalusian-Elegance", "Secluded", "Refined"],
    locationSummary: "Souissi / Hassan Modern District",
    availabilityText: "Only 2 rooms left",
    googleMapsUrl: "https://maps.google.com/?q=STORY+Rabat",
    address: "Angle Rue Bani Yadder et Rue Jebala, Souissi, Rabat 10000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "STORY Rabat was designed as a private sanctuary for guests who value discretion and high design, echoing Rabat’s grand villas.",
    neighborhoodOverview: "Souissi is Rabat’s elite diplomatic and residential district, known for embassies, villas, secure leafy streets, golf access, and a car-oriented luxury lifestyle.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Exceptional privacy", "Beautiful Andalusian gardens", "High-end personalized service"],
    cons: ["Far from medina", "Limited facilities compared with large resorts"],
    trustScores: {
      cleanliness: 9.8,
      safety: 9.9,
      staff: 9.7,
      value: 8.5,
      comfort: 9.7,
      location: 9.1,
    },
    logistics: {
      checkIn: "15:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free secure parking",
      contact: "+212 537 752 019",
    },
    roomFeatures: ["garden-access-available", "premium-linens", "modern-andalusian-decor", "ac", "heating", "pool-view"],
    roomTypes: [
      {
              name: "Luxury Room",
              price: 260,
              beds: "1 Queen",
              size: "35m²",
            },
      {
              name: "Andalusian Suite",
              price: 420,
              beds: "1 King",
              size: "60m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Royal Golf Dar Es Salam",
              distance: "3km",
              time: "7 min drive",
              icon: "nature",
            },
      {
              label: "Hassan Tower",
              distance: "8km",
              time: "15 min drive",
              icon: "monument",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome, though best suited for adults and seniors",
    officialWebsite: "https://story-rabat.com",
    instagramHandle: "@storyrabat",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and quiet oasis for a discreet solo retreat.",
      couples: "The most romantic and secluded garden stay in Rabat.",
      families: "Better suited for adults and seniors due to the quiet atmosphere.",
      business: "A prestigious quiet alternative for business meetings in Souissi.",
      nomad: "Working from the poolside garden is a dream.",
    },
    coordinates: {
      lat: 33.943656,
      lng: -6.815736
    },
    tags: ["heritage"]
  },
  {
    id: "r-sleep-8",
    city: "rabat",
    name: "Riad Dar El Kebira",
    type: "riad",
    neighborhood: "Medina",
    description: "A luxurious historic riad arranged around two tiled courtyard patios with fountains, warm zellij, and carved plasterwork for an authentic royal feel.",
    pricePerNight: 180,
    lifestyle: "balanced",
    amenities: ["Two Courtyard Patios", "Traditional Hammam & Massage", "Gourmet Moroccan Kitchen", "Rooftop Terrace", "Wifi", "AC"],
    googleRating: 4.8,
    googleReviewCount: 1310,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 1310,
    bookingRating: 4.8,
    bookingReviewCount: 1310,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 1310,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["couple", "seniors", "family"],
    tip: "Visit the nearby Kasbah of the Udayas early in the morning to beat crowds and enjoy ocean views.",
    vibeTags: ["Royal", "Historic", "Authentic", "Grand"],
    locationSummary: "Historic Medina & Kasbah des Oudayas",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Dar+El+Kebira+Rabat",
    address: "1 Rue des Consuls, Rabat Medina, Rabat 10030, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Dar El Kebira was once a merchant palace; its restoration preserved the grand nature of the property and fine plaster carvings.",
    neighborhoodOverview: "Rabat Medina is calmer and more orderly than many Moroccan old towns, with blue-and-white lanes, traditional souks, nearby tram/taxi access, and easy walks to the Kasbah of the Udayas and Atlantic edge.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Regally decorated historic property", "Two spacious courtyards", "Exceptional traditional kitchen"],
    cons: ["No pool", "Courtyard can be noisy at breakfast"],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.5,
      staff: 9.8,
      value: 8.8,
      comfort: 9.5,
      location: 9.9,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Nearby public parking (Sidi Makhlouf)",
      contact: "+212 537 733 333",
    },
    roomFeatures: ["traditional-carvings", "premium-bedding", "fireplace-available", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Deluxe Room",
              price: 180,
              beds: "1 Queen",
              size: "28m²",
            },
      {
              name: "Imperial Suite",
              price: 320,
              beds: "1 King",
              size: "55m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Kasbah of Udayas",
              distance: "300m",
              time: "4 min walk",
              icon: "history",
            },
      {
              label: "Hassan Tower",
              distance: "1km",
              time: "12 min walk",
              icon: "monument",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - suites suit families",
    officialWebsite: "https://darelkebira.com",
    instagramHandle: "@riaddarelkebira",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and regally atmospheric base for a solo history lover.",
      couples: "Traditional courtyard dinners were romantic.",
      families: "Spacious and grand for children to experience history.",
      business: "A quiet unique setting for business travelers who value culture.",
      nomad: "The second courtyard is usually quiet and perfect for work.",
    },
    coordinates: {
      lat: 34.028225,
      lng: -6.835939
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "r-sleep-9",
    city: "rabat",
    name: "Riad Kalaa",
    type: "riad",
    neighborhood: "Medina",
    description: "A magnificent 19th-century riad within Rabat's medina ramparts, blending historic architecture and contemporary comfort with a pool, hammam, and restaurant.",
    pricePerNight: 160,
    lifestyle: "premium",
    amenities: ["Outdoor Swimming Pool", "Traditional Hammam & Spa", "Gourmet Moroccan Restaurant", "Rooftop Terrace", "Wifi", "AC"],
    googleRating: 4.6,
    googleReviewCount: 310,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 310,
    bookingRating: 4.6,
    bookingReviewCount: 310,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 310,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["couple", "family", "solo"],
    tip: "The courtyard pool is a rare luxury in the medina—perfect after a morning of exploring.",
    vibeTags: ["Palatial", "Historic", "Sophisticated", "Refreshing"],
    locationSummary: "Historic Medina & Kasbah des Oudayas",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Kalaa+Rabat",
    address: "3-5 Rue Zebdi, Rabat Medina, Rabat 10030, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Built in 1815, Riad Kalaa was a prominent family residence before being restored into a boutique riad.",
    neighborhoodOverview: "Rabat Medina is calmer and more orderly than many Moroccan old towns, with blue-and-white lanes, traditional souks, nearby tram/taxi access, and easy walks to the Kasbah of the Udayas and Atlantic edge.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night.",
    pros: ["Grand restored architecture", "Rare medina swimming pool", "Excellent on-site dining"],
    cons: ["Some ground-floor rooms can be dark"],
    trustScores: {
      cleanliness: 9.7,
      safety: 9.6,
      staff: 9.8,
      value: 8.8,
      comfort: 9.5,
      location: 9.8,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 537 202 028",
    },
    roomFeatures: ["traditional-tadelakt", "original-zellij", "pool-view-available", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Double Superior",
              price: 160,
              beds: "1 Queen",
              size: "30m²",
            },
      {
              name: "Suite",
              price: 230,
              beds: "1 King",
              size: "42m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Kasbah of the Udayas",
              distance: "600m",
              time: "8 min walk",
              icon: "castle",
            },
      {
              label: "Rabat Beach",
              distance: "1km",
              time: "12 min walk",
              icon: "beach",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - pool and suites suit families",
    officialWebsite: "https://riadkalaa.com",
    instagramHandle: "@riadkalaa",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe, majestic, and comfortable stay in the medina.",
      couples: "The pool and historic design are romantic.",
      families: "The pool is a hit with children after sightseeing.",
      business: "A quiet inspiring alternative with good business facilities.",
      nomad: "The rooftop is an incredible breezy work spot.",
    },
    coordinates: {
      lat: 34.027892,
      lng: -6.837525
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "r-sleep-10",
    city: "rabat",
    name: "Riad Dar Soufa",
    type: "riad",
    neighborhood: "Medina",
    description: "An elegant historic riad around a peaceful courtyard with a fountain. White arches and Moroccan carvings create a serene sanctuary near the souks.",
    pricePerNight: 120,
    lifestyle: "balanced",
    amenities: ["Central Courtyard with Fountain", "Panoramic Rooftop Terrace", "Daily Fresh-Cooked Breakfast", "Traditional Cooking Workshops", "Wifi", "AC"],
    googleRating: 4.5,
    googleReviewCount: 1060,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 1060,
    bookingRating: 4.5,
    bookingReviewCount: 1060,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 1060,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    tip: "If you have an early flight, staff can prepare a portable breakfast box if requested the night before.",
    vibeTags: ["Elegant", "Serene", "Historic", "Hospitality"],
    locationSummary: "Historic Medina & Kasbah des Oudayas",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Dar+Soufa+Rabat",
    address: "7 Derb Souaf Legza, Rabat Medina, Rabat 10030, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Dar Soufa was restored using traditional techniques; the name references local weaving heritage in the Rabat medina.",
    neighborhoodOverview: "Rabat Medina is calmer and more orderly than many Moroccan old towns, with blue-and-white lanes, traditional souks, nearby tram/taxi access, and easy walks to the Kasbah of the Udayas and Atlantic edge.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Serene quiet courtyard", "Views toward Salé", "Cooking workshops on-site"],
    cons: ["No pool", "Nearby alleys can be confusing"],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.5,
      staff: 9.8,
      value: 9.1,
      comfort: 9.4,
      location: 9.7,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Nearby public parking (Sidi Makhlouf)",
      contact: "+212 537 733 333",
    },
    roomFeatures: ["traditional-carvings", "natural-light", "quiet-location", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 120,
              beds: "1 Queen",
              size: "24m²",
            },
      {
              name: "Suite Soufa",
              price: 180,
              beds: "1 King",
              size: "40m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "River Bank",
              distance: "300m",
              time: "5 min walk",
              icon: "beach",
            },
      {
              label: "Kasbah of Udayas",
              distance: "600m",
              time: "8 min walk",
              icon: "history",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - staff are family-friendly",
    officialWebsite: "https://riaddarsoufa.com",
    instagramHandle: "@riaddarsoufa",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and serene sanctuary for solo travelers.",
      couples: "The rooftop terrace with river views is romantic.",
      families: "Wonderful hospitality and accommodating for families.",
      business: "A quiet and bright alternative to central business hotels.",
      nomad: "The rooftop terrace is a peaceful high-view work spot.",
    },
    coordinates: {
      lat: 34.024241,
      lng: -6.839629
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "r-sleep-11",
    city: "rabat",
    name: "Dar Shâan",
    type: "riad",
    neighborhood: "Medina",
    description: "A stylish riad combining boho-chic decor with Andalusian craftsmanship, with a rooftop pool and views across the medina toward the Atlantic.",
    pricePerNight: 140,
    lifestyle: "balanced",
    amenities: ["Rooftop Swimming Pool", "Cozy Central Fireplace", "Artisanal Moroccan Restaurant", "Wellness Spa", "Wifi", "AC"],
    googleRating: 4.5,
    googleReviewCount: 1020,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 1020,
    bookingRating: 4.5,
    bookingReviewCount: 1020,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 1020,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "friends"],
    tip: "Have breakfast on the rooftop terrace to enjoy ocean breezes as the medina wakes up.",
    vibeTags: ["Boho-Chic", "Stylish", "Panoramic", "Artisanal"],
    locationSummary: "Historic Medina & Kasbah des Oudayas",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Dar+Shaan+Rabat",
    address: "24 Rue Jirari, Rabat Medina, Rabat 10030, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Dar Shâan was created by collectors who wanted Moroccan craftsmanship in a modern, light-filled setting.",
    neighborhoodOverview: "Rabat Medina is calmer and more orderly than many Moroccan old towns, with blue-and-white lanes, traditional souks, nearby tram/taxi access, and easy walks to the Kasbah of the Udayas and Atlantic edge.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Rooftop pool and ocean views", "Trendy high-quality design", "Excellent service and food"],
    cons: ["Hard to find in medina streets", "Pool is plunge style"],
    trustScores: {
      cleanliness: 9.7,
      safety: 9.5,
      staff: 9.8,
      value: 9.1,
      comfort: 9.6,
      location: 9.7,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Nearby public parking (Sidi Makhlouf)",
      contact: "+212 537 733 333",
    },
    roomFeatures: ["artisanal-decor", "fireplace-available", "balcony-available", "ac", "heating", "rooftop-pool-access"],
    roomTypes: [
      {
              name: "Superior Room",
              price: 140,
              beds: "1 Queen",
              size: "26m²",
            },
      {
              name: "Junior Suite",
              price: 220,
              beds: "1 King",
              size: "38m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Kasbah of Udayas",
              distance: "500m",
              time: "7 min walk",
              icon: "history",
            },
      {
              label: "Atlantic Coast",
              distance: "400m",
              time: "5 min walk",
              icon: "beach",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome, though best for adults and friends",
    officialWebsite: "https://dar-shaan.com",
    instagramHandle: "@darshaanrabat",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe, stylish, and welcoming place for a solo design lover.",
      couples: "The rooftop pool and chic design made it romantic.",
      families: "Better suited for couples or friends due to boutique quiet vibe.",
      business: "A quiet alternative to business hotels with great WiFi.",
      nomad: "The rooftop terrace is a dream for morning remote work.",
    },
    coordinates: {
      lat: 34.13945,
      lng: -6.725164
    },
    tags: ["heritage"]
  },
  {
    id: "r-sleep-12",
    city: "rabat",
    name: "Conrad Rabat Arzana",
    type: "hotel",
    neighborhood: "Harhoura",
    description: "Perched on an oceanfront cliffside south of Rabat, this resort offers modern minimalist seaside design with floor-to-ceiling windows and Atlantic views.",
    pricePerNight: 320,
    lifestyle: "premium",
    amenities: ["Ocean-View Infinity Pool", "Direct Beach Access", "Acclaimed 99 Sushi Bar", "Signature Wellness Spa", "Fitness Center", "Wifi", "AC"],
    googleRating: 4.5,
    googleReviewCount: 880,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 880,
    bookingRating: 4.5,
    bookingReviewCount: 880,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 880,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "friends", "business-friendly"],
    tip: "Book 99 Sushi Bar early for a prime sunset oceanfront table.",
    vibeTags: ["Seaside-Minimalism", "Dramatic", "Coastal-Luxe", "Serene"],
    locationSummary: "Souissi / Hassan Modern District",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Conrad+Rabat+Arzana",
    address: "Plage Val d’Or, Harhoura, Rabat 12040, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Conrad Rabat Arzana emphasizes the power of the Atlantic landscape through bold, light-filled architecture.",
    neighborhoodOverview: "Harhoura is the premium coastal area south of Rabat, known for oceanfront residences, beaches, seafood spots, and quieter resort living away from the center.",
    hiddenFeesNotice: "City tax of 39.60 MAD per person/night not included.",
    pros: ["Exceptional ocean views", "World-class 99 Sushi Bar", "Quiet modern atmosphere"],
    cons: ["20 minutes south of central Rabat", "Car/taxi required for city exploration"],
    trustScores: {
      cleanliness: 9.8,
      safety: 9.9,
      staff: 9.4,
      value: 8.5,
      comfort: 9.7,
      location: 8.2,
    },
    logistics: {
      checkIn: "15:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Free secure parking",
      contact: "+212 537 749 400",
    },
    roomFeatures: ["floor-to-ceiling-ocean-views", "private-terrace", "modernist-decor", "ac", "heating", "workspace"],
    roomTypes: [
      {
              name: "Deluxe Ocean Room",
              price: 320,
              beds: "1 King",
              size: "45m²",
            },
      {
              name: "Ocean Front Suite",
              price: 550,
              beds: "1 King",
              size: "85m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Harhoura Beach",
              distance: "200m",
              time: "3 min walk",
              icon: "beach",
            },
      {
              label: "Hay Riad",
              distance: "12km",
              time: "15 min drive",
              icon: "city",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - pool and beach access suit families",
    officialWebsite: "https://www.hilton.com/en/hotels/rbacczi-conrad-rabat-arzana/",
    instagramHandle: "@conradrabatarzana",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and quiet retreat with excellent sushi and ocean sounds.",
      couples: "The most romantic sunset view in Rabat.",
      families: "Spacious and safe with great pool facilities for kids.",
      business: "A refreshing quiet alternative to central business hotels.",
      nomad: "Working with ocean sound and fast WiFi is a luxury.",
    },
    coordinates: {
      lat: 33.900296,
      lng: -6.998432
    },
    tags: ["family-favorite"]
  },
  {
    id: "r-sleep-13",
    city: "rabat",
    name: "Riad Dar Zen",
    type: "riad",
    neighborhood: "Medina",
    description: "An adults-only sanctuary with modern minimalist design and traditional Moroccan stonework, featuring an indoor plunge pool and quiet library.",
    pricePerNight: 83,
    lifestyle: "balanced",
    amenities: ["Indoor Plunge Pool", "Sun-Soaked Rooftop Terrace", "Quiet Library Lounge", "Airport Shuttle", "Wifi", "AC"],
    googleRating: 4.5,
    googleReviewCount: 230,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 230,
    bookingRating: 4.5,
    bookingReviewCount: 230,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 230,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple"],
    tip: "This adults-only riad is ideal for couples or digital nomads seeking silence.",
    vibeTags: ["Zen", "Minimalist", "Quiet", "Adults-Only"],
    locationSummary: "Historic Medina & Kasbah des Oudayas",
    availabilityText: "Only 2 rooms left",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Dar+Zen+Rabat",
    address: "5 Rue Frej, Rabat Medina, Rabat 10030, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Dar Zen was designed as a breath of fresh air in the medina, stripping away ornate complexity for a clean Moroccan experience.",
    neighborhoodOverview: "Rabat Medina is calmer and more orderly than many Moroccan old towns, with blue-and-white lanes, traditional souks, nearby tram/taxi access, and easy walks to the Kasbah of the Udayas and Atlantic edge.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Adults-only quiet", "Great spaces for remote work", "Minimalist design"],
    cons: ["No children allowed", "No dinner restaurant on-site"],
    trustScores: {
      cleanliness: 9.8,
      safety: 9.6,
      staff: 9.7,
      value: 9.3,
      comfort: 9.5,
      location: 9.4,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 661 234 567",
    },
    roomFeatures: ["minimalist-decor", "high-speed-wifi", "work-desk-available", "ac", "heating", "library-access"],
    roomTypes: [
      {
              name: "Standard Zen Room",
              price: 83,
              beds: "1 Queen",
              size: "22m²",
            },
      {
              name: "Suite Zen",
              price: 130,
              beds: "1 King",
              size: "35m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Central Souks",
              distance: "300m",
              time: "5 min walk",
              icon: "shopping",
            },
      {
              label: "Rabat Ville Station",
              distance: "1.2km",
              time: "15 min walk",
              icon: "train",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Adults-only property; children not accepted",
    officialWebsite: "https://riaddarzen.com",
    instagramHandle: "@riaddarzen",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A perfect safe silent retreat for a solo traveler or nomad.",
      couples: "The adults-only quiet is incredibly romantic.",
      families: "Not suitable as they do not accept children.",
      business: "Excellent WiFi and a very quiet work environment.",
      nomad: "The library and courtyard are among the best work spots in the medina.",
    },
    coordinates: {
      lat: 34.022499,
      lng: -6.838039
    },
    tags: []
  },
  {
    id: "r-sleep-14",
    city: "rabat",
    name: "Le Diwan Hotel Rabat - MGallery Collection",
    type: "hotel",
    neighborhood: "Hassan",
    description: "A chic boutique hotel fusing French Art Deco with Moroccan colors in the historic center near Hassan Tower and the medina.",
    pricePerNight: 140,
    lifestyle: "balanced",
    amenities: ["French-Moroccan Restaurant", "Lobby Bar & Lounge", "Wellness Spa", "Fitness Center", "Wifi", "AC"],
    googleRating: 4.5,
    googleReviewCount: 3900,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 3900,
    bookingRating: 4.5,
    bookingReviewCount: 3900,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 3900,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "friends", "seniors", "business-friendly"],
    tip: "Use the tram two minutes away at Place Al Joulane to explore the city quickly.",
    vibeTags: ["Chic", "Art-Deco", "Historic-Center", "Sophisticated"],
    locationSummary: "Souissi / Hassan Modern District",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Le+Diwan+Hotel+Rabat+MGallery",
    address: "Place de l’Unité Africaine, Hassan, Rabat 10005, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Le Diwan is part of MGallery, celebrating Rabat’s 1930s Art Deco heritage with a French-Moroccan design story.",
    neighborhoodOverview: "The Hassan district is Rabat’s historic administrative heart, close to Hassan Tower, the Mausoleum, tram stops, ministries, and the medina edge.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Excellent sightseeing location", "Stylish comfortable rooms", "Good business facilities"],
    cons: ["No pool", "Busy during diplomatic events"],
    trustScores: {
      cleanliness: 9.5,
      safety: 9.8,
      staff: 9.6,
      value: 8.8,
      comfort: 9.4,
      location: 9.9,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 537 262 727",
    },
    roomFeatures: ["art-deco-decor", "premium-bedding", "city-view", "ac", "heating", "workspace"],
    roomTypes: [
      {
              name: "Superior Room",
              price: 140,
              beds: "1 Queen",
              size: "28m²",
            },
      {
              name: "Luxury Suite",
              price: 260,
              beds: "1 King",
              size: "48m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Hassan Tower",
              distance: "400m",
              time: "5 min walk",
              icon: "monument",
            },
      {
              label: "Medina Entrance",
              distance: "600m",
              time: "8 min walk",
              icon: "gate",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome, best for older children and city sightseeing",
    officialWebsite: "https://all.accor.com/hotel/2820/index.en.shtml",
    instagramHandle: "@lediwanrabat",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe, chic, and central base for exploring Rabat.",
      couples: "Art Deco style and central location are great for sightseeing couples.",
      families: "Helpful staff and central location make it family-friendly.",
      business: "Reliable MGallery standards near government offices.",
      nomad: "The lobby lounge is stylish and quiet for work.",
    },
    coordinates: {
      lat: 34.017433,
      lng: -6.828154
    },
    tags: ["heritage"]
  },
  {
    id: "r-sleep-15",
    city: "rabat",
    name: "Riad Meftaha",
    type: "riad",
    neighborhood: "Ocean",
    description: "A warm traditional guesthouse on the Marassa Ocean district border, with blue-and-white zellij and Moroccan architecture steps from the Atlantic.",
    pricePerNight: 60,
    lifestyle: "lean",
    amenities: ["Traditional Tiled Courtyard", "Rooftop Terrace", "Daily Authentic Breakfast", "Luggage Storage", "Wifi", "AC"],
    googleRating: 4.5,
    googleReviewCount: 1500,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 1500,
    bookingRating: 4.5,
    bookingReviewCount: 1500,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 1500,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Book the Hassan V suite for spacious family accommodation with a traditional touch.",
    vibeTags: ["Ocean-Inspired", "Authentic", "Welcoming", "Budget-Friendly"],
    locationSummary: "Historic Medina & Kasbah des Oudayas",
    availabilityText: "Only 3 rooms left",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Meftaha+Rabat",
    address: "15 Rue Iran, Quartier de l’Océan, Rabat 10000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad Meftaha was once a family home; its name means The Key, symbolizing a warm welcome to Rabat’s secrets.",
    neighborhoodOverview: "Quartier de l’Océan is a lively residential district where Rabat meets the Atlantic, with local cafés, ocean air, promenades, and easy access to both beach and medina.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Excellent value", "Close to ocean promenade", "Authentic and clean"],
    cons: ["15 min walk to main souks", "No elevator"],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.5,
      staff: 9.8,
      value: 9.5,
      comfort: 9.2,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 537 721 111",
    },
    roomFeatures: ["traditional-zellij", "premium-linens", "quiet-location", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Standard Double",
              price: 60,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Family Suite",
              price: 110,
              beds: "1 Queen + 2 Singles",
              size: "40m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Ocean Promenade",
              distance: "300m",
              time: "4 min walk",
              icon: "beach",
            },
      {
              label: "Bab El Had Gate",
              distance: "800m",
              time: "10 min walk",
              icon: "gate",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - family suites available",
    officialWebsite: "https://riad-meftaha.com",
    instagramHandle: "@riadmeftaha",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe, clean, and welcoming riad for solo budget travelers.",
      couples: "The blue-and-white theme is bright and romantic.",
      families: "Family suites are large and great value.",
      business: "A quiet reliable place with good WiFi for short business trips.",
      nomad: "The courtyard is peaceful for morning work.",
    },
    coordinates: {
      lat: 34.025508,
      lng: -6.84253
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "r-sleep-16",
    city: "rabat",
    name: "Riad Dar Fassi",
    type: "riad",
    neighborhood: "Medina",
    description: "A renovated budget-friendly riad with colorful stained-glass windows, traditional archways, family-style welcome, and a peaceful old-city atmosphere.",
    pricePerNight: 48,
    lifestyle: "lean",
    amenities: ["Shared Lounge", "Two Rooftops", "Daily Halal Breakfast", "Tour Services", "Wifi", "AC"],
    googleRating: 4.4,
    googleReviewCount: 170,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 170,
    bookingRating: 4.4,
    bookingReviewCount: 170,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 170,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "friends"],
    tip: "Enjoy mint tea on check-in while relaxing in the stone courtyard.",
    vibeTags: ["Budget-Friendly", "Authentic", "Quiet", "Historic"],
    locationSummary: "Historic Medina & Kasbah des Oudayas",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Dar+Fassi+Rabat",
    address: "Rabat Medina, Rabat 10030, Morocco",
    paymentMethods: ["cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Dar Fassi reflects Fassi-style architecture brought to the capital for an affordable historic stay.",
    neighborhoodOverview: "Rabat Medina is calmer and more orderly than many Moroccan old towns, with blue-and-white lanes, traditional souks, nearby tram/taxi access, and easy walks to the Kasbah of the Udayas and Atlantic edge.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Strong budget option", "Friendly family atmosphere", "Authentic historic design"],
    cons: ["Rooms can be small", "Cash only"],
    trustScores: {
      cleanliness: 9.2,
      safety: 9.3,
      staff: 9.7,
      value: 9.8,
      comfort: 8.8,
      location: 9.5,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 537 733 333",
    },
    roomFeatures: ["traditional-tilework", "stained-glass", "quiet-at-night", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Double Room",
              price: 48,
              beds: "1 Queen",
              size: "18m²",
            },
      {
              name: "Twin Room",
              price: 55,
              beds: "2 Twin",
              size: "18m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Central Souks",
              distance: "200m",
              time: "3 min walk",
              icon: "shopping",
            },
      {
              label: "Bab Chellah",
              distance: "800m",
              time: "10 min walk",
              icon: "gate",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome, but rooms are compact",
    officialWebsite: "https://riaddarfassi.com",
    instagramHandle: "@riaddarfassi",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and cheap riad for solo budget travelers.",
      couples: "Simple but authentic for affordable medina stays.",
      families: "May be small for larger families, but fine for small ones.",
      business: "Good for a quick overnight, less ideal for long work.",
      nomad: "Basic but peaceful for work in the shared courtyard.",
    },
    coordinates: {
      lat: 34.026641,
      lng: -6.835068
    },
    tags: ["heritage"]
  },
  {
    id: "r-sleep-17",
    city: "rabat",
    name: "Riad Kalaa",
    type: "riad",
    neighborhood: "Medina",
    description: "Dating back to 1815, this restored riad within the medina walls features Moorish brickwork, an outdoor pool, and fireplace lounges.",
    pricePerNight: 120,
    lifestyle: "balanced",
    amenities: ["Outdoor Swimming Pool", "Cozy Fireplace Lounges", "Traditional Courtyard Bar", "Moroccan Spa", "Wifi", "AC"],
    googleRating: 4.4,
    googleReviewCount: 1670,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 1670,
    bookingRating: 4.4,
    bookingReviewCount: 1670,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 1670,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["couple", "friends", "seniors", "family"],
    tip: "Dine by the pool at night for a romantic candlelit atmosphere in the medina.",
    vibeTags: ["Historic", "Moorish", "Authentic", "Atmospheric"],
    locationSummary: "Historic Medina & Kasbah des Oudayas",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Kalaa+Rabat",
    address: "Rabat Medina, Rabat 10030, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad Kalaa was built into the foundations of the Almohad walls, preserving Rabat’s distinctive historic red brickwork.",
    neighborhoodOverview: "Rabat Medina is calmer and more orderly than many Moroccan old towns, with blue-and-white lanes, traditional souks, nearby tram/taxi access, and easy walks to the Kasbah of the Udayas and Atlantic edge.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Rare medina pool", "Deep historical atmosphere", "Professional service"],
    cons: ["Some rooms can be dark", "Walk from medina gate required"],
    trustScores: {
      cleanliness: 9.4,
      safety: 9.5,
      staff: 9.6,
      value: 8.9,
      comfort: 9.2,
      location: 9.8,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      luggageStorage: "Free",
      parking: "Nearby public parking (Bab El Had)",
      contact: "+212 537 202 020",
    },
    roomFeatures: ["traditional-brickwork", "fireplace-lounges", "balcony-available", "ac", "heating", "pool-view-available"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 120,
              beds: "1 Queen",
              size: "24m²",
            },
      {
              name: "Sultana Suite",
              price: 190,
              beds: "1 King",
              size: "42m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Andalusian Wall",
              distance: "100m",
              time: "2 min walk",
              icon: "history",
            },
      {
              label: "Bab El Had",
              distance: "600m",
              time: "8 min walk",
              icon: "gate",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - pool and suites available",
    officialWebsite: "https://riadkalaa.com",
    instagramHandle: "@riadkalaa",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A historic and quiet sanctuary in the medina.",
      couples: "Moorish architecture and pool make it romantic.",
      families: "Open courtyards and suites work well for families.",
      business: "Quiet enough for work, with good WiFi in common areas.",
      nomad: "A beautiful place to work from rooftop or courtyards.",
    },
    coordinates: {
      lat: 34.027892,
      lng: -6.837525
    },
    tags: ["family-favorite", "heritage"]
  },
  {
    id: "r-sleep-18",
    city: "rabat",
    name: "Riad El Maâti",
    type: "riad",
    neighborhood: "Medina",
    description: "An authentic budget-friendly riad close to Bab Chellah, with a traditional stone courtyard, cozy seating, plants, and rare elevator access.",
    pricePerNight: 53,
    lifestyle: "lean",
    amenities: ["Rooftop Terrace", "On-Site Restaurant", "Massage & Spa", "Elevator", "Wifi", "AC"],
    googleRating: 4.3,
    googleReviewCount: 160,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 160,
    bookingRating: 4.3,
    bookingReviewCount: 160,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 160,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "friends", "seniors"],
    tip: "One of the few medina riads with an elevator, ideal if you dislike carrying heavy bags up stairs.",
    vibeTags: ["Authentic", "Accessible", "Historic", "Budget-Friendly"],
    locationSummary: "Historic Medina & Kasbah des Oudayas",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+El+Maati+Rabat",
    address: "15 Rue Sidi El Maati, Rabat Medina, Rabat 10030, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad El Maâti has been in the same family for generations and preserves the neighborhood near Chellah as a guesthouse.",
    neighborhoodOverview: "Rabat Medina is calmer and more orderly than many Moroccan old towns, with blue-and-white lanes, traditional souks, nearby tram/taxi access, and easy walks to the Kasbah of the Udayas and Atlantic edge.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Rare elevator in medina", "Close to Bab Chellah and transport", "Friendly staff"],
    cons: ["Can be noisy near main street", "Simple room decor"],
    trustScores: {
      cleanliness: 9.1,
      safety: 9.4,
      staff: 9.6,
      value: 9.4,
      comfort: 9.0,
      location: 9.7,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:30",
      luggageStorage: "Free",
      parking: "Nearby public parking (Bab Chellah)",
      contact: "+212 537 733 333",
    },
    roomFeatures: ["traditional-stone-work", "elevator-access", "city-view-available", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 53,
              beds: "1 Queen",
              size: "22m²",
            },
      {
              name: "Accessible Room",
              price: 70,
              beds: "1 Queen",
              size: "24m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Bab Chellah",
              distance: "100m",
              time: "2 min walk",
              icon: "gate",
            },
      {
              label: "Chellah Necropolis",
              distance: "500m",
              time: "7 min walk",
              icon: "history",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome, elevator helps with family luggage",
    officialWebsite: "https://riadelmaati.com",
    instagramHandle: "@riadelmaati",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Safe and convenient with elevator and transport proximity.",
      couples: "The rooftop terrace is great for sunset over Rabat.",
      families: "Elevator makes it practical for families with gear.",
      business: "Good budget location near the city center.",
      nomad: "Decent WiFi and a large rooftop to work from.",
    },
    coordinates: {
      lat: 34.026152,
      lng: -6.83484
    },
    tags: ["heritage"]
  },
  {
    id: "r-sleep-19",
    city: "rabat",
    name: "Hostel Capital",
    type: "hostel",
    neighborhood: "Center",
    description: "A clean, lively, social hostel inside a historic courtyard house in the city center, with bright shared spaces for budget travelers and digital nomads.",
    pricePerNight: 35,
    lifestyle: "lean",
    amenities: ["Shared Lounge", "Guest Kitchen", "Rooftop Sun Terrace", "Bicycle Rental", "Wifi"],
    googleRating: 4.2,
    googleReviewCount: 300,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 300,
    bookingRating: 4.2,
    bookingReviewCount: 300,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 300,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: false,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "friends"],
    tip: "Order a packed lunch for budget-friendly day trips to Salé or Kenitra.",
    vibeTags: ["Social", "Budget-Friendly", "Lively", "Young"],
    locationSummary: "Historic Medina & Kasbah des Oudayas",
    availabilityText: "Beds available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Hostel+Capital+Rabat",
    address: "Rabat City Center, Rabat 10000, Morocco",
    paymentMethods: ["cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Hostel Capital was founded by former backpackers to bring a high-quality social hostel experience to the Moroccan capital.",
    neighborhoodOverview: "Rabat city center is practical and walkable, with Rabat Ville station, cafés, tram access, shops, government offices, and quick links to the medina.",
    hiddenFeesNotice: "City tax of 11.00 MAD per person/night not included.",
    pros: ["Best social atmosphere in Rabat", "Clean modern facilities", "Walk to Rabat Ville station"],
    cons: ["Can be noisy at night", "No AC in shared dorms"],
    trustScores: {
      cleanliness: 9.4,
      safety: 9.5,
      staff: 9.7,
      value: 9.9,
      comfort: 8.5,
      location: 9.8,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "On-street public parking",
      contact: "+212 537 733 333",
    },
    roomFeatures: ["privacy-curtains-on-bunks", "individual-lockers", "shared-kitchen-access", "rooftop-access", "heating"],
    roomTypes: [
      {
              name: "Dorm Bed",
              price: 35,
              beds: "1 Single (Dorm)",
              size: "30m² shared",
            },
      {
              name: "Private Double",
              price: 75,
              beds: "1 Queen",
              size: "18m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Rabat Ville Station",
              distance: "400m",
              time: "5 min walk",
              icon: "train",
            },
      {
              label: "Medina Entrance",
              distance: "500m",
              time: "7 min walk",
              icon: "gate",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Not recommended for families",
    officialWebsite: "https://hostelcapitalrabat.com",
    instagramHandle: "@hostelcapitalrabat",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "The safest and most social place for a solo backpacker in Rabat.",
      couples: "Private rooms are great value for social couples.",
      families: "Not recommended for families.",
      business: "Too noisy for serious business trips.",
      nomad: "Good for meeting people, but find a cafe for quiet work.",
    },
    coordinates: {
      lat: 34.026378,
      lng: -6.834424
    },
    tags: ["dorm", "heritage"]
  },
  {
    id: "r-sleep-20",
    city: "rabat",
    name: "Riad Jbara",
    type: "riad",
    neighborhood: "Medina",
    description: "A budget-friendly riad with a quaint courtyard and traditional Moroccan brickwork, offering a relaxed local atmosphere in the old city.",
    pricePerNight: 55,
    lifestyle: "lean",
    amenities: ["Rooftop Terrace", "Shared Courtyard Lounge", "Home-Cooked Dinners", "Wifi"],
    googleRating: 4.1,
    googleReviewCount: 1550,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 1550,
    bookingRating: 4.1,
    bookingReviewCount: 1550,
    hotelguruRating: 4.1,
    hotelguruReviewCount: 1550,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "friends"],
    tip: "Head to the rooftop at twilight to hear the call to prayer echoing from surrounding minarets.",
    vibeTags: ["Budget-Friendly", "Simple", "Local", "Relaxed"],
    locationSummary: "Historic Medina & Kasbah des Oudayas",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Jbara+Rabat",
    address: "Rabat Medina, Rabat 10030, Morocco",
    paymentMethods: ["cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad Jbara was established by a local family to offer affordable lodging for travelers who want a local medina experience.",
    neighborhoodOverview: "Rabat Medina is calmer and more orderly than many Moroccan old towns, with blue-and-white lanes, traditional souks, nearby tram/taxi access, and easy walks to the Kasbah of the Udayas and Atlantic edge.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Very affordable medina stay", "Cheap home-cooked dinners", "Authentic local atmosphere"],
    cons: ["Very simple rooms", "No AC, fans only", "Hard to find"],
    trustScores: {
      cleanliness: 8.8,
      safety: 9.2,
      staff: 9.5,
      value: 9.7,
      comfort: 8.2,
      location: 9.0,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      luggageStorage: "Free",
      parking: "Nearby public parking",
      contact: "+212 537 733 333",
    },
    roomFeatures: ["traditional-brickwork", "shared-lounge-access", "medina-terrace-view", "heating", "fan-available", "rooftop-access"],
    roomTypes: [
      {
              name: "Standard Double",
              price: 55,
              beds: "1 Queen",
              size: "20m²",
            },
      {
              name: "Twin Room",
              price: 60,
              beds: "2 Twin",
              size: "20m²",
            },
    ],
    neighborhoodDistances: [
      {
              label: "Medina Souks",
              distance: "400m",
              time: "6 min walk",
              icon: "shopping",
            },
      {
              label: "Rabat Ville Station",
              distance: "1.5km",
              time: "20 min walk",
              icon: "train",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome, but facilities are basic and better for older kids",
    officialWebsite: "https://riadjbara.com",
    instagramHandle: "@riadjbara",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and cheap local-vibe option for solo travelers.",
      couples: "Simple but authentic, with home-cooked dinners as the highlight.",
      families: "May be too basic for families with young children.",
      business: "Not recommended for business stays.",
      nomad: "Good for social nomads on a tight budget, though WiFi can be spotty.",
    },
    coordinates: {
      lat: 34.026834,
      lng: -6.835832
    },
    tags: []
  }
]
