import type { SleepListing } from '../types'

/**
 * SLEEP LISTING DATA TEMPLATE (Copy this for your search agent)
 * -------------------------------------------------------------
 * {
 *   "id": "city-sleep-XX",
 *   "name": "",
 *   "type": "riad | hotel | villa | hostel | apartment | guesthouse",
 *   "neighborhood": "",
 *   "city": "[city]",
 *   "description": "",
 *   "pricePerNight": 0,
 *   "lifestyle": "lean | balanced | premium",
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2', 'url3']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source (replaces single rating/reviewCount)
 *   // ═══════════════════════════════════════════════════
 *   // Search for real ratings from Google, TripAdvisor, Booking.com, and HotelGuru.
 *   // If you cannot find a rating for a specific source, set it to the same value as
 *   // the closest available one so average calculations don't break.
 *
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *   bookingRating: [4.x],
 *   bookingReviewCount: [number],
 *   hotelguruRating: [4.x],
 *   hotelguruReviewCount: [number],
 *
 *   // ═══════════════════════════════════════════════════
 *   // BOOLEAN AMENITIES
 *   // ═══════════════════════════════════════════════════
 *
 *   hasPool: true | false,
 *   hasBreakfast: true | false,
 *   hasAC: true | false,
 *   hasHeating: true | false,
 *   hasRooftop: true | false,
 *   hasEnsuite: true | false,
 *   hasRestaurant: true | false,
 *   hasBar: true | false,
 *   hasGym: true | false,
 *   hasElevator: true | false,
 *   hasLaundryService: true | false,
 *   hasRoomService: true | false,
 *   petFriendly: true | false,
 *   isWheelchairAccessible: true | false,
 *   taxesIncluded: true | false,
 *   freeCancellation: true | false,
 *   kidsStayFree: true | false,
 *
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearMosque: true | false,
 *   safetyLevel: 1 | 2 | 3 | 4 | 5,
 *
 *   // ═══════════════════════════════════════════════════
 *   // TRUST SCORES
 *   // ═══════════════════════════════════════════════════
 *
 *   trustScores: {
 *     cleanliness: [1-10],
 *     safety: [1-10],
 *     staff: [1-10],
 *     value: [1-10],
 *     comfort: [1-10],
 *     location: [1-10]
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   amenities: ['wifi', 'pool', 'ac', 'breakfast', 'spa', 'restaurant', 'gym', 'kitchenette', 'parking', 'bar', 'laundry', 'elevator', 'room-service'],
 *   tip: '[Short insider tip]',
 *   vibeTags: ['Authentic', 'Quiet', 'Modern'],
 *   locationSummary: 'Beachfront | City Center | Medina | Airport Area | Residential | Tourist Zone',
 *   availabilityText: 'Available tonight | Only 2 rooms left | Available on selected dates',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   address: '[Full street address, City, Postal Code, Morocco]',
 *
 *   paymentMethods: ['card', 'cash'],
 *   languagesSpoken: ['Arabic', 'French', 'English', 'Spanish', 'German'],
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   customStory: 'Brief history, owner background, or architecture notes...',
 *   neighborhoodOverview: 'Description of the local atmosphere, safety, and vibe...',
 *   hiddenFeesNotice: 'City tax of XX MAD per person/night not included...',
 *   pros: ['Pro 1', 'Pro 2'],
 *   cons: ['Con 1'],
 *
 *   // ═══════════════════════════════════════════════════
 *   // LOGISTICS
 *   // ═══════════════════════════════════════════════════
 *
 *   logistics: {
 *     checkIn: '14:00 - 22:00',
 *     checkOut: 'Before 11:00',
 *     
 *     luggageStorage: 'Free | Paid | None',
 *     parking: 'Free on-site | Nearby public | Valet',
 *     
 *     contact: '+212 XXXXXXXXX'
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *   // ROOM FEATURES & TYPES
 *   // ═══════════════════════════════════════════════════
 *
 *   roomFeatures: ['soundproof', 'workspace', 'private-balcony', 'ac', 'heating', 'balcony', 'shower-ensuite', 'sea-view', 'garden-view', 'pool-view'],
 *   roomTypes: [
 *     {
 *       name: 'Double Room',
 *       price: 500,
 *       beds: '1 Queen',
 *       size: '20m2',
 *       
 *     }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *   // NEIGHBORHOOD DISTANCES
 *   // ═══════════════════════════════════════════════════
 *
 *   neighborhoodDistances: [
 *     { label: 'Beach', distance: '500m', time: '5 min walk', icon: 'beach' }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   cancellationPolicy: 'Free cancellation up to 24h before check-in | Flexible | Non-refundable',
 *   childPolicy: 'Children welcome | Free under 6 | Extra bed 200 MAD',
 *   officialWebsite: 'https://...',
 *   instagramHandle: '@...',
 *
 *   // googlePlaceId: "PLACE_ID_HERE",
 *
 *   // ═══════════════════════════════════════════════════
 *   // REVIEW HIGHLIGHTS
 *   // ═══════════════════════════════════════════════════
 *
 *   reviewHighlights: {
 *     solo: 'Great insight for solo...',
 *     couples: 'Great for couples...',
 *     families: 'Kid-friendly details...',
 *     business: 'Wi-Fi test details...',
 *     nomad: 'Remote work specific insight...'
 *   }
 * }
 */

export const tangierSleep: SleepListing[] = [
  {
    id: "t-sleep-1",
    city: "tangier",
    name: "Fairmont Tazi Palace Tangier",
    type: "hotel",
    neighborhood: "Boubana",
    description: "A grand and meticulously restored palace originally built in the 1920s as a residence for the Sultan’s advisor. Perched on a hill with sweeping city and forest views, it offers the ultimate luxury experience in Tangier.",
    pricePerNight: 450,
    lifestyle: "premium",
    amenities: ["Outdoor Infinity Pool", "Fairmont Spa", "Signature Restaurants", "Botanical Gardens", "Butler Service", "Wifi", "AC", "5-star", "pool", "spa", "rooftop-terrace", "ocean-view", "airport-shuttle"],
    googleRating: 4.9,
    googleReviewCount: 350,
    tripadvisorRating: 4.9,
    tripadvisorReviewCount: 350,
    bookingRating: 4.9,
    bookingReviewCount: 350,
    hotelguruRating: 4.9,
    hotelguruReviewCount: 350,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["couple", "family", "seniors", "solo", "business-friendly"],
    tip: "The sunset view from the pool terrace is one of the most exclusive and beautiful in the city.",
    vibeTags: ["Palatial", "Majestic", "Secluded", "Ultra-Luxe"],
    locationSummary: "Boulevard & Ville Nouvelle Waterfront",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Fairmont+Tazi+Palace+Tangier",
    address: "Palais Tazi, Route de Boubana, Tangier 90000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Spanish"],
    customStory: "The palace was designed by Pacha Tazi in 1920 but remained unfinished for decades until its transformation into a Fairmont property.",
    neighborhoodOverview: "Boubana is a leafy hillside district with villas, views, forest edges, and a more secluded feel than central Tangier, best reached by taxi or private transfer.",
    hiddenFeesNotice: "City tax of 39.60 MAD per person/night not included.",
    pros: ["Highest level of luxury in Tangier", "Exceptional spa and pool facilities", "Quiet and secure location"],
    cons: ["10-minute drive to medina", "Highest price point in the city"],
    trustScores: {
      cleanliness: 9.9,
      safety: 9.9,
      staff: 9.8,
      value: 8.4,
      comfort: 9.9,
      location: 9.2,
    },
    logistics: {
      checkIn: "15:00",
      checkOut: "12:00",
      
      luggageStorage: "Free",
      parking: "Free valet",
      
      contact: "+212 539 378 989",
    },
    roomFeatures: ["soundproof", "panoramic-balcony", "marble-bathroom", "smart-room-controls", "ac", "heating"],
    roomTypes: [
      {
              name: "Deluxe Room",
              price: 450,
              beds: "1 King",
              size: "45m²",
              
            },
      {
              name: "Palace Suite",
              price: 1200,
              beds: "1 King",
              size: "100m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Kasbah Museum",
              distance: "3.5km",
              time: "10 min drive",
              icon: "history",
            },
      {
              label: "Grand Socco",
              distance: "3km",
              time: "8 min drive",
              icon: "city",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - gardens and pool suit families",
    officialWebsite: "https://www.fairmont.com/tangier/tazi-palace/",
    instagramHandle: "@fairmonttazipalace",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe, regal, and quiet haven for the high-end traveler.",
      couples: "The most romantic and sophisticated stay in Tangier.",
      families: "Great pool and gardens for children to enjoy in peace.",
      business: "Discreet and prestigious for high-level meetings.",
      nomad: "Excellent connectivity and several quiet spots to work from.",
    },
    coordinates: {
      lat: 35.78187,
      lng: -5.850714
    },
    tags: ["family-favorite", "heritage", "5-star", "pool", "spa", "rooftop-terrace", "ocean-view", "airport-shuttle"]
  },
  {
    id: "t-sleep-2",
    city: "tangier",
    name: "Palais Zahia Hotel & Spa",
    type: "hotel",
    neighborhood: "Medina",
    description: "A beautifully restored 1920s building that once served as a bank, now a boutique hotel in the medina with Moroccan craftsmanship, high ceilings, and a spa.",
    pricePerNight: 120,
    lifestyle: "premium",
    amenities: ["Luxury Spa", "Traditional Hammam", "Rooftop Terrace", "Gourmet Restaurant", "Wifi", "AC", "in-medina", "spa", "rooftop-terrace", "5-star"],
    googleRating: 4.6,
    googleReviewCount: 850,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 850,
    bookingRating: 4.6,
    bookingReviewCount: 850,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 850,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["couple", "solo", "family"],
    tip: "The hammam experience here is one of the best in Tangier—perfect after a day in the souks.",
    vibeTags: ["Historic", "Artisanal", "Refined", "Boutique"],
    locationSummary: "Kasbah & Medina Quarter",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Palais+Zahia+Hotel+Spa+Tangier",
    address: "Rue de la Marine, Tangier Medina, Tangier 90000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Spanish"],
    customStory: "This building was originally the Banque d’Etat du Maroc in 1920 and was restored to preserve its architectural heritage.",
    neighborhoodOverview: "Tangier Medina is compact, atmospheric, and steep, with Petit Socco, food stalls, port access, cafés, and winding lanes that are best explored on foot.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Exceptional historic restoration", "High-quality spa facilities", "Central medina location"],
    cons: ["No pool", "Can be noisy due to central location"],
    trustScores: {
      cleanliness: 9.7,
      safety: 9.8,
      staff: 9.6,
      value: 8.9,
      comfort: 9.5,
      location: 9.9,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      
      luggageStorage: "Free",
      parking: "Nearby public lot (Port)",
      
      contact: "+212 539 334 500",
    },
    roomFeatures: ["high-ceilings", "artisanal-plasterwork", "marble-bathrooms", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Deluxe Room",
              price: 120,
              beds: "1 Queen",
              size: "28m²",
              
            },
      {
              name: "Palace Suite",
              price: 210,
              beds: "1 King",
              size: "45m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Petit Socco",
              distance: "100m",
              time: "2 min walk",
              icon: "square",
            },
      {
              label: "Kasbah",
              distance: "600m",
              time: "8 min walk",
              icon: "history",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - family rooms available",
    officialWebsite: "https://www.palais-zahia.com",
    instagramHandle: "@palaiszahia",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and grand home base right in the action.",
      couples: "Historical charm and the spa made it romantic.",
      families: "Staff are helpful with luggage and children in the medina.",
      business: "Prestigious spot with good WiFi, though lively outside.",
      nomad: "An inspiring piece of history to work from for a few days.",
    },
    coordinates: {
      lat: 35.785681,
      lng: -5.810089
    },
    tags: ["family-favorite", "heritage", "in-medina", "spa", "rooftop-terrace", "5-star"]
  },
  {
    id: "t-sleep-3",
    city: "tangier",
    name: "El Minzah Hotel",
    type: "hotel",
    neighborhood: "Ville Nouvelle",
    description: "The legendary El Minzah has been Tangier’s most famous hotel since 1930, with Andalusian architecture, gardens, and a pool that hosted writers, diplomats, and stars.",
    pricePerNight: 165,
    lifestyle: "premium",
    amenities: ["Outdoor Pool", "Andalusian Gardens", "Historic Wine Bar", "Health Club", "Wifi", "AC", "5-star", "pool", "spa", "rooftop-terrace", "in-medina", "ocean-view"],
    googleRating: 4.6,
    googleReviewCount: 1850,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 1850,
    bookingRating: 4.6,
    bookingReviewCount: 1850,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 1850,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["couple", "seniors", "family"],
    tip: "Visit Caid’s Bar, a famous hangout for writers and diplomats during the International Zone era.",
    vibeTags: ["Iconic", "Historic", "Institutional", "Grand"],
    locationSummary: "Boulevard & Ville Nouvelle Waterfront",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=El+Minzah+Hotel+Tangier",
    address: "85 Rue de la Liberté, Tangier 90000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Spanish"],
    customStory: "Built in 1930 by Lord Bute, El Minzah became the heart of Tangier during its International Zone era.",
    neighborhoodOverview: "Ville Nouvelle is Tangier’s modern colonial-era center, with Grand Socco, Place de France, cafés, galleries, shops, and easier taxi access than the medina.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Incredible sense of history", "Best central location in Tangier", "Beautiful gardens and pool"],
    cons: ["Some rooms feel dated", "Service can be old-fashioned"],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.8,
      staff: 9.5,
      value: 8.8,
      comfort: 9.2,
      location: 9.9,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      
      luggageStorage: "Free",
      parking: "Secure private parking",
      
      contact: "+212 539 333 444",
    },
    roomFeatures: ["traditional-tiling", "heavy-fabrics", "garden-view-available", "ac", "heating", "classic-decor"],
    roomTypes: [
      {
              name: "Classic Room",
              price: 165,
              beds: "1 Queen",
              size: "25m²",
              
            },
      {
              name: "Deluxe Suite",
              price: 320,
              beds: "1 King",
              size: "45m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Grand Socco",
              distance: "100m",
              time: "2 min walk",
              icon: "city",
            },
      {
              label: "Place de France",
              distance: "400m",
              time: "5 min walk",
              icon: "city",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - pool and central location suit families",
    officialWebsite: "http://www.elminzah.com",
    instagramHandle: "@elminzahhotel",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A grand and very safe landmark for the solo traveler.",
      couples: "The gardens and history make it romantic.",
      families: "Great central pool for kids to burn off energy.",
      business: "A prestigious address for meetings and work.",
      nomad: "The bar and gardens are inspiring places to work from.",
    },
    coordinates: {
      lat: 35.781874,
      lng: -5.812409
    },
    tags: ["family-favorite", "heritage", "5-star", "pool", "spa", "rooftop-terrace", "in-medina", "ocean-view"]
  },
  {
    id: "t-sleep-4",
    city: "tangier",
    name: "Hotel Continental",
    type: "hotel",
    neighborhood: "Medina",
    description: "The oldest hotel in Morocco, established in 1865, overlooking the port. Famous for traditional Moroccan decor, historic terrace, and literary/film history.",
    pricePerNight: 65,
    lifestyle: "balanced",
    amenities: ["Historic Terrace", "Port Views", "Traditional Restaurant", "Wifi", "Gift Shop", "ocean-view", "rooftop-terrace", "in-medina"],
    googleRating: 4.1,
    googleReviewCount: 2450,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 2450,
    bookingRating: 4.1,
    bookingReviewCount: 2450,
    hotelguruRating: 4.1,
    hotelguruReviewCount: 2450,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "friends", "family"],
    tip: "Ask for an upper-floor sea-view room for sunrise over the Strait of Gibraltar.",
    vibeTags: ["Authentic", "Vintage", "Historic", "Bohemian"],
    locationSummary: "Kasbah & Medina Quarter",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Hotel+Continental+Tangier",
    address: "36 Rue Dar Baroud, Tangier 90000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Spanish"],
    customStory: "Established in 1865, this living museum of Tangier served as a set for The Sheltering Sky and preserved its 19th-century soul.",
    neighborhoodOverview: "Tangier Medina is compact, atmospheric, and steep, with Petit Socco, food stalls, port access, cafés, and winding lanes that are best explored on foot.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Unmatched historical atmosphere", "Stunning terrace views", "Authentic Moroccan decor"],
    cons: ["No AC or pool", "Can be noisy near the port"],
    trustScores: {
      cleanliness: 8.5,
      safety: 9.4,
      staff: 9.2,
      value: 9.0,
      comfort: 8.2,
      location: 9.8,
    },
    logistics: {
      checkIn: "13:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Nearby public lot (Port)",
      
      contact: "+212 539 931 024",
    },
    roomFeatures: ["traditional-zellij", "vintage-furniture", "port-view-available", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 65,
              beds: "1 Double",
              size: "20m²",
              
            },
      {
              name: "Sea View Suite",
              price: 95,
              beds: "1 Queen",
              size: "35m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Tangier Port",
              distance: "200m",
              time: "3 min walk",
              icon: "anchor",
            },
      {
              label: "Grand Socco",
              distance: "500m",
              time: "7 min walk",
              icon: "city",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - historic atmosphere, no elevator comfort",
    officialWebsite: "http://www.hotel-continental.ma",
    instagramHandle: "@hotelcontinentaltangier",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and authentic place to feel Tangier history.",
      couples: "Vintage charm and port views are romantic.",
      families: "Good for families who want Moroccan history.",
      business: "Good for a quick transit stay near the port with character.",
      nomad: "An inspiring but basic place to work from a historic terrace.",
    },
    coordinates: {
      lat: 35.787519,
      lng: -5.809523
    },
    tags: ["family-favorite", "heritage", "ocean-view", "rooftop-terrace", "in-medina"]
  },
  {
    id: "t-sleep-5",
    city: "tangier",
    name: "Grand Hotel Villa de France",
    type: "hotel",
    neighborhood: "Ville Nouvelle",
    description: "An elegant heritage hotel on a hill where Henri Matisse stayed and painted in 1912, with restored interiors, pool, gardens, and refined atmosphere.",
    pricePerNight: 160,
    lifestyle: "premium",
    amenities: ["Outdoor Pool", "Lush Gardens", "Panoramic Terrace", "Fine Dining", "Wifi", "AC", "5-star", "pool", "ocean-view", "rooftop-terrace", "spa"],
    googleRating: 4.7,
    googleReviewCount: 980,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 980,
    bookingRating: 4.7,
    bookingReviewCount: 980,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 980,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["couple", "seniors", "family"],
    tip: "Room 35 is where Matisse painted Window at Tangier—ask if you can see it.",
    vibeTags: ["Artistic", "Elegant", "Historic", "Serene"],
    locationSummary: "Boulevard & Ville Nouvelle Waterfront",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Grand+Hotel+Villa+de+France+Tangier",
    address: "Angle Rue de Hollande et Rue d’Angleterre, Tangier 90000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Spanish"],
    customStory: "This hotel was an early 20th-century social center; Henri Matisse stayed here and painted the medina view from his room.",
    neighborhoodOverview: "Ville Nouvelle is Tangier’s modern colonial-era center, with Grand Socco, Place de France, cafés, galleries, shops, and easier taxi access than the medina.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Fascinating artistic history", "Beautiful gardens and pool", "Excellent city and bay views"],
    cons: ["Slightly formal atmosphere", "Steep walk from medina gates"],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.8,
      staff: 9.7,
      value: 8.7,
      comfort: 9.5,
      location: 9.8,
    },
    logistics: {
      checkIn: "15:00",
      checkOut: "12:00",
      
      luggageStorage: "Free",
      parking: "On-site secure parking",
      
      contact: "+212 539 333 111",
    },
    roomFeatures: ["period-art", "high-ceilings", "garden-view-available", "ac", "heating", "balcony-available"],
    roomTypes: [
      {
              name: "Classic Room",
              price: 160,
              beds: "1 Queen",
              size: "28m²",
              
            },
      {
              name: "Matisse Suite",
              price: 350,
              beds: "1 King",
              size: "55m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Grand Socco",
              distance: "200m",
              time: "3 min walk",
              icon: "city",
            },
      {
              label: "St. Andrew’s Church",
              distance: "100m",
              time: "2 min walk",
              icon: "church",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - pool and gardens suit families",
    officialWebsite: "http://www.villadefrance.ma",
    instagramHandle: "@grandhotelvilladefrance",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A sophisticated and safe landmark for solo travelers.",
      couples: "The history and pool made it romantic.",
      families: "Great quiet pool for kids away from the noise.",
      business: "A prestigious address for quiet evening work and meetings.",
      nomad: "The terrace and gardens are inspiring places to work from.",
    },
    coordinates: {
      lat: 35.782312,
      lng: -5.8145
    },
    tags: ["family-favorite", "heritage", "5-star", "pool", "ocean-view", "rooftop-terrace", "spa"]
  },
  {
    id: "t-sleep-6",
    city: "tangier",
    name: "Riad Dar Nour",
    type: "riad",
    neighborhood: "Kasbah",
    description: "One of Tangier’s oldest and most celebrated guesthouses, Dar Nour offers chic bohemian decor and a multi-level panoramic terrace over the city and Strait of Gibraltar.",
    pricePerNight: 95,
    lifestyle: "premium",
    amenities: ["Panoramic Terrace", "Traditional Breakfast", "Massage Service", "Library", "Wifi", "AC", "in-medina", "rooftop-terrace", "ocean-view"],
    googleRating: 4.8,
    googleReviewCount: 720,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 720,
    bookingRating: 4.8,
    bookingReviewCount: 720,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 720,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["couple", "solo"],
    tip: "Dinner on the rooftop terrace is a must-book experience; sunsets over the Strait are unforgettable.",
    vibeTags: ["Bohemian", "Panoramic", "Chic", "Authentic"],
    locationSummary: "Kasbah & Medina Quarter",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Dar+Nour+Tangier",
    address: "20 Rue Gourna, Kasbah, Tangier 90000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Dar Nour was founded by French and Moroccan friends to celebrate Tangier’s light and artistic spirit.",
    neighborhoodOverview: "The Kasbah is the high, historic residential quarter above the medina, known for sea views, quieter lanes, old palaces, and the Kasbah Museum.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Best rooftop views in Tangier", "Stylish bohemian atmosphere", "Exceptional hospitality"],
    cons: ["Many stairs", "No pool"],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.5,
      staff: 9.5,
      value: 9.0,
      comfort: 9.1,
      location: 9.5,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Nearby public lot (Kasbah Gate)",
      
      contact: "+212 662 112 724",
    },
    roomFeatures: ["natural-fabrics", "artisanal-decor", "balcony-available", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 95,
              beds: "1 Double",
              size: "20m²",
              
            },
      {
              name: "Suite Nour",
              price: 175,
              beds: "1 Queen",
              size: "38m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Kasbah Museum",
              distance: "200m",
              time: "3 min walk",
              icon: "history",
            },
      {
              label: "Grand Socco",
              distance: "800m",
              time: "12 min walk",
              icon: "gate",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome, but many stairs make it best for older children",
    officialWebsite: "https://www.darnour.com",
    instagramHandle: "@darnourtangier",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A beautiful and safe oasis for a solo traveler with an eye for design.",
      couples: "Rooftop dinner at sunset was the most romantic part of our trip.",
      families: "Better suited for couples or solo travelers due to stairs.",
      business: "The terrace is a quiet place to work with a view.",
      nomad: "A perfect creative retreat with incredible light and atmosphere.",
    },
    coordinates: {
      lat: 35.78786,
      lng: -5.814188
    },
    tags: ["in-medina", "rooftop-terrace", "ocean-view"]
  },
  {
    id: "t-sleep-7",
    city: "tangier",
    name: "Mimi Calpe",
    type: "guesthouse",
    neighborhood: "Marshan",
    description: "A stunning 19th-century villa in Marshan transformed into a boutique guesthouse, with Mediterranean gardens, pool, and views of the Strait of Gibraltar.",
    pricePerNight: 140,
    lifestyle: "premium",
    amenities: ["Mediterranean Garden", "Outdoor Pool", "Gourmet Dining", "Strait Views", "Wifi", "AC", "pool", "ocean-view", "spa"],
    googleRating: 4.9,
    googleReviewCount: 350,
    tripadvisorRating: 4.9,
    tripadvisorReviewCount: 350,
    bookingRating: 4.9,
    bookingReviewCount: 350,
    hotelguruRating: 4.9,
    hotelguruReviewCount: 350,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["couple", "solo"],
    tip: "Spend an afternoon reading by the pool in the garden to escape the city buzz.",
    vibeTags: ["Stylish", "Garden-Oasis", "Historic", "Serene"],
    locationSummary: "Boulevard & Ville Nouvelle Waterfront",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Mimi+Calpe+Tangier",
    address: "71 Rue de la Plage, Marshan, Tangier 90000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Built in the late 19th century as a private villa, Mimi Calpe was restored into one of Tangier’s most stylish intimate stays.",
    neighborhoodOverview: "Marshan is one of Tangier’s most prestigious residential districts, close to the royal palace, villas, gardens, and the Kasbah while staying quieter than the medina core.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Secluded garden and pool", "Personalized stylish service", "Quiet prestigious location"],
    cons: ["15-minute walk to medina gates", "Limited rooms book fast"],
    trustScores: {
      cleanliness: 9.8,
      safety: 9.8,
      staff: 9.9,
      value: 8.8,
      comfort: 9.6,
      location: 9.5,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "On-site secure parking",
      
      contact: "+212 539 333 444",
    },
    roomFeatures: ["garden-view", "high-ceilings", "natural-fabrics", "ac", "heating", "pool-access"],
    roomTypes: [
      {
              name: "Garden Room",
              price: 140,
              beds: "1 Queen",
              size: "24m²",
              
            },
      {
              name: "Villa Suite",
              price: 240,
              beds: "1 King",
              size: "42m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Royal Palace",
              distance: "300m",
              time: "4 min walk",
              icon: "palace",
            },
      {
              label: "Grand Socco",
              distance: "1.2km",
              time: "15 min walk",
              icon: "city",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome, but quiet atmosphere is best for adults",
    officialWebsite: "https://www.mimicalpe.com",
    instagramHandle: "@mimicalpetangier",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and stylish haven; the garden is perfect for a quiet stay.",
      couples: "The most romantic and peaceful garden stay in Tangier.",
      families: "Better suited for couples or solo travelers seeking quiet.",
      business: "A quiet inspiring setting with good WiFi for remote work.",
      nomad: "The best garden to work from while feeling like a classic villa.",
    },
    coordinates: {
      lat: 35.768132,
      lng: -5.761399
    },
    tags: ["heritage"]
  },
  {
    id: "t-sleep-8",
    city: "tangier",
    name: "Dar Rif",
    type: "riad",
    neighborhood: "Medina",
    description: "A charming traditional riad in the medina with a warm atmosphere, well-stocked library, and rooftop terrace with city and port views.",
    pricePerNight: 75,
    lifestyle: "balanced",
    amenities: ["Well-Stocked Library", "Panoramic Rooftop Terrace", "Traditional Moroccan Breakfast", "Shared Lounge", "Wifi", "AC", "in-medina", "rooftop-terrace"],
    googleRating: 4.5,
    googleReviewCount: 1240,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 1240,
    bookingRating: 4.5,
    bookingReviewCount: 1240,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 1240,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "friends"],
    tip: "The library is a hidden gem—spend an hour with mint tea for the ultimate medina retreat.",
    vibeTags: ["Charming", "Quiet", "Literary", "Authentic"],
    locationSummary: "Kasbah & Medina Quarter",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Dar+Rif+Tangier",
    address: "Rue de la Kasbah, Tangier Medina, Tangier 90000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Dar Rif was created by local bibliophiles to combine Tangier’s literary history with Moroccan hospitality.",
    neighborhoodOverview: "Tangier Medina is compact, atmospheric, and steep, with Petit Socco, food stalls, port access, cafés, and winding lanes that are best explored on foot.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Excellent library and quiet spaces", "Central and easy to find", "Warm helpful staff"],
    cons: ["Small rooms", "No pool"],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.5,
      staff: 9.5,
      value: 9.0,
      comfort: 9.1,
      location: 9.5,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Nearby public parking",
      
      contact: "+212 539 334 500",
    },
    roomFeatures: ["traditional-tiling", "quiet-corner-room", "library-access", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 75,
              beds: "1 Double",
              size: "18m²",
              
            },
      {
              name: "Terrace Room",
              price: 95,
              beds: "1 Queen",
              size: "22m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Grand Socco",
              distance: "300m",
              time: "4 min walk",
              icon: "city",
            },
      {
              label: "Petit Socco",
              distance: "500m",
              time: "7 min walk",
              icon: "square",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome, but best for older children and quiet guests",
    officialWebsite: "https://dar-rif.com",
    instagramHandle: "@darriftangier",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and quiet sanctuary for solo travelers who love books.",
      couples: "The library and rooftop views made it unique and romantic.",
      families: "Better suited for couples or solo travelers due to the quiet vibe.",
      business: "A refreshing quiet alternative to central business hotels.",
      nomad: "The library is a great place to work with a city view.",
    },
    coordinates: {
      lat: 35.787137,
      lng: -5.810573
    },
    tags: ["in-medina", "rooftop-terrace"]
  },
  {
    id: "t-sleep-9",
    city: "tangier",
    name: "Bayt Alice",
    type: "hostel",
    neighborhood: "Medina",
    description: "A cozy boutique hostel in a restored medina house, known for welcoming social atmosphere, colorful decor, and a rooftop where travelers gather for sunsets.",
    pricePerNight: 35,
    lifestyle: "lean",
    amenities: ["Rooftop Sunset Terrace", "Shared Kitchen", "Communal Lounge", "Personal Lockers", "Wifi"],
    googleRating: 4.6,
    googleReviewCount: 1540,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 1540,
    bookingRating: 4.6,
    bookingReviewCount: 1540,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 1540,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: false,
    hasRooftop: true,
    hasEnsuite: false,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "friends"],
    tip: "Ask staff for their favorite hole-in-the-wall eateries in the medina.",
    vibeTags: ["Friendly", "Social", "Vibrant", "Budget-Friendly"],
    locationSummary: "Kasbah & Medina Quarter",
    availabilityText: "Beds available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Bayt+Alice+Tangier",
    address: "26 Rue Khatib Beni Idder, Tangier Medina, Tangier 90000, Morocco",
    paymentMethods: ["cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Bayt Alice was created to provide a warm home-away-from-home for young backpackers visiting Tangier.",
    neighborhoodOverview: "Tangier Medina is compact, atmospheric, and steep, with Petit Socco, food stalls, port access, cafés, and winding lanes that are best explored on foot.",
    hiddenFeesNotice: "City tax of 11.00 MAD per person/night not included.",
    pros: ["Unbeatable social atmosphere", "Excellent rooftop for meeting travelers", "Helpful local staff"],
    cons: ["Basic facilities", "No AC", "Cash only"],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.4,
      staff: 9.8,
      value: 9.9,
      comfort: 8.5,
      location: 9.9,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Nearby public parking lot",
      
      contact: "+212 539 333 444",
    },
    roomFeatures: ["individual-lockers", "traditional-rugs", "quiet-alley-location", "shared-kitchen-access", "rooftop-access"],
    roomTypes: [
      {
              name: "Dorm Bed",
              price: 35,
              beds: "1 Single (Dorm)",
              size: "25m² shared",
              
            },
      {
              name: "Private Room",
              price: 75,
              beds: "1 Double",
              size: "16m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Petit Socco",
              distance: "200m",
              time: "3 min walk",
              icon: "square",
            },
      {
              label: "Port of Tangier",
              distance: "400m",
              time: "6 min walk",
              icon: "anchor",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Not recommended for families",
    officialWebsite: "https://baytalice.com",
    instagramHandle: "@baytalice_tangier",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "The most welcoming and safe social environment for a solo traveler.",
      couples: "Great for budget couples who do not mind a shared experience.",
      families: "Not recommended for families.",
      business: "Not suitable for business travel.",
      nomad: "The rooftop is a decent place to work for a few hours.",
    },
    coordinates: {
      lat: 35.729194,
      lng: -5.912969
    },
    tags: ["dorm"]
  },
  {
    id: "t-sleep-10",
    city: "tangier",
    name: "Tangier Kasbah Hostel",
    type: "hostel",
    neighborhood: "Kasbah",
    description: "A budget-friendly hostel in the historic Kasbah with relaxed vibe, basic clean dorms, and a rooftop terrace overlooking the Strait of Gibraltar.",
    pricePerNight: 25,
    lifestyle: "lean",
    amenities: ["Rooftop Terrace", "Communal Lounge", "Personal Lockers", "Wifi"],
    googleRating: 4.3,
    googleReviewCount: 400,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 400,
    bookingRating: 4.3,
    bookingReviewCount: 400,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 400,
    hasPool: false,
    hasBreakfast: false,
    hasAC: false,
    hasHeating: false,
    hasRooftop: true,
    hasEnsuite: false,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "friends"],
    tip: "Bring a padlock for the lockers; the rooftop view over the Strait is free and excellent.",
    vibeTags: ["Budget-Friendly", "Relaxed", "Scenic", "Authentic"],
    locationSummary: "Kasbah & Medina Quarter",
    availabilityText: "Beds available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Tangier+Kasbah+Hostel",
    address: "Kasbah, Tangier 90000, Morocco",
    paymentMethods: ["cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Tangier Kasbah Hostel was started by a local guide to provide an affordable insider experience in the historic Kasbah.",
    neighborhoodOverview: "The Kasbah is the high, historic residential quarter above the medina, known for sea views, quieter lanes, old palaces, and the Kasbah Museum.",
    hiddenFeesNotice: "City tax of 11.00 MAD per person/night not included.",
    pros: ["Great value", "Excellent rooftop view", "Helpful local staff"],
    cons: ["Very basic facilities", "No breakfast included", "Cash only"],
    trustScores: {
      cleanliness: 8.8,
      safety: 9.1,
      staff: 9.6,
      value: 9.9,
      comfort: 8.0,
      location: 9.8,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Nearby public parking lot",
      
      contact: "+212 539 333 444",
    },
    roomFeatures: ["individual-lockers", "traditional-textiles", "quiet-alley-location", "rooftop-access", "shared-bathroom"],
    roomTypes: [
      {
              name: "Mixed Dorm Bed",
              price: 25,
              beds: "1 Single (Dorm)",
              size: "20m² shared",
              
            },
      {
              name: "Private Double",
              price: 55,
              beds: "1 Double",
              size: "14m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Kasbah Museum",
              distance: "200m",
              time: "3 min walk",
              icon: "history",
            },
      {
              label: "Petit Socco",
              distance: "800m",
              time: "12 min walk",
              icon: "square",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Not recommended for families",
    officialWebsite: "https://tangierkasbahhostel.com",
    instagramHandle: "@tangierkasbahhostel",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe, cheap, and friendly place for a solo backpacker.",
      couples: "Great for budget couples who do not mind a shared experience.",
      families: "Not recommended for families.",
      business: "Not suitable for business travel.",
      nomad: "The rooftop is a decent place to work for a few hours.",
    },
    coordinates: {
      lat: 35.787859,
      lng: -5.812366
    },
    tags: ["dorm", "heritage"]
  },
  {
    id: "t-sleep-11",
    city: "tangier",
    name: "The Medina Hostel",
    type: "hostel",
    neighborhood: "Medina",
    description: "A vibrant social hostel combining Moroccan style with backpacker essentials, lively atmosphere, central location, and highly rated free Moroccan breakfast.",
    pricePerNight: 30,
    lifestyle: "lean",
    amenities: ["Rooftop Social Terrace", "Free Traditional Breakfast", "Shared Kitchen", "Organized Tours", "Wifi"],
    googleRating: 4.5,
    googleReviewCount: 1540,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 1540,
    bookingRating: 4.5,
    bookingReviewCount: 1540,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 1540,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: false,
    hasRooftop: true,
    hasEnsuite: false,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "friends"],
    tip: "Do not miss the free Moroccan breakfast with fresh msemen and honey on the rooftop.",
    vibeTags: ["Social", "Vibrant", "Central", "Friendly"],
    locationSummary: "Kasbah & Medina Quarter",
    availabilityText: "Beds available tonight",
    googleMapsUrl: "https://maps.google.com/?q=The+Medina+Hostel+Tangier",
    address: "6 Rue des Postes, Tangier 90000, Morocco",
    paymentMethods: ["cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "The Medina Hostel was created to offer a social and community-driven experience for young travelers visiting Tangier.",
    neighborhoodOverview: "Tangier Medina is compact, atmospheric, and steep, with Petit Socco, food stalls, port access, cafés, and winding lanes that are best explored on foot.",
    hiddenFeesNotice: "City tax of 11.00 MAD per person/night not included.",
    pros: ["Excellent social atmosphere", "Great free breakfast", "Helpful local staff"],
    cons: ["Basic facilities", "No AC", "Cash only"],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.4,
      staff: 9.8,
      value: 9.9,
      comfort: 8.5,
      location: 9.9,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Nearby public parking lot",
      
      contact: "+212 539 333 444",
    },
    roomFeatures: ["individual-lockers", "traditional-rugs", "quiet-alley-location", "shared-kitchen-access", "rooftop-access"],
    roomTypes: [
      {
              name: "Dorm Bed",
              price: 30,
              beds: "1 Single (Dorm)",
              size: "25m² shared",
              
            },
      {
              name: "Private Room",
              price: 65,
              beds: "1 Double",
              size: "16m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Petit Socco",
              distance: "200m",
              time: "3 min walk",
              icon: "square",
            },
      {
              label: "Port of Tangier",
              distance: "400m",
              time: "6 min walk",
              icon: "anchor",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Adults only environment; 18+ for dorms.",
    officialWebsite: "https://themedinahostel.com",
    instagramHandle: "@themedinahostel",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "The most welcoming and safe social environment for a solo traveler.",
      couples: "Great for budget couples who do not mind a shared experience.",
      families: "Not recommended for families.",
      business: "Not suitable for business travel.",
      nomad: "The rooftop is a decent place to work for a few hours.",
    },
    coordinates: {
      lat: 35.787354,
      lng: -5.810295
    },
    tags: ["dorm"]
  },
  {
    id: "t-sleep-12",
    city: "tangier",
    name: "Riad Tingis",
    type: "riad",
    neighborhood: "Medina",
    description: "An authentic peaceful riad in the ancient medina, with traditional patio, fountain, restaurant, and rooftop terrace views over the old city.",
    pricePerNight: 95,
    lifestyle: "balanced",
    amenities: ["Traditional Central Patio", "On-Site Moroccan Restaurant", "Panoramic Rooftop Terrace", "Guided Medina Tours", "Wifi", "AC"],
    googleRating: 4.7,
    googleReviewCount: 1240,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 1240,
    bookingRating: 4.7,
    bookingReviewCount: 1240,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 1240,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["couple", "family", "solo"],
    tip: "Staff can organize private guided tours of the medina and Hercules Caves for a stress-free experience.",
    vibeTags: ["Authentic", "Peaceful", "Traditional", "Immersive"],
    locationSummary: "Kasbah & Medina Quarter",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Tingis+Tangier",
    address: "Rue de la Marine, Tangier 90000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Riad Tingis was created to provide an honest riad experience for travelers who want the real pulse of the ancient medina.",
    neighborhoodOverview: "Tangier Medina is compact, atmospheric, and steep, with Petit Socco, food stalls, port access, cafés, and winding lanes that are best explored on foot.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Architectural charm", "Peaceful central patio", "Exceptional Moroccan hospitality"],
    cons: ["Rooms are cozy", "No pool"],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.5,
      staff: 9.5,
      value: 9.0,
      comfort: 9.1,
      location: 9.5,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Nearby public parking",
      
      contact: "+212 539 333 444",
    },
    roomFeatures: ["traditional-tiling", "quiet-corner-room", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 95,
              beds: "1 Double",
              size: "18m²",
              
            },
      {
              name: "Family Room",
              price: 135,
              beds: "1 Queen + 1 Single",
              size: "28m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Petit Socco",
              distance: "200m",
              time: "3 min walk",
              icon: "square",
            },
      {
              label: "Port of Tangier",
              distance: "400m",
              time: "6 min walk",
              icon: "anchor",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children of all ages are welcome; baby cots available on request.",
    officialWebsite: "https://riad-tingis.com",
    instagramHandle: "@riadtingistangier",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe, peaceful, and welcoming home base for a solo traveler.",
      couples: "Traditional beauty and rooftop views made it romantic.",
      families: "Staff were helpful with luggage and kids in the medina.",
      business: "A refreshing quiet alternative to central business hotels.",
      nomad: "The rooftop terrace is a dream for morning remote work.",
    },
    coordinates: {
      lat: 35.802699,
      lng: -5.743784
    },
    tags: ["heritage"]
  },
  {
    id: "t-sleep-13",
    city: "tangier",
    name: "Saba's House",
    type: "riad",
    neighborhood: "Kasbah",
    description: "An ultra-exclusive boutique riad in the Kasbah, styled with Art Deco and Moroccan heritage, curated art, piano lounge, and panoramic Strait views.",
    pricePerNight: 190,
    lifestyle: "premium",
    amenities: ["Piano Lounge", "Panoramic Terrace", "Curated Art Collection", "Luxury Spa", "Fine Dining", "Wifi", "in-medina", "rooftop-terrace", "ocean-view", "spa", "5-star"],
    googleRating: 4.9,
    googleReviewCount: 220,
    tripadvisorRating: 4.9,
    tripadvisorReviewCount: 220,
    bookingRating: 4.9,
    bookingReviewCount: 220,
    hotelguruRating: 4.9,
    hotelguruReviewCount: 220,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["couple", "seniors"],
    tip: "Enjoy a quiet rooftop cocktail at sunset while watching ferries cross the Strait.",
    vibeTags: ["Sophisticated", "Art-Deco", "Exclusive", "Panoramic"],
    locationSummary: "Kasbah - Highest point of the Medina",
    availabilityText: "Only 1 room left",
    googleMapsUrl: "https://maps.google.com/?q=Saba%27s+House+Tangier",
    address: "61 Place de la Kasbah, Tangier 90000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Named after the owner’s grandmother, Saba’s House is a tribute to Tangier’s cosmopolitan and artistic history.",
    neighborhoodOverview: "The Kasbah is the high, historic residential quarter above the medina, known for sea views, quieter lanes, old palaces, and the Kasbah Museum.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Highest quality design in the Kasbah", "Stunning panoramic views", "Personalized service"],
    cons: ["No pool", "Car-free Kasbah zone requires short walk"],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.5,
      staff: 9.5,
      value: 9.0,
      comfort: 9.1,
      location: 9.5,
    },
    logistics: {
      checkIn: "15:00",
      checkOut: "12:00",
      
      luggageStorage: "Free",
      parking: "Nearby public lot (Kasbah Gate)",
      
      contact: "+212 539 333 444",
    },
    roomFeatures: ["smart-lighting", "custom-art", "luxury-linens", "ac", "heating", "panoramic-terrace"],
    roomTypes: [
      {
              name: "Superior Room",
              price: 190,
              beds: "1 Queen",
              size: "26m²",
              
            },
      {
              name: "Sultan Suite",
              price: 340,
              beds: "1 King",
              size: "52m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Kasbah Museum",
              distance: "150m",
              time: "2 min walk",
              icon: "history",
            },
      {
              label: "Grand Socco",
              distance: "850m",
              time: "12 min walk",
              icon: "city",
            },
    ],
    cancellationPolicy: "Strict 7 days",
    childPolicy: "Adult-oriented atmosphere; children 12+ generally welcome.",
    officialWebsite: "https://www.riadsabashouse.com",
    instagramHandle: "@sabas.house",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and sophisticated sanctuary in the Kasbah.",
      couples: "The design and view made it the highlight of our stay.",
      families: "Better suited for couples or adult families seeking quiet.",
      business: "A prestigious quiet setting for high-level remote work.",
      nomad: "The most visually inspiring and luxurious stay in the old city.",
    },
    coordinates: {
      lat: 35.790437,
      lng: -5.816798
    },
    tags: ["heritage", "in-medina", "rooftop-terrace", "ocean-view", "spa", "5-star"]
  },
  {
    id: "t-sleep-14",
    city: "tangier",
    name: "La Maison de Tanger",
    type: "hotel",
    neighborhood: "Marshan",
    description: "A restored 1950s villa turned boutique guesthouse, set in a Mediterranean garden with pool and views of the Strait of Gibraltar and Kasbah.",
    pricePerNight: 165,
    lifestyle: "premium",
    amenities: ["Lush Mediterranean Garden", "Outdoor Swimming Pool", "Panoramic Views of the Strait", "Gourmet Dining", "Wifi", "AC", "pool", "ocean-view", "rooftop-terrace"],
    googleRating: 4.9,
    googleReviewCount: 350,
    tripadvisorRating: 4.9,
    tripadvisorReviewCount: 350,
    bookingRating: 4.9,
    bookingReviewCount: 350,
    hotelguruRating: 4.9,
    hotelguruReviewCount: 350,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["couple", "solo", "seniors"],
    tip: "Spend an afternoon reading by the pool in the garden to escape the city buzz.",
    vibeTags: ["Stylish", "Garden-Oasis", "Mid-Century-Modern", "Serene"],
    locationSummary: "Boulevard & Ville Nouvelle Waterfront",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=La+Maison+de+Tanger",
    address: "9 Rue de la Liberté, Tangier 90000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Built in the 1950s as a private residence, the villa was restored to maintain Mid-Century Modern charm with contemporary luxury.",
    neighborhoodOverview: "Marshan is one of Tangier’s most prestigious residential districts, close to the royal palace, villas, gardens, and the Kasbah while staying quieter than the medina core.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Secluded garden and pool", "Personalized stylish service", "Quiet prestigious location"],
    cons: ["15-minute walk to medina gates", "Limited rooms book fast"],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.5,
      staff: 9.5,
      value: 9.0,
      comfort: 9.1,
      location: 9.5,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "On-site secure parking",
      
      contact: "+212 539 333 444",
    },
    roomFeatures: ["garden-view", "mid-century-decor", "high-ceilings", "ac", "heating", "pool-access"],
    roomTypes: [
      {
              name: "Garden View Room",
              price: 165,
              beds: "1 Queen",
              size: "28m²",
              
            },
      {
              name: "Panoramic Suite",
              price: 290,
              beds: "1 King",
              size: "45m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Kasbah Gate",
              distance: "400m",
              time: "5 min walk",
              icon: "gate",
            },
      {
              label: "Grand Socco",
              distance: "1.2km",
              time: "15 min walk",
              icon: "city",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children of all ages are welcome; peaceful garden environment to be respected.",
    officialWebsite: "https://www.lamaisondetanger.com",
    instagramHandle: "@lamaisondetanger",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and stylish haven; the garden is perfect for quiet stays.",
      couples: "The most romantic and peaceful garden stay in Tangier.",
      families: "Better suited for couples or solo travelers seeking quiet.",
      business: "A quiet inspiring setting with good WiFi for remote work.",
      nomad: "The best garden to work from while feeling like a classic villa.",
    },
    coordinates: {
      lat: 35.776386,
      lng: -5.796169
    },
    tags: ["heritage", "pool", "ocean-view", "rooftop-terrace"]
  },
  {
    id: "t-sleep-15",
    city: "tangier",
    name: "Marina Bay Hotel",
    type: "hotel",
    neighborhood: "Beachfront",
    description: "A stylish modern hotel directly on the Tangier corniche, offering contemporary rooms, marina and Strait views, poolside atmosphere, and central beachfront location.",
    pricePerNight: 95,
    lifestyle: "balanced",
    amenities: ["Beachfront Pool", "Modern Gym", "Lounge Bar", "Marina Views", "Wifi", "AC", "on-the-beach", "ocean-view", "pool", "rooftop-terrace"],
    googleRating: 4.2,
    googleReviewCount: 1250,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 1250,
    bookingRating: 4.2,
    bookingReviewCount: 1250,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 1250,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["couple", "family", "friends", "solo"],
    tip: "Book a sea-view room for sunrise over the marina; city-view rooms can be noisier at night.",
    vibeTags: ["Modern", "Vibrant", "Beachfront", "Contemporary"],
    locationSummary: "Boulevard & Ville Nouvelle Waterfront",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Marina+Bay+Hotel+Tangier",
    address: "Avenue Mohammed VI, Tangier 90000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Spanish"],
    customStory: "One of Tangier’s early beachfront hotels, Marina Bay was fully renovated for modern travelers while keeping its prime bay position.",
    neighborhoodOverview: "Tangier’s corniche is the modern beachfront strip, lined with hotels, restaurants, malls, nightlife, marina views, and easy taxi access to the train station.",
    hiddenFeesNotice: "City tax of 19.80 MAD per person/night not included.",
    pros: ["Prime beachfront and marina location", "Modern pool area", "Clean contemporary rooms"],
    cons: ["Corniche nightlife can be noisy", "20-minute walk to medina"],
    trustScores: {
      cleanliness: 9.2,
      safety: 9.6,
      staff: 9.1,
      value: 8.8,
      comfort: 9.0,
      location: 9.8,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      
      luggageStorage: "Free",
      parking: "On-site private parking",
      
      contact: "+212 539 328 300",
    },
    roomFeatures: ["marina-view", "minimalist-decor", "balcony-available", "ac", "heating", "pool-access"],
    roomTypes: [
      {
              name: "Classic Room",
              price: 95,
              beds: "1 Queen",
              size: "24m²",
              
            },
      {
              name: "Executive Sea View",
              price: 145,
              beds: "1 King",
              size: "32m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Tanger City Center",
              distance: "1.5km",
              time: "5 min drive",
              icon: "city",
            },
      {
              label: "Port of Tangier",
              distance: "500m",
              time: "7 min walk",
              icon: "anchor",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children of all ages are welcome; extra beds available for a fee.",
    officialWebsite: "https://www.marinabay-tangier.com",
    instagramHandle: "@marinabaytangier",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe, modern, and convenient beachfront spot.",
      couples: "Marina views at night from the balcony are romantic.",
      families: "Great pool and easy beach access for kids.",
      business: "Reliable modern option with good connectivity and views.",
      nomad: "The lounge and poolside are good work spots with sea breeze.",
    },
    coordinates: {
      lat: 35.780999,
      lng: -5.806343
    },
    tags: ["on-the-beach", "ocean-view", "pool", "rooftop-terrace"]
  },
  {
    id: "t-sleep-16",
    city: "tangier",
    name: "Hilton Tangier Al Houara Resort & Spa",
    type: "hotel",
    neighborhood: "Outskirts",
    description: "A sprawling world-class resort on a 5-kilometer beach, surrounded by protected forest, with golf course, three pools, kids club, and luxury spa.",
    pricePerNight: 180,
    lifestyle: "premium",
    amenities: ["Professional Golf Course", "Luxury Spa & Hammam", "Three Outdoor Pools", "Direct Beach Access", "Kids Club", "Wifi", "AC", "5-star", "on-the-beach", "ocean-view", "pool", "spa", "golf-course", "kids-club", "airport-shuttle"],
    googleRating: 4.5,
    googleReviewCount: 1100,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 1100,
    bookingRating: 4.5,
    bookingReviewCount: 1100,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 1100,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "countryside",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["family", "couple", "seniors", "business-friendly"],
    tip: "Perfect for families or a quiet resort experience away from the city; try the spa treatments.",
    vibeTags: ["Sprawling", "Resort-Style", "Secluded", "Luxury"],
    locationSummary: "Al Houara Coastal Nature Reserve",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Hilton+Tangier+Al+Houara+Resort+Spa",
    address: "Km 19.8 Route Nationale 1, Tangier 90000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Spanish"],
    customStory: "Part of a sustainable development project, the resort harmonizes with surrounding forest and the wilder Atlantic coast.",
    neighborhoodOverview: "The Al Houara coast south of Tangier is a quieter resort zone with Atlantic beach, golf, protected forest, and a car-dependent retreat atmosphere.",
    hiddenFeesNotice: "City tax of 39.60 MAD per person/night not included.",
    pros: ["Exceptional resort facilities", "Huge clean private beach", "Professional golf and spa"],
    cons: ["25-minute drive to city center", "Isolated from local cafés and markets"],
    trustScores: {
      cleanliness: 9.8,
      safety: 9.9,
      staff: 9.6,
      value: 8.5,
      comfort: 9.7,
      location: 8.2,
    },
    logistics: {
      checkIn: "15:00",
      checkOut: "12:00",
      
      luggageStorage: "Free",
      parking: "Free secure parking",
      
      contact: "+212 539 409 400",
    },
    roomFeatures: ["ocean-view", "private-balcony", "marble-bathroom", "ac", "heating", "resort-view"],
    roomTypes: [
      {
              name: "King Guest Room",
              price: 180,
              beds: "1 King",
              size: "42m²",
              
            },
      {
              name: "One Bedroom Suite",
              price: 380,
              beds: "1 King",
              size: "95m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Hercules Caves",
              distance: "12km",
              time: "15 min drive",
              icon: "history",
            },
      {
              label: "Tangier Airport",
              distance: "15km",
              time: "18 min drive",
              icon: "plane",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Kids under 6 stay free in existing bedding; 6-12 receive 50% breakfast discount.",
    officialWebsite: "https://www.hilton.com/en/hotels/tngahit-hilton-tangier-al-houara-resort-and-spa/",
    instagramHandle: "@hiltonalhouara",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and quiet retreat for self-care and golf.",
      couples: "Isolation and Atlantic sunsets were perfect for couples.",
      families: "Kids club and huge pools entertain children all day.",
      business: "Excellent for high-end conferences and executive retreats.",
      nomad: "Great for a deep-work week with resort amenities.",
    },
    coordinates: {
      lat: 35.667332,
      lng: -5.965774
    },
    tags: ["family-favorite", "5-star", "on-the-beach", "ocean-view", "pool", "spa", "golf-course", "kids-club", "airport-shuttle"]
  },
  {
    id: "t-sleep-17",
    city: "tangier",
    name: "Barceló Tanger",
    type: "hotel",
    neighborhood: "Beachfront",
    description: "A fully renovated modern hotel overlooking the Bay of Tangier, with design-forward rooms, large outdoor pool, dining, and beach promenade access.",
    pricePerNight: 125,
    lifestyle: "premium",
    amenities: ["Outdoor Pool", "Beachfront Access", "Wellness Center", "B-Heaven Rooftop Bar", "Wifi", "AC", "5-star", "on-the-beach", "ocean-view", "pool", "spa", "rooftop-terrace", "rooftop-bar"],
    googleRating: 4.4,
    googleReviewCount: 1550,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 1550,
    bookingRating: 4.4,
    bookingReviewCount: 1550,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 1550,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["couple", "family", "friends", "business-friendly"],
    tip: "The B-Heaven rooftop bar is one of the coolest spots for a drink with a bay view.",
    vibeTags: ["Design-Forward", "Chic", "Modern", "Beachfront"],
    locationSummary: "Boulevard & Ville Nouvelle Waterfront",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Barcelo+Tanger",
    address: "43 Avenue Mohammed VI, Tangier 90000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Spanish"],
    customStory: "One of Tangier’s first major international hotels, Barceló Tanger was transformed by a major renovation into a modern Mediterranean landmark.",
    neighborhoodOverview: "Tangier’s corniche is the modern beachfront strip, lined with hotels, restaurants, malls, nightlife, marina views, and easy taxi access to the train station.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Stunning modern design", "Top rooftop bar and pool", "Excellent buffet breakfast"],
    cons: ["Can feel corporate", "Beachfront busy on summer weekends"],
    trustScores: {
      cleanliness: 9.7,
      safety: 9.8,
      staff: 9.4,
      value: 8.9,
      comfort: 9.6,
      location: 9.8,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      
      luggageStorage: "Free",
      parking: "Secure private parking",
      
      contact: "+212 539 342 100",
    },
    roomFeatures: ["rain-shower", "sleek-design", "sea-view-available", "ac", "heating", "rooftop-bar-access"],
    roomTypes: [
      {
              name: "Superior Room",
              price: 125,
              beds: "1 Queen",
              size: "28m²",
              
            },
      {
              name: "Deluxe Sea View",
              price: 185,
              beds: "1 King",
              size: "35m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Tanger City Mall",
              distance: "1km",
              time: "12 min walk",
              icon: "shopping",
            },
      {
              label: "Al Boraq Station",
              distance: "1.2km",
              time: "15 min walk",
              icon: "train",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children of all ages welcome; baby cots free on request.",
    officialWebsite: "https://www.barcelo.com/en-gb/barcelo-tanger/",
    instagramHandle: "@barcelotanger",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A very safe, modern, and high-standard stay with great views.",
      couples: "The rooftop bar at night was the highlight.",
      families: "Great pool and helpful staff for children.",
      business: "Perfect for business travelers with fast WiFi and station proximity.",
      nomad: "The rooftop and lobby lounge are excellent work spaces.",
    },
    coordinates: {
      lat: 35.77764,
      lng: -5.800003
    },
    tags: ["5-star", "on-the-beach", "ocean-view", "pool", "spa", "rooftop-terrace", "rooftop-bar"]
  },
  {
    id: "t-sleep-18",
    city: "tangier",
    name: "Kenzi Solazur",
    type: "hotel",
    neighborhood: "Beachfront",
    description: "A large bustling hotel on the corniche, with entertainment options, multiple restaurants, sea-view rooms, and a central beachfront location.",
    pricePerNight: 85,
    lifestyle: "balanced",
    amenities: ["Outdoor Pool", "Nightclub", "Wellness Spa", "Multiple Restaurants", "Wifi", "AC", "on-the-beach", "ocean-view", "pool", "spa", "rooftop-bar", "nightclubs"],
    googleRating: 4.0,
    googleReviewCount: 2200,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 2200,
    bookingRating: 4.0,
    bookingReviewCount: 2200,
    hotelguruRating: 4.0,
    hotelguruReviewCount: 2200,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: true,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ["friends", "family", "couple"],
    tip: "Ask for a higher-floor room to reduce nightclub and corniche traffic noise.",
    vibeTags: ["Lively", "Bustling", "Beachfront", "Entertainment-Focused"],
    locationSummary: "Boulevard & Ville Nouvelle Waterfront",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Kenzi+Solazur+Tangier",
    address: "Avenue Mohammed VI, Tangier 90000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Spanish"],
    customStory: "Kenzi Solazur has long been a staple of Tangier tourism, known for events and its prime bay location.",
    neighborhoodOverview: "Tangier’s corniche is the modern beachfront strip, lined with hotels, restaurants, malls, nightlife, marina views, and easy taxi access to the train station.",
    hiddenFeesNotice: "City tax of 19.80 MAD per person/night not included.",
    pros: ["Dining and nightlife options", "Excellent sea views", "Competitive beachfront pricing"],
    cons: ["Very loud at night", "Impersonal during busy periods"],
    trustScores: {
      cleanliness: 8.8,
      safety: 9.4,
      staff: 8.9,
      value: 9.1,
      comfort: 8.7,
      location: 9.9,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      
      luggageStorage: "Free",
      parking: "Secure private parking",
      
      contact: "+212 539 340 500",
    },
    roomFeatures: ["sea-view-available", "classic-decor", "ac", "heating", "higher-floor-recommended"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 85,
              beds: "1 Queen",
              size: "25m²",
              
            },
      {
              name: "Executive Sea View",
              price: 135,
              beds: "1 King",
              size: "35m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Tanger City Mall",
              distance: "800m",
              time: "10 min walk",
              icon: "shopping",
            },
      {
              label: "Al Boraq Station",
              distance: "1km",
              time: "12 min walk",
              icon: "train",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "One child under 6 stays free; over 6 considered an adult.",
    officialWebsite: "https://www.kenzi-hotels.com/kenzi-solazur",
    instagramHandle: "@kenzisolazur",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Safe and lively for travelers who enjoy action.",
      couples: "Sea view was great, though nightlife noise can be much.",
      families: "Kids enjoy the pool and nearby family cafés.",
      business: "Convenient location, but noisy for early meetings.",
      nomad: "Good if you want to work by day and party by night.",
    },
    coordinates: {
      lat: 35.776487,
      lng: -5.797505
    },
    tags: ["family-favorite", "on-the-beach", "ocean-view", "pool", "spa", "rooftop-bar", "nightclubs"]
  },
  {
    id: "t-sleep-19",
    city: "tangier",
    name: "Ibis Tanger City Center",
    type: "hotel",
    neighborhood: "City Center",
    description: "A modern reliable hotel in the city center beside the Al Boraq train station, with standardized comfort, minimalist rooms, and pool.",
    pricePerNight: 55,
    lifestyle: "lean",
    amenities: ["Central Swimming Pool", "Modern Restaurant & Bar", "Proximity to Train Station", "24-Hour Reception", "Wifi", "AC", "pool", "airport-shuttle"],
    googleRating: 4.1,
    googleReviewCount: 1800,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 1800,
    bookingRating: 4.1,
    bookingReviewCount: 1800,
    hotelguruRating: 4.1,
    hotelguruReviewCount: 1800,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: false,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    // sleep-location quiz question tag
    locationFeel: "ville-nouvelle",
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "friends", "business-friendly"],
    tip: "Perfect if you have an early Al Boraq high-speed train—the station is practically next door.",
    vibeTags: ["Practical", "Reliable", "Central", "Modern"],
    locationSummary: "Boulevard & Ville Nouvelle Waterfront",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Ibis+Tanger+City+Center",
    address: "City Center, Place Maghreb Arabe, Tangier 90000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Designed for modern travelers, this Ibis property is a staple for consistency and convenience in Tangier.",
    neighborhoodOverview: "Tangier’s corniche is the modern beachfront strip, lined with hotels, restaurants, malls, nightlife, marina views, and easy taxi access to the train station.",
    hiddenFeesNotice: "City tax of 17.60 MAD per person/night not included.",
    pros: ["Unbeatable train location", "Standard clean facilities", "Good value"],
    cons: ["Busy and impersonal at peak times", "Away from medina charm"],
    trustScores: {
      cleanliness: 9.2,
      safety: 9.4,
      staff: 9.0,
      value: 9.5,
      comfort: 8.8,
      location: 9.8,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "12:00",
      
      luggageStorage: "Free",
      parking: "On-site public parking",
      
      contact: "+212 539 300 000",
    },
    roomFeatures: ["sweet-bed-concept", "work-desk", "city-view", "ac", "heating", "elevator-access"],
    roomTypes: [
      {
              name: "Standard Double",
              price: 55,
              beds: "1 Queen",
              size: "20m²",
              
            },
      {
              name: "Twin Room",
              price: 60,
              beds: "2 Twin",
              size: "20m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Tangier Ville Station",
              distance: "100m",
              time: "2 min walk",
              icon: "train",
            },
      {
              label: "Tangier Corniche",
              distance: "300m",
              time: "4 min walk",
              icon: "beach",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Up to 2 children under 16 stay free when sharing a room with parents.",
    officialWebsite: "https://all.accor.com/hotel/5736/index.en.shtml",
    instagramHandle: "@ibishotels",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Safe and very convenient for a quick transit stay.",
      couples: "Simple and practical base for exploring the city center.",
      families: "Functional and easy for families on the move.",
      business: "Excellent for business travelers using the TGV.",
      nomad: "Reliable WiFi and central location make it a decent work base.",
    },
    coordinates: {
      lat: 35.772285,
      lng: -5.782874
    },
    tags: ["family-favorite"]
  },
  {
    id: "t-sleep-20",
    city: "tangier",
    name: "Riad Dar Yasmine",
    type: "riad",
    neighborhood: "Medina",
    description: "A charming intimate traditional house deep in Tangier medina, offering personalized service, traditional decor, and a warm family-like atmosphere.",
    pricePerNight: 65,
    lifestyle: "balanced",
    amenities: ["Panoramic Rooftop Terrace", "Traditional Home-Cooked Breakfast", "Personalized Tour Assistance", "Library & Lounge", "Wifi", "AC"],
    googleRating: 4.8,
    googleReviewCount: 250,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 250,
    bookingRating: 4.8,
    bookingReviewCount: 250,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 250,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: false,
    freeCancellation: true,
    kidsStayFree: false,
    nearMedina: true,
    // sleep-location quiz question tag
    locationFeel: "medina-heart",
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "friends", "family"],
    tip: "The host makes an amazing home-cooked tagine on request—better than many restaurants.",
    vibeTags: ["Intimate", "Warm", "Authentic", "Homey"],
    locationSummary: "Kasbah & Medina Quarter",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Dar+Yasmine+Tangier",
    address: "15 Rue Sidi Mansour, Medina, Tangier 90000, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English"],
    customStory: "Dar Yasmine is a family-run passion project preserving traditional Tangier hospitality in a modernizing city.",
    neighborhoodOverview: "Tangier Medina is compact, atmospheric, and steep, with Petit Socco, food stalls, port access, cafés, and winding lanes that are best explored on foot.",
    hiddenFeesNotice: "City tax of 28.60 MAD per person/night not included.",
    pros: ["Warm personalized service", "Authentic atmosphere", "Excellent breakfast and rooftop views"],
    cons: ["Tricky to find first time", "Steep traditional stairs"],
    trustScores: {
      cleanliness: 9.3,
      safety: 9.5,
      staff: 9.5,
      value: 9.0,
      comfort: 9.1,
      location: 9.5,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Nearby public parking (Grand Socco)",
      
      contact: "+212 539 934 000",
    },
    roomFeatures: ["traditional-fabrics", "hand-painted-details", "rooftop-view", "ac", "heating", "library-access"],
    roomTypes: [
      {
              name: "Standard Double",
              price: 65,
              beds: "1 Queen",
              size: "22m²",
              
            },
      {
              name: "Family Room",
              price: 95,
              beds: "1 Queen + 1 Single",
              size: "30m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Kasbah",
              distance: "400m",
              time: "6 min walk",
              icon: "castle",
            },
      {
              label: "Grand Socco",
              distance: "500m",
              time: "7 min walk",
              icon: "city",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children of all ages welcome; family-friendly but quiet atmosphere.",
    officialWebsite: "https://daryasmine.com",
    instagramHandle: "@daryasmine_tangier",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe, warm, and welcoming sanctuary in the medina.",
      couples: "The intimate atmosphere and rooftop breakfasts were perfect.",
      families: "Small and quiet, best for older children or couples.",
      business: "A peaceful and inspiring alternative to standard hotels.",
      nomad: "The rooftop is a wonderful spot for quiet afternoon work.",
    },
    coordinates: {
      lat: 35.787354,
      lng: -5.810295
    },
    tags: []
  }
]
