import type { SleepListing } from '../types';

export const taroudant_tafraouteSleep: SleepListing[] = [
  {
    id: 's-taroudant-riad-maryam',
    name: 'Riad Maryam',
    groupTypes: ['couple', 'solo'], type: 'riad',
    neighborhood: 'Taroudant Medina',
    city: 'taroudant_tafraoute',
    description: 'A charming, authentic family-run riad nestled inside the historic red-mud ramparts of Taroudant. Features an orange-and-lemon tree patio garden, traditional hand-carved wooden doors, rooftop mountain views, and renowned home-cooked Southern Moroccan gastronomy.',
    pricePerNight: 70,
    lifestyle: 'balanced',
    googleRating: 4.8,
    googleReviewCount: 350,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 280,
    bookingRating: 9.1,
    bookingReviewCount: 410,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 350,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    trustScores: {
      cleanliness: 9,
      safety: 10,
      staff: 10,
      value: 10,
      comfort: 9,
      location: 10
    },
    amenities: ['Free WiFi', 'Homemade Breakfast Included', 'Orange Tree Courtyard', 'Rooftop Solarium', 'Air Conditioning', 'Traditional Restaurant'],
    tip: 'Make sure to order Latifah\'s homemade dinner pastilla on arrival day.',
    vibeTags: ['Family Run', 'Orange Garden Patio', 'Authentic Southerner Hospitality', 'Gourmet Gastronomy'],
    locationSummary: 'Inside Taroudant Medina, 3 minutes walk from the central souks and Bab El Kasbah',
    availabilityText: 'High demand—book ahead for spring and autumn',
    googleMapsUrl: 'https://maps.google.com/?q=Riad+Maryam+Taroudant',
    address: 'Derb Fkih, Medina, Taroudant'
  },
  {
    id: 's-taroudant-dar-zitoune',
    name: 'Dar Zitoune',
    groupTypes: ['couple', 'solo'], type: 'hotel',
    neighborhood: 'Taroudant Countryside',
    city: 'taroudant_tafraoute',
    description: 'An eco-friendly luxury garden lodge and boutique resort surrounded by acres of ancient olive trees and bougainvillea just south of Taroudant walls. Offers spacious bungalow suites, a large heated outdoor swimming pool, a traditional spa hammam, and organic Moroccan dining.',
    pricePerNight: 140,
    lifestyle: 'premium',
    googleRating: 4.7,
    googleReviewCount: 320,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 240,
    bookingRating: 9.0,
    bookingReviewCount: 390,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 320,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    trustScores: {
      cleanliness: 10,
      safety: 10,
      staff: 10,
      value: 9,
      comfort: 10,
      location: 9
    },
    amenities: ['Large Heated Swimming Pool', 'Spa & Hammam', 'Organic Garden Restaurant', 'Free WiFi', 'Private Parking', 'Air Conditioning'],
    tip: 'Perfect peaceful retreat after exploring the bustling souks of Taroudant.',
    vibeTags: ['Olive Grove Retreat', 'Heated Pool', 'Spa Hammam', 'Eco Luxury'],
    locationSummary: 'Located 2 km south of Taroudant ramparts in a quiet agricultural oasis',
    availabilityText: 'Recommended for multi-day relaxation stays',
    googleMapsUrl: 'https://maps.google.com/?q=Dar+Zitoune+Taroudant',
    address: 'Route de Ouarzazate, BP 823, Taroudant'
  },
  {
    id: 's-tafraoute-les-amandiers',
    name: 'Hotel Les Amandiers Tafraoute',
    groupTypes: ['couple', 'solo'], type: 'hotel',
    neighborhood: 'Tafraoute Hillside',
    city: 'taroudant_tafraoute',
    description: 'A classic 4-star hilltop hotel commanding 360-degree panoramic views of Tafraoute town, almond groves, and the dramatic pink granite rock formations of the Anti-Atlas. Features an outdoor swimming pool on a sun terrace, Berber-style lounges, and traditional Moroccan dining.',
    pricePerNight: 75,
    lifestyle: 'balanced',
    googleRating: 4.3,
    googleReviewCount: 410,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 220,
    bookingRating: 8.2,
    bookingReviewCount: 480,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 410,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    trustScores: {
      cleanliness: 8,
      safety: 9,
      staff: 9,
      value: 9,
      comfort: 8,
      location: 10
    },
    amenities: ['Outdoor Swimming Pool', 'Panoramic Mountain View Terrace', 'Free WiFi', 'Free Parking', 'Restaurant & Bar', 'Air Conditioning'],
    tip: 'Sunset from the poolside terrace over the illuminated pink granite peaks is breathtaking.',
    vibeTags: ['Panoramic Mountain Views', 'Pool Terrace', 'Anti-Atlas Base', 'Almond Blossom'],
    locationSummary: 'Perched on the hill overlooking central Tafraoute, 5 minutes walk to town center',
    availabilityText: 'Peak season during February-March almond blossom festival',
    googleMapsUrl: 'https://maps.google.com/?q=Hotel+Les+Amandiers+Tafraoute',
    address: 'Place Al Massira, Tafraoute'
  },
  {
    id: 's-taroudant-palais-salam',
    name: 'Hotel Palais Salam Taroudant',
    groupTypes: ['couple', 'solo'], type: 'hotel',
    neighborhood: 'Taroudant Kasbah Ramparts',
    city: 'taroudant_tafraoute',
    description: 'A grand historic hotel built directly within the 16th-century Pasha\'s palace and fortress walls of Taroudant. Showcases sub-tropical banana and palm garden courtyards, two outdoor swimming pools, mosaic fountains, and authentic Southern Moroccan architecture.',
    pricePerNight: 90,
    lifestyle: 'balanced',
    googleRating: 4.2,
    googleReviewCount: 520,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 310,
    bookingRating: 8.0,
    bookingReviewCount: 610,
    hotelguruRating: 4.2,
    hotelguruReviewCount: 520,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    trustScores: {
      cleanliness: 8,
      safety: 9,
      staff: 8,
      value: 8,
      comfort: 8,
      location: 10
    },
    amenities: ['Two Outdoor Swimming Pools', 'Sub-tropical Palm Gardens', 'Free WiFi', 'Restaurant & Bar', 'Air Conditioning', 'Free Parking'],
    tip: 'Walk through the lush palm gardens inside the historic ramparts for a glimpse into 16th-century royal Moroccan architecture.',
    vibeTags: ['16th Century Pasha Palace', 'Sub-tropical Gardens', 'Rampart Walls', 'Historic Landmark'],
    locationSummary: 'Built directly inside Bab El Kasbah rampart gates in central Taroudant',
    availabilityText: 'Available year round',
    googleMapsUrl: 'https://maps.google.com/?q=Palais+Salam+Taroudant',
    address: 'Bab Kasbah, Taroudant'
  }
];
