import type { SleepListing } from '../types';

export const tetouan_martilSleep: SleepListing[] = [
  {
    id: 's-tetouan-riad-el-reducto',
    name: 'Riad El Reducto',
    groupTypes: ['couple', 'solo'], type: 'riad',
    neighborhood: 'Tetouan Medina (UNESCO)',
    city: 'tetouan_martil',
    description: 'A beautifully restored 19th-century Hispano-Moorish palace situated at the entrance of Tetouan\'s UNESCO-listed medina. Blending traditional zellij tilework with Spanish colonial elegance, offering a quiet central patio, a gourmet restaurant, and a rooftop terrace with sweeping views of the Rif Mountains and the royal palace.',
    pricePerNight: 85,
    lifestyle: 'balanced',
    googleRating: 4.6,
    googleReviewCount: 380,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 290,
    bookingRating: 8.9,
    bookingReviewCount: 450,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 380,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    trustScores: {
      cleanliness: 9,
      safety: 9,
      staff: 10,
      value: 9,
      comfort: 9,
      location: 10
    },
    amenities: ['Free WiFi', 'Breakfast Included', 'Rooftop Terrace', 'Air Conditioning', 'Ensuite Bathroom', 'Restaurant'],
    tip: 'Request a upper-floor suite for mountain views and optimal morning light over the medina rooftops.',
    vibeTags: ['Hispano-Moorish', 'Romantic', 'UNESCO Medina', 'Rooftop Views'],
    locationSummary: 'Located at Bab El Oukla medina entrance, 5 minutes walk from Place El Mechouar',
    availabilityText: 'Popular on weekends—book 2 weeks in advance',
    googleMapsUrl: 'https://maps.google.com/?q=Riad+El+Reducto+Tetouan',
    address: '27 Rue Zaouia Kadiria, Medina, Tetouan'
  },
  {
    id: 's-tetouan-hotel-blanco-riad',
    name: 'Hotel Blanco Riad',
    groupTypes: ['couple', 'solo'], type: 'riad',
    neighborhood: 'Tetouan Medina',
    city: 'tetouan_martil',
    description: 'A luxurious boutique hotel housed in a historic 19th-century building that formerly served as the Spanish Consulate. Features an exquisite marble courtyard fountain, elegant rooms with carved cedarwood and Andalusian tiles, a peaceful garden patio, and one of Tetouan\'s finest restaurants.',
    pricePerNight: 110,
    lifestyle: 'premium',
    googleRating: 4.7,
    googleReviewCount: 420,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 310,
    bookingRating: 9.1,
    bookingReviewCount: 520,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 420,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    trustScores: {
      cleanliness: 10,
      safety: 10,
      staff: 10,
      value: 9,
      comfort: 10,
      location: 10
    },
    amenities: ['Free High-Speed WiFi', 'Gourmet Breakfast', 'Garden Patio', 'Rooftop Terrace', 'Air Conditioning', 'Fine Dining Restaurant'],
    tip: 'Dine at the courtyard restaurant in the evening for an unbeatable candlelit Andalusian atmosphere.',
    vibeTags: ['Boutique Luxury', 'Historical Consulate', 'Garden Courtyard', 'Fine Dining'],
    locationSummary: 'In the heart of Tetouan Medina, 2 minutes from Plaza Primo and royal palace',
    availabilityText: 'High demand during spring and summer',
    googleMapsUrl: 'https://maps.google.com/?q=Hotel+Blanco+Riad+Tetouan',
    address: '25 Rue Del Consulado, Medina, Tetouan'
  },
  {
    id: 's-tetouan-riad-benyara',
    name: 'Riad Benyara',
    groupTypes: ['couple', 'solo'], type: 'riad',
    neighborhood: 'Tetouan Medina',
    city: 'tetouan_martil',
    description: 'A serene and authentic traditional Moroccan riad located inside the whitewashed alleyways of Tetouan. Boasts a courtyard plunge pool, beautifully appointed air-conditioned suites, handcrafted artisan decor, and a friendly host family that serves freshly baked Moroccan bread and pancakes each morning.',
    pricePerNight: 65,
    lifestyle: 'balanced',
    googleRating: 4.8,
    googleReviewCount: 190,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 120,
    bookingRating: 9.2,
    bookingReviewCount: 280,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 190,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: true,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    trustScores: {
      cleanliness: 9,
      safety: 9,
      staff: 10,
      value: 10,
      comfort: 9,
      location: 9
    },
    amenities: ['Plunge Pool', 'Free WiFi', 'Homemade Breakfast', 'Rooftop Solarium', 'Air Conditioning'],
    tip: 'The plunge pool in the central courtyard is refreshing after a warm afternoon exploring the artisan souks.',
    vibeTags: ['Plunge Pool', 'Authentic Hospitality', 'Quiet Oasis', 'Value Luxury'],
    locationSummary: 'Tucked away in a quiet residential alley inside Tetouan Medina',
    availabilityText: 'Available most dates',
    googleMapsUrl: 'https://maps.google.com/?q=Riad+Benyara+Tetouan',
    address: 'Derb Benyara, Medina, Tetouan'
  },
  {
    id: 's-martil-riad-salt-river',
    name: 'Riad Salt River Martil',
    groupTypes: ['couple', 'solo'], type: 'apartment',
    neighborhood: 'Martil Beachfront',
    city: 'tetouan_martil',
    description: 'A modern coastal residence and apartment riad situated near the Mediterranean beach promenade in Martil. Featuring air-conditioned suites with private balconies, garden access, a shared indoor pool, and quick access to Martil\'s lively seafood restaurants and sandy beach.',
    pricePerNight: 55,
    lifestyle: 'lean',
    googleRating: 4.3,
    googleReviewCount: 210,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 85,
    bookingRating: 8.3,
    bookingReviewCount: 310,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 210,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: false,
    hasBar: false,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: true,
    nearMosque: true,
    safetyLevel: 4,
    trustScores: {
      cleanliness: 8,
      safety: 8,
      staff: 9,
      value: 9,
      comfort: 8,
      location: 9
    },
    amenities: ['Indoor Swimming Pool', 'Free WiFi', 'Balcony Sea Views', 'Air Conditioning', 'Kitchenette'],
    tip: 'Ideal for families or groups seeking beach proximity and self-catering flexibility near Martil corniche.',
    vibeTags: ['Beachfront Access', 'Family Friendly', 'Apartment Suites', 'Coastal Breeze'],
    locationSummary: '1.5 km from Martil city center and 300 meters from Martil Beach',
    availabilityText: 'Peak summer availability fills early',
    googleMapsUrl: 'https://maps.google.com/?q=Riad+Salt+River+Martil',
    address: 'Avenue Oued Laou, Martil'
  }
];
