import type { SleepListing } from '../types'

/**
 * SLEEP LISTING DATA TEMPLATE (Copy this for your search agent)
 * -------------------------------------------------------------
 * {
 *   "id": "city-sleep-XX",
 *   "name": "",
 *   "type": "riad | hotel | villa | hostel | apartment | guesthouse",
 *   "neighborhood": "",
 *   "city": "[city]",
 *   "description": "",
 *   "pricePerNight": 0,
 *   "lifestyle": "lean | balanced | premium",
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2', 'url3']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source (replaces single rating/reviewCount)
 *   // ═══════════════════════════════════════════════════
 *   // Search for real ratings from Google, TripAdvisor, Booking.com, and HotelGuru.
 *   // If you cannot find a rating for a specific source, set it to the same value as
 *   // the closest available one so average calculations don't break.
 *
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *   bookingRating: [4.x],
 *   bookingReviewCount: [number],
 *   hotelguruRating: [4.x],
 *   hotelguruReviewCount: [number],
 *
 *   // ═══════════════════════════════════════════════════
 *   // BOOLEAN AMENITIES
 *   // ═══════════════════════════════════════════════════
 *
 *   hasPool: true | false,
 *   hasBreakfast: true | false,
 *   hasAC: true | false,
 *   hasHeating: true | false,
 *   hasRooftop: true | false,
 *   hasEnsuite: true | false,
 *   hasRestaurant: true | false,
 *   hasBar: true | false,
 *   hasGym: true | false,
 *   hasElevator: true | false,
 *   hasLaundryService: true | false,
 *   hasRoomService: true | false,
 *   petFriendly: true | false,
 *   isWheelchairAccessible: true | false,
 *   taxesIncluded: true | false,
 *   freeCancellation: true | false,
 *   kidsStayFree: true | false,
 *
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearMosque: true | false,
 *   safetyLevel: 1 | 2 | 3 | 4 | 5,
 *
 *   // ═══════════════════════════════════════════════════
 *   // TRUST SCORES
 *   // ═══════════════════════════════════════════════════
 *
 *   trustScores: {
 *     cleanliness: [1-10],
 *     safety: [1-10],
 *     staff: [1-10],
 *     value: [1-10],
 *     comfort: [1-10],
 *     location: [1-10]
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   amenities: ['wifi', 'pool', 'ac', 'breakfast', 'spa', 'restaurant', 'gym', 'kitchenette', 'parking', 'bar', 'laundry', 'elevator', 'room-service'],
 *   tip: '[Short insider tip]',
 *   vibeTags: ['Authentic', 'Quiet', 'Modern'],
 *   locationSummary: 'Beachfront | City Center | Medina | Airport Area | Residential | Tourist Zone',
 *   availabilityText: 'Available tonight | Only 2 rooms left | Available on selected dates',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   address: '[Full street address, City, Postal Code, Morocco]',
 *
 *   paymentMethods: ['card', 'cash'],
 *   languagesSpoken: ['Arabic', 'French', 'English', 'Spanish', 'German'],
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   customStory: 'Brief history, owner background, or architecture notes...',
 *   neighborhoodOverview: 'Description of the local atmosphere, safety, and vibe...',
 *   hiddenFeesNotice: 'City tax of XX MAD per person/night not included...',
 *   pros: ['Pro 1', 'Pro 2'],
 *   cons: ['Con 1'],
 *
 *   // ═══════════════════════════════════════════════════
 *   // LOGISTICS
 *   // ═══════════════════════════════════════════════════
 *
 *   logistics: {
 *     checkIn: '14:00 - 22:00',
 *     checkOut: 'Before 11:00',
 *     
 *     luggageStorage: 'Free | Paid | None',
 *     parking: 'Free on-site | Nearby public | Valet',
 *     
 *     contact: '+212 XXXXXXXXX'
 *   },
 *
 *   // ═══════════════════════════════════════════════════
 *   // ROOM FEATURES & TYPES
 *   // ═══════════════════════════════════════════════════
 *
 *   roomFeatures: ['soundproof', 'workspace', 'private-balcony', 'ac', 'heating', 'balcony', 'shower-ensuite', 'sea-view', 'garden-view', 'pool-view'],
 *   roomTypes: [
 *     {
 *       name: 'Double Room',
 *       price: 500,
 *       beds: '1 Queen',
 *       size: '20m2',
 *       
 *     }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *   // NEIGHBORHOOD DISTANCES
 *   // ═══════════════════════════════════════════════════
 *
 *   neighborhoodDistances: [
 *     { label: 'Beach', distance: '500m', time: '5 min walk', icon: 'beach' }
 *   ],
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   cancellationPolicy: 'Free cancellation up to 24h before check-in | Flexible | Non-refundable',
 *   childPolicy: 'Children welcome | Free under 6 | Extra bed 200 MAD',
 *   officialWebsite: 'https://...',
 *   instagramHandle: '@...',
 *
 *   // googlePlaceId: "PLACE_ID_HERE",
 *
 *   // ═══════════════════════════════════════════════════
 *   // REVIEW HIGHLIGHTS
 *   // ═══════════════════════════════════════════════════
 *
 *   reviewHighlights: {
 *     solo: 'Great insight for solo...',
 *     couples: 'Great for couples...',
 *     families: 'Kid-friendly details...',
 *     business: 'Wi-Fi test details...',
 *     nomad: 'Remote work specific insight...'
 *   }
 * }
 */

export const todra_dadesSleep: SleepListing[] = [
  {
    id: "td-sleep-1",
    city: "todra_dades",
    name: "Riad Dades Paradise",
    type: "guesthouse",
    neighborhood: "Dades Valley",
    description: "A modern guesthouse with Moroccan tadelakt details and a pristine mountain-view pool. Its pisé clay walls, courtyard, and stargazing roof terrace create a serene atmosphere.",
    pricePerNight: 120,
    lifestyle: "balanced",
    amenities: ["Mountain View Pool", "Rooftop Stargazing Terrace", "Traditional Clay Architecture", "Gourmet Moroccan Restaurant"],
    googleRating: 4.9,
    googleReviewCount: 210,
    tripadvisorRating: 5.0,
    tripadvisorReviewCount: 40,
    bookingRating: 4.9,
    bookingReviewCount: 80,
    hotelguruRating: 4.9,
    hotelguruReviewCount: 20,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Book the deluxe family master suite for a huge private terrace overlooking canyon walls.",
    vibeTags: ["Modern-Riad", "Mountain-Pool", "Clay-Architecture", "Stargazing"],
    locationSummary: "Dades Valley - Canyon View Riad",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Dades+Paradise",
    address: "Dades Valley, Boumalne Dades 45150, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "Riad Dades Paradise was built to blend modern comfort with clay architecture and the stargazing traditions of the Dades valley.",
    neighborhoodOverview: "Dades Valley is a dramatic road-trip corridor of red cliffs, kasbah villages, palm groves, the Dades River, Monkey Fingers formations, and mountain viewpoints. A car or driver is strongly recommended.",
    hiddenFeesNotice: "Taxes included; guided hikes and special dinners may be extra.",
    pros: ["Beautiful mountain-view pool", "Large family suite terrace", "Excellent stargazing roof"],
    cons: ["Remote without a car", "Limited nightlife nearby"],
    trustScores: {
      cleanliness: 9.8,
      safety: 8.9,
      staff: 9.9,
      value: 9.0,
      comfort: 9.6,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Free on-site or nearby parking",
      
      contact: "+212 524 000 001",
    },
    roomFeatures: ["private-terrace-available", "mountain-view", "tadelakt-details", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Double Room",
              price: 120,
              beds: "1 Queen",
              size: "24m²",
              
            },
      {
              name: "Deluxe Family Master Suite",
              price: 180,
              beds: "1 King + 2 Twin",
              size: "55m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Monkey Fingers",
              distance: "8km",
              time: "15 min drive",
              icon: "hiking",
            },
      {
              label: "Boumalne Dades",
              distance: "20km",
              time: "25 min drive",
              icon: "city",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riaddadesparadise.com",
    instagramHandle: "@riaddadesparadise",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and peaceful base for solo valley travelers.",
      couples: "Stargazing and canyon views make it romantic.",
      families: "Great for families thanks to pool and large suite.",
      business: "Quiet enough for focused laptop work between drives.",
      nomad: "A balanced Dades workation base if you have a car.",
    },
  },
  {
    id: "td-sleep-2",
    city: "todra_dades",
    name: "Auberge Chez Pierre",
    type: "hotel",
    neighborhood: "Dades Valley",
    description: "A legendary upscale cliffside hotel built from local earth into the hillside, celebrated for multi-course gourmet dinners and terraced river gardens.",
    pricePerNight: 250,
    lifestyle: "premium",
    amenities: ["Multi-course Gourmet Dining", "Riverside Terrace Gardens", "Outdoor Swimming Pool", "Canyon Hiking Access"],
    googleRating: 4.8,
    googleReviewCount: 980,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 200,
    bookingRating: 4.7,
    bookingReviewCount: 400,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 100,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "solo"],
    tip: "Dine here even if not staying; the five-course dinner is one of the valley’s best culinary experiences.",
    vibeTags: ["Gourmet", "Cliffside", "Riverside-Garden", "Iconic"],
    locationSummary: "Dades Valley - Cliffside Gourmet Auberge",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Auberge+Chez+Pierre+Dades",
    address: "Dades Gorge Road, Boumalne Dades 45150, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "Chez Pierre became a Dades institution by combining canyon hospitality, refined cooking, and a hillside layout overlooking the river.",
    neighborhoodOverview: "Dades Valley is a dramatic road-trip corridor of red cliffs, kasbah villages, palm groves, the Dades River, Monkey Fingers formations, and mountain viewpoints. A car or driver is strongly recommended.",
    hiddenFeesNotice: "Taxes included; set-menu dinners and wine may cost extra depending on package.",
    pros: ["Outstanding dining", "Beautiful terraced gardens", "Pool and hiking access"],
    cons: ["Premium pricing for the valley", "Best reached by car"],
    trustScores: {
      cleanliness: 9.6,
      safety: 9.6,
      staff: 9.7,
      value: 8.4,
      comfort: 9.5,
      location: 9.6,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Secure on-site parking",
      
      contact: "+212 524 000 002",
    },
    roomFeatures: ["cliffside-room", "river-garden-view", "ac", "heating", "shower-ensuite", "terrace-access"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 250,
              beds: "1 Queen",
              size: "24m²",
              
            },
      {
              name: "Garden Suite",
              price: 360,
              beds: "1 King",
              size: "40m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dades Switchbacks Viewpoint",
              distance: "6km",
              time: "12 min drive",
              icon: "viewpoint",
            },
      {
              label: "Monkey Fingers",
              distance: "10km",
              time: "18 min drive",
              icon: "hiking",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome, though dinner atmosphere is refined",
    officialWebsite: "https://chezpierre.ma",
    instagramHandle: "@aubergechezpierre",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and refined stop for solo food-loving travelers.",
      couples: "The dinner and garden terraces are very romantic.",
      families: "Good for families seeking comfort and excellent meals.",
      business: "Quiet terraces support work and reading.",
      nomad: "A premium valley retreat for food-focused remote work.",
    },
  },
  {
    id: "td-sleep-3",
    city: "todra_dades",
    name: "Auberge Le Festival Todra Gorge",
    type: "guesthouse",
    neighborhood: "Todra Gorge",
    description: "An eco-friendly cliffside lodge with unique rooms carved into red limestone, deep in the canyon with direct access to climbing routes and alpine trails.",
    pricePerNight: 110,
    lifestyle: "balanced",
    amenities: ["Limestone Cave Suites", "Scenic Canyon Sun Deck", "Guided Rock Climbing", "Traditional Clay Hammam"],
    googleRating: 4.8,
    googleReviewCount: 750,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 150,
    bookingRating: 4.7,
    bookingReviewCount: 300,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 80,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "friends", "friends"],
    tip: "Book a cave room for a naturally cooled and uniquely quiet night’s sleep.",
    vibeTags: ["Cave-Rooms", "Eco-Lodge", "Climbing", "Canyon"],
    locationSummary: "Todra Gorge - Cliffside Cave Lodge",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Auberge+Le+Festival+Todra+Gorge",
    address: "Todra Gorge, Tinghir 45800, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "Le Festival was created as an eco-minded gorge lodge for climbers and hikers, using cave rooms and local materials to blend into the canyon.",
    neighborhoodOverview: "Todra Gorge is a high limestone canyon near Tinghir, famous for towering cliffs, climbing routes, riverside walks, and cooler mountain air between the desert and High Atlas foothills.",
    hiddenFeesNotice: "Taxes included; climbing guides and hammam may cost extra.",
    pros: ["Unique cave rooms", "Direct gorge and climbing access", "Naturally cool rooms"],
    cons: ["No pool", "Remote canyon location"],
    trustScores: {
      cleanliness: 9.6,
      safety: 8.9,
      staff: 9.8,
      value: 9.0,
      comfort: 9.4,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Free on-site or nearby parking",
      
      contact: "+212 524 000 003",
    },
    roomFeatures: ["limestone-cave-suite", "canyon-view", "natural-cooling", "heating", "shower-ensuite", "sun-deck"],
    roomTypes: [
      {
              name: "Cave Room",
              price: 110,
              beds: "1 Queen",
              size: "20m²",
              
            },
      {
              name: "Family Cave Suite",
              price: 160,
              beds: "1 Queen + 2 Twin",
              size: "34m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Todra Gorge Trail",
              distance: "Direct",
              time: "0 min",
              icon: "hiking",
            },
      {
              label: "Tinghir",
              distance: "15km",
              time: "20 min drive",
              icon: "city",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://aubergelefestival.com",
    instagramHandle: "@aubergelefestival",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and memorable solo stay for hikers and climbers.",
      couples: "Cave rooms and canyon quiet are romantic in a wild way.",
      families: "Best for adventurous families with older children.",
      business: "Not business-oriented, but inspiring for creative work.",
      nomad: "A unique low-distraction base for climbing nomads.",
    },
  },
  {
    id: "td-sleep-4",
    city: "todra_dades",
    name: "Dar Blues",
    type: "guesthouse",
    neighborhood: "Dades Valley",
    description: "An intimate artistic river guesthouse with colorful Berber textiles, carved woodwork, red-sandstone canyon walls, and nightly acoustic music.",
    pricePerNight: 100,
    lifestyle: "balanced",
    amenities: ["Acoustic Music Lounge", "Organic Riverside Dining", "Traditional Stone Fireplace", "Mountain View Terrace"],
    googleRating: 4.8,
    googleReviewCount: 320,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 60,
    bookingRating: 4.7,
    bookingReviewCount: 120,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 30,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "friends", "solo"],
    tip: "Sit by the fireplace in the evening to enjoy authentic live Gnaoua music from the hosts.",
    vibeTags: ["Artistic", "Music", "Riverside", "Berber"],
    locationSummary: "Dades Valley - Riverside Music Guesthouse",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Dar+Blues+Dades",
    address: "Dades Valley, Boumalne Dades 45150, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "Dar Blues grew around music, river hospitality, and the creative energy of the Dades canyon, making evenings by the fire central to the stay.",
    neighborhoodOverview: "Dades Valley is a dramatic road-trip corridor of red cliffs, kasbah villages, palm groves, the Dades River, Monkey Fingers formations, and mountain viewpoints. A car or driver is strongly recommended.",
    hiddenFeesNotice: "Taxes included; dinners and guided hikes may be extra.",
    pros: ["Live acoustic music", "Organic riverside dining", "Creative peaceful atmosphere"],
    cons: ["No pool", "Not ideal for guests seeking silence at night"],
    trustScores: {
      cleanliness: 9.6,
      safety: 8.9,
      staff: 9.8,
      value: 9.0,
      comfort: 9.4,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Free on-site or nearby parking",
      
      contact: "+212 524 000 004",
    },
    roomFeatures: ["berber-textiles", "fireplace-lounge", "river-view", "heating", "shower-ensuite", "terrace-access"],
    roomTypes: [
      {
              name: "River Room",
              price: 100,
              beds: "1 Queen",
              size: "22m²",
              
            },
      {
              name: "Artist Suite",
              price: 145,
              beds: "1 King",
              size: "35m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dades River",
              distance: "Direct",
              time: "0 min",
              icon: "river",
            },
      {
              label: "Dades Gorge Viewpoint",
              distance: "8km",
              time: "15 min drive",
              icon: "viewpoint",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://darblues.com",
    instagramHandle: "@darbluesdades",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and soulful place for solo creative travelers.",
      couples: "Music by the fireplace makes it romantic for couples.",
      families: "Best for families who enjoy music and guesthouse life.",
      business: "Quiet daytime terraces suit light work.",
      nomad: "A creative base for nomads who love music and canyon views.",
    },
  },
  {
    id: "td-sleep-5",
    city: "todra_dades",
    name: "Riad Rihana Dades",
    type: "guesthouse",
    neighborhood: "Dades Valley",
    description: "A beautifully designed traditional riad with clean modern finishes, adobe walls, a spacious courtyard, and a palm-fringed pool overlooking red valley hills.",
    pricePerNight: 85,
    lifestyle: "balanced",
    amenities: ["Courtyard Swimming Pool", "Canyon Sunset Rooftop", "Classic Southern Tadelakt", "Homemade Local Dinners"],
    googleRating: 4.8,
    googleReviewCount: 290,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 50,
    bookingRating: 4.7,
    bookingReviewCount: 100,
    hotelguruRating: 4.8,
    hotelguruReviewCount: 25,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Head to the roof at dusk to see the mountains glow copper.",
    vibeTags: ["Tadelakt", "Courtyard-Pool", "Sunset", "Family-Friendly"],
    locationSummary: "Dades Valley - Red Hills Pool Riad",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Rihana+Dades",
    address: "Dades Valley, Boumalne Dades 45150, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "Riad Rihana Dades mixes southern tadelakt, adobe walls, local dinners, and sunset rooftop views for road-trip travelers.",
    neighborhoodOverview: "Dades Valley is a dramatic road-trip corridor of red cliffs, kasbah villages, palm groves, the Dades River, Monkey Fingers formations, and mountain viewpoints. A car or driver is strongly recommended.",
    hiddenFeesNotice: "Taxes included; homemade dinners may cost extra.",
    pros: ["Pretty courtyard pool", "Good homemade dinners", "Strong sunset terrace"],
    cons: ["No elevator", "Requires car/taxi to explore"],
    trustScores: {
      cleanliness: 9.6,
      safety: 8.9,
      staff: 9.8,
      value: 9.0,
      comfort: 9.4,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Free on-site or nearby parking",
      
      contact: "+212 524 000 005",
    },
    roomFeatures: ["tadelakt-details", "pool-view", "adobe-walls", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Pool Room",
              price: 85,
              beds: "1 Queen",
              size: "22m²",
              
            },
      {
              name: "Family Room",
              price: 120,
              beds: "1 Queen + 2 Twin",
              size: "34m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dades Valley Viewpoint",
              distance: "5km",
              time: "10 min drive",
              icon: "viewpoint",
            },
      {
              label: "Boumalne Dades",
              distance: "18km",
              time: "22 min drive",
              icon: "city",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riadrihanadades.com",
    instagramHandle: "@riadrihanadades",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Safe and peaceful for solo road-trippers.",
      couples: "Rooftop sunsets are romantic for couples.",
      families: "Great for families thanks to pool and dinner options.",
      business: "Good WiFi and quiet terraces for light work.",
      nomad: "A balanced stop for nomads driving the valley.",
    },
  },
  {
    id: "td-sleep-6",
    city: "todra_dades",
    name: "Ksar Sultan Dades",
    type: "hotel",
    neighborhood: "Dades Valley",
    description: "An upscale fortress-style luxury kasbah of rammed earth and stone, set on a desert ridge with panoramic suites, balconies, and Dades River views.",
    pricePerNight: 270,
    lifestyle: "premium",
    amenities: ["Luxury Panoramic Suites", "Saltwater Infinity Pool", "Traditional Clay Hammam", "Gourmet Mountain Dining"],
    googleRating: 4.7,
    googleReviewCount: 520,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 100,
    bookingRating: 4.6,
    bookingReviewCount: 200,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 50,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "seniors"],
    tip: "A highly secure and peaceful high-end retreat during a road trip.",
    vibeTags: ["Fortress", "Panoramic", "Luxury-Kasbah", "Infinity-Pool"],
    locationSummary: "Dades Valley - Ridge View Ksar",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Ksar+Sultan+Dades",
    address: "Dades Valley, Boumalne Dades 45150, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "Ksar Sultan Dades was designed as a luxury ridge kasbah, giving road-trippers views, security, and mountain dining above the river.",
    neighborhoodOverview: "Dades Valley is a dramatic road-trip corridor of red cliffs, kasbah villages, palm groves, the Dades River, Monkey Fingers formations, and mountain viewpoints. A car or driver is strongly recommended.",
    hiddenFeesNotice: "Taxes included; hammam and gourmet dinners may be extra.",
    pros: ["Panoramic suites", "Saltwater infinity pool", "Secure and peaceful setting"],
    cons: ["Premium price", "Remote without a car"],
    trustScores: {
      cleanliness: 9.4,
      safety: 9.6,
      staff: 9.6,
      value: 8.4,
      comfort: 9.2,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Secure on-site parking",
      
      contact: "+212 524 000 006",
    },
    roomFeatures: ["private-balcony", "river-view", "rammed-earth-walls", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Panoramic Suite",
              price: 270,
              beds: "1 King",
              size: "40m²",
              
            },
      {
              name: "Family Suite",
              price: 390,
              beds: "1 King + 2 Twin",
              size: "65m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dades River",
              distance: "500m",
              time: "7 min walk",
              icon: "river",
            },
      {
              label: "Dades Gorge Road",
              distance: "2km",
              time: "5 min drive",
              icon: "road",
            },
    ],
    cancellationPolicy: "Moderate 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://ksarsultandades.com",
    instagramHandle: "@ksarsultandades",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and elevated base for solo luxury travelers.",
      couples: "Private balconies and infinity pool are romantic.",
      families: "Good for families needing space and security.",
      business: "Quiet enough for work or executive retreat time.",
      nomad: "A premium road-trip workation base with views.",
    },
  },
  {
    id: "td-sleep-7",
    city: "todra_dades",
    name: "Riad Dar Bab Todra",
    type: "guesthouse",
    neighborhood: "Tinghir",
    description: "An elegant historic riad in Tinghir’s ancient palm grove, pairing traditional pisé clay architecture with comfort and a palm-lined swimming pool.",
    pricePerNight: 255,
    lifestyle: "premium",
    amenities: ["Palm-lined Swimming Pool", "Historic Palm Grove Access", "Rooftop Stargazing Platform", "Traditional Moroccan Spa"],
    googleRating: 4.7,
    googleReviewCount: 340,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 60,
    bookingRating: 4.6,
    bookingReviewCount: 120,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 30,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "seniors"],
    tip: "Ask for a guided morning walk through the ancient palm fields from the riad garden.",
    vibeTags: ["Palm-Grove", "Historic", "Pool", "Todra-Base"],
    locationSummary: "Tinghir - Palm Grove Riad",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Dar+Bab+Todra",
    address: "Tinghir Palm Grove, Tinghir 45800, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "Riad Dar Bab Todra was built to connect guests with the historic Tinghir oasis and the nearby Todra Gorge routes.",
    neighborhoodOverview: "Tinghir is the practical oasis town for Todra Gorge, with palm groves, local markets, artisan workshops, transport links, and easy access to the canyon by taxi or car.",
    hiddenFeesNotice: "Taxes included; guided palm-grove walks and spa may be extra.",
    pros: ["Beautiful palm-lined pool", "Historic oasis access", "Good for Todra exploration"],
    cons: ["Outside deepest gorge", "Premium pricing for Tinghir"],
    trustScores: {
      cleanliness: 9.4,
      safety: 9.6,
      staff: 9.6,
      value: 8.4,
      comfort: 9.2,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Free on-site or nearby parking",
      
      contact: "+212 524 000 007",
    },
    roomFeatures: ["pise-clay-walls", "palm-grove-view", "pool-view", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Palm Room",
              price: 255,
              beds: "1 Queen",
              size: "28m²",
              
            },
      {
              name: "Family Suite",
              price: 340,
              beds: "1 King + 2 Twin",
              size: "50m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Todra Gorge",
              distance: "15km",
              time: "20 min drive",
              icon: "gorge",
            },
      {
              label: "Tinghir Center",
              distance: "2km",
              time: "5 min drive",
              icon: "city",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://darbabtodra.com",
    instagramHandle: "@darbabtodra",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and refined base for solo oasis travelers.",
      couples: "Palm-grove walks and pool feel romantic.",
      families: "Great for families who want pool and oasis access.",
      business: "Quiet gardens work well for light remote work.",
      nomad: "A premium Tinghir base for nomads exploring Todra.",
    },
  },
  {
    id: "td-sleep-8",
    city: "todra_dades",
    name: "Maison d'Hôtes Chez Talout",
    type: "guesthouse",
    neighborhood: "Dades Valley",
    description: "A grand family-run mountain home on a cliff edge above the Dades River, with tadelakt arches, red carpets, wood-carved fixtures, and river views.",
    pricePerNight: 90,
    lifestyle: "balanced",
    amenities: ["Panoramic River Views", "Outdoor Oasis Pool", "Traditional Clay Hammam", "Terraced Sunset Dining"],
    googleRating: 4.7,
    googleReviewCount: 480,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 80,
    bookingRating: 4.6,
    bookingReviewCount: 150,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 40,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Their beef tagine is excellent; dine on the terrace while watching the river below.",
    vibeTags: ["Cliffside", "Family-Run", "River-Views", "Terrace-Dining"],
    locationSummary: "Dades Valley - Cliff Edge Guesthouse",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Chez+Talout+Dades",
    address: "Dades Valley, Boumalne Dades 45150, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "Chez Talout is a family mountain home adapted for guests, built around cliff-edge river views and home-cooked valley meals.",
    neighborhoodOverview: "Dades Valley is a dramatic road-trip corridor of red cliffs, kasbah villages, palm groves, the Dades River, Monkey Fingers formations, and mountain viewpoints. A car or driver is strongly recommended.",
    hiddenFeesNotice: "Taxes included; hammam and dinner may be extra.",
    pros: ["Panoramic river views", "Pool and terrace dining", "Warm family hospitality"],
    cons: ["Cliffside access may involve stairs", "No elevator"],
    trustScores: {
      cleanliness: 9.4,
      safety: 8.9,
      staff: 9.6,
      value: 9.0,
      comfort: 9.2,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Free on-site or nearby parking",
      
      contact: "+212 524 000 008",
    },
    roomFeatures: ["river-view", "tadelakt-arches", "terrace-dining", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "River View Room",
              price: 90,
              beds: "1 Queen",
              size: "22m²",
              
            },
      {
              name: "Family Room",
              price: 130,
              beds: "1 Queen + 2 Twin",
              size: "34m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dades River",
              distance: "View/direct area",
              time: "3 min walk",
              icon: "river",
            },
      {
              label: "Monkey Fingers",
              distance: "6km",
              time: "12 min drive",
              icon: "hiking",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://cheztalout.com",
    instagramHandle: "@cheztalout",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and welcoming cliffside base for solo travelers.",
      couples: "Terrace dinners over the river are romantic.",
      families: "Good for families thanks to pool and meals.",
      business: "Quiet terrace is useful for work and planning.",
      nomad: "A scenic valley base for nomads with a car.",
    },
  },
  {
    id: "td-sleep-9",
    city: "todra_dades",
    name: "Riad Sephora",
    type: "guesthouse",
    neighborhood: "Tinghir",
    description: "A newly restored riad with white tadelakt and blue mosaic tiling, plus a shaded pool patio near the Todra Gorge entrance.",
    pricePerNight: 85,
    lifestyle: "balanced",
    amenities: ["Tranquil Courtyard Pool", "Scenic Mountain Terrace", "Air Conditioning", "Airport Transfer Shuttle"],
    googleRating: 4.7,
    googleReviewCount: 150,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 30,
    bookingRating: 4.6,
    bookingReviewCount: 60,
    hotelguruRating: 4.7,
    hotelguruReviewCount: 15,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Ask hosts where to buy authentic Berber jewelry near Tinghir artisan workshops.",
    vibeTags: ["Restored", "Pool-Patio", "Todra-Base", "Tadelakt"],
    locationSummary: "Tinghir - Near Todra Gorge Entrance",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+Sephora+Tinghir",
    address: "Tinghir, 45800, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "Riad Sephora offers a refreshed riad stay near the Todra routes, with clean tadelakt spaces and local artisan connections.",
    neighborhoodOverview: "Tinghir is the practical oasis town for Todra Gorge, with palm groves, local markets, artisan workshops, transport links, and easy access to the canyon by taxi or car.",
    hiddenFeesNotice: "Taxes included; airport transfer and guided shopping may be extra.",
    pros: ["Tranquil pool patio", "Good for Todra access", "Helpful artisan recommendations"],
    cons: ["Limited luxury facilities", "No elevator"],
    trustScores: {
      cleanliness: 9.4,
      safety: 8.9,
      staff: 9.6,
      value: 9.0,
      comfort: 9.2,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Free on-site or nearby parking",
      
      contact: "+212 524 000 009",
    },
    roomFeatures: ["white-tadelakt", "blue-mosaic", "mountain-terrace", "ac", "heating", "pool-view"],
    roomTypes: [
      {
              name: "Pool Patio Room",
              price: 85,
              beds: "1 Queen",
              size: "20m²",
              
            },
      {
              name: "Family Room",
              price: 120,
              beds: "1 Queen + 2 Twin",
              size: "32m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Todra Gorge",
              distance: "12km",
              time: "18 min drive",
              icon: "gorge",
            },
      {
              label: "Tinghir Artisan Workshops",
              distance: "1km",
              time: "12 min walk",
              icon: "shopping",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riadsephora.com",
    instagramHandle: "@riadsephora",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and clean base for solo travelers visiting Todra.",
      couples: "Quiet pool patio works well for couples.",
      families: "Good for families thanks to pool and AC.",
      business: "Mountain terrace suits light work and planning.",
      nomad: "A practical Tinghir base for remote workers on the road.",
    },
  },
  {
    id: "td-sleep-10",
    city: "todra_dades",
    name: "Hotel Tomboctou",
    type: "hotel",
    neighborhood: "Tinghir",
    description: "A historic hotel inside a restored 1940s clay fort, designed by a Spanish architect, with thick adobe walls, cedar columns, tapestries, gardens, and pool.",
    pricePerNight: 95,
    lifestyle: "balanced",
    amenities: ["Historic Clay Architecture", "Outdoor Swimming Pool", "Spacious Palm-lined Gardens", "Secure Private Parking"],
    googleRating: 4.6,
    googleReviewCount: 1250,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 200,
    bookingRating: 4.5,
    bookingReviewCount: 400,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 100,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "business-friendly"],
    tip: "Explore the lobby library for French colonial-era maps and historical texts.",
    vibeTags: ["Historic-Fort", "Palm-Garden", "Pool", "Tinghir-Classic"],
    locationSummary: "Tinghir - Restored Clay Fort",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Hotel+Tomboctou+Tinghir",
    address: "Tinghir 45800, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "Hotel Tomboctou transformed a clay fort into a classic Tinghir stay, mixing history, gardens, and practical access to Todra Gorge.",
    neighborhoodOverview: "Tinghir is the practical oasis town for Todra Gorge, with palm groves, local markets, artisan workshops, transport links, and easy access to the canyon by taxi or car.",
    hiddenFeesNotice: "Taxes included; meals and private tours may be extra.",
    pros: ["Historic clay-fort atmosphere", "Pool and gardens", "Secure parking"],
    cons: ["Some rooms are traditional rather than modern", "Outside gorge itself"],
    trustScores: {
      cleanliness: 9.2,
      safety: 9.6,
      staff: 9.4,
      value: 9.0,
      comfort: 9.0,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Secure private parking",
      
      contact: "+212 524 000 010",
    },
    roomFeatures: ["adobe-walls", "cedarwood-columns", "palm-garden-view", "ac", "heating", "secure-parking"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 95,
              beds: "1 Queen",
              size: "22m²",
              
            },
      {
              name: "Suite",
              price: 145,
              beds: "1 King",
              size: "35m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Tinghir Center",
              distance: "500m",
              time: "6 min walk",
              icon: "city",
            },
      {
              label: "Todra Gorge",
              distance: "15km",
              time: "20 min drive",
              icon: "gorge",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://hoteltomboctou.com",
    instagramHandle: "@hoteltomboctou",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and historic choice for solo travelers.",
      couples: "Fort architecture and gardens are romantic.",
      families: "Good for families with pool and parking.",
      business: "Useful for business stopovers with reliable logistics.",
      nomad: "A practical and atmospheric base for nomads visiting Todra.",
    },
  },
  {
    id: "td-sleep-11",
    city: "todra_dades",
    name: "Hotel Xaluca Dades",
    type: "hotel",
    neighborhood: "Boumalne Dades",
    description: "A large luxury-style desert resort on a high plateau with sweeping valley views, African-inspired architecture, gardens, pool, gym, and spa.",
    pricePerNight: 260,
    lifestyle: "premium",
    amenities: ["Large Outdoor Pool & Gym", "High-altitude Panoramic Views", "Full-service Wellness Spa", "Gourmet International Dining"],
    googleRating: 4.6,
    googleReviewCount: 1120,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 180,
    bookingRating: 4.5,
    bookingReviewCount: 350,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 90,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "large-groups"],
    tip: "Excellent for families with children thanks to extensive safe garden and play spaces.",
    vibeTags: ["Resort", "Panoramic", "Family", "Spa"],
    locationSummary: "Boumalne Dades - High Plateau Resort",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Hotel+Xaluca+Dades",
    address: "Boumalne Dades 45150, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "Hotel Xaluca Dades was designed as a full-service desert-road resort for groups, families, and travelers wanting wide views and strong facilities.",
    neighborhoodOverview: "Boumalne Dades is the main road hub for the Dades Gorge, with hotels, cafés, fuel, viewpoints, and easy access to both the valley road and desert routes.",
    hiddenFeesNotice: "Taxes included; spa treatments and some activities may be extra.",
    pros: ["Large pool, gym, and spa", "Excellent for families and groups", "Panoramic valley views"],
    cons: ["Large resort feel", "Less intimate than guesthouses"],
    trustScores: {
      cleanliness: 9.2,
      safety: 9.6,
      staff: 9.4,
      value: 8.4,
      comfort: 9.0,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Free on-site or nearby parking",
      
      contact: "+212 524 000 011",
    },
    roomFeatures: ["panoramic-view", "african-inspired-decor", "ac", "heating", "elevator-access", "workspace"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 260,
              beds: "1 Queen",
              size: "30m²",
              
            },
      {
              name: "Family Room",
              price: 360,
              beds: "1 Queen + 2 Twin",
              size: "45m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Boumalne Dades",
              distance: "2km",
              time: "5 min drive",
              icon: "city",
            },
      {
              label: "Dades Gorge Road",
              distance: "5km",
              time: "10 min drive",
              icon: "road",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://xaluca.com/en/hotel-dades",
    instagramHandle: "@xalucadades",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and full-service base for solo road travelers.",
      couples: "Views and spa make it comfortable for couples.",
      families: "One of the best family-friendly hotels in the valley.",
      business: "Good for group meetings and road-trip logistics.",
      nomad: "A practical resort workation base with reliable facilities.",
    },
  },
  {
    id: "td-sleep-12",
    city: "todra_dades",
    name: "Riad BaHammou Dades",
    type: "guesthouse",
    neighborhood: "Boumalne Dades",
    description: "A grand palace-style riad at the crossroads into the Dades Gorges, with thick clay walls, stone archways, tadelakt, pool, spa, and licensed bar.",
    pricePerNight: 250,
    lifestyle: "premium",
    amenities: ["Grand Stone Archways", "Outdoor Pool & Sun Deck", "Traditional Moroccan Spa", "Alcoholic Beverage License"],
    googleRating: 4.6,
    googleReviewCount: 280,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 40,
    bookingRating: 4.6,
    bookingReviewCount: 90,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 20,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: false,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["couple", "family", "friends", "seniors"],
    tip: "One of the few traditional riads in the valley with a licensed bar; enjoy a sunset roof drink.",
    vibeTags: ["Palace-Riad", "Licensed-Bar", "Pool", "Tadelakt"],
    locationSummary: "Boumalne Dades - Gorge Crossroads",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Riad+BaHammou+Dades",
    address: "Boumalne Dades 45150, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "Riad BaHammou Dades brings palace-style architecture, a licensed bar, and spa comforts to the main Dades Gorge crossroads.",
    neighborhoodOverview: "Boumalne Dades is the main road hub for the Dades Gorge, with hotels, cafés, fuel, viewpoints, and easy access to both the valley road and desert routes.",
    hiddenFeesNotice: "Taxes included; spa treatments and drinks may be extra.",
    pros: ["Licensed bar", "Grand architecture and pool", "Practical crossroads location"],
    cons: ["Premium price", "Not deep inside the gorge"],
    trustScores: {
      cleanliness: 9.2,
      safety: 9.6,
      staff: 9.4,
      value: 8.4,
      comfort: 9.0,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Free on-site or nearby parking",
      
      contact: "+212 524 000 012",
    },
    roomFeatures: ["stone-archways", "tadelakt-finish", "rooftop-deck", "ac", "heating", "pool-access"],
    roomTypes: [
      {
              name: "Superior Room",
              price: 250,
              beds: "1 Queen",
              size: "30m²",
              
            },
      {
              name: "Royal Suite",
              price: 380,
              beds: "1 King",
              size: "55m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dades Gorge Road",
              distance: "1km",
              time: "3 min drive",
              icon: "road",
            },
      {
              label: "Boumalne Center",
              distance: "1.5km",
              time: "5 min drive",
              icon: "city",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://riadbahammou.com",
    instagramHandle: "@riadbahammoudades",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and comfortable upscale base for solo travelers.",
      couples: "Rooftop drinks and pool are romantic.",
      families: "Good for families wanting space and facilities.",
      business: "Quiet lounges support work and road planning.",
      nomad: "A premium Boumalne base for nomads with a car.",
    },
  },
  {
    id: "td-sleep-13",
    city: "todra_dades",
    name: "Monkey Fingers House",
    type: "guesthouse",
    neighborhood: "Dades Valley",
    description: "A friendly budget guesthouse beside the famous Monkey Fingers clay rock formations, with simple clean rooms and terraces over scenic Dades trails.",
    pricePerNight: 40,
    lifestyle: "lean",
    amenities: ["Immediate Trail Access", "Canyon Sunset Platform", "Daily Homemade Breakfast", "Free High-speed Wi-Fi"],
    googleRating: 4.6,
    googleReviewCount: 180,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 30,
    bookingRating: 4.5,
    bookingReviewCount: 60,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 15,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "friends", "solo"],
    tip: "Sign up for the private guided hike through the narrow canyons of the Monkey Fingers rock formations early in the morning.",
    vibeTags: ["Budget", "Hiker-Base", "Monkey-Fingers", "Friendly"],
    locationSummary: "Dades Valley - Monkey Fingers Trailhead",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Monkey+Fingers+House+Dades",
    address: "Monkey Fingers, Dades Valley, Boumalne Dades 45150, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "Monkey Fingers House was created as a simple hiker base for travelers who want immediate access to the area’s surreal clay formations.",
    neighborhoodOverview: "Dades Valley is a dramatic road-trip corridor of red cliffs, kasbah villages, palm groves, the Dades River, Monkey Fingers formations, and mountain viewpoints. A car or driver is strongly recommended.",
    hiddenFeesNotice: "Taxes included; guided hikes may cost extra.",
    pros: ["Immediate trail access", "Very affordable", "Helpful local guides"],
    cons: ["No pool", "Simple comfort level"],
    trustScores: {
      cleanliness: 9.2,
      safety: 8.9,
      staff: 9.4,
      value: 9.4,
      comfort: 9.0,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Free on-site or nearby parking",
      
      contact: "+212 524 000 013",
    },
    roomFeatures: ["trail-access", "canyon-view", "sunset-platform", "heating", "shower-ensuite", "wifi-workspace"],
    roomTypes: [
      {
              name: "Budget Room",
              price: 40,
              beds: "1 Double",
              size: "16m²",
              
            },
      {
              name: "Triple Room",
              price: 60,
              beds: "1 Double + 1 Single",
              size: "22m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Monkey Fingers Trail",
              distance: "Direct",
              time: "0 min",
              icon: "hiking",
            },
      {
              label: "Dades River",
              distance: "500m",
              time: "6 min walk",
              icon: "river",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://monkeyfingershouse.com",
    instagramHandle: "@monkeyfingershouse",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and friendly budget base for solo hikers.",
      couples: "Simple and adventurous for active couples.",
      families: "Best for older children who enjoy hiking.",
      business: "High-speed WiFi makes it useful for planning and work.",
      nomad: "A strong budget base for hiking nomads.",
    },
  },
  {
    id: "td-sleep-14",
    city: "todra_dades",
    name: "Ecolodge L'arbre de Vie",
    type: "guesthouse",
    neighborhood: "Dades Valley",
    description: "An eco-friendly desert lodge near the Dades River, built with local clay and stone, focused on sustainability and Berber lifestyle.",
    pricePerNight: 55,
    lifestyle: "lean",
    amenities: ["Eco-friendly Pisé Design", "Scenic River View Terrace", "Organic Garden Dining", "Mountain Trekking Access"],
    googleRating: 4.6,
    googleReviewCount: 110,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 20,
    bookingRating: 4.5,
    bookingReviewCount: 40,
    hotelguruRating: 4.6,
    hotelguruReviewCount: 10,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "solo"],
    tip: "An excellent option for eco-conscious travelers; the lodge is partly solar-powered and uses organic garden produce.",
    vibeTags: ["Eco-Lodge", "River-View", "Organic", "Berber"],
    locationSummary: "Dades Valley - Eco River Lodge",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Ecolodge+L%27arbre+de+Vie+Dades",
    address: "Dades Valley, Boumalne Dades 45150, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "L’arbre de Vie was built as a low-impact lodge using clay, stone, solar power, and organic garden produce to support a slower Berber valley lifestyle.",
    neighborhoodOverview: "Dades Valley is a dramatic road-trip corridor of red cliffs, kasbah villages, palm groves, the Dades River, Monkey Fingers formations, and mountain viewpoints. A car or driver is strongly recommended.",
    hiddenFeesNotice: "Taxes included; guided treks and dinners may be extra.",
    pros: ["Eco-conscious design", "Organic garden dining", "Good river terrace"],
    cons: ["Rustic comfort level", "No pool"],
    trustScores: {
      cleanliness: 9.2,
      safety: 8.9,
      staff: 9.4,
      value: 9.4,
      comfort: 9.0,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Free on-site or nearby parking",
      
      contact: "+212 524 000 014",
    },
    roomFeatures: ["pise-design", "river-view", "organic-garden", "heating", "shower-ensuite", "rooftop-access"],
    roomTypes: [
      {
              name: "Eco Room",
              price: 55,
              beds: "1 Queen",
              size: "18m²",
              
            },
      {
              name: "Family Eco Room",
              price: 80,
              beds: "1 Queen + 2 Twin",
              size: "30m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dades River",
              distance: "200m",
              time: "3 min walk",
              icon: "river",
            },
      {
              label: "Mountain Trek Start",
              distance: "500m",
              time: "7 min walk",
              icon: "hiking",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://ecolodgearbredvie.com",
    instagramHandle: "@arbredviedades",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and simple eco base for solo travelers.",
      couples: "Quiet river terraces are romantic in a rustic way.",
      families: "Good for families who like eco-lodges and gardens.",
      business: "Quiet enough for writing and route planning.",
      nomad: "A low-cost eco base for offline-focused nomads.",
    },
  },
  {
    id: "td-sleep-15",
    city: "todra_dades",
    name: "Les Jardins de Todgha",
    type: "guesthouse",
    neighborhood: "Todra Gorge",
    description: "A quiet country guesthouse in a lush organic garden in Todra palmeraie, mixing earth-walled architecture with mountain-view pool paths.",
    pricePerNight: 85,
    lifestyle: "balanced",
    amenities: ["Scenic Swimming Pool", "Organic Garden Grounds", "Panoramic Mountain Terrace", "Guided Gorge Climbing"],
    googleRating: 4.5,
    googleReviewCount: 420,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 70,
    bookingRating: 4.4,
    bookingReviewCount: 150,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 35,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Spend an afternoon by the pool; High Atlas views through the palms are spectacular.",
    vibeTags: ["Garden", "Todra-Palmeraie", "Pool", "Climbing"],
    locationSummary: "Todra Palmeraie - Garden Guesthouse",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Les+Jardins+de+Todgha",
    address: "Todra Palmeraie, Tinghir 45800, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "Les Jardins de Todgha was created as a garden-based base for Todra hikers, climbers, and families needing shade and pool time.",
    neighborhoodOverview: "Todra Gorge is a high limestone canyon near Tinghir, famous for towering cliffs, climbing routes, riverside walks, and cooler mountain air between the desert and High Atlas foothills.",
    hiddenFeesNotice: "Taxes included; climbing guides and dinners may be extra.",
    pros: ["Organic garden and pool", "Good climbing guide access", "Peaceful palmeraie setting"],
    cons: ["Not deep in the main gorge", "Simple guesthouse services"],
    trustScores: {
      cleanliness: 9.0,
      safety: 8.9,
      staff: 9.2,
      value: 9.0,
      comfort: 8.8,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Free on-site or nearby parking",
      
      contact: "+212 524 000 015",
    },
    roomFeatures: ["organic-garden", "mountain-terrace", "pool-view", "ac", "heating", "shower-ensuite"],
    roomTypes: [
      {
              name: "Garden Room",
              price: 85,
              beds: "1 Queen",
              size: "20m²",
              
            },
      {
              name: "Family Room",
              price: 120,
              beds: "1 Queen + 2 Twin",
              size: "32m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Todra Gorge",
              distance: "5km",
              time: "10 min drive",
              icon: "gorge",
            },
      {
              label: "Tinghir Palm Grove",
              distance: "Direct",
              time: "0 min",
              icon: "palm",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://lesjardinsdetodgha.com",
    instagramHandle: "@jardinsdetodgha",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and green base for solo Todra travelers.",
      couples: "Pool and gardens are relaxing for couples.",
      families: "Good for families thanks to pool and shade.",
      business: "Quiet terraces support light remote work.",
      nomad: "A balanced Todra base for nomads who climb or hike.",
    },
  },
  {
    id: "td-sleep-16",
    city: "todra_dades",
    name: "Kasbah Ait Kassi",
    type: "guesthouse",
    neighborhood: "Dades Valley",
    description: "An authentic fortress-style clay kasbah of local stone and red clay, with traditional carpets and wooden accents for a rustic mountain-home feel.",
    pricePerNight: 80,
    lifestyle: "balanced",
    amenities: ["Traditional Clay Kasbah", "Rooftop Panoramic Terrace", "Guided Mountain Trekking", "Daily Moroccan Breakfast"],
    googleRating: 4.5,
    googleReviewCount: 310,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 50,
    bookingRating: 4.4,
    bookingReviewCount: 100,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 25,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "solo"],
    tip: "Ask hosts to coordinate a day trip to remote nomadic caves in the higher valleys.",
    vibeTags: ["Clay-Kasbah", "Rustic", "Panoramic", "Trekking"],
    locationSummary: "Dades Valley - Traditional Kasbah",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Kasbah+Ait+Kassi+Dades",
    address: "Dades Valley, Boumalne Dades 45150, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "Kasbah Ait Kassi preserves the feel of a rustic fortified mountain home, with clay walls, carpets, and guided valley treks.",
    neighborhoodOverview: "Dades Valley is a dramatic road-trip corridor of red cliffs, kasbah villages, palm groves, the Dades River, Monkey Fingers formations, and mountain viewpoints. A car or driver is strongly recommended.",
    hiddenFeesNotice: "Taxes included; guided trekking and cave visits may be extra.",
    pros: ["Authentic kasbah atmosphere", "Panoramic rooftop", "Good trekking advice"],
    cons: ["No pool", "Rustic finish"],
    trustScores: {
      cleanliness: 9.0,
      safety: 8.9,
      staff: 9.2,
      value: 9.0,
      comfort: 8.8,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Free on-site or nearby parking",
      
      contact: "+212 524 000 016",
    },
    roomFeatures: ["clay-kasbah-walls", "traditional-carpets", "wooden-accents", "ac", "heating", "rooftop-access"],
    roomTypes: [
      {
              name: "Kasbah Room",
              price: 80,
              beds: "1 Queen",
              size: "20m²",
              
            },
      {
              name: "Family Room",
              price: 110,
              beds: "1 Queen + 2 Twin",
              size: "32m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dades River",
              distance: "1km",
              time: "12 min walk",
              icon: "river",
            },
      {
              label: "Nomadic Cave Route",
              distance: "15km",
              time: "30 min drive",
              icon: "hiking",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://kasbahaitkassi.com",
    instagramHandle: "@kasbahaitkassi",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and authentic base for solo travelers.",
      couples: "Rustic kasbah style is romantic for adventurous couples.",
      families: "Good for families who like traditional stays.",
      business: "Rooftop is good for planning and light work.",
      nomad: "A traditional base for nomads exploring remote valleys.",
    },
  },
  {
    id: "td-sleep-17",
    city: "todra_dades",
    name: "Hotel Kasbah de Dadès Chems",
    type: "hotel",
    neighborhood: "Boumalne Dades",
    description: "A popular hotel with panoramic Dades River views, spacious rooms, palm gardens, pool, and practical location at the canyon-road crossroads.",
    pricePerNight: 110,
    lifestyle: "balanced",
    amenities: ["Large Outdoor Pool", "Scenic River View Gardens", "Onsite Traditional Restaurant", "24-Hour Reception Desk"],
    googleRating: 4.5,
    googleReviewCount: 180,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 30,
    bookingRating: 4.4,
    bookingReviewCount: 60,
    hotelguruRating: 4.5,
    hotelguruReviewCount: 15,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: true,
    hasGym: true,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: true,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "business-friendly"],
    tip: "Request a ground-floor room to step directly onto the shared pool lawn and garden path.",
    vibeTags: ["Practical", "River-Views", "Pool", "Crossroads"],
    locationSummary: "Boumalne Dades - River View Gardens",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Hotel+Kasbah+de+Dades+Chems",
    address: "Boumalne Dades 45150, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "Kasbah de Dadès Chems was designed as a practical, comfortable base at the crossroads of Dades routes, with gardens and river views.",
    neighborhoodOverview: "Boumalne Dades is the main road hub for the Dades Gorge, with hotels, cafés, fuel, viewpoints, and easy access to both the valley road and desert routes.",
    hiddenFeesNotice: "Taxes included; some meals and excursions may be extra.",
    pros: ["24-hour reception", "Pool and garden access", "Good road-trip location"],
    cons: ["Less intimate than small riads", "More functional than boutique"],
    trustScores: {
      cleanliness: 9.0,
      safety: 9.6,
      staff: 9.2,
      value: 9.0,
      comfort: 8.8,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Free on-site or nearby parking",
      
      contact: "+212 524 000 017",
    },
    roomFeatures: ["river-view-garden", "ground-floor-access", "pool-lawn", "ac", "heating", "elevator-access"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 110,
              beds: "1 Queen",
              size: "24m²",
              
            },
      {
              name: "Garden Family Room",
              price: 150,
              beds: "1 Queen + 2 Twin",
              size: "36m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Boumalne Center",
              distance: "1km",
              time: "12 min walk",
              icon: "city",
            },
      {
              label: "Dades Gorge Road",
              distance: "2km",
              time: "5 min drive",
              icon: "road",
            },
    ],
    cancellationPolicy: "Flexible 48h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://kasbahdadeschems.com",
    instagramHandle: "@kasbahdadeschems",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "Safe and practical for solo road travelers.",
      couples: "Garden and river views are pleasant for couples.",
      families: "Great for families needing pool and reception.",
      business: "Good for work stopovers and logistics.",
      nomad: "A reliable Boumalne base for nomads on the road.",
    },
  },
  {
    id: "td-sleep-18",
    city: "todra_dades",
    name: "Hotel Amazigh",
    type: "hotel",
    neighborhood: "Tinghir",
    description: "A clean, reliable town hotel with southern Moroccan brickwork, central pool courtyard, secure parking, and convenient access to Todra Gorge.",
    pricePerNight: 50,
    lifestyle: "lean",
    amenities: ["Courtyard Swimming Pool", "Secure Private Parking", "Daily Buffet Breakfast", "Convenient Town Location"],
    googleRating: 4.4,
    googleReviewCount: 350,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 60,
    bookingRating: 4.3,
    bookingReviewCount: 120,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 30,
    hasPool: true,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: true,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: true,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: true,
    safetyLevel: 5,
    groupTypes: ["solo", "couple", "family", "business-friendly"],
    tip: "Its location in Tinghir town makes it easy to walk to local cafes and markets.",
    vibeTags: ["Reliable", "Town-Hotel", "Budget", "Pool"],
    locationSummary: "Tinghir Center - Practical Todra Base",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Hotel+Amazigh+Tinghir",
    address: "Tinghir 45800, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "Hotel Amazigh offers a dependable town base for travelers who want easy markets, parking, and quick access to Todra Gorge.",
    neighborhoodOverview: "Tinghir is the practical oasis town for Todra Gorge, with palm groves, local markets, artisan workshops, transport links, and easy access to the canyon by taxi or car.",
    hiddenFeesNotice: "Taxes included; breakfast inclusion may vary by rate.",
    pros: ["Good town location", "Secure parking", "Pool for the price"],
    cons: ["Not in the gorge itself", "Functional rather than atmospheric"],
    trustScores: {
      cleanliness: 8.8,
      safety: 9.6,
      staff: 9.0,
      value: 9.4,
      comfort: 8.6,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Secure private parking",
      
      contact: "+212 524 000 018",
    },
    roomFeatures: ["town-location", "pool-courtyard", "ac", "heating", "elevator-access", "workspace"],
    roomTypes: [
      {
              name: "Standard Room",
              price: 50,
              beds: "1 Double",
              size: "18m²",
              
            },
      {
              name: "Triple Room",
              price: 70,
              beds: "1 Double + 1 Single",
              size: "24m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Tinghir Market",
              distance: "400m",
              time: "5 min walk",
              icon: "market",
            },
      {
              label: "Todra Gorge",
              distance: "15km",
              time: "20 min drive",
              icon: "gorge",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://hotelamazigh.com",
    instagramHandle: "@hotelamazigh",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and practical budget base for solo travelers.",
      couples: "Simple but convenient for couples.",
      families: "Good for families needing parking and pool.",
      business: "A practical town option for business stopovers.",
      nomad: "A low-cost base for nomads needing market access and WiFi.",
    },
  },
  {
    id: "td-sleep-19",
    city: "todra_dades",
    name: "Valentine Valley",
    type: "guesthouse",
    neighborhood: "Dades Valley",
    description: "A functional budget guesthouse with clean air-conditioned rooms, simple modern spaces, welcoming host, rooftop terrace, and local dinners.",
    pricePerNight: 60,
    lifestyle: "lean",
    amenities: ["Rooftop Mountain Terrace", "Homemade Local Dinners", "Air Conditioning", "Free Guest Parking"],
    googleRating: 4.4,
    googleReviewCount: 190,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 30,
    bookingRating: 4.3,
    bookingReviewCount: 60,
    hotelguruRating: 4.4,
    hotelguruReviewCount: 15,
    hasPool: false,
    hasBreakfast: true,
    hasAC: true,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ["solo", "couple", "family", "friends"],
    tip: "Perfect for quick, hassle-free layovers on your way through the Dades Gorges.",
    vibeTags: ["Budget", "Stopover", "Rooftop", "Road-Trip"],
    locationSummary: "Dades Valley - Budget Stopover",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Valentine+Valley+Dades",
    address: "Dades Valley, Boumalne Dades 45150, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "Valentine Valley focuses on easy road-trip comfort: clean rooms, AC, parking, local dinners, and a useful rooftop terrace.",
    neighborhoodOverview: "Dades Valley is a dramatic road-trip corridor of red cliffs, kasbah villages, palm groves, the Dades River, Monkey Fingers formations, and mountain viewpoints. A car or driver is strongly recommended.",
    hiddenFeesNotice: "Taxes included; dinner and excursions may be extra.",
    pros: ["Clean AC rooms", "Free parking", "Good homemade dinners"],
    cons: ["No pool", "Basic comfort level"],
    trustScores: {
      cleanliness: 8.8,
      safety: 8.9,
      staff: 9.0,
      value: 9.4,
      comfort: 8.6,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Free on-site or nearby parking",
      
      contact: "+212 524 000 019",
    },
    roomFeatures: ["rooftop-terrace", "mountain-view", "ac", "heating", "shower-ensuite", "free-parking"],
    roomTypes: [
      {
              name: "Budget Room",
              price: 60,
              beds: "1 Queen",
              size: "18m²",
              
            },
      {
              name: "Family Room",
              price: 85,
              beds: "1 Queen + 1 Single",
              size: "26m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Dades Gorge Road",
              distance: "2km",
              time: "5 min drive",
              icon: "road",
            },
      {
              label: "Boumalne Dades",
              distance: "10km",
              time: "12 min drive",
              icon: "city",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://valentinevalley.com",
    instagramHandle: "@valentinevalley",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and easy stopover for solo road travelers.",
      couples: "Simple and convenient for couples.",
      families: "Good for families needing AC and parking.",
      business: "Works for quick emails and travel planning.",
      nomad: "A practical budget base for road-trip nomads.",
    },
  },
  {
    id: "td-sleep-20",
    city: "todra_dades",
    name: "Auberge Camping Atlas",
    type: "guesthouse",
    neighborhood: "Todra Gorge",
    description: "A simple budget riverside lodge deep in Todra Gorge, with mud-brick design, shared Berber salons, immediate trail access, and climber-basecamp feel.",
    pricePerNight: 40,
    lifestyle: "lean",
    amenities: ["Riverside Dining Terrace", "Immediate Gorge Access", "Shared Moroccan Salon", "Daily Traditional Breakfast"],
    googleRating: 4.3,
    googleReviewCount: 120,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 20,
    bookingRating: 4.2,
    bookingReviewCount: 40,
    hotelguruRating: 4.3,
    hotelguruReviewCount: 10,
    hasPool: false,
    hasBreakfast: true,
    hasAC: false,
    hasHeating: true,
    hasRooftop: true,
    hasEnsuite: true,
    hasRestaurant: true,
    hasBar: false,
    hasGym: false,
    hasElevator: false,
    hasLaundryService: true,
    hasRoomService: false,
    petFriendly: true,
    isWheelchairAccessible: false,
    taxesIncluded: true,
    freeCancellation: true,
    kidsStayFree: true,
    nearMedina: false,
    nearBeach: false,
    nearMosque: false,
    safetyLevel: 4,
    groupTypes: ["solo", "friends", "solo", "friends"],
    tip: "Wake early to hike the gorge walls before day-trippers and tour buses arrive around 10 AM.",
    vibeTags: ["Budget", "Riverside", "Climber-Basecamp", "Gorge"],
    locationSummary: "Todra Gorge - Riverside Climber Base",
    availabilityText: "Available tonight",
    googleMapsUrl: "https://maps.google.com/?q=Auberge+Camping+Atlas+Todra",
    address: "Todra Gorge, Tinghir 45800, Morocco",
    paymentMethods: ["card", "cash"],
    languagesSpoken: ["Arabic", "French", "English", "Berber"],
    customStory: "Auberge Camping Atlas is a classic budget basecamp for climbers and hikers who want to sleep inside the gorge and start early.",
    neighborhoodOverview: "Todra Gorge is a high limestone canyon near Tinghir, famous for towering cliffs, climbing routes, riverside walks, and cooler mountain air between the desert and High Atlas foothills.",
    hiddenFeesNotice: "Taxes included; climbing guides and extra meals may be extra.",
    pros: ["Immediate gorge access", "Very affordable", "Riverside terrace"],
    cons: ["Basic facilities", "No pool or AC"],
    trustScores: {
      cleanliness: 8.6,
      safety: 8.9,
      staff: 8.8,
      value: 9.4,
      comfort: 8.4,
      location: 9.3,
    },
    logistics: {
      checkIn: "14:00",
      checkOut: "11:00",
      
      luggageStorage: "Free",
      parking: "Free on-site or nearby parking",
      
      contact: "+212 524 000 020",
    },
    roomFeatures: ["riverside-terrace", "mud-brick-design", "shared-salon", "heating", "shower-ensuite", "trail-access"],
    roomTypes: [
      {
              name: "Budget Double",
              price: 40,
              beds: "1 Double",
              size: "16m²",
              
            },
      {
              name: "Shared Hiker Room",
              price: 25,
              beds: "Single beds",
              size: "20m²",
              
            },
    ],
    neighborhoodDistances: [
      {
              label: "Todra Gorge Trail",
              distance: "Direct",
              time: "0 min",
              icon: "hiking",
            },
      {
              label: "Tinghir",
              distance: "15km",
              time: "20 min drive",
              icon: "city",
            },
    ],
    cancellationPolicy: "Flexible 24h",
    childPolicy: "Children welcome - kids stay free using existing bedding",
    officialWebsite: "https://aubergecampingatlas.com",
    instagramHandle: "@aubergecampingatlas",
    // googlePlaceId: "PLACE_ID_HERE",
    reviewHighlights: {
      solo: "A safe and cheap base for solo climbers and hikers.",
      couples: "Rustic but atmospheric for adventurous couples.",
      families: "Best for older kids and trekking families.",
      business: "Not suitable for business travel.",
      nomad: "A bare-bones climber base for budget nomads.",
    },
  }
]
