import type { ThingToDoListing } from '../types'

export const tangierThings: ThingToDoListing[] = [
  {
    id: "tangier-caves-hercules",
    city: "tangier",
    name: "Caves of Hercules",
    neighborhood: "Cap Spartel",
    description: "An archaeological cave complex steeped in Greek mythology where the sea opening forms a silhouette of the African continent. Watch the Atlantic waves crash directly into the caverns.",
    price: 8,
    lifestyle: ["balanced"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "bustling",
    durationMinutes: 45,
    hasEnglishGuide: false,
    hasFrenchGuide: true,
    images: [
      "https://images.unsplash.com/photo-1548013146-72479768bada?w=1000&q=80",
      "https://images.unsplash.com/photo-1509060464153-4466739f78d0"
    ],
    googleRating: 4.0,
    reviewCount: 7176,
    googleMapsUrl: "https://www.google.com/maps/place/Caves+of+Hercules/@35.7599298,-5.9398553,17z",
    safetyLevel: 5,
    energyLevel: "moderate",
    transportMode: "taxi",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: false,
    isPhotographyFriendly: true,
    tags: ["authentic", "nature", "coastal", "instagrammable", "photo-spot", "port-express"],
    archetypeAffinity: ["first-timer", "culture"],
    tip: "Bring cash in Moroccan Dirham (80 MAD) as international cards are rarely accepted at the ticket counter."
  },
  {
    id: "tangier-cap-spartel",
    city: "tangier",
    name: "Cap Spartel Lighthouse",
    neighborhood: "Cap Spartel",
    description: "Stand at the northwesternmost tip of mainland Africa, where the deep blue Atlantic Ocean meets the Mediterranean Sea. Explore the restored 1864 lighthouse, its maritime museum, and well-kept botanical gardens.",
    price: 5,
    lifestyle: ["balanced"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "balanced",
    durationMinutes: 60,
    hasEnglishGuide: false,
    hasFrenchGuide: true,
    images: [
      "https://images.unsplash.com/photo-1542838132-92c53300491e",
      "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43"
    ],
    googleRating: 4.5,
    reviewCount: 4445,
    googleMapsUrl: "https://www.google.com/maps/place/Cap+Spartel/@35.7901765,-5.9238384,17z",
    safetyLevel: 5,
    energyLevel: "relaxed",
    transportMode: "taxi",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: true,
    isPhotographyFriendly: true,
    tags: ["coastal", "nature", "authentic", "instagrammable", "photo-spot", "golden-hour", "sunset-view", "port-express", "step-free"],
    archetypeAffinity: ["first-timer", "culture"],
    tip: "Visit during sunset to watch the golden glow light up the meeting point of the two seas."
  },
  {
    id: "tangier-kasbah-museum",
    city: "tangier",
    name: "Kasbah Museum (Dar el-Makhzen)",
    neighborhood: "Kasbah",
    description: "Housed inside the former 17th-century Sultan's palace, this museum showcases Tangier's history from prehistoric times through Roman, Phoenician, and Islamic eras. Don’t miss the serene Andalusian courtyard garden filled with free-roaming tortoises.",
    price: 3,
    lifestyle: ["lean"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "balanced",
    durationMinutes: 90,
    hasEnglishGuide: true,
    hasFrenchGuide: true,
    images: [
      "https://images.unsplash.com/photo-1580618672591-eb180b1a973f",
      "https://images.unsplash.com/photo-1548013146-72479768bada?w=1000&q=80"
    ],
    googleRating: 4.4,
    reviewCount: 2162,
    googleMapsUrl: "https://www.google.com/maps/place/Kasbah+Museum/@35.7891334,-5.8143962,17z",
    safetyLevel: 5,
    energyLevel: "relaxed",
    transportMode: "walkable",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: true,
    isPhotographyFriendly: true,
    tags: ["cultural-tour", "authentic", "medina", "instagrammable", "photo-spot", "port-express", "step-free"],
    archetypeAffinity: ["culture"],
    tip: "Your ticket also grants free entry to the nearby Contemporary Art Space, making it an excellent two-for-one deal."
  },
  {
    id: "tangier-legation-museum",
    city: "tangier",
    name: "Tangier American Legation Museum",
    neighborhood: "Medina",
    description: "The first and only American National Historic Landmark located on foreign soil, gifted by the Sultan of Morocco in 1821. Discover beautifully restored, tiled rooms packed with regional art, historic maps, and a wing dedicated to expatriate author Paul Bowles.",
    price: 5,
    lifestyle: ["balanced"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "balanced",
    durationMinutes: 60,
    hasEnglishGuide: true,
    hasFrenchGuide: true,
    images: [
      "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43",
      "https://images.unsplash.com/photo-1542838132-92c53300491e"
    ],
    googleRating: 4.6,
    reviewCount: 1250,
    googleMapsUrl: "https://www.google.com/maps/place/Tangier+American+Legation+Museum/@35.7836109,-5.8118029,17z",
    safetyLevel: 5,
    energyLevel: "relaxed",
    transportMode: "walkable",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: true,
    isPhotographyFriendly: true,
    tags: ["cultural-tour", "authentic", "medina", "instagrammable"],
    archetypeAffinity: ["culture", "first-timer"],
    tip: "Ask the staff to show you the \"Moroccan Mona Lisa\" painting by James McBey—it is the crown jewel of the collection."
  },
  {
    id: "tangier-cafe-hafa",
    city: "tangier",
    name: "Café Hafa",
    neighborhood: "Marshan",
    description: "A legendary cliffside establishment that has been serving mint tea since 1921 to famous bohemians like the Rolling Stones, William S. Burroughs, and Jimi Hendrix. Take a seat on its terraced, whitewashed steps and look across the Strait of Gibraltar toward Spain.",
    price: 1.5,
    lifestyle: ["lean"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "balanced",
    durationMinutes: 60,
    hasEnglishGuide: false,
    hasFrenchGuide: false,
    images: [
      "https://images.unsplash.com/photo-1509060464153-4466739f78d0",
      "https://images.unsplash.com/photo-1580618672591-eb180b1a973f"
    ],
    googleRating: 3.9,
    reviewCount: 10900,
    googleMapsUrl: "https://www.google.com/maps/place/Caf%C3%A9+Hafa/@35.7912448,-5.8239088,17z",
    safetyLevel: 5,
    energyLevel: "relaxed",
    transportMode: "walkable",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: false,
    isPhotographyFriendly: true,
    tags: ["authentic", "coastal", "off-the-beaten-path", "instagrammable"],
    archetypeAffinity: ["first-timer", "nomad"],
    tip: "Order the traditional Moroccan mint tea and be prepared to find your own table, as service here is famously laid-back."
  },
  {
    id: "tangier-grand-socco",
    city: "tangier",
    name: "Grand Socco (Place du 9 Avril 1947)",
    neighborhood: "Medina",
    description: "The energetic and beating heart of Tangier that bridges the ancient, narrow streets of the Medina with the modern Ville Nouvelle. It features palm trees, a lively central fountain, and surrounding historic cafes perfect for people-watching.",
    price: 0,
    lifestyle: ["lean"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "bustling",
    durationMinutes: 60,
    hasEnglishGuide: false,
    hasFrenchGuide: false,
    images: [
      "https://images.unsplash.com/photo-1548013146-72479768bada?w=1000&q=80",
      "https://images.unsplash.com/photo-1542838132-92c53300491e"
    ],
    googleRating: 4.5,
    reviewCount: 10113,
    googleMapsUrl: "https://www.google.com/maps/place/Grand+Socco/@35.7853112,-5.814522,17z",
    safetyLevel: 5,
    energyLevel: "moderate",
    transportMode: "walkable",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: true,
    isPhotographyFriendly: true,
    tags: ["authentic", "medina", "shopping", "instagrammable"],
    archetypeAffinity: ["first-timer", "nomad"],
    tip: "Take a seat on a cafe terrace on the square around dusk to experience the local transition from day to night."
  },
  {
    id: "tangier-petit-socco",
    city: "tangier",
    name: "Petit Socco",
    neighborhood: "Medina",
    description: "Once a notorious hub for international spies, writers, and bohemians in the early 20th century, this cozy square is now a charming crossroads of medina life. Sip a coffee or mint tea at a historic cafe and watch the vibrant daily life of the old city walk by.",
    price: 0,
    lifestyle: ["lean"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "balanced",
    durationMinutes: 45,
    hasEnglishGuide: false,
    hasFrenchGuide: false,
    images: [
      "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43",
      "https://images.unsplash.com/photo-1509060464153-4466739f78d0"
    ],
    googleRating: 4.4,
    reviewCount: 819,
    googleMapsUrl: "https://www.google.com/maps/place/Petit+Socco/@35.7849684,-5.8115668,17z",
    safetyLevel: 5,
    energyLevel: "relaxed",
    transportMode: "walkable",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: true,
    isPhotographyFriendly: true,
    tags: ["authentic", "medina", "cultural-tour", "off-the-beaten-path"],
    archetypeAffinity: ["culture", "nomad"],
    tip: "Head to the iconic Gran Café Central directly on the square, which was once a favorite haunt of William S. Burroughs."
  },
  {
    id: "tangier-perdicaris-park",
    city: "tangier",
    name: "Perdicaris Park (Parc Forestier de Perdicaris)",
    neighborhood: "Rmilat",
    description: "A lush, 70-hectare coastal forest park perched on a hillside overlooking the Strait of Gibraltar. Walk along well-maintained nature trails under towering eucalyptus, pine, and oak trees, and explore the historic, beautifully restored 19th-century Perdicaris Castle.",
    price: 0,
    lifestyle: ["balanced"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "balanced",
    durationMinutes: 90,
    hasEnglishGuide: false,
    hasFrenchGuide: false,
    images: [
      "https://images.unsplash.com/photo-1580618672591-eb180b1a973f",
      "https://images.unsplash.com/photo-1542838132-92c53300491e"
    ],
    googleRating: 4.6,
    reviewCount: 7918,
    googleMapsUrl: "https://www.google.com/maps/place/Parc+Perdicaris/@35.7937965,-5.8659618,15z",
    safetyLevel: 5,
    energyLevel: "moderate",
    transportMode: "taxi",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: true,
    isPhotographyFriendly: true,
    tags: ["nature", "coastal", "authentic", "off-the-beaten-path"],
    archetypeAffinity: ["nomad", "adventure"],
    tip: "Pack a light lunch; the park is a favorite weekend picnic spot for locals and has fantastic designated overlook tables."
  },
  {
    id: "tangier-phoenician-tombs",
    city: "tangier",
    name: "Phoenician Tombs (Tombeaux Phéniciens)",
    neighborhood: "Marshan",
    description: "A collection of dozens of ancient tombs carved directly into the rocky cliffs of the Marshan plateau, dating back thousands of years. It offers some of the most panoramic, unobstructed sea views of the Strait of Gibraltar and Spain.",
    price: 0,
    lifestyle: ["lean"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "balanced",
    durationMinutes: 30,
    hasEnglishGuide: false,
    hasFrenchGuide: false,
    images: [
      "https://images.unsplash.com/photo-1509060464153-4466739f78d0",
      "https://images.unsplash.com/photo-1548013146-72479768bada?w=1000&q=80"
    ],
    googleRating: 4.4,
    reviewCount: 1000,
    googleMapsUrl: "https://www.google.com/maps/place/Phoenician+tombs/@35.7915562,-5.819875,17z",
    safetyLevel: 5,
    energyLevel: "relaxed",
    transportMode: "walkable",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: true,
    isPhotographyFriendly: true,
    tags: ["off-the-beaten-path", "coastal", "authentic", "nature"],
    archetypeAffinity: ["culture", "nomad"],
    tip: "This is a highly popular, completely free spot where locals gather to play guitars and watch the sunset; arrive in the late afternoon for the best vibe."
  },
  {
    id: "tangier-st-andrew",
    city: "tangier",
    name: "St. Andrew’s Anglican Church",
    neighborhood: "Medina",
    description: "A fascinating historical testament to interfaith harmony, this active Anglican church is constructed in a Moorish architectural style. Admire its intricate geometric carvings, zellij tiles, and the Lord's Prayer beautifully written in Arabic calligraphy inside.",
    price: 2,
    lifestyle: ["balanced"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "quiet",
    durationMinutes: 30,
    hasEnglishGuide: true,
    hasFrenchGuide: true,
    images: [
      "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43",
      "https://images.unsplash.com/photo-1542838132-92c53300491e"
    ],
    googleRating: 4.1,
    reviewCount: 325,
    googleMapsUrl: "https://www.google.com/maps/place/St.+Andrew's+Church/@35.7845612,-5.815915,17z",
    safetyLevel: 5,
    energyLevel: "relaxed",
    transportMode: "walkable",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: true,
    isPhotographyFriendly: true,
    tags: ["cultural-tour", "authentic", "medina", "off-the-beaten-path"],
    archetypeAffinity: ["culture"],
    tip: "Speak to the resident caretaker, who is a local Muslim maintaining this Christian church, and ask to see the historic gravestones in the lush backyard cemetery."
  },
  {
    id: "tangier-villa-harris",
    city: "tangier",
    name: "Villa Harris Museum (Musée Villa Harris)",
    neighborhood: "Malabata",
    description: "Once the grand 19th-century residence of British journalist Walter Burton Harris, this property is now a modern art museum. Explore two floors of vibrant Moroccan paintings, sculptures, and international orientalist art, surrounded by a peaceful botanical park.",
    price: 2,
    lifestyle: ["premium"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "quiet",
    durationMinutes: 60,
    hasEnglishGuide: true,
    hasFrenchGuide: true,
    images: [
      "https://images.unsplash.com/photo-1580618672591-eb180b1a973f",
      "https://images.unsplash.com/photo-1548013146-72479768bada?w=1000&q=80"
    ],
    googleRating: 4.5,
    reviewCount: 500,
    googleMapsUrl: "https://www.google.com/maps/place/Villa+Harris+Museum/@35.7766521,-5.7733475,17z",
    safetyLevel: 5,
    energyLevel: "relaxed",
    transportMode: "taxi",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: true,
    isPhotographyFriendly: true,
    tags: ["cultural-tour", "instagrammable", "nature", "off-the-beaten-path"],
    archetypeAffinity: ["culture", "luxury"],
    tip: "Placed in Malabata, this museum features trilingual informational placards (including English), making it highly accessible for international visitors."
  },
  {
    id: "tangier-dar-niaba",
    city: "tangier",
    name: "Dar Niaba Cultural Museum",
    neighborhood: "Medina",
    description: "Housed inside a restored Portuguese-era mansion that served as the former French consulate and the office of the Sultan's diplomatic representative. It hosts a collection of 19th and 20th-century Orientalist portraits, diplomatic artifacts, and historical archives.",
    price: 2,
    lifestyle: ["balanced"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "quiet",
    durationMinutes: 45,
    hasEnglishGuide: false,
    hasFrenchGuide: true,
    images: [
      "https://images.unsplash.com/photo-1542838132-92c53300491e",
      "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43"
    ],
    googleRating: 4.4,
    reviewCount: 180,
    googleMapsUrl: "https://www.google.com/maps/place/Mus%C3%A9e+Dar+Niaba/@35.7847125,-5.8130252,17z",
    safetyLevel: 5,
    energyLevel: "relaxed",
    transportMode: "walkable",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: true,
    isPhotographyFriendly: true,
    tags: ["cultural-tour", "authentic", "medina", "off-the-beaten-path"],
    archetypeAffinity: ["culture"],
    tip: "Take a slow stroll through the peaceful central courtyard downstairs, which features a beautiful array of orange trees."
  },
  {
    id: "tangier-cinematheque",
    city: "tangier",
    name: "Cinémathèque de Tanger (Cinema Rif)",
    neighborhood: "Grand Socco",
    description: "Step into a restored 1930s Art Deco movie house that operates as a vibrant non-profit cultural cinema and cafe. It serves as a beloved meeting point for local students and artists, screening independent Moroccan, African, and international films.",
    price: 4,
    lifestyle: ["lean"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "balanced",
    durationMinutes: 90,
    hasEnglishGuide: false,
    hasFrenchGuide: false,
    images: [
      "https://images.unsplash.com/photo-1509060464153-4466739f78d0",
      "https://images.unsplash.com/photo-1580618672591-eb180b1a973f"
    ],
    googleRating: 4.4,
    reviewCount: 1026,
    googleMapsUrl: "https://www.google.com/maps/place/Cin%C3%A9math%C3%A8que+de+Tanger/@35.7852327,-5.8143924,17z",
    safetyLevel: 5,
    energyLevel: "relaxed",
    transportMode: "walkable",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: true,
    isPhotographyFriendly: true,
    tags: ["authentic", "workshop", "shopping", "instagrammable"],
    archetypeAffinity: ["nomad", "culture"],
    tip: "If you don't have time to watch a movie, you can still grab a local verbena tea or coffee on their outdoor terrace overlooking the Grand Socco."
  },
  {
    id: "tangier-terrasse-paresseux",
    city: "tangier",
    name: "Terrasse des Paresseux (Faro Square)",
    neighborhood: "Ville Nouvelle",
    description: "Known famously as the \"Idlers' Terrace,\" this breezy promenade is lined with historic bronze cannons facing the sea. It offers a spectacular, unobstructed panoramic viewpoint of the busy port, the Mediterranean, and the distant hills of Spain.",
    price: 0,
    lifestyle: ["lean"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "balanced",
    durationMinutes: 30,
    hasEnglishGuide: false,
    hasFrenchGuide: false,
    images: [
      "https://images.unsplash.com/photo-1548013146-72479768bada?w=1000&q=80",
      "https://images.unsplash.com/photo-1542838132-92c53300491e"
    ],
    googleRating: 4.4,
    reviewCount: 373,
    googleMapsUrl: "https://www.google.com/maps/place/Terrasse+des+Paresseux/@35.7841123,-5.8089254,17z",
    safetyLevel: 5,
    energyLevel: "relaxed",
    transportMode: "walkable",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: true,
    isPhotographyFriendly: true,
    tags: ["coastal", "authentic", "instagrammable", "nature"],
    archetypeAffinity: ["first-timer", "nomad"],
    tip: "Keep an eye out for binoculars along the terrace wall on clear days; you can drop a small coin in to get a sharp view of the Spanish coastline."
  },
  {
    id: "tangier-moshe-nahon",
    city: "tangier",
    name: "Moshe Nahon Synagogue",
    neighborhood: "Medina",
    description: "Built in the mid-19th century, this hidden synagogue is a tribute to Tangier's historical Jewish heritage. Wander through its restored interior featuring Andalusian arches, intricate stucco work, and a collection of old liturgical artifacts.",
    price: 3,
    lifestyle: ["balanced"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "quiet",
    durationMinutes: 30,
    hasEnglishGuide: false,
    hasFrenchGuide: false,
    images: [
      "https://images.unsplash.com/photo-1564507592333-c60657eea523",
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511"
    ],
    googleRating: 4.5,
    reviewCount: 150,
    googleMapsUrl: "https://www.google.com/maps/place/Moshe+Nahon+Synagogue/@35.7851121,-5.8119123,17z",
    safetyLevel: 5,
    energyLevel: "relaxed",
    transportMode: "walkable",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: true,
    isPhotographyFriendly: true,
    tags: ["cultural-tour", "authentic", "medina", "off-the-beaten-path"],
    archetypeAffinity: ["culture"],
    tip: "The synagogue is tucked deep inside an alleyway; look out for a local caretaker nearby who holds the key and will unlock it for a small tip."
  },
  {
    id: "tangier-mendoubia-gardens",
    city: "tangier",
    name: "Mendoubia Gardens (Parc de la Mendoubia)",
    neighborhood: "Marshan",
    description: "A historic green park located on the edge of the Medina, serving as a tranquil retreat from the city center's bustle. It is lined with colonial-era buildings, historic French cannons, and a legendary, giant banyan tree believed to be centuries old.",
    price: 0,
    lifestyle: ["lean"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "quiet",
    durationMinutes: 45,
    hasEnglishGuide: false,
    hasFrenchGuide: false,
    images: [
      "https://images.unsplash.com/photo-1580618672591-eb180b1a973f",
      "https://images.unsplash.com/photo-1542838132-92c53300491e"
    ],
    googleRating: 4.1,
    reviewCount: 871,
    googleMapsUrl: "https://www.google.com/maps/place/Mendoubia+Garden/@35.7865123,-5.8159124,17z",
    safetyLevel: 5,
    energyLevel: "relaxed",
    transportMode: "walkable",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: true,
    isPhotographyFriendly: true,
    tags: ["nature", "authentic", "off-the-beaten-path", "cultural-tour"],
    archetypeAffinity: ["first-timer", "nomad"],
    tip: "It's a peaceful place to relax on a bench in the late afternoon while children play football and friendly local street cats wander by."
  },
  {
    id: "tangier-jewish-cemetery",
    city: "tangier",
    name: "Beit Hahayim (Old Jewish Cemetery of Tangier)",
    neighborhood: "Medina",
    description: "Perched on a hillside just outside the old medina walls, this cemetery holds thousands of centuries-old tombstones with unique Hebrew inscriptions. It provides a peaceful, reflective look into the deep-rooted historical multicultural identity of Tangier.",
    price: 2,
    lifestyle: ["lean"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "quiet",
    durationMinutes: 45,
    hasEnglishGuide: false,
    hasFrenchGuide: false,
    images: [
      "https://images.unsplash.com/photo-1548013146-72479768bada?w=1000&q=80",
      "https://images.unsplash.com/photo-1509060464153-4466739f78d0"
    ],
    googleRating: 4.6,
    reviewCount: 18,
    googleMapsUrl: "https://www.google.com/maps/place/Jewish+Cemetery+Tangier/@35.7855123,-5.8105124,17z",
    safetyLevel: 5,
    energyLevel: "relaxed",
    transportMode: "walkable",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: true,
    isPhotographyFriendly: true,
    tags: ["cultural-tour", "authentic", "medina", "off-the-beaten-path"],
    archetypeAffinity: ["culture"],
    tip: "While the main iron gates on Rue Portugal are kept locked, knock gently and the friendly resident caretaker will let you in. A small tip of 20 MAD is customary."
  },
  {
    id: "tangier-ibn-battouta-tomb",
    city: "tangier",
    name: "Tomb of Ibn Battouta",
    neighborhood: "Medina",
    description: "Pay your respects at the modest final resting place of history’s greatest pre-modern traveler, Ibn Battouta, who was born in Tangier in 1304. This humble, whitewashed mausoleum pays tribute to his epic 29-year, 75,000-mile journey across Africa, Europe, and Asia.",
    price: 0,
    lifestyle: ["lean"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "quiet",
    durationMinutes: 15,
    hasEnglishGuide: false,
    hasFrenchGuide: false,
    images: [
      "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43",
      "https://images.unsplash.com/photo-1542838132-92c53300491e"
    ],
    googleRating: 4.1,
    reviewCount: 196,
    googleMapsUrl: "https://maps.google.com/?q=Tomb+of+Ibn+Battouta/@35.7874125,-5.8149124,17z",
    safetyLevel: 5,
    energyLevel: "relaxed",
    transportMode: "walkable",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: true,
    isPhotographyFriendly: true,
    tags: ["cultural-tour", "authentic", "medina", "off-the-beaten-path"],
    archetypeAffinity: ["culture", "adventure"],
    tip: "The tomb is located inside a small maze of residential streets in the medina. Feel free to ask a local shopkeeper for \"Qabr Ibn Battouta\" if you lose your way."
  },
  {
    id: "tangier-achakkar-beach",
    city: "tangier",
    name: "Achakkar Beach (Plage Achakar)",
    neighborhood: "Achakkar",
    description: "A gorgeous, expansive stretch of clean golden sand where the waves of the Atlantic coast crash forcefully against the shore. Located right next to the Caves of Hercules, it is highly popular for ocean swimming, dramatic sunset walks, and camel rides.",
    price: 0,
    lifestyle: ["balanced"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "balanced",
    durationMinutes: 120,
    hasEnglishGuide: false,
    hasFrenchGuide: false,
    images: [
      "https://images.unsplash.com/photo-1509060464153-4466739f78d0",
      "https://images.unsplash.com/photo-1580618672591-eb180b1a973f"
    ],
    googleRating: 4.3,
    reviewCount: 1394,
    googleMapsUrl: "https://maps.google.com/?q=Achakkar+Beach/@35.7621124,-5.9379124,15z",
    safetyLevel: 5,
    energyLevel: "moderate",
    transportMode: "taxi",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: true,
    isPhotographyFriendly: true,
    tags: ["coastal", "nature", "authentic", "instagrammable"],
    archetypeAffinity: ["first-timer", "adventure"],
    tip: "Local owners offer short camel rides directly along the surf; you can typically negotiate a 10-to-15 minute ride with photo ops for about 2 to 3 EUR (20-30 MAD)."
  },
  {
    id: "tangier-darna-association",
    city: "tangier",
    name: "Darna Association Café & Restaurant",
    neighborhood: "Grand Socco",
    description: "A welcoming community space and restaurant operated by the Darna Association, which supports vulnerable local women and youth. Enjoy fresh, home-cooked traditional Moroccan tagines and pastries in a peaceful courtyard, knowing your money supports a noble social cause.",
    price: 6,
    lifestyle: ["lean"],
    groupTypes: ["solo", "couple", "family", "friends", "seniors"],
    crowdLevel: "balanced",
    durationMinutes: 60,
    hasEnglishGuide: true,
    hasFrenchGuide: true,
    images: [
      "https://images.unsplash.com/photo-1542838132-92c53300491e",
      "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43"
    ],
    googleRating: 4.5,
    reviewCount: 151,
    googleMapsUrl: "https://maps.google.com/?q=Darna/@35.7844123,-5.8155124,17z",
    safetyLevel: 5,
    energyLevel: "relaxed",
    transportMode: "walkable",
    isKidFriendly: true,
    isFemaleFriendly: true,
    isWheelchairAccessible: true,
    isPhotographyFriendly: true,
    tags: ["authentic", "cultural-tour", "shopping", "wellness"],
    archetypeAffinity: ["culture", "nomad"],
    tip: "Make sure to visit their small on-site artisan shop afterward, where they sell beautiful hand-woven textiles and crafts made directly by the women of the association."
  }
]
