import { ShopListing } from '../types'

export const asilahShops: ShopListing[] = [
  {
    id: 'sh-asi-1',
    city: 'asilah',
    name: 'Galerie Hakim Art & Antiques',
    type: 'concept_store',
    category: 'Art & Antiques',
    neighborhood: 'Medina',
    description: 'Renowned medina art gallery showcasing original paintings by local Asilah mural artists alongside curated vintage Moroccan carpets, silver jewelry, and ceramics.',
    googleRating: 4.8,
    googleReviewCount: 220,
    priceLevel: 'premium',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJGalerieHakimArtAntiquesAsilah',
    googleMapsUrl: 'https://maps.google.com/?q=Galerie+Hakim+Asilah',
    address: 'Rue Ibn Khaldoun, Medina, Asilah',
    landmark: 'Raissouni Palace / Medina Sea Ramparts',
    coordinates: { lat: 35.4660, lng: -6.0375 },
    distanceText: '2 min walk from Bab Al Kasbah gate',
    navSteps: [
      'Enter through Bab Al Kasbah gate into the white-washed medina',
      'Walk straight along the main rampart alley toward the sea view bastion',
      'Galerie Hakim is located on your right opposite Raissouni Palace'
    ],
    what3words: 'mural.canvas.rampart',
    tags: ['Original Art', 'Asilah Murals', 'Fine Antiques', 'Coastal Gallery'],
    paymentMethods: ['cash', 'visa', 'mastercard', 'amex'],
    productCategories: ['Asilah Seascape Paintings', 'Mural Sketches', 'Vintage Silver Jewelry', 'Coastal Rugs'],
    languagesSpoken: ['Spanish', 'French', 'English', 'Arabic'],
    phoneNumber: '+212 5394-17850',
    openingHours: [{ day: 'Mon-Sun', hours: '10:00 - 20:00' }],
    shipping: { available: true, partner: 'dhl' },
    isLocalFavorite: true
  },
  {
    id: 'sh-asi-2',
    city: 'asilah',
    name: 'Bazar Asilah Medina Straw & Decor',
    type: 'boutique',
    category: 'Basketry & Fashion',
    neighborhood: 'Medina',
    description: 'Charming white-and-blue painted medina shop selling hand-decorated straw sun hats, woven beach totes with leather handles, flowy kaftans, and colorful ceramics.',
    googleRating: 4.7,
    googleReviewCount: 310,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJBazarAsilahMedinaStrawDecorAsilah',
    googleMapsUrl: 'https://maps.google.com/?q=Bazar+Asilah+Medina',
    address: 'Rue Commerce, Medina, Asilah',
    landmark: 'Bab Homar Gate',
    coordinates: { lat: 35.4652, lng: -6.0360 },
    distanceText: '1 min walk inside Bab Homar entrance',
    tags: ['Straw Hats', 'Beach Totes', 'Linen Kaftans', 'Coastal Decor'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Custom Straw Sun Hats', 'Leather-handled Beach Totes', 'Linen Beach Wraps'],
    languagesSpoken: ['Spanish', 'French', 'English', 'Arabic'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:30 - 21:00' }]
  },
  {
    id: 'sh-asi-3',
    city: 'asilah',
    name: 'Asilah Handwoven Rug Collective',
    type: 'cooperative',
    category: 'Carpets & Textiles',
    neighborhood: 'Medina',
    description: 'Artisan collective producing pastel-toned, lightweight coastal flat-weave carpets, cotton throws, striped wool blankets, and floor cushions.',
    googleRating: 4.8,
    googleReviewCount: 175,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJAsilahHandwovenRugCollectiveAsilah',
    googleMapsUrl: 'https://maps.google.com/?q=Asilah+Handwoven+Rugs',
    address: 'Rue Tijani, Medina, Asilah',
    landmark: 'Krikia Viewpoint Alley',
    coordinates: { lat: 35.4665, lng: -6.0380 },
    distanceText: '3 min walk from Krikia sea lookout',
    tags: ['Coastal Carpets', 'Pastel Kilims', 'Handwoven Throws', 'Cotton Blankets'],
    authenticitySeals: ['wfto', 'label_artisanat'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Pastel Flat-weave Rugs', 'Striped Cotton Blankets', 'Floor Cushions'],
    languagesSpoken: ['Spanish', 'English', 'French', 'Arabic'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:30 - 20:00' }],
    shipping: { available: true, partner: 'fedex' }
  },
  {
    id: 'sh-asi-4',
    city: 'asilah',
    name: 'Boutique Bohemian Chic Asilah',
    type: 'concept_store',
    category: 'Fashion & Jewelry',
    neighborhood: 'Medina',
    description: 'Photogenic, Instagram-favorite boutique featuring airy white linen dresses, handcrafted silver cowrie shell jewelry, woven sun umbrellas, and scented candles.',
    googleRating: 4.9,
    googleReviewCount: 240,
    priceLevel: 'premium',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJBoutiqueBohemianChicAsilahAsilah',
    googleMapsUrl: 'https://maps.google.com/?q=Bohemian+Chic+Asilah',
    address: 'Place Al Kharcha, Medina, Asilah',
    landmark: 'Al Kharcha Medina Square',
    coordinates: { lat: 35.4658, lng: -6.0368 },
    distanceText: '2 min walk from Bab Homar',
    tags: ['Bohemian Fashion', 'Linen Dresses', 'Shell Jewelry', 'Resort Wear'],
    paymentMethods: ['cash', 'visa', 'mastercard', 'apple_pay'],
    productCategories: ['White Linen Tunics', 'Silver Shell Necklaces', 'Hand-poured Scented Candles'],
    languagesSpoken: ['French', 'English', 'Spanish', 'Arabic'],
    openingHours: [{ day: 'Mon-Sun', hours: '10:00 - 21:00' }],
    isLocalFavorite: true
  },
  {
    id: 'sh-asi-5',
    city: 'asilah',
    name: 'Galerie d\'Art Aza',
    type: 'concept_store',
    category: 'Art & Sculptures',
    neighborhood: 'Medina',
    description: 'Contemporary gallery space exhibiting modern Moroccan pop art, recycled metal sea-creature sculptures, ceramics, and art books from the Asilah Cultural Arts Festival.',
    googleRating: 4.8,
    googleReviewCount: 130,
    priceLevel: 'premium',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJGalerieDAsilah',
    googleMapsUrl: 'https://maps.google.com/?q=Galerie+Aza+Asilah',
    address: 'Rue de la Kasbah, Asilah',
    landmark: 'Asilah Cultural Center',
    coordinates: { lat: 35.4662, lng: -6.0370 },
    distanceText: '3 min walk from Bab Al Kasbah',
    tags: ['Contemporary Art', 'Metal Sculptures', 'Asilah Festival Art', 'Art Books'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Pop Art Canvas Prints', 'Metal Fish Sculptures', 'Festival Catalogues'],
    languagesSpoken: ['Spanish', 'French', 'English', 'Arabic'],
    openingHours: [{ day: 'Mon-Sat', hours: '10:30 - 19:30' }]
  },
  {
    id: 'sh-asi-6',
    city: 'asilah',
    name: 'Marché Central d\'Asilah',
    type: 'souk_stall',
    category: 'Fresh Seafood & Produce',
    neighborhood: 'Centre Ville',
    description: 'Vibrant local covered market outside the medina walls famous for fresh Atlantic catches—sardines, sea bream, sole—alongside local goat cheeses and regional olives.',
    googleRating: 4.5,
    googleReviewCount: 380,
    priceLevel: 'budget',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJMarchCentralDAsilah',
    googleMapsUrl: 'https://maps.google.com/?q=Marche+Central+Asilah',
    address: 'Avenue Hassan II, Asilah',
    landmark: 'Asilah Grand Mosque (New Town)',
    coordinates: { lat: 35.4640, lng: -6.0345 },
    distanceText: '3 min walk outside Bab Homar gate',
    tags: ['Fresh Atlantic Fish', 'Goat Cheese', 'Fresh Produce', 'Central Market'],
    paymentMethods: ['cash'],
    productCategories: ['Fresh Sole & Sea Bream', 'Goat Cheese Rounds', 'Marinated Olives'],
    languagesSpoken: ['Arabic', 'Spanish', 'French'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:00 - 18:00' }],
    isLocalFavorite: true
  },
  {
    id: 'sh-asi-7',
    city: 'asilah',
    name: 'Herboristerie Sannaj',
    type: 'pharmacy',
    category: 'Spices & Cosmetics',
    neighborhood: 'Medina',
    description: 'Aromatic medina pharmacy stocked with pure cosmetic argan oil, natural loofah sponges, red clay face masks, rose water, and culinary Atlantic sea salt blends.',
    googleRating: 4.7,
    googleReviewCount: 190,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJHerboristerieSannajAsilah',
    googleMapsUrl: 'https://maps.google.com/?q=Herboristerie+Sannaj+Asilah',
    address: 'Rue Bab Homar, Medina, Asilah',
    landmark: 'Bab Homar Entrance Alley',
    coordinates: { lat: 35.4650, lng: -6.0358 },
    distanceText: '1 min walk from Bab Homar gate',
    tags: ['Argan Oil', 'Red Clay Mask', 'Natural Loofah', 'Atlantic Sea Salt'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Cosmetic Argan Elixir', 'Red Ghassoul Masks', 'Sea Salt Herbs', 'Black Soap'],
    languagesSpoken: ['Arabic', 'Spanish', 'French'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 20:30' }]
  },
  {
    id: 'sh-asi-8',
    city: 'asilah',
    name: 'The Mural Photo Studio & Gallery',
    type: 'boutique',
    category: 'Photography & Prints',
    neighborhood: 'Medina',
    description: 'Studio shop selling professional fine-art photography prints, postcards, and canvas framing depicting Asilah’s famous annual street art murals and coastal sunsets.',
    googleRating: 4.9,
    googleReviewCount: 115,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJTheMuralPhotoStudioGalleryAsilah',
    googleMapsUrl: 'https://maps.google.com/?q=Mural+Photo+Studio+Asilah',
    address: 'Rue Al Hakam, Medina, Asilah',
    landmark: 'Asilah Ramparts Tower',
    coordinates: { lat: 35.4668, lng: -6.0372 },
    distanceText: '4 min walk from Bab Al Kasbah',
    tags: ['Fine Art Photography', 'Mural Prints', 'Asilah Postcards', 'Canvas Prints'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Framed Photo Prints', 'Postcard Packs', 'Art Canvas'],
    languagesSpoken: ['Spanish', 'English', 'French', 'Arabic'],
    openingHours: [{ day: 'Mon-Sun', hours: '10:00 - 20:00' }]
  },
  {
    id: 'sh-asi-9',
    city: 'asilah',
    name: 'Asilah Blue & White Linen Shop',
    type: 'boutique',
    category: 'Fashion & Home Textiles',
    neighborhood: 'Medina',
    description: 'Boutique embodying Asilah’s classic blue-and-white color palette with striped linen curtains, blue-rimmed ceramic mugs, cotton throws, and light summer robes.',
    googleRating: 4.8,
    googleReviewCount: 155,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJAsilahBlueWhiteLinenShopAsilah',
    googleMapsUrl: 'https://maps.google.com/?q=Blue+and+White+Asilah',
    address: 'Rue Moulay Ali Cherif, Medina, Asilah',
    landmark: 'Raissouni Palace Gate',
    coordinates: { lat: 35.4655, lng: -6.0365 },
    distanceText: '2 min walk from central medina square',
    tags: ['Blue White Linens', 'Striped Curtains', 'Ceramic Mugs', 'Summer Robes'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Blue-rimmed Mugs', 'Striped Linen Robes', 'Cotton Throw Pillows'],
    languagesSpoken: ['Spanish', 'French', 'English', 'Arabic'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:30 - 20:30' }]
  },
  {
    id: 'sh-asi-10',
    city: 'asilah',
    name: 'The Spice & Salt Garden Asilah',
    type: 'boutique',
    category: 'Spices & Gourmet',
    neighborhood: 'Medina',
    description: 'Clean, fragrant boutique specializing in organic cooking spices, Atlantic mineral salt flakes, custom ras el hanout, wild herb tea mixtures, and amlou almond spread.',
    googleRating: 4.8,
    googleReviewCount: 205,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJTheSpiceSaltGardenAsilahAsilah',
    googleMapsUrl: 'https://maps.google.com/?q=Spice+Garden+Asilah',
    address: 'Rue Ibn Batouta, Medina, Asilah',
    landmark: 'Bab Al Bahr Sea Gate',
    coordinates: { lat: 35.4664, lng: -6.0362 },
    distanceText: '3 min walk from Bab Homar',
    tags: ['Atlantic Sea Salt', 'Organic Spices', 'Ras El Hanout', 'Almond Amlou'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Mineral Sea Salt Flakes', 'Custom Ras El Hanout', 'Wild Herb Teas', 'Fresh Amlou'],
    languagesSpoken: ['Spanish', 'French', 'English', 'Arabic'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 20:30' }]
  }
]
