import { ShopListing } from '../types'

export const elJadidaShops: ShopListing[] = [
  {
    id: 'sh-elj-1',
    city: 'el_jadida',
    name: 'Bazar Mazagan (Portuguese Cistern Antiques)',
    type: 'boutique',
    category: 'Antiques & Collectibles',
    neighborhood: 'Cité Portugaise',
    description: 'Old-world antique shop inside the UNESCO Portuguese Fortress right next to the historic stone Cistern, selling colonial Portuguese coins, brass maritime lanterns, and old maps.',
    googleRating: 4.7,
    googleReviewCount: 230,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJBazarMazaganPortugueseCisternAntiquesElJadida',
    googleMapsUrl: 'https://maps.google.com/?q=Portuguese+Cistern+El+Jadida',
    address: 'Rue de la Citerne, Cité Portugaise, El Jadida',
    landmark: 'Portuguese Cistern (Citerne Portugaise)',
    coordinates: { lat: 33.2562, lng: -8.5085 },
    distanceText: '10 meters from the Portuguese Cistern entrance',
    navSteps: [
      'Enter the stone gate of the Cité Portugaise fortress',
      'Walk down Rue de la Citerne toward the underground water reservoir',
      'The antique shop is located directly adjacent to the cistern ticket kiosk'
    ],
    what3words: 'cistern.fortress.coin',
    tags: ['Portuguese Fort', 'Colonial Coins', 'Maritime Antiques', 'Brass Lanterns'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Colonial Coins', 'Brass Ships Lanterns', 'Vintage Maps', 'Pottery'],
    languagesSpoken: ['Arabic', 'French', 'Portuguese', 'English'],
    phoneNumber: '+212 5233-42150',
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 19:00' }],
    isLocalFavorite: true
  },
  {
    id: 'sh-elj-2',
    city: 'el_jadida',
    name: 'Marché Central d\'El Jadida',
    type: 'souk_stall',
    category: 'Fresh Seafood & Produce',
    neighborhood: 'Centre Ville',
    description: 'Bustling covered municipal market famous for ultra-fresh Atlantic catches—sea urchins, sardines, octopus, red mullet—alongside Doukkala regional olives and fresh produce.',
    googleRating: 4.6,
    googleReviewCount: 480,
    priceLevel: 'budget',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJMarchCentralDElJadida',
    googleMapsUrl: 'https://maps.google.com/?q=Marche+Central+El+Jadida',
    address: 'Avenue Saint Exupéry, El Jadida',
    landmark: 'Parc Mohammed V',
    coordinates: { lat: 33.2530, lng: -8.5040 },
    distanceText: '5 min walk from Place Moulay Hassan',
    tags: ['Fresh Atlantic Seafood', 'Sea Urchins', 'Doukkala Olives', 'Covered Market'],
    paymentMethods: ['cash'],
    productCategories: ['Atlantic Sardines & Mullet', 'Fresh Sea Urchins', 'Spiced Doukkala Olives'],
    languagesSpoken: ['Arabic', 'French'],
    openingHours: [{ day: 'Mon-Sun', hours: '07:30 - 18:00' }],
    isLocalFavorite: true
  },
  {
    id: 'sh-elj-3',
    city: 'el_jadida',
    name: 'El Jadida Coastal Pottery Co-op',
    type: 'cooperative',
    category: 'Ceramics & Pottery',
    neighborhood: 'Route de Safi',
    description: 'Artisan pottery showroom producing distinct ocean-blue and terracotta glazed garden urns, decorative wall plates, and durable cooking tagines.',
    googleRating: 4.6,
    googleReviewCount: 160,
    priceLevel: 'budget',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJElJadidaCoastalPotteryCoOpElJadida',
    googleMapsUrl: 'https://maps.google.com/?q=Poterie+El+Jadida',
    address: 'Route de Safi, El Jadida',
    landmark: 'El Jadida Lighthouse (Phare de Sidi Bouafi)',
    coordinates: { lat: 33.2480, lng: -8.5120 },
    distanceText: '3 min drive from Sidi Bouafi lighthouse',
    tags: ['Ocean Blue Pottery', 'Garden Urns', 'Terracotta Tagines', 'Pottery Co-op'],
    authenticitySeals: ['label_artisanat'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Blue Glazed Garden Pots', 'Terracotta Tagines', 'Decorative Ceramic Plates'],
    languagesSpoken: ['Arabic', 'French'],
    openingHours: [{ day: 'Mon-Sat', hours: '08:30 - 18:00' }],
    workshopVisitable: true
  },
  {
    id: 'sh-elj-4',
    city: 'el_jadida',
    name: 'Cooperative de Tissage Doukkala',
    type: 'cooperative',
    category: 'Textiles & Embroidery',
    neighborhood: 'Centre Ville',
    description: 'Local weaving cooperative famous for producing heavy geometric Doukkala wool blankets, striped cotton beach towels, and embroidered table runners.',
    googleRating: 4.8,
    googleReviewCount: 125,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJCooperativeDeTissageDoukkalaElJadida',
    googleMapsUrl: 'https://maps.google.com/?q=Tissage+Doukkala+El+Jadida',
    address: 'Avenue Suez, El Jadida',
    landmark: 'Théâtre Afifi El Jadida',
    coordinates: { lat: 33.2515, lng: -8.5030 },
    distanceText: '3 min walk from Place Hansali',
    tags: ['Doukkala Embroidery', 'Wool Blankets', 'Cotton Beach Towels', 'Women Cooperative'],
    authenticitySeals: ['wfto'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Doukkala Wool Blankets', 'Striped Cotton Towels', 'Embroidered Table Runners'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:00 - 18:00' }]
  },
  {
    id: 'sh-elj-5',
    city: 'el_jadida',
    name: 'Bazar Bab Al-Bahr Fortress',
    type: 'boutique',
    category: 'Souvenirs & Leather',
    neighborhood: 'Cité Portugaise',
    description: 'Boutique along the fortress sea wall stocking vegetable-tanned leather weekender bags, yellow slippers, brass lanterns, and painted ceramic bowls.',
    googleRating: 4.7,
    googleReviewCount: 190,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJBazarBabAlBahrFortressElJadida',
    googleMapsUrl: 'https://maps.google.com/?q=Bazar+Bab+Al+Bahr+El+Jadida',
    address: 'Rue Bastion de San Sebastian, Cité Portugaise, El Jadida',
    landmark: 'San Sebastian Sea Bastion',
    coordinates: { lat: 33.2568, lng: -8.5078 },
    distanceText: '2 min walk from Portuguese Cistern',
    tags: ['Fortress Souvenirs', 'Leather Bags', 'Yellow Babouches', 'Sea Wall'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Leather Travel Duffels', 'Yellow Slippers', 'Brass Lanterns'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Portuguese'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 19:30' }]
  },
  {
    id: 'sh-elj-6',
    city: 'el_jadida',
    name: 'Herboristerie Royale El Jadida',
    type: 'pharmacy',
    category: 'Spices & Cosmetics',
    neighborhood: 'Centre Ville',
    description: 'Trusted traditional pharmacy offering pure Souss argan oil, black soap, eucalyptus honey, orange blossom water, and Doukkala culinary spices.',
    googleRating: 4.8,
    googleReviewCount: 210,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJHerboristerieRoyaleElJadidaElJadida',
    googleMapsUrl: 'https://maps.google.com/?q=Herboristerie+Royale+El+Jadida',
    address: 'Avenue Zarqtouni, El Jadida',
    landmark: 'Poste Maroc Central',
    coordinates: { lat: 33.2522, lng: -8.5050 },
    distanceText: '2 min walk from Central Post Office',
    tags: ['Argan Oil', 'Eucalyptus Honey', 'Black Soap', 'Doukkala Spices'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Pure Cosmetic Argan Oil', 'Eucalyptus Honey', 'Ghassoul Clay', 'Orange Blossom Elixir'],
    languagesSpoken: ['Arabic', 'French'],
    openingHours: [{ day: 'Mon-Sat', hours: '08:30 - 20:00' }]
  },
  {
    id: 'sh-elj-7',
    city: 'el_jadida',
    name: 'Boutique Caftan Al Mazagan',
    type: 'boutique',
    category: 'Fashion & Caftans',
    neighborhood: 'Centre Ville',
    description: 'High-fashion traditional dress atelier specializing in modern tailored caftans, silk takchita gowns, embroidered gandouras, and bridal wear.',
    googleRating: 4.9,
    googleReviewCount: 140,
    priceLevel: 'premium',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJBoutiqueCaftanAlMazaganElJadida',
    googleMapsUrl: 'https://maps.google.com/?q=Caftan+Al+Mazagan+El+Jadida',
    address: 'Boulevard Nabeul, El Jadida',
    landmark: 'Hôtel Casablanca El Jadida',
    coordinates: { lat: 33.2505, lng: -8.5020 },
    distanceText: '4 min walk from beach promenade',
    tags: ['Haute Couture Caftan', 'Silk Takchita', 'Bridal Gowns', 'Tailored Fashion'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Silk Embroidered Caftans', 'Bridal Takchitas', 'Sfifa Trim Gandouras'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:30 - 20:00' }]
  },
  {
    id: 'sh-elj-8',
    city: 'el_jadida',
    name: 'Doukkala Honey & Amlou House',
    type: 'boutique',
    category: 'Gourmet Food & Honey',
    neighborhood: 'Centre Ville',
    description: 'Specialty food boutique providing pure eucalyptus, thyme, and wildflower honey from the Doukkala plains, alongside almond-and-argan amlou paste.',
    googleRating: 4.8,
    googleReviewCount: 175,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJDoukkalaHoneyAmlouHouseElJadida',
    googleMapsUrl: 'https://maps.google.com/?q=Doukkala+Honey+El+Jadida',
    address: 'Avenue Ibn Khaldoun, El Jadida',
    landmark: 'Place de la Comédie',
    coordinates: { lat: 33.2538, lng: -8.5060 },
    distanceText: '3 min walk from Municipal Market',
    tags: ['Eucalyptus Honey', 'Doukkala Honey', 'Almond Amlou', 'Gourmet Food'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Pure Eucalyptus Honey', 'Thyme Honey', 'Almond-Argan Amlou Dip'],
    languagesSpoken: ['Arabic', 'French'],
    openingHours: [{ day: 'Mon-Sat', hours: '08:30 - 20:00' }]
  },
  {
    id: 'sh-elj-9',
    city: 'el_jadida',
    name: 'Bazar Les Remparts Mazagan',
    type: 'boutique',
    category: 'Decor & Lamps',
    neighborhood: 'Cité Portugaise',
    description: 'Rooftop fortress shop offering panoramic ocean views over the Portuguese ramparts while stocking brass filigree lamps, leather poufs, and ceramics.',
    googleRating: 4.7,
    googleReviewCount: 165,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJBazarLesRempartsMazaganElJadida',
    googleMapsUrl: 'https://maps.google.com/?q=Bazar+Remparts+Mazagan+El+Jadida',
    address: 'Rue Rampart Nord, Cité Portugaise, El Jadida',
    landmark: 'Portuguese Ramparts Lookout',
    coordinates: { lat: 33.2565, lng: -8.5070 },
    distanceText: '3 min walk from fortress entrance',
    tags: ['Rooftop Shop', 'Rampart Views', 'Brass Filigree Lamps', 'Leather Poufs'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Brass Filigree Hanging Lamps', 'Leather Ottoman Poufs', 'Ceramic Bowls'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 19:30' }]
  },
  {
    id: 'sh-elj-10',
    city: 'el_jadida',
    name: 'Leather Craft Atelier Ahmed',
    type: 'designer_atelier',
    category: 'Leather Goods',
    neighborhood: 'Cité Portugaise',
    description: 'Intimate fortress leather workshop where master craftsman Ahmed custom-makes leather belts, watch straps, and wallets on the spot.',
    googleRating: 4.9,
    googleReviewCount: 130,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJLeatherCraftAtelierAhmedElJadida',
    googleMapsUrl: 'https://maps.google.com/?q=Leather+Atelier+Ahmed+El+Jadida',
    address: 'Derb El Houssoun, Cité Portugaise, El Jadida',
    landmark: 'Porto-Morisco Gate',
    coordinates: { lat: 33.2558, lng: -8.5080 },
    distanceText: '1 min walk from Portuguese Cistern',
    tags: ['Custom Leather', 'Handmade Belts', 'Watch Straps', 'Master Leather Crafter'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Custom Stitched Leather Belts', 'Handmade Leather Wallets', 'Leather Watch Straps'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:00 - 18:30' }],
    workshopVisitable: true
  }
]
