import { ShopListing } from '../types';

/**
 * ESSAOUIRA SHOP LISTINGS DATA
 * 20 Authentic Touristic Listings in Essaouira (Medina, Kasbah, Mellah, Skala Area, Port Area)
 */
export const essaouiraShopListings: ShopListing[] = [
  {
    id: 'sh-ess-1',
    city: 'essaouira',
    name: 'Coopérative Féminine Marjana Argan',
    type: 'cooperative',
    category: 'Spices & Cosmetics',
    neighborhood: 'Medina',
    description: 'Pioneering fair-trade women’s argan cooperative located 14 km outside Essaouira. Offers live extraction demonstrations of cosmetic and culinary Argan oil, Amlou almond paste, and black soap.',
    googleRating: 4.2,
    googleReviewCount: 800,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJCoopRativeFMinineMarjanaArganEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Cooperative+Marjana+Essaouira',
    address: 'Route de Marrakech (N8), Douar Ait Sraidi, 14 km from Essaouira',
    landmark: 'Route de Marrakech (N8)',
    coordinates: { lat: 31.5200, lng: -9.6400 },
    distanceText: '20 min drive (14 km east) from Essaouira',
    navSteps: [
      'Drive 14 km east from Essaouira along the N8 Route de Marrakech',
      'Look for the large sign on the left with argan tree orchards',
      'The cooperative facility features processing rooms and a garden showroom'
    ],
    what3words: 'argan.press.women',
    tags: ['Pure Argan Oil', 'Fair Trade', 'Amlou Paste', 'Women Co-op'],
    authenticitySeals: ['wfto', 'label_artisanat'],
    paymentMethods: ['cash', 'visa', 'mastercard', 'apple_pay'],
    productCategories: ['Cosmetic Argan Oil', 'Culinary Argan Oil', 'Amlou Paste', 'Black Soap', 'Prickly Pear Oil'],
    languagesSpoken: ['Arabic', 'French', 'English', 'German'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:30 - 19:30' }],
    shipping: { available: true, partner: 'dhl' }
  },
  {
    id: 'sh-ess-2',
    city: 'essaouira',
    name: 'Coopérative Artisanale du Bois de Thuya',
    type: 'designer_atelier',
    category: 'Antiques & Woodwork',
    neighborhood: 'Skala Area',
    description: 'Master artisan woodworkers collective under the historic ramparts of Skala de la Ville. Carves fragrant thuya wood burls into secret boxes, chessboards, and inlaid tables.',
    googleRating: 4.8,
    googleReviewCount: 620,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJCoopRativeArtisanaleDuBoisDeThuyaEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Skala+de+la+Ville+Essaouira',
    address: 'Rue Skala de la Ville, Medina, Essaouira',
    landmark: 'Skala de la Ville Cannon Battery',
    coordinates: { lat: 31.5135, lng: -9.7715 },
    distanceText: 'Located under the sea rampart arches',
    tags: ['Thuya Wood', 'Skala Ramparts', 'Master Craftsman', 'Aromatic Wood'],
    authenticitySeals: ['label_artisanat', 'maalem_certified'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Thuya Secret Boxes', 'Inlaid Chess Sets', 'Carved Mirrors', 'Salad Bowls'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:30 - 19:30' }],
    workshopVisitable: true
  },
  {
    id: 'sh-ess-3',
    city: 'essaouira',
    name: 'Histoire de Filles Concept Store',
    type: 'concept_store',
    category: 'Fashion & Design',
    neighborhood: 'Kasbah',
    description: 'Chic bohemian concept boutique in the Kasbah of Essaouira selling designer linen tunics, palm leaf beach totes, silver jewelry, and fragrant candles.',
    googleRating: 4.5,
    googleReviewCount: 85,
    priceLevel: 'premium',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJHistoireDeFillesConceptStoreEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Histoire+de+Filles+Essaouira',
    address: '1 Rue Mohammed Ben Massoud, Médina, Essaouira',
    landmark: 'Place Moulay Hassan',
    coordinates: { lat: 31.5115, lng: -9.7695 },
    distanceText: '2 min walk from Place Moulay Hassan',
    tags: ['Concept Store', 'Boho Chic', 'Linen Tunics', 'Kasbah'],
    paymentMethods: ['cash', 'visa', 'mastercard', 'apple_pay'],
    productCategories: ['Linen Dresses', 'Beach Totes', 'Silver Rings', 'Design Ceramics'],
    languagesSpoken: ['French', 'English', 'Arabic'],
    openingHours: [{ day: 'Mon-Sun', hours: '10:00 - 19:30' }]
  },
  {
    id: 'sh-ess-4',
    city: 'essaouira',
    name: 'Bazar Berbère Bijoux d’Argent',
    type: 'souk_stall',
    category: 'Jewelry & Silver',
    neighborhood: 'Medina',
    description: 'Historic silver shop on Rue Souss selling authentic Jewish-Moroccan and Amazigh silver enamel jewelry, heavy cuffs, and amber beads.',
    googleRating: 4.6,
    googleReviewCount: 210,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJBazarBerbReBijouxDArgentEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Rue+Souss+Essaouira',
    address: 'Rue Souss, Medina, Essaouira',
    landmark: 'Souss Market Archway',
    coordinates: { lat: 31.5128, lng: -9.7680 },
    distanceText: '3 min walk from Place Moulay Hassan',
    tags: ['Amazigh Silver', 'Enamel Cuffs', 'Amber Beads', 'Jewish Heritage'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Enamel Silver Cuffs', 'Fibula Pins', 'Amber Necklaces'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 20:00' }]
  },
  {
    id: 'sh-ess-5',
    city: 'essaouira',
    name: 'Galerie Kasbah d’Art & Tapis Mogador',
    type: 'boutique',
    category: 'Carpet & Textiles',
    neighborhood: 'Kasbah',
    description: 'Respected art and carpet gallery housed in a 18th-century merchant house in the Kasbah. Rare Chiadma and Haha tribal wool rugs, plus local artwork.',
    googleRating: 4.8,
    googleReviewCount: 340,
    priceLevel: 'premium',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJGalerieKasbahDArtTapisMogadorEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Galerie+Kasbah+Essaouira',
    address: '4 Rue Tetouan, Kasbah, Essaouira',
    landmark: 'Kasbah Ramparts / Rue Tetouan',
    coordinates: { lat: 31.5110, lng: -9.7700 },
    distanceText: '1 min walk from Place Moulay Hassan',
    tags: ['Chiadma Rugs', 'Haha Weaves', 'Art Gallery', 'Kasbah Riad'],
    authenticitySeals: ['label_artisanat'],
    paymentMethods: ['cash', 'visa', 'mastercard', 'amex'],
    productCategories: ['Tribal Wool Rugs', 'Flat-Woven Kilims', 'Local Paintings'],
    languagesSpoken: ['Arabic', 'French', 'English', 'German'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 19:30' }],
    shipping: { available: true, partner: 'dhl' }
  },
  {
    id: 'sh-ess-6',
    city: 'essaouira',
    name: 'Coopérative L’Arganeraie d’Essaouira',
    type: 'cooperative',
    category: 'Spices & Cosmetics',
    neighborhood: 'Medina',
    description: 'Certified fair-trade women’s cooperative on Avenue Oqba Ibn Nafaa. Offers cold-pressed culinary argan oil toasted over wood fires and cosmetic serums.',
    googleRating: 4.7,
    googleReviewCount: 620,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJCoopRativeLArganeraieDEssaouiraEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Avenue+Oqba+Ibn+Nafaa+Essaouira',
    address: 'Avenue Oqba Ibn Nafaa, Medina, Essaouira',
    landmark: 'Bab Sbaa Gate',
    coordinates: { lat: 31.5122, lng: -9.7670 },
    distanceText: '2 min walk from Bab Sbaa',
    tags: ['Wood-Toasted Argan Oil', 'Fair Trade', 'Women Co-op'],
    authenticitySeals: ['wfto', 'label_artisanat'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Toasted Culinary Argan Oil', 'Argan Face Serum', 'Black Soap'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 19:30' }]
  },
  {
    id: 'sh-ess-7',
    city: 'essaouira',
    name: 'Marché aux Poissons & Epices du Port',
    type: 'souk_stall',
    category: 'Spices & Cosmetics',
    neighborhood: 'Port Area',
    description: 'Vibrant outdoor fish and spice market at the entrance of the blue-boat fishing port. Sells rock salt, fish barbecue spice rubs, and cumin.',
    googleRating: 4.5,
    googleReviewCount: 1850,
    priceLevel: 'budget',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJMarchAuxPoissonsEpicesDuPortEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Port+of+Essaouira',
    address: 'Port d’Essaouira Entrance, Essaouira',
    landmark: 'Sqala du Port',
    coordinates: { lat: 31.5085, lng: -9.7710 },
    distanceText: '1 min walk from Sqala du Port',
    tags: ['Fishing Port', 'Fish Rub Spices', 'Blue Boats', 'Rock Salt'],
    paymentMethods: ['cash'],
    productCategories: ['Fish BBQ Spice Rub', 'Rock Salt', 'Sea Cumin'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:00 - 17:00' }]
  },
  {
    id: 'sh-ess-8',
    city: 'essaouira',
    name: 'Boutique Tissages des Artisans',
    type: 'cooperative',
    category: 'Carpet & Textiles',
    neighborhood: 'Medina',
    description: 'Medina weaver workshop creating thick cotton and cactus silk beach blankets, pestemal towels, and colorful striped curtains.',
    googleRating: 4.6,
    googleReviewCount: 310,
    priceLevel: 'budget',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJBoutiqueTissagesDesArtisansEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Medina+Essaouira',
    address: 'Rue Laalouj, Medina, Essaouira',
    landmark: 'Sidi Mohamed Ben Abdallah Museum',
    coordinates: { lat: 31.5130, lng: -9.7690 },
    distanceText: '2 min walk from Museum Sidi Mohamed Ben Abdallah',
    tags: ['Pestemal Towels', 'Beach Blankets', 'Cotton Throws'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Beach Blankets', 'Pestemal Towels', 'Striped Cushions'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 19:30' }]
  },
  {
    id: 'sh-ess-9',
    city: 'essaouira',
    name: 'Raffia Surf & Craft Boutique',
    type: 'boutique',
    category: 'Fashion & Design',
    neighborhood: 'Mellah',
    description: 'Unique coastal boutique crafting sustainable raffia palm fiber shoes, woven hats, raffia totes, and relaxed surf apparel.',
    googleRating: 4.7,
    googleReviewCount: 290,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJRaffiaSurfCraftBoutiqueEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Mellah+Essaouira',
    address: 'Rue Zerktouni, Mellah, Essaouira',
    landmark: 'Synagogue Smail Attia',
    coordinates: { lat: 31.5152, lng: -9.7675 },
    distanceText: '4 min walk from Bab Doukkala',
    tags: ['Raffia Shoes', 'Sustainable Fiber', 'Surf Accessories', 'Handmade'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Raffia Shoes', 'Raffia Hats', 'Woven Totes'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:30 - 19:00' }]
  },
  {
    id: 'sh-ess-10',
    city: 'essaouira',
    name: 'Bazar La Skala Leather & Crafts',
    type: 'souk_stall',
    category: 'Leather & Shoes',
    neighborhood: 'Skala Area',
    description: 'Charming shop next to the Skala ramparts specializing in soft goatskin leather duffel bags, yellow babouches, and embossed leather journals.',
    googleRating: 4.5,
    googleReviewCount: 420,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJBazarLaSkalaLeatherCraftsEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Skala+Essaouira',
    address: 'Rue de la Skala, Medina, Essaouira',
    landmark: 'Skala de la Ville Ramparts',
    coordinates: { lat: 31.5138, lng: -9.7712 },
    distanceText: '1 min walk from Skala Ramparts',
    tags: ['Leather Duffels', 'Embossed Journals', 'Yellow Babouches'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Leather Backpacks', 'Embossed Journals', 'Babouche Slippers'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 19:30' }]
  },
  {
    id: 'sh-ess-11',
    city: 'essaouira',
    name: 'Herboristerie Mogador Skala',
    type: 'pharmacy',
    category: 'Spices & Cosmetics',
    neighborhood: 'Kasbah',
    description: 'Aromatic herbalist shop in the Kasbah selling organic cumin, saffron from Taliouine, pure eucalyptus honey, and dried lavender.',
    googleRating: 4.7,
    googleReviewCount: 380,
    priceLevel: 'budget',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJHerboristerieMogadorSkalaEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Kasbah+Essaouira',
    address: 'Rue Ibn Rochd, Kasbah, Essaouira',
    landmark: 'Place Moulay Hassan',
    coordinates: { lat: 31.5118, lng: -9.7692 },
    distanceText: '2 min walk from Place Moulay Hassan',
    tags: ['Herbal Apothecary', 'Eucalyptus Honey', 'Organic Cumin'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Saffron', 'Eucalyptus Honey', 'Organic Spices', 'Rose Water'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 20:00' }]
  },
  {
    id: 'sh-ess-12',
    city: 'essaouira',
    name: 'Atelier de Sculptures sur Bois de Cèdre',
    type: 'designer_atelier',
    category: 'Antiques & Woodwork',
    neighborhood: 'Medina',
    description: 'Artist-run studio crafting sculptural wooden vessels, cedar cutting boards, and smooth turned thuya coasters.',
    googleRating: 4.8,
    googleReviewCount: 210,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJAtelierDeSculpturesSurBoisDeCDreEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Medina+Essaouira',
    address: 'Rue Touahen, Medina, Essaouira',
    landmark: 'Clock Tower',
    coordinates: { lat: 31.5125, lng: -9.7682 },
    distanceText: '3 min walk from Place Moulay Hassan',
    tags: ['Cedar Cutting Boards', 'Wooden Sculptures', 'Thuya Coasters'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Cedar Cutting Boards', 'Wood Sculptures', 'Thuya Bowls'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:00 - 19:00' }]
  },
  {
    id: 'sh-ess-13',
    city: 'essaouira',
    name: 'Avande Design Studio & Ceramics',
    type: 'concept_store',
    category: 'Ceramics & Pottery',
    neighborhood: 'Kasbah',
    description: 'Modern craft concept space featuring matte black glazed ceramics, linen tablecloths, and contemporary brass lamps.',
    googleRating: 4.9,
    googleReviewCount: 160,
    priceLevel: 'premium',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJAvandeDesignStudioCeramicsEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Kasbah+Essaouira',
    address: 'Rue el Attarine, Kasbah, Essaouira',
    landmark: 'Place Moulay Hassan',
    coordinates: { lat: 31.5112, lng: -9.7698 },
    distanceText: '2 min walk from Place Moulay Hassan',
    tags: ['Matte Ceramics', 'Linen Linens', 'Modern Design'],
    paymentMethods: ['cash', 'visa', 'mastercard', 'apple_pay'],
    productCategories: ['Matte Ceramics', 'Linen Napkins', 'Brass Lamps'],
    languagesSpoken: ['French', 'English', 'Arabic'],
    openingHours: [{ day: 'Tue-Sun', hours: '10:00 - 19:00' }]
  },
  {
    id: 'sh-ess-14',
    city: 'essaouira',
    name: 'Souk Jdid Antique Market',
    type: 'souk_stall',
    category: 'Antiques & Woodwork',
    neighborhood: 'Medina',
    description: 'Historic covered market hall (Souk Jdid) filled with vintage brass lamps, old wooden fishing boat planks, and antique copper teapots.',
    googleRating: 4.5,
    googleReviewCount: 510,
    priceLevel: 'budget',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJSoukJdidAntiqueMarketEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Souk+Jdid+Essaouira',
    address: 'Avenue Istiqlal, Souk Jdid, Essaouira',
    landmark: 'Souk Jdid Clock Tower',
    coordinates: { lat: 31.5135, lng: -9.7665 },
    distanceText: '4 min walk from Bab Marrakech',
    tags: ['Covered Market', 'Vintage Copper', 'Reclaimed Boat Wood'],
    paymentMethods: ['cash'],
    productCategories: ['Vintage Copperware', 'Reclaimed Wood Frames', 'Brass Lamps'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:30 - 19:00' }]
  },
  {
    id: 'sh-ess-15',
    city: 'essaouira',
    name: 'Boutique Maroquinerie Mogador',
    type: 'boutique',
    category: 'Leather & Shoes',
    neighborhood: 'Medina',
    description: 'Family leather store near Bab Marrakech creating custom leather sandals, goat skin weekend bags, and leather laptop sleeves.',
    googleRating: 4.6,
    googleReviewCount: 270,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJBoutiqueMaroquinerieMogadorEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Bab+Marrakech+Essaouira',
    address: 'Avenue Cairo, Medina, Essaouira',
    landmark: 'Bab Marrakech Gate',
    coordinates: { lat: 31.5120, lng: -9.7655 },
    distanceText: '1 min walk inside Bab Marrakech',
    tags: ['Custom Leather Sandals', 'Laptop Sleeves', 'Goat Leather'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Leather Sandals', 'Laptop Sleeves', 'Travel Bags'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 19:30' }]
  },
  {
    id: 'sh-ess-16',
    city: 'essaouira',
    name: 'Coopérative Tissage de Laine Haha',
    type: 'cooperative',
    category: 'Carpet & Textiles',
    neighborhood: 'Mellah',
    description: 'Rural weavers outlet representing women from the Haha region. Sells heavy hand-spun wool blankets, Berber pom-pom throws, and floor cushions.',
    googleRating: 4.7,
    googleReviewCount: 210,
    priceLevel: 'budget',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJCoopRativeTissageDeLaineHahaEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Mellah+Essaouira',
    address: 'Rue du Mellah, Medina, Essaouira',
    landmark: 'Bab Doukkala',
    coordinates: { lat: 31.5155, lng: -9.7670 },
    distanceText: '3 min walk from Bab Doukkala',
    tags: ['Haha Region Weavers', 'Pom-Pom Throws', 'Hand Spun Wool'],
    authenticitySeals: ['wfto', 'label_artisanat'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Pom-Pom Throws', 'Heavy Wool Blankets', 'Floor Cushions'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:00 - 18:30' }]
  },
  {
    id: 'sh-ess-17',
    city: 'essaouira',
    name: 'Bijouterie Amazigh Mogador',
    type: 'boutique',
    category: 'Jewelry & Silver',
    neighborhood: 'Kasbah',
    description: 'Fine silver artisan creating traditional hand-engraved Berber fibula brooches, silver coral rings, and delicate ear cuffs.',
    googleRating: 4.8,
    googleReviewCount: 180,
    priceLevel: 'premium',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJBijouterieAmazighMogadorEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Kasbah+Essaouira',
    address: 'Rue Chaban, Kasbah, Essaouira',
    landmark: 'Place Moulay Hassan',
    coordinates: { lat: 31.5116, lng: -9.7690 },
    distanceText: '2 min walk from Place Moulay Hassan',
    tags: ['Silver Fibula', 'Coral Rings', 'Hand Engraved Silver'],
    authenticitySeals: ['label_artisanat'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Silver Fibulas', 'Coral Rings', 'Ear Cuffs'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:30 - 19:00' }]
  },
  {
    id: 'sh-ess-18',
    city: 'essaouira',
    name: 'Boutique Instruments Gnawa & Musique',
    type: 'boutique',
    category: 'Artisan Crafts',
    neighborhood: 'Medina',
    description: 'Historic music shop making authentic Gnawa guembri lute instruments, metal krakeb castanets, goat skin drums, and incense.',
    googleRating: 4.9,
    googleReviewCount: 320,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJBoutiqueInstrumentsGnawaMusiqueEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Medina+Essaouira',
    address: 'Rue el Hajjali, Medina, Essaouira',
    landmark: 'Dar Souiri Cultural Center',
    coordinates: { lat: 31.5128, lng: -9.7675 },
    distanceText: '2 min walk from Dar Souiri',
    tags: ['Gnawa Guembri', 'Krakeb Castanets', 'World Music', 'Heritage Instrument'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Guembri Lutes', 'Krakeb Castanets', 'Goat Skin Drums'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:30 - 20:00' }]
  },
  {
    id: 'sh-ess-19',
    city: 'essaouira',
    name: 'Atelier de Peinture Mogador Art',
    type: 'designer_atelier',
    category: 'Artisan Crafts',
    neighborhood: 'Kasbah',
    description: 'Local Naive style painter studio selling vivid original acrylic paintings on canvas depicting fishermen, gulls, blue doors, and wind surfers.',
    googleRating: 4.7,
    googleReviewCount: 150,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJAtelierDePeintureMogadorArtEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Kasbah+Essaouira',
    address: 'Rue de la Skala, Kasbah, Essaouira',
    landmark: 'Skala Ramparts',
    coordinates: { lat: 31.5132, lng: -9.7708 },
    distanceText: '1 min walk from Skala Ramparts',
    tags: ['Naive Art', 'Original Paintings', 'Wind Surfers Art'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Acrylic Canvas Paintings', 'Art Prints', 'Painted Tiles'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '10:00 - 19:00' }]
  },
  {
    id: 'sh-ess-20',
    city: 'essaouira',
    name: 'Pharmacie Naturelle Souss Argan',
    type: 'pharmacy',
    category: 'Spices & Cosmetics',
    neighborhood: 'Medina',
    description: 'Certified organic shop near Bab Sbaa offering pure rose water, prickly pear oil, ghassoul clay facial masks, and eucalyptus bath salt.',
    googleRating: 4.6,
    googleReviewCount: 280,
    priceLevel: 'budget',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJPharmacieNaturelleSoussArganEssaouira',
    googleMapsUrl: 'https://maps.google.com/?q=Bab+Sbaa+Essaouira',
    address: 'Avenue Cairo near Bab Sbaa, Medina, Essaouira',
    landmark: 'Bab Sbaa Gate',
    coordinates: { lat: 31.5124, lng: -9.7662 },
    distanceText: '1 min walk from Bab Sbaa',
    tags: ['Prickly Pear Oil', 'Ghassoul Mask', 'Eucalyptus Salt'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Prickly Pear Oil', 'Rose Water', 'Ghassoul Clay', 'Eucalyptus Salt'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:30 - 19:30' }]
  }
];
