import { ShopListing } from '../types';

/**
 * FES SHOP LISTINGS DATA
 * 20 Authentic Touristic Listings in Fes Medina & Crafts Districts
 */
export const fesShopListings: ShopListing[] = [
  {
    id: 'sh-fes-1',
    city: 'fes',
    name: 'Terrasse Tannerie Chouara Leather Shops',
    type: 'cooperative',
    category: 'Leather & Shoes',
    neighborhood: 'Medina',
    description: 'Master leather craftsmen terraces overlooking the 11th-century Chouara Tannery pits. Sells hand-dyed sheepskin jackets, babouche slippers, and leather poufs.',
    googleRating: 4.6,
    googleReviewCount: 840,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJTerrasseTannerieChouaraLeatherShopsFes',
    googleMapsUrl: 'https://maps.google.com/?q=Chouara+Tannery+Fes',
    address: 'Derb Chaouwara, Fes el-Bali, Fes',
    landmark: 'Chouara Tannery Entrance',
    coordinates: { lat: 34.0664, lng: -4.9722 },
    distanceText: '8 min walk from Place Seffarine',
    navSteps: [
      'From Place Seffarine, take the alley leading northeast along the copper coppersmith sounds',
      'Follow signs for Tannerie Chouara up the cobblestone ramp',
      'Enter the leather terrace showroom on the right'
    ],
    what3words: 'tannery.dye.leather',
    tags: ['Leather', 'Handmade', 'Iconic View', 'Maalem Certified', 'live-workshop'],
    authenticitySeals: ['label_artisanat', 'maalem_certified'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Leather Jackets', 'Babouches', 'Poufs', 'Travel Bags'],
    languagesSpoken: ['Arabic', 'Darija', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:30 - 19:30' }],
    workshopVisitable: true,
    atmosphere: 'Bustling historic artisan terrace'
  },
  {
    id: 'sh-fes-2',
    city: 'fes',
    name: 'Art Naji Fes Zellige & Ceramics',
    type: 'designer_atelier',
    category: 'Ceramics & Pottery',
    neighborhood: 'Fes el-Bali',
    description: 'Premier hand-painted Fes cobalt blue pottery and hand-cut zellige mosaic tile workshop. Live demonstrations of traditional clay firing.',
    googleRating: 4.7,
    googleReviewCount: 1120,
    priceLevel: 'premium',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJArtNajiFesZelligeCeramicsFes',
    googleMapsUrl: 'https://maps.google.com/?q=Art+Naji+Fes',
    address: 'Complexe Artisanal, Ain Nokbi, Fes',
    landmark: 'Ain Nokbi Potter Quarter',
    coordinates: { lat: 34.0608, lng: -4.9497 },
    distanceText: '10 min taxi from Bab Bou Jeloud',
    what3words: 'cobalt.clay.mosaic',
    tags: ['Ceramics', 'Zellige', 'Worldwide Shipping', 'Demonstrations', 'fixed-price', 'live-workshop'],
    authenticitySeals: ['label_artisanat', 'zellige_de_fes'],
    paymentMethods: ['cash', 'visa', 'mastercard', 'apple_pay'],
    productCategories: ['Cobalt Blue Bowls', 'Zellige Tables', 'Fountains', 'Tagines'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:00 - 19:00' }],
    shipping: { available: true, partner: 'dhl' },
    workshopVisitable: true
  },
  {
    id: 'sh-fes-3',
    city: 'fes',
    name: 'Place Seffarine Coppersmiths',
    type: 'souk_stall',
    category: 'Brassware & Metalwork',
    neighborhood: 'Seffarine',
    description: 'Open-air brass and copper artisan square where master craftsmen hammer brass teapots, buckets, trays, and carved lanterns by hand.',
    googleRating: 4.8,
    googleReviewCount: 950,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJPlaceSeffarineCoppersmithsFes',
    googleMapsUrl: 'https://maps.google.com/?q=Place+Seffarine+Fes',
    address: 'Place Seffarine, Fes el-Bali, Fes',
    landmark: 'Karakouine Library & Seffarine Square',
    coordinates: { lat: 34.0648, lng: -4.9733 },
    distanceText: '5 min walk from Al-Qarawiyyin Mosque',
    navSteps: [
      'From Al-Qarawiyyin Library, follow the rhythmic metal hammering sound',
      'Enter the open square shaded by the grand plane tree',
      'Stalls line all four sides of the historic plaza'
    ],
    tags: ['Coppersmiths', 'Teapots', 'Brass Lanterns', 'Historic Square', 'live-workshop'],
    authenticitySeals: ['label_artisanat'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Brass Teapots', 'Carved Trays', 'Hammered Buckets', 'Copper Vessels'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:00 - 19:00' }],
    workshopVisitable: true
  },
  {
    id: 'sh-fes-4',
    city: 'fes',
    name: 'Palais de la Babouche & Broderie',
    type: 'boutique',
    category: 'Leather & Shoes',
    neighborhood: 'Batha',
    description: 'Famous historic shop specializing in traditional Fassi gold-embroidered silk and fine goatskin babouche slippers for men and women.',
    googleRating: 4.5,
    googleReviewCount: 310,
    priceLevel: 'budget',
    pricingModel: 'mixed',
    isVerified: true,
    googlePlaceId: 'ChIJPalaisDeLaBaboucheBroderieFes',
    googleMapsUrl: 'https://maps.google.com/?q=Bab+Bou+Jeloud+Fes',
    address: 'Rue Talaa Kebira near Place Batha, Fes',
    landmark: 'Batha Museum',
    coordinates: { lat: 34.0615, lng: -4.9825 },
    distanceText: '3 min walk from Bab Bou Jeloud',
    tags: ['Babouches', 'Gold Embroidery', 'Fassi Slippers', 'leather'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Goatskin Slippers', 'Bridal Babouches', 'Silk Slippers'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 20:00' }]
  },
  {
    id: 'sh-fes-5',
    city: 'fes',
    name: 'Herboristerie Traditionnelle Chez Rachid',
    type: 'pharmacy',
    category: 'Spices & Cosmetics',
    neighborhood: 'Medina',
    description: 'Traditional certified apothecary in Fes Medina stocking organic cold-pressed Argan oil, saffron from Taliouine, Nigella seed oils, and dried Damask rosebuds.',
    googleRating: 4.7,
    googleReviewCount: 410,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJHerboristerieTraditionnelleChezRachidFes',
    googleMapsUrl: 'https://maps.google.com/?q=Herboristerie+Chez+Rachid+Fes',
    address: 'Rue Attarine, Talaa Kebira, Fes el-Bali, Fes',
    landmark: 'Attarine Madrasa / Talaa Kebira',
    coordinates: { lat: 34.0652, lng: -4.9745 },
    distanceText: '5 min walk from Bab Bou Jeloud down Talaa Kebira',
    tags: ['Argan Oil', 'Organic Saffron', 'Herbal Remedies', 'Spices', 'fixed-price'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Pure Argan Oil', 'Saffron', 'Black Soap', 'Rose Water', 'Natural Clay'],
    languagesSpoken: ['Arabic', 'French', 'English', 'German'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 20:00' }]
  },
  {
    id: 'sh-fes-6',
    city: 'fes',
    name: 'Coin Berbère Carpet Cooperative',
    type: 'cooperative',
    category: 'Carpet & Textiles',
    neighborhood: 'Medina',
    description: 'Fair-trade weavers collective featuring antique Tribal kilims, Middle Atlas Beni Ourain wool rugs, and hand-woven Fes embroidery.',
    googleRating: 4.7,
    googleReviewCount: 430,
    priceLevel: 'premium',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJCoinBerbReCarpetCooperativeFes',
    googleMapsUrl: 'https://maps.google.com/?q=Place+Nejjarine+Fes',
    address: 'Place Nejjarine, Talaa Kebira, Fes el-Bali, Fes',
    landmark: 'Place Nejjarine / Fondouk Nejjarine',
    coordinates: { lat: 34.0642, lng: -4.9765 },
    distanceText: '6 min walk from Bab Bou Jeloud',
    tags: ['Beni Ourain', 'Vintage Rugs', 'Fair Trade', 'Weaving'],
    authenticitySeals: ['wfto', 'label_artisanat'],
    paymentMethods: ['cash', 'visa', 'mastercard', 'amex'],
    productCategories: ['Wool Carpets', 'Kilim Runners', 'Cushion Covers', 'Cactus Silk Blankets'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 19:30' }],
    shipping: { available: true, partner: 'dhl' }
  },
  {
    id: 'sh-fes-7',
    city: 'fes',
    name: 'Fondouk El-Nejjarine Woodworking Atelier',
    type: 'designer_atelier',
    category: 'Antiques & Woodwork',
    neighborhood: 'Medina',
    description: 'Cedarwood carving masters adjacent to the historic Nejjarine Museum of Wooden Arts. Hand-carved cedar jewelry boxes, mirrors, and Koran stands.',
    googleRating: 4.8,
    googleReviewCount: 380,
    priceLevel: 'premium',
    pricingModel: 'mixed',
    isVerified: true,
    googlePlaceId: 'ChIJFondoukElNejjarineWoodworkingAtelierFes',
    googleMapsUrl: 'https://maps.google.com/?q=Nejjarine+Museum+Fes',
    address: 'Place Nejjarine, Fes el-Bali, Fes',
    landmark: 'Nejjarine Fountain',
    coordinates: { lat: 34.0645, lng: -4.9758 },
    distanceText: '7 min walk from Bab Bou Jeloud',
    tags: ['Cedarwood', 'Hand Carved', 'Heritage Craft'],
    authenticitySeals: ['label_artisanat', 'maalem_certified'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Cedar Boxes', 'Carved Mirrors', 'Wood Inlay Trays'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:00 - 18:30' }]
  },
  {
    id: 'sh-fes-8',
    city: 'fes',
    name: 'Serghini Ceramics Heritage Studio',
    type: 'designer_atelier',
    category: 'Ceramics & Pottery',
    neighborhood: 'Fes el-Bali',
    description: 'Eight generations of master potters crafting royal tableware, intricate geometric vases, and collectible hand-glazed terracotta.',
    googleRating: 4.9,
    googleReviewCount: 610,
    priceLevel: 'luxury',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJSerghiniCeramicsHeritageStudioFes',
    googleMapsUrl: 'https://maps.google.com/?q=Fes+Pottery+Serghini',
    address: 'Rue Qetaniyeh, Fes el-Bali, Fes',
    landmark: 'Moulay Idriss II Shrine',
    coordinates: { lat: 34.0651, lng: -4.9742 },
    distanceText: '5 min walk from Place Seffarine',
    tags: ['Master Potter', 'Royal Provenance', 'Heritage Ceramics', 'ceramics', 'fixed-price'],
    authenticitySeals: ['label_artisanat', 'zellige_de_fes'],
    paymentMethods: ['cash', 'visa', 'mastercard', 'apple_pay'],
    productCategories: ['Hand-Glazed Vases', 'Decorative Plates', 'Tajine Cookware'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Italian'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:30 - 19:00' }]
  },
  {
    id: 'sh-fes-9',
    city: 'fes',
    name: 'Souk el-Attarine Spice & Perfume Market',
    type: 'souk_stall',
    category: 'Spices & Cosmetics',
    neighborhood: 'Medina',
    description: 'Atmospheric medieval spice souk filled with mounds of paprika, cumin, ras el hanout spice blends, dried flowers, and orange blossom essences.',
    googleRating: 4.7,
    googleReviewCount: 780,
    priceLevel: 'budget',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJSoukElAttarineSpicePerfumeMarketFes',
    googleMapsUrl: 'https://maps.google.com/?q=Souk+Attarine+Fes',
    address: 'Souk Attarine, Fes el-Bali, Fes',
    landmark: 'Attarine Madrasa',
    coordinates: { lat: 34.0655, lng: -4.9738 },
    distanceText: '2 min walk from Al-Qarawiyyin Mosque',
    tags: ['Spices', 'Ras El Hanout', 'Traditional Market'],
    paymentMethods: ['cash'],
    productCategories: ['Ras El Hanout', 'Cumin & Paprika', 'Orange Blossom Water', 'Frankincense'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 19:30' }]
  },
  {
    id: 'sh-fes-10',
    city: 'fes',
    name: 'Mellah Silver & Antique Jewelry Market',
    type: 'souk_stall',
    category: 'Jewelry & Silver',
    neighborhood: 'Mellah',
    description: 'Historic Jewish quarter jewellers selling vintage Berber filigree silver bracelets, amber beads, and hand-engraved brass fibula brooches.',
    googleRating: 4.5,
    googleReviewCount: 290,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJMellahSilverAntiqueJewelryMarketFes',
    googleMapsUrl: 'https://maps.google.com/?q=Mellah+Fes',
    address: 'Rue des Bijoutiers, Mellah, Fes',
    landmark: 'Ibn Danan Synagogue',
    coordinates: { lat: 34.0531, lng: -4.9912 },
    distanceText: '10 min walk from Royal Palace Gates',
    tags: ['Silver Jewelry', 'Berber Filigree', 'Antiques'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Berber Silver', 'Amber Necklaces', 'Filigree Rings'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Sun-Fri', hours: '09:30 - 18:30' }]
  },
  {
    id: 'sh-fes-11',
    city: 'fes',
    name: 'Talaa Sghira Silk Weavers Guild',
    type: 'cooperative',
    category: 'Fashion & Design',
    neighborhood: 'Medina',
    description: 'Tranquil workshop where traditional hand loom operators craft agave cactus silk (sabra) scarves, shawls, and kaftan trims.',
    googleRating: 4.6,
    googleReviewCount: 340,
    priceLevel: 'budget',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJTalaaSghiraSilkWeaversGuildFes',
    googleMapsUrl: 'https://maps.google.com/?q=Talaa+Sghira+Fes',
    address: '88 Talaa Sghira, Fes el-Bali, Fes',
    landmark: 'Bab Bou Jeloud Gate',
    coordinates: { lat: 34.0618, lng: -4.9812 },
    distanceText: '3 min walk from Bab Bou Jeloud',
    tags: ['Cactus Silk', 'Hand Loom', 'Scarves', 'Sabra'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Cactus Silk Scarves', 'Kaftan Trims', 'Table Runners'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 19:30' }]
  },
  {
    id: 'sh-fes-12',
    city: 'fes',
    name: 'Maison Fassie Damascene Steel & Brass',
    type: 'designer_atelier',
    category: 'Brassware & Metalwork',
    neighborhood: 'Fes el-Bali',
    description: 'Unique master workshop practicing the rare art of Damascene steel inlay with silver and gold threads on decorative daggers and brass boxes.',
    googleRating: 4.8,
    googleReviewCount: 210,
    priceLevel: 'luxury',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJMaisonFassieDamasceneSteelBrassFes',
    googleMapsUrl: 'https://maps.google.com/?q=Place+Seffarine+Fes',
    address: 'Derb el Horra, Fes el-Bali, Fes',
    landmark: 'Place Seffarine',
    coordinates: { lat: 34.0649, lng: -4.9731 },
    distanceText: '1 min walk from Place Seffarine',
    tags: ['Damascene Steel', 'Gold Inlay', 'Rare Craft', 'fixed-price'],
    authenticitySeals: ['label_artisanat', 'maalem_certified'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Decorative Daggers', 'Inlaid Boxes', 'Collector Knives'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:00 - 18:00' }]
  },
  {
    id: 'sh-fes-13',
    city: 'fes',
    name: 'Ensemble Artisanal de Fes',
    type: 'cooperative',
    category: 'Artisan Crafts',
    neighborhood: 'Ville Nouvelle',
    description: 'Government-backed artisan complex featuring fixed-price government certified stalls for ceramics, leather, woodwork, and embroidery.',
    googleRating: 4.4,
    googleReviewCount: 510,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJEnsembleArtisanalDeFesFes',
    googleMapsUrl: 'https://maps.google.com/?q=Ensemble+Artisanal+Fes',
    address: 'Avenue Allal Ben Abdellah, Ville Nouvelle, Fes',
    landmark: 'Place Florence',
    coordinates: { lat: 34.0381, lng: -5.0012 },
    distanceText: '5 min drive from Fes Railway Station',
    tags: ['Government Certified', 'Fixed Prices', 'No Hassle', 'Fair Prices', 'leather', 'ceramics', 'fixed-price'],
    authenticitySeals: ['label_artisanat'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Ceramics', 'Leatherware', 'Embroidery', 'Copperware'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 19:00' }]
  },
  {
    id: 'sh-fes-14',
    city: 'fes',
    name: 'Au Petit Bazar Fassi Antiques',
    type: 'boutique',
    category: 'Antiques & Woodwork',
    neighborhood: 'Batha',
    description: 'Curated antique vault housing 19th-century Fes ceramics, hand-painted wooden ceiling fragments, old Berber jewelry, and antique lanterns.',
    googleRating: 4.6,
    googleReviewCount: 190,
    priceLevel: 'premium',
    pricingModel: 'mixed',
    isVerified: true,
    googlePlaceId: 'ChIJAuPetitBazarFassiAntiquesFes',
    googleMapsUrl: 'https://maps.google.com/?q=Batha+Fes',
    address: '12 Rue Batha, Fes el-Bali, Fes',
    landmark: 'Hôtel Batha',
    coordinates: { lat: 34.0611, lng: -4.9829 },
    distanceText: '4 min walk from Bab Bou Jeloud',
    tags: ['Antiques', 'Collectibles', 'Vintage Fes Ceramics', 'ceramics'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['19th Century Pottery', 'Carved Wood', 'Antique Lamps'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:30 - 19:30' }]
  },
  {
    id: 'sh-fes-15',
    city: 'fes',
    name: 'Coopérative Babouches Ain Nokbi',
    type: 'cooperative',
    category: 'Leather & Shoes',
    neighborhood: 'Fes el-Bali',
    description: 'Authentic artisans collective producing durable goat and calfskin leather babouches with rubber soles for daily walking.',
    googleRating: 4.5,
    googleReviewCount: 220,
    priceLevel: 'budget',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJCoopRativeBabouchesAinNokbiFes',
    googleMapsUrl: 'https://maps.google.com/?q=Ain+Nokbi+Fes',
    address: 'Zone Artisanale Ain Nokbi, Fes',
    landmark: 'Ain Nokbi Craft Zone',
    coordinates: { lat: 34.0588, lng: -4.9592 },
    distanceText: '10 min taxi ride from Medina',
    tags: ['Fair Trade', 'Durable Leather', 'Direct Artisan Prices', 'leather', 'fixed-price'],
    authenticitySeals: ['label_artisanat', 'wfto'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Leather Babouches', 'Suede Slippers', 'Belts'],
    languagesSpoken: ['Arabic', 'French'],
    openingHours: [{ day: 'Mon-Sat', hours: '08:30 - 18:00' }]
  },
  {
    id: 'sh-fes-16',
    city: 'fes',
    name: 'Dhar el-Mehraz Pottery Co-op',
    type: 'cooperative',
    category: 'Ceramics & Pottery',
    neighborhood: 'Fes el-Bali',
    description: 'Community-run pottery kiln crafting unglazed terra cotta tagines, clay water jugs (gourde), and traditional garden planters.',
    googleRating: 4.6,
    googleReviewCount: 170,
    priceLevel: 'budget',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJDharElMehrazPotteryCoOpFes',
    googleMapsUrl: 'https://maps.google.com/?q=Ain+Nokbi+Fes',
    address: 'Ain Nokbi Pottery Hill, Fes',
    landmark: 'Pottery Kilns',
    coordinates: { lat: 34.0595, lng: -4.9580 },
    distanceText: '12 min taxi from Medina center',
    tags: ['Unglazed Terra Cotta', 'Cooking Tagines', 'Raw Clay', 'ceramics', 'fixed-price'],
    paymentMethods: ['cash'],
    productCategories: ['Clay Tagines', 'Terracotta Planters', 'Water Jugs'],
    languagesSpoken: ['Arabic', 'French'],
    openingHours: [{ day: 'Mon-Sat', hours: '08:00 - 18:00' }]
  },
  {
    id: 'sh-fes-17',
    city: 'fes',
    name: 'Sidi Frej Candle & Lantern Guild',
    type: 'souk_stall',
    category: 'Artisan Crafts',
    neighborhood: 'Medina',
    description: 'Small historic souk near the historic Maristan Sidi Frej specialized in hand-carved beeswax candles, brass lamps, and aromatic incense.',
    googleRating: 4.7,
    googleReviewCount: 260,
    priceLevel: 'budget',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJSidiFrejCandleLanternGuildFes',
    googleMapsUrl: 'https://maps.google.com/?q=Sidi+Frej+Fes',
    address: 'Souk Henna, Sidi Frej, Fes',
    landmark: 'Henna Souk Fountain',
    coordinates: { lat: 34.0641, lng: -4.9752 },
    distanceText: '5 min walk from Bab Bou Jeloud',
    tags: ['Beeswax Candles', 'Incense', 'Henna Souk', 'spices', 'souvenirs'],
    paymentMethods: ['cash'],
    productCategories: ['Handmade Candles', 'Frankincense', 'Myrrh', 'Brass Oil Lamps'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 19:30' }]
  },
  {
    id: 'sh-fes-18',
    city: 'fes',
    name: 'Fondouk El-Kettanine Fabric Market',
    type: 'souk_stall',
    category: 'Fashion & Design',
    neighborhood: 'Medina',
    description: 'Restored 18th-century fondouk housing textiles merchants selling brocade silk, wool djellaba fabrics, and hand-woven blankets.',
    googleRating: 4.5,
    googleReviewCount: 200,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJFondoukElKettanineFabricMarketFes',
    googleMapsUrl: 'https://maps.google.com/?q=Fondouk+Kettanine+Fes',
    address: 'Fondouk Kettanine, Talaa Kebira, Fes',
    landmark: 'Talaa Kebira',
    coordinates: { lat: 34.0646, lng: -4.9760 },
    distanceText: '6 min walk from Bab Bou Jeloud',
    tags: ['Fabrics', 'Silk Brocade', 'Djellaba Wool', 'Historic Fondouk'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Silk Fabrics', 'Wool Clotting', 'Blankets'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:00 - 19:00' }]
  },
  {
    id: 'sh-fes-19',
    city: 'fes',
    name: 'Broderie Fassie Maalem Atelier',
    type: 'designer_atelier',
    category: 'Fashion & Design',
    neighborhood: 'Bou Inania',
    description: 'Renowned women weavers atelier specialized in "Point de Fès" two-sided monochrome blue and red silk hand embroidery on table linens.',
    googleRating: 4.8,
    googleReviewCount: 150,
    priceLevel: 'premium',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJBroderieFassieMaalemAtelierFes',
    googleMapsUrl: 'https://maps.google.com/?q=Bou+Inania+Fes',
    address: '15 Derb el-Memsi, Talaa Kebira, Fes',
    landmark: 'Bou Inania Madrasa',
    coordinates: { lat: 34.0625, lng: -4.9802 },
    distanceText: '3 min walk from Bab Bou Jeloud',
    tags: ['Point de Fes', 'Hand Embroidery', 'Table Linens', 'Heritage Craft', 'fixed-price'],
    authenticitySeals: ['label_artisanat'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Embroidery Napkins', 'Tablecloths', 'Bridal Linens'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:30 - 18:30' }]
  },
  {
    id: 'sh-fes-20',
    city: 'fes',
    name: 'Pharmacie Végétale Souk el-Henna',
    type: 'pharmacy',
    category: 'Spices & Cosmetics',
    neighborhood: 'Medina',
    description: 'Shaded historic apothecary underneath ancient plane trees at Henna Souk selling natural henna powders, kohl eye powders, and kessa scrubbing gloves.',
    googleRating: 4.7,
    googleReviewCount: 480,
    priceLevel: 'budget',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJPharmacieVGTaleSoukElHennaFes',
    googleMapsUrl: 'https://maps.google.com/?q=Souk+Henna+Fes',
    address: 'Place Souk el-Henna, Fes el-Bali, Fes',
    landmark: 'Maristan Sidi Frej',
    coordinates: { lat: 34.0640, lng: -4.9750 },
    distanceText: '5 min walk from Bab Bou Jeloud',
    tags: ['Henna', 'Kohl', 'Kessa Glove', 'Natural Skincare', 'spices', 'fixed-price'],
    paymentMethods: ['cash'],
    productCategories: ['Pure Henna', 'Natural Kohl', 'Kessa Gloves', 'Ghassoul Clay'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 19:30' }]
  },
  {
    id: 'sh-fes-marjane-1',
    city: 'fes',
    name: 'Marjane Fes Agdal',
    type: 'supermarket',
    category: 'Hypermarket',
    neighborhood: 'Ville Nouvelle',
    description: 'Major hypermarket in the southern Agdal sector of Ville Nouvelle. Complete selection of Moroccan olive oils, Fassi pastry ingredients, canned olives, electronics, clothing, and water.',
    googleRating: 4.2,
    googleReviewCount: 6800,
    priceLevel: 'budget',
    pricingModel: 'fixed',
    isVerified: true,
    googleMapsUrl: 'https://www.google.com/maps/search/Marjane+Fes+Agdal/@34.0150,-4.9850,13z',
    address: 'Route d\'Ifrane, Agdal, Ville Nouvelle, Fes',
    coordinates: { lat: 34.015, lng: -4.985 },
    tags: ["supermarket","hypermarket","groceries","travel-supplies","fixed-price","verified"],
    paymentMethods: ["cash","visa","mastercard","apple_pay"],
    productCategories: ["Groceries","Local Olive Oil","Bakery","Electronics","Toiletries"],
    languagesSpoken: ["Arabic","French","English"],
    openingHours: [{"day":"Mon-Sun","hours":"09:00 - 22:00"}]
  },
  {
    id: 'sh-fes-carrefour-1',
    city: 'fes',
    name: 'Carrefour Market Borj Fez',
    type: 'supermarket',
    category: 'Supermarket',
    neighborhood: 'Ville Nouvelle',
    description: 'Spacious supermarket in the Borj Fez Shopping Center between Ville Nouvelle and the medina. Provides French dairy, fresh bread, snacks, bottled water, toiletries, and international goods.',
    googleRating: 4.3,
    googleReviewCount: 4120,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googleMapsUrl: 'https://www.google.com/maps/search/Carrefour+Market+Borj+Fez+Mall/@34.0450,-4.9920,13z',
    address: 'Borj Fez Mall, Boulevard Allal Ben Abdallah, Ville Nouvelle, Fes',
    coordinates: { lat: 34.045, lng: -4.992 },
    tags: ["supermarket","french-groceries","bakery","borj-fez","fixed-price","verified"],
    paymentMethods: ["cash","visa","mastercard","apple_pay"],
    productCategories: ["European Groceries","Dairy","Bakery","Fresh Fruit","Toiletries"],
    languagesSpoken: ["French","Arabic","English"],
    openingHours: [{"day":"Mon-Sun","hours":"09:00 - 22:00"}]
  },
  {
    id: 'sh-fes-decathlon-1',
    city: 'fes',
    name: 'Decathlon Fes Borj Fez',
    type: 'mall_store',
    category: 'Sports Store',
    neighborhood: 'Ville Nouvelle',
    description: 'Modern sports store in the Borj Fez shopping complex. Great resource for Middle Atlas hiking shoes, rainwear, water bottles, backpacks, and gym apparel.',
    googleRating: 4.4,
    googleReviewCount: 3950,
    priceLevel: 'budget',
    pricingModel: 'fixed',
    isVerified: true,
    googleMapsUrl: 'https://www.google.com/maps/search/Decathlon+Borj+Fez/@34.0452,-4.9918,13z',
    address: 'Borj Fez Mall, Boulevard Allal Ben Abdallah, Ville Nouvelle, Fes',
    coordinates: { lat: 34.0452, lng: -4.9918 },
    tags: ["sports","outdoor","hiking","middle-atlas","shoes","fixed-price","verified"],
    paymentMethods: ["cash","visa","mastercard","apple_pay"],
    productCategories: ["Hiking Shoes","Backpacks","Trek Jackets","Sportswear","Camping Supplies"],
    languagesSpoken: ["French","Arabic","English"],
    openingHours: [{"day":"Mon-Sun","hours":"10:00 - 21:30"}]
  },
  {
    id: 'sh-fes-atacadao-1',
    city: 'fes',
    name: 'Atacadão Fes',
    type: 'supermarket',
    category: 'Supermarket',
    neighborhood: 'Ville Nouvelle',
    description: 'Wholesale and bulk discount supermarket located on Route de Meknès in Bensouda. Excellent for purchasing bulk cases of water, dry fruit, tea, and dry provisions.',
    googleRating: 4.1,
    googleReviewCount: 2840,
    priceLevel: 'budget',
    pricingModel: 'fixed',
    isVerified: true,
    googleMapsUrl: 'https://www.google.com/maps/search/Atacadao+Bensouda+Fes/@34.0205,-5.0450,13z',
    address: 'Route de Meknès, Quartier Bensouda, Fes',
    coordinates: { lat: 34.0205, lng: -5.045 },
    tags: ["supermarket","wholesale","bulk-staples","discount","fixed-price","verified"],
    paymentMethods: ["cash","visa","mastercard"],
    productCategories: ["Bottled Water Cases","Bulk Tea & Sugar","Canned Goods","Cleaning Essentials"],
    languagesSpoken: ["Arabic","French"],
    openingHours: [{"day":"Mon-Sun","hours":"08:30 - 20:30"}]
  },
  {
    id: 'sh-fes-bim-1',
    city: 'fes',
    name: 'BIM Ville Nouvelle',
    type: 'supermarket',
    category: 'Supermarket',
    neighborhood: 'Ville Nouvelle',
    description: 'Accessible discount supermarket along Avenue Hassan II in Ville Nouvelle. Quick stop for affordable chilled beverages, breakfast cookies, and toiletries.',
    googleRating: 4,
    googleReviewCount: 320,
    priceLevel: 'budget',
    pricingModel: 'fixed',
    isVerified: true,
    googleMapsUrl: 'https://www.google.com/maps/search/BIM+Avenue+Hassan+II+Ville+Nouvelle+Fes/@34.0375,-4.9995,13z',
    address: 'Avenue Hassan II, Ville Nouvelle, Fes',
    coordinates: { lat: 34.0375, lng: -4.9995 },
    tags: ["supermarket","discount-grocery","snacks","water","fixed-price","verified"],
    paymentMethods: ["cash","visa","mastercard"],
    productCategories: ["Mineral Water","Biscuits","Dairy","Snacks","Basic Hygiene"],
    languagesSpoken: ["Arabic","French"],
    openingHours: [{"day":"Mon-Sun","hours":"08:30 - 21:00"}]
  }
];
