import { ShopListing } from '../types'

export const ifraneShops: ShopListing[] = [
  {
    id: 'sh-ifr-1',
    city: 'ifrane_azrou',
    name: 'Complexe Artisanal d\'Ifrane',
    type: 'cooperative',
    category: 'Artisan Crafts',
    neighborhood: 'Centre Ville',
    description: 'Premier government artisan complex in Ifrane specializing in aromatic Atlas cedar wood carving, handcrafted cedar furniture, Middle Atlas wool carpets, and stone sculptures.',
    googleRating: 4.6,
    googleReviewCount: 380,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJComplexeArtisanalDIfrane',
    googleMapsUrl: 'https://maps.google.com/?q=Complexe+Artisanal+Ifrane',
    address: 'Route de Fez, Centre Ville, Ifrane',
    landmark: 'Ifrane Town Center Park',
    coordinates: { lat: 33.5350, lng: -5.1080 },
    distanceText: '5 min walk from lion statue square',
    navSteps: [
      'From the iconic lion statue, walk north along Route de Fez',
      'Look for the stone-and-timber mountain style building on your right',
      'Enter the cedar wood carving hall and showroom'
    ],
    what3words: 'cedar.wood.mountain',
    tags: ['Cedar Wood', 'Wood Carvings', 'Beni Ourain Rugs', 'Middle Atlas Crafts'],
    authenticitySeals: ['label_artisanat'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Cedar Boxes', 'Carved Sculptures', 'Wool Blankets', 'Middle Atlas Rugs'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Berber'],
    phoneNumber: '+212 5355-66120',
    openingHours: [{ day: 'Mon-Sat', hours: '08:30 - 18:30' }],
    workshopVisitable: true,
    isLocalFavorite: true
  },
  {
    id: 'sh-ifr-2',
    city: 'ifrane_azrou',
    name: 'Marché Central d\'Ifrane',
    type: 'souk_stall',
    category: 'Fresh Produce & Honey',
    neighborhood: 'Centre Ville',
    description: 'European-style covered market in downtown Ifrane famous for wild lavender and rosemary mountain honey, fresh walnuts, Middle Atlas apples, and local cheeses.',
    googleRating: 4.5,
    googleReviewCount: 420,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJMarchCentralDIfrane',
    googleMapsUrl: 'https://maps.google.com/?q=Marche+Central+Ifrane',
    address: 'Place du Marché, Ifrane',
    landmark: 'Ifrane Post Office',
    coordinates: { lat: 33.5332, lng: -5.1105 },
    distanceText: '2 min walk from Lion Statue',
    tags: ['Mountain Honey', 'Walnuts', 'Fresh Produce', 'Covered Market'],
    paymentMethods: ['cash'],
    productCategories: ['Lavender Honey', 'Wild Thyme Honey', 'Atlas Walnuts', 'Fresh Apples'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:00 - 19:30' }],
    isLocalFavorite: true
  },
  {
    id: 'sh-ifr-3',
    city: 'ifrane_azrou',
    name: 'The Lion Statue Souvenir Row',
    type: 'souk_stall',
    category: 'Souvenirs & Keepsakes',
    neighborhood: 'Centre Ville',
    description: 'Bustling pedestrian strip right beside the iconic stone Lion Statue, selling miniature hand-carved stone lion replicas, cedar keychains, and postcards.',
    googleRating: 4.4,
    googleReviewCount: 650,
    priceLevel: 'budget',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJTheLionStatueSouvenirRowIfrane',
    googleMapsUrl: 'https://maps.google.com/?q=Lion+Statue+Ifrane',
    address: 'Avenue Moulay Hassan, Ifrane',
    landmark: 'Lion Statue Ifrane',
    coordinates: { lat: 33.5325, lng: -5.1118 },
    distanceText: 'Directly at the Lion Statue plaza',
    tags: ['Lion Statue', 'Cedar Keychains', 'Stone Carvings', 'Postcards'],
    paymentMethods: ['cash'],
    productCategories: ['Stone Lion Replicas', 'Cedar Trinkets', 'Ifrane Postcards'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:30 - 20:00' }]
  },
  {
    id: 'sh-ifr-4',
    city: 'ifrane_azrou',
    name: 'Cooperative Al-Akhawayn Rugs',
    type: 'cooperative',
    category: 'Carpets & Textiles',
    neighborhood: 'Al-Akhawayn Sector',
    description: 'High-end carpet collective producing plush white-and-black Beni Ourain wool rugs, Middle Atlas hand-knotted carpets, and warm wool shawls.',
    googleRating: 4.8,
    googleReviewCount: 160,
    priceLevel: 'premium',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJCooperativeAlAkhawaynRugsIfrane',
    googleMapsUrl: 'https://maps.google.com/?q=Al+Akhawayn+University+Ifrane',
    address: 'Avenue Hassan II, near Al-Akhawayn, Ifrane',
    landmark: 'Al-Akhawayn University Gate',
    coordinates: { lat: 33.5380, lng: -5.1050 },
    distanceText: '8 min walk from Al-Akhawayn campus',
    tags: ['Beni Ourain', 'Middle Atlas Rugs', 'Plush Wool', 'Handmade Carpets'],
    authenticitySeals: ['wfto', 'label_artisanat'],
    paymentMethods: ['cash', 'visa', 'mastercard', 'apple_pay'],
    productCategories: ['Beni Ourain Rugs', 'Middle Atlas Runners', 'Wool Shawls'],
    languagesSpoken: ['English', 'French', 'Arabic'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:00 - 18:00' }],
    shipping: { available: true, partner: 'dhl' }
  },
  {
    id: 'sh-ifr-5',
    city: 'ifrane_azrou',
    name: 'Michlifen Pro Sports Shop',
    type: 'boutique',
    category: 'Sports & Winter Gear',
    neighborhood: 'Centre Ville',
    description: 'Premier mountain gear boutique stocking winter jackets, ski and snowboard rentals, hiking boots, and outdoor accessories for exploring the Middle Atlas.',
    googleRating: 4.7,
    googleReviewCount: 210,
    priceLevel: 'premium',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJMichlifenProSportsShopIfrane',
    googleMapsUrl: 'https://maps.google.com/?q=Michlifen+Resort+Ifrane',
    address: 'Avenue de la Marche Verte, Ifrane',
    landmark: 'Michlifen Hotel Entrance',
    coordinates: { lat: 33.5310, lng: -5.1130 },
    distanceText: '3 min walk from city center',
    tags: ['Ski Rental', 'Winter Apparel', 'Hiking Boots', 'Mountain Gear'],
    paymentMethods: ['cash', 'visa', 'mastercard', 'apple_pay'],
    productCategories: ['Winter Jackets', 'Ski Gear', 'Hiking Boots', 'Thermal Gloves'],
    languagesSpoken: ['French', 'English', 'Arabic'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:30 - 19:30' }]
  },
  {
    id: 'sh-ifr-6',
    city: 'ifrane_azrou',
    name: 'Boutique Miel Sauvage de l\'Atlas',
    type: 'boutique',
    category: 'Gourmet Food & Honey',
    neighborhood: 'Centre Ville',
    description: 'Specialty artisanal shop selling pure, lab-tested mountain honeys harvested from cedar, lavender, and wild thyme flowers in the Middle Atlas biosphere.',
    googleRating: 4.9,
    googleReviewCount: 180,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJBoutiqueMielSauvageDeLIfrane',
    googleMapsUrl: 'https://maps.google.com/?q=Miel+Sauvage+Ifrane',
    address: 'Boulevard Mohammed V, Ifrane',
    landmark: 'Ifrane Town Hall',
    coordinates: { lat: 33.5340, lng: -5.1095 },
    distanceText: '4 min walk from Central Park',
    tags: ['Pure Wild Honey', 'Cedar Honey', 'Lavender Honey', 'Atlas Gourmet'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Cedar Tree Honey', 'Wild Lavender Honey', 'Pollen & Royal Jelly', 'Propolis'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:00 - 20:00' }]
  },
  {
    id: 'sh-ifr-7',
    city: 'ifrane_azrou',
    name: 'The Cedar Craft Studio',
    type: 'designer_atelier',
    category: 'Woodwork & Decor',
    neighborhood: 'Centre Ville',
    description: 'Boutique woodwork atelier creating polished aromatic cedar jewelry boxes, chess sets, hand-carved bowls, and custom cedar home decor items.',
    googleRating: 4.8,
    googleReviewCount: 145,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJTheCedarCraftStudioIfrane',
    googleMapsUrl: 'https://maps.google.com/?q=Cedar+Craft+Studio+Ifrane',
    address: 'Rue de la Foret, Ifrane',
    landmark: 'Parc La Prairie',
    coordinates: { lat: 33.5360, lng: -5.1070 },
    distanceText: '6 min walk from lion statue',
    tags: ['Cedar Boxes', 'Chess Sets', 'Carved Wood', 'Cedar Decor'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Aromatic Cedar Jewelry Boxes', 'Hand-carved Chessboards', 'Cedar Serving Bowls'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:00 - 18:30' }],
    workshopVisitable: true
  },
  {
    id: 'sh-ifr-8',
    city: 'ifrane_azrou',
    name: 'Ifrane Pastry & Chocolaterie',
    type: 'boutique',
    category: 'Gourmet Pastries',
    neighborhood: 'Centre Ville',
    description: 'Chalet-style alpine bakery famous for hand-crafted hazelnut pralines, warm almond cornes de gazelle, dark chocolates, and spiced mountain herbal teas.',
    googleRating: 4.8,
    googleReviewCount: 310,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJIfranePastryChocolaterieIfrane',
    googleMapsUrl: 'https://maps.google.com/?q=Chocolaterie+Ifrane',
    address: 'Avenue Moulay Hassan, Ifrane',
    landmark: 'Café Chamonix Ifrane',
    coordinates: { lat: 33.5328, lng: -5.1110 },
    distanceText: '1 min walk from main square',
    tags: ['Alpine Chocolates', 'Cornes de Gazelle', 'Chalet Pastry', 'Gourmet Food'],
    paymentMethods: ['cash', 'visa', 'mastercard', 'apple_pay'],
    productCategories: ['Handmade Chocolates', 'Moroccan Pastries', 'Macarons', 'Mountain Herbal Tea'],
    languagesSpoken: ['French', 'Arabic', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '07:30 - 21:00' }],
    isLocalFavorite: true
  },
  {
    id: 'sh-ifr-9',
    city: 'ifrane_azrou',
    name: 'Cooperative de Poterie d\'Ifrane',
    type: 'cooperative',
    category: 'Ceramics & Pottery',
    neighborhood: 'Route de Fez',
    description: 'Artisan pottery cooperative making thick, frost-resistant alpine clay ceramics, terracotta flower pots, glazed tagines, and garden urns.',
    googleRating: 4.6,
    googleReviewCount: 130,
    priceLevel: 'budget',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJCooperativeDePoterieDIfrane',
    googleMapsUrl: 'https://maps.google.com/?q=Poterie+Ifrane',
    address: 'Route de Fez KM 2, Ifrane',
    landmark: 'Ifrane Garden Nursery',
    coordinates: { lat: 33.5420, lng: -5.1020 },
    distanceText: '3 min drive from city center',
    tags: ['Alpine Pottery', 'Frost Resistant Clay', 'Garden Urns', 'Terracotta Tagines'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Garden Planters', 'Glazed Cooking Tagines', 'Terracotta Vases'],
    languagesSpoken: ['Arabic', 'French'],
    openingHours: [{ day: 'Mon-Sat', hours: '08:30 - 18:00' }],
    workshopVisitable: true
  },
  {
    id: 'sh-ifr-10',
    city: 'ifrane_azrou',
    name: 'Bazar Suisse Marocain',
    type: 'boutique',
    category: 'Souvenirs & Decor',
    neighborhood: 'Centre Ville',
    description: 'Charming boutique blending European alpine chalet decorations with traditional Moroccan brass lamps, cuckoo clocks, and woven wool rugs.',
    googleRating: 4.5,
    googleReviewCount: 175,
    priceLevel: 'mid-range',
    pricingModel: 'mixed',
    isVerified: true,
    googlePlaceId: 'ChIJBazarSuisseMarocainIfrane',
    googleMapsUrl: 'https://maps.google.com/?q=Bazar+Suisse+Marocain+Ifrane',
    address: 'Boulevard Mohammed V, Ifrane',
    landmark: 'Ifrane Municipal Garden',
    coordinates: { lat: 33.5335, lng: -5.1090 },
    distanceText: '3 min walk from Lion Statue',
    tags: ['Chalet Decor', 'Brass Lamps', 'Swiss Clocks', 'Woven Rugs'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Brass Lanterns', 'Wood Clocks', 'Wool Blankets', 'Mountain Souvenirs'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 19:30' }]
  }
]
