import { ShopListing } from '../types'

export const meknesShops: ShopListing[] = [
  {
    id: 'sh-mek-1',
    city: 'meknes',
    name: 'L\'art De La Damasquinerie',
    type: 'designer_atelier',
    category: 'Damascene Metalwork',
    neighborhood: 'Medina',
    description: 'Master multi-generational workshop practicing Meknes’ unique Damascene craft—inlaying pure silver and gold wire into dark chiseled iron plates, vases, and decorative daggers.',
    googleRating: 4.9,
    googleReviewCount: 280,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJLMeknes',
    googleMapsUrl: 'https://maps.google.com/?q=L+art+De+La+Damasquinerie+Meknes',
    address: 'Place El Hedim, Medina, Meknes',
    landmark: 'Bab Mansour / Place El Hedim',
    coordinates: { lat: 33.8932, lng: -5.5658 },
    distanceText: '2 min walk across Place El Hedim from Bab Mansour',
    navSteps: [
      'Stand in Place El Hedim facing Bab Mansour',
      'Walk along the northern covered artisan arcade',
      'Look for the ironwork studio with silver wire inlay demonstrations'
    ],
    what3words: 'iron.silver.damascene',
    tags: ['Damascene Metalwork', 'Silver Inlay', 'Meknes Heritage', 'Master Artisan'],
    authenticitySeals: ['label_artisanat', 'maalem_certified'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Silver-inlaid Plates', 'Decorative Daggers', 'Iron Vases', 'Chiseled Mirrors'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    phoneNumber: '+212 5355-32140',
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 19:30' }],
    workshopVisitable: true,
    isLocalFavorite: true
  },
  {
    id: 'sh-mek-2',
    city: 'meknes',
    name: 'Dar Al Antiques Meknes',
    type: 'boutique',
    category: 'Antiques & Art',
    neighborhood: 'Medina',
    description: 'Beautifully restored medina townhouse gallery curated with rare Jewish-Moroccan silver ceremonial items, antique Middle Atlas rugs, vintage brassware, and carved woodwork.',
    googleRating: 4.8,
    googleReviewCount: 190,
    priceLevel: 'premium',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJDarAlAntiquesMeknesMeknes',
    googleMapsUrl: 'https://maps.google.com/?q=Dar+Al+Antiques+Meknes',
    address: 'Derb El Hammam, Medina, Meknes',
    landmark: 'Grand Mosque Meknes',
    coordinates: { lat: 33.8948, lng: -5.5645 },
    distanceText: '3 min walk from Place El Hedim',
    tags: ['Jewish-Moroccan Heritage', 'Rare Antiques', 'Middle Atlas Rugs', 'Medina Mansion'],
    paymentMethods: ['cash', 'visa', 'mastercard', 'amex'],
    productCategories: ['Silver Judaica', 'Antique Middle Atlas Rugs', 'Engraved Brass Trays'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Spanish'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:30 - 19:00' }],
    shipping: { available: true, partner: 'dhl' }
  },
  {
    id: 'sh-mek-3',
    city: 'meknes',
    name: 'Souk Lahdim Olives & Spices',
    type: 'souk_stall',
    category: 'Food & Spices',
    neighborhood: 'Place El Hedim',
    description: 'Morocco’s most famous covered olive and spice market hall. Features towering barrels of garlic-marinated olives, cured harissa, ras el hanout, and local olive oil.',
    googleRating: 4.7,
    googleReviewCount: 850,
    priceLevel: 'budget',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJSoukLahdimOlivesSpicesMeknes',
    googleMapsUrl: 'https://maps.google.com/?q=Souk+Lahdim+Olives+Meknes',
    address: 'Marché Couvert, Place El Hedim, Meknes',
    landmark: 'Place El Hedim Covered Market',
    coordinates: { lat: 33.8928, lng: -5.5662 },
    distanceText: 'Directly on Place El Hedim',
    tags: ['Meknes Olives', 'Marinated Harissa', 'Covered Market', 'Ras El Hanout'],
    paymentMethods: ['cash'],
    productCategories: ['Garlic Marinated Olives', 'Cured Harissa Paste', 'Ras El Hanout Spice', 'Meknes Olive Oil'],
    languagesSpoken: ['Arabic', 'French'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:00 - 20:00' }],
    isLocalFavorite: true
  },
  {
    id: 'sh-mek-4',
    city: 'meknes',
    name: 'Souk Sekkakine Coppersmiths & Cutlery',
    type: 'souk_stall',
    category: 'Metalwork & Cookware',
    neighborhood: 'Medina',
    description: 'Vibrant historical market street buzzing with ironworkers and coppersmiths forging brass mint-tea pots, copper tagine bottoms, custom kitchen knives, and metal lanterns.',
    googleRating: 4.6,
    googleReviewCount: 310,
    priceLevel: 'budget',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJSoukSekkakineCoppersmithsCutleryMeknes',
    googleMapsUrl: 'https://maps.google.com/?q=Souk+Sekkakine+Meknes',
    address: 'Rue Sekkakine, Medina, Meknes',
    landmark: 'Bou Inania Madrasa Meknes',
    coordinates: { lat: 33.8952, lng: -5.5650 },
    distanceText: '4 min walk from Place El Hedim',
    tags: ['Coppersmiths', 'Brass Teapots', 'Custom Knives', 'Copper Tagines'],
    paymentMethods: ['cash'],
    productCategories: ['Hand-hammered Teapots', 'Copper Basins', 'Chef Knives', 'Brass Trays'],
    languagesSpoken: ['Arabic', 'French'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:00 - 19:00' }],
    workshopVisitable: true
  },
  {
    id: 'sh-mek-5',
    city: 'meknes',
    name: 'Souk Bezzazine Wicker & Basketry',
    type: 'souk_stall',
    category: 'Basketry & Wood',
    neighborhood: 'Medina',
    description: 'Aromatic historic covered alleyway dedicated completely to palm-leaf basketry, reed laundry baskets, hand-woven wicker hats, and cedar wood kitchen utensils.',
    googleRating: 4.7,
    googleReviewCount: 220,
    priceLevel: 'budget',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJSoukBezzazineWickerBasketryMeknes',
    googleMapsUrl: 'https://maps.google.com/?q=Souk+Bezzazine+Meknes',
    address: 'Rue Bezzazine, Medina, Meknes',
    landmark: 'Grand Mosque Entrance',
    coordinates: { lat: 33.8945, lng: -5.5640 },
    distanceText: '3 min walk from Bab Aissa',
    tags: ['Wickerwork', 'Palm Baskets', 'Reed Mats', 'Cedar Utensils'],
    paymentMethods: ['cash'],
    productCategories: ['Wicker Laundry Baskets', 'Straw Hats', 'Cedar Spatulas', 'Palm Mats'],
    languagesSpoken: ['Arabic', 'French'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:00 - 19:00' }]
  },
  {
    id: 'sh-mek-6',
    city: 'meknes',
    name: 'Label\'Gallery Meknes',
    type: 'mall_store',
    category: 'Shopping Mall',
    neighborhood: 'Hamria (New City)',
    description: 'Modern air-conditioned shopping center in Meknes Ville Nouvelle featuring Carrefour hypermarket, boutique fashion outlets, cosmetics shops, and cafes.',
    googleRating: 4.4,
    googleReviewCount: 1200,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJLabelMeknes',
    googleMapsUrl: 'https://maps.google.com/?q=Label+Gallery+Meknes',
    address: 'Avenue Hassan II, Hamria, Meknes',
    landmark: 'Meknes Ville Railway Station',
    coordinates: { lat: 33.8985, lng: -5.5480 },
    distanceText: '5 min walk from Meknes Ville Train Station',
    tags: ['Shopping Mall', 'Ville Nouvelle', 'Air Conditioned', 'Fashion Brands'],
    paymentMethods: ['cash', 'visa', 'mastercard', 'apple_pay'],
    productCategories: ['International Fashion', 'Cosmetics', 'Packaged Local Food', 'Electronics'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 21:00' }]
  },
  {
    id: 'sh-mek-7',
    city: 'meknes',
    name: 'Produits de Terroir Meknassi (Bir Anzarane)',
    type: 'boutique',
    category: 'Gourmet Food & Pastries',
    neighborhood: 'Hamria (New City)',
    description: 'Upscale regional artisan food boutique showcasing Zerhoun extra virgin olive oil, wild lavender honey, Meknes almond cornes de gazelle, and organic jams.',
    googleRating: 4.8,
    googleReviewCount: 175,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJProduitsDeTerroirMeknassiBirAnzaraneMeknes',
    googleMapsUrl: 'https://maps.google.com/?q=Produits+de+Terroir+Bir+Anzarane+Meknes',
    address: 'Avenue Bir Anzarane, Hamria, Meknes',
    landmark: 'Place Administrative',
    coordinates: { lat: 33.8965, lng: -5.5510 },
    distanceText: '3 min walk from Place de la Liberté',
    tags: ['Zerhoun Olive Oil', 'Gourmet Pastries', 'Mountain Honey', 'Local Specialty'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Zerhoun Virgin Olive Oil', 'Cornes de Gazelle', 'Lavender Honey', 'Almond Amlou'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sat', hours: '08:30 - 20:00' }]
  },
  {
    id: 'sh-mek-8',
    city: 'meknes',
    name: 'Souk Bab Mansour Babouches',
    type: 'souk_stall',
    category: 'Leather & Shoes',
    neighborhood: 'Place El Hedim',
    description: 'Bustling leather slipper arcade near Bab Mansour stocking soft goat-leather babouche slippers in royal yellow, dark burgundy embroidery, and comfortable outdoor soles.',
    googleRating: 4.6,
    googleReviewCount: 290,
    priceLevel: 'budget',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJSoukBabMansourBabouchesMeknes',
    googleMapsUrl: 'https://maps.google.com/?q=Bab+Mansour+Meknes',
    address: 'Rue Bab Mansour, Medina, Meknes',
    landmark: 'Bab Mansour Gate',
    coordinates: { lat: 33.8930, lng: -5.5652 },
    distanceText: '1 min walk from Bab Mansour',
    tags: ['Leather Slippers', 'Babouches', 'Bab Mansour', 'Soft Goat Leather'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Royal Yellow Babouches', 'Embroided Slippers', 'Leather Sandals'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 20:00' }]
  },
  {
    id: 'sh-mek-9',
    city: 'meknes',
    name: 'Herboristerie Al-Malaki',
    type: 'pharmacy',
    category: 'Spices & Herbal Remedies',
    neighborhood: 'Medina',
    description: 'Traditional certified medina spice shop and herbal pharmacy known for pure Taliouine saffron, Zerhoun herbal tea infusions, black soap, and natural argan cosmetics.',
    googleRating: 4.7,
    googleReviewCount: 210,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJHerboristerieAlMalakiMeknes',
    googleMapsUrl: 'https://maps.google.com/?q=Herboristerie+Al-Malaki+Meknes',
    address: 'Rue Kebira, Medina, Meknes',
    landmark: 'Bou Inania Madrasa Corridor',
    coordinates: { lat: 33.8950, lng: -5.5648 },
    distanceText: '3 min walk from Place El Hedim',
    tags: ['Pure Saffron', 'Herbal Infusions', 'Argan Oil', 'Black Soap'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Saffron Threads', 'Custom Herbal Teas', 'Argan Beauty Oil', 'Ghassoul Clay'],
    languagesSpoken: ['Arabic', 'French'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:30 - 20:00' }]
  },
  {
    id: 'sh-mek-10',
    city: 'meknes',
    name: 'Meknes Carpet Palace (Palais de l\'Artisanat)',
    type: 'cooperative',
    category: 'Carpets & Textiles',
    neighborhood: 'Medina',
    description: 'Multi-level medina mansion showcasing plush Middle Atlas Beni Ourain rugs, colorful Azilal flat-weaves, vintage silk embroidery, and brass lanterns.',
    googleRating: 4.8,
    googleReviewCount: 340,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJMeknesCarpetPalacePalaisDeLMeknes',
    googleMapsUrl: 'https://maps.google.com/?q=Palais+de+l+Artisanat+Meknes',
    address: 'Rue El Ksar, Medina, Meknes',
    landmark: 'Dar Jamai Museum',
    coordinates: { lat: 33.8940, lng: -5.5655 },
    distanceText: '2 min walk from Place El Hedim',
    tags: ['Beni Ourain Rugs', 'Middle Atlas Carpets', 'Silk Embroidery', 'Carpet Mansion'],
    authenticitySeals: ['label_artisanat'],
    paymentMethods: ['cash', 'visa', 'mastercard', 'amex'],
    productCategories: ['Beni Ourain Wool Carpets', 'Azilal Flat-weaves', 'Vintage Silk Cushions'],
    languagesSpoken: ['Arabic', 'French', 'English', 'German', 'Spanish'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:30 - 19:30' }],
    shipping: { available: true, partner: 'dhl', details: 'International door-to-door carpet delivery' }
  }
]
