import { ShopListing } from '../types'

export const merzougaShops: ShopListing[] = [
  {
    id: 'sh-mer-1',
    city: 'merzouga',
    name: 'Depot Nomade Antique Souvenir',
    type: 'cooperative',
    category: 'Carpets & Textiles',
    neighborhood: 'Hassilabied',
    description: 'An iconic desert warehouse in Hassilabied showcasing authentic nomadic Berber carpets, ancient tribal textiles, brass lanterns, and Saharan silver jewelry.',
    googleRating: 4.8,
    googleReviewCount: 310,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJDepotNomadeAntiqueSouvenirMerzouga',
    googleMapsUrl: 'https://maps.google.com/?q=Depot+Nomade+Merzouga',
    address: 'N13 Highway, Hassilabied, Merzouga',
    landmark: 'Hassilabied Village Entrance',
    coordinates: { lat: 31.1182, lng: -4.0142 },
    distanceText: '5 min drive from Erg Chebbi dunes',
    navSteps: [
      'Follow the main N13 road through Hassilabied',
      'Look for the large mudbrick showroom with outdoor carpet displays',
      'Enter the carpet hall for tea and weaving demonstrations'
    ],
    what3words: 'dune.carpet.nomad',
    tags: ['Berber Rugs', 'Nomadic Textiles', 'Desert Antiques', 'Saharan Silver', 'leather', 'live-workshop', 'local-favorite'],
    authenticitySeals: ['label_artisanat'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Berber Carpets', 'Brass Lanterns', 'Tuareg Jewelry', 'Leather Poufs'],
    languagesSpoken: ['Arabic', 'English', 'French', 'Berber', 'Spanish'],
    phoneNumber: '+212 662-184520',
    openingHours: [{ day: 'Mon-Sun', hours: '08:00 - 21:00' }],
    shipping: { available: true, partner: 'dhl', details: 'International rug shipping with tracking' },
    workshopVisitable: true,
    isLocalFavorite: true
  },
  {
    id: 'sh-mer-2',
    city: 'merzouga',
    name: 'Driss Fossils and Minerals Shop',
    type: 'boutique',
    category: 'Fossils & Minerals',
    neighborhood: 'Hassilabied',
    description: 'Specialized geological workshop offering authentic prehistoric trilobites, orthoceras fossil carvings, polished ammonites, and Sahara desert minerals.',
    googleRating: 4.9,
    googleReviewCount: 185,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJDrissFossilsAndMineralsShopMerzouga',
    googleMapsUrl: 'https://maps.google.com/?q=Driss+Fossils+Merzouga',
    address: 'Main Street, Hassilabied, Merzouga',
    landmark: 'Hassilabied Oasis Palm Grove',
    coordinates: { lat: 31.1195, lng: -4.0150 },
    distanceText: '2 min walk from Hassilabied Mosque',
    navSteps: [
      'Walk along the main paved street of Hassilabied',
      'Located next to the desert guide office',
      'Look for the glass cases displaying prehistoric ammonites'
    ],
    what3words: 'fossil.stone.desert',
    tags: ['Fossils', 'Trilobites', 'Minerals', 'Geology', 'fixed-price', 'live-workshop'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Trilobite Specimens', 'Ammonite Slabs', 'Desert Roses', 'Geodes'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Berber'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:30 - 20:30' }],
    shipping: { available: true, partner: 'fedex' },
    workshopVisitable: true
  },
  {
    id: 'sh-mer-3',
    city: 'merzouga',
    name: 'Merzouga Nomadic Art Crafts',
    type: 'cooperative',
    category: 'Artisan Crafts',
    neighborhood: 'Hassilabied',
    description: 'Fair-trade desert craft cooperative showcasing hand-woven tribal tapestries, desert indigo fabrics, carved wooden camel figures, and authentic Saharan crafts.',
    googleRating: 4.7,
    googleReviewCount: 140,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJMerzougaNomadicArtCraftsMerzouga',
    googleMapsUrl: 'https://maps.google.com/?q=Merzouga+Nomadic+Art+Crafts',
    address: 'Ksar Hassilabied, Merzouga',
    landmark: 'Hassilabied Cultural Center',
    coordinates: { lat: 31.1170, lng: -4.0130 },
    distanceText: '10 min walk from desert dune edge',
    tags: ['Nomad Crafts', 'Handloom', 'Indigo Dye', 'Saharan Woodwork', 'ceramics'],
    authenticitySeals: ['wfto'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Handwoven Cushions', 'Indigo Wraps', 'Carved Wood', 'Clay Tagines'],
    languagesSpoken: ['Arabic', 'Berber', 'English', 'French'],
    openingHours: [{ day: 'Mon-Sun', hours: '09:00 - 20:00' }]
  },
  {
    id: 'sh-mer-4',
    city: 'merzouga',
    name: 'Chez Aissa le Bedouin',
    type: 'souk_stall',
    category: 'Traditional Clothing',
    neighborhood: 'Merzouga Center',
    description: 'Classic village bazaar in Merzouga center packed with authentic blue Saharan cheich headscarves, indigo gandouras, leather desert boots, and camel bells.',
    googleRating: 4.8,
    googleReviewCount: 95,
    priceLevel: 'budget',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJChezAissaLeBedouinMerzouga',
    googleMapsUrl: 'https://maps.google.com/?q=Chez+Aissa+le+bedouin+Merzouga',
    address: 'Rue Principale, Merzouga Center',
    landmark: 'Merzouga Central Taxi Stand',
    coordinates: { lat: 31.0988, lng: -4.0112 },
    distanceText: 'Center of Merzouga village',
    tags: ['Cheich Turbans', 'Indigo Robes', 'Desert Gear', 'Nomad Clothing', 'leather'],
    paymentMethods: ['cash'],
    productCategories: ['Blue Saharan Turbans', 'Gandoura Robes', 'Leather Sandals', 'Camel Bells'],
    languagesSpoken: ['Arabic', 'Berber', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:00 - 21:00' }]
  },
  {
    id: 'sh-mer-5',
    city: 'merzouga',
    name: 'Souvenirs Shop Merzouga',
    type: 'boutique',
    category: 'Jewelry & Gifts',
    neighborhood: 'Hassilabied',
    description: 'Popular desert gift shop known for handcrafted Tuareg silver pendants, sand-filled hour-glasses, Saharan tea pots, and camel bone trinkets.',
    googleRating: 4.6,
    googleReviewCount: 110,
    priceLevel: 'budget',
    pricingModel: 'mixed',
    isVerified: true,
    googlePlaceId: 'ChIJSouvenirsShopMerzougaMerzouga',
    googleMapsUrl: 'https://maps.google.com/?q=Souvenirs+Shop+Merzouga',
    address: 'N13, Hassilabied, Merzouga',
    landmark: 'Hassilabied Oasis Gate',
    coordinates: { lat: 31.1188, lng: -4.0138 },
    distanceText: '3 min walk from Hassilabied Center',
    tags: ['Tuareg Silver', 'Desert Hourglasses', 'Sahara Tea Sets', 'Souvenirs', 'leather'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Silver Pendants', 'Sand Bottles', 'Brass Teapots', 'Camel Leather Bags'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:30 - 21:00' }]
  },
  {
    id: 'sh-mer-6',
    city: 'merzouga',
    name: 'Depot des Mineraux et Fossiles Chez Hassan',
    type: 'designer_atelier',
    category: 'Fossils & Minerals',
    neighborhood: 'Hassilabied',
    description: 'Expansive mineral showroom showcasing raw desert geodes, polished marble fossil tables, quartz crystals, and prehistoric marine fossils from the Sahara basin.',
    googleRating: 4.8,
    googleReviewCount: 220,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJDepotDesMinerauxEtFossilesChezHassanMerzouga',
    googleMapsUrl: 'https://maps.google.com/?q=Depot+des+Mineraux+Chez+Hassan+Merzouga',
    address: 'Route de Rissani, Hassilabied',
    landmark: 'Erg Chebbi North Turnoff',
    coordinates: { lat: 31.1210, lng: -4.0165 },
    distanceText: '4 min drive north of Hassilabied',
    tags: ['Geodes', 'Fossil Tables', 'Quartz Crystals', 'Sahara Minerals', 'live-workshop'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Fossil Marble Slabs', 'Ammonites', 'Quartz Geodes', 'Desert Rose Stones'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Berber', 'Spanish'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:00 - 19:30' }],
    shipping: { available: true, partner: 'dhl', details: 'Freight shipping for heavy fossil tables' },
    workshopVisitable: true
  },
  {
    id: 'sh-mer-7',
    city: 'merzouga',
    name: 'Depot Alibaba Merzouga',
    type: 'boutique',
    category: 'Brassware & Antiques',
    neighborhood: 'Merzouga Center',
    description: 'Atmospheric bazaar styled after Aladdin’s cave, filled with brass teapots, floor cushions, vintage tribal daggers, and colorful glass lanterns.',
    googleRating: 4.7,
    googleReviewCount: 160,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJDepotAlibabaMerzougaMerzouga',
    googleMapsUrl: 'https://maps.google.com/?q=Depot+Alibaba+Merzouga',
    address: 'Avenue Hassan II, Merzouga',
    landmark: 'Merzouga Grand Mosque',
    coordinates: { lat: 31.0995, lng: -4.0105 },
    distanceText: 'In Merzouga village center',
    tags: ['Brassware', 'Lanterns', 'Tribal Daggers', 'Moroccan Decor', 'leather'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Brass Lamps', 'Tea Sets', 'Nomad Daggers', 'Leather Poufs'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Italian'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:30 - 21:00' }]
  },
  {
    id: 'sh-mer-8',
    city: 'merzouga',
    name: 'Supermarché Ben Sassi Shop',
    type: 'supermarket',
    category: 'Local Provisions',
    neighborhood: 'Merzouga Center',
    description: 'Essential central supply hub for desert expeditions. Sells bottled spring water, dried dates, Saharan mint tea blends, sunscreen, and local dried fruits.',
    googleRating: 4.5,
    googleReviewCount: 130,
    priceLevel: 'budget',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJSupermarchBenSassiShopMerzouga',
    googleMapsUrl: 'https://maps.google.com/?q=BEN+SASSI+SHOP+Merzouga',
    address: 'Rue Principale, Merzouga Center',
    landmark: 'Merzouga Bus Terminal',
    coordinates: { lat: 31.0982, lng: -4.0118 },
    distanceText: '1 min walk from Supratours bus stop',
    tags: ['Groceries', 'Dates', 'Desert Supplies', 'Mint Tea', 'fixed-price'],
    paymentMethods: ['cash'],
    productCategories: ['Rissani Dates', 'Spring Water', 'Green Tea', 'Sun Protection'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '07:30 - 22:00' }]
  },
  {
    id: 'sh-mer-9',
    city: 'merzouga',
    name: 'Marché Merzouga (Weekly Souk)',
    type: 'souk_stall',
    category: 'Local Souk',
    neighborhood: 'Merzouga Center',
    description: 'Vibrant open-air desert market where local nomads and villagers trade fresh produce, Saharan spices, dates, livestock, and handcrafted leather sandals.',
    googleRating: 4.6,
    googleReviewCount: 200,
    priceLevel: 'budget',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJMarchMerzougaWeeklySoukMerzouga',
    googleMapsUrl: 'https://maps.google.com/?q=Marche+Merzouga',
    address: 'Place du Souk, Merzouga',
    landmark: 'Merzouga Weekly Souk Field',
    coordinates: { lat: 31.0970, lng: -4.0125 },
    distanceText: '5 min walk south of village center',
    tags: ['Weekly Souk', 'Nomad Trade', 'Fresh Spices', 'Oasis Produce', 'spices', 'local-favorite'],
    paymentMethods: ['cash'],
    productCategories: ['Fresh Spices', 'Dates', 'Oasis Herbs', 'Traditional Sandals'],
    languagesSpoken: ['Arabic', 'Berber'],
    openingHours: [{ day: 'Sun', hours: '07:00 - 15:00' }, { day: 'Thu', hours: '07:00 - 14:00' }],
    isLocalFavorite: true
  },
  {
    id: 'sh-mer-10',
    city: 'merzouga',
    name: 'Nomad Women’s Weaving Cooperative',
    type: 'cooperative',
    category: 'Carpets & Textiles',
    neighborhood: 'Hassilabied',
    description: 'Social-impact weaving initiative empowering desert women. Produces vibrant wool flat-weave kilims, camel-hair blankets, and natural-dyed runners.',
    googleRating: 4.9,
    googleReviewCount: 175,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJNomadWomenSWeavingCooperativeMerzouga',
    googleMapsUrl: 'https://maps.google.com/?q=Nomad+Women+Weaving+Cooperative+Hassilabied',
    address: 'Douar Hassilabied, Merzouga',
    landmark: 'Hassilabied Women Center',
    coordinates: { lat: 31.1178, lng: -4.0145 },
    distanceText: '4 min walk from Hassilabied main street',
    tags: ['Women Cooperative', 'Handmade Rugs', 'Fair Trade', 'Kilims', 'fixed-price', 'live-workshop'],
    authenticitySeals: ['wfto', 'label_artisanat'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Flat-weave Kilims', 'Camel Wool Blankets', 'Woven Wall Hangings'],
    languagesSpoken: ['Arabic', 'Berber', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:00 - 18:00' }],
    shipping: { available: true, partner: 'la_poste' },
    workshopVisitable: true
  }
]
