import { ShopListing } from '../types'

export const zagoraShops: ShopListing[] = [
  {
    id: 'sh-zag-1',
    city: 'mhamid',
    name: 'Tamgrout Green Pottery Outlet',
    type: 'cooperative',
    category: 'Ceramics & Pottery',
    neighborhood: 'Tamgroute Village',
    description: 'The world-famous green pottery workshop outlet in Tamgroute village, where potters use manganese oxide ore and acacia wood kilns to create emerald-glazed bowls, jars, and oil lamps.',
    googleRating: 4.8,
    googleReviewCount: 410,
    priceLevel: 'budget',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJTamgroutePotteryZagora',
    googleMapsUrl: 'https://maps.google.com/?q=Tamgroute+Pottery+Zagora',
    address: 'Zaouia Tamgroute, N12, Zagora',
    landmark: 'Tamgroute Underground Kasbah & Library',
    coordinates: { lat: 30.2615, lng: -5.6845 },
    distanceText: '18 km south of Zagora town on the road to M\'hamid',
    navSteps: [
      'Take the N12 highway south from Zagora toward Tamgroute',
      'Turn right at the historic Zaouia Naciria library sign',
      'Follow the mudbrick alley to the subterranean wood-fired pottery kilns'
    ],
    what3words: 'green.pottery.emerald',
    tags: ['Tamgroute Green Pottery', 'Manganese Glaze', 'Wood Kilns', 'Saharan Ceramics'],
    authenticitySeals: ['label_artisanat', 'maalem_certified'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Green Emerald Glazed Bowls', 'Water Jars', 'Oil Lamps', 'Candle Holders'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Berber'],
    phoneNumber: '+212 5248-47120',
    openingHours: [{ day: 'Mon-Sun', hours: '08:00 - 18:30' }],
    workshopVisitable: true,
    isLocalFavorite: true
  },
  {
    id: 'sh-zag-2',
    city: 'mhamid',
    name: 'The Zagora Date Souk (Marché des Dattes)',
    type: 'souk_stall',
    category: 'Fresh Produce & Dates',
    neighborhood: 'Centre Ville',
    description: 'Dedicated market square in Zagora where Draa Valley farmers sell sweet Majhoul, Bouskri, and Jihel dates straight from palm groves in woven palm baskets.',
    googleRating: 4.7,
    googleReviewCount: 520,
    priceLevel: 'budget',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJSoukdesDattesZagora',
    googleMapsUrl: 'https://maps.google.com/?q=Souk+des+Dattes+Zagora',
    address: 'Place du Souk, Zagora',
    landmark: 'Zagora Municipal Market',
    coordinates: { lat: 30.3312, lng: -5.8380 },
    distanceText: 'Center of Zagora town',
    tags: ['Draa Valley Dates', 'Majhoul Dates', 'Bouskri Dates', 'Palm Baskets'],
    paymentMethods: ['cash'],
    productCategories: ['Majhoul Dates', 'Bouskri Dates', 'Jihel Dates', 'Date Paste'],
    languagesSpoken: ['Arabic', 'Berber', 'French'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:00 - 19:30' }],
    isLocalFavorite: true
  },
  {
    id: 'sh-zag-3',
    city: 'mhamid',
    name: 'Bazar Timbuktu 52 Jours',
    type: 'boutique',
    category: 'Antiques & Saharan Relics',
    neighborhood: 'Centre Ville',
    description: 'Thematic Saharan antique bazaar named after the iconic "Timbuktu 52 Days by Camel" signpost, filled with Tuareg silver daggers, camel saddles, and desert relics.',
    googleRating: 4.8,
    googleReviewCount: 290,
    priceLevel: 'mid-range',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJBazarTimbuktuZagora',
    googleMapsUrl: 'https://maps.google.com/?q=Bazar+Timbuktu+Zagora',
    address: 'Boulevard Mohammed V, Zagora',
    landmark: 'Timbuktu 52 Days Signpost',
    coordinates: { lat: 30.3325, lng: -5.8395 },
    distanceText: 'Next to the famous Timbuktu street signpost',
    tags: ['Timbuktu 52 Days', 'Tuareg Daggers', 'Camel Saddles', 'Saharan Relics'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Tuareg Silver Crosses', 'Engraved Daggers', 'Leather Camel Saddles', 'Carved Masks'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Berber', 'Spanish'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:30 - 20:30' }]
  },
  {
    id: 'sh-zag-4',
    city: 'mhamid',
    name: 'Cooperative Artisanale d\'Amezrou Silver',
    type: 'cooperative',
    category: 'Jewelry & Silver',
    neighborhood: 'Ksar Amezrou',
    description: 'Historic silver casting workshop in the ancient Jewish Ksar of Amezrou, where silversmiths cast traditional Draa valley silver bangles and geometric pendants.',
    googleRating: 4.9,
    googleReviewCount: 230,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJAmezrouSilverCooperative',
    googleMapsUrl: 'https://maps.google.com/?q=Amezrou+Silver+Cooperative+Zagora',
    address: 'Ksar Amezrou, Zagora',
    landmark: 'Ksar Amezrou Mudbrick Citadel',
    coordinates: { lat: 30.3180, lng: -5.8310 },
    distanceText: '2 km south of Zagora town center',
    tags: ['Amezrou Silver', 'Jewish Ksar Heritage', 'Cast Silver Bangles', 'Draa Valley Silver'],
    authenticitySeals: ['label_artisanat', 'wfto'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Cast Silver Bangles', 'Geometric Draa Pendants', 'Filigree Rings'],
    languagesSpoken: ['Arabic', 'Berber', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sat', hours: '08:30 - 18:30' }],
    workshopVisitable: true
  },
  {
    id: 'sh-zag-5',
    city: 'mhamid',
    name: 'Bazar Nomad Saharien',
    type: 'boutique',
    category: 'Traditional Clothing & Scarves',
    neighborhood: 'Centre Ville',
    description: 'Specialty desert apparel shop stocking dark indigo blue cheich turbans, lightweight gandoura robes, leather camel boots, and Saharan desert wind goggles.',
    googleRating: 4.7,
    googleReviewCount: 180,
    priceLevel: 'budget',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJBazarNomadSaharienZagora',
    googleMapsUrl: 'https://maps.google.com/?q=Bazar+Nomad+Saharien+Zagora',
    address: 'Avenue Hassan II, Zagora',
    landmark: 'Poste Maroc Zagora',
    coordinates: { lat: 30.3330, lng: -5.8370 },
    distanceText: '2 min walk from central square',
    tags: ['Indigo Turbans', 'Gandoura Robes', 'Desert Boots', 'Saharan Gear'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Blue Indigo Cheich Turbans', 'Gandoura Robes', 'Leather Desert Boots', 'Wind Goggles'],
    languagesSpoken: ['Arabic', 'French', 'English', 'Berber'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:00 - 21:00' }]
  },
  {
    id: 'sh-zag-6',
    city: 'mhamid',
    name: 'The Draa Valley Spice House',
    type: 'pharmacy',
    category: 'Spices & Natural Remedies',
    neighborhood: 'Centre Ville',
    description: 'Fragrant oasis spice pharmacy selling pure Draa desert cumin, organic henna powder, wild rose water, black soap, and custom oasis herbal teas.',
    googleRating: 4.8,
    googleReviewCount: 210,
    priceLevel: 'budget',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJDraaValleySpiceHouseZagora',
    googleMapsUrl: 'https://maps.google.com/?q=Draa+Valley+Spice+House+Zagora',
    address: 'Rue du Marché, Zagora',
    landmark: 'Zagora Central Mosque',
    coordinates: { lat: 30.3308, lng: -5.8388 },
    distanceText: '1 min walk from Date Souk',
    tags: ['Desert Cumin', 'Organic Henna', 'Oasis Herbal Teas', 'Rose Water'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Draa Cumin', 'Henna Leaf Powder', 'Black Soap', 'Oasis Mint Tea'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sat', hours: '08:30 - 20:00' }]
  },
  {
    id: 'sh-zag-7',
    city: 'mhamid',
    name: 'Cooperative de Tapis de Zagora',
    type: 'cooperative',
    category: 'Carpets & Reed Mats',
    neighborhood: 'Centre Ville',
    description: 'Artisan weaving collective producing durable Draa reed mats, coarse wool camel-hair blankets, and vibrant flat-weave kilims.',
    googleRating: 4.7,
    googleReviewCount: 140,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJCooperativeTapisZagora',
    googleMapsUrl: 'https://maps.google.com/?q=Cooperative+Tapis+Zagora',
    address: 'Avenue Mohammed V, Zagora',
    landmark: 'Hôtel Reda Zagora',
    coordinates: { lat: 30.3340, lng: -5.8410 },
    distanceText: '4 min walk from city center',
    tags: ['Reed Mats', 'Camel Hair Blankets', 'Flat-weave Kilims', 'Desert Weaving'],
    paymentMethods: ['cash', 'visa', 'mastercard'],
    productCategories: ['Draa Reed Mats', 'Camel Hair Blankets', 'Woven Kilims'],
    languagesSpoken: ['Arabic', 'French', 'Berber'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:00 - 18:00' }]
  },
  {
    id: 'sh-zag-8',
    city: 'mhamid',
    name: 'The Desert Rose Stone Gallery',
    type: 'boutique',
    category: 'Fossils & Stones',
    neighborhood: 'N12 Highway',
    description: 'Roadside mineral gallery selling naturally formed crystalline "desert rose" gypsum formations, quartz geodes, and ancient fossil plates.',
    googleRating: 4.6,
    googleReviewCount: 165,
    priceLevel: 'budget',
    pricingModel: 'negotiable',
    isVerified: true,
    googlePlaceId: 'ChIJDesertRoseStonesZagora',
    googleMapsUrl: 'https://maps.google.com/?q=Desert+Rose+Stones+Zagora',
    address: 'N12 Highway North Entrance, Zagora',
    landmark: 'Zagora Welcome Arch',
    coordinates: { lat: 30.3450, lng: -5.8450 },
    distanceText: '2 km north of town entrance',
    tags: ['Desert Rose Stones', 'Quartz Geodes', 'Sahara Minerals', 'Geology'],
    paymentMethods: ['cash'],
    productCategories: ['Desert Rose Formations', 'Quartz Crystals', 'Fossil Slabs'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sun', hours: '08:00 - 19:00' }]
  },
  {
    id: 'sh-zag-9',
    city: 'mhamid',
    name: 'Amezrou Reed & Palm Weaving Shop',
    type: 'souk_stall',
    category: 'Basketry & Mats',
    neighborhood: 'Ksar Amezrou',
    description: 'Village craft workshop weaving palm-leaf hats, sunshades, fruit baskets, and palm-fiber floor mats harvested from Draa oasis palm groves.',
    googleRating: 4.8,
    googleReviewCount: 120,
    priceLevel: 'budget',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJAmezrouReedWeavingZagora',
    googleMapsUrl: 'https://maps.google.com/?q=Amezrou+Reed+Weaving+Zagora',
    address: 'Ksar Amezrou Oasis Path, Zagora',
    landmark: 'Amezrou Palm Grove Gate',
    coordinates: { lat: 30.3175, lng: -5.8300 },
    distanceText: '2 km south of Zagora center',
    tags: ['Palm Fiber Baskets', 'Oasis Sunshades', 'Palm Leaf Hats', 'Amezrou Weaving'],
    paymentMethods: ['cash'],
    productCategories: ['Palm Leaf Hats', 'Woven Date Baskets', 'Palm Fiber Mats'],
    languagesSpoken: ['Arabic', 'Berber', 'French'],
    openingHours: [{ day: 'Mon-Sat', hours: '08:30 - 18:00' }]
  },
  {
    id: 'sh-zag-10',
    city: 'mhamid',
    name: 'The Zagora Camel Leather Center',
    type: 'designer_atelier',
    category: 'Leather Goods',
    neighborhood: 'Centre Ville',
    description: 'Specialty leather shop producing thick camel-hide travel bags, heat-resistant sandals, belts, and embossed notebook covers.',
    googleRating: 4.8,
    googleReviewCount: 155,
    priceLevel: 'mid-range',
    pricingModel: 'fixed',
    isVerified: true,
    googlePlaceId: 'ChIJCamelLeatherZagora',
    googleMapsUrl: 'https://maps.google.com/?q=Camel+Leather+Zagora',
    address: 'Boulevard Mohammed V, Zagora',
    landmark: 'Hôtel Fibule du Draa',
    coordinates: { lat: 30.3320, lng: -5.8390 },
    distanceText: '3 min walk from central square',
    tags: ['Camel Leather', 'Heat Resistant Sandals', 'Travel Duffels', 'Embossed Leather'],
    paymentMethods: ['cash', 'visa'],
    productCategories: ['Camel Leather Duffels', 'Heavy Sandals', 'Leather Notebook Covers'],
    languagesSpoken: ['Arabic', 'French', 'English'],
    openingHours: [{ day: 'Mon-Sat', hours: '09:00 - 19:00' }],
    workshopVisitable: true
  }
]
