import type { EatListing } from '../types';

/**
 * EAT LISTING TEMPLATE
 * {
 *   id: 'e-[city]-[name]',
 *   city: '[city]',
 *   name: '[Name]',
 *   neighborhood: '[Neighborhood]',
 *   description: '[Long description]',
 *   pricePerPerson: [number],
 *   lifestyle: 'lean' | 'balanced' | 'premium',
 *   mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'latenight', 'afternoon-tea', 'flexible'],
 *   experienceTypes: ['Fine Dining' | 'Waterfront Dining' | 'Romantic Sunset' | 'Beachfront Dining' | 'Garden restaurant with live music' | 'Fountain courtyard' | 'French-Moroccan fusion' | 'Casual Italian Dining' | 'Family Pizza Night' | 'Spanish Beach Lounge' | 'Paella & Tapas' | 'Live Music Terrace' | 'Upscale Romantic Dining' | 'Fine Seafood' | 'Classic Royal Ambiance' | '24/7 Brasserie' | 'People Watching' | 'Bakery-Patisserie' | 'Traditional Breakfast Ritual' | 'Local Gathering Spot' | 'Fishing Harbor Dining' | 'Gourmet Seafood' | 'French-Italian Fusion' | 'Authentic Berber Feast' | 'Traditional Dining' | 'Cozy casual family-run Moroccan eatery' | 'Amazigh-inspired decor' | 'Beachfront Grill' | 'Casual Dining' | 'Sunset Views' | 'Wood-Fired Pizza' | 'Family Friendly' | 'Leafy Tennis Oasis' | 'Tranquil Dining' | 'Upscale Lounge' | 'Modern Fusion Dining' | 'Unverified'],
 *   foodStyles: ['French' | 'Moroccan' | 'Seafood' | 'Mediterranean' | 'European' | 'International' | 'Italian' | 'Pizza' | 'Spanish' | 'Berber' | 'Barbecue' | 'Middle Eastern' | 'Healthy' | 'Cafe' | 'Bakery' | 'Patisserie' | 'Gourmet' | 'Fast Food'],
 *   crowdLevel: 'bustling' | 'balanced' | 'quiet',
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *   hasEnglishStaff: true | false,
 *   hasFrenchStaff: true | false,
 *   hasDelivery: true | false,
 *   hasParking: true | false,
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearCenter: true | false,
 *   isVegetarianFriendly: true | false,
 *   isHalal: true | false,
 *   openTime: 'HH:mm',
 *   closeTime: 'HH:mm',
 *   badge: 'local-favorite' | 'splurge' | 'hidden-gem' | 'local',
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source
 *   // ═══════════════════════════════════════════════════
 *   // Search for real ratings from Google, TripAdvisor, TheFork, and RestaurantGuru.
 *   // If you cannot find a rating for a specific source, set it to the same value as
 *   // the closest available one so the code that calculates average ratings doesn't break.
 *   // Example: if no TripAdvisor rating found, set tripadvisorRating = googleRating
 *
 *   // Google Places rating
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *
 *   // TripAdvisor rating
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *
 *   // TheFork rating
 *   theforkRating: [4.x],
 *   theforkReviewCount: [number],
 *
 *   // RestaurantGuru rating
 *   restaurantguruRating: [4.x],
 *   restaurantguruReviewCount: [number],
 *
 *   // REMOVED: rating, reviewCount, ratingSource (old single-source fields)
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   fullMenu: { type: 'image' | 'text', content: 'https://...' },
 *   tip: '[Short tip]',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   reservationContact: '+212XXXXXXXXX',
 *   bestDishes: ['Dish 1', 'Dish 2'],
 *   alcoholPolicy: 'serves-alcohol' | 'dry',
 *   ramadanFriendly: 'serves-lunch' | 'special-ftour' | 'closed',
 *
 *   // ═══════════════════════════════════════════════════
 *   // NEW FIELDS — psychological UX optimization
 *   // ═══════════════════════════════════════════════════
 *
 *   bestTimeToVisit: 'Early evening around 18:30 for sunset' | 'Lunch around 13:00 for quiet' | 'Late evening after 20:00 for lively crowd' | 'Early morning for fresh baked goods' | 'Sunday morning for brunch peak',
 *   averageWaitMinutes: 0 | 5 | 10 | 15 | 20 | 30 | 45 | 60,
 *   seatingTypes: ['indoor'] | ['terrace'] | ['rooftop'] | ['garden'] | ['beachfront'] | ['indoor', 'terrace'] | ['indoor', 'garden'] | ['terrace', 'rooftop'],
 *   viewType: 'beach' | 'mountain' | 'city' | 'garden' | 'none',
 *   wiFi: true | false,
 *   airConditioning: true | false,
 *   wheelchairAccessible: true | false,
 *   website: 'https://...',
 *   instagram: '@handle' | 'https://instagram.com/...'
 * }
 */

export const agadirEat: EatListing[] = [
  {
    id: 'e-agadir-1',
    city: 'agadir',
    name: 'Pure Passion Restaurant',
    neighborhood: 'Marina Agadir',
    description: 'An elegant waterfront fine-dining jewel overlooking the serene marina yachts. Celebrated for its exquisite French and international fusion, meticulous plating of local seafood, and a refined cosmopolitan terrace.',
    pricePerPerson: 32,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Waterfront Dining', 'Romantic Sunset'],
    foodStyles: ['French', 'Seafood', 'Mediterranean', 'European'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'business-friendly', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '00:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 1800,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 2823,
    theforkRating: 4.5,
    theforkReviewCount: 800,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 2823,

    fullMenu: {
      type: 'image',
      content: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/76/8a/85/pure-passion.jpg?w=900&h=500&s=1'
    },
    tip: 'Book at least 1–2 days ahead. For sunset views without major crowds, arrive around 18:30–19:00.',
    archetypeAffinity: ['luxury', 'first-timer'],
    vibeTags: ['chic', 'scenic', 'polished', 'cosmopolitan'],
    isHiddenGem: false,
    paymentMethods: ['card', 'cash'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212528840120',
    googleMapsUrl: 'https://maps.google.com/?q=Pure+Passion+Restaurant+Agadir',
    bestDishes: ['Grilled Squid / Calamari', 'Ribeye Steak', 'Moroccan Lamb', 'Sea Bass', 'Prawns with Peanut Mayo', 'Tiramisu'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    customStory: "Pure Passion was founded around a 'love and passion for food' philosophy and has become one of Agadir Marina's most popular restaurants. It pairs a European-style fine-dining menu with Moroccan hospitality, beachfront views, and an extensive wine and cocktail list.",
    languagesSpoken: ['French', 'Arabic/Darija', 'English'],
    exactAddressAndCoordinates: {
      address: 'Résidence N°02 M1, Complexe Marina, Agadir 80010, Morocco',
      lat: 30.422686,
      lng: -9.618676
    },
    pros: [
      'Beautiful marina terrace with sunset views and polished presentation.',
      'Attentive, professional service and generous portions.',
      'Wide menu covering seafood, steaks and dietary options.'
    ],
    cons: [
      'Premium prices and highly popular — reservations are essential.',
      'Some diners report inconsistent pacing on very busy nights.'
    ]
  },

  {
    id: 'e-agadir-2',
    city: 'agadir',
    name: 'Les Blancs Agadir',
    neighborhood: 'Marina Agadir',
    description: 'A high-energy Spanish-Moroccan beachfront lounge at the marina entrance. Famous for authentic paella, white-on-white aesthetic, and a lively atmosphere with sunset views and sea breezes.',
    pricePerPerson: 22,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Spanish Beach Lounge', 'Paella & Tapas', 'Live Music Terrace'],
    foodStyles: ['Spanish', 'Seafood', 'Mediterranean', 'European'],
    crowdLevel: 'bustling',
    groupTypes: ['couple', 'friends', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '10:00',
    closeTime: '00:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 3.7,
    googleReviewCount: 300,
    tripadvisorRating: 3.7,
    tripadvisorReviewCount: 463,
    theforkRating: 3.7,
    theforkReviewCount: 100,
    restaurantguruRating: 3.7,
    restaurantguruReviewCount: 463,

    tip: 'No reservation needed for lunch, but dinner fills quickly. Best at 18:30–19:30 for a sunset table.',
    archetypeAffinity: ['luxury', 'first-timer'],
    vibeTags: ['chic', 'scenic', 'polished', 'lively'],
    isHiddenGem: false,
    paymentMethods: ['card', 'cash'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212528828368',
    googleMapsUrl: 'https://maps.google.com/?q=Les+Blancs+Agadir',
    bestDishes: ['Seafood paella', 'Spanish tapas', 'Garlic prawns', 'Fillet steak', 'Sangria'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    customStory: "Les Blancs has established itself as the go-to Spanish beachfront venue at the entrance of Agadir Marina, offering a feet-in-the-sand atmosphere with white-on-white decor, live music, and a menu built around Spanish tapas and seafood.",
    languagesSpoken: ['French', 'Arabic/Darija', 'English', 'Spanish'],
    exactAddressAndCoordinates: {
      address: "Marina d'Agadir, Route Marina, Agadir 80000, Morocco",
      lat: 30.42385,
      lng: -9.615373
    },
    pros: [
      'Prime beach-and-marina location with strong sunset atmosphere.',
      'Authentic Spanish menu (paella, tapas, sangria) in a tourist city.',
      'Live music and late-night lounge vibe.'
    ],
    cons: [
      'Mixed reviews on service consistency during peak hours.',
      'Can be crowded, noisy, and windy on the open terrace.'
    ]
  },

  {
    id: 'e-agadir-3',
    city: 'agadir',
    name: 'Restaurant Yacht Club Agadir',
    neighborhood: 'Fishing Port',
    description: "A refined seafood institution directly in Agadir's working fishing harbor. Celebrated for ultra-fresh fish sourced directly from the morning catch, prepared with French and Italian culinary expertise.",
    pricePerPerson: 32,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fishing Harbor Dining', 'Gourmet Seafood', 'French-Italian Fusion'],
    foodStyles: ['Seafood', 'French', 'Italian', 'Mediterranean'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: false,
    isHalal: true,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '23:30',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 200,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 306,
    theforkRating: 4.2,
    theforkReviewCount: 306,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 306,

    tip: 'Reserve ahead for lunch to get the freshest catch of the day. The oysters gratinées are a standout specialty.',
    archetypeAffinity: ['luxury', 'culture'],
    vibeTags: ['authentic', 'maritime', 'polished'],
    isHiddenGem: true,
    paymentMethods: ['card', 'cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212525090528',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Yacht+Club+Agadir',
    bestDishes: ['Grilled or baked sea bream', 'Oysters gratinées', 'Fish soup', 'Sole meunière'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    customStory: "Restaurant Yacht Club Agadir — also known as Restaurant du Port de Pêche — sits inside the Agadir fishing harbor, one of the busiest in Africa. The venue is built around the daily catch: fishermen unload sardines and shellfish in the morning, which are then transformed into French- and Italian-influenced plates.",
    languagesSpoken: ['French', 'Arabic/Darija', 'English'],
    exactAddressAndCoordinates: {
      address: 'Port de Pêche, Yacht Club, Agadir 80000, Morocco',
      lat: 30.4240313,
      lng: -9.6199724
    },
    pros: [
      "Ultra-fresh seafood sourced directly from Agadir's fishing port.",
      'Authentic harbor atmosphere away from the main tourist promenade.',
      'Strong French and Italian seafood preparation.'
    ],
    cons: [
      'The industrial port area can be intimidating for some visitors.',
      'Premium pricing for specific fish by weight; reservations are essential.'
    ]
  },

  {
    id: 'e-agadir-4',
    city: 'agadir',
    name: 'Tafarnout',
    neighborhood: 'Ville Nouvelle',
    description: "An Agadir institution since 1984. This legendary bakery-patisserie, café, and breakfast room serves the city's finest viennoiseries, traditional breads, and Moroccan pastries.",
    pricePerPerson: 8,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'brunch', 'afternoon-tea'],
    experienceTypes: ['Bakery-Patisserie', 'Traditional Breakfast Ritual', 'Local Gathering Spot'],
    foodStyles: ['French', 'Moroccan', 'Cafe', 'Bakery', 'Patisserie'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '06:00',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 400,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 672,
    theforkRating: 4.2,
    theforkReviewCount: 672,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 672,

    tip: 'Best between 07:00–09:00 for the freshest baked goods. Try the traditional Souss breakfast sets.',
    archetypeAffinity: ['culture', 'first-timer', 'nomad'],
    vibeTags: ['traditional', 'homestyle', 'lively', 'authentic'],
    isHiddenGem: false,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    reservationContact: '+212528844450',
    googleMapsUrl: 'https://maps.google.com/?q=Tafarnout+Agadir',
    bestDishes: ['Fresh Croissants', 'Lemon Tart', 'Traditional Moroccan breakfast set', 'Mint tea'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    customStory: "Pâtisserie Tafarnout has been an Agadir institution since 1984, starting as a traditional bakery and evolving into a full-service patisserie, café, and breakfast room. It remains a morning ritual for locals and visitors seeking fresh baguettes, croissants, and Moroccan pastries.",
    languagesSpoken: ['French', 'Arabic/Darija', 'English'],
    exactAddressAndCoordinates: {
      address: 'Avenue Hassan II, Agadir 80000, Morocco',
      lat: 30.417381,
      lng: -9.596071
    },
    pros: [
      'Excellent quality-to-price ratio for fresh pastries and breakfast.',
      'Long-established local institution with a central location.',
      'Wide selection of breads, cakes, and breakfast set menus.'
    ],
    cons: [
      'Can be crowded and noisy during the morning rush.',
      'Service is efficient rather than leisurely.'
    ]
  },

  {
    id: 'e-agadir-6',
    city: 'agadir',
    name: 'La Scala Restaurant Agadir',
    neighborhood: 'Secteur Touristique',
    description: 'An upscale romantic institution famous for its refined French-Mediterranean seafood. Features a live lobster tank and a polished, classic dining room perfect for special occasions.',
    pricePerPerson: 40,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Upscale Romantic Dining', 'Fine Seafood', 'Classic Royal Ambiance'],
    foodStyles: ['French', 'Seafood', 'International', 'European', 'Mediterranean'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '02:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 600,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 1348,
    theforkRating: 4.1,
    theforkReviewCount: 1348,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 1348,

    tip: 'Complimentary shuttle service is available for guests in nearby hotels. Perfect for a refined dinner with high-quality service.',
    archetypeAffinity: ['first-timer', 'luxury'],
    vibeTags: ['elegant', 'romantic', 'refined', 'upscale'],
    isHiddenGem: false,
    paymentMethods: ['card', 'cash'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212528846773',
    googleMapsUrl: 'https://maps.google.com/?q=La+Scala+Restaurant+Agadir',
    bestDishes: ['Grilled Sole', 'Lobster Thermidor', 'Prime Rib', 'Crème Brûlée'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    customStory: "La Scala has been a fixture of Agadir's tourist-zone dining scene for decades. It built its reputation on a French-influenced menu and a live lobster tank, attracting couples and families seeking a polished evening.",
    languagesSpoken: ['French', 'Arabic/Darija', 'English'],
    exactAddressAndCoordinates: {
      address: 'Rue de l\'Oued Souss, Agadir 80000, Morocco',
      lat: 30.40857,
      lng: -9.598747
    },
    pros: [
      'Consistently refined French-Mediterranean seafood in a polished setting.',
      'Strong value for the tourist-zone quality and large portions.',
      'Free shuttle service and attentive staff.'
    ],
    cons: [
      'Premium pricing compared to main streets.',
      'Music can become loud later in the evening.'
    ]
  },

  {
    id: 'e-agadir-7',
    city: 'agadir',
    name: 'Café Jour et Nuit',
    neighborhood: 'Corniche',
    description: 'An iconic, sprawling beachfront café and brasserie operating 24/7. Highly beloved by families and beachgoers for international comfort food, wood-fired pizzas, local pastries, and perfect oceanfront people-watching.',
    pricePerPerson: 12,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'latenight', 'flexible'],
    experienceTypes: ['Beachfront Dining', '24/7 Brasserie', 'People Watching'],
    foodStyles: ['International', 'Moroccan', 'Pizza'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '00:00',
    closeTime: '23:59',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 3.2,
    googleReviewCount: 200,
    tripadvisorRating: 3.2,
    tripadvisorReviewCount: 305,
    theforkRating: 3.2,
    theforkReviewCount: 305,
    restaurantguruRating: 3.2,
    restaurantguruReviewCount: 305,

    tip: 'Great stop for a late-night snack or a refreshing mint tea after walking along the beach promenade.',
    archetypeAffinity: ['adventure', 'first-timer'],
    vibeTags: ['lively', 'casual', 'coastal'],
    isHiddenGem: false,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212528840610',
    googleMapsUrl: 'https://maps.google.com/?q=Jour+et+Nuit+Agadir',
    bestDishes: ['Pizza Jour et Nuit', 'Beef Kefta Brochettes', 'Traditional Harira Soup'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour'
  },

  {
    id: 'e-agadir-8',
    city: 'agadir',
    name: "Le Jardin d'Eau",
    neighborhood: 'Tourist Zone',
    description: "One of Agadir's oldest dining institutions, set in a lush garden complex on Boulevard du 20 Août. It is beloved for its French-Moroccan fusion cuisine, calming water fountains, and live acoustic music performances most evenings.",
    pricePerPerson: 18,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Garden restaurant with live music', 'Fountain courtyard', 'French-Moroccan fusion'],
    foodStyles: ['French', 'Moroccan', 'Seafood', 'European', 'Healthy'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '10:00',
    closeTime: '01:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 700,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 1299,
    theforkRating: 4.3,
    theforkReviewCount: 1299,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 1299,

    tip: 'Reservations are highly recommended for dinner, particularly on live acoustic music and traditional Bodeguita theme nights.',
    archetypeAffinity: ['culture', 'first-timer'],
    vibeTags: ['charming', 'relaxed', 'melodic', 'festive'],
    isHiddenGem: false,
    paymentMethods: ['card', 'cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212528840195',
    googleMapsUrl: 'https://maps.google.com/?q=Le+Jardin+d+Eau+Agadir',
    bestDishes: ['7-hour slow-braised lamb', 'Seafood / fish platter', 'Lobster fricassee with king prawns', 'Tiramisu', 'Crème brûlée', 'Chocolate moelleux'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    customStory: "Le Jardin d'Eau is one of Agadir's oldest dining institutions, set in a garden complex on Boulevard du 20 Août. It has long been a favorite for French-Moroccan fusion, live music, and a festive 'Bodeguita' atmosphere, pairing tagines and seafood with a lounge-style bar and cocktail program.",
    languagesSpoken: ['French', 'Arabic/Darija', 'English'],
    exactAddressAndCoordinates: {
      address: 'Complexe Tagadirt, Boulevard du 20 Août, Agadir 80000, Morocco',
      lat: 30.4139,
      lng: -9.600732
    },
    pros: [
      'Long-established Agadir institution with reliable French-Moroccan food.',
      'Live music and festive garden atmosphere.',
      'Good value for the location and generous portions.'
    ],
    cons: [
      'Can get crowded and noisy during peak dinner / live-music hours.',
      'Service speed and English fluency vary during busy nights.'
    ]
  },

  {
    id: 'e-agadir-11',
    city: 'agadir',
    name: 'Mimi La Brochette',
    neighborhood: 'Corniche',
    description: 'An iconic beachfront culinary landmark in Agadir. Known for its breezy ocean views, historic Agadir connection, exceptional charcoal grills, and fantastic fresh squid.',
    pricePerPerson: 19,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Beachfront Grill', 'Casual Dining', 'Sunset Views'],
    foodStyles: ['International', 'Barbecue', 'Seafood'],
    crowdLevel: 'bustling',
    groupTypes: ['couple', 'friends', 'family', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '00:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 300,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 435,
    theforkRating: 4.3,
    theforkReviewCount: 435,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 435,

    tip: 'Sit on the upper tier terrace to get the most majestic, uninterrupted breeze and coastal sunset views.',
    archetypeAffinity: ['adventure', 'luxury'],
    vibeTags: ['breezy', 'casual', 'coastal'],
    isHiddenGem: false,
    paymentMethods: ['card', 'cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212691339036',
    googleMapsUrl: 'https://maps.google.com/?q=Mimi+La+Brochette+Agadir',
    bestDishes: ['Charcoal Beef Fillet Skewers', 'Fried Calamari Platter', 'Chocolate Moelleux'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    exactAddressAndCoordinates: {
      address: 'Rue La Plage, Agadir, Morocco',
      lat: 30.4218682,
      lng: -9.6098178
    }
  },

  {
    id: 'e-agadir-12',
    city: 'agadir',
    name: 'Le Mauresque',
    neighborhood: 'Secteur Touristique',
    description: 'A stylish Moroccan restaurant in Agadir\'s tourist zone, known for refined Moroccan dishes, attentive service, and an elegant evening atmosphere.',
    pricePerPerson: 28,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner', 'afternoon-tea'],
    experienceTypes: ['Upscale Lounge', 'Modern Fusion Dining'],
    foodStyles: ['Moroccan', 'International', 'Seafood'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'business-friendly', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '18:00',
    closeTime: '02:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.0,
    googleReviewCount: 200,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 393,
    theforkRating: 4.0,
    theforkReviewCount: 393,
    restaurantguruRating: 4.0,
    restaurantguruReviewCount: 393,

    tip: 'The ocean fusion dishes like seafood tagine with modern saffron-infused risotto are highly unique.',
    archetypeAffinity: ['luxury'],
    vibeTags: ['stylish', 'chic', 'oriental-chic'],
    isHiddenGem: false,
    paymentMethods: ['card', 'cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212528820444',
    googleMapsUrl: 'https://maps.google.com/?q=Le+Mauresque+Agadir',
    bestDishes: ['Saffron Risotto with Tiger Prawns', 'Slow-cooked Lamb Tanjia', 'Traditional Souss Salad'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    exactAddressAndCoordinates: {
      address: '12 Complexe Valtur - Chemin de Oued Souss, Agadir 80000, Morocco',
      lat: 30.406393,
      lng: -9.598389
    }
  },

  {
    id: 'e-agadir-15',
    city: 'agadir',
    name: 'Cafe Restaurant Ibtissam',
    neighborhood: 'Talborjt',
    description: 'An exceptional restaurant in historic Talborjt dedicated to authentic Berber and traditional Moroccan Souss-region culinary heritage. Celebrated for slow-simmered tajines inside real clay pots and rich couscous.',
    pricePerPerson: 11,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Authentic Berber Feast', 'Traditional Dining'],
    foodStyles: ['Moroccan', 'Berber'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '11:30',
    closeTime: '22:30',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 100,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 166,
    theforkRating: 4.3,
    theforkReviewCount: 166,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 166,

    tip: 'Their vegetable tagine cooked strictly in clay pots over embers is deeply flavorful and perfect for vegetarians.',
    archetypeAffinity: ['culture', 'first-timer'],
    vibeTags: ['cozy', 'homestyle', 'friendly'],
    isHiddenGem: true,
    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212670128435',
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Restaurant+Ibtissam+Agadir',
    bestDishes: ['Slow-cooked Vegetable Tagine', 'Beef Tagine with Almonds', 'Friday Souss Couscous'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    exactAddressAndCoordinates: {
      address: 'Place Tamri, Talborjt, Agadir, Morocco',
      lat: 30.4244,
      lng: -9.593001
    }
  },

  {
    id: 'e-agadir-16',
    city: 'agadir',
    name: 'Mezzo Mezzo',
    neighborhood: 'Ville Nouvelle',
    description: 'A cozy Italian bistro in the bustling city center, famed for authentic wood-fired pizzas, delicious creamy pastas, and refreshing gelato in a lively, European-style courtyard.',
    pricePerPerson: 15,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Casual Italian Dining', 'Family Pizza Night'],
    foodStyles: ['Italian', 'Pizza', 'Mediterranean'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '23:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 250,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 381,
    theforkRating: 4.2,
    theforkReviewCount: 381,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 381,

    tip: 'Try the Calzone or any pizza topped with local fresh-cured meats. They can also deliver directly to most hotels.',
    archetypeAffinity: ['first-timer', 'luxury'],
    vibeTags: ['casual', 'kid-friendly', 'lively'],
    isHiddenGem: false,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212666828055',
    googleMapsUrl: 'https://maps.google.com/?q=Mezzo+Mezzo+Agadir',
    bestDishes: ['Wood-Fired Pizza Regina', 'Spaghetti Frutti di Mare', 'Homemade Tiramisu'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    exactAddressAndCoordinates: {
      address: '19 Avenue Hassan II, Agadir 80000, Morocco',
      lat: 30.415997,
      lng: -9.595236
    }
  },

  {
    id: 'e-agadir-17',
    city: 'agadir',
    name: "Restaurant Cote' Court",
    neighborhood: 'City Center',
    description: 'A peaceful, lush garden restaurant located inside the Agadir Royal Tennis Club. Offers a serene, shaded escape from the beach crowds, serving excellent Mediterranean, French-style, and Moroccan plates.',
    pricePerPerson: 17.5,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'brunch'],
    experienceTypes: ['Leafy Tennis Oasis', 'Tranquil Dining'],
    foodStyles: ['Mediterranean', 'French', 'Seafood'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'friends', 'business-friendly', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '11:30',
    closeTime: '23:00',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 150,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 270,
    theforkRating: 4.1,
    theforkReviewCount: 270,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 270,

    tip: 'Perfect choice for a quiet business lunch or a relaxed Sunday afternoon brunch under the tall eucalyptus trees.',
    archetypeAffinity: ['first-timer', 'luxury', 'nomad'],
    vibeTags: ['peaceful', 'verdant', 'refined'],
    isHiddenGem: true,
    paymentMethods: ['card', 'cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212616070760',
    googleMapsUrl: 'https://maps.google.com/?q=Cote+Court+Agadir+Royal+Tennis+Club',
    bestDishes: ['Grilled Monkfish Brochette', 'Steak Tartare', 'Lemon Tart'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    exactAddressAndCoordinates: {
      address: 'Avenue Hassan II, Royal Tennis Club Agadir, Agadir 80020, Morocco',
      lat: 30.417606,
      lng: -9.597778
    }
  },

  {
    id: 'e-agadir-19',
    city: 'agadir',
    name: 'Restaurant Daffy',
    neighborhood: 'Talborjt',
    description: 'A legendary family-run diner tucked away in the authentic Talborjt quarter. Highly celebrated for over 45 years of home-style Moroccan cooking, offering rich tagines and fresh local salads in a warm, Amazigh-infused environment.',
    pricePerPerson: 9,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Cozy casual family-run Moroccan eatery', 'Amazigh-inspired decor', 'Traditional Dining'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Middle Eastern'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '10:00',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 30,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 45,
    theforkRating: 4.5,
    theforkReviewCount: 45,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 45,

    tip: 'Famous for Friday couscous and their slow-cooked beef tagines. Pair it with their signature freshly-brewed hot mint tea.',
    archetypeAffinity: ['culture', 'first-timer'],
    vibeTags: ['warm', 'lively', 'traditional', 'authentic'],
    isHiddenGem: false,
    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212661091614',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Daffy+Agadir',
    bestDishes: ['Beef tagine', 'Kefta tagine', 'Chicken tagine', 'Couscous', 'Harira soup', 'Grilled sardines', 'Mint tea'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    customStory: "Restaurant Daffy is a family-run institution in the Talborjt quarter, celebrated for more than 45 years of home-style Moroccan cooking. The dining room features traditional Amazigh decor, and the menu changes with the market, focusing on fresh tagines, couscous, grilled meats and a justly famous mint tea.",
    languagesSpoken: ['French', 'Arabic/Darija', 'English'],
    exactAddressAndCoordinates: {
      address: '2 Rue des Orangers, Talborjt, Agadir 80000, Morocco',
      lat: 30.422903,
      lng: -9.601278
    },
    pros: [
      'Authentic, affordable Moroccan home cooking in a friendly family setting.',
      'Consistently praised mint tea and traditional harira soup.',
      'Great value and central Talborjt location.'
    ],
    cons: [
      'Small, simple decor and limited seating can mean waits at peak times.',
      'Service can be slow when busy; English menu/communication may be limited.'
    ]
  },

  {
    id: 'e-agadir-21',
    city: 'agadir',
    name: 'La Siciliana',
    neighborhood: 'Ville Nouvelle',
    description: 'A downtown Agadir fixture since 1996, operating a Moroccan-run Italian pizzeria built around a cozy wood-fired oven. Renowned for thin, crispy, and authentic wood-baked crusts paired with highly hospitable service.',
    pricePerPerson: 8,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Pizzeria', 'Wood-Fired Pizza', 'Family Friendly'],
    foodStyles: ['Italian', 'Pizza', 'Seafood'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '00:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 3.7,
    googleReviewCount: 80,
    tripadvisorRating: 3.7,
    tripadvisorReviewCount: 126,
    theforkRating: 3.7,
    theforkReviewCount: 126,
    restaurantguruRating: 3.7,
    restaurantguruReviewCount: 126,

    tip: 'Make sure to order pizza baked natively in the wood-fired brick oven. They are thin, crispy, and baked fresh on order.',
    archetypeAffinity: ['first-timer', 'nomad'],
    vibeTags: ['casual', 'friendly', 'cozy', 'warm'],
    isHiddenGem: false,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212528820973',
    googleMapsUrl: 'https://maps.google.com/?q=La+Siciliana+Agadir',
    bestDishes: ['Wood-fired pizza', 'Calzone', 'Lasagna', 'Tiramisu', 'Crème brûlée'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    customStory: 'La Siciliana has been a downtown Agadir fixture since 1996, operating a Moroccan-run Italian pizzeria built around a wood-fired oven. It is known for thin, crispy pizzas, friendly service, and very reasonable prices, making it a reliable local favorite for casual lunches and dinners.',
    languagesSpoken: ['French', 'Arabic/Darija', 'English'],
    exactAddressAndCoordinates: {
      address: '65 bis & 67 Avenue Hassan II, Ville Nouvelle, Agadir 80020, Morocco',
      lat: 30.421875,
      lng: -9.601104
    },
    pros: [
      'Excellent value: authentic wood-fired pizzas at low prices.',
      'Friendly, welcoming staff and quick service.',
      'Halal and vegetarian-friendly Italian menu.'
    ],
    cons: [
      'Menu and staff primarily in French; English communication may be basic.',
      'Alcohol-free, which may disappoint some tourists expecting wine with pizza.'
    ]
  },

  {
    id: 'e-agadir-darzitoune',
    city: 'agadir',
    name: 'Dar Zitoune',
    neighborhood: 'Taroudant (Region Souss)',
    description: "Located in nearby Taroudant (around 80 km east of Agadir), Dar Zitoune is an exceptional garden riad restaurant set in a one-and-a-half-hectare garden with citrus, papaya, and olive trees. Celebrated as one of the Souss region's finest gourmet tables.",
    pricePerPerson: 40,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Garden Oasis', 'Boutique Riad'],
    foodStyles: ['Moroccan', 'French', 'Mediterranean', 'Gourmet'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'friends', 'business-friendly', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '12:30',
    closeTime: '23:30',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 150,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 246,
    theforkRating: 4.5,
    theforkReviewCount: 246,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 246,

    tip: 'A beautiful gourmet stop on a day-excursion from Agadir. It is recommended to book in advance and request specialty dishes.',
    archetypeAffinity: ['luxury', 'culture'],
    vibeTags: ['romantic', 'peaceful', 'verdant', 'refined'],
    isHiddenGem: true,
    paymentMethods: ['card', 'cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212528551141',
    googleMapsUrl: 'https://maps.google.com/?q=Dar+Zitoune+Taroudant',
    bestDishes: ['Charolais Beef Tartare', 'Smoked Duck-Breast Tatin', 'Traditional Mechoui Lamb', 'Royal Couscous', 'Moroccan Pastilla'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    customStory: "Dar Zitoune ('House of the Olives') opened as a 4-star boutique hotel in 2005, built in traditional Berber style on the edge of Taroudant. Its restaurant is set in a garden of olive, citrus and papaya trees, and is celebrated as one of the finest tables in the Souss region, blending refined European cuisine with Moroccan classics.",
    languagesSpoken: ['French', 'Arabic/Darija', 'English'],
    exactAddressAndCoordinates: {
      address: 'Boutarial El Berrania (N10), Taroudant 83000, Morocco',
      lat: 30.452158,
      lng: -8.880196
    },
    pros: [
      'Stunning garden oasis and Riad-setting with organic estate fruit groves.',
      'High-end gastronomy marrying Moroccan traditional cooking with refined French classics.',
      'Impeccable multilingual hospitality and quiet, romantic ambiance.'
    ],
    cons: [
      'Requires a 1-hour drive east from Agadir (not situated inside Agadir city).',
      'Dinner frequently shifts to a fixed-price set menu, offering less individual menu flexibility.'
    ]
  },

  {
    id: 'e-agadir-kounouz',
    city: 'agadir',
    name: 'Kounouz (Unverified)',
    neighborhood: 'Talborjt',
    description: 'Unverified entry for Kounouz in Talborjt. Location and operational status are currently under review.',
    pricePerPerson: 0,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Unverified'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'quiet',
    groupTypes: ['solo'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: false,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: false,
    isHalal: true,
    halalStatus: 'unknown',
    verificationStatus: 'unverified',
    isTemporarilyHidden: true,
    openTime: '00:00',
    closeTime: '00:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 0,
    googleReviewCount: 0,
    tripadvisorRating: 0,
    tripadvisorReviewCount: 0,
    theforkRating: 0,
    theforkReviewCount: 0,
    restaurantguruRating: 0,
    restaurantguruReviewCount: 0
  },

  {
    id: 'e-agadir-obleu',
    city: 'agadir',
    name: "O'Bleu (Unverified)",
    neighborhood: 'Marina',
    description: "Unverified entry for O'Bleu in Agadir Marina. Location and operational status are currently under review.",
    pricePerPerson: 0,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Unverified'],
    foodStyles: ['International'],
    crowdLevel: 'quiet',
    groupTypes: ['solo'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: false,
    hasParking: false,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: false,
    isHalal: true,
    halalStatus: 'unknown',
    verificationStatus: 'unverified',
    isTemporarilyHidden: true,
    openTime: '00:00',
    closeTime: '00:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 0,
    googleReviewCount: 0,
    tripadvisorRating: 0,
    tripadvisorReviewCount: 0,
    theforkRating: 0,
    theforkReviewCount: 0,
    restaurantguruRating: 0,
    restaurantguruReviewCount: 0
  },

  {
    id: 'e-agadir-snackfounty',
    city: 'agadir',
    name: 'Snack Founty (Unverified)',
    neighborhood: 'Founty',
    description: 'Unverified entry for Snack Founty. Location and operational status are currently under review.',
    pricePerPerson: 0,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Unverified'],
    foodStyles: ['Fast Food'],
    crowdLevel: 'quiet',
    groupTypes: ['solo'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: false,
    isHalal: true,
    halalStatus: 'unknown',
    verificationStatus: 'unverified',
    isTemporarilyHidden: true,
    openTime: '00:00',
    closeTime: '00:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 0,
    googleReviewCount: 0,
    tripadvisorRating: 0,
    tripadvisorReviewCount: 0,
    theforkRating: 0,
    theforkReviewCount: 0,
    restaurantguruRating: 0,
    restaurantguruReviewCount: 0
  }
];