import type { EatListing } from '../types';

/**
 * EAT LISTING TEMPLATE
 * {
 *   id: 'e-[city]-[name]',
 *   city: '[city]',
 *   name: '[Name]',
 *   neighborhood: '[Neighborhood]',
 *   description: '[Long description]',
 *   pricePerPerson: [number],
 *   lifestyle: 'lean' | 'balanced' | 'premium',
 *   mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'latenight', 'afternoon-tea', 'flexible'],
 *   experienceTypes: ['Fine Dining' | 'Waterfront Dining' | 'Romantic Sunset' | 'Beachfront Dining' | 'Garden restaurant with live music' | 'Fountain courtyard' | 'French-Moroccan fusion' | 'Casual Italian Dining' | 'Family Pizza Night' | 'Spanish Beach Lounge' | 'Paella & Tapas' | 'Live Music Terrace' | 'Upscale Romantic Dining' | 'Fine Seafood' | 'Classic Royal Ambiance' | '24/7 Brasserie' | 'People Watching' | 'Bakery-Patisserie' | 'Traditional Breakfast Ritual' | 'Local Gathering Spot' | 'Fishing Harbor Dining' | 'Gourmet Seafood' | 'French-Italian Fusion' | 'Authentic Berber Feast' | 'Traditional Dining' | 'Cozy casual family-run Moroccan eatery' | 'Amazigh-inspired decor' | 'Beachfront Grill' | 'Casual Dining' | 'Sunset Views' | 'Wood-Fired Pizza' | 'Family Friendly' | 'Leafy Tennis Oasis' | 'Tranquil Dining' | 'Upscale Lounge' | 'Modern Fusion Dining' | 'Unverified'],
 *   foodStyles: ['French' | 'Moroccan' | 'Seafood' | 'Mediterranean' | 'European' | 'International' | 'Italian' | 'Pizza' | 'Spanish' | 'Berber' | 'Barbecue' | 'Middle Eastern' | 'Healthy' | 'Cafe' | 'Bakery' | 'Patisserie' | 'Gourmet' | 'Fast Food'],
 *   crowdLevel: 'bustling' | 'balanced' | 'quiet',
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *   hasEnglishStaff: true | false,
 *   hasFrenchStaff: true | false,
 *   hasDelivery: true | false,
 *   hasParking: true | false,
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearCenter: true | false,
 *   isVegetarianFriendly: true | false,
 *   isHalal: true | false,
 *   openTime: 'HH:mm',
 *   closeTime: 'HH:mm',
 *   badge: 'local-favorite' | 'splurge' | 'hidden-gem' | 'local',
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source
 *   // ═══════════════════════════════════════════════════
 *   // Search for real ratings from Google, TripAdvisor, TheFork, and RestaurantGuru.
 *   // If you cannot find a rating for a specific source, set it to the same value as
 *   // the closest available one so the code that calculates average ratings doesn't break.
 *   // Example: if no TripAdvisor rating found, set tripadvisorRating = googleRating
 *
 *   // Google Places rating
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *
 *   // TripAdvisor rating
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *
 *   // TheFork rating
 *   theforkRating: [4.x],
 *   theforkReviewCount: [number],
 *
 *   // RestaurantGuru rating
 *   restaurantguruRating: [4.x],
 *   restaurantguruReviewCount: [number],
 *
 *   // REMOVED: rating, reviewCount, ratingSource (old single-source fields)
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   fullMenu: { type: 'image' | 'text', content: 'https://...' },
 *   tip: '[Short tip]',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   reservationContact: '+212XXXXXXXXX',
 *   bestDishes: ['Dish 1', 'Dish 2'],
 *   alcoholPolicy: 'serves-alcohol' | 'dry',
 *   ramadanFriendly: 'serves-lunch' | 'special-ftour' | 'closed',
 *
 *   // ═══════════════════════════════════════════════════
 *   // NEW FIELDS — psychological UX optimization
 *   // ═══════════════════════════════════════════════════
 *
 *   bestTimeToVisit: 'Early evening around 18:30 for sunset' | 'Lunch around 13:00 for quiet' | 'Late evening after 20:00 for lively crowd' | 'Early morning for fresh baked goods' | 'Sunday morning for brunch peak',
 *   averageWaitMinutes: 0 | 5 | 10 | 15 | 20 | 30 | 45 | 60,
 *   seatingTypes: ['indoor'] | ['terrace'] | ['rooftop'] | ['garden'] | ['beachfront'] | ['indoor', 'terrace'] | ['indoor', 'garden'] | ['terrace', 'rooftop'],
 *   viewType: 'beach' | 'mountain' | 'city' | 'garden' | 'none',
 *   wiFi: true | false,
 *   airConditioning: true | false,
 *   wheelchairAccessible: true | false,
 *   website: 'https://...',
 *   instagram: '@handle' | 'https://instagram.com/...'
 * }
 */

export const asilahEat: EatListing[] = [
  {
    id: 'e-asilah-1',
    city: 'asilah',
    name: 'Casa Garcia',
    neighborhood: 'Medina / Port Entrance',
    description: 'A legendary culinary landmark in Asilah. Highly celebrated for its exceptional Spanish-Mediterranean seafood gastronomy, featuring world-class paella, wild oysters, and expertly grilled daily catches on a sun-drenched terrace.',
    pricePerPerson: 18,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Scenic Views'],
    foodStyles: ['Seafood', 'Spanish', 'Mediterranean'],
    // food-cuisine quiz question tags
    cuisineTags: ['seafood', 'international'],
    crowdLevel: 'bustling',
    groupTypes: ['couple', 'family', 'friends', 'seniors', 'large-groups'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '23:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 3.9,
    googleReviewCount: 1834,
    tripadvisorRating: 3.5,
    tripadvisorReviewCount: 615,
    theforkRating: 3.9,
    theforkReviewCount: 150,
    restaurantguruRating: 3.9,
    restaurantguruReviewCount: 1834,

    tip: 'Often very busy on sunny weekends. The seafood paella and fresh grilled calamari are outstanding. Serves excellent local wine.',
    archetypeAffinity: ['culture', 'luxury'],
    vibeTags: ['lively', 'beachside', 'classic'],
    isHiddenGem: false,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212539417465',
    googleMapsUrl: 'https://maps.google.com/?q=Casa+Garcia+Asilah',
    bestDishes: ['Seafood Paella', 'Grilled Sole', 'Tapas Platter'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch'
  ,
    tags: ["medina","fine","budget","terrace","alcohol","dinner"]
  },

  {
    id: 'e-asilah-2',
    city: 'asilah',
    name: 'Dar Al Maghrebia',
    neighborhood: 'Medina',
    description: 'A charming, beautiful family-run Riad restaurant tucked in a quiet medina alleyway. Highly trusted for its authentic, slow-cooked tagines, pigeon pastillas, and spectacular rooftop dining.',
    pricePerPerson: 11,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'brunch'],
    experienceTypes: ['Traditional Dining', 'Scenic Views', 'Romantic Sunset'],
    foodStyles: ['Moroccan'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 1262,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 420,
    theforkRating: 4.5,
    theforkReviewCount: 180,
    restaurantguruRating: 4.9,
    restaurantguruReviewCount: 1661,

    tip: 'Ask to sit on the rooftop terrace for a peaceful dinner under the stars with lovely medina views.',
    archetypeAffinity: ['culture'],
    vibeTags: ['cozy', 'traditional', 'tranquil', 'warm'],
    isHiddenGem: false,
    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212671043087',
    googleMapsUrl: 'https://maps.google.com/?q=Dar+Al+Maghrebia+Asilah',
    bestDishes: ['Swordfish Tagine', 'Pigeon Pastilla', 'Friday Lamb Couscous'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour'
  ,
    tags: ["breakfast","tagine","couscous","pastilla","riad","sunset","medina","budget","rooftop","dry","dinner"]
  },

  {
    id: 'e-asilah-3',
    city: 'asilah',
    name: "La Perle d'Asilah",
    neighborhood: 'Centre Ville',
    description: "Asilah's premier French-Moroccan gourmet restaurant. Beautifully styled like a Parisian bistro, it features dark-wood furniture and white tablecloths, serving refined fish specials and rich desserts.",
    pricePerPerson: 22,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner', 'brunch'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset'],
    foodStyles: ['French', 'Seafood', 'Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'seniors', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '13:00',
    closeTime: '22:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 410,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 305,
    theforkRating: 4.4,
    theforkReviewCount: 150,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 410,

    tip: 'Closed on Mondays. Highly famous for its chocolate fondue and daily chalk-board fish specials. Excellent wine selection.',
    archetypeAffinity: ['culture', 'luxury'],
    vibeTags: ['elegant', 'romantic', 'refined', 'classic'],
    isHiddenGem: false,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212618418758',
    googleMapsUrl: 'https://maps.google.com/?q=La+Perle+d+Asilah',
    bestDishes: ['Sautéed John Dory', 'Local Crab Salad', 'Indulgent Chocolate Fondue'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch'
  ,
    tags: ["breakfast","sunset","fine","budget","alcohol","dinner"]
  },

  {
    id: 'e-asilah-4',
    city: 'asilah',
    name: 'Port XIV',
    neighborhood: 'Corniche',
    description: 'A gorgeous, light-filled waterfront farm-to-table seafood restaurant. Owned by Karim Ben Ali, it features large bay windows overlooking the sea and an exquisite Art Deco design.',
    pricePerPerson: 19,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Scenic Views', 'Romantic Sunset'],
    foodStyles: ['Seafood', 'Mediterranean'],
    // food-cuisine quiz question tags
    cuisineTags: ['seafood', 'international'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '12:30',
    closeTime: '23:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 624,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 310,
    theforkRating: 4.4,
    theforkReviewCount: 150,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 624,

    tip: 'Karim serves fresh produce sourced directly from his family farm. Their crab and avocado salad with sweet chili vinaigrette is a masterpiece.',
    archetypeAffinity: ['culture', 'luxury'],
    vibeTags: ['scenic', 'art-deco', 'coastal', 'chic'],
    isHiddenGem: false,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212539416677',
    googleMapsUrl: 'https://maps.google.com/?q=Port+XIV+Asilah',
    bestDishes: ['Asilah Crab and Avocado Salad', 'Garlic Butter Clams', 'Grilled Swordfish Steak'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch'
  ,
    tags: ["sunset","fine","budget","alcohol","dinner"]
  },

  {
    id: 'e-asilah-5',
    city: 'asilah',
    name: 'Al Alba Restaurant',
    neighborhood: 'Medina Entrance / Beachfront',
    description: 'A spectacular, highly-rated culinary fusion restaurant located inside Hotel Al Alba. Merges creative Spanish Valencian techniques with profound Moroccan spice heritage.',
    pricePerPerson: 16,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'brunch'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset'],
    foodStyles: ['Mediterranean', 'Moroccan', 'Spanish'],
    // food-cuisine quiz question tags
    cuisineTags: ['international', 'moroccan-traditional'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '13:00',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.9,
    googleReviewCount: 466,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 213,
    theforkRating: 4.8,
    theforkReviewCount: 120,
    restaurantguruRating: 4.9,
    restaurantguruReviewCount: 466,

    tip: 'Collaboration between Chef Jaume from Valencia and Chef Amal from Morocco. Perfect for an intimate, relaxing dinner in a highly tranquil riad setting.',
    archetypeAffinity: ['culture', 'luxury'],
    vibeTags: ['intimate', 'refined', 'creative', 'tranquil'],
    isHiddenGem: false,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212613429190',
    googleMapsUrl: 'https://maps.google.com/?q=Al+Alba+Restaurant+Asilah',
    bestDishes: ['Slow-Cooked Meat stews', 'Creative Pastelas', 'Traditional Valencian Paella'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch'
  ,
    tags: ["breakfast","sunset","medina","fine","budget","alcohol","dinner"]
  },

  {
    id: 'e-asilah-6',
    city: 'asilah',
    name: 'Restaurant Oceano Casa Pepe',
    neighborhood: 'Place Zallaka',
    description: 'A historic town-center institution with a friendly Spanish atmosphere. Celebrated for high-quality seafood, classic tapas, and refreshing sangrias right on Place Zallaka.',
    pricePerPerson: 14,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Traditional Dining'],
    foodStyles: ['Seafood', 'Spanish', 'Mediterranean'],
    // food-cuisine quiz question tags
    cuisineTags: ['seafood', 'international'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '23:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 3.7,
    googleReviewCount: 733,
    tripadvisorRating: 3.1,
    tripadvisorReviewCount: 304,
    theforkRating: 3.5,
    theforkReviewCount: 110,
    restaurantguruRating: 3.7,
    restaurantguruReviewCount: 733,

    tip: 'A superb spot for traditional Spanish tapas. Their complementary appetizers perfectly whet your appetite before ordering fresh sea bass.',
    archetypeAffinity: ['culture'],
    vibeTags: ['classic', 'bustling', 'coastal'],
    isHiddenGem: false,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212539417395',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Oceano+Casa+Pepe+Asilah',
    bestDishes: ['Spanish Garlic Prawns', 'Mixed Sea Tapas', 'Grilled Sea Bass'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch'
  ,
    tags: ["medina","budget","alcohol","dinner"]
  },

  {
    id: 'e-asilah-7',
    city: 'asilah',
    name: 'Restaurant Ali Baba',
    neighborhood: 'Avenue Hassan II',
    description: 'An exceptionally popular casual dining spot facing the ancient Medina ramparts. Highly favored for its rapid service, diverse menu of grilled meats, rotisserie chicken, and fresh seafood.',
    pricePerPerson: 6.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Casual Dining'],
    foodStyles: ['Moroccan', 'Seafood'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'seafood'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '11:00',
    closeTime: '23:30',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 3.7,
    googleReviewCount: 1441,
    tripadvisorRating: 3.5,
    tripadvisorReviewCount: 400,
    theforkRating: 3.7,
    theforkReviewCount: 120,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 1698,

    tip: 'A very welcoming family restaurant. Their grilled sardine platter is a classic street-food style favorite.',
    archetypeAffinity: ['culture', 'first-timer'],
    vibeTags: ['no-frills', 'bustling', 'family-friendly'],
    isHiddenGem: false,
    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212633580050',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Ali+Baba+Asilah',
    bestDishes: ['Grilled Sardines Platter', 'Kofta Tagine with Egg', 'Rotisserie Chicken'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour'
  ,
    tags: ["tagine","medina","budget","dry","dinner"]
  },

  {
    id: 'e-asilah-8',
    city: 'asilah',
    name: 'Le 32 Restaurant',
    neighborhood: 'Avenue Hassan II',
    description: 'A popular modern seafood and Mediterranean restaurant directly overlooking the historic Medina ramparts. Serves beautifully presented fish tajines, paellas, and custom Northern mocktails.',
    pricePerPerson: 11,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Scenic Views'],
    foodStyles: ['Seafood', 'Mediterranean', 'Moroccan'],
    // food-cuisine quiz question tags
    cuisineTags: ['seafood', 'international', 'moroccan-traditional'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 3.8,
    googleReviewCount: 120,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 60,
    theforkRating: 3.8,
    theforkReviewCount: 40,
    restaurantguruRating: 4.0,
    restaurantguruReviewCount: 120,

    tip: 'The restaurant offers a great terrace with direct views of the sunset hitting the medina walls.',
    archetypeAffinity: ['adventure', 'culture'],
    vibeTags: ['modern', 'coastal', 'relaxed', 'scenic'],
    isHiddenGem: false,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212539416452',
    googleMapsUrl: 'https://maps.google.com/?q=Le+32+Restaurant+Asilah',
    bestDishes: ['Octopus Salad', 'Fish Paella', 'Creamy Shrimp Pasta'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour'
  ,
    tags: ["tagine","medina","budget","dry","dinner"]
  },

  {
    id: 'e-asilah-9',
    city: 'asilah',
    name: 'Restaurant Al Kasaba',
    neighborhood: 'Avenue Hassan II',
    description: 'A cozy outdoor dining terrace positioned directly opposite the historic Medina walls. Guests can dine under the shaded canopy of eucalyptus trees, enjoying classic seafood paella.',
    pricePerPerson: 8.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Scenic Views', 'Traditional Dining'],
    foodStyles: ['Moroccan', 'Seafood'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'seafood'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '11:30',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 3.4,
    googleReviewCount: 517,
    tripadvisorRating: 2.9,
    tripadvisorReviewCount: 66,
    theforkRating: 3.2,
    theforkReviewCount: 50,
    restaurantguruRating: 3.4,
    restaurantguruReviewCount: 517,

    tip: 'Highly popular on sunny afternoons. Sit under the eucalyptus trees and try their fresh, value-priced fish pastillas.',
    archetypeAffinity: ['culture', 'first-timer'],
    vibeTags: ['lively', 'shaded', 'relaxed', 'scenic'],
    isHiddenGem: false,
    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212645691802',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Al+Kasaba+Asilah',
    bestDishes: ['Seafood pastilla', 'Grilled Sea Bream', 'Tajine with olives'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch'
  ,
    tags: ["tagine","pastilla","medina","budget","terrace","dry","dinner"]
  },

  {
    id: 'e-asilah-10',
    city: 'asilah',
    name: 'The Blue Door Café',
    neighborhood: 'Medina',
    description: 'A lovely bohemian café in the heart of Asilah\'s white-washed Medina. Renowned for rich coffee, freshly baked pastries, and a beautiful outdoor terrace looking over blue-painted streets.',
    pricePerPerson: 5.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'brunch', 'flexible'],
    experienceTypes: ['Cafe', 'Casual Dining'],
    foodStyles: ['Cafe', 'Mediterranean'],
    // food-cuisine quiz question tags
    cuisineTags: ['cafe-pastry', 'international'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'unknown',
    verificationStatus: 'unverified',
    isTemporarilyHidden: true,
    openTime: '08:30',
    closeTime: '20:00',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 120,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 220,
    theforkRating: 4.5,
    theforkReviewCount: 220,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 220,

    tip: 'A superb spot for digital nomads and early-morning explorers. Try the cappuccino with a fresh almond tart.',
    archetypeAffinity: ['first-timer', 'nomad'],
    vibeTags: ['bohemian', 'relaxed', 'friendly', 'colorful'],
    isHiddenGem: true,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=The+Blue+Door+Cafe+Asilah',
    bestDishes: ['Fresh Almond Tart', 'Vegetable Panini', 'Moroccan Coffee Nos-Nos'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour'
  ,
    tags: ["pastry","cafe-pastry","breakfast","medina","budget","terrace","dry"]
  },

  {
    id: 'e-asilah-11',
    city: 'asilah',
    name: 'Bab Ssour Restaurant',
    neighborhood: 'Medina',
    description: 'Tucked inside a beautiful traditional riad courtyard in the Medina. Renowned for its superb Moroccan home-style stews, fluffy couscous, and custom cooking workshops.',
    pricePerPerson: 9,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Traditional Dining'],
    foodStyles: ['Moroccan'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'unknown',
    verificationStatus: 'wrong-city',
    isTemporarilyHidden: true,
    openTime: '12:00',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 180,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 340,
    theforkRating: 4.6,
    theforkReviewCount: 340,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 340,

    tip: 'You can register for a traditional cooking class here. The slow-simmered beef and prune tagine is extremely popular.',
    archetypeAffinity: ['culture'],
    vibeTags: ['authentic', 'tranquil', 'cozy', 'warm'],
    isHiddenGem: false,
    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Bab+Ssour+Restaurant+Asilah',
    bestDishes: ['Beef Tagine with Prunes', 'Friday Vegetable Couscous', 'Kefta Meatball Claypot'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour'
  ,
    tags: ["tagine","couscous","riad","medina","budget","dry","dinner"]
  },

  {
    id: 'e-asilah-12',
    city: 'asilah',
    name: 'Restaurant Seville',
    neighborhood: 'Avenue Imam-Assili',
    description: 'A delightful traditional restaurant serving outstanding Andalusian-influenced Moroccan fish stews, fresh sea bream, and traditional northern Moroccan soups.',
    pricePerPerson: 12,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Traditional Dining'],
    foodStyles: ['Seafood', 'Spanish', 'Moroccan'],
    // food-cuisine quiz question tags
    cuisineTags: ['seafood', 'international', 'moroccan-traditional'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 3.5,
    googleReviewCount: 221,
    tripadvisorRating: 3.2,
    tripadvisorReviewCount: 85,
    theforkRating: 3.3,
    theforkReviewCount: 40,
    restaurantguruRating: 3.1,
    restaurantguruReviewCount: 335,

    tip: 'Deeply trusted by locals. Their fish tagine features local herbs, olives, and preserves, offering a lighter northern taste.',
    archetypeAffinity: ['culture'],
    vibeTags: ['traditional', 'authentic', 'quiet'],
    isHiddenGem: false,
    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212539418505',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Seville+Asilah',
    bestDishes: ['Seafood Claypot Seville', 'Grilled Seabream', 'Spiced Harira Soup'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour'
  ,
    tags: ["budget","dry","dinner"]
  },

  {
    id: 'e-asilah-13',
    city: 'asilah',
    name: 'Yali Restaurant',
    neighborhood: 'Avenue Ibn Batouta',
    description: 'A trendy coastal seafood spot situated near the city port. Celebrated for its young, energetic staff, incredibly fresh daily catches, and vibrant beachfront vibe.',
    pricePerPerson: 8.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Scenic Views'],
    foodStyles: ['Seafood', 'Mediterranean'],
    // food-cuisine quiz question tags
    cuisineTags: ['seafood', 'international'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'friends', 'couple'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 3.3,
    googleReviewCount: 144,
    tripadvisorRating: 3.3,
    tripadvisorReviewCount: 45,
    theforkRating: 3.3,
    theforkReviewCount: 30,
    restaurantguruRating: 3.3,
    restaurantguruReviewCount: 144,

    tip: 'Positioned right opposite the port, ensuring the fish is caught and cooked within hours. The staff is young and highly welcoming.',
    archetypeAffinity: ['adventure', 'culture', 'first-timer'],
    vibeTags: ['friendly', 'coastal', 'youthful', 'lively'],
    isHiddenGem: false,
    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212671043277',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Sandwicherie+Yali+Asilah',
    bestDishes: ['Crispy Fried Calamari', 'Grilled Sardines', 'Tomato Cucumber Salad'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch'
  ,
    tags: ["budget","dry","dinner"]
  },

  {
    id: 'e-asilah-14',
    city: 'asilah',
    name: 'Restaurant Arrabii',
    neighborhood: 'Avenue Hassan II',
    description: 'A cheerful, convivial local restaurant facing the medina walls under eucalyptus trees. Offers an extensive choice of grilled meats, traditional northern harira, and family-sized seafood tajines.',
    pricePerPerson: 7,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining'],
    foodStyles: ['Moroccan', 'Seafood'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'seafood'],
    crowdLevel: 'bustling',
    groupTypes: ['couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '11:00',
    closeTime: '23:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 3.0,
    googleReviewCount: 76,
    tripadvisorRating: 3.0,
    tripadvisorReviewCount: 30,
    theforkRating: 3.0,
    theforkReviewCount: 20,
    restaurantguruRating: 2.8,
    restaurantguruReviewCount: 76,

    tip: 'Extremely popular with local families. Their spiced lentil soup and charcoal meat skewers are a highly satisfying, cheap local lunch.',
    archetypeAffinity: ['culture', 'first-timer'],
    vibeTags: ['family-friendly', 'bustling', 'cozy'],
    isHiddenGem: false,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Arrabii+Asilah',
    bestDishes: ['Charcoal Meat Skewers', 'Northern Harira Soup', 'Fish Tajine with Spiced Olives'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour'
  ,
    tags: ["tagine","medina","budget","dry","dinner"]
  },

  {
    id: 'e-asilah-15',
    city: 'asilah',
    name: 'Cafe Daya',
    neighborhood: 'Medina / Bab el-Bhar',
    description: 'A scenic clifftop café positioned right next to the historic sea gate of Bab el-Bhar. Famously loved for fresh juices, rich Moroccan coffee, and sweeps of the rugged Atlantic ocean.',
    pricePerPerson: 4,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'flexible', 'afternoon-tea'],
    experienceTypes: ['Cafe', 'Scenic Views'],
    foodStyles: ['Cafe', 'Moroccan'],
    // food-cuisine quiz question tags
    cuisineTags: ['cafe-pastry', 'moroccan-traditional'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '08:00',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 3.5,
    googleReviewCount: 1289,
    tripadvisorRating: 3.4,
    tripadvisorReviewCount: 10,
    theforkRating: 3.5,
    theforkReviewCount: 50,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 1301,

    tip: 'Dine on the roof deck at dusk to capture beautiful photos of the waves breaking on the medina walls while enjoying mint tea.',
    archetypeAffinity: ['culture', 'first-timer'],
    vibeTags: ['scenic', 'sunset-spot', 'cozy', 'oceanfront'],
    isHiddenGem: false,
    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212768452761',
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Daya+Asilah',
    bestDishes: ['Freshly Squeezed Avocado Shake', 'Hot Mint Tea', 'Semolina Harcha Flatbread'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour'
  ,
    tags: ["juice","cafe-pastry","breakfast","medina","budget","dry"]
  },

  {
    id: 'e-asilah-16',
    city: 'asilah',
    name: 'Jus Farid',
    neighborhood: 'Medina',
    description: 'A highly famous, bustling juice bar in the heart of the Medina. Celebrated for its towering freshly-pressed fruit shakes, healthy customized smoothies, and quick sweet tarts.',
    pricePerPerson: 3.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'flexible', 'brunch'],
    experienceTypes: ['Cafe', 'Casual Dining'],
    foodStyles: ['Healthy', 'Cafe'],
    // food-cuisine quiz question tags
    cuisineTags: ['international', 'cafe-pastry'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '09:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.8,
    googleReviewCount: 112,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 50,
    theforkRating: 4.6,
    theforkReviewCount: 30,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 112,

    tip: 'An absolute local favorite for sweet treats. Order their mixed avocado, mango, and date shake—it is thick and incredibly refreshing.',
    archetypeAffinity: ['adventure', 'culture', 'first-timer'],
    vibeTags: ['vibrant', 'healthy', 'friendly', 'fast-paced'],
    isHiddenGem: false,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Jus+Farid+Asilah',
    bestDishes: ['Custom Fruit Smoothie', 'Avocado Date Shake', 'Citrus Orange Juice'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour'
  ,
    tags: ["juice","cafe-pastry","breakfast","medina","budget","dry"]
  },

  {
    id: 'e-asilah-17',
    city: 'asilah',
    name: 'Coffee El Medina',
    neighborhood: 'Medina',
    description: 'A cozy traditional café nestled deep in the white-washed streets of the medina. Offers a quiet courtyard retreat serving local pastries, Moroccan breakfasts, and custom herbal teas.',
    pricePerPerson: 4.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'brunch', 'afternoon-tea'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Traditional Dining'],
    foodStyles: ['Cafe', 'Moroccan'],
    // food-cuisine quiz question tags
    cuisineTags: ['cafe-pastry', 'moroccan-traditional'],
    crowdLevel: 'quiet',
    groupTypes: ['solo', 'couple', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '07:30',
    closeTime: '21:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 3.0,
    googleReviewCount: 40,
    tripadvisorRating: 3.0,
    tripadvisorReviewCount: 25,
    theforkRating: 3.0,
    theforkReviewCount: 15,
    restaurantguruRating: 3.0,
    restaurantguruReviewCount: 40,

    tip: 'Perfect for a quiet morning. Their semolina harcha and local honey make for an exceptional, simple breakfast.',
    archetypeAffinity: ['culture', 'nomad'],
    vibeTags: ['tranquil', 'cozy', 'traditional', 'authentic'],
    isHiddenGem: false,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Coffee+El+Medina+Asilah',
    bestDishes: ['Semolina Harcha with Honey', 'Turkish Style Coffee', 'Local Moroccan Pastries'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour'
  ,
    tags: ["pastry","cafe-pastry","breakfast","medina","budget","dry","quiet"]
  },

  {
    id: 'e-asilah-18',
    city: 'asilah',
    name: 'Restaurant Le Collier de la Méditerranée',
    neighborhood: 'Corniche',
    description: 'A gorgeous ocean-facing seafood restaurant located right on the corniche. Highly celebrated for its massive portions of seafood paella and slow-simmered Moroccan fish stews.',
    pricePerPerson: 15,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Scenic Views'],
    foodStyles: ['Seafood', 'Moroccan', 'Mediterranean'],
    // food-cuisine quiz question tags
    cuisineTags: ['seafood', 'moroccan-traditional', 'international'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'unknown',
    verificationStatus: 'unverified',
    isTemporarilyHidden: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 250,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 450,
    theforkRating: 4.3,
    theforkReviewCount: 450,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 450,

    tip: 'Request a window seat for spectacular views of the Atlantic while enjoying a traditional fish pastilla.',
    archetypeAffinity: ['adventure', 'culture'],
    vibeTags: ['scenic', 'beachside', 'classic', 'breezy'],
    isHiddenGem: false,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Le+Collier+de+la+Mediterranee+Asilah',
    bestDishes: ['Atlantic Fish Pastilla', 'Seafood Paella', 'Spiced Fish Tagine'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch'
  ,
    tags: ["tagine","pastilla","budget","dry","dinner"]
  },

  {
    id: 'e-asilah-19',
    city: 'asilah',
    name: 'Café Daymoun',
    neighborhood: 'Medina',
    description: 'A delightful bohemian café hidden inside the white-washed streets of the old Medina. Features cozy whitewashed terrace seating, serving fresh coffees, local sweet mint teas, and pastries.',
    pricePerPerson: 4,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'flexible', 'afternoon-tea'],
    experienceTypes: ['Cafe', 'Casual Dining'],
    foodStyles: ['Cafe', 'Moroccan'],
    // food-cuisine quiz question tags
    cuisineTags: ['cafe-pastry', 'moroccan-traditional'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'unknown',
    verificationStatus: 'unverified',
    isTemporarilyHidden: true,
    openTime: '08:00',
    closeTime: '21:30',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 80,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 160,
    theforkRating: 4.5,
    theforkReviewCount: 160,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 160,

    tip: 'Tucked away from the busy main squares. Sit on the lovely top terrace for a relaxed, quiet afternoon tea.',
    archetypeAffinity: ['culture', 'first-timer', 'nomad'],
    vibeTags: ['bohemian', 'cozy', 'tranquil', 'hidden'],
    isHiddenGem: true,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Daymoun+Asilah',
    bestDishes: ['Local Honey Pancakes (Msemen)', 'Traditional Sage Tea', 'Assorted Almond Biscuits'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour'
  ,
    tags: ["pastry","cafe-pastry","breakfast","medina","budget","terrace","dry"]
  },

  {
    id: 'e-asilah-20',
    city: 'asilah',
    name: 'Snack Moulay',
    neighborhood: 'Avenue Hassan II',
    description: 'A highly bustling, budget-friendly local street food sandwich stall. Famously loved for serving northern-style bocadillos stuffed with tuna, boiled eggs, and crispy fresh sardines.',
    pricePerPerson: 3,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'latenight', 'flexible'],
    experienceTypes: ['Casual Dining'],
    foodStyles: ['Moroccan', 'Seafood'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'seafood'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'unknown',
    verificationStatus: 'unverified',
    isTemporarilyHidden: true,
    openTime: '11:00',
    closeTime: '02:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 250,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 480,
    theforkRating: 4.4,
    theforkReviewCount: 480,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 480,

    tip: 'The cheapest place near the medina gates for a quick, exceptionally tasty sandwich wrap. Try the freshly grilled local sardine box.',
    archetypeAffinity: ['first-timer'],
    vibeTags: ['no-frills', 'fast-paced', 'bustling', 'popular'],
    isHiddenGem: false,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Snack+Moulay+Asilah',
    bestDishes: ['Northern Tuna Bocadillo', 'Crispy Grilled Sardines Box', 'French Fries with Garlic dip'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour'
  ,
    tags: ["street-food","late-night","medina","budget","dry","dinner"]
  }
];