import type { EatListing } from '../types';

/**
 * EAT LISTING TEMPLATE
 * {
 *   id: 'e-[city]-[name]',
 *   city: '[city]',
 *   name: '[Name]',
 *   neighborhood: '[Neighborhood]',
 *   description: '[Long description]',
 *   pricePerPerson: [number],
 *   lifestyle: 'lean' | 'balanced' | 'premium',
 *   mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'latenight', 'afternoon-tea', 'flexible'],
 *   experienceTypes: ['Fine Dining' | 'Waterfront Dining' | 'Romantic Sunset' | 'Beachfront Dining' | 'Garden restaurant with live music' | 'Fountain courtyard' | 'French-Moroccan fusion' | 'Casual Italian Dining' | 'Family Pizza Night' | 'Spanish Beach Lounge' | 'Paella & Tapas' | 'Live Music Terrace' | 'Upscale Romantic Dining' | 'Fine Seafood' | 'Classic Royal Ambiance' | '24/7 Brasserie' | 'People Watching' | 'Bakery-Patisserie' | 'Traditional Breakfast Ritual' | 'Local Gathering Spot' | 'Fishing Harbor Dining' | 'Gourmet Seafood' | 'French-Italian Fusion' | 'Authentic Berber Feast' | 'Traditional Dining' | 'Cozy casual family-run Moroccan eatery' | 'Amazigh-inspired decor' | 'Beachfront Grill' | 'Casual Dining' | 'Sunset Views' | 'Wood-Fired Pizza' | 'Family Friendly' | 'Leafy Tennis Oasis' | 'Tranquil Dining' | 'Upscale Lounge' | 'Modern Fusion Dining' | 'Unverified'],
 *   foodStyles: ['French' | 'Moroccan' | 'Seafood' | 'Mediterranean' | 'European' | 'International' | 'Italian' | 'Pizza' | 'Spanish' | 'Berber' | 'Barbecue' | 'Middle Eastern' | 'Healthy' | 'Cafe' | 'Bakery' | 'Patisserie' | 'Gourmet' | 'Fast Food'],
 *   crowdLevel: 'bustling' | 'balanced' | 'quiet',
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *   hasEnglishStaff: true | false,
 *   hasFrenchStaff: true | false,
 *   hasDelivery: true | false,
 *   hasParking: true | false,
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearCenter: true | false,
 *   isVegetarianFriendly: true | false,
 *   isHalal: true | false,
 *   openTime: 'HH:mm',
 *   closeTime: 'HH:mm',
 *   badge: 'local-favorite' | 'splurge' | 'hidden-gem' | 'local',
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source
 *   // ═══════════════════════════════════════════════════
 *   // Search for real ratings from Google, TripAdvisor, TheFork, and RestaurantGuru.
 *   // If you cannot find a rating for a specific source, set it to the same value as
 *   // the closest available one so the code that calculates average ratings doesn't break.
 *   // Example: if no TripAdvisor rating found, set tripadvisorRating = googleRating
 *
 *   // Google Places rating
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *
 *   // TripAdvisor rating
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *
 *   // TheFork rating
 *   theforkRating: [4.x],
 *   theforkReviewCount: [number],
 *
 *   // RestaurantGuru rating
 *   restaurantguruRating: [4.x],
 *   restaurantguruReviewCount: [number],
 *
 *   // REMOVED: rating, reviewCount, ratingSource (old single-source fields)
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   fullMenu: { type: 'image' | 'text', content: 'https://...' },
 *   tip: '[Short tip]',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   reservationContact: '+212XXXXXXXXX',
 *   bestDishes: ['Dish 1', 'Dish 2'],
 *   alcoholPolicy: 'serves-alcohol' | 'dry',
 *   ramadanFriendly: 'serves-lunch' | 'special-ftour' | 'closed',
 *
 *   // ═══════════════════════════════════════════════════
 *   // NEW FIELDS — psychological UX optimization
 *   // ═══════════════════════════════════════════════════
 *
 *   bestTimeToVisit: 'Early evening around 18:30 for sunset' | 'Lunch around 13:00 for quiet' | 'Late evening after 20:00 for lively crowd' | 'Early morning for fresh baked goods' | 'Sunday morning for brunch peak',
 *   averageWaitMinutes: 0 | 5 | 10 | 15 | 20 | 30 | 45 | 60,
 *   seatingTypes: ['indoor'] | ['terrace'] | ['rooftop'] | ['garden'] | ['beachfront'] | ['indoor', 'terrace'] | ['indoor', 'garden'] | ['terrace', 'rooftop'],
 *   viewType: 'beach' | 'mountain' | 'city' | 'garden' | 'none',
 *   wiFi: true | false,
 *   airConditioning: true | false,
 *   wheelchairAccessible: true | false,
 *   website: 'https://...',
 *   instagram: '@handle' | 'https://instagram.com/...'
 * }
 */

export const chefchaouenEat: EatListing[] = [
  {
    id: 'chefchaouen-eat-1',
    city: 'chefchaouen',
    name: 'Beldi Bab Ssour',
    neighborhood: 'Medina',
    description: 'Home-cooked mountain-style stews, goat tagines, and creamy bissara served in a bustling, unpretentious multi-story medina setting.',
    pricePerPerson: 8,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery', 'Sunset Views'],
    foodStyles: ['Moroccan', 'Berber'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends', 'family', 'kids-friendly'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 3205,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 1529,
    theforkRating: 4.3,
    theforkReviewCount: 1529,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 3205,

    paymentMethods: ['cash-only'],
    reservationMethod: ['phone', 'walk-in-only'],
    reservationContact: '+212660262256',
    googleMapsUrl: 'https://maps.google.com/?q=Beldi+Bab+Ssour+Chefchaouen',
    bestDishes: ['Goat Tagine', 'Bissara Soup', 'Kefta in Tomato Sauce'],
    tip: 'Arrive slightly before standard dining hours; their famous goat tagine sells out quickly.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'rooftop'],
    viewType: 'mountain',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'chefchaouen-eat-2',
    city: 'chefchaouen',
    name: 'Sofia\'s Restaurant',
    neighborhood: 'Medina',
    description: 'Cozy, women-owned eatery near the plaza presenting highly-rated, generations-old family recipes and outstandingly creative vegetable tagines.',
    pricePerPerson: 4.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Healthy'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 52,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 1042,
    theforkRating: 4.5,
    theforkReviewCount: 1042,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 2141,

    paymentMethods: ['cash-only'],
    reservationMethod: ['phone', 'walk-in-only'],
    reservationContact: '+212670349811',
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Restaurant+Sofia+Chefchaouen',
    bestDishes: ['Vegetable Tagine', 'Beef Carpaccio', 'Harira Soup'],
    tip: 'Ask Sofia about her off-menu seasonal vegetable sides; they are incredibly fresh and locally sourced.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'chefchaouen-eat-3',
    city: 'chefchaouen',
    name: 'Cafe Clock Chefchaouen',
    neighborhood: 'Medina',
    description: 'Vibrant cultural cafe in a lovely blue-washed riad, famous for camel burgers, storytelling, and panoramic rooftop mountain views.',
    pricePerPerson: 9.5,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'brunch', 'lunch', 'dinner', 'afternoon-tea'],
    experienceTypes: ['Cafe', 'Sunset Views', 'Traditional Dining'],
    foodStyles: ['Moroccan', 'International', 'Cafe'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends', 'kids-friendly', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '09:00',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 1985,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 481,
    theforkRating: 4.5,
    theforkReviewCount: 481,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 1985,

    paymentMethods: ['cash-only', 'credit-cards'],
    reservationMethod: ['walk-in-only'],
    reservationContact: '+212539988788',
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Clock+Chefchaouen',
    bestDishes: ['Spiced Camel Burger', 'Avocado Date Milkshake', 'Shakshuka'],
    tip: 'Check their weekly schedule for live Riffian musical sessions and traditional storytelling nights.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor', 'rooftop'],
    viewType: 'mountain',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'chefchaouen-eat-4',
    city: 'chefchaouen',
    name: 'Restaurant Lala Mesouda',
    neighborhood: 'Medina',
    description: 'Traditional homestyle cooking in the upper medina, celebrating generations-old Fassi culinary secrets and slow-braised mountain meats.',
    pricePerPerson: 9,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'seniors'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: false,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:00',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 1043,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 489,
    theforkRating: 4.4,
    theforkReviewCount: 489,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 1043,

    paymentMethods: ['cash-only', 'credit-cards'],
    reservationMethod: ['phone'],
    reservationContact: '+212615546321',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Lala+Mesouda+Chefchaouen',
    bestDishes: ['Lamb Tagine with Prunes', 'Chicken Pastilla', 'Tfaya Couscous'],
    tip: 'Their domestic-style kitchen serves hard-to-find regional wild herb starters; ask for the daily recommendations.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'city',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'chefchaouen-eat-5',
    city: 'chefchaouen',
    name: 'Triana Café & Restaurant',
    neighborhood: 'Medina',
    description: 'Luxurious, high-end rooftop dining blending Spanish-Andalusian refinement with local Rif mountain herbs, mocktails, and romantic sunset views.',
    pricePerPerson: 22,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Upscale Lounge'],
    foodStyles: ['Spanish', 'Mediterranean', 'Moroccan', 'Seafood'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'business-friendly', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: false,
    isHalal: false,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 3.6,
    googleReviewCount: 233,
    tripadvisorRating: 3.6,
    tripadvisorReviewCount: 233,
    theforkRating: 3.6,
    theforkReviewCount: 233,
    restaurantguruRating: 3.6,
    restaurantguruReviewCount: 233,

    paymentMethods: ['credit-cards', 'cash-only'],
    reservationMethod: ['phone', 'instagram'],
    reservationContact: '+212539987050',
    googleMapsUrl: 'https://maps.google.com/?q=Triana+Chefchaouen',
    bestDishes: ['Seafood Paella', 'Tapas Platter', 'Grilled Sea Bass'],
    tip: 'Book a table on the upper rooftop deck at sunset for one of the most stunning, clear mountain vistas.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor', 'rooftop', 'terrace'],
    viewType: 'mountain',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'chefchaouen-eat-6',
    city: 'chefchaouen',
    name: 'Restaurant Aladdin',
    neighborhood: 'Medina',
    description: 'Charming multi-level landmark on the main square with an Arabian Nights feel, spectacular Kasbah views, and sweet pastillas.',
    pricePerPerson: 8.5,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Sunset Views'],
    foodStyles: ['Moroccan', 'Mediterranean'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    crowdLevel: 'bustling',
    groupTypes: ['family', 'couple', 'friends', 'large-groups'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: false,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 800,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 1600,
    theforkRating: 4.1,
    theforkReviewCount: 1600,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 800,

    paymentMethods: ['credit-cards', 'cash-only'],
    reservationMethod: ['phone', 'instagram'],
    reservationContact: '+212539989071',
    googleMapsUrl: 'https://maps.google.com/?q=Aladdin+Restaurant+Chefchaouen',
    bestDishes: ['Chicken Pastilla', 'Lamb Tagine with Almonds', 'Eggplant Zaalouk'],
    tip: 'Sit by the cozy roaring fireplace on the middle floors during chilly mountain winter evenings.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'rooftop'],
    viewType: 'city',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'chefchaouen-eat-7',
    city: 'chefchaouen',
    name: 'Casa Hassan',
    neighborhood: 'Medina',
    description: 'Cozy, textile-decorated institution with a roaring open fireplace, highly regarded for its fresh Friday-only traditional beef couscous.',
    pricePerPerson: 9.5,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Mediterranean'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    crowdLevel: 'bustling',
    groupTypes: ['family', 'couple', 'seniors'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: false,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 600,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 1200,
    theforkRating: 4.3,
    theforkReviewCount: 1200,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 600,

    paymentMethods: ['credit-cards', 'cash-only'],
    reservationMethod: ['phone'],
    reservationContact: '+212539986153',
    googleMapsUrl: 'https://maps.google.com/?q=Casa+Hassan+Chefchaouen',
    bestDishes: ['Preserved Lemon Chicken Tagine', 'Friday Beef Couscous', 'Goat Cheese Salad'],
    tip: 'They only serve their legendary, slow-steamed traditional couscous on Fridays—plan your visit accordingly.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'chefchaouen-eat-8',
    city: 'chefchaouen',
    name: 'Auberge Dardara',
    neighborhood: 'Derdara',
    description: 'Rustic, farm-to-table mountain escape outside Chefchaouen specializing in wild Rif herbs, artisanal goat cheeses, and premium olive oils.',
    pricePerPerson: 18,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner', 'brunch'],
    experienceTypes: ['Fine Dining', 'Garden restaurant with live music'],
    foodStyles: ['Moroccan', 'Berber', 'Mediterranean', 'Gourmet'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'seniors', 'business-friendly'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 240,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 193,
    theforkRating: 4.2,
    theforkReviewCount: 193,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 240,

    paymentMethods: ['credit-cards', 'cash-only'],
    reservationMethod: ['phone', 'whatsapp'],
    reservationContact: '+212539981155',
    googleMapsUrl: 'https://maps.google.com/?q=Auberge+Dardara+Chefchaouen',
    bestDishes: ['Goat Tagine', 'Bissara Soup', 'Fresh Mountain Salads'],
    tip: 'This licensed spot outside town is the premier choice for pairing wild-caught trout with cold Moroccan wine.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'garden', 'terrace'],
    viewType: 'mountain',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'chefchaouen-eat-9',
    city: 'chefchaouen',
    name: 'Pizzeria Mandala',
    neighborhood: 'Medina Edge',
    description: 'Charming, welcoming Italian favorite steps from the medina, offering wood-fired pizzas, delicious pasta, and great vegan cheese options.',
    pricePerPerson: 7.5,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Italian Dining', 'Family Pizza Night'],
    foodStyles: ['Italian', 'Pizza', 'International'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends', 'kids-friendly'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 400,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 800,
    theforkRating: 4.5,
    theforkReviewCount: 800,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 400,

    paymentMethods: ['cash-only', 'credit-cards'],
    reservationMethod: ['phone', 'walk-in-only'],
    reservationContact: '+212539986161',
    googleMapsUrl: 'https://maps.google.com/?q=Pizzeria+Mandala+Chefchaouen',
    bestDishes: ['Four-Cheese Pizza', 'Truffle Pasta', 'Vegan Cheeseburger'],
    tip: 'If you need a break from traditional tagines, their authentic Italian-style wood-fired pizzas hit the spot.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: true
  },

  {
    id: 'chefchaouen-eat-10',
    city: 'chefchaouen',
    name: 'Dar Com',
    neighborhood: 'Medina',
    description: 'Beautiful, plant-filled riad providing healthy Moroccan salads, hearty vegetarian couscous, and peaceful, romantic multi-level terrace seating.',
    pricePerPerson: 11,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Sunset Views'],
    foodStyles: ['Moroccan', 'Healthy'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'solo', 'seniors'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 350,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 700,
    theforkRating: 4.4,
    theforkReviewCount: 700,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 350,

    paymentMethods: ['cash-only'],
    reservationMethod: ['phone'],
    reservationContact: '+212539989123',
    googleMapsUrl: 'https://maps.google.com/?q=Dar+Com+Chefchaouen',
    bestDishes: ['Seven-Vegetable Couscous', 'Moroccan Salad Tasting Platter', 'Sliced Oranges with Cinnamon'],
    tip: 'This place is a dream for vegetarians; order their comprehensive multi-plate Moroccan salad tasting sampler.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace', 'rooftop'],
    viewType: 'mountain',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'chefchaouen-eat-11',
    city: 'chefchaouen',
    name: 'El Cielo',
    neighborhood: 'Medina Edge',
    description: 'Charming garden oasis at Molino Garden Hotel offering organic Arabic fusion dishes, lush mountain views, and romantic atmosphere.',
    pricePerPerson: 11.5,
    lifestyle: 'premium',
    mealTypes: ['breakfast', 'lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Garden restaurant with live music', 'Romantic Sunset'],
    foodStyles: ['Mediterranean', 'International', 'Healthy'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'solo', 'seniors'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: false,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '23:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 200,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 400,
    theforkRating: 4.7,
    theforkReviewCount: 400,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 200,

    paymentMethods: ['credit-cards', 'cash-only'],
    reservationMethod: ['phone', 'instagram'],
    reservationContact: '+212610123456',
    googleMapsUrl: 'https://maps.google.com/?q=El+Cielo+Chefchaouen',
    bestDishes: ['Moroccan-Style Lamb', 'Falafel Mezze Platter', 'Chicken Tandoori Pita'],
    tip: 'Perfect for a serene, romantic dinner surrounded by lush gardens, koi ponds, and towering bamboo.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'chefchaouen-eat-12',
    city: 'chefchaouen',
    name: 'Twins Restaurant',
    neighborhood: 'Medina',
    description: 'Lively square-side hotspot featuring sizzling steaks, hearty pizzas, and traditional tagines with prime, front-row outdoor people-watching seats.',
    pricePerPerson: 7,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Casual Dining', 'People Watching'],
    foodStyles: ['International', 'Moroccan'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    crowdLevel: 'bustling',
    groupTypes: ['friends', 'family', 'kids-friendly'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: false,
    isHalal: true,
    openTime: '11:00',
    closeTime: '23:30',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.0,
    googleReviewCount: 500,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 1000,
    theforkRating: 4.0,
    theforkReviewCount: 1000,
    restaurantguruRating: 4.0,
    restaurantguruReviewCount: 500,

    paymentMethods: ['cash-only', 'credit-cards'],
    reservationMethod: ['phone', 'walk-in-only'],
    reservationContact: '+212654730577',
    googleMapsUrl: 'https://maps.google.com/?q=Twins+Restaurant+Chefchaouen',
    bestDishes: ['Sizzling Beef Steak', 'Vegetarian Pizza', 'White Bean Soup'],
    tip: 'Their outdoor patio tables face Outa el-Hammam square directly, making it the perfect spot for people-watching.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'chefchaouen-eat-13',
    city: 'chefchaouen',
    name: 'Restaurant Jbaria',
    neighborhood: 'Medina',
    description: 'Charming family-run diner right down the street from Bab Ssour, praised for highly affordable, generously portioned Moroccan stews.',
    pricePerPerson: 6.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    crowdLevel: 'balanced',
    groupTypes: ['family', 'solo', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: false,
    isHalal: true,
    openTime: '11:00',
    closeTime: '22:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 300,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 600,
    theforkRating: 4.6,
    theforkReviewCount: 600,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 300,

    paymentMethods: ['cash-only'],
    reservationMethod: ['phone', 'walk-in-only'],
    reservationContact: '+212664316007',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Jbaria+Chefchaouen',
    bestDishes: ['Chicken Tagine with Olives', 'Beef Couscous', 'Tomato Kefta'],
    tip: 'If you love extra broth with your Friday couscous, ask the staff politely and they will gladly bring extra.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'chefchaouen-eat-14',
    city: 'chefchaouen',
    name: 'Restaurant Morisco',
    neighborhood: 'Medina',
    description: 'Lively plaza terrace restaurant famous for its traditional Ftour Beldi breakfast of fresh mountain goat cheese and olives.',
    pricePerPerson: 5.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner'],
    experienceTypes: ['Cafe', 'Traditional Breakfast Ritual', 'Casual Dining'],
    foodStyles: ['Moroccan', 'Mediterranean'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends', 'kids-friendly'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '22:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 400,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 800,
    theforkRating: 4.2,
    theforkReviewCount: 800,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 400,

    paymentMethods: ['cash-only', 'credit-cards'],
    reservationMethod: ['phone', 'walk-in-only'],
    reservationContact: '+212539987114',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Morisco+Chefchaouen',
    bestDishes: ['Ftour Beldi Breakfast', 'Lamb Tagine', 'Mint Tea'],
    tip: 'Enjoying their traditional mountain breakfast while watching the medina wake up is highly recommended.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'chefchaouen-eat-15',
    city: 'chefchaouen',
    name: 'Assaada',
    neighborhood: 'Medina Edge',
    description: 'Generous, ultra-budget local diner serving quick, piping-hot roasted chicken, comforting lentil soups, and robust, slow-cooked meat tagines.',
    pricePerPerson: 4,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Local Gathering Spot'],
    foodStyles: ['Moroccan'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends', 'family'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: false,
    isHalal: true,
    openTime: '09:00',
    closeTime: '21:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 350,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 700,
    theforkRating: 4.3,
    theforkReviewCount: 700,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 350,

    paymentMethods: ['cash-only'],
    reservationMethod: ['phone', 'walk-in-only'],
    reservationContact: '+212619569778',
    googleMapsUrl: 'https://maps.google.com/?q=Assaada+Chefchaouen',
    bestDishes: ['Roasted Chicken with Fries', 'Lamb Kefta', 'White Beans'],
    tip: 'This is a great spot to try traditional bean soups with freshly baked local flatbread.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'chefchaouen-eat-16',
    city: 'chefchaouen',
    name: 'Café Sindibad',
    neighborhood: 'Medina',
    description: 'Spacious, relaxed cafe tucked behind the historic Kasbah, offering cheap Moroccan mint tea and unbeatable panoramic medina views.',
    pricePerPerson: 3.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'flexible'],
    experienceTypes: ['Cafe', 'Sunset Views', 'People Watching'],
    foodStyles: ['Moroccan', 'Cafe'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'friends', 'couple'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '21:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 600,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 1200,
    theforkRating: 4.1,
    theforkReviewCount: 1200,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 600,

    paymentMethods: ['cash-only'],
    reservationMethod: ['walk-in-only'],
    reservationContact: 'None',
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Sindibad+Chefchaouen',
    bestDishes: ['Mint Tea', 'Harira Soup', 'Simple Kefta Panini'],
    tip: 'Sit on the upper panoramic deck for some of the best sunset photo angles over the blue rooftops.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 0,
    seatingTypes: ['indoor', 'rooftop'],
    viewType: 'mountain',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'chefchaouen-eat-17',
    city: 'chefchaouen',
    name: 'Lecheria Venezia',
    neighborhood: 'Medina',
    description: 'Tiny, four-chair medina gem serving Chefchaouen\'s best and most affordable traditional Moroccan breakfast platters and fresh msemen.',
    pricePerPerson: 3.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'brunch'],
    experienceTypes: ['Cafe', 'Traditional Breakfast Ritual'],
    foodStyles: ['Moroccan', 'Cafe', 'Bakery'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    crowdLevel: 'quiet',
    groupTypes: ['solo', 'friends', 'couple'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '07:00',
    closeTime: '18:00',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 200,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 400,
    theforkRating: 4.7,
    theforkReviewCount: 400,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 200,

    paymentMethods: ['cash-only'],
    reservationMethod: ['walk-in-only'],
    reservationContact: 'None',
    googleMapsUrl: 'https://maps.google.com/?q=Lecheria+Venezia+Chefchaouen',
    bestDishes: ['Moroccan Breakfast Platter', 'Msemen with Honey', 'Avocado Toast'],
    tip: 'Their rich, local almond-honey amlou spread is absolutely outstanding; don\'t leave without trying it.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'chefchaouen-eat-18',
    city: 'chefchaouen',
    name: 'Restaurant Hamsa',
    neighborhood: 'Medina',
    description: 'Trendy, hipster-friendly rooftop cafe serving fresh organic salads, healthy bowls, craft specialty coffee, and modern Mediterranean bites.',
    pricePerPerson: 8,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'afternoon-tea'],
    experienceTypes: ['Cafe', 'Sunset Views', 'Modern Fusion Dining'],
    foodStyles: ['Mediterranean', 'Healthy', 'Cafe'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'friends', 'couple'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '09:00',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 300,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 600,
    theforkRating: 4.5,
    theforkReviewCount: 600,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 300,

    paymentMethods: ['cash-only', 'credit-cards'],
    reservationMethod: ['phone', 'instagram'],
    reservationContact: '+212539988990',
    googleMapsUrl: 'https://maps.google.com/?q=Hamsa+Chefchaouen',
    bestDishes: ['Healthy Quinoa Salad', 'Beetroot Hummus', 'Specialty Flat White'],
    tip: 'It\'s the absolute premier spot in Chefchaouen\'s medina for getting a proper flat white or single-origin pour-over.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'rooftop'],
    viewType: 'mountain',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'chefchaouen-eat-19',
    city: 'chefchaouen',
    name: 'Restaurant Paloma',
    neighborhood: 'Medina',
    description: 'Peaceful, beautifully decorated town house townhouse serving delicate Fassi pastillas, slow-cooked tagines, and highly rated mint tea.',
    pricePerPerson: 7.5,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:00',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 250,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 500,
    theforkRating: 4.3,
    theforkReviewCount: 500,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 250,

    paymentMethods: ['cash-only'],
    reservationMethod: ['phone', 'walk-in-only'],
    reservationContact: '+212610987654',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Paloma+Chefchaouen',
    bestDishes: ['Lemon Chicken Tagine', 'Beef Pastilla', 'Moroccan Salads'],
    tip: 'Sit on the small rooftop terrace for a peaceful dining experience away from Medina crowds.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'rooftop'],
    viewType: 'city',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'chefchaouen-eat-20',
    city: 'chefchaouen',
    name: 'Fornaccio',
    neighborhood: 'Medina Edge',
    description: 'Friendly pizzeria and international grill located outside the Medina walls, offering reliable, quick service and fresh ingredients.',
    pricePerPerson: 7,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Casual Italian Dining', 'Family Friendly'],
    foodStyles: ['Italian', 'Pizza', 'International'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    crowdLevel: 'balanced',
    groupTypes: ['family', 'kids-friendly', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: false,
    hasDelivery: false,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: false,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 300,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 600,
    theforkRating: 4.2,
    theforkReviewCount: 600,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 300,

    paymentMethods: ['cash-only', 'credit-cards'],
    reservationMethod: ['phone'],
    reservationContact: '+212539987150',
    googleMapsUrl: 'https://maps.google.com/?q=Fornaccio+Chefchaouen',
    bestDishes: ['Four-Cheese Pizza', 'Chicken Milanese', 'Fresh Fruit Smoothie'],
    tip: 'A highly convenient spot if you are staying in the newer part of town or parked nearby.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: true
  }
];