import type { EatListing } from '../types';

export const el_jadidaEat: EatListing[] = [
  {
    id: 'e-el_jadida-la-portugaise',
    city: 'el_jadida',
    name: 'Restaurant La Portugaise',
    neighborhood: 'Cité Portugaise',
    description: 'A charming, authentic seafood and Moroccan eatery nestled inside the historic ramparts of the Portuguese City (Mazagan). Famous for freshly caught sea bass, sizzling grilled sardine platters, rich seafood pastillas, and warm local hospitality.',
    pricePerPerson: 16,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Historical Ambience', 'Seafood Feast', 'Local Gathering Spot'],
    foodStyles: ['Seafood', 'Moroccan', 'Mediterranean'],
    crowdLevel: 'bustling',
    groupTypes: ['couple', 'family', 'friends', 'solo'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '22:30',
    badge: 'local-favorite',
    googleRating: 4.8,
    googleReviewCount: 1399,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 420,
    restaurantguruRating: 4.9,
    restaurantguruReviewCount: 1399,
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+La+Portugaise+El+Jadida',
    bestDishes: ['Seafood Pastilla', 'Grilled Sea Bass', 'Tajine de Poisson du Jour'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Book ahead or arrive right at 12:30 for lunch as tables inside the historic stone interior fill up quickly.',
    bestTimeToVisit: 'Lunch around 13:00 after exploring the Manueline Cistern',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  },
  {
    id: 'e-el_jadida-le-lokal',
    city: 'el_jadida',
    name: 'Le Lokal',
    neighborhood: 'Cité Portugaise',
    description: 'A vibrant cultural café and rooftop restaurant perched atop the ancient ramparts of Mazagan. Serving homemade Moroccan dishes, artisan pastries, fresh fruit smoothies, and specialty coffees alongside panoramic views of the Atlantic Ocean and port.',
    pricePerPerson: 14,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'brunch', 'lunch', 'dinner'],
    experienceTypes: ['Rooftop Dining', 'Sunset Views', 'Cultural Cafe'],
    foodStyles: ['Moroccan', 'Cafe', 'Healthy'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'solo'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '09:00',
    closeTime: '22:00',
    badge: 'hidden-gem',
    googleRating: 4.7,
    googleReviewCount: 520,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 210,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 520,
    googleMapsUrl: 'https://maps.google.com/?q=Le+Lokal+El+Jadida',
    bestDishes: ['Berber Omelette Breakfast', 'Homemade Moroccan Lemon Cake', 'Avocado Seafood Salad'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Head up to the top rooftop terrace around 18:30 for one of the finest sunset ocean views in El Jadida.',
    bestTimeToVisit: 'Late afternoon coffee and cake at 17:30 before sunset',
    averageWaitMinutes: 5,
    seatingTypes: ['terrace', 'rooftop'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-el_jadida-la-capitainerie',
    city: 'el_jadida',
    name: 'La Capitainerie',
    neighborhood: 'Cité Portugaise',
    description: 'An atmospheric fine-dining seafood restaurant set inside a historic 16th-century Portuguese fortress building. Renowned for upscale French-Moroccan culinary creations, whole grilled turbot, spider crab, and elegant candlelit dining.',
    pricePerPerson: 28,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Historical Ambience', 'Upscale Romantic Dining'],
    foodStyles: ['French', 'Seafood', 'Moroccan'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'business-friendly', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '12:30',
    closeTime: '23:00',
    badge: 'splurge',
    googleRating: 4.6,
    googleReviewCount: 310,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 180,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 310,
    googleMapsUrl: 'https://maps.google.com/?q=La+Capitainerie+El+Jadida',
    bestDishes: ['Grilled Spider Crab', 'Filet de Saint-Pierre', 'Seafood Soup Royal'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Ideal for romantic dinners; reserve a table in advance for weekend evenings.',
    bestTimeToVisit: 'Dinner around 20:00 for a romantic atmosphere',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'city',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-el_jadida-cafe-do-mar',
    city: 'el_jadida',
    name: 'Café do Mar',
    neighborhood: 'Cité Portugaise Ramparts',
    description: 'A relaxed oceanfront bistro perched right on the fortified sea wall. Offers fresh calamari, grilled gambas, Italian pastas, and chilled juices while Atlantic waves crash against the ramparts below.',
    pricePerPerson: 18,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'snack'],
    experienceTypes: ['Waterfront Dining', 'Sunset Views', 'People Watching'],
    foodStyles: ['Mediterranean', 'Seafood', 'Italian'],
    crowdLevel: 'bustling',
    groupTypes: ['couple', 'friends', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '10:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    googleRating: 4.5,
    googleReviewCount: 480,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 290,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 480,
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+do+Mar+El+Jadida',
    bestDishes: ['Fried Calamari Platter', 'Seafood Spaghetti', 'Fresh Mango Juice'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Sit at the outer balcony edge for dramatic Atlantic wave views.',
    bestTimeToVisit: 'Sunset around 18:30',
    averageWaitMinutes: 10,
    seatingTypes: ['terrace', 'rooftop'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-el_jadida-puccini',
    city: 'el_jadida',
    name: 'Puccini El Jadida',
    neighborhood: 'Centre-Ville',
    description: 'A stylish, family-friendly Italian restaurant and pizzeria in downtown El Jadida. Celebrated for authentic wood-fired Neapolitan pizzas, creamy truffle pastas, fresh risottos, and artisan gelato desserts.',
    pricePerPerson: 15,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Wood-Fired Pizza', 'Family Friendly', 'Casual Italian Dining'],
    foodStyles: ['Italian', 'Pizza', 'European'],
    crowdLevel: 'bustling',
    groupTypes: ['family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '23:30',
    badge: 'local-favorite',
    googleRating: 4.8,
    googleReviewCount: 288,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 110,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 288,
    googleMapsUrl: 'https://maps.google.com/?q=Puccini+El+Jadida',
    bestDishes: ['Pizza Puccini Four Cheese', 'Truffle Tagliatelle', 'Tiramisu House Special'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Great spot for families with children looking for high-quality Italian food after a beach day.',
    bestTimeToVisit: 'Dinner at 20:00 for a lively family atmosphere',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-el_jadida-snack-aymane-marina',
    city: 'el_jadida',
    name: 'Snack Aymane Marina',
    neighborhood: 'Fishing Harbor & Beach Promenade',
    description: 'A famous budget-friendly seafood joint near the fishing port where locals go for generous, ultra-fresh fried and grilled fish platters accompanied by zaalouk, fries, and spicy harissa sauce.',
    pricePerPerson: 8,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fishing Harbor Dining', 'Gourmet Seafood', 'Casual Dining'],
    foodStyles: ['Seafood', 'Moroccan', 'Fast Food'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends', 'family'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: false,
    isHalal: true,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '11:30',
    closeTime: '23:00',
    badge: 'local',
    googleRating: 4.8,
    googleReviewCount: 400,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 95,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 400,
    googleMapsUrl: 'https://maps.google.com/?q=Snack+Aymane+Marina+El+Jadida',
    bestDishes: ['Mixed Seafood Grill Platter', 'Fried Sole & Whiting', 'Moroccan Tomato Salad'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Order the mixed seafood plate for two—generous portions at unbeatable local market prices.',
    bestTimeToVisit: 'Lunch around 13:30 right after fish boats land',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: true
  }
];
