import type { EatListing } from '../types';

/**
 * EAT LISTING TEMPLATE
 * {
 *   id: 'e-[city]-[name]',
 *   city: '[city]',
 *   name: '[Name]',
 *   neighborhood: '[Neighborhood]',
 *   description: '[Long description]',
 *   pricePerPerson: [number],
 *   lifestyle: 'lean' | 'balanced' | 'premium',
 *   mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'latenight', 'afternoon-tea', 'flexible'],
 *   experienceTypes: ['Fine Dining' | 'Waterfront Dining' | 'Romantic Sunset' | 'Beachfront Dining' | 'Garden restaurant with live music' | 'Fountain courtyard' | 'French-Moroccan fusion' | 'Casual Italian Dining' | 'Family Pizza Night' | 'Spanish Beach Lounge' | 'Paella & Tapas' | 'Live Music Terrace' | 'Upscale Romantic Dining' | 'Fine Seafood' | 'Classic Royal Ambiance' | '24/7 Brasserie' | 'People Watching' | 'Bakery-Patisserie' | 'Traditional Breakfast Ritual' | 'Local Gathering Spot' | 'Fishing Harbor Dining' | 'Gourmet Seafood' | 'French-Italian Fusion' | 'Authentic Berber Feast' | 'Traditional Dining' | 'Cozy casual family-run Moroccan eatery' | 'Amazigh-inspired decor' | 'Beachfront Grill' | 'Casual Dining' | 'Sunset Views' | 'Wood-Fired Pizza' | 'Family Friendly' | 'Leafy Tennis Oasis' | 'Tranquil Dining' | 'Upscale Lounge' | 'Modern Fusion Dining' | 'Unverified'],
 *   foodStyles: ['French' | 'Moroccan' | 'Seafood' | 'Mediterranean' | 'European' | 'International' | 'Italian' | 'Pizza' | 'Spanish' | 'Berber' | 'Barbecue' | 'Middle Eastern' | 'Healthy' | 'Cafe' | 'Bakery' | 'Patisserie' | 'Gourmet' | 'Fast Food'],
 *   crowdLevel: 'bustling' | 'balanced' | 'quiet',
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *   hasEnglishStaff: true | false,
 *   hasFrenchStaff: true | false,
 *   hasDelivery: true | false,
 *   hasParking: true | false,
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearCenter: true | false,
 *   isVegetarianFriendly: true | false,
 *   isHalal: true | false,
 *   openTime: 'HH:mm',
 *   closeTime: 'HH:mm',
 *   badge: 'local-favorite' | 'splurge' | 'hidden-gem' | 'local',
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source
 *   // ═══════════════════════════════════════════════════
 *   // Search for real ratings from Google, TripAdvisor, TheFork, and RestaurantGuru.
 *   // If you cannot find a rating for a specific source, set it to the same value as
 *   // the closest available one so the code that calculates average ratings doesn't break.
 *   // Example: if no TripAdvisor rating found, set tripadvisorRating = googleRating
 *
 *   // Google Places rating
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *
 *   // TripAdvisor rating
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *
 *   // TheFork rating
 *   theforkRating: [4.x],
 *   theforkReviewCount: [number],
 *
 *   // RestaurantGuru rating
 *   restaurantguruRating: [4.x],
 *   restaurantguruReviewCount: [number],
 *
 *   // REMOVED: rating, reviewCount, ratingSource (old single-source fields)
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   fullMenu: { type: 'image' | 'text', content: 'https://...' },
 *   tip: '[Short tip]',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   reservationContact: '+212XXXXXXXXX',
 *   bestDishes: ['Dish 1', 'Dish 2'],
 *   alcoholPolicy: 'serves-alcohol' | 'dry',
 *   ramadanFriendly: 'serves-lunch' | 'special-ftour' | 'closed',
 *
 *   // ═══════════════════════════════════════════════════
 *   // NEW FIELDS — psychological UX optimization
 *   // ═══════════════════════════════════════════════════
 *
 *   bestTimeToVisit: 'Early evening around 18:30 for sunset' | 'Lunch around 13:00 for quiet' | 'Late evening after 20:00 for lively crowd' | 'Early morning for fresh baked goods' | 'Sunday morning for brunch peak',
 *   averageWaitMinutes: 0 | 5 | 10 | 15 | 20 | 30 | 45 | 60,
 *   seatingTypes: ['indoor'] | ['terrace'] | ['rooftop'] | ['garden'] | ['beachfront'] | ['indoor', 'terrace'] | ['indoor', 'garden'] | ['terrace', 'rooftop'],
 *   viewType: 'beach' | 'mountain' | 'city' | 'garden' | 'none',
 *   wiFi: true | false,
 *   airConditioning: true | false,
 *   wheelchairAccessible: true | false,
 *   website: 'https://...',
 *   instagram: '@handle' | 'https://instagram.com/...'
 * }
 */

export const essaouiraEat: EatListing[] = [
  {
    id: 'e-essaouira-1',
    city: 'essaouira',
    name: 'La Table by Madada',
    neighborhood: 'Medina Entrance',
    description: 'An exceptional fine-dining restaurant housed under magnificent historic stone arches near the port. Renowned for its refined Moroccan seafood gastronomy, including lobster couscous and spider crab gratin.',
    pricePerPerson: 25,
    lifestyle: 'premium',
    mealTypes: ['dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Fine Seafood'],
    foodStyles: ['Seafood', 'Moroccan', 'French'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'seniors', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '19:00',
    closeTime: '23:00',
    badge: 'splurge',
    googlePlaceId: "ChIJW5p532Pyrw0R_85bW0_NfGA",
    images: [
      "https://images.unsplash.com/photo-1541518763669-27fef04b14e8?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?auto=format&fit=crop&w=800&q=80"
    ],

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 1459,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 1459,
    theforkRating: 4.6,
    theforkReviewCount: 1459,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 1459,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212524472106',
    googleMapsUrl: 'https://maps.google.com/?q=La+Table+by+Madada+Essaouira',
    bestDishes: ['Spider Crab Gratin', 'Sea Bass in Salt Crust', 'Lobster Couscous'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Be sure to reserve days in advance. The spider crab gratin and sea bass in salt crust are magnificent culinary showpieces.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 0,
    seatingTypes: ['indoor'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'e-essaouira-2',
    city: 'essaouira',
    name: 'Salut Maroc Rooftop',
    neighborhood: 'Medina',
    description: 'A vibrant, extraordinarily colorful boutique hotel rooftop overlooking the Atlantic and historic ramparts. Serves creative Moroccan fusion dishes, seafood tagines, and custom mocktails with sunset live music.',
    pricePerPerson: 22,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner', 'brunch'],
    experienceTypes: ['Sunset Views', 'Scenic Views', 'Romantic Sunset'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Seafood'],
    crowdLevel: 'bustling',
    groupTypes: ['couple', 'friends', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:30',
    badge: 'local-favorite',
    googlePlaceId: "ChIJJ28R12Pyrw0ROg4qX60_NfGA",
    images: [
      "https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?auto=format&fit=crop&w=800&q=80"
    ],

    // ── RATINGS ──
    googleRating: 3.6,
    googleReviewCount: 260,
    tripadvisorRating: 3.6,
    tripadvisorReviewCount: 260,
    theforkRating: 3.6,
    theforkReviewCount: 260,
    restaurantguruRating: 3.6,
    restaurantguruReviewCount: 260,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212524475512',
    googleMapsUrl: 'https://maps.google.com/?q=Salut+Maroc+Essaouira',
    bestDishes: ['Seafood Pastilla', 'Slow-Cooked Lamb Tagine', 'Octopus Carpaccio'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Ideal for sunset drinks. They often have a live DJ or acoustic musicians playing while the sun dips below the ramparts.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'rooftop', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-essaouira-3',
    city: 'essaouira',
    name: 'Mega Loft',
    neighborhood: 'Medina',
    description: 'An eclectic, multi-level restaurant and music lounge decorated with retro Moroccan furniture and pop-art. Offers a spectacular rooftop and a menu full of inventive fusion tagines, fish burgers, and live Gnawa sets.',
    pricePerPerson: 16,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Modern Fusion Dining', 'Sunset Views', 'Live Music Terrace'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Seafood'],
    crowdLevel: 'bustling',
    groupTypes: ['friends', 'couple', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 1437,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 474,
    theforkRating: 4.1,
    theforkReviewCount: 1437,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 1437,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Mega+Loft+Essaouira',
    bestDishes: ['Fig and Goat Cheese Tagine', 'Essaouira Fish Burger', 'Spiced Pumpkin Hummus'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Make sure to visit on evenings when live Gnawa fusion musicians play in the central atrium.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor', 'rooftop'],
    viewType: 'city',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-essaouira-4',
    city: 'essaouira',
    name: 'Dar Baba',
    neighborhood: 'Medina',
    description: 'A beautifully designed Mediterranean restaurant and tapas lounge inside a 19th-century Medina mansion. Features retro velvet seats, amazing signature cocktails, and vibrant contemporary Mediterranean dishes.',
    pricePerPerson: 22,
    lifestyle: 'premium',
    mealTypes: ['dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Upscale Lounge'],
    foodStyles: ['Mediterranean', 'Italian', 'Seafood'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'solo'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: false,
    openTime: '18:00',
    closeTime: '01:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 650,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 650,
    theforkRating: 4.7,
    theforkReviewCount: 650,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 650,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['online', 'phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Dar+Baba+Essaouira',
    bestDishes: ['Octopus and Orzo', 'Truffle Ravioli', 'Beef Carpaccio'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Try their signature Argan Sour cocktail alongside their slow-roasted octopus or fresh truffle gnocchi.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'e-essaouira-5',
    city: 'essaouira',
    name: 'Ocean Vagabond',
    neighborhood: 'Essaouira Beach',
    description: 'An incredibly popular beachfront restaurant, surf club, and café tucked under palm trees on the main bay. Famous for its relaxed, sandy-toes atmosphere, ocean views, wood-fired pizzas, and salads.',
    pricePerPerson: 13,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch'],
    experienceTypes: ['Waterfront Dining', 'Beachfront Grill', 'Casual Dining'],
    foodStyles: ['Mediterranean', 'Seafood', 'International'],
    crowdLevel: 'bustling',
    groupTypes: ['family', 'friends', 'couple', 'kids-friendly', 'solo'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '09:00',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 1704,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 1156,
    theforkRating: 4.3,
    theforkReviewCount: 2648,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 2648,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Ocean+Vagabond+Essaouira',
    bestDishes: ['Wood-Fired Pizza Regina', 'Crispy Calamari', 'Fresh fruit smoothies'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'The best spot on the beach to watch kitesurfers over lunch. Very child-friendly with dromedaries passing by.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor', 'beachfront', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  },

  {
    id: 'e-essaouira-6',
    city: 'essaouira',
    name: 'Le Chalet de la Plage',
    neighborhood: 'Essaouira Beach',
    description: 'A historic beachfront restaurant operating since the 1960s. Known for its old-world marine decor, extensive terrace overlooking the ocean, fresh local oysters, and classic French-Moroccan seafood platters.',
    pricePerPerson: 28,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Waterfront Dining', 'Fine Seafood'],
    foodStyles: ['Seafood', 'French', 'Mediterranean'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'seniors', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 1050,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 1050,
    theforkRating: 4.1,
    theforkReviewCount: 1050,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 1050,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Le+Chalet+de+la+Plage+Essaouira',
    bestDishes: ['Oualidia Oysters', 'Sardine Tagine', 'Grilled Lobster Platter'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Order the fresh oysters from nearby Oualidia and the grilled sea bream with butter sauce. Ideal for sunset dining.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'e-essaouira-7',
    city: 'essaouira',
    name: 'Chez Sam',
    neighborhood: 'Essaouira Port',
    description: 'A local legend positioned at the very end of the fishing port. Built like a rustic, cozy wooden ship, it serves exceptionally fresh daily catches directly overlooking the harbor and Mogador Island.',
    pricePerPerson: 18,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fishing Harbor Dining', 'Casual Dining', 'Scenic Views'],
    foodStyles: ['Seafood', 'Mediterranean'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 3.7,
    googleReviewCount: 711,
    tripadvisorRating: 3.7,
    tripadvisorReviewCount: 711,
    theforkRating: 3.7,
    theforkReviewCount: 711,
    restaurantguruRating: 3.7,
    restaurantguruReviewCount: 711,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Chez+Sam+Essaouira',
    bestDishes: ['Grilled Sardines', 'Fish Soup', 'Mixed Seafood Platter'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Walk right to the end of the harbor past the shipyard to find this gem. The service is friendly, and the fish is as fresh as it gets.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'beach',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-essaouira-8',
    city: 'essaouira',
    name: 'Chez Fatima',
    neighborhood: 'Medina',
    description: 'A warm, family-run traditional diner hidden in the medina alleyways. Fatima prepares incredible home-cooked beef and plum tagines and incredible Friday couscous with motherly care.',
    pricePerPerson: 6.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:00',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 220,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 220,
    theforkRating: 4.7,
    theforkReviewCount: 220,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 220,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Chez+Fatima+Essaouira',
    bestDishes: ['Lemon Chicken Tagine', 'Beef Pastilla', 'Friday Couscous'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Fatima prepares everything fresh. Ask for her legendary tagine of local sea fish or the beef pastilla.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-essaouira-9',
    city: 'essaouira',
    name: 'Il Mare',
    neighborhood: 'Medina',
    description: 'An iconic multi-level bar and dining venue facing the ancient ramparts of Essaouira. Features panoramic views of the stormy Atlantic waves, specializing in fresh Oualidia oysters and fish.',
    pricePerPerson: 21,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Fine Seafood', 'Romantic Sunset', 'Sunset Views'],
    foodStyles: ['Seafood', 'Mediterranean', 'French'],
    crowdLevel: 'bustling',
    groupTypes: ['couple', 'friends', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '01:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 780,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 780,
    theforkRating: 4.1,
    theforkReviewCount: 780,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 780,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Il+Mare+Essaouira',
    bestDishes: ['Raw Oysters with Lemon', 'Grilled Sea Bream Filet', 'Seafood Pasta'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Climb to the top terrace for sunset. Sip on local wine or mint tea with raw oysters while listening to live acoustic sets.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor', 'rooftop', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-essaouira-10',
    city: 'essaouira',
    name: 'The Port Fish Grills (Stall #11)',
    neighborhood: 'Essaouira Port',
    description: 'The quintessential Essaouira street food experience. Sit at rough-and-ready outdoor benches right at the harbor entrance to select your fresh raw fish and have it grilled immediately on open coals.',
    pricePerPerson: 9,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Fishing Harbor Dining', 'Casual Dining', 'Local Gathering Spot'],
    foodStyles: ['Seafood'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends', 'family', 'couple'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: false,
    isHalal: true,
    openTime: '11:00',
    closeTime: '21:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.0,
    googleReviewCount: 1500,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 1500,
    theforkRating: 4.0,
    theforkReviewCount: 1500,
    restaurantguruRating: 4.0,
    restaurantguruReviewCount: 1500,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Port+Grills+Essaouira',
    bestDishes: ['Coal-Grilled Sardines', 'Grilled Prawns', 'Squid Skewers'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'Negotiate your plate price before sitting down. Always ask to include local sardines, giant prawns, and squid in your mix.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['beachfront'],
    viewType: 'beach',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: true
  },

  {
    id: 'e-essaouira-11',
    city: 'essaouira',
    name: 'Caravane Café',
    neighborhood: 'Medina',
    description: 'An extraordinary fusion of art gallery, cocktail lounge, and dining room set in a beautiful riad. Hand-curated by artist Didier Spindler, offering live fire dancers, Gnawa shows, and world-class French-Moroccan cuisine.',
    pricePerPerson: 26,
    lifestyle: 'premium',
    mealTypes: ['dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Modern Fusion Dining'],
    foodStyles: ['French', 'Mediterranean', 'Moroccan'],
    crowdLevel: 'bustling',
    groupTypes: ['couple', 'friends', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '18:00',
    closeTime: '23:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 1100,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 1100,
    theforkRating: 4.5,
    theforkReviewCount: 1100,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 1100,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212808655441',
    googleMapsUrl: 'https://maps.google.com/?q=Caravane+Cafe+Essaouira',
    bestDishes: ['Caramelized Lamb Shank', 'Garlic Honey Prawns', 'Gratinated Crab Shell'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Book ahead for a table in the courtyard to enjoy the magic tricks, fire dancers, and live Gnawa fusion musicians who move between dining salons.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'e-essaouira-12',
    city: 'essaouira',
    name: 'La Licorne',
    neighborhood: 'Medina',
    description: 'An upscale, atmospheric traditional restaurant tucked under majestic high stone arches in the old medina. Renowned for its superb Moroccan royal couscous, savory fish pastillas, and quiet sophistication.',
    pricePerPerson: 22,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Traditional Dining'],
    foodStyles: ['Moroccan', 'Seafood'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'seniors', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 450,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 450,
    theforkRating: 4.4,
    theforkReviewCount: 450,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 450,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=La+Licorne+Essaouira',
    bestDishes: ['Royal Couscous', 'Fish Pastilla', 'Lamb Tagine with Pears & Almonds'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'The lamb tagine with almonds and pears is a remarkable dish that slow-cooks for hours.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'e-essaouira-13',
    city: 'essaouira',
    name: 'Taros',
    neighborhood: 'Place Moulay Hassan',
    description: 'A massive, multi-level open rooftop terrace right on the central Place Moulay Hassan. Highly popular for late afternoon drinks, harbor views, simple burgers, and standard Moroccan tagines.',
    pricePerPerson: 16,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'latenight', 'flexible'],
    experienceTypes: ['Sunset Views', 'Scenic Views', 'Casual Dining'],
    foodStyles: ['Mediterranean', 'Moroccan', 'Seafood'],
    crowdLevel: 'bustling',
    groupTypes: ['friends', 'couple', 'large-groups'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:00',
    closeTime: '02:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 3.9,
    googleReviewCount: 2200,
    tripadvisorRating: 3.9,
    tripadvisorReviewCount: 2200,
    theforkRating: 3.9,
    theforkReviewCount: 2200,
    restaurantguruRating: 3.9,
    restaurantguruReviewCount: 2200,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Taros+Essaouira',
    bestDishes: ['Essaouira Fish Burger', 'Fritto Misto (Fried Fish Mix)', 'Classic Tagine'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'The food is basic, but the rooftop cocktail terrace is unmatched for location. Grab a drink and enjoy the sunset wind over the port.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['rooftop', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-essaouira-14',
    city: 'essaouira',
    name: 'Trattoria Silvestro',
    neighborhood: 'Medina',
    description: 'A long-running, exceptionally authentic Italian trattoria in the heart of the Medina. Known for offering wood-fired pizzas, house-made ravioli, and fresh local seafood-based pastas.',
    pricePerPerson: 12,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Italian Dining', 'Family Pizza Night', 'Romantic Sunset'],
    foodStyles: ['Italian', 'Seafood', 'Mediterranean'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: false,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 950,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 950,
    theforkRating: 4.4,
    theforkReviewCount: 950,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 950,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Trattoria+Silvestro+Essaouira',
    bestDishes: ['Seafood Linguine', 'Pizza Diavola', 'House Tiramisu'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'If you need a break from traditional tagines, this is the best spot in the city for a perfect wood-fired pizza or seafood spaghetti.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'e-essaouira-15',
    city: 'essaouira',
    name: 'Munchies',
    neighborhood: 'Medina',
    description: 'A popular, modern hole-in-the-wall spot in the Medina offering top-notch fast casual street food. Celebrated for high-quality smash burgers, crispy chicken tenders, and gourmet wraps.',
    pricePerPerson: 7.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Casual Dining', 'Quick Bites'],
    foodStyles: ['Mediterranean', 'Fast Food'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '00:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 380,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 380,
    theforkRating: 4.6,
    theforkReviewCount: 380,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 380,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Munchies+Essaouira',
    bestDishes: ['Gourmet Smash Burger', 'Crispy Chicken Wrap', 'Truffle Fries'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Perfect for a quick, delicious Western-style meal. Their homemade fries and spicy garlic sauce are brilliant.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  },

  {
    id: 'e-essaouira-16',
    city: 'essaouira',
    name: 'Chaabi Chic',
    neighborhood: 'Medina',
    description: 'A bright, charming little café inside the Medina offering a lovely aesthetic twist on traditional Moroccan fast casual. Focuses on healthy organic salads, light tagines, and custom fruit juices.',
    pricePerPerson: 8.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'afternoon-tea'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Traditional Dining'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Healthy'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'friends', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '09:00',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 510,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 510,
    theforkRating: 4.5,
    theforkReviewCount: 510,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 510,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Chaabi+Chic+Essaouira',
    bestDishes: ['Vegetarian Tagine', 'Chaabi Orange Juice', 'Chicken pastilla'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Sit by the window to watch the busy medina shoppers below. Excellent vegetarian couscous and ginger juices.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'city',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-essaouira-17',
    city: 'essaouira',
    name: 'Le Corail Vegan Food',
    neighborhood: 'Medina',
    description: 'The absolute pioneer of purely vegan and vegetarian dining in Essaouira. Offers beautifully plated plant-based tagines, fresh-pressed organic power juices, and tasty raw vegan pastries.',
    pricePerPerson: 9,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Traditional Dining'],
    foodStyles: ['Healthy', 'Moroccan', 'Mediterranean'],
    crowdLevel: 'quiet',
    groupTypes: ['solo', 'couple', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '21:30',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 280,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 280,
    theforkRating: 4.7,
    theforkReviewCount: 280,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 280,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Le+Corail+Vegan+Food+Essaouira',
    bestDishes: ['Vegan Cheese Tagine', 'Organic Energy Juice', 'Gluten-Free Chocolate Cake'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'An exceptionally friendly spot run by a dedicated local couple. The vegan almond cheese tagine is a unique culinary triumph.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-essaouira-18',
    city: 'essaouira',
    name: 'The Loft',
    neighborhood: 'Medina',
    description: 'A modern, stylishly intimate restaurant featuring gorgeous warm wood paneled walls and eclectic vintage details. Specializes in incredibly refined French-Moroccan seafood and meats.',
    pricePerPerson: 18,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Modern Fusion Dining'],
    foodStyles: ['Seafood', 'French', 'Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 880,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 880,
    theforkRating: 4.6,
    theforkReviewCount: 880,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 880,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=The+Loft+Essaouira',
    bestDishes: ['Saffron Seafood Filet', 'Gourmet Lamb Shoulder', 'Warm Apple Tarte Tatin'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'An intimate room, so booking is highly advised. The fish filet with saffron sauce is outstanding.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'e-essaouira-19',
    city: 'essaouira',
    name: 'La Clef de Voûte',
    neighborhood: 'Medina',
    description: 'A stunningly cozy hidden gem with exposed stone walls in a quiet medina side-alley. Offers exceptionally creative French-Moroccan fusion dishes, fresh fish, and warm hospitality.',
    pricePerPerson: 16,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Traditional Dining'],
    foodStyles: ['French', 'Moroccan', 'Mediterranean'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'solo'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:30',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.8,
    googleReviewCount: 420,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 420,
    theforkRating: 4.8,
    theforkReviewCount: 420,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 420,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=La+Clef+de+Voute+Essaouira',
    bestDishes: ['Grilled John Dory', 'Slow-cooked Plum Lamb', 'Signature Chocolate Fondant'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Their chocolate fondant is praised by travelers as the finest in Morocco. A beautiful, romantic escape.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-essaouira-20',
    city: 'essaouira',
    name: 'One Love Cafe',
    neighborhood: 'Essaouira Dunes',
    description: 'A colorful surf-inspired café with a relaxed Rastafarian vibe located near the beach. Offers delicious organic acai bowls, vegan breakfast selections, and great smoothies for active travelers.',
    pricePerPerson: 8,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'brunch', 'afternoon-tea'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Beachfront Grill'],
    foodStyles: ['Healthy', 'Mediterranean', 'Cafe'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'friends', 'couple', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:30',
    closeTime: '20:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 310,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 310,
    theforkRating: 4.5,
    theforkReviewCount: 310,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 310,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=One+Love+Cafe+Essaouira',
    bestDishes: ['Acai Berry Bowl', 'Surfers Vegan Breakfast', 'Avocado Shake'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'The ideal chill-out spot after camel riding or quad biking along the dunes. Great positive vibes.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  }
];