import type { EatListing } from '../types';

/**
 * EAT LISTING TEMPLATE — Ifrane & Azrou
 */

export const ifrane_azrouEat: EatListing[] = [
  {
    id: 'e-ifrane-la-paix',
    city: 'ifrane_azrou',
    name: 'Café Restaurant La Paix',
    neighborhood: 'Ifrane Town Center',
    description: 'The iconic hearth of Ifrane town center located steps from the famous Stone Lion monument. Featuring a heated Alpine-style glass terrace, serving traditional Moroccan tagines, French onion soup, wood-fired pizzas, and rich pastries in a cozy chalet environment.',
    pricePerPerson: 18,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'brunch', 'lunch', 'dinner'],
    experienceTypes: ['People Watching', 'Traditional Dining', 'Family Friendly'],
    foodStyles: ['Moroccan', 'French', 'International', 'Cafe'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international', 'cafe-pastry'],
    crowdLevel: 'bustling',
    groupTypes: ['family', 'friends', 'couple', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '07:30',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.8,
    googleReviewCount: 3223,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 410,
    theforkRating: 4.4,
    theforkReviewCount: 85,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 3223,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'none'],
    reservationContact: '+212535566023',
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Restaurant+La+Paix+Ifrane',
    bestDishes: ['Lamb Tagine with Prunes', 'French Onion Soup', 'Hot Chocolate & Croissants'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Sit on the outdoor heated terrace during autumn and winter for prime people watching near the central gardens.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Lunch around 13:00 or late afternoon tea at 16:30',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dinner", "dry", "pastry", "tagine", "terrace", "wifi"]
  },

  {
    id: 'e-ifrane-my-lil-rome',
    city: 'ifrane_azrou',
    name: 'My Lil Rome',
    neighborhood: 'Ifrane Center',
    description: 'A cozy, highly-rated Italian pizzeria in the heart of Ifrane. Popular among Al Akhawayn University students and visiting families for crisp, wood-fired Neapolitan pizzas, freshly tossed pastas, and authentic espresso.',
    pricePerPerson: 12,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Wood-Fired Pizza', 'Casual Italian Dining'],
    foodStyles: ['Italian', 'Pizza', 'Fast Food'],
    // food-cuisine quiz question tags
    cuisineTags: ['international'],
    crowdLevel: 'bustling',
    groupTypes: ['friends', 'family', 'solo', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '11:30',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.9,
    googleReviewCount: 510,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 120,
    theforkRating: 4.6,
    theforkReviewCount: 35,
    restaurantguruRating: 4.9,
    restaurantguruReviewCount: 510,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'none'],
    reservationContact: '+212535567789',
    googleMapsUrl: 'https://maps.google.com/?q=My+Lil+Rome+Ifrane',
    bestDishes: ['Pizza Margherita Special', 'Pesto Penne', 'Garlic Cheese Bread'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Quick service and top-rated crust—perfect for a comforting dinner after hiking or skiing.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Dinner around 19:30',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["budget", "dinner", "dry", "street-food", "terrace", "wifi"]
  },

  {
    id: 'e-ifrane-foodies',
    city: 'ifrane_azrou',
    name: 'Foodies Ifrane',
    neighborhood: 'Ifrane Ville Nouvelle',
    description: 'A trendy gourmet burger and grill joint serving juicy smash burgers, crispy chicken tenders, loaded fries, and thick milkshakes in a sleek, modern timber cabin interior.',
    pricePerPerson: 10,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Casual Dining', 'Family Friendly'],
    foodStyles: ['Fast Food', 'International'],
    // food-cuisine quiz question tags
    cuisineTags: ['international'],
    crowdLevel: 'bustling',
    groupTypes: ['friends', 'solo', 'kids-friendly', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '00:00',
    badge: 'local',

    // ── RATINGS ──
    googleRating: 4.8,
    googleReviewCount: 1614,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 180,
    theforkRating: 4.5,
    theforkReviewCount: 50,
    restaurantguruRating: 4.9,
    restaurantguruReviewCount: 1614,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    reservationContact: 'None',
    googleMapsUrl: 'https://maps.google.com/?q=Foodies+Ifrane',
    bestDishes: ['Smash Bacon Cheeseburger', 'Crispy Chicken Tender Combo', 'Loaded Truffle Fries'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Great value for students and young travelers seeking fast, quality comfort food.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Lunch at 13:00 or late evening 21:00',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["budget", "dinner", "dry", "late-night", "street-food", "wifi"]
  },

  {
    id: 'e-azrou-cedar-forest-grill',
    city: 'ifrane_azrou',
    name: 'Café Restaurant Cedar Gouraud',
    neighborhood: 'Cedar Forest Azrou',
    description: 'A rustic mountain woodland outdoor eatery located right at the edge of the ancient Cèdre Gouraud forest. Famous for piping-hot Berber claypot tagines cooked over cedar charcoal, mint tea, and fresh flatbreads served amidst Atlas mountain pine air.',
    pricePerPerson: 12,
    lifestyle: 'lean',
    mealTypes: ['lunch'],
    experienceTypes: ['Authentic Berber Feast', 'Tranquil Dining', 'Sunset Views'],
    foodStyles: ['Berber', 'Moroccan', 'Barbecue'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international', 'cafe-pastry'],
    crowdLevel: 'balanced',
    groupTypes: ['family', 'friends', 'solo', 'couple'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '09:00',
    closeTime: '18:00',
    badge: 'hidden-gem',

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 380,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 110,
    theforkRating: 4.2,
    theforkReviewCount: 25,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 350,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    reservationContact: 'None',
    googleMapsUrl: 'https://maps.google.com/?q=Cedar+Gouraud+Azrou',
    bestDishes: ['Berber Lamb Tagine with Vegetables', 'Charcoal Grilled Kefta Brochettes', 'Middle Atlas Wild Thyme Tea'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Eat lunch here after visiting the Barbary Macaques in the surrounding cedar forest.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Lunch around 12:30 after a forest walk',
    averageWaitMinutes: 15,
    seatingTypes: ['terrace', 'garden'],
    viewType: 'garden',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: true
  ,
    tags: ["budget", "cafe-pastry", "dry", "mountain", "sunset", "tagine", "terrace"]
  },

  {
    id: 'e-ifrane-le-cedray',
    city: 'ifrane_azrou',
    name: 'Le Cedray',
    neighborhood: 'Michlifen Resort & Golf',
    description: 'Luxurious alpine chalet fine-dining venue at the 5-star Michlifen Resort, offering elevated French gastronomy, game specialties, and an exceptional wine cellar with panoramic mountain vistas.',
    pricePerPerson: 65,
    lifestyle: 'premium',
    mealTypes: ['dinner'],
    experienceTypes: ['Fine Dining', 'Upscale Romantic Dining', 'Classic Royal Ambiance'],
    foodStyles: ['French', 'Gourmet', 'European'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    alcoholPolicy: 'serves-alcohol',
    servesAlcohol: false,
    ramadanFriendly: 'serves-lunch',
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'business-friendly', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '19:00',
    closeTime: '23:30',
    badge: 'splurge',

    // ── RATINGS ──
    googleRating: 4.8,
    googleReviewCount: 1374,
    tripadvisorRating: 4.9,
    tripadvisorReviewCount: 320,
    theforkRating: 4.8,
    theforkReviewCount: 110,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 1200,

    paymentMethods: ['card'],
    reservationMethod: ['phone'],
    reservationContact: '+212535864000',
    googleMapsUrl: 'https://maps.google.com/?q=Le+Cedray+Michlifen+Ifrane',
    bestDishes: ['Foie Gras Poêlé', 'Middle Atlas Trout Meunière', 'Filet de Boeuf aux Morilles'],
    tip: 'Reservations are required. Dress code is smart elegant, fitting this palatial mountain lodge.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Dinner at 20:00 for a cozy fireside experience',
    averageWaitMinutes: 0,
    seatingTypes: ['indoor'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["alcohol", "dinner", "fine", "mountain", "quiet", "wifi"]
  },

  {
    id: 'e-ifrane-le-chalet',
    city: 'ifrane_azrou',
    name: 'Le Chalet',
    neighborhood: 'Michlifen Resort & Golf',
    description: 'Warm mountain brasserie and sun-drenched terrace overlooking cedar forests, serving hearty alpine classics, fondues, club sandwiches, and gourmet breakfasts.',
    pricePerPerson: 35,
    lifestyle: 'premium',
    mealTypes: ['breakfast', 'brunch', 'lunch'],
    experienceTypes: ['Casual Dining', 'Sunset Views', 'People Watching'],
    foodStyles: ['French', 'European', 'International'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    alcoholPolicy: 'serves-alcohol',
    servesAlcohol: false,
    ramadanFriendly: 'serves-lunch',
    crowdLevel: 'balanced',
    groupTypes: ['family', 'friends', 'couple'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '08:00',
    closeTime: '17:00',
    badge: 'splurge',

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 950,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 240,
    theforkRating: 4.6,
    theforkReviewCount: 60,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 890,

    paymentMethods: ['card', 'cash'],
    reservationMethod: ['phone', 'none'],
    reservationContact: '+212535864000',
    googleMapsUrl: 'https://maps.google.com/?q=Le+Chalet+Michlifen+Ifrane',
    bestDishes: ['Traditional Cheese Fondue', 'Michlifen Club Sandwich', 'Artisanal Hot Chocolate'],
    tip: 'Request a terrace table on clear sunny days for breathtaking views over the snow-capped cedar ridge.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Lunch at 12:30 on the sunlit terrace',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["alcohol", "breakfast", "budget", "fine", "mountain", "street-food", "sunset", "terrace", "wifi"]
  },

  {
    id: 'e-ifrane-l-oriental',
    city: 'ifrane_azrou',
    name: "L'Oriental",
    neighborhood: 'Michlifen Resort & Golf',
    description: 'Regal Moroccan gastronomic sanctuary inside Michlifen Resort celebrating imperial Fassi and Atlas mountain recipes, pigeon pastillas, and fragrant saffron tagines.',
    pricePerPerson: 50,
    lifestyle: 'premium',
    mealTypes: ['dinner'],
    experienceTypes: ['Fine Dining', 'Traditional Dining', 'Classic Royal Ambiance'],
    foodStyles: ['Moroccan', 'Gourmet'],
    alcoholPolicy: 'serves-alcohol',
    servesAlcohol: true,
    ramadanFriendly: 'special-ftour',
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '19:30',
    closeTime: '23:30',
    badge: 'splurge',

    // ── RATINGS ──
    googleRating: 4.8,
    googleReviewCount: 620,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 190,
    theforkRating: 4.7,
    theforkReviewCount: 55,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 580,

    paymentMethods: ['card', 'cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212535864000',
    googleMapsUrl: 'https://maps.google.com/?q=L+Oriental+Michlifen+Ifrane',
    bestDishes: ['Royal Pigeon Pastilla', 'Slow-cooked Atlas Lamb Tagine with Saffron', 'Orange Blossom Pastilla Tart'],
    tip: 'Book ahead during holiday seasons; this is considered the premier traditional Moroccan dinner setting in Ifrane.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Dinner around 20:00 for the full royal ambiance',
    averageWaitMinutes: 0,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["alcohol", "dinner", "fine", "mountain", "pastilla", "quiet", "tagine", "wifi"]
  },

  {
    id: 'e-ifrane-la-ferme',
    city: 'ifrane_azrou',
    name: 'La Ferme Michlifen',
    neighborhood: 'Michlifen Grounds',
    description: 'Pastoral farm-to-table dining experience situated between fragrant kitchen gardens and traditional clay bread ovens, offering organic Berber tagines and outdoor tranquility.',
    pricePerPerson: 30,
    lifestyle: 'premium',
    mealTypes: ['lunch'],
    experienceTypes: ['Garden restaurant with live music', 'Tranquil Dining', 'Family Friendly'],
    foodStyles: ['Moroccan', 'Berber', 'Healthy'],
    // food-cuisine quiz question tags
    cuisineTags: ['international', 'moroccan-traditional'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    crowdLevel: 'quiet',
    groupTypes: ['family', 'kids-friendly', 'couple'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '17:00',
    badge: 'hidden-gem',

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 430,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 140,
    theforkRating: 4.5,
    theforkReviewCount: 40,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 410,

    paymentMethods: ['card', 'cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212535864000',
    googleMapsUrl: 'https://maps.google.com/?q=La+Ferme+Michlifen+Ifrane',
    bestDishes: ['Clay-oven Baked Country Bread', 'Farm Garden Vegetable Tagine', 'Fresh Mountain Herb Tea'],
    tip: 'Perfect for families with kids who will love exploring the nearby vegetable plots and herb gardens.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Lunch around 13:00 for leisurely outdoor dining',
    averageWaitMinutes: 5,
    seatingTypes: ['garden', 'terrace'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  ,
    tags: ["budget", "dry", "fine", "live-music", "quiet", "tagine", "terrace", "wifi"]
  },

  {
    id: 'e-ifrane-empreinte',
    city: 'ifrane_azrou',
    name: "L'Empreinte d'Ifrane",
    neighborhood: 'Downtown Ifrane',
    description: 'Elegant timber-accented boutique cafe and restaurant serving Asian noodles, sushi, Moroccan tajines, gourmet burgers, and rich Italian roast espresso.',
    pricePerPerson: 18,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Modern Fusion Dining', 'People Watching'],
    foodStyles: ['Moroccan', 'International', 'Cafe'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    crowdLevel: 'balanced',
    groupTypes: ['friends', 'couple', 'solo', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '08:00',
    closeTime: '23:30',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 1181,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 210,
    theforkRating: 4.3,
    theforkReviewCount: 65,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 1181,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'none'],
    reservationContact: '+212535566790',
    googleMapsUrl: 'https://maps.google.com/?q=L+Empreinte+d+Ifrane',
    bestDishes: ['Beef Tagine with Almonds', 'Chicken Teriyaki Wok', 'Artisanal Waffles with Chantilly'],
    tip: 'Great central wifi hub with comfortable armchairs, ideal for remote working or reading in the afternoon.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Mid-afternoon 15:30 for coffee and pastry',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dinner", "dry", "tagine", "terrace", "wifi"]
  },

  {
    id: 'e-ifrane-for-you',
    city: 'ifrane_azrou',
    name: 'For You Restaurant',
    neighborhood: 'Ifrane Centre Ville',
    description: 'Popular contemporary gathering spot offering sweet & savory crepes, American BBQ burgers, fresh pasta bowls, and Belgian waffles in an alpine bistro setup.',
    pricePerPerson: 11,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Family Friendly'],
    foodStyles: ['International', 'Fast Food', 'French'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    crowdLevel: 'bustling',
    groupTypes: ['friends', 'solo', 'kids-friendly', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '11:00',
    closeTime: '23:00',
    badge: 'local',

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 1015,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 130,
    theforkRating: 4.4,
    theforkReviewCount: 45,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 1015,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    reservationContact: 'None',
    googleMapsUrl: 'https://maps.google.com/?q=For+You+Restaurant+Ifrane',
    bestDishes: ['Cheese & Smoked Turkey Crepe', 'Double Beef Burger Deluxe', 'Nutella Banana Waffle'],
    tip: 'A student favorite from Al Akhawayn University; arrive before 20:00 to snag a booth table.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Early dinner at 19:00',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["budget", "dinner", "dry", "street-food", "wifi"]
  },

  {
    id: 'e-ifrane-houari-grill',
    city: 'ifrane_azrou',
    name: 'Houari Grill',
    neighborhood: 'Marché Municipal Ifrane',
    description: 'Local favorite butcher-grill serving impeccably spiced minced kefta skewers, Atlas lamb chops, and merguez brochettes grilled over hot olive charcoal with freshly baked batbout.',
    pricePerPerson: 9,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery', 'Local Gathering Spot'],
    foodStyles: ['Barbecue', 'Moroccan', 'Berber'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    crowdLevel: 'bustling',
    groupTypes: ['friends', 'solo', 'family'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '11:30',
    closeTime: '22:00',
    badge: 'local',

    // ── RATINGS ──
    googleRating: 4.8,
    googleReviewCount: 235,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 50,
    theforkRating: 4.3,
    theforkReviewCount: 20,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 235,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    reservationContact: 'None',
    googleMapsUrl: 'https://maps.google.com/?q=Houari+Grill+Ifrane',
    bestDishes: ['Charcoal Kefta Brochettes', 'Atlas Lamb Chops', 'Fresh Tomato Onion Salad'],
    tip: 'Choose your cuts directly at the butcher counter, and they will grill them fresh to order right in front of you.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Lunch at 13:00 when grills are smoking hot',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: true
  ,
    tags: ["budget", "dinner", "dry", "mountain", "street-food", "terrace"]
  },

  {
    id: 'e-ifrane-grand-hotel',
    city: 'ifrane_azrou',
    name: 'Grand Hôtel Ifrane Restaurant',
    neighborhood: 'Avenue de la Marche Verte',
    description: 'Historic colonial alpine dining room serving Middle Atlas freshwater trout meunière, tender beef fillet with morel sauce, and classic French-Moroccan dishes.',
    pricePerPerson: 26,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Classic Royal Ambiance', 'Fine Dining'],
    foodStyles: ['French', 'Moroccan', 'Seafood'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    alcoholPolicy: 'serves-alcohol',
    servesAlcohol: false,
    ramadanFriendly: 'serves-lunch',
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'seniors', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 580,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 160,
    theforkRating: 4.2,
    theforkReviewCount: 45,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 520,

    paymentMethods: ['card', 'cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212535566207',
    googleMapsUrl: 'https://maps.google.com/?q=Grand+Hotel+Ifrane',
    bestDishes: ['Fresh Atlas Trout with Lemon Butter', 'Filet de Boeuf Grillé', 'Warm Tarte Tatin'],
    tip: 'One of the few spots in central Ifrane outside of Michlifen that serves Moroccan wine alongside fresh mountain trout.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Dinner around 19:30',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'city',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["alcohol", "budget", "dinner", "fine", "mountain", "wifi"]
  },

  {
    id: 'e-azrou-restaurant-hassan',
    city: 'ifrane_azrou',
    name: 'Restaurant Hassan',
    neighborhood: 'Marché Municipal Azrou',
    description: 'Legendary Azrou culinary staple celebrated for sizzling Atlas mountain trout with herbs, succulent grilled lamb cutlets, and slow-braised veal tagines in a bustling market setting.',
    pricePerPerson: 10,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Local Gathering Spot', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Seafood', 'Barbecue'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    crowdLevel: 'bustling',
    groupTypes: ['family', 'friends', 'solo'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '11:00',
    closeTime: '22:30',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.8,
    googleReviewCount: 1198,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 290,
    theforkRating: 4.5,
    theforkReviewCount: 80,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 1198,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    reservationContact: 'None',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Hassan+Azrou',
    bestDishes: ['Fresh Pan-Fried Atlas Trout', 'Grilled Lamb Cutlets', 'Veal Tagine with Prunes & Almonds'],
    tip: 'Widely recognized as the premier value-for-money spot in the Middle Atlas for fresh river trout.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Lunch between 12:30 and 14:00',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: true
  ,
    tags: ["budget", "dinner", "dry", "mountain", "tagine", "terrace"]
  },

  {
    id: 'e-azrou-restaurant-rif',
    city: 'ifrane_azrou',
    name: 'Restaurant Rif Chez Khalid',
    neighborhood: 'Place Hassan II Azrou',
    description: 'Beloved central square terrace restaurant serving authentic Middle Atlas Berber tagines, tender brochettes, fresh Moroccan salads, and piping-hot mint tea.',
    pricePerPerson: 8,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner'],
    experienceTypes: ['People Watching', 'Traditional Dining', 'Local Gathering Spot'],
    foodStyles: ['Moroccan', 'Berber', 'Barbecue'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends', 'family'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '08:00',
    closeTime: '22:00',
    badge: 'local',

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 316,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 120,
    theforkRating: 4.2,
    theforkReviewCount: 30,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 316,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    reservationContact: 'None',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Rif+Chez+Khalid+Azrou',
    bestDishes: ['Chicken Tagine with Preserved Lemon', 'Mixed Charcoal Brochettes', 'Fresh Berber Salad'],
    tip: 'Sit outside on Place Hassan II under the green canvas umbrellas to watch village market life unfold.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Lunch around 13:00 on Tuesday market day',
    averageWaitMinutes: 5,
    seatingTypes: ['terrace', 'indoor'],
    viewType: 'city',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: true
  ,
    tags: ["breakfast", "budget", "dinner", "dry", "mountain", "tagine", "terrace"]
  },

  {
    id: 'e-azrou-foodies',
    city: 'ifrane_azrou',
    name: 'Foodies Azrou',
    neighborhood: 'Downtown Azrou',
    description: 'Modern casual fast-food grill featuring crispy chicken tenders, smash burgers, cheesy loaded tacos, and milkshakes catering to locals and travelers on the N13 route.',
    pricePerPerson: 7.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Family Friendly'],
    foodStyles: ['Fast Food', 'International'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    crowdLevel: 'bustling',
    groupTypes: ['friends', 'solo', 'kids-friendly'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '23:30',
    badge: 'local',

    // ── RATINGS ──
    googleRating: 4.8,
    googleReviewCount: 366,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 70,
    theforkRating: 4.3,
    theforkReviewCount: 25,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 366,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    reservationContact: 'None',
    googleMapsUrl: 'https://maps.google.com/?q=Foodies+Azrou',
    bestDishes: ['Double Cheeseburger', 'Crispy Chicken French Tacos', 'Oreo Shake'],
    tip: 'Ideal pit stop for a quick, filling, hygienic meal when traveling between Fes and Midelt.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Quick lunch at 13:30',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["budget", "dinner", "dry", "street-food", "wifi"]
  },

  {
    id: 'e-azrou-bilal',
    city: 'ifrane_azrou',
    name: 'Restaurant Café Bilal',
    neighborhood: 'Boulevard Mohammed V Azrou',
    description: 'Multi-story family restaurant and salon de thé overlooking the heart of Azrou, delivering hearty Friday couscous, Moroccan tajines, French tacos, and aromatic cafe au lait.',
    pricePerPerson: 8.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner'],
    experienceTypes: ['People Watching', 'Traditional Dining', 'Local Gathering Spot'],
    foodStyles: ['Moroccan', 'Cafe', 'Fast Food'],
    // food-cuisine quiz question tags
    cuisineTags: ['cafe-pastry'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    crowdLevel: 'balanced',
    groupTypes: ['family', 'friends', 'solo'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '07:30',
    closeTime: '23:00',
    badge: 'local',

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 336,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 85,
    theforkRating: 3.9,
    theforkReviewCount: 20,
    restaurantguruRating: 3.8,
    restaurantguruReviewCount: 351,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    reservationContact: 'None',
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Restaurant+Bilal+Azrou',
    bestDishes: ['Friday Seven-Vegetable Couscous', 'Beef Kefta Tajine', 'Spiced Mint Tea with Pine Nuts'],
    tip: 'Head up to the second floor for great elevated street views over Boulevard Mohammed V.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Friday lunch for couscous at 13:00',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "couscous", "dinner", "dry", "street-food", "tagine", "terrace", "wifi"]
  },

  {
    id: 'e-azrou-el-hanae',
    city: 'ifrane_azrou',
    name: 'Restaurant El Hanae chez El Haja',
    neighborhood: 'Medina Quarter Azrou',
    description: 'Humble, deeply authentic Berber kitchen run with motherly warmth, serving slow-simmered beef with wild artichokes, harira, and freshly griddled msemmen.',
    pricePerPerson: 7,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Cozy casual family-run Moroccan eatery', 'Traditional Dining', 'Authentic Berber Feast'],
    foodStyles: ['Moroccan', 'Berber'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'family', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '10:30',
    closeTime: '21:30',
    badge: 'hidden-gem',

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 222,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 60,
    theforkRating: 4.3,
    theforkReviewCount: 15,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 222,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    reservationContact: 'None',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+El+Hanae+chez+El+Haja+Azrou',
    bestDishes: ['Beef Tagine with Seasonal Artichoke & Peas', 'Bowl of Hot Harira Soup', 'Handmade Msemmen with Mountain Honey'],
    tip: 'Authentic homestyle cooking at local prices; ask El Haja what dish was simmered longest today.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Lunch around 12:45',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["breakfast", "budget", "dinner", "dry", "medina", "tagine"]
  },

  {
    id: 'e-azrou-rik-steakhouse',
    city: 'ifrane_azrou',
    name: 'RIK Steakhouse',
    neighborhood: 'Centre Azrou',
    description: 'Contemporary steakhouse offering quality butchered Atlas beef steaks, grilled chicken platters, and crispy french fries with spicy house pepper sauce.',
    pricePerPerson: 14,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Family Friendly'],
    foodStyles: ['Barbecue', 'International'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    crowdLevel: 'balanced',
    groupTypes: ['friends', 'family', 'couple'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local',

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 120,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 35,
    theforkRating: 4.1,
    theforkReviewCount: 15,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 50,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'none'],
    reservationContact: '+212614223344',
    googleMapsUrl: 'https://maps.google.com/?q=RIK+Steakhouse+Azrou',
    bestDishes: ['Grilled Ribeye Steak with Herb Butter', 'Mixed Brochette Skewer Platter', 'Loaded Pepper Fries'],
    tip: 'Order steaks cooked medium or medium-rare for tender Atlas beef.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Dinner at 20:00',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["budget", "dinner", "dry", "mountain", "wifi"]
  },

  {
    id: 'e-ifrane-relais-ras-el-maa',
    city: 'ifrane_azrou',
    name: 'Restaurant Relais Ras El Maa',
    neighborhood: 'Ras El Maa Forest Springs',
    description: 'Scenic forest-edge dining lodge next to the natural springs and trout pisciculture station, famed for fresh catch-of-the-day trout pan-fried with almonds and lemon.',
    pricePerPerson: 15,
    lifestyle: 'balanced',
    mealTypes: ['lunch'],
    experienceTypes: ['Tranquil Dining', 'Scenic Views', 'Traditional Dining'],
    foodStyles: ['Seafood', 'Moroccan'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    crowdLevel: 'balanced',
    groupTypes: ['family', 'seniors', 'couple'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '10:00',
    closeTime: '18:00',
    badge: 'hidden-gem',

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 410,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 120,
    theforkRating: 4.0,
    theforkReviewCount: 30,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 390,

    paymentMethods: ['cash'],
    reservationMethod: ['phone', 'none'],
    reservationContact: '+212535566114',
    googleMapsUrl: 'https://maps.google.com/?q=Hotel+Relais+Ras+El+Maa+Ifrane',
    bestDishes: ['Fresh Trout with Toasted Almonds', 'Grilled Trout en Papillote', 'Atlas Mixed Salad'],
    tip: 'Stroll around the nearby trout ponds and Gouraud cedar woods after a relaxing lunch.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Lunch at 13:00 amidst forest bird songs',
    averageWaitMinutes: 10,
    seatingTypes: ['terrace', 'indoor'],
    viewType: 'garden',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: true
  ,
    tags: ["budget", "dry", "terrace"]
  },

  {
    id: 'e-ifrane-patisserie-la-paix',
    city: 'ifrane_azrou',
    name: 'Pâtisserie de la Paix & Salon de Thé',
    neighborhood: 'Ifrane Lion Plaza',
    description: 'Refined European-style salon de thé celebrated for hot spiced chocolate, mille-feuille, almond croissants, and warm apple tartes enjoyed next to the central stone lion gardens.',
    pricePerPerson: 6.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'afternoon-tea'],
    experienceTypes: ['Bakery-Patisserie', 'People Watching', 'Cafe'],
    foodStyles: ['Bakery', 'Patisserie', 'Cafe'],
    // food-cuisine quiz question tags
    cuisineTags: ['cafe-pastry'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends', 'family', 'couple'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '07:00',
    closeTime: '22:30',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 1420,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 380,
    theforkRating: 4.5,
    theforkReviewCount: 90,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 1350,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    reservationContact: 'None',
    googleMapsUrl: 'https://maps.google.com/?q=Patisserie+La+Paix+Ifrane',
    bestDishes: ['Classic Vanilla Mille-Feuille', 'Thick Alpine Hot Chocolate', 'Almond Croissant'],
    tip: 'The ultimate winter warmup spot after taking photos with the famous Ifrane Stone Lion.',

    // ── LOGISTICS ──
    bestTimeToVisit: 'Morning breakfast at 09:00 or afternoon tea at 16:00',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dry", "pastry", "terrace", "wifi"]
  }
];
