import type { EatListing } from '../types';

/**
 * EAT LISTING TEMPLATE
 * {
 *   id: 'e-[city]-[name]',
 *   city: '[city]',
 *   name: '[Name]',
 *   neighborhood: '[Neighborhood]',
 *   description: '[Long description]',
 *   pricePerPerson: [number],
 *   lifestyle: 'lean' | 'balanced' | 'premium',
 *   mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'latenight', 'afternoon-tea', 'flexible'],
 *   experienceTypes: ['Fine Dining' | 'Waterfront Dining' | 'Romantic Sunset' | 'Beachfront Dining' | 'Garden restaurant with live music' | 'Fountain courtyard' | 'French-Moroccan fusion' | 'Casual Italian Dining' | 'Family Pizza Night' | 'Spanish Beach Lounge' | 'Paella & Tapas' | 'Live Music Terrace' | 'Upscale Romantic Dining' | 'Fine Seafood' | 'Classic Royal Ambiance' | '24/7 Brasserie' | 'People Watching' | 'Bakery-Patisserie' | 'Traditional Breakfast Ritual' | 'Local Gathering Spot' | 'Fishing Harbor Dining' | 'Gourmet Seafood' | 'French-Italian Fusion' | 'Authentic Berber Feast' | 'Traditional Dining' | 'Cozy casual family-run Moroccan eatery' | 'Amazigh-inspired decor' | 'Beachfront Grill' | 'Casual Dining' | 'Sunset Views' | 'Wood-Fired Pizza' | 'Family Friendly' | 'Leafy Tennis Oasis' | 'Tranquil Dining' | 'Upscale Lounge' | 'Modern Fusion Dining' | 'Unverified'],
 *   foodStyles: ['French' | 'Moroccan' | 'Seafood' | 'Mediterranean' | 'European' | 'International' | 'Italian' | 'Pizza' | 'Spanish' | 'Berber' | 'Barbecue' | 'Middle Eastern' | 'Healthy' | 'Cafe' | 'Bakery' | 'Patisserie' | 'Gourmet' | 'Fast Food'],
 *   crowdLevel: 'bustling' | 'balanced' | 'quiet',
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *   hasEnglishStaff: true | false,
 *   hasFrenchStaff: true | false,
 *   hasDelivery: true | false,
 *   hasParking: true | false,
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearCenter: true | false,
 *   isVegetarianFriendly: true | false,
 *   isHalal: true | false,
 *   openTime: 'HH:mm',
 *   closeTime: 'HH:mm',
 *   badge: 'local-favorite' | 'splurge' | 'hidden-gem' | 'local',
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source
 *   // ═══════════════════════════════════════════════════
 *   // Search for real ratings from Google, TripAdvisor, TheFork, and RestaurantGuru.
 *   // If you cannot find a rating for a specific source, set it to the same value as
 *   // the closest available one so the code that calculates average ratings doesn't break.
 *   // Example: if no TripAdvisor rating found, set tripadvisorRating = googleRating
 *
 *   // Google Places rating
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *
 *   // TripAdvisor rating
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *
 *   // TheFork rating
 *   theforkRating: [4.x],
 *   theforkReviewCount: [number],
 *
 *   // RestaurantGuru rating
 *   restaurantguruRating: [4.x],
 *   restaurantguruReviewCount: [number],
 *
 *   // REMOVED: rating, reviewCount, ratingSource (old single-source fields)
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   fullMenu: { type: 'image' | 'text', content: 'https://...' },
 *   tip: '[Short tip]',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   reservationContact: '+212XXXXXXXXX',
 *   bestDishes: ['Dish 1', 'Dish 2'],
 *   alcoholPolicy: 'serves-alcohol' | 'dry',
 *   ramadanFriendly: 'serves-lunch' | 'special-ftour' | 'closed',
 *
 *   // ═══════════════════════════════════════════════════
 *   // NEW FIELDS — psychological UX optimization
 *   // ═══════════════════════════════════════════════════
 *
 *   bestTimeToVisit: 'Early evening around 18:30 for sunset' | 'Lunch around 13:00 for quiet' | 'Late evening after 20:00 for lively crowd' | 'Early morning for fresh baked goods' | 'Sunday morning for brunch peak',
 *   averageWaitMinutes: 0 | 5 | 10 | 15 | 20 | 30 | 45 | 60,
 *   seatingTypes: ['indoor'] | ['terrace'] | ['rooftop'] | ['garden'] | ['beachfront'] | ['indoor', 'terrace'] | ['indoor', 'garden'] | ['terrace', 'rooftop'],
 *   viewType: 'beach' | 'mountain' | 'city' | 'garden' | 'none',
 *   wiFi: true | false,
 *   airConditioning: true | false,
 *   wheelchairAccessible: true | false,
 *   website: 'https://...',
 *   instagram: '@handle' | 'https://instagram.com/...'
 * }
 */

export const marrakechEat: EatListing[] = [
  {
    id: 'm-eat-1',
    city: 'marrakech',
    name: 'Le Jardin',
    neighborhood: 'Medina',
    description: 'A beautifully restored 16th-century riad transformed into a lush green garden oasis. Serves a lovely mix of classic Moroccan dishes and light international fare in a serene, plant-filled courtyard.',
    googlePlaceId: 'ChIJb7M_c23urw0RE4_wA_2aXAY',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1541518763669-27fef04b14e8?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 16,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'afternoon-tea'],
    experienceTypes: ['Casual Dining', 'Romantic Sunset', 'Garden restaurant with live music'],
    foodStyles: ['Moroccan', 'Mediterranean'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 3100,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 3100,
    theforkRating: 4.4,
    theforkReviewCount: 3100,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 3100,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['online', 'phone'],
    reservationContact: '+212524378295',
    googleMapsUrl: 'https://maps.google.com/?q=Le+Jardin+Marrakech',
    bestDishes: ['Saffron Chicken Tagine', 'Vegetarian Couscous', 'Moroccan Mint Tea'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Excellent for escaping the midday heat of the souks. The courtyard is completely shaded, cool, and filled with songbirds.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'm-eat-2',
    city: 'marrakech',
    name: 'La Famille',
    neighborhood: 'Medina',
    description: 'An incredibly popular, chic vegetarian garden lunch spot. Hidden away in a quiet alley, it offers daily-changing Mediterranean menus with fresh, organic ingredients.',
    googlePlaceId: 'ChIJy0qZVG3urw0RGH19bK-S8m4',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 14,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'brunch'],
    experienceTypes: ['Casual Dining', 'Garden restaurant with live music', 'Cafe'],
    foodStyles: ['Mediterranean', 'Healthy'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '16:00',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 1400,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 1400,
    theforkRating: 4.6,
    theforkReviewCount: 1400,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 1400,

    paymentMethods: ['cash'],
    reservationMethod: ['online'],
    googleMapsUrl: 'https://maps.google.com/?q=La+Famille+Marrakech',
    bestDishes: ['Fresh Fig and Goat Cheese Salad', 'Daily Homemade Pasta', 'Organic Orange Blossom Tart'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'Only open for lunch and completely vegetarian. You must book a few days in advance as seats are limited and highly sought after.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 0,
    seatingTypes: ['garden'],
    viewType: 'garden',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'm-eat-3',
    city: 'marrakech',
    name: 'Chez Lamine Hadj Mustapha',
    neighborhood: 'Medina / Jemaa el-Fna',
    description: 'The absolute reference point for traditional, slow-roasted pit lamb (Mechoui) and authentic clay-pot Tanjia Marrakchia. Run by a legendary local master chef.',
    googlePlaceId: 'ChIJc1eWcG3urw0RuX3f3qD3C9g',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 9,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery', 'Local Gathering Spot'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: false,
    isHalal: true,
    openTime: '09:00',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 1800,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 1800,
    theforkRating: 4.6,
    theforkReviewCount: 1800,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 1800,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Chez+Lamine+Hadj+Mustapha+Marrakech',
    bestDishes: ['Mechoui (Pit-Roasted Lamb)', 'Tanjia Marrakchia', 'Traditional Khobz'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: "Head down 'Mechoui Alley' off Jemaa el-Fna. Order the lamb by weight (e.g., 1/4 kg) and dip it in cumin and salt.",

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'm-eat-4',
    city: 'marrakech',
    name: 'Café des Épices',
    neighborhood: 'Medina / Rahba Kedima',
    description: 'The most iconic multi-story rooftop cafe in the Medina, located right on the bustling Rahba Kedima (Spice Square). Perfect for views of the local markets, spice stalls, and Atlas Mountains.',
    googlePlaceId: 'ChIJuX4rVG3urw0RD8i8J7R2B6U',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 7.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'flexible'],
    experienceTypes: ['Cafe', 'Sunset Views', 'Casual Dining', 'People Watching'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Cafe'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '09:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 4800,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 4800,
    theforkRating: 4.2,
    theforkReviewCount: 4800,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 4800,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+des+Epices+Marrakech',
    bestDishes: ['Kefta Egg Tagine', 'Spice Square Juice (Ginger & Orange)', 'Saffron Milk Tea'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Head up to the second or third rooftop tier just before sunset. The view of the daily market activity below is unbeatable.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'rooftop', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'm-eat-5',
    city: 'marrakech',
    name: 'Nomad',
    neighborhood: 'Medina',
    description: 'A trendy, internationally acclaimed restaurant with chic modern-Moroccan design. Offers dual rooftop terraces with views of the Rahba Kedima square and serves fresh, modern Maghrebi-fusion plates.',
    googlePlaceId: 'ChIJn5-m_23urw0RNy-T1B4f34g',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 18,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Modern Fusion Dining', 'Sunset Views', 'Scenic Views'],
    foodStyles: ['Moroccan', 'Mediterranean'],
    crowdLevel: 'bustling',
    groupTypes: ['couple', 'friends', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.0,
    googleReviewCount: 6886,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 6886,
    theforkRating: 4.0,
    theforkReviewCount: 6886,
    restaurantguruRating: 4.0,
    restaurantguruReviewCount: 6886,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['online', 'phone'],
    reservationContact: '+212524387329',
    googleMapsUrl: 'https://maps.google.com/?q=Nomad+Marrakech',
    bestDishes: ['Lamb Burger with Harissa Mayo', 'Vegetarian Lentil Salad', 'Saffron Scented Orange Cake'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Highly popular with international foodies. Reserve a table on the top deck well in advance to catch the sunset over the Atlas range.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 20,
    seatingTypes: ['indoor', 'rooftop', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'm-eat-6',
    city: 'marrakech',
    name: 'Al Fassia',
    neighborhood: 'Gueliz',
    description: "One of Marrakech's most respected restaurants, entirely operated by women. Specializes in incredibly slow-cooked, delicate stews and tagines representing the high-culinary heritage of Fes.",
    googlePlaceId: 'ChIJlWv0_m3urw0R5D-k0eQZ1xA',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 25,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Traditional Dining', 'Upscale Lounge'],
    foodStyles: ['Moroccan', 'Mediterranean'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'seniors', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 376,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 376,
    theforkRating: 4.3,
    theforkReviewCount: 376,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 376,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212524434060',
    googleMapsUrl: 'https://maps.google.com/?q=Al+Fassia+Gueliz',
    bestDishes: ['Lamb Tagine with Caramelized Onions', 'Pigeon Pastilla', 'Moroccan Salad Assortment'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Unlike most tourist spots, their tagines are slow-cooked to order. Their Lamb Tagine with Almonds and Caramelized Onions is award-winning.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'm-eat-7',
    city: 'marrakech',
    name: 'Le Grand Café de la Poste',
    neighborhood: 'Gueliz',
    description: 'A beautifully restored 1920s French colonial-style brasserie in Gueliz. Features deep-set leather chairs, brass fans, and a leafy veranda, serving classic French bistro meals and modern Mediterranean food.',
    googlePlaceId: 'ChIJt1m_dm3urw0R6E9vG_BfX0Q',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 22,
    lifestyle: 'premium',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'flexible'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Upscale Lounge'],
    foodStyles: ['French', 'Mediterranean', 'European'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'business-friendly', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '01:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 1900,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 1900,
    theforkRating: 4.3,
    theforkReviewCount: 1900,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 1900,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212524433038',
    googleMapsUrl: 'https://maps.google.com/?q=Le+Grand+Cafe+de+la+Poste+Marrakech',
    bestDishes: ['Steak Frites', 'Oysters from Oualidia', 'Brunch Benedict'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Excellent romantic atmosphere on the first floor. Highly favored by expats and stylish locals for weekend brunch.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'm-eat-8',
    city: 'marrakech',
    name: 'Cafe Clock',
    neighborhood: 'Kasbah',
    description: 'A cross-cultural oasis in the historic Kasbah. Famous for camel burgers, traditional Moroccan storytelling nights, and calligraphy lessons. It serves a vibrant, student-friendly international & Moroccan hybrid menu.',
    googlePlaceId: 'ChIJwSg88mzurw0RDh5G3N6s_10',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 8.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'flexible'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Traditional Dining'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Cafe'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'friends', 'kids-friendly', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '09:00',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 2300,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 2300,
    theforkRating: 4.4,
    theforkReviewCount: 2300,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 2300,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Clock+Marrakech',
    bestDishes: ['Camel Burger', 'Date and Cardamom Milkshake', 'Vegetarian Platter'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'They host traditional Moroccan storytelling (Hikayat) in English and Arabic on select evenings—great for a cultural experience.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'rooftop'],
    viewType: 'city',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'm-eat-9',
    city: 'marrakech',
    name: 'Dar Cherifa',
    neighborhood: 'Medina',
    description: 'One of the oldest, most beautifully preserved 15th-century riads in the Medina, operating as a quiet literary café and cultural space. Serves premium herbal teas, Moroccan cookies, and delicate home-cooked tagines.',
    googlePlaceId: 'ChIJs79A_m3urw0RwX1s6L7f3e8',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 12,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'afternoon-tea'],
    experienceTypes: ['Cafe', 'Traditional Dining', 'Tranquil Dining'],
    foodStyles: ['Moroccan', 'Cafe'],
    crowdLevel: 'quiet',
    groupTypes: ['solo', 'couple', 'family', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '10:00',
    closeTime: '21:30',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 450,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 450,
    theforkRating: 4.6,
    theforkReviewCount: 450,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 450,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Dar+Cherifa+Marrakech',
    bestDishes: ['Saffron Lamb Tagine', 'Msemen with Honey', 'Mint Tea with Kaab el Ghazal'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'A magnificent artistic sanctuary to read, relax, or write. The intricate cedarwood and plaster carvings inside this riad are museum-quality.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 0,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'm-eat-10',
    city: 'marrakech',
    name: 'Bacha Coffee',
    neighborhood: 'Medina / Dar El Bacha',
    description: 'An incredibly opulent coffee salon situated inside the grand Dar El Bacha Palace. Features stunning tiled floors, servers in tailored uniforms, and an extensive global coffee list of over 200 single-origin beans.',
    googlePlaceId: 'ChIJs2-X_23urw0Rt3e2S1x8D4Q',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 18,
    lifestyle: 'premium',
    mealTypes: ['breakfast', 'afternoon-tea', 'brunch', 'flexible'],
    experienceTypes: ['Cafe', 'Fine Dining', 'Upscale Lounge'],
    foodStyles: ['Cafe', 'French', 'Patisserie'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'friends', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '10:00',
    closeTime: '18:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 3800,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 3800,
    theforkRating: 4.7,
    theforkReviewCount: 3800,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 3800,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Bacha+Coffee+Marrakech',
    bestDishes: ['100% Arabica Specialty Coffee', 'Chantilly Cream and Honey Croissant', 'Lemon Tart'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'They do not accept reservations and wait times can easily exceed 2 hours during peak holiday seasons. Put your name on the list first, then visit the Dar El Bacha museum while you wait.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 60,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'm-eat-11',
    city: 'marrakech',
    name: 'Mouton Noir',
    neighborhood: 'Gueliz',
    description: 'A chic and stylish contemporary bistro in the heart of Gueliz. Specializes in incredibly creative fusion cooking that marries classic French culinary craft with bold Asian and Moroccan ingredients.',
    googlePlaceId: 'ChIJ_z78_m3urw0R9v3e7X6b_12',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 19,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Modern Fusion Dining', 'Casual Dining', 'Upscale Lounge'],
    foodStyles: ['Mediterranean', 'French', 'International'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 520,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 520,
    theforkRating: 4.6,
    theforkReviewCount: 520,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 520,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212661828551',
    googleMapsUrl: 'https://maps.google.com/?q=Mouton+Noir+Marrakech',
    bestDishes: ['Pulled Lamb Tacos with Harissa', 'Prawn Ravioli', 'Yuzu Panna Cotta'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: "A true local favorite for Gueliz's young professionals. The slow-roasted lamb tacos and seasonal salads are phenomenal.",

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'm-eat-12',
    city: 'marrakech',
    name: 'Plus 61',
    neighborhood: 'Gueliz',
    description: 'A highly acclaimed, design-forward Australian-inspired bistro. Features a minimalistic interior and serves extremely clean, organic Mediterranean and international plates sourcing local farm ingredients.',
    googlePlaceId: 'ChIJx15_923urw0R3f8E6V1b4w0',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 22,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Modern Fusion Dining', 'Casual Dining'],
    foodStyles: ['Mediterranean', 'Seafood', 'Healthy'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'solo', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:30',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 750,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 750,
    theforkRating: 4.5,
    theforkReviewCount: 750,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 750,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['online', 'phone'],
    reservationContact: '+212524434661',
    googleMapsUrl: 'https://maps.google.com/?q=Plus+61+Marrakech',
    bestDishes: ['Organic Roast Half Chicken', 'Ricotta Gnocchi with Sage', 'Atlantic Sea Bass Carpaccio'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Perfect if you want a break from spiced stews. The menu is light, seasonal, and exceptionally fresh.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'm-eat-13',
    city: 'marrakech',
    name: 'Chez Bejgueni',
    neighborhood: 'Gueliz',
    description: 'An incredibly bustling, historic local fast-food barbecue counter. Known throughout Marrakech for serving rapid-fire grilled kefta, beef skewers, and frites stuffed inside freshly baked local bread.',
    googlePlaceId: 'ChIJb_3_4m3urw0Rv8e_8b1c4w8',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 4.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Casual Dining', 'Local Gathering Spot', 'Quick Bites'],
    foodStyles: ['Moroccan', 'Fast Food'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends', 'family'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: false,
    isHalal: true,
    openTime: '11:00',
    closeTime: '02:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 1950,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 1950,
    theforkRating: 4.4,
    theforkReviewCount: 1950,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 1950,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Chez+Bejgueni+Marrakech',
    bestDishes: ['Merguez Sausage Sandwich', 'Spiced Kefta Brochettes', 'Fresh French Fries'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: "A true local institution. Order a 'Mixed Grill Sandwich' with fries, and douse it with their smoky house-harissa.",

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'm-eat-14',
    city: 'marrakech',
    name: 'Dar Moha',
    neighborhood: 'Medina',
    description: "An opulent dining room set around the stunning mosaic pool of the former palace of Pasha el Glaoui's secretary. Helmed by legendary Chef Moha, it presents high-end, inventive gourmet Moroccan culinary art.",
    googlePlaceId: 'ChIJ5f3_323urw0Rq8e_7X2b1v0',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1541518763669-27fef04b14e8?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 42,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Traditional Dining', 'Romantic Sunset'],
    foodStyles: ['Moroccan', 'Gourmet'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'seniors', 'large-groups'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 2200,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 2200,
    theforkRating: 4.5,
    theforkReviewCount: 2200,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 2200,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['online', 'phone'],
    reservationContact: '+212524386400',
    googleMapsUrl: 'https://maps.google.com/?q=Dar+Moha+Marrakech',
    bestDishes: ['Gourmet Lamb Tanjia', 'Filet of Sea Bream with Argan Oil', 'Royal Pigeon Pastilla'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Sit poolside in the evenings for a truly magical atmosphere accompanied by acoustic Andalusian lute strings. Dress strictly smart-casual.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'm-eat-15',
    city: 'marrakech',
    name: 'Atay Cafe',
    neighborhood: 'Medina',
    description: 'A cozy, highly rustic multi-tiered rooftop cafe in the Medina. Decorated with colorful textiles and local pottery, it offers sweeping 360-degree views of the old city and budget-friendly Moroccan stews.',
    googlePlaceId: 'ChIJz_2_223urw0Rp3e_6X1a5b8',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 6.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'flexible'],
    experienceTypes: ['Cafe', 'Sunset Views', 'Scenic Views', 'Casual Dining'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Cafe'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'friends', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '09:00',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 1650,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 1650,
    theforkRating: 4.4,
    theforkReviewCount: 1650,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 1650,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Atay+Cafe+Marrakech',
    bestDishes: ['Lemon Chicken Tagine', 'Vegetarian Couscous', 'Cold Mint & Cucumber Mocktail'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'The highest deck gets windy, but offers unmatched photo opportunities over the rooftops of Bab Doukkala at dusk.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'rooftop'],
    viewType: 'city',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'm-eat-16',
    city: 'marrakech',
    name: 'Le Jardin Secret - Café',
    neighborhood: 'Medina',
    description: 'A serene and historically significant garden café within the Le Jardin Secret complex. Offers a tranquil environment for artisanal tea and snacks surrounded by rare botanical species.',
    googlePlaceId: 'ChIJw_1_123urw0Ro3e_5X0a4b7',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 5,
    lifestyle: 'balanced',
    mealTypes: ['snack', 'afternoon-tea', 'breakfast'],
    experienceTypes: ['Cafe', 'Tranquil Dining', 'Garden restaurant with live music'],
    foodStyles: ['Cafe', 'Moroccan', 'Bakery'],
    crowdLevel: 'quiet',
    groupTypes: ['solo', 'couple', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '09:30',
    closeTime: '19:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 850,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 850,
    theforkRating: 4.5,
    theforkReviewCount: 850,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 850,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Le+Jardin+Secret+Cafe+Marrakech',
    bestDishes: ['Artisanal Mint Tea', 'Home-made Moroccan cookies', 'Fresh Juice'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'A perfect peaceful respite from the busy Medina. Entrance fee to the garden required.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['garden', 'indoor'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  },

  {
    id: 'm-eat-17',
    city: 'marrakech',
    name: 'Patisserie des Princes',
    neighborhood: 'Gueliz',
    description: 'A historic, upscale local pastry shop known for perfecting traditional Moroccan and French sweets. A beloved destination for both locals and tourists to buy boxes of handmade almond treats.',
    googlePlaceId: 'ChIJv_0_023urw0Rn3e_4X9a3b6',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 5,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'afternoon-tea'],
    experienceTypes: ['Cafe', 'Bakery-Patisserie'],
    foodStyles: ['Patisserie', 'Moroccan', 'French', 'Bakery'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '07:30',
    closeTime: '21:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 1200,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 1200,
    theforkRating: 4.7,
    theforkReviewCount: 1200,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 1200,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Patisserie+des+Princes+Marrakech',
    bestDishes: ['Kaab el Ghazal', 'Almond Baklava', 'French-style Macarons'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Buy their beautifully presented gift boxes of mixed almond pastries to bring home.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'm-eat-18',
    city: 'marrakech',
    name: 'Kabana',
    neighborhood: 'Medina',
    description: 'A hip rooftop restaurant and lounge featuring sophisticated Mediterranean and sushi-inspired cuisine, plus top-notch crafted non-alcoholic mocktails with a vibrant Marrakech party vibe.',
    googlePlaceId: 'ChIJu_9_913urw0Rm3e_3X8a2b5',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 25,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Fine Dining', 'Sunset Views', 'Modern Fusion Dining', 'Upscale Lounge'],
    foodStyles: ['Mediterranean', 'Seafood', 'International'],
    crowdLevel: 'bustling',
    groupTypes: ['couple', 'friends', 'solo'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '02:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 950,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 950,
    theforkRating: 4.4,
    theforkReviewCount: 950,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 950,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['online', 'phone'],
    reservationContact: '+212660357599',
    googleMapsUrl: 'https://maps.google.com/?q=Kabana+Marrakech',
    bestDishes: ['Fresh Salmon Tartare', 'Kabana Specialty Roll', 'Spiced Mocktail'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Perfect for late-night vibes. Their rooftop transforms into a lively lounge with excellent music after dark.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor', 'rooftop'],
    viewType: 'city',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'm-eat-19',
    city: 'marrakech',
    name: 'Limoni',
    neighborhood: 'Medina',
    description: 'A bright, lemon-yellow Italian-Moroccan oasis in the Medina. Known for its stylish terrace, wood-fired pizzas, homemade pastas, and a very relaxing, chic, and bright Mediterranean vibe.',
    googlePlaceId: 'ChIJt_8_813urw0Rl3e_2X7a1b4',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 15,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Italian Dining', 'Romantic Sunset', 'Garden restaurant with live music'],
    foodStyles: ['Italian', 'Moroccan', 'Mediterranean', 'Pizza'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 2100,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 2100,
    theforkRating: 4.4,
    theforkReviewCount: 2100,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 2100,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Limoni+Marrakech',
    bestDishes: ['Lemon Basil Pizza', 'Homemade Tagliatelle', 'House Tiramisu'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Their indoor courtyard is filled with lemon trees. The Italian-Moroccan fusion dishes, like tagine-flavored pastas, are surprisingly brilliant.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'm-eat-20',
    city: 'marrakech',
    name: 'Street Food Market (Jemaa el-Fna)',
    neighborhood: 'Medina / Jemaa el-Fna',
    description: 'The epicenter of Marrakech food culture. A massive, chaotic, and essential evening experience featuring dozens of independent stalls serving snails, fried fish, sheep heads, and mixed tajines.',
    googlePlaceId: 'ChIJs_7_713urw0Rk3e_1X6a0b3',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1509315811355-57bd3b7771b6?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 3,
    lifestyle: 'lean',
    mealTypes: ['dinner', 'latenight'],
    experienceTypes: ['Local Gathering Spot', 'Traditional Dining', 'People Watching'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '18:00',
    closeTime: '01:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 4500,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 4500,
    theforkRating: 4.5,
    theforkReviewCount: 4500,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 4500,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Jemaa+el-Fna+Stalls+Marrakech',
    bestDishes: ['Snail Soup (Babbouche)', 'Grilled Merguez Sausages', 'Fried Fish Mix'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Stall 14 is the go-to for seafood, Stall 31 for sausages. Always agree on price before sitting down to avoid overcharging.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'city',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: true
  }
];