import type { EatListing } from '../types';

export const marrakechEat: EatListing[] = [
  {
    id: 'm-eat-1',
    city: 'marrakech',
    name: 'Le Jardin',
    neighborhood: 'Medina',
    description: 'A beautifully restored 16th-century riad transformed into a lush green garden oasis. Serves a lovely mix of classic Moroccan dishes and light international fare in a serene, plant-filled courtyard.',
    googlePlaceId: 'ChIJ_1XbVGjurw0RHNXyrVPvcwc',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1541518763669-27fef04b14e8?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 18,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'afternoon-tea'],
    experienceTypes: ['Casual Dining', 'Romantic Sunset', 'Garden restaurant with live music', 'Fountain courtyard'],
    foodStyles: ['Moroccan', 'Mediterranean', 'European'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international'],
    crowdLevel: 'bustling',
    groupTypes: ['couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '10:00',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 6480,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 2930,
    theforkRating: 4.1,
    theforkReviewCount: 450,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 10990,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['online', 'phone'],
    reservationContact: '+212524378295',
    googleMapsUrl: 'https://maps.google.com/?q=Le+Jardin+Marrakech',
    bestDishes: ['Beef Tanjia Marrakchia', 'Chicken Pastilla with Cherries', 'Saffron Crème Brûlée'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Strictly dry (no alcohol served). Courtyard is completely shaded and cool, making it ideal to escape midday heat in the souks.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'garden', 'terrace'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["budget", "dinner", "dry", "live-music", "medina", "pastilla", "riad", "sunset", "tanjia", "terrace", "wifi"]
  },

  {
    id: 'm-eat-2',
    city: 'marrakech',
    name: 'La Famille',
    neighborhood: 'Medina',
    description: 'An incredibly popular, chic vegetarian garden lunch spot. Hidden away in a quiet alley, it offers daily-changing Mediterranean menus with fresh, organic ingredients under lemon trees.',
    googlePlaceId: 'ChIJy0qZVG3urw0RGH19bK-S8m4',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 16,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'brunch'],
    experienceTypes: ['Casual Dining', 'Tranquil Dining', 'Cafe'],
    foodStyles: ['Mediterranean', 'Healthy'],
    // food-cuisine quiz question tags
    cuisineTags: ['international'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '12:00',
    closeTime: '16:00',
    badge: 'hidden-gem',

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 1650,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 550,
    theforkRating: 4.3,
    theforkReviewCount: 180,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 2200,

    paymentMethods: ['cash'],
    reservationMethod: ['online'],
    googleMapsUrl: 'https://maps.google.com/?q=La+Famille+Marrakech',
    bestDishes: ['Fresh Fig and Goat Cheese Salad', 'Daily Homemade Pasta', 'Organic Orange Blossom Tart'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'Lunch service only, closed on Sundays, and 100% vegetarian. Book online several days in advance as seating is scarce.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 0,
    seatingTypes: ['garden'],
    viewType: 'garden',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dry", "medina"]
  },

  {
    id: 'm-eat-3',
    city: 'marrakech',
    name: 'Chez Lamine Hadj Mustapha',
    neighborhood: 'Medina / Jemaa el-Fna',
    description: 'The historic reference point for traditional, slow-roasted pit lamb (Méchoui) and authentic clay-pot Tanjia Marrakchia. Run by a legendary local master chef off Jemaa el-Fna.',
    googlePlaceId: 'ChIJc1eWcG3urw0RuX3f3qD3C9g',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 10,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery', 'Local Gathering Spot'],
    foodStyles: ['Moroccan'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: false,
    isHalal: true,
    servesAlcohol: false,
    openTime: '11:30',
    closeTime: '21:30',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 3.7,
    googleReviewCount: 3420,
    tripadvisorRating: 3.8,
    tripadvisorReviewCount: 1640,
    theforkRating: 3.7,
    theforkReviewCount: 300,
    restaurantguruRating: 3.8,
    restaurantguruReviewCount: 3420,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    reservationContact: '+212662022080',
    googleMapsUrl: 'https://maps.google.com/?q=Chez+Lamine+Hadj+Mustapha+Marrakech',
    bestDishes: ['Mechoui (Pit-Roasted Lamb)', 'Tanjia Marrakchia', 'Traditional Khobz'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Arrive between 12:00 and 13:30. The lamb méchoui is roasted underground in the morning and frequently sells out by mid-afternoon.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'rooftop'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["budget", "dinner", "dry", "medina", "rooftop", "tanjia"]
  },

  {
    id: 'm-eat-4',
    city: 'marrakech',
    name: 'Café des Épices',
    neighborhood: 'Medina / Rahba Kedima',
    description: 'The iconic multi-story rooftop cafe in the Medina, located right on the bustling Rahba Kedima (Spice Square). Perfect for market views, spice stalls, and Atlas Mountains panoramas.',
    googlePlaceId: 'ChIJuX4rVG3urw0RD8i8J7R2B6U',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 8,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'flexible'],
    experienceTypes: ['Cafe', 'Sunset Views', 'Casual Dining', 'People Watching'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Cafe'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international', 'cafe-pastry'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '09:00',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 7150,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 6680,
    theforkRating: 4.1,
    theforkReviewCount: 750,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 14000,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    reservationContact: '+212662564134',
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+des+Epices+Marrakech',
    bestDishes: ['Kefta Egg Tagine', 'Spice Square Juice (Ginger & Orange)', 'Saffron Spiced Coffee'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Walk-ins only. Head up to the second or top rooftop terrace just before sunset for sweeping views over Rahba Kedima.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'rooftop', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dinner", "dry", "juice", "medina", "mountain", "rooftop", "sunset", "tagine", "terrace", "wifi"]
  },

  {
    id: 'm-eat-5',
    city: 'marrakech',
    name: 'Nomad',
    neighborhood: 'Medina / Rahba Kedima',
    description: 'A trendy, internationally acclaimed multi-level restaurant with chic modern-Moroccan design. Offers dual rooftop terraces overlooking Spice Square serving inventive Maghrebi-fusion plates.',
    googlePlaceId: 'ChIJuXAbl2Xurw0R9pfGiHPcnso',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 20,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Modern Fusion Dining', 'Sunset Views', 'Fine Dining'],
    foodStyles: ['Moroccan', 'Mediterranean'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international'],
    crowdLevel: 'bustling',
    groupTypes: ['couple', 'friends', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.0,
    googleReviewCount: 7530,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 6670,
    theforkRating: 4.1,
    theforkReviewCount: 880,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 14500,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['online', 'phone'],
    reservationContact: '+212524381609',
    googleMapsUrl: 'https://maps.google.com/?q=Nomad+Marrakech',
    bestDishes: ['Lamb Burger with Harissa Mayo', 'Spiced Calamari', 'Saffron Scented Orange Cake'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Book 1-2 weeks in advance for top terrace tables at sunset. Completely dry; serves signature infused mocktails.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 20,
    seatingTypes: ['indoor', 'rooftop', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  ,
    tags: ["budget", "dinner", "dry", "fine", "medina", "rooftop", "sunset", "terrace", "wifi"]
  },

  {
    id: 'm-eat-6',
    city: 'marrakech',
    name: 'Al Fassia',
    neighborhood: 'Gueliz',
    description: 'One of Marrakech’s most respected dining institutions, operated entirely by women since 1987. Specializes in exquisite, slow-cooked tagines and stews preserving the authentic culinary heritage of Fes.',
    googlePlaceId: 'ChIJlWv0_m3urw0R5D-k0eQZ1xA',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 28,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Traditional Dining', 'Upscale Lounge'],
    foodStyles: ['Moroccan', 'Gourmet'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'seniors', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    openTime: '17:00',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 3410,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 2400,
    theforkRating: 4.5,
    theforkReviewCount: 520,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 3400,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212524434060',
    googleMapsUrl: 'https://maps.google.com/?q=Al+Fassia+Gueliz',
    bestDishes: ['Lamb Tagine with Caramelized Onions', 'Royal Pigeon Pastilla', 'Assortment of 12 Moroccan Salads'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Closed on Tuesdays. Features a full licensed Moroccan wine list. Dishes like the shoulder of lamb for two require calling 24h ahead.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["alcohol", "budget", "dinner", "fine", "pastilla", "tagine", "terrace", "wifi"]
  },

  {
    id: 'm-eat-7',
    city: 'marrakech',
    name: 'Le Grand Café de la Poste',
    neighborhood: 'Gueliz',
    description: 'A restored 1920s French colonial brasserie in Gueliz. Features deep leather armchairs, brass fans, and a leafy veranda, serving classic French bistro meals and Mediterranean plates.',
    googlePlaceId: 'ChIJt1m_dm3urw0R6E9vG_BfX0Q',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 26,
    lifestyle: 'premium',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'flexible'],
    experienceTypes: ['Fine Dining', '24/7 Brasserie', 'Upscale Lounge', 'People Watching'],
    foodStyles: ['French', 'Mediterranean', 'European'],
    // food-cuisine quiz question tags
    cuisineTags: ['international', 'cafe-pastry'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'business-friendly', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    openTime: '08:00',
    closeTime: '01:00',
    badge: 'splurge',

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 4500,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 2800,
    theforkRating: 4.3,
    theforkReviewCount: 650,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 5500,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212524433038',
    googleMapsUrl: 'https://maps.google.com/?q=Le+Grand+Cafe+de+la+Poste+Marrakech',
    bestDishes: ['Steak Frites', 'Oysters from Oualidia', 'Duck Confit Parmentier'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'The ground floor and mezzanine offer vintage atmosphere with jazz in the background. Excellent wine and cocktail selection.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["alcohol", "breakfast", "budget", "cafe-pastry", "dinner", "fine", "late-night", "terrace", "wifi"]
  },

  {
    id: 'm-eat-8',
    city: 'marrakech',
    name: 'Cafe Clock',
    neighborhood: 'Kasbah',
    description: 'A cross-cultural oasis in the historic Kasbah. Famous for camel burgers, traditional Moroccan storytelling nights (Hikayat), and calligraphy classes in a student-friendly, hybrid Moroccan setting.',
    googlePlaceId: 'ChIJwSg88mzurw0RDh5G3N6s_10',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 9,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'flexible'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Traditional Dining'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Cafe'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international', 'cafe-pastry'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'friends', 'kids-friendly', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '09:00',
    closeTime: '22:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 2500,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 1800,
    theforkRating: 4.4,
    theforkReviewCount: 220,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 3000,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    reservationContact: '+212524378367',
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Clock+Marrakech',
    bestDishes: ['Camel Burger with Spiced Wedges', 'Spiced Date Shake', 'Falafel & Hummus Bowl'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Hosts live traditional Moroccan storytelling in English on Thursday evenings and Gnawa jams on Sundays.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'rooftop'],
    viewType: 'city',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dinner", "dry", "medina", "rooftop", "wifi"]
  },

  {
    id: 'm-eat-9',
    city: 'marrakech',
    name: 'Dar Cherifa',
    neighborhood: 'Medina',
    description: 'One of the oldest, most beautifully preserved 15th-century riads in the Medina, operating as a quiet literary café and cultural space with museum-grade stucco and cedar woodwork.',
    googlePlaceId: 'ChIJs79A_m3urw0RwX1s6L7f3e8',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 15,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'afternoon-tea'],
    experienceTypes: ['Cafe', 'Traditional Dining', 'Tranquil Dining', 'Fountain courtyard'],
    foodStyles: ['Moroccan', 'Cafe'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'cafe-pastry'],
    crowdLevel: 'quiet',
    groupTypes: ['solo', 'couple', 'family', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '10:00',
    closeTime: '22:00',
    badge: 'hidden-gem',

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 2630,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 920,
    theforkRating: 4.5,
    theforkReviewCount: 150,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 2630,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212524426550',
    googleMapsUrl: 'https://maps.google.com/?q=Dar+Cherifa+Marrakech',
    bestDishes: ['Saffron Lamb Tagine', 'Msemen with Orange Blossom Honey', 'Artisanal Mint Tea with Cornes de Gazelle'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'One of the most tranquil architectural sanctuaries in the souks. Closes at 19:00 on Wednesdays.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 0,
    seatingTypes: ['indoor', 'rooftop'],
    viewType: 'none',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["budget", "cafe-pastry", "dinner", "dry", "medina", "quiet", "riad", "rooftop", "tagine", "wifi"]
  },

  {
    id: 'm-eat-10',
    city: 'marrakech',
    name: 'Bacha Coffee',
    neighborhood: 'Medina / Dar El Bacha',
    description: 'An opulent coffee salon situated inside the grand Dar El Bacha Palace. Features zellige mosaic tiles, tailored liveried waiters, and an unmatched catalog of over 200 single-origin Arabica coffees.',
    googlePlaceId: 'ChIJs2-X_23urw0Rt3e2S1x8D4Q',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 20,
    lifestyle: 'premium',
    mealTypes: ['breakfast', 'afternoon-tea', 'brunch', 'flexible'],
    experienceTypes: ['Cafe', 'Fine Dining', 'Upscale Lounge'],
    foodStyles: ['Cafe', 'French', 'Patisserie'],
    // food-cuisine quiz question tags
    cuisineTags: ['cafe-pastry', 'international'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'friends', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '10:00',
    closeTime: '18:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 4250,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 1250,
    theforkRating: 4.4,
    theforkReviewCount: 100,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 4500,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    reservationContact: '+212524381293',
    googleMapsUrl: 'https://maps.google.com/?q=Bacha+Coffee+Marrakech',
    bestDishes: ['100% Arabica Specialty Coffee Pot', 'Fresh Chantilly Croissant', 'Pistachio Lemon Brioche'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'Closed on Mondays. Requires paid entry to Dar El Bacha museum. No reservations taken—arrive at 10:00 AM sharp to put your name on the buzzer list.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 60,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dry", "fine", "medina", "palace", "wifi"]
  },

  {
    id: 'm-eat-11',
    city: 'marrakech',
    name: 'Cantine Mouton Noir',
    neighborhood: 'Gueliz',
    description: 'A stylish, Montreal-inspired contemporary bistro in Gueliz. Renowned for innovative fusion cooking pairing French culinary technique with bold Moroccan and Mediterranean ingredients.',
    googlePlaceId: 'ChIJ592LSmzurw0R8t5W4aB7L2k',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 19,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'brunch'],
    experienceTypes: ['Modern Fusion Dining', 'Casual Dining', 'Upscale Lounge'],
    foodStyles: ['Mediterranean', 'French', 'International'],
    // food-cuisine quiz question tags
    cuisineTags: ['international'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 420,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 160,
    theforkRating: 4.6,
    theforkReviewCount: 80,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 420,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212669149054',
    googleMapsUrl: 'https://maps.google.com/?q=Cantine+Mouton+Noir+Marrakech',
    bestDishes: ['Slow-Roasted Lamb Tacos with Harissa', 'Prawn Ravioli', 'Gourmet French Toast'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'A favorite for weekend brunch in Gueliz. Features an open kitchen and inventive seasonal specials.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["breakfast", "budget", "dinner", "dry", "fine", "terrace", "wifi"]
  },

  {
    id: 'm-eat-12',
    city: 'marrakech',
    name: 'Plus61',
    neighborhood: 'Gueliz',
    description: 'An acclaimed Australian-inspired bistro featured on the 50 Best MENA list. Features minimalist styling and serves fresh, produce-forward plates blending Mediterranean, Middle Eastern, and Moroccan flavors.',
    googlePlaceId: 'ChIJgU_fN2zurw0R7J05XF3o8pM',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 25,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Modern Fusion Dining', 'Casual Dining'],
    foodStyles: ['Mediterranean', 'Seafood', 'Healthy'],
    // food-cuisine quiz question tags
    cuisineTags: ['international', 'seafood'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'solo', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    openTime: '12:00',
    closeTime: '22:30',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 940,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 340,
    theforkRating: 4.6,
    theforkReviewCount: 120,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 1050,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['online', 'phone'],
    reservationContact: '+212524207020',
    googleMapsUrl: 'https://maps.google.com/?q=Plus61+Marrakech',
    bestDishes: ['Slow-Cooked Lamb Shoulder with Flatbread', 'Ricotta Gnocchi with Sage Butter', 'Chargrilled Octopus with Chermoula'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Closed on Sundays. Superb natural wine selection and craft cocktails; counter seats along the kitchen pass are ideal for solo diners.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["alcohol", "budget", "dinner", "fine", "wifi"]
  },

  {
    id: 'm-eat-13',
    city: 'marrakech',
    name: 'Chez Bejgueni',
    neighborhood: 'Gueliz',
    description: 'A bustling, legendary local fast-casual grill spot in Gueliz. Packed with locals day and night for sizzling charcoal-grilled kefta skewers, merguez, and fresh frites.',
    googlePlaceId: 'ChIJg_3qL2zurw0R4vO7R6v7D1U',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Casual Dining', 'Local Gathering Spot'],
    foodStyles: ['Moroccan', 'Fast Food', 'Barbecue'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends', 'family'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: false,
    isHalal: true,
    servesAlcohol: false,
    openTime: '11:00',
    closeTime: '02:00',
    badge: 'local',

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 2250,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 1800,
    theforkRating: 4.2,
    theforkReviewCount: 100,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 2000,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Chez+Bejgueni+Marrakech',
    bestDishes: ['Charcoal Kefta Brochettes', 'Merguez Sausage Sandwich', 'Fresh Moroccan Fries with Harissa'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Authentic Gueliz street-grill experience. Order the mixed grill plate with fresh khobz and extra grilled tomatoes.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["budget", "dinner", "dry", "late-night", "street-food", "terrace"]
  },

  {
    id: 'm-eat-14',
    city: 'marrakech',
    name: 'Dar Moha',
    neighborhood: 'Medina',
    description: 'An opulent dining room set around the mosaic pool of the former palace of Pierre Balmain and Pasha el Glaoui’s secretary. Helmed by Chef Moha Fedal, it is a pioneer in refined nouvelle cuisine marocaine.',
    googlePlaceId: 'ChIJu_v52Gfurw0RTerhpHuxAp0',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1541518763669-27fef04b14e8?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 52,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Traditional Dining', 'Romantic Sunset', 'Fountain courtyard'],
    foodStyles: ['Moroccan', 'Gourmet'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'seniors', 'large-groups'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    openTime: '12:30',
    closeTime: '23:00',
    badge: 'splurge',

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 2500,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 2100,
    theforkRating: 4.3,
    theforkReviewCount: 350,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 2600,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['online', 'phone'],
    reservationContact: '+212524386400',
    googleMapsUrl: 'https://maps.google.com/?q=Dar+Moha+Marrakech',
    bestDishes: ['14-Salad Tasting Assortment', 'Seafood Pastilla with Bisque', 'Slow-Braised Lamb Shank with Sweet Fruits'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Multi-course set menu (~530–650 MAD) accompanied by acoustic lute/Andalusian musicians. Request a poolside courtyard table.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  ,
    tags: ["alcohol", "dinner", "fine", "medina", "palace", "pastilla", "sunset", "wifi"]
  },

  {
    id: 'm-eat-15',
    city: 'marrakech',
    name: 'Atay Cafe',
    neighborhood: 'Medina',
    description: 'A rustic multi-tiered rooftop cafe in Bab Doukkala. Decorated with colorful Berber rugs and wicker lamps, it offers panoramic 360-degree views of the old city and budget-friendly Moroccan tagines.',
    googlePlaceId: 'ChIJ7eXqP2furw0R6pG1vN3z0bQ',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 8,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'flexible'],
    experienceTypes: ['Cafe', 'Sunset Views', 'Casual Dining'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Cafe'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international', 'cafe-pastry'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'friends', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '10:00',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 2850,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 1520,
    theforkRating: 4.2,
    theforkReviewCount: 100,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 3000,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Atay+Cafe+Marrakech',
    bestDishes: ['Lemon Chicken Tagine with Olives', 'Vegetarian Couscous', 'Mint Cucumber Lemonade'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Climb all the way to the top deck for sunset photos facing the Koutoubia minaret. Cash only.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'rooftop', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "couscous", "dinner", "dry", "medina", "rooftop", "sunset", "tagine", "terrace", "wifi"]
  },

  {
    id: 'm-eat-16',
    city: 'marrakech',
    name: 'Le Jardin Secret - Café',
    neighborhood: 'Medina',
    description: 'A serene garden café situated within the restored 19th-century palace grounds of Le Jardin Secret. Enjoy fresh juices, iced teas, and light pastries beside exotic botanical flora.',
    googlePlaceId: 'ChIJzWv6yGfurw0RQ4U4Q02T3oI',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 6,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'afternoon-tea', 'flexible'],
    experienceTypes: ['Cafe', 'Tranquil Dining', 'Garden restaurant with live music'],
    foodStyles: ['Cafe', 'Moroccan', 'Bakery'],
    // food-cuisine quiz question tags
    cuisineTags: ['cafe-pastry', 'moroccan-traditional'],
    crowdLevel: 'quiet',
    groupTypes: ['solo', 'couple', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '09:30',
    closeTime: '18:30',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 1350,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 850,
    theforkRating: 4.5,
    theforkReviewCount: 100,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 1500,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Le+Jardin+Secret+Cafe+Marrakech',
    bestDishes: ['Iced Mint Tea with Fresh Lemon', 'Almond Briouates', 'Fresh Citrus Fruit Juice'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'Requires purchasing standard admission to Le Jardin Secret. Perfect midday reading and cooling-off spot.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['garden', 'terrace'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dry", "juice", "live-music", "medina", "palace", "pastry", "quiet", "terrace", "wifi"]
  },

  {
    id: 'm-eat-17',
    city: 'marrakech',
    name: 'Pâtisserie des Princes',
    neighborhood: 'Medina / Jemaa el-Fna',
    description: 'Marrakech’s legendary pastry parlor operating since 1989 on Passage Prince Moulay Rachid, steps from Jemaa el-Fna. Renowned for authentic handmade almond sweets, cornets de gazelle, and ice creams.',
    googlePlaceId: 'ChIJ22xOumuurw0RzQ0N9v6u8-0',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 4,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'afternoon-tea', 'flexible'],
    experienceTypes: ['Cafe', 'Bakery-Patisserie', 'Local Gathering Spot'],
    foodStyles: ['Patisserie', 'Moroccan', 'French', 'Bakery'],
    // food-cuisine quiz question tags
    cuisineTags: ['cafe-pastry'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '07:00',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 2520,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 1100,
    theforkRating: 4.2,
    theforkReviewCount: 100,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 2600,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    reservationContact: '+212524443033',
    googleMapsUrl: 'https://maps.google.com/?q=Patisserie+des+Princes+Marrakech',
    bestDishes: ['Cornes de Gazelle', 'Mhancha (Almond Serpent Cake)', 'House Pistachio Gelato'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Head upstairs to the air-conditioned salon for mint tea and pastries away from the street crowds. Pastries can be boxed by the kilo to take home.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: false,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dry", "medina", "pastry", "terrace"]
  },

  {
    id: 'm-eat-18',
    city: 'marrakech',
    name: 'Kabana',
    neighborhood: 'Medina',
    description: 'A vibrant, botanical rooftop cocktail lounge and restaurant overlooking the Koutoubia minaret. Features an eclectic menu of Mediterranean tapas, sushi, and DJ sets after dark.',
    googlePlaceId: 'ChIJK0tXvWjurw0R1s72aP5zM7c',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 28,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Fine Dining', 'Sunset Views', 'Modern Fusion Dining', 'Upscale Lounge'],
    foodStyles: ['Mediterranean', 'Seafood', 'International'],
    // food-cuisine quiz question tags
    cuisineTags: ['international', 'seafood'],
    crowdLevel: 'bustling',
    groupTypes: ['couple', 'friends', 'solo'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    openTime: '11:00',
    closeTime: '02:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 5650,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 1050,
    theforkRating: 4.4,
    theforkReviewCount: 350,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 6000,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['online', 'phone'],
    reservationContact: '+212664464450',
    googleMapsUrl: 'https://maps.google.com/?q=Kabana+Rooftop+Marrakech',
    bestDishes: ['Kabana Signature Sushi Rolls', 'Salmon Tartare with Avocado', 'Craft Passion Fruit Cocktails'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'One of the highest licensed rooftop bars in the Medina. Book a table at the railing for direct Koutoubia sunset views.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor', 'rooftop', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  ,
    tags: ["alcohol", "budget", "dinner", "fine", "late-night", "medina", "rooftop", "sunset", "terrace", "wifi"]
  },

  {
    id: 'm-eat-19',
    city: 'marrakech',
    name: 'Limoni',
    neighborhood: 'Medina',
    description: 'A charming Italian-Moroccan trattoria set in a quiet residential alley in Bab Taghzout. Guests dine on fresh handmade pasta and wood-fired pizza surrounded by lemon trees and zellige fountains.',
    googlePlaceId: 'ChIJj7k_wWfurw0R8U6Q5c1s8s0',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 18,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Italian Dining', 'Romantic Sunset', 'Fountain courtyard'],
    foodStyles: ['Italian', 'Moroccan', 'Mediterranean', 'Pizza'],
    // food-cuisine quiz question tags
    cuisineTags: ['international', 'moroccan-traditional'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 3950,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 1500,
    theforkRating: 4.5,
    theforkReviewCount: 400,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 4200,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212524383030',
    googleMapsUrl: 'https://maps.google.com/?q=Limoni+Marrakech',
    bestDishes: ['Camel Burger with Rosemary Fries', 'Homemade Tagliatelle with Lemon & Truffle', 'Traditional Wood-Fired Pizza'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Licensed to serve wine and beer. Located deeper in the northern medina, so drop a pin on your map beforehand.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'garden', 'terrace'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["alcohol", "budget", "dinner", "medina", "sunset", "terrace", "wifi"]
  },

  {
    id: 'm-eat-20',
    city: 'marrakech',
    name: 'Street Food Market (Jemaa el-Fna)',
    neighborhood: 'Medina / Jemaa el-Fna',
    description: 'The pulsating heart of Marrakech street food culture. A massive open-air nocturnal food market featuring numbered stalls serving snails, skewers, fried seafood, sheep heads, and spiced broths.',
    googlePlaceId: 'ChIJj7m9pWuurw0R1s4_1vQe0u8',
    nonCopyrightImage: 'https://images.unsplash.com/photo-1509315811355-57bd3b7771b6?auto=format&fit=crop&w=800&q=80',
    pricePerPerson: 4,
    lifestyle: 'lean',
    mealTypes: ['dinner', 'latenight'],
    experienceTypes: ['Local Gathering Spot', 'Traditional Dining', 'People Watching'],
    foodStyles: ['Moroccan', 'Fast Food'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '18:00',
    closeTime: '01:00',
    badge: 'local',

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 5200,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 4500,
    theforkRating: 4.2,
    theforkReviewCount: 500,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 5500,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Jemaa+el-Fna+Stalls+Marrakech',
    bestDishes: ['Babbouche (Herbal Snail Broth)', 'Grilled Merguez & Kefta Brochettes', 'Fried Calamari & Whiting Plate'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Bench seating directly on the open square. Always confirm prices before sitting down. Stall 14 is favored for fried fish and Stall 31 for grilled skewers.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 5,
    seatingTypes: ['terrace'],
    viewType: 'city',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: true
  ,
    tags: ["budget", "dinner", "dry", "late-night", "medina", "street-food", "terrace"]
  },
  {
    id: "m-eat-mcdonalds-gueliz",
    city: "marrakech",
    name: "McDonald's Gueliz",
    neighborhood: "Gu\u00e9liz",
    district: "Centre Gu\u00e9liz",
    description: "Iconic Gu\u00e9liz branch on Avenue Mohammed V offering indoor air-conditioned seating, sidewalk caf\u00e9 terrace, McCaf\u00e9, and late-night burgers.",
    pricePerPerson: 65,
    lifestyle: "lean",
    mealTypes: ["breakfast", "lunch", "dinner", "latenight"],
    experienceTypes: ["Fast Food", "Casual Dining", "Terrace Seating"],
    foodStyles: ["Burgers", "Fast Food", "American"],
    alcoholPolicy: "dry",
    ramadanFriendly: "special-ftour",
    crowdLevel: "bustling",
    groupTypes: ["family", "friends", "solo"],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: "halal-certified",
    verificationStatus: "verified",
    openTime: "07:00",
    closeTime: "02:00",
    badge: "local-favorite",
    googleRating: 4.0,
    googleReviewCount: 7800,
    googleMapsUrl: "https://maps.google.com/?cid=1209384756192837465",
    paymentMethods: ["Cash", "Credit Card", "Contactless"],
    languagesSpoken: ["Arabic", "French", "English"],
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true,
    tags: ["street-food", "late-night", "breakfast", "budget", "terrace"],
    exactAddressAndCoordinates: {
      address: "Boulevard Mohammed V, Gu\u00e9liz, Marrakech",
      lat: 31.6348,
      lng: -8.0125
    }
  },
  {
    id: "m-eat-kfc-gueliz",
    city: "marrakech",
    name: "KFC Gueliz",
    neighborhood: "Gu\u00e9liz",
    district: "Gu\u00e9liz",
    description: "Centrally located on Avenue Mohammed V in Gu\u00e9liz, serving original recipe fried chicken, hot wings, and family buckets.",
    pricePerPerson: 60,
    lifestyle: "lean",
    mealTypes: ["lunch", "dinner", "latenight"],
    experienceTypes: ["Fast Food", "Casual Dining"],
    foodStyles: ["Fried Chicken", "Fast Food", "American"],
    // food-cuisine quiz question tags
    cuisineTags: ['international'],
    alcoholPolicy: "dry",
    ramadanFriendly: "special-ftour",
    crowdLevel: "bustling",
    groupTypes: ["family", "friends", "solo"],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: false,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: "halal-certified",
    verificationStatus: "verified",
    openTime: "11:00",
    closeTime: "01:00",
    badge: "local-favorite",
    googleRating: 3.9,
    googleReviewCount: 2900,
    googleMapsUrl: "https://maps.google.com/?cid=8912304918273645123",
    paymentMethods: ["Cash", "Credit Card", "Contactless"],
    languagesSpoken: ["Arabic", "French", "English"],
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true,
    tags: ["street-food", "late-night", "budget"],
    exactAddressAndCoordinates: {
      address: "Boulevard Mohammed V, Gu\u00e9liz, Marrakech",
      lat: 31.6335,
      lng: -8.0118
    }
  },
  {
    id: "m-eat-burger-king-carre-eden",
    city: "marrakech",
    name: "Burger King Carr\u00e9 Eden",
    neighborhood: "Gu\u00e9liz",
    district: "Carr\u00e9 Eden Shopping Center",
    description: "Modern food court Burger King inside the Carr\u00e9 Eden shopping mall in Gu\u00e9liz, serving Whoppers, crispy fries, and milkshakes.",
    pricePerPerson: 65,
    lifestyle: "lean",
    mealTypes: ["lunch", "dinner"],
    experienceTypes: ["Fast Food", "Mall Dining"],
    foodStyles: ["Burgers", "Fast Food", "American"],
    // food-cuisine quiz question tags
    cuisineTags: ['international'],
    alcoholPolicy: "dry",
    ramadanFriendly: "special-ftour",
    crowdLevel: "bustling",
    groupTypes: ["family", "friends", "solo"],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: "halal-certified",
    verificationStatus: "verified",
    openTime: "11:00",
    closeTime: "23:30",
    badge: "local-favorite",
    googleRating: 4.0,
    googleReviewCount: 2450,
    googleMapsUrl: "https://maps.google.com/?cid=1029384756192837465",
    paymentMethods: ["Cash", "Credit Card", "Contactless"],
    languagesSpoken: ["Arabic", "French", "English"],
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true,
    tags: ["street-food", "budget"],
    exactAddressAndCoordinates: {
      address: "Carr\u00e9 Eden, Boulevard Mohammed V, Gu\u00e9liz, Marrakech",
      lat: 31.6362,
      lng: -8.0142
    }
  },
  {
    id: "m-eat-pizza-hut-menara-mall",
    city: "marrakech",
    name: "Pizza Hut Menara Mall",
    neighborhood: "Hivernage",
    district: "Avenue Mohammed VI",
    description: "Family-friendly Pizza Hut on the top food court level of Menara Mall with views toward the Atlas Mountains and outdoor terrace seating.",
    pricePerPerson: 70,
    lifestyle: "lean",
    mealTypes: ["lunch", "dinner"],
    experienceTypes: ["Casual Dining", "Mall Dining", "Terrace Views"],
    foodStyles: ["Pizza", "Italian-American", "Fast Food"],
    // food-cuisine quiz question tags
    cuisineTags: ['international'],
    alcoholPolicy: "dry",
    ramadanFriendly: "special-ftour",
    crowdLevel: "balanced",
    groupTypes: ["family", "kids-friendly", "friends"],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: "halal-certified",
    verificationStatus: "verified",
    openTime: "11:30",
    closeTime: "23:30",
    badge: "local-favorite",
    googleRating: 3.9,
    googleReviewCount: 1850,
    googleMapsUrl: "https://maps.google.com/?cid=7819230491827364512",
    paymentMethods: ["Cash", "Credit Card", "Contactless"],
    languagesSpoken: ["Arabic", "French", "English"],
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true,
    tags: ["budget", "terrace"],
    exactAddressAndCoordinates: {
      address: "Menara Mall, Avenue Mohammed VI, Hivernage, Marrakech",
      lat: 31.6186,
      lng: -8.0162
    }
  },
  {
    id: "m-eat-dominos-gueliz",
    city: "marrakech",
    name: "Domino's Pizza Gueliz",
    neighborhood: "Gu\u00e9liz",
    district: "Gu\u00e9liz",
    description: "Carry-out and express delivery branch serving freshly baked hand-tossed pizzas, stuffed cheesy bread, and lava cakes in central Marrakech.",
    pricePerPerson: 60,
    lifestyle: "lean",
    mealTypes: ["lunch", "dinner", "latenight"],
    experienceTypes: ["Takeaway", "Delivery", "Pizza"],
    foodStyles: ["Pizza", "Fast Food", "American"],
    alcoholPolicy: "dry",
    ramadanFriendly: "special-ftour",
    crowdLevel: "balanced",
    groupTypes: ["friends", "solo", "family"],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: "halal-certified",
    verificationStatus: "verified",
    openTime: "11:30",
    closeTime: "01:00",
    badge: "local-favorite",
    googleRating: 3.8,
    googleReviewCount: 1420,
    googleMapsUrl: "https://maps.google.com/?cid=4918273645102938475",
    paymentMethods: ["Cash", "Credit Card", "Contactless"],
    languagesSpoken: ["Arabic", "French", "English"],
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true,
    tags: ["late-night", "budget"],
    exactAddressAndCoordinates: {
      address: "Boulevard Allal El Fassi, Gu\u00e9liz, Marrakech",
      lat: 31.6482,
      lng: -8.0094
    }
  }
];