import type { EatListing } from '../types';

/**
 * EAT LISTING TEMPLATE
 * {
 *   id: 'e-[city]-[name]',
 *   city: '[city]',
 *   name: '[Name]',
 *   neighborhood: '[Neighborhood]',
 *   description: '[Long description]',
 *   pricePerPerson: [number],
 *   lifestyle: 'lean' | 'balanced' | 'premium',
 *   mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'latenight', 'afternoon-tea', 'flexible'],
 *   experienceTypes: ['Fine Dining' | 'Waterfront Dining' | 'Romantic Sunset' | 'Beachfront Dining' | 'Garden restaurant with live music' | 'Fountain courtyard' | 'French-Moroccan fusion' | 'Casual Italian Dining' | 'Family Pizza Night' | 'Spanish Beach Lounge' | 'Paella & Tapas' | 'Live Music Terrace' | 'Upscale Romantic Dining' | 'Fine Seafood' | 'Classic Royal Ambiance' | '24/7 Brasserie' | 'People Watching' | 'Bakery-Patisserie' | 'Traditional Breakfast Ritual' | 'Local Gathering Spot' | 'Fishing Harbor Dining' | 'Gourmet Seafood' | 'French-Italian Fusion' | 'Authentic Berber Feast' | 'Traditional Dining' | 'Cozy casual family-run Moroccan eatery' | 'Amazigh-inspired decor' | 'Beachfront Grill' | 'Casual Dining' | 'Sunset Views' | 'Wood-Fired Pizza' | 'Family Friendly' | 'Leafy Tennis Oasis' | 'Tranquil Dining' | 'Upscale Lounge' | 'Modern Fusion Dining' | 'Unverified'],
 *   foodStyles: ['French' | 'Moroccan' | 'Seafood' | 'Mediterranean' | 'European' | 'International' | 'Italian' | 'Pizza' | 'Spanish' | 'Berber' | 'Barbecue' | 'Middle Eastern' | 'Healthy' | 'Cafe' | 'Bakery' | 'Patisserie' | 'Gourmet' | 'Fast Food'],
 *   crowdLevel: 'bustling' | 'balanced' | 'quiet',
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *   hasEnglishStaff: true | false,
 *   hasFrenchStaff: true | false,
 *   hasDelivery: true | false,
 *   hasParking: true | false,
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearCenter: true | false,
 *   isVegetarianFriendly: true | false,
 *   isHalal: true | false,
 *   openTime: 'HH:mm',
 *   closeTime: 'HH:mm',
 *   badge: 'local-favorite' | 'splurge' | 'hidden-gem' | 'local',
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source
 *   // ═══════════════════════════════════════════════════
 *   // Search for real ratings from Google, TripAdvisor, TheFork, and RestaurantGuru.
 *   // If you cannot find a rating for a specific source, set it to the same value as
 *   // the closest available one so the code that calculates average ratings doesn't break.
 *   // Example: if no TripAdvisor rating found, set tripadvisorRating = googleRating
 *
 *   // Google Places rating
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *
 *   // TripAdvisor rating
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *
 *   // TheFork rating
 *   theforkRating: [4.x],
 *   theforkReviewCount: [number],
 *
 *   // RestaurantGuru rating
 *   restaurantguruRating: [4.x],
 *   restaurantguruReviewCount: [number],
 *
 *   // REMOVED: rating, reviewCount, ratingSource (old single-source fields)
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   fullMenu: { type: 'image' | 'text', content: 'https://...' },
 *   tip: '[Short tip]',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   reservationContact: '+212XXXXXXXXX',
 *   bestDishes: ['Dish 1', 'Dish 2'],
 *   alcoholPolicy: 'serves-alcohol' | 'dry',
 *   ramadanFriendly: 'serves-lunch' | 'special-ftour' | 'closed',
 *
 *   // ═══════════════════════════════════════════════════
 *   // NEW FIELDS — psychological UX optimization
 *   // ═══════════════════════════════════════════════════
 *
 *   bestTimeToVisit: 'Early evening around 18:30 for sunset' | 'Lunch around 13:00 for quiet' | 'Late evening after 20:00 for lively crowd' | 'Early morning for fresh baked goods' | 'Sunday morning for brunch peak',
 *   averageWaitMinutes: 0 | 5 | 10 | 15 | 20 | 30 | 45 | 60,
 *   seatingTypes: ['indoor'] | ['terrace'] | ['rooftop'] | ['garden'] | ['beachfront'] | ['indoor', 'terrace'] | ['indoor', 'garden'] | ['terrace', 'rooftop'],
 *   viewType: 'beach' | 'mountain' | 'city' | 'garden' | 'none',
 *   wiFi: true | false,
 *   airConditioning: true | false,
 *   wheelchairAccessible: true | false,
 *   website: 'https://...',
 *   instagram: '@handle' | 'https://instagram.com/...'
 * }
 */

export const meknesEat: EatListing[] = [
  {
    id: 'e-meknes-1',
    city: 'meknes',
    name: 'Aisha',
    neighborhood: 'Medina',
    description: 'A legendary, cupboard-sized diner nestled deep in the souks of the Medina. Extremely famous for its budget-friendly, authentic Moroccan cooking prepared by Aisha herself.',
    pricePerPerson: 3.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Cozy casual family-run Moroccan eatery', 'Casual Dining', 'Traditional Dining'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '21:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.8,
    googleReviewCount: 310,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 310,
    theforkRating: 4.8,
    theforkReviewCount: 310,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 310,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Aisha+Meknes',
    bestDishes: ['Chicken Pastilla', 'Vegetable Couscous', 'Beef Tagine with Prunes'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'It is a tiny, rustic shop but has incredible hospitality. The chicken pastilla and vegetable couscous are fantastic value.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-meknes-2',
    city: 'meknes',
    name: 'Le Collier de la Colombe',
    neighborhood: 'Medina',
    description: 'Located in an elegant, palace-style building with stunning panoramic terrace views overlooking the valley and the old city. Serves refined traditional Moroccan recipes alongside selected international dishes.',
    pricePerPerson: 18,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Traditional Dining', 'Sunset Views'],
    foodStyles: ['Moroccan', 'Mediterranean'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'seniors', 'large-groups'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 464,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 212,
    theforkRating: 4.1,
    theforkReviewCount: 212,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 464,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Le+Collier+de+la+Colombe+Meknes',
    bestDishes: ['Lemon Chicken Tagine', 'Royal Couscous', 'Moroccan Pastry Assortment'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Ask to sit on the terrace for sunset to enjoy unparalleled views of the valley while dining.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'e-meknes-3',
    city: 'meknes',
    name: 'Le Relais de Paris',
    neighborhood: 'Ville Nouvelle',
    description: 'An elegant French bistro in the modern Ville Nouvelle. Features a high-end French menu, a relaxing romantic atmosphere, views of Mt. Zerhoun, and a beautiful green garden.',
    pricePerPerson: 29,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Upscale Lounge'],
    foodStyles: ['French', 'Mediterranean', 'European'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:30',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 350,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 350,
    theforkRating: 4.2,
    theforkReviewCount: 350,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 350,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Le+Relais+de+Paris+Meknes',
    bestDishes: ['Steak Frites', 'Braised Lamb with Rosemary', 'Chocolate Profiteroles'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'The garden tables are perfect for couples. They serve classical French dishes such as steak frites and braised lamb alongside fine wines.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'mountain',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'e-meknes-4',
    city: 'meknes',
    name: 'Dar Sabre Wa Tourate',
    neighborhood: 'Medina',
    description: 'Housed inside a beautifully restored, contemporary-designed medina riad. Features beautiful zellige mosaic tilework and vibrant decor, serving slow-cooked homestyle Moroccan tagines and pastillas.',
    pricePerPerson: 16,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery', 'Garden restaurant with live music'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:30',
    closeTime: '22:00',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 140,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 140,
    theforkRating: 4.7,
    theforkReviewCount: 140,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 140,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Dar+Sabre+Wa+Tourate+Meknes',
    bestDishes: ['Pigeon Pastilla', 'Plum Lamb Tagine', 'Assorted Moroccan Salads'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'A superb quiet lunch or dinner spot to escape the noisy medina alleys. Try the pigeon pastilla.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-meknes-5',
    city: 'meknes',
    name: 'Restaurant Omnia',
    neighborhood: 'Medina',
    description: 'A cozy family-run riad restaurant located on a quiet street in the historic Medina. Highly favored for its deeply welcoming hospitality and authentic, grandmother-style Moroccan chicken and tajines.',
    pricePerPerson: 11,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'quiet',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '21:30',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 260,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 260,
    theforkRating: 4.5,
    theforkReviewCount: 260,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 260,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Omnia+Meknes',
    bestDishes: ['Chicken Pastilla', 'Beef Tagine with Almonds', 'Homemade Harrira'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'This is a genuine home dining environment. The chicken pastilla and lemon-olive tagine are prepared strictly to order.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-meknes-6',
    city: 'meknes',
    name: 'Palais Didi',
    neighborhood: 'Medina',
    description: 'A majestic 17th-century palace restaurant near the Mausoleum of Moulay Ismaïl. Offers refined traditional Moroccan gastronomy inside a beautiful Andalusian patio with stunning architecture.',
    pricePerPerson: 35,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Traditional Dining', 'Romantic Sunset'],
    foodStyles: ['Moroccan', 'Gourmet'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'seniors', 'large-groups'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 420,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 420,
    theforkRating: 4.5,
    theforkReviewCount: 420,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 420,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    googleMapsUrl: 'https://maps.google.com/?q=Palais+Didi+Meknes',
    bestDishes: ['Royal Lamb Couscous', 'Pigeon Pastilla with Almonds', 'Baked Sea Bream Moroccan Style'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Highly recommended for an opulent Moroccan dinner setting. Combine it with a visit to the adjacent historical mausoleum.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'city',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'e-meknes-7',
    city: 'meknes',
    name: 'Pavillon des Idrissides',
    neighborhood: 'El-Hedime',
    description: 'Boasting a large, spectacular panoramic terrace right at the entrance of the Medina on El-Hedime Square. Excellent for traditional tajines, kebabs, and mint tea with views of the monumental Bab Mansour.',
    pricePerPerson: 9,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Casual Dining', 'Sunset Views', 'People Watching'],
    foodStyles: ['Moroccan', 'Mediterranean'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 1250,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 1250,
    theforkRating: 4.1,
    theforkReviewCount: 1250,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 1250,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Pavillon+des+Idrissides+Meknes',
    bestDishes: ['Lamb Tagine with Apricots', 'Moroccan Chicken Brochettes', 'Mint Tea with Pastries'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Grab a table on the second-floor terrace. It is the best spot in Meknes to people-watch over the lively El-Hedime Square at dusk.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-meknes-8',
    city: 'meknes',
    name: 'Palais Terrab',
    neighborhood: 'Ville Nouvelle',
    description: 'A spectacular, highly opulent palace restaurant located in the modern Ville Nouvelle. Decorated with detailed plaster carvings and cedarwood, serving highly-rated grand Moroccan feasts.',
    pricePerPerson: 22,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Traditional Dining'],
    foodStyles: ['Moroccan', 'Gourmet'],
    crowdLevel: 'balanced',
    groupTypes: ['family', 'couple', 'seniors', 'large-groups', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 710,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 710,
    theforkRating: 4.3,
    theforkReviewCount: 710,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 710,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Palais+Terrab+Meknes',
    bestDishes: ['Royal Saffron Lamb Couscous', 'Beef Pastilla', 'Slow-cooked Tagine'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Perfect for large groups and families looking for a high-quality, comfortable royal dinner setting.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'e-meknes-9',
    city: 'meknes',
    name: 'Restaurant Bab Mansour',
    neighborhood: 'El-Hedime',
    description: 'A popular and very affordable traditional spot facing the majestic Bab Mansour gate. Serves classic, delicious Moroccan tajines, harira, and couscous in a fast-paced setting.',
    pricePerPerson: 7,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Casual Dining', 'Local Gathering Spot'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:00',
    closeTime: '23:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 950,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 950,
    theforkRating: 4.1,
    theforkReviewCount: 950,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 950,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Bab+Mansour+Meknes',
    bestDishes: ['Kefta Tagine with Egg', 'Chicken Couscous', 'Harira Soup'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'It is a very straightforward diner. Great for a quick, cheap tajine lunch after visiting the Bab Mansour Gate.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'city',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-meknes-10',
    city: 'meknes',
    name: 'Bistrot Art & Le Wine Bar',
    neighborhood: 'Ville Nouvelle',
    description: 'Located in the historic Hotel Transatlantique, this bistro offers an elegant, French-Moroccan fusion dining experience with a breathtaking panoramic view of the ancient Medina.',
    pricePerPerson: 28,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Modern Fusion Dining'],
    foodStyles: ['French', 'Moroccan', 'Mediterranean'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:30',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 480,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 480,
    theforkRating: 4.3,
    theforkReviewCount: 480,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 480,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Bistrot+Art+and+Wine+Bar+Meknes',
    bestDishes: ['Duck Confit', 'Seafood Gratin', 'Moroccan Premium Wine Selection'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Perfect for an elegant lunch. Ask to sit near the window for the best panoramas of the Meknes skyline.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'city',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'e-meknes-11',
    city: 'meknes',
    name: 'Riad Ritaj Restaurant',
    neighborhood: 'Medina',
    description: 'Set in a traditional riad patio within the ancient Medina. Features high Andalusian-style ceilings and fine zellige work, serving traditional Meknassi tagines, royal pastillas, and orange salads.',
    pricePerPerson: 16,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Romantic Sunset', 'Garden restaurant with live music'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:30',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 380,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 380,
    theforkRating: 4.6,
    theforkReviewCount: 380,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 380,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Riad+Ritaj+Meknes',
    bestDishes: ['Sweet Plum Lamb Tagine', 'Almond Pigeon Pastilla', 'Cinnamon Orange Salad'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'A superb quiet lunch or dinner spot to escape the noisy medina alleys. Try the pigeon pastilla.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-meknes-12',
    city: 'meknes',
    name: 'Riad Bahia Restaurant',
    neighborhood: 'Medina',
    description: 'Positioned wonderfully between El Hedim Square and the Bou Inania Madrasa. Offers traditional Meknassi recipes in a tranquil, flower-filled riad courtyard with lovely local service.',
    pricePerPerson: 15,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Casual Dining', 'Garden restaurant with live music'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'seniors', 'large-groups'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 320,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 320,
    theforkRating: 4.5,
    theforkReviewCount: 320,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 320,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Riad+Bahia+Meknes',
    bestDishes: ['Slow-Cooked Beef Tanjia', 'Royal Couscous', 'Harira Soup'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Also runs excellent traditional cooking workshops if you reserve in advance.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-meknes-13',
    city: 'meknes',
    name: 'Venezia Ice',
    neighborhood: 'Hamria / Ville Nouvelle',
    description: 'The premier modern cafe and dessert parlor in the Ville Nouvelle. Immensely popular among local families and young crowds for its Italian gelato, coffee, and light continental meals.',
    pricePerPerson: 6,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'brunch', 'flexible'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Family Friendly'],
    foodStyles: ['Italian', 'Cafe', 'Bakery'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '00:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 1450,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 1450,
    theforkRating: 4.2,
    theforkReviewCount: 1450,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 1450,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Venezia+Ice+Meknes',
    bestDishes: ['Pistachio Gelato', 'Nutella Crepe', 'Italian Espresso'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Perfect for families with kids looking for top-notch local ice cream, crepes, and safe modern cafe environment.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'e-meknes-14',
    city: 'meknes',
    name: 'Black Iris Café',
    neighborhood: 'Hamria / Ville Nouvelle',
    description: 'A cozy, trendy, and modern family-friendly cafe-bistro in Ville Nouvelle. Highly popular for delicious modern continental breakfast spreads, premium desserts, and great coffee.',
    pricePerPerson: 7.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'brunch', 'flexible'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Family Friendly'],
    foodStyles: ['Mediterranean', 'Cafe', 'Bakery'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '07:30',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 290,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 290,
    theforkRating: 4.5,
    theforkReviewCount: 290,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 290,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Black+Iris+Meknes',
    bestDishes: ['Continental Breakfast Board', 'French Crepes', 'Specialty Caramel Macchiato'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Highly recommended for an authentic, trendy Meknassi modern coffee culture experience.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'e-meknes-15',
    city: 'meknes',
    name: 'Cube Noir',
    neighborhood: 'Ville Nouvelle',
    description: 'A highly fashionable, upscale casual restaurant and lounge in the Marjane neighborhood. Offers excellent international continental dishes, premium steaks, and artisanal mocktails.',
    pricePerPerson: 19,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Fine Dining', 'Upscale Lounge', 'Modern Fusion Dining'],
    foodStyles: ['Mediterranean', 'Italian', 'International'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'business-friendly', 'large-groups'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '01:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 380,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 380,
    theforkRating: 4.4,
    theforkReviewCount: 380,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 380,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Cube+Noir+Meknes',
    bestDishes: ['Chateaubriand Steak', 'Pesto Penne Pasta', 'Signature Virgin Mojito'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'A great choice if you are seeking high-quality international steaks and chic modern ambiance outside the medina.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'e-meknes-16',
    city: 'meknes',
    name: 'As D-Lys',
    neighborhood: 'Hamria / Ville Nouvelle',
    description: 'A beautifully styled, cozy modern bistro and crêperie in the Hamriya neighborhood. Celebrated for its fresh gourmet pastas, savory French crepes, and lively social scene.',
    pricePerPerson: 8,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'flexible'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Family Friendly'],
    foodStyles: ['French', 'Italian', 'Cafe'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '23:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 340,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 340,
    theforkRating: 4.3,
    theforkReviewCount: 340,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 340,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=As+DLys+Meknes',
    bestDishes: ['Savoury Buckwheat Crepe', 'Almond Alfredo Pasta', 'Gourmet French Pastry'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Perfect place for a casual, comfortable meal with clean, modern European taste.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'e-meknes-17',
    city: 'meknes',
    name: 'Snack El Khmiss',
    neighborhood: 'Medina / Bab El Khemis',
    description: 'An exceptionally popular, high-volume local street food sandwich counter near Bab El Khemis. Serves classic spiced kefta, chicken skewers, and rotisserie chicken in fresh Moroccan crusty bread.',
    pricePerPerson: 3,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Casual Dining', 'Quick Bites', 'Local Gathering Spot'],
    foodStyles: ['Moroccan', 'Fast Food'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: false,
    isHalal: true,
    openTime: '11:00',
    closeTime: '02:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 520,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 520,
    theforkRating: 4.4,
    theforkReviewCount: 520,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 520,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Snack+El+Khmiss+Meknes',
    bestDishes: ['Kefta and Fries Sandwich', 'Rotisserie Chicken', 'Spiced Merguez Skewers'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Order the spiced kefta mixed sandwich with double harissa if you like it hot. Be prepared for a bustling local line.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-meknes-18',
    city: 'meknes',
    name: 'La Maison du Blé',
    neighborhood: 'Hamria / Ville Nouvelle',
    description: 'An authentic Moroccan bakery and traditional salon de thé in the Ville Nouvelle. Locals gather here every single morning for freshly baked harcha, msemen, rghaif, and excellent Moroccan mint tea.',
    pricePerPerson: 4,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'brunch', 'flexible'],
    experienceTypes: ['Cafe', 'Traditional Breakfast Ritual', 'Bakery-Patisserie'],
    foodStyles: ['Bakery', 'Moroccan', 'Cafe'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '06:30',
    closeTime: '21:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 680,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 680,
    theforkRating: 4.5,
    theforkReviewCount: 680,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 680,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=La+Maison+du+Ble+Meknes',
    bestDishes: ['Traditional Msemen with Honey', 'Warm Semolina Harcha', 'Freshly Brewed Mint Tea'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Perfect for an authentic, delicious breakfast. Try the warm harcha topped with local honey and goat cheese.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-meknes-19',
    city: 'meknes',
    name: 'Café Bella Cita',
    neighborhood: 'Ville Nouvelle',
    description: 'A sleek, contemporary, and bustling local cafe popular with young crowds and families. Serves excellent Italian espresso, freshly squeezed juices, light pastas, and crispy pizzas.',
    pricePerPerson: 7,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'brunch', 'flexible'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Family Friendly'],
    foodStyles: ['Italian', 'Mediterranean', 'Cafe'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '07:00',
    closeTime: '23:30',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 480,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 480,
    theforkRating: 4.1,
    theforkReviewCount: 480,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 480,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Bella+Cita+Meknes',
    bestDishes: ['Margherita Pizza', 'Double Espresso', 'Gourmet Club Sandwich'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Excellent outdoor patio seating for morning coffee and people-watching.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'e-meknes-20',
    city: 'meknes',
    name: 'Le Stream',
    neighborhood: 'Hamria / Ville Nouvelle',
    description: 'An ultra-chic modern cafe-lounge featuring a clean industrial design. Beloved by the local youth and digital nomads for its artisan mocktails, premium burgers, and great Italian coffee.',
    pricePerPerson: 9,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'flexible'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Modern Fusion Dining'],
    foodStyles: ['Mediterranean', 'Italian', 'Cafe'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'friends', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '23:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 420,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 420,
    theforkRating: 4.3,
    theforkReviewCount: 420,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 420,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Le+Stream+Meknes',
    bestDishes: ['Gourmet Stream Burger', 'Choco-Fudge Frappuccino', 'Truffle Mushroom Pasta'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'It has a very modern, design-forward vibe with great laptop workspace setups and fantastic craft burgers.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  }
];