import type { EatListing } from '../types';

/**
 * EAT LISTING TEMPLATE
 * {
 *   id: 'e-[city]-[name]',
 *   city: '[city]',
 *   name: '[Name]',
 *   neighborhood: '[Neighborhood]',
 *   description: '[Long description]',
 *   pricePerPerson: [number],
 *   lifestyle: 'lean' | 'balanced' | 'premium',
 *   mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'latenight', 'afternoon-tea', 'flexible'],
 *   experienceTypes: ['Fine Dining' | 'Waterfront Dining' | 'Romantic Sunset' | 'Beachfront Dining' | 'Garden restaurant with live music' | 'Fountain courtyard' | 'French-Moroccan fusion' | 'Casual Italian Dining' | 'Family Pizza Night' | 'Spanish Beach Lounge' | 'Paella & Tapas' | 'Live Music Terrace' | 'Upscale Romantic Dining' | 'Fine Seafood' | 'Classic Royal Ambiance' | '24/7 Brasserie' | 'People Watching' | 'Bakery-Patisserie' | 'Traditional Breakfast Ritual' | 'Local Gathering Spot' | 'Fishing Harbor Dining' | 'Gourmet Seafood' | 'French-Italian Fusion' | 'Authentic Berber Feast' | 'Traditional Dining' | 'Cozy casual family-run Moroccan eatery' | 'Amazigh-inspired decor' | 'Beachfront Grill' | 'Casual Dining' | 'Sunset Views' | 'Wood-Fired Pizza' | 'Family Friendly' | 'Leafy Tennis Oasis' | 'Tranquil Dining' | 'Upscale Lounge' | 'Modern Fusion Dining' | 'Unverified'],
 *   foodStyles: ['French' | 'Moroccan' | 'Seafood' | 'Mediterranean' | 'European' | 'International' | 'Italian' | 'Pizza' | 'Spanish' | 'Berber' | 'Barbecue' | 'Middle Eastern' | 'Healthy' | 'Cafe' | 'Bakery' | 'Patisserie' | 'Gourmet' | 'Fast Food'],
 *   crowdLevel: 'bustling' | 'balanced' | 'quiet',
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *   hasEnglishStaff: true | false,
 *   hasFrenchStaff: true | false,
 *   hasDelivery: true | false,
 *   hasParking: true | false,
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearCenter: true | false,
 *   isVegetarianFriendly: true | false,
 *   isHalal: true | false,
 *   openTime: 'HH:mm',
 *   closeTime: 'HH:mm',
 *   badge: 'local-favorite' | 'splurge' | 'hidden-gem' | 'local',
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source
 *   // ═══════════════════════════════════════════════════
 *   // Search for real ratings from Google, TripAdvisor, TheFork, and RestaurantGuru.
 *   // If you cannot find a rating for a specific source, set it to the same value as
 *   // the closest available one so the code that calculates average ratings doesn't break.
 *   // Example: if no TripAdvisor rating found, set tripadvisorRating = googleRating
 *
 *   // Google Places rating
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *
 *   // TripAdvisor rating
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *
 *   // TheFork rating
 *   theforkRating: [4.x],
 *   theforkReviewCount: [number],
 *
 *   // RestaurantGuru rating
 *   restaurantguruRating: [4.x],
 *   restaurantguruReviewCount: [number],
 *
 *   // REMOVED: rating, reviewCount, ratingSource (old single-source fields)
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   fullMenu: { type: 'image' | 'text', content: 'https://...' },
 *   tip: '[Short tip]',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   reservationContact: '+212XXXXXXXXX',
 *   bestDishes: ['Dish 1', 'Dish 2'],
 *   alcoholPolicy: 'serves-alcohol' | 'dry',
 *   ramadanFriendly: 'serves-lunch' | 'special-ftour' | 'closed',
 *
 *   // ═══════════════════════════════════════════════════
 *   // NEW FIELDS — psychological UX optimization
 *   // ═══════════════════════════════════════════════════
 *
 *   bestTimeToVisit: 'Early evening around 18:30 for sunset' | 'Lunch around 13:00 for quiet' | 'Late evening after 20:00 for lively crowd' | 'Early morning for fresh baked goods' | 'Sunday morning for brunch peak',
 *   averageWaitMinutes: 0 | 5 | 10 | 15 | 20 | 30 | 45 | 60,
 *   seatingTypes: ['indoor'] | ['terrace'] | ['rooftop'] | ['garden'] | ['beachfront'] | ['indoor', 'terrace'] | ['indoor', 'garden'] | ['terrace', 'rooftop'],
 *   viewType: 'beach' | 'mountain' | 'city' | 'garden' | 'none',
 *   wiFi: true | false,
 *   airConditioning: true | false,
 *   wheelchairAccessible: true | false,
 *   website: 'https://...',
 *   instagram: '@handle' | 'https://instagram.com/...'
 * }
 */

export const merzougaEat: EatListing[] = [
  {
    id: 'e-merzouga-1',
    city: 'merzouga',
    name: 'Restaurant Cafe Nora',
    neighborhood: 'Khamlia Village',
    description: 'An iconic cultural stop in the Gnawa village of Khamlia. Renowned for serving the most authentic, slow-baked Medfouna (Berber pizza) while local Gnawa musicians play hypnotic traditional rhythms.',
    pricePerPerson: 8.5,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery', 'Live Music Terrace'],
    foodStyles: ['Moroccan', 'Berber'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly', 'large-groups'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:00',
    closeTime: '21:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 519,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 519,
    theforkRating: 4.7,
    theforkReviewCount: 519,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 519,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212667612191',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Nora+Khamlia+Merzouga',
    bestDishes: ['Medfouna (Berber Pizza)', 'Vegetarian Medfouna', 'Spiced Berber Mint Tea'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Everything is baked strictly to order in their traditional clay ovens, so expect a 30-40 minute wait. Sit back and enjoy the complimentary mint tea and live Gnawa music.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 30,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-merzouga-2',
    city: 'merzouga',
    name: 'Café Chez Ibrahim',
    neighborhood: 'Khamlia Village',
    description: 'A beautifully authentic roadside restaurant nestled at the gates of Khamlia. Offers a gorgeous sun-drenched terrace overlooking the black desert terrain, serving incredibly flavorful tagines and medfouna.',
    pricePerPerson: 7.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Traditional Dining', 'Sunset Views'],
    foodStyles: ['Moroccan', 'Berber'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '10:00',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.8,
    googleReviewCount: 282,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 282,
    theforkRating: 4.8,
    theforkReviewCount: 282,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 282,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Chez+Ibrahim+Khamlia',
    bestDishes: ['Charcoal Beef Brochettes', 'Eggplant Tapas', 'Berber Pizza'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'The lamb kefta brochettes and the vegetable tajine cooked over slow charcoal embers are highly recommended.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'mountain',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-merzouga-3',
    city: 'merzouga',
    name: 'Sahara Time',
    neighborhood: 'Hassi Labied',
    description: 'A magical desert dining oasis set under large traditional tents at the very edge of the towering Erg Chebbi dunes. Managed by Youssef, a warm host who invites guests to relax and savor slow-cooked Moroccan stews.',
    pricePerPerson: 11,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Romantic Sunset', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Berber'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:00',
    closeTime: '23:00',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 190,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 190,
    theforkRating: 4.7,
    theforkReviewCount: 190,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 190,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Sahara+Time+Hassi+Labied',
    bestDishes: ['Slow-Cooked Lemon Chicken Tajine', 'Traditional Harira Soup', 'Nomad Lamb Skewers'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Book a dinner reservation to watch the stars light up over the dunes while enjoying a warm bowl of spiced Harira.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'mountain',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-merzouga-4',
    city: 'merzouga',
    name: 'Snack Mustapha',
    neighborhood: 'Merzouga Center',
    description: 'The go-to local budget spot in Merzouga village. Unpretentious and bustling, Snack Mustapha serves up quick, freshly seared meat sandwiches, loaded fries, and simple tagines to hungry travelers and locals.',
    pricePerPerson: 4,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Casual Dining', 'Quick Bites', 'Local Gathering Spot'],
    foodStyles: ['Moroccan', 'Fast Food'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends', 'kids-friendly'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:00',
    closeTime: '01:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 150,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 150,
    theforkRating: 4.4,
    theforkReviewCount: 150,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 150,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Snack+Mustapha+Merzouga',
    bestDishes: ['Spiced Kofta Sandwich', 'Merguez Brochettes', 'Loaded French Fries'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Order the spiced kofta sandwich with frites inside—an absolute local classic and incredibly cheap.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-merzouga-5',
    city: 'merzouga',
    name: 'Restaurant Cafe Fatima',
    neighborhood: 'Hassi Labied',
    description: 'A beloved family-owned culinary landmark operating for over 15 years in the quiet Hassi Labied village. Famed for serving exceptionally rich, homestyle tagines simmered on clay coal burners.',
    pricePerPerson: 8,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Berber'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:30',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 310,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 310,
    theforkRating: 4.7,
    theforkReviewCount: 310,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 310,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Cafe+Fatima+Hassi+Labied',
    bestDishes: ['Beef Tagine with Plums', 'Friday Seven-Vegetable Couscous', 'Warm Moroccan Salads'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Try the beef tagine with plums and boiled eggs—Fatima\'s traditional spice blend makes it one of the best in the Sahara.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-merzouga-6',
    city: 'merzouga',
    name: 'Café Restaurant Alla',
    neighborhood: 'Khamlia Village',
    description: 'A warm and vibrant hub in Khamlia village. Alla and his family welcome guests onto a lovely shaded terrace for freshly prepared Moroccan salad, authentic Berber pizza, and traditional tea ceremonies.',
    pricePerPerson: 7,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'brunch'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery', 'Cafe'],
    foodStyles: ['Moroccan', 'Berber'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '10:00',
    closeTime: '21:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.9,
    googleReviewCount: 185,
    tripadvisorRating: 4.9,
    tripadvisorReviewCount: 185,
    theforkRating: 4.9,
    theforkReviewCount: 185,
    restaurantguruRating: 4.9,
    restaurantguruReviewCount: 185,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Restaurant+Alla+Khamlia',
    bestDishes: ['Berber Pizza (Medfouna)', 'Spiced Eggplant Dip', 'Slow-cooked Berber Tagine'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Ask Alla for a quick tour to learn how they bake the Berber pizza on hot stones under the sand.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-merzouga-7',
    city: 'merzouga',
    name: 'Restaurant Zafa',
    neighborhood: 'Merzouga / Taouz Road',
    description: 'Operating since 2007, Zaid and his wife Fatima invite guests to dine directly inside their lovely family home. Experience deeply personal Berber hospitality and slow-cooked desert specialties.',
    pricePerPerson: 9,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Berber'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:00',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.8,
    googleReviewCount: 110,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 110,
    theforkRating: 4.8,
    theforkReviewCount: 110,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 110,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Zafa+Merzouga',
    bestDishes: ['Fatima\'s Spiced Chicken Tagine', 'Zaza Dessert (Avocado & Fruits)', 'Saffron Beef Tajine'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Since everything is made completely from scratch inside their family kitchen, booking a few hours in advance is highly recommended.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 0,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-merzouga-8',
    city: 'merzouga',
    name: 'Cafe Hamid',
    neighborhood: 'Hassi Labied',
    description: 'A highly popular local snack counter in Hassi Labied. Celebrated for its ultra-fast service, incredible kofta wraps, and satisfying daily portions of Moroccan lentil soup.',
    pricePerPerson: 4.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Casual Dining', 'Quick Bites', 'Local Gathering Spot'],
    foodStyles: ['Moroccan', 'Fast Food'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:00',
    closeTime: '23:30',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 5.0,
    googleReviewCount: 279,
    tripadvisorRating: 5.0,
    tripadvisorReviewCount: 279,
    theforkRating: 5.0,
    theforkReviewCount: 279,
    restaurantguruRating: 5.0,
    restaurantguruReviewCount: 279,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Hamid+Hassi+Labied',
    bestDishes: ['Hamid\'s Kofta Sandwich', 'Spiced Merguez Wrap', 'Lentil Soup (Loubia)'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Hamid\'s seasoned kofta is charred to perfection over a charcoal grill. Simply the best quick bite after a dune excursion.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-merzouga-9',
    city: 'merzouga',
    name: 'Kanz Erremal Restaurant',
    neighborhood: 'Erg Chebbi Dunes',
    description: 'An elegant hotel dining room housed in a gorgeous Kasbah structure built directly on the sand dunes. Features panoramic pool and dune views, specializing in high-end desert dining and interactive culinary workshops.',
    pricePerPerson: 22,
    lifestyle: 'premium',
    mealTypes: ['breakfast', 'lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Sunset Views', 'Traditional Dining'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Gourmet'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'seniors', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '23:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 380,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 380,
    theforkRating: 4.5,
    theforkReviewCount: 380,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 380,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    googleMapsUrl: 'https://maps.google.com/?q=Kanz+Erremal+Hotel+Merzouga',
    bestDishes: ['Slow-Braised Saffron Lamb Shank', 'Hands-on baked Berber Pizza', 'Cinnamon Orange Salad'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'They host highly rated, immersive workshops where you learn to mix and bake traditional Medfouna yourself in a wood-fired oven.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'mountain',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'e-merzouga-10',
    city: 'merzouga',
    name: 'Restaurant Chez Youssef',
    neighborhood: 'Merzouga Center',
    description: 'Nestled right in the heart of Merzouga village, this charming, highly welcoming restaurant is heavily favored by desert guides and travelers for its exceptionally crispy, wood-fired medfouna.',
    pricePerPerson: 7.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Berber'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:00',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 190,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 190,
    theforkRating: 4.6,
    theforkReviewCount: 190,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 190,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Restaurant+Chez+Youssef+Merzouga',
    bestDishes: ['Youssef\'s Classic Medfouna', 'Chicken and Olive Tagine', 'Fresh Mint Tea'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Youssef is an outstanding host. His special Berber pizza is packed with hard-boiled eggs, almonds, and perfectly spiced minced lamb.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-merzouga-11',
    city: 'merzouga',
    name: 'Cafe Chez Marrakesh',
    neighborhood: 'Merzouga Village',
    description: 'A cozy local café-restaurant with traditional earthen architecture. Loved for its incredibly juicy, slow-cooked tagines, fresh local yogurts, and highly relaxed atmosphere.',
    pricePerPerson: 6.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'flexible'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Traditional Dining'],
    foodStyles: ['Moroccan', 'Cafe'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.9,
    googleReviewCount: 147,
    tripadvisorRating: 4.9,
    tripadvisorReviewCount: 147,
    theforkRating: 4.9,
    theforkReviewCount: 147,
    restaurantguruRating: 4.9,
    restaurantguruReviewCount: 147,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Chez+Marrakesh+Merzouga',
    bestDishes: ['Berber Breakfast Board', 'Lemon Chicken Tagine', 'Creamy Local Desert Yogurt'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Highly recommended for an authentic, leisurely Berber breakfast featuring warm khobz, olive oil, honey, and fresh goat cheese.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-merzouga-12',
    city: 'merzouga',
    name: 'Restaurant Tifawt',
    neighborhood: 'Merzouga Village',
    description: 'Featuring a magnificent raised terrace with views of the approaching dunes, Tifawt serves massive, wonderfully balanced clay-pot tagines and vibrant Moroccan cooked salad platters.',
    pricePerPerson: 9,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Sunset Views', 'Traditional Dining'],
    foodStyles: ['Moroccan', 'Berber'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 320,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 320,
    theforkRating: 4.5,
    theforkReviewCount: 320,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 320,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Tifawt+Merzouga',
    bestDishes: ['Beef Tagine with Prunes & Almonds', 'Spiced Tomato Kefta Tagine', 'Traditional Moroccan Salad Medley'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Sit on the upper terrace at sunset. Their slow-cooked beef tagine with caramelized prunes is exceptionally tender.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'mountain',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-merzouga-13',
    city: 'merzouga',
    name: 'Restaurant Chez Ibrahim',
    neighborhood: 'Khamlia Village',
    description: 'Positioned right on the main Taouz highway, this traditional roadside rest stop features a lovely cool interior and sunny terrace. Serves exceptionally fresh, homestyle tagines to travelers.',
    pricePerPerson: 8,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Berber'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '10:00',
    closeTime: '22:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.8,
    googleReviewCount: 190,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 190,
    theforkRating: 4.8,
    theforkReviewCount: 190,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 190,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Chez+Ibrahim+Khamlia',
    bestDishes: ['Slow-simmered Lamb Tagine', 'Berber Pizza (Medfouna)', 'Fresh Fruit Platters'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Perfect pitstop during a 4x4 desert excursion. They have a lovely, shaded garden patio to cool off from the Saharan heat.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-merzouga-14',
    city: 'merzouga',
    name: 'Sahara Stars Camp Restaurant',
    neighborhood: 'Erg Chebbi Dunes',
    description: 'An ultra-luxurious camp dining experience deep in the dunes of Erg Chebbi. Guests dine on premium, chef-elevated Moroccan gastronomy under a canopy of Saharan stars, accompanied by local drumming.',
    pricePerPerson: 35,
    lifestyle: 'premium',
    mealTypes: ['breakfast', 'dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Traditional Dining'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Gourmet'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'large-groups'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '18:30',
    closeTime: '23:30',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.9,
    googleReviewCount: 95,
    tripadvisorRating: 4.9,
    tripadvisorReviewCount: 95,
    theforkRating: 4.9,
    theforkReviewCount: 95,
    restaurantguruRating: 4.9,
    restaurantguruReviewCount: 95,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    googleMapsUrl: 'https://maps.google.com/?q=Sahara+Stars+Camp+Merzouga',
    bestDishes: ['Slow-Roasted Lamb Mechoui', 'Chef\'s Special Saffron Tagine', 'Decadent Pistachio Baklava'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Booking is strictly required. The dinner package typically includes private 4x4 transport into the dunes and a traditional campfire drum circle.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 0,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'mountain',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-merzouga-15',
    city: 'merzouga',
    name: 'Dar Aytma Restaurant',
    neighborhood: 'Khamlia Area',
    description: 'A gorgeous, rustic Kasbah-style restaurant highly praised by food documentarians. Specializes in ancient traditional clay-pot techniques, utilizing organic local ingredients to present raw desert flavors.',
    pricePerPerson: 13,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Berber'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:30',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.8,
    googleReviewCount: 120,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 120,
    theforkRating: 4.8,
    theforkReviewCount: 120,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 120,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Dar+Aytma+Restaurant+Merzouga',
    bestDishes: ['Slow-baked Chicken with Local Dates', 'Traditional Berber Flatbread', 'Handmade Harissa Salads'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Famous for its preservation of rare pre-Saharan recipes. Try their slow-baked chicken with dates and walnuts.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'mountain',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-merzouga-16',
    city: 'merzouga',
    name: 'Café Restaurant Tenere',
    neighborhood: 'Hassi Labied',
    description: 'A lovely, highly laid-back desert cafe featuring a beautiful terrace overlooking the local palmeraie. Serves freshly-pressed Saharan juices, tasty light lunches, and classic Italian espresso.',
    pricePerPerson: 6.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'brunch', 'flexible'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Tranquil Dining'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Cafe'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 160,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 160,
    theforkRating: 4.4,
    theforkReviewCount: 160,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 160,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Restaurant+Tenere+Hassi+Labied',
    bestDishes: ['Fresh Pomegranate Mocktail', 'Club Sandwich with Local Fries', 'Berber Pizza'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'The perfect spot to cool down under their misting fans while sipping on a fresh pomegranate juice after camel trekking.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-merzouga-17',
    city: 'merzouga',
    name: 'Faran B\'Lal',
    neighborhood: 'Rissani',
    description: 'The most historic, highly famous communal mud bakery ("faran") in nearby Rissani. While technically in Rissani, it is the key food pilgrimage stop for Merzouga travelers wanting to see how medfouna is baked in ancient wood-fired ovens.',
    pricePerPerson: 4,
    lifestyle: 'lean',
    mealTypes: ['lunch'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Berber'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: false,
    isHalal: true,
    openTime: '08:00',
    closeTime: '15:00',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.9,
    googleReviewCount: 95,
    tripadvisorRating: 4.9,
    tripadvisorReviewCount: 95,
    theforkRating: 4.9,
    theforkReviewCount: 95,
    restaurantguruRating: 4.9,
    restaurantguruReviewCount: 95,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Faran+BLal+Rissani',
    bestDishes: ['Traditional Stuffed Medfouna with Almonds', 'Freshly baked Khobz', 'Local Mint Tea'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'This is a working communal bakery. You can buy fresh medfouna directly from them, or watch local families bring their custom-made flatbreads to be baked in the historic clay pit.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-merzouga-18',
    city: 'merzouga',
    name: 'Auberge Haven La Chance Restaurant',
    neighborhood: 'Hassi Labied',
    description: 'Located inside the famed haven, this laid-back desert resort restaurant is ideal for relaxed poolside lunches. Serves fresh Moroccan salads, juicy brochettes, and healthy organic juices directly facing the dunes.',
    pricePerPerson: 12,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch'],
    experienceTypes: ['Casual Dining', 'Sunset Views', 'Family Friendly'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Healthy'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '07:30',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 240,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 240,
    theforkRating: 4.6,
    theforkReviewCount: 240,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 240,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Haven+La+Chance+Merzouga',
    bestDishes: ['Grilled Lamb Skewers', 'Mixed Moroccan Mezze Plate', 'Freshly Squeezed Orange Juice'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Perfect for travelers seeking a modern, comfortable resort meal. Guests can use the lovely swimming pool for a small fee.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'mountain',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'e-merzouga-19',
    city: 'merzouga',
    name: 'Ksar Bicha Restaurant',
    neighborhood: 'Merzouga Village',
    description: 'A highly refined traditional dining room set inside the beautiful Ksar Bicha. Offers refined, slow-cooked Saharan cuisine with beef, figs, and sesame seeds served in a stylish, mud-brick architectural lounge.',
    pricePerPerson: 14,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Traditional Dining', 'Upscale Lounge'],
    foodStyles: ['Moroccan', 'Gourmet'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'seniors', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 180,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 180,
    theforkRating: 4.5,
    theforkReviewCount: 180,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 180,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Ksar+Bicha+Merzouga',
    bestDishes: ['Slow-cooked Beef Tagine with Figs', 'Moroccan Pastilla', 'Harira Soup'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Perfect for a quiet, incredibly comfortable traditional dinner. Their beef tagine with local desert figs is outstanding.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'e-merzouga-20',
    city: 'merzouga',
    name: 'Snack Milano',
    neighborhood: 'Merzouga Center',
    description: 'A highly bustling, extremely budget-friendly diner right in Merzouga village. Serving quick personal-sized pizzas, stuffed paninis, and hot Moroccan mint tea to active backpackers and locals.',
    pricePerPerson: 3.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Casual Dining', 'Quick Bites', 'Local Gathering Spot'],
    foodStyles: ['Moroccan', 'Italian', 'Fast Food'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:00',
    closeTime: '01:30',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 95,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 95,
    theforkRating: 4.2,
    theforkReviewCount: 95,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 95,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Snack+Milano+Merzouga',
    bestDishes: ['Saharan Beef Pizza', 'Merguez Panini', 'Fries with Garlic Sauce'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'The cheapest place in Merzouga for a quick, comforting pizza or panini. Great and friendly local service.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  }
];