import type { EatListing } from '../types';

export const merzougaEat: EatListing[] = [
  {
    id: 'e-merzouga-1',
    city: 'merzouga',
    name: 'Restaurant Cafe Nora',
    neighborhood: 'Khamlia Village',
    description: 'An iconic cultural stop in the Gnawa village of Khamlia. Renowned for serving the most authentic, slow-baked Medfouna (Berber pizza) while local Gnawa musicians play hypnotic traditional rhythms.',
    pricePerPerson: 8.5,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery', 'Live Music Terrace'],
    foodStyles: ['Moroccan', 'Berber'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'cafe-pastry'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly', 'large-groups'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '09:00',
    closeTime: '20:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 1156,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 450,
    theforkRating: 4.6,
    theforkReviewCount: 60,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 1200,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212667612191',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Nora+Khamlia+Merzouga',
    bestDishes: ['Medfouna (Berber Pizza)', 'Vegetarian Medfouna', 'Spiced Berber Mint Tea'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Everything is baked strictly to order in their traditional clay ovens, so expect a 30-40 minute wait. Relax and enjoy the complimentary mint tea and live Gnawa percussion while it bakes.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 30,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["budget", "cafe-pastry", "dinner", "dry", "live-music", "terrace"]
  },

  {
    id: 'e-merzouga-2',
    city: 'merzouga',
    name: 'Café Restaurant Chez Ibrahim',
    neighborhood: 'Khamlia Village',
    description: 'An authentic roadside restaurant situated at Kser El Khamlia on the Taouz road. Offers a sun-drenched terrace overlooking the desert plains, serving rich aubergine tagines, charcoal brochettes, and freshly baked medfouna.',
    pricePerPerson: 7.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Traditional Dining', 'Sunset Views'],
    foodStyles: ['Moroccan', 'Berber'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'cafe-pastry'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '10:00',
    closeTime: '21:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 289,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 85,
    theforkRating: 4.7,
    theforkReviewCount: 25,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 290,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212666147161',
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Chez+Ibrahim+Khamlia',
    bestDishes: ['Eggplant and Cheese Tagine', 'Berber Pizza (Medfouna)', 'Charcoal Kefta Brochettes'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Their set lunch menu includes cooked Moroccan vegetable salads, an aubergine tajine, freshly baked medfouna, and fresh fruit for dessert.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'mountain',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["budget", "cafe-pastry", "dinner", "dry", "mountain", "sunset", "tagine", "terrace", "wifi"]
  },

  {
    id: 'e-merzouga-3',
    city: 'merzouga',
    name: 'Café Restaurant SaharaTime',
    neighborhood: 'Hassi Labied',
    description: 'A desert dining oasis set under traditional nomad tenting directly at the edge of the Erg Chebbi sand dunes. Managed by Youssef, welcoming guests to savor wood-fired slow-simmered Moroccan stews with dune views.',
    pricePerPerson: 11,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Romantic Sunset', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Berber'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'cafe-pastry'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '09:00',
    closeTime: '22:30',
    badge: 'hidden-gem',

    // ── RATINGS ──
    googleRating: 4.9,
    googleReviewCount: 313,
    tripadvisorRating: 4.9,
    tripadvisorReviewCount: 90,
    theforkRating: 4.8,
    theforkReviewCount: 20,
    restaurantguruRating: 4.9,
    restaurantguruReviewCount: 313,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212673239229',
    googleMapsUrl: 'https://maps.google.com/?q=Sahara+Time+Hassi+Labied',
    bestDishes: ['Slow-Cooked Lemon Chicken Tagine', 'Smoky Meat Tagine on Wood Embers', 'Traditional Harira Soup'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Book a sunset dinner to watch the dunes change colors from golden to deep red, followed by campfire tea under the starry desert sky.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'mountain',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["budget", "cafe-pastry", "dinner", "dry", "mountain", "sunset", "tagine"]
  },

  {
    id: 'e-merzouga-4',
    city: 'merzouga',
    name: 'Snack Mustapha',
    neighborhood: 'Merzouga Center',
    description: 'The go-to local budget counter in Merzouga village. Unpretentious and bustling, Snack Mustapha serves quick, freshly seared meat sandwiches, loaded fries, and simple tagines to hungry travelers and desert guides.',
    pricePerPerson: 4,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Casual Dining', 'Local Gathering Spot'],
    foodStyles: ['Moroccan', 'Fast Food'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends', 'kids-friendly'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '11:00',
    closeTime: '01:00',
    badge: 'local',

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 121,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 30,
    theforkRating: 4.5,
    theforkReviewCount: 15,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 121,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Snack+Mustapha+Merzouga',
    bestDishes: ['Spiced Kefta Sandwich with Fries', 'Grilled Merguez Brochettes', 'Berber Omelet'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Order the spiced kefta sandwich with frites tucked inside the crusty khobz—an authentic local staple that costs next to nothing.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["budget", "dinner", "dry", "late-night", "street-food", "tagine"]
  },

  {
    id: 'e-merzouga-5',
    city: 'merzouga',
    name: 'Restaurant Cafe Fatima',
    neighborhood: 'Hassi Labied',
    description: 'A family-owned culinary landmark operating for years in quiet Hassi Labied village. Famed for exceptionally rich, homestyle tagines simmered slowly over clay coal burners and served on a scenic roof terrace.',
    pricePerPerson: 8,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery', 'Sunset Views'],
    foodStyles: ['Moroccan', 'Berber'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'cafe-pastry'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '11:30',
    closeTime: '22:30',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 278,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 263,
    theforkRating: 4.6,
    theforkReviewCount: 40,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 581,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Cafe+Fatima+Hassi+Labied',
    bestDishes: ['Beef Tagine with Prunes & Boiled Eggs', 'Tajine Galia', 'Friday Seven-Vegetable Couscous'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Head upstairs to the roof terrace for lovely dune views while eating. The set menu includes complimentary harira soup, olives, and mint tea.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'mountain',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["budget", "cafe-pastry", "couscous", "dinner", "dry", "mountain", "sunset", "tagine", "terrace"]
  },

  {
    id: 'e-merzouga-6',
    city: 'merzouga',
    name: 'Café Restaurant Alla',
    neighborhood: 'Khamlia Village',
    description: 'A welcoming culinary stop in Khamlia village. Alla and his family greet travelers into a lovely shaded desert courtyard for fresh Moroccan salads, authentic stone-baked Berber pizza, and tea ceremonies.',
    pricePerPerson: 7,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'brunch'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery', 'Casual Dining'],
    foodStyles: ['Moroccan', 'Berber'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'cafe-pastry'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '08:00',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.9,
    googleReviewCount: 172,
    tripadvisorRating: 4.9,
    tripadvisorReviewCount: 45,
    theforkRating: 4.8,
    theforkReviewCount: 15,
    restaurantguruRating: 4.9,
    restaurantguruReviewCount: 175,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    reservationContact: '+212611094484',
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Restaurant+Alla+Khamlia',
    bestDishes: ['Authentic Medfouna (Berber Pizza)', 'Cooked Moroccan Tomato & Pepper Salad', 'Fresh Mint Tea'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Located just off the main road down a sandy track. Medfouna is baked completely fresh to order (takes ~45 mins) and easily feeds two hungry adults.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 20,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dinner", "dry", "terrace", "wifi"]
  },

  {
    id: 'e-merzouga-7',
    city: 'merzouga',
    name: 'Restaurant Zafa',
    neighborhood: 'Merzouga / Taouz Road',
    description: 'Operating since 2007, Zaid and his wife Fatima invite guests to dine directly inside their decorated roadside family home. Offers deeply personal Berber hospitality and slow-simmered desert recipes.',
    pricePerPerson: 9,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Berber'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '12:00',
    closeTime: '22:00',
    badge: 'hidden-gem',

    // ── RATINGS ──
    googleRating: 4.8,
    googleReviewCount: 110,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 40,
    theforkRating: 4.7,
    theforkReviewCount: 10,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 110,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Zafa+Merzouga',
    bestDishes: ['Fatima’s Spiced Chicken Tagine', 'Zaza Fruit Dessert with Avocado', 'Saffron Beef Tajine'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Since every meal is made from scratch in their family kitchen, calling ahead or dropping in earlier in the day to place your order ensures minimal waiting.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["budget", "dinner", "dry", "quiet", "tagine"]
  },

  {
    id: 'e-merzouga-8',
    city: 'merzouga',
    name: 'Cafe Snack Restaurant Hamid',
    neighborhood: 'Hassi Labied',
    description: 'An overwhelmingly popular culinary institution in Hassi Labied. Renowned for its extraordinarily kind owner Hamid, huge portions of fresh market salads, grilled brochettes, tacos, and slow-cooked tagines.',
    pricePerPerson: 5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Casual Dining', 'Cozy casual family-run Moroccan eatery', 'Local Gathering Spot'],
    foodStyles: ['Moroccan', 'Fast Food', 'Berber'],
    // food-cuisine quiz question tags
    cuisineTags: ['cafe-pastry', 'moroccan-traditional'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '08:00',
    closeTime: '22:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.9,
    googleReviewCount: 1471,
    tripadvisorRating: 5.0,
    tripadvisorReviewCount: 420,
    theforkRating: 4.9,
    theforkReviewCount: 80,
    restaurantguruRating: 4.9,
    restaurantguruReviewCount: 1500,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    reservationContact: '+212667069078',
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Hamid+Hassi+Labied',
    bestDishes: ['Kefta Tagine with Egg and Cheese', 'House Spiced Chicken Tacos', 'Fresh Moroccan Salad Platter'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'One of the highest-rated eateries in the region. Hamid speaks multiple languages and often prepares takeout meals early in the morning for travelers departing toward Fes.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["budget", "cafe-pastry", "dinner", "dry", "street-food", "tagine", "wifi"]
  },

  {
    id: 'e-merzouga-9',
    city: 'merzouga',
    name: 'Kanz Erremal Restaurant',
    neighborhood: 'Erg Chebbi Dunes',
    description: 'An elegant hotel dining room housed in a traditional Kasbah structure built right against the foot of the Erg Chebbi dunes. Features panoramic pool and dune views, offering refined Moroccan cuisine and wine.',
    pricePerPerson: 22,
    lifestyle: 'premium',
    mealTypes: ['breakfast', 'lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Sunset Views', 'Traditional Dining'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Gourmet'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'seniors', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    openTime: '08:00',
    closeTime: '23:00',
    badge: 'splurge',

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 450,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 280,
    theforkRating: 4.2,
    theforkReviewCount: 40,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 450,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212535578482',
    googleMapsUrl: 'https://maps.google.com/?q=Kanz+Erremal+Hotel+Merzouga',
    bestDishes: ['Slow-Braised Saffron Lamb Shank', 'Assorted Couscous with Vegetables', 'Moroccan Pastry Assortment'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'One of the few dining rooms right on the dunes that serves wine and cold beer. Relax on the terrace beside the pool overlooking Erg Chebbi.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'mountain',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["alcohol", "breakfast", "budget", "couscous", "dinner", "fine", "mountain", "sunset", "terrace", "wifi"]
  },

  {
    id: 'e-merzouga-10',
    city: 'merzouga',
    name: 'Cafe Restaurant Chez Youssef',
    neighborhood: 'Merzouga Center',
    description: 'Located in the heart of Merzouga village, this welcoming family eatery is favored by local desert guides and independent travelers for its crispy wood-fired medfouna and hearty tagines.',
    pricePerPerson: 7.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Berber'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'cafe-pastry'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '11:00',
    closeTime: '22:30',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 157,
    tripadvisorRating: 4.9,
    tripadvisorReviewCount: 220,
    theforkRating: 4.7,
    theforkReviewCount: 30,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 180,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212666367174',
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Restaurant+Chez+Youssef+Merzouga',
    bestDishes: ['Youssef’s Classic Medfouna', 'Chicken and Green Olive Tagine', 'Berber Omelet with Cumin'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Youssef is an attentive host. His stuffed Berber flatbread is filled with minced meat, hard-boiled eggs, almonds, and traditional Saharan spices.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  ,
    tags: ["budget", "cafe-pastry", "dinner", "dry", "tagine", "wifi"]
  },

  {
    id: 'e-merzouga-11',
    city: 'merzouga',
    name: 'Cafe Chez Marrakesh',
    neighborhood: 'Merzouga Village',
    description: 'A cozy local cafe-restaurant featuring traditional earthen decor. Known for its slow-cooked tagines, Moroccan breakfast sets, and relaxed village setting.',
    pricePerPerson: 6.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'flexible'],
    experienceTypes: ['Traditional Dining', 'Casual Dining'],
    foodStyles: ['Moroccan', 'Cafe'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'cafe-pastry'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '08:00',
    closeTime: '22:30',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 110,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 40,
    theforkRating: 4.5,
    theforkReviewCount: 15,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 110,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Chez+Marrakesh+Merzouga',
    bestDishes: ['Berber Breakfast Board', 'Lemon Chicken Tagine', 'Fresh Squeezed Orange Juice'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'A great morning spot for a classic Moroccan breakfast with warm flatbread, olive oil, honey, and mint tea.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dinner", "dry", "juice", "tagine"]
  },

  {
    id: 'e-merzouga-12',
    city: 'merzouga',
    name: 'Restaurant Tifawt',
    neighborhood: 'Merzouga Village',
    description: 'Featuring a raised terrace with direct sightlines to the dunes, Tifawt serves generous clay-pot tagines, skewers, and vibrant cooked Moroccan salads at very reasonable prices.',
    pricePerPerson: 8,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Sunset Views', 'Traditional Dining'],
    foodStyles: ['Moroccan', 'Berber'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '11:00',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 180,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 35,
    theforkRating: 4.2,
    theforkReviewCount: 15,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 180,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Tifawt+Merzouga',
    bestDishes: ['Beef Tagine with Prunes & Almonds', 'Spiced Kefta Tagine', 'Moroccan Salad Medley'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Take a table on the upper terrace around sunset to take in the desert colors while waiting for your tagine.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'mountain',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["budget", "dinner", "dry", "mountain", "sunset", "tagine", "terrace"]
  },

  {
    id: 'e-merzouga-13',
    city: 'merzouga',
    name: 'Restaurant Hassilabiad Appart Chez Toupie',
    neighborhood: 'Hassi Labied',
    description: 'A top-rated dining retreat in Hassi Labied run by a welcoming family. Serves generous, freshly cooked Berber feasts, tagines, and salads in modern indoor salons or beside their courtyard pool.',
    pricePerPerson: 10,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery', 'Family Friendly'],
    foodStyles: ['Moroccan', 'Mediterranean'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '08:00',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.9,
    googleReviewCount: 591,
    tripadvisorRating: 5.0,
    tripadvisorReviewCount: 157,
    theforkRating: 4.9,
    theforkReviewCount: 50,
    restaurantguruRating: 4.9,
    restaurantguruReviewCount: 736,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212624422542',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Hassilabiad+Appart+Chez+Toupie',
    bestDishes: ['Moroccan Lemon Chicken', 'Traditional Beef Tajine', 'Fresh Fruit Parfait'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'A hidden gem in Hassi Labied. The family also operates the adjacent Depot Nomad carpet gallery. Excellent service in fluent English.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["budget", "dinner", "dry", "tagine", "terrace", "wifi"]
  },

  {
    id: 'e-merzouga-14',
    city: 'merzouga',
    name: 'Sahara Stars Camp Restaurant',
    neighborhood: 'Erg Chebbi Dunes',
    description: 'A luxury camp dining experience deep in the dunes of Erg Chebbi. Guests dine on multi-course Moroccan cuisine under a canopy of Saharan stars, accompanied by campfire Gnawa drumming.',
    pricePerPerson: 35,
    lifestyle: 'premium',
    mealTypes: ['breakfast', 'dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Traditional Dining'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Gourmet'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'large-groups'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    openTime: '18:30',
    closeTime: '23:30',
    badge: 'splurge',

    // ── RATINGS ──
    googleRating: 4.9,
    googleReviewCount: 95,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 40,
    theforkRating: 4.8,
    theforkReviewCount: 10,
    restaurantguruRating: 4.9,
    restaurantguruReviewCount: 95,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    googleMapsUrl: 'https://maps.google.com/?q=Sahara+Stars+Camp+Merzouga',
    bestDishes: ['Slow-Roasted Lamb Mechoui', 'Saffron Chicken Tagine', 'Pistachio Baklava'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Advance booking is required. Packages typically include 4x4 dune transit, candlelit tables under the stars, and campfire music.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 0,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'mountain',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["alcohol", "breakfast", "budget", "dinner", "fine", "live-music", "mountain", "quiet", "sunset", "tagine"]
  },

  {
    id: 'e-merzouga-15',
    city: 'merzouga',
    name: 'Dar Aytma Restaurant',
    neighborhood: 'Khamlia Village',
    description: 'A traditional Kasbah restaurant in Khamlia celebrated for preserving ancient clay-pot techniques and pre-Saharan recipes with local dates, nuts, and farm-fresh ingredients.',
    pricePerPerson: 13,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Berber'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '12:00',
    closeTime: '22:30',
    badge: 'hidden-gem',

    // ── RATINGS ──
    googleRating: 4.9,
    googleReviewCount: 282,
    tripadvisorRating: 5.0,
    tripadvisorReviewCount: 58,
    theforkRating: 4.9,
    theforkReviewCount: 20,
    restaurantguruRating: 4.9,
    restaurantguruReviewCount: 282,

    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Dar+Aytma+Restaurant+Merzouga',
    bestDishes: ['Slow-Baked Chicken with Desert Dates', 'Berber Pizza (Medfouna)', 'Handmade Harissa Salad'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Try their slow-baked chicken with dates and almonds—a rare authentic Saharan specialty prepared with local palm grove produce.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'mountain',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["budget", "dinner", "dry", "mountain", "quiet", "terrace"]
  },

  {
    id: 'e-merzouga-16',
    city: 'merzouga',
    name: 'Café Restaurant Tenere',
    neighborhood: 'Hassi Labied',
    description: 'A relaxed desert cafe and pizzeria featuring an open terrace with views of the palm groves. Serves freshly-pressed juices, pizzas, kebabs, and Italian coffees.',
    pricePerPerson: 6.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'brunch', 'flexible'],
    experienceTypes: ['Casual Dining', 'Tranquil Dining'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Pizza'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international', 'cafe-pastry'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '08:00',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 110,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 30,
    theforkRating: 4.0,
    theforkReviewCount: 10,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 110,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    reservationContact: '+212646037818',
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Restaurant+Tenere+Hassi+Labied',
    bestDishes: ['Thin-Crust Wood Pizza', 'Kefta Sandwich with Fries', 'Fresh Pomegranate Juice'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Great rooftop and terrace seating to relax with cold juice and pizza after camel riding through the dunes.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dry", "juice", "terrace", "wifi"]
  },

  {
    id: 'e-merzouga-17',
    city: 'merzouga',
    name: 'Faran B\'Lal',
    neighborhood: 'Rissani',
    description: 'A historic communal mud-brick bakery ("faran") in the ancient trading post of Rissani (birthplace of Medfouna). Visitors stop here during day tours to observe Berber pizzas baked on wood embers.',
    pricePerPerson: 4,
    lifestyle: 'lean',
    mealTypes: ['lunch'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Berber'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: false,
    isHalal: true,
    servesAlcohol: false,
    openTime: '08:00',
    closeTime: '15:00',
    badge: 'hidden-gem',

    // ── RATINGS ──
    googleRating: 4.8,
    googleReviewCount: 95,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 30,
    theforkRating: 4.7,
    theforkReviewCount: 10,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 95,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Faran+BLal+Rissani',
    bestDishes: ['Traditional Stuffed Medfouna with Almonds & Eggs', 'Wood-Fired Khobz', 'Local Mint Tea'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Located inside Rissani souk. Best visited on market days (Sunday, Tuesday, Thursday). Watch the baker shovel flatbreads directly into the wood-fired hearth.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["budget", "cafe-pastry", "dry", "medina", "pastry"]
  },

  {
    id: 'e-merzouga-18',
    city: 'merzouga',
    name: 'Auberge Haven La Chance Restaurant',
    neighborhood: 'Hassi Labied',
    description: 'Located inside Haven La Chance at the base of the dunes, this hotel restaurant offers relaxed poolside dining, Moroccan salads, juicy brochettes, and cold beer facing Erg Chebbi.',
    pricePerPerson: 12,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch'],
    experienceTypes: ['Casual Dining', 'Sunset Views', 'Family Friendly'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Healthy'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    openTime: '07:30',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 320,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 110,
    theforkRating: 4.2,
    theforkReviewCount: 25,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 320,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212535577299',
    googleMapsUrl: 'https://maps.google.com/?q=Haven+La+Chance+Merzouga',
    bestDishes: ['Grilled Lamb Skewers', 'Mixed Moroccan Mezze Plate', 'Fresh Squeezed Orange Juice'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'A licensed desert hotel where you can enjoy an evening beer or wine on the terrace while looking directly up at the sand dunes.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'mountain',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["alcohol", "breakfast", "budget", "dinner", "juice", "mountain", "sunset", "terrace", "wifi"]
  },

  {
    id: 'e-merzouga-19',
    city: 'merzouga',
    name: 'Ksar Bicha Restaurant',
    neighborhood: 'Merzouga Village',
    description: 'A traditional dining room and poolside lounge set inside the adobe-walled Ksar Bicha. Offers slow-cooked Saharan tagines, Moroccan salads, and licensed bar drinks in a mud-brick Kasbah lounge.',
    pricePerPerson: 14,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Traditional Dining', 'Upscale Lounge'],
    foodStyles: ['Moroccan', 'Gourmet'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'seniors', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '12:00',
    closeTime: '22:30',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 77,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 45,
    theforkRating: 4.3,
    theforkReviewCount: 15,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 77,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212535577113',
    googleMapsUrl: 'https://maps.google.com/?q=Ksar+Bicha+Merzouga',
    bestDishes: ['Slow-Cooked Beef Tagine with Figs', 'Chicken Pastilla with Almonds', 'Spiced Harira'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Features an outdoor pool and licensed bar/lounge. Ideal for a relaxing dinner with Moroccan wine away from the dust of the dunes.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  ,
    tags: ["alcohol", "budget", "dinner", "fine", "pastilla", "quiet", "tagine", "wifi"]
  },

  {
    id: 'e-merzouga-20',
    city: 'merzouga',
    name: 'Snack Milano',
    neighborhood: 'Merzouga Center',
    description: 'A budget-friendly village counter right in Merzouga center. Serves quick personal-sized pizzas, toasted paninis, and sweet mint tea to budget backpackers and locals.',
    pricePerPerson: 3.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Casual Dining', 'Local Gathering Spot'],
    foodStyles: ['Moroccan', 'Italian', 'Fast Food'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '11:00',
    closeTime: '01:30',
    badge: 'local',

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 35,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 15,
    theforkRating: 4.4,
    theforkReviewCount: 5,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 35,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Snack+Milano+Merzouga',
    bestDishes: ['Beef & Cheese Pizza', 'Merguez Panini', 'Fresh French Fries'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Unpretentious and very fast. Great spot for a quick late-night panini or pizza after returning from a desert excursion.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["budget", "dinner", "dry", "late-night", "street-food"]
  }
];