import type { EatListing } from '../types';

/**
 * EAT LISTING TEMPLATE
 * {
 *   id: 'e-[city]-[name]',
 *   city: '[city]',
 *   name: '[Name]',
 *   neighborhood: '[Neighborhood]',
 *   description: '[Long description]',
 *   pricePerPerson: [number],
 *   lifestyle: 'lean' | 'balanced' | 'premium',
 *   mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'latenight', 'afternoon-tea', 'flexible'],
 *   experienceTypes: ['Fine Dining' | 'Waterfront Dining' | 'Romantic Sunset' | 'Beachfront Dining' | 'Garden restaurant with live music' | 'Fountain courtyard' | 'French-Moroccan fusion' | 'Casual Italian Dining' | 'Family Pizza Night' | 'Spanish Beach Lounge' | 'Paella & Tapas' | 'Live Music Terrace' | 'Upscale Romantic Dining' | 'Fine Seafood' | 'Classic Royal Ambiance' | '24/7 Brasserie' | 'People Watching' | 'Bakery-Patisserie' | 'Traditional Breakfast Ritual' | 'Local Gathering Spot' | 'Fishing Harbor Dining' | 'Gourmet Seafood' | 'French-Italian Fusion' | 'Authentic Berber Feast' | 'Traditional Dining' | 'Cozy casual family-run Moroccan eatery' | 'Amazigh-inspired decor' | 'Beachfront Grill' | 'Casual Dining' | 'Sunset Views' | 'Wood-Fired Pizza' | 'Family Friendly' | 'Leafy Tennis Oasis' | 'Tranquil Dining' | 'Upscale Lounge' | 'Modern Fusion Dining' | 'Unverified'],
 *   foodStyles: ['French' | 'Moroccan' | 'Seafood' | 'Mediterranean' | 'European' | 'International' | 'Italian' | 'Pizza' | 'Spanish' | 'Berber' | 'Barbecue' | 'Middle Eastern' | 'Healthy' | 'Cafe' | 'Bakery' | 'Patisserie' | 'Gourmet' | 'Fast Food'],
 *   crowdLevel: 'bustling' | 'balanced' | 'quiet',
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *   hasEnglishStaff: true | false,
 *   hasFrenchStaff: true | false,
 *   hasDelivery: true | false,
 *   hasParking: true | false,
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearCenter: true | false,
 *   isVegetarianFriendly: true | false,
 *   isHalal: true | false,
 *   openTime: 'HH:mm',
 *   closeTime: 'HH:mm',
 *   badge: 'local-favorite' | 'splurge' | 'hidden-gem' | 'local',
 *
 *   // ═══════════════════════════════════════════════════
 *   // IMAGES — now fetched from Google Places API via googlePlaceId
 *   // ═══════════════════════════════════════════════════
 *   // REMOVED: images: ['url1', 'url2']
 *   // Instead, just add: // googlePlaceId: "ChIJ..."
 *   // Frontend uses googlePlaceId to call Google Places API → gets photo_reference → builds <img> URLs
 *
 *   // ═══════════════════════════════════════════════════
 *   // RATINGS — organized per source
 *   // ═══════════════════════════════════════════════════
 *   // Search for real ratings from Google, TripAdvisor, TheFork, and RestaurantGuru.
 *   // If you cannot find a rating for a specific source, set it to the same value as
 *   // the closest available one so the code that calculates average ratings doesn't break.
 *   // Example: if no TripAdvisor rating found, set tripadvisorRating = googleRating
 *
 *   // Google Places rating
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *
 *   // TripAdvisor rating
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *
 *   // TheFork rating
 *   theforkRating: [4.x],
 *   theforkReviewCount: [number],
 *
 *   // RestaurantGuru rating
 *   restaurantguruRating: [4.x],
 *   restaurantguruReviewCount: [number],
 *
 *   // REMOVED: rating, reviewCount, ratingSource (old single-source fields)
 *
 *   // ═══════════════════════════════════════════════════
 *
 *   fullMenu: { type: 'image' | 'text', content: 'https://...' },
 *   tip: '[Short tip]',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   reservationContact: '+212XXXXXXXXX',
 *   bestDishes: ['Dish 1', 'Dish 2'],
 *   alcoholPolicy: 'serves-alcohol' | 'dry',
 *   ramadanFriendly: 'serves-lunch' | 'special-ftour' | 'closed',
 *
 *   // ═══════════════════════════════════════════════════
 *   // NEW FIELDS — psychological UX optimization
 *   // ═══════════════════════════════════════════════════
 *
 *   bestTimeToVisit: 'Early evening around 18:30 for sunset' | 'Lunch around 13:00 for quiet' | 'Late evening after 20:00 for lively crowd' | 'Early morning for fresh baked goods' | 'Sunday morning for brunch peak',
 *   averageWaitMinutes: 0 | 5 | 10 | 15 | 20 | 30 | 45 | 60,
 *   seatingTypes: ['indoor'] | ['terrace'] | ['rooftop'] | ['garden'] | ['beachfront'] | ['indoor', 'terrace'] | ['indoor', 'garden'] | ['terrace', 'rooftop'],
 *   viewType: 'beach' | 'mountain' | 'city' | 'garden' | 'none',
 *   wiFi: true | false,
 *   airConditioning: true | false,
 *   wheelchairAccessible: true | false,
 *   website: 'https://...',
 *   instagram: '@handle' | 'https://instagram.com/...'
 * }
 */

export const ouarzazateEat: EatListing[] = [
  {
    id: 'e-ouarzazate-1',
    city: 'ouarzazate',
    name: 'La Kasbah des Sables',
    neighborhood: 'Ait Kdif',
    description: 'An extraordinary gourmet destination located in Ouarzazate\'s oldest neighborhood. Built like an opulent desert palace, it features six distinct dining salons, a central plunge pool, and intricate Amazigh craftsmanship.',
    pricePerPerson: 32,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Traditional Dining', 'Romantic Sunset'],
    foodStyles: ['Moroccan', 'French', 'Mediterranean', 'Gourmet'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'seniors', 'large-groups'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:30',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 573,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 573,
    theforkRating: 4.6,
    theforkReviewCount: 573,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 573,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212524885428',
    googleMapsUrl: 'https://maps.google.com/?q=La+Kasbah+des+Sables+Ouarzazate',
    bestDishes: ['Argan-infused Lamb Tagine', 'Saffron Sea Bass', 'Pastilla with Almond Milk'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Sit around the central pool in the evening. The candlelit atmosphere is spectacular, and the French owner, Brigitte, offers wonderful service.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'e-ouarzazate-2',
    city: 'ouarzazate',
    name: 'Chez Dimitri',
    neighborhood: 'Centre Ville',
    description: 'Ouarzazate\'s oldest and most legendary restaurant, operating since 1928. Originally a Foreign Legion post, it is decorated with decades of signed movie star photos, from Orson Welles and Ridley Scott to Michael Douglas.',
    pricePerPerson: 13,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Casual Dining', 'Traditional Dining', 'Local Gathering Spot'],
    foodStyles: ['Mediterranean', 'French', 'Moroccan', 'Italian'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:30',
    closeTime: '00:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.0,
    googleReviewCount: 275,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 275,
    theforkRating: 4.0,
    theforkReviewCount: 275,
    restaurantguruRating: 4.0,
    restaurantguruReviewCount: 275,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212524887346',
    googleMapsUrl: 'https://maps.google.com/?q=Chez+Dimitri+Ouarzazate',
    bestDishes: ['Classic French Steak Frites', 'Lamb Tagine with Prunes', 'Handmade Thin Crust Pizza'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Take some time to look at the vintage movie-set photos on the walls. It is a fantastic historical monument of the Moroccan film industry.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'e-ouarzazate-3',
    city: 'ouarzazate',
    name: 'Jardin des Arômes',
    neighborhood: 'Centre Ville',
    description: 'A stylish and highly refined French-Moroccan fusion restaurant. It offers an upscale dining experience with beautifully presented stews and modern steaks inside a chic Moroccan salon.',
    pricePerPerson: 21,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Upscale Lounge'],
    foodStyles: ['Moroccan', 'French', 'Mediterranean', 'Gourmet'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 680,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 680,
    theforkRating: 4.5,
    theforkReviewCount: 680,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 680,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    googleMapsUrl: 'https://maps.google.com/?q=Jardin+des+Aromes+Ouarzazate',
    bestDishes: ['Gourmet Chicken Pastilla', 'Slow-cooked Beef Tagine', 'Chocolate Fondant'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'One of the highest-end meals in the city center. Their modern chicken pastilla is outstanding.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'e-ouarzazate-4',
    city: 'ouarzazate',
    name: 'Le Relais de Saint-Exupéry',
    neighborhood: 'Centre Ville',
    description: 'A cozy and warm French bistro celebrating the famous writer-aviator Antoine de Saint-Exupéry. Managed by a Bordeaux chef, it serves classic French delicacies using highly demanding fresh local products.',
    pricePerPerson: 18,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Upscale Lounge'],
    foodStyles: ['French', 'Mediterranean', 'European'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'seniors', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 310,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 310,
    theforkRating: 4.4,
    theforkReviewCount: 310,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 310,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Le+Relais+de+Saint-Exupery+Ouarzazate',
    bestDishes: ['Bordeaux Style Roasted Beef', 'Fresh Herb Lemon Fish', 'Warm Apple Tarte Tatin'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Perfect for expats and travelers seeking top-tier French culinary craft in a warm, friendly setting.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'e-ouarzazate-5',
    city: 'ouarzazate',
    name: 'El Bahja',
    neighborhood: 'Douar Cheums',
    description: 'The ultimate, no-frills local canteen in Ouarzazate. Always humming with locals and desert drivers, it serves excellent charcoal-grilled meats, rotisserie chicken, and hot, spiced bean stews.',
    pricePerPerson: 4.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Casual Dining', 'Quick Bites', 'Local Gathering Spot'],
    foodStyles: ['Moroccan', 'Barbecue'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:00',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 950,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 950,
    theforkRating: 4.6,
    theforkReviewCount: 950,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 950,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Bahja+Ouarzazate',
    bestDishes: ['Mixed Grill Platter', 'Spiced Loubia (White Beans)', 'Rotisserie Chicken with Olives'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'closed',
    tip: 'Order their famous "loubia" (spiced white beans) to accompany your mixed charcoal meat plate. Very cheap and deeply satisfying.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-ouarzazate-6',
    city: 'ouarzazate',
    name: 'Restaurant Douyria',
    neighborhood: 'Centre Ville',
    description: 'A cozy traditional Moroccan restaurant featuring beautiful Berber carpets and a scenic rooftop terrace. Famously trusted for its Friday couscous and traditional clay-pot tagines.',
    pricePerPerson: 9.5,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Traditional Dining', 'Sunset Views'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:30',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 820,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 820,
    theforkRating: 4.4,
    theforkReviewCount: 820,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 820,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Douyria+Ouarzazate',
    bestDishes: ['Friday Seven-Vegetable Couscous', 'Lamb Tagine with Apricots', 'Traditional Harira Soup'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Excellent Friday couscous. Dine on the upper terrace for a relaxing, breezy view of the cityscape.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'rooftop'],
    viewType: 'city',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-ouarzazate-7',
    city: 'ouarzazate',
    name: 'The Full Sun',
    neighborhood: 'Zone Touristique',
    description: 'A contemporary, bright restaurant and café located in Ouarzazate\'s tourist zone near the Ibis Hotel. Offers fresh breakfasts, homemade pizzas, fresh salads to compile yourself, and stews.',
    pricePerPerson: 8.5,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'flexible'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Family Friendly'],
    foodStyles: ['Mediterranean', 'Italian', 'Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '07:30',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 290,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 290,
    theforkRating: 4.5,
    theforkReviewCount: 290,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 290,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+The+Full+Sun+Ouarzazate',
    bestDishes: ['Build-your-own Fresh Salad', 'Wood-fired Pizza Pepperoni', 'Chicken Tagine with Lemon'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Perfect place to fill up on vitamins and fresh continental breakfasts before heading deep into the desert.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'e-ouarzazate-8',
    city: 'ouarzazate',
    name: 'Dar Chamaa Restaurant',
    neighborhood: 'Zone Touristique',
    description: 'A beautiful guesthouse restaurant offering poolside dining surrounded by olive trees. Known for its quiet, romantic, and highly atmospheric evening dinners under the Saharan stars.',
    pricePerPerson: 18,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Garden restaurant with live music'],
    foodStyles: ['Moroccan', 'Mediterranean'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '22:30',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 310,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 310,
    theforkRating: 4.6,
    theforkReviewCount: 310,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 310,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    googleMapsUrl: 'https://maps.google.com/?q=Dar+Chamaa+Ouarzazate',
    bestDishes: ['Beef Tagine with Prunes', 'Organic Saffron Rice with Vegetables', 'Moroccan Pastry Sampler'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Dine by the pool in the evening. Their beef tagine with caramelized prunes and roasted almonds is exceptionally tender.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-ouarzazate-9',
    city: 'ouarzazate',
    name: 'Restaurant 3 Thés',
    neighborhood: 'Ait Kdif',
    description: 'A classic, traditional riad-style restaurant located near the Taourirt Kasbah. Features high-quality Moroccan salons and a panoramic terrace serving generous, authentic Moroccan set menus.',
    pricePerPerson: 11,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Sunset Views', 'Traditional Dining'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:30',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 520,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 520,
    theforkRating: 4.3,
    theforkReviewCount: 520,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 520,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+3+Thes+Ouarzazate',
    bestDishes: ['Berber Tagine with Vegetables', 'Chicken Pastilla', 'Assorted Moroccan Salads'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Sit on the upper roof terrace for beautiful views of the historic Kasbah Taourirt at sunset.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'rooftop'],
    viewType: 'city',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-ouarzazate-10',
    city: 'ouarzazate',
    name: 'Kasbah Tafarnout',
    neighborhood: 'Centre Ville',
    description: 'A highly popular modern bakery, pastry shop, and café. Famed among locals and travelers for freshly baked French pastries, traditional Moroccan cookies, and satisfying modern breakfast boards.',
    pricePerPerson: 5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'brunch', 'afternoon-tea', 'flexible'],
    experienceTypes: ['Cafe', 'Bakery-Patisserie', 'Casual Dining'],
    foodStyles: ['Bakery', 'French', 'Moroccan', 'Cafe'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '06:30',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 610,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 610,
    theforkRating: 4.3,
    theforkReviewCount: 610,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 610,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Kasbah+Tafarnout+Ouarzazate',
    bestDishes: ['Almond Croissant', 'Traditional Mint Tea with Cookies', 'Belgian Chocolate Waffle'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'The best spot in town to pick up traditional Moroccan cookies like Chebakia and Kaab el Ghazal, or grab a rapid espresso before visiting the studios.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },

  {
    id: 'e-ouarzazate-11',
    city: 'ouarzazate',
    name: 'Restaurant Sabrine',
    neighborhood: 'Centre Ville',
    description: 'A cozy, highly reliable central restaurant serving authentic, home-style Berber dishes. Offers a highly relaxed street-facing terrace, perfect for affordable Moroccan stews and salads.',
    pricePerPerson: 7.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Casual Dining', 'Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Berber'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:00',
    closeTime: '22:30',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 280,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 280,
    theforkRating: 4.4,
    theforkReviewCount: 280,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 280,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Sabrine+Ouarzazate',
    bestDishes: ['Saffron Chicken Tagine', 'Kefta Egg Tagine', 'Fresh Fruit Salad'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Perfect for travelers on a budget seeking simple, highly authentic tagines with exceptionally welcoming service.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-ouarzazate-12',
    city: 'ouarzazate',
    name: 'La Terrasse Café & Restaurant',
    neighborhood: 'Centre Ville',
    description: 'A stylish and popular rooftop café in the city center. Known for its breezy top terrace and wide selection of continental breakfasts, custom fresh juices, and light Italian pasta.',
    pricePerPerson: 6.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'brunch', 'flexible'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Sunset Views'],
    foodStyles: ['Mediterranean', 'Italian', 'Cafe'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '07:00',
    closeTime: '23:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 340,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 340,
    theforkRating: 4.1,
    theforkReviewCount: 340,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 340,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=La+Terrasse+Cafe+Ouarzazate',
    bestDishes: ['Fresh Avocado Almond Shake', 'Alfredo Penne Pasta', 'Continental Breakfast Board'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Sit on the terrace for excellent morning breeze. Their fresh avocado and almond shake is delicious.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'rooftop'],
    viewType: 'city',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-ouarzazate-13',
    city: 'ouarzazate',
    name: 'Afoulki Café Restaurant',
    neighborhood: 'Centre Ville',
    description: 'A bustling local café-restaurant with traditional earthen motifs. Offers street-level shaded terrace seating, serving highly popular barbecue plates, pizzas, and paninis.',
    pricePerPerson: 6,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'flexible'],
    experienceTypes: ['Casual Dining', 'Family Friendly', 'Local Gathering Spot'],
    foodStyles: ['Moroccan', 'Italian', 'Barbecue'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '23:30',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 195,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 195,
    theforkRating: 4.2,
    theforkReviewCount: 195,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 195,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Afoulki+Cafe+Ouarzazate',
    bestDishes: ['Spiced Charcoal Mixed Grill', 'Margherita Pizza', 'Msemen with honey'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Perfect place for families. Their charcoal mixed grill and cheese pizzas are highly popular with kids.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-ouarzazate-14',
    city: 'ouarzazate',
    name: 'Restaurant Habous',
    neighborhood: 'Centre Ville',
    description: 'A charming local café-restaurant and tea salon. Renowned for its traditional Moroccan pastries, fresh fruit shakes, and satisfying classic tagines served on a breezy sidewalk terrace.',
    pricePerPerson: 5.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'afternoon-tea', 'flexible'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Bakery-Patisserie'],
    foodStyles: ['Moroccan', 'Cafe', 'Bakery'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '07:00',
    closeTime: '22:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 220,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 220,
    theforkRating: 4.3,
    theforkReviewCount: 220,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 220,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Cafe+Habous+Ouarzazate',
    bestDishes: ['Almond Ghriba Cookies', 'Sage Mint Tea', 'Kefta Tagine with Eggs'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Try their classic almond pastries along with a pot of hot sage-infused mint tea.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: true
  },

  {
    id: 'e-ouarzazate-15',
    city: 'ouarzazate',
    name: 'Restaurant César',
    neighborhood: 'Centre Ville',
    description: 'A stylish, highly popular local café and bistro. Serves excellent continental breakfasts, fresh mocktails, and Mediterranean-inspired light stews in a stylish, design-forward setting.',
    pricePerPerson: 8,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'flexible'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Modern Fusion Dining'],
    foodStyles: ['Mediterranean', 'Italian', 'Cafe'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '07:30',
    closeTime: '23:30',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 140,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 140,
    theforkRating: 4.1,
    theforkReviewCount: 140,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 140,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Cesar+Cafe+Ouarzazate',
    bestDishes: ['Italian Double Espresso', 'Chicken Alfredo Pasta', 'Gourmet Beef Burger'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Perfect spot for digital nomads needing a quiet, clean place to work with excellent coffee.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'e-ouarzazate-16',
    city: 'ouarzazate',
    name: 'Restaurant Oasis',
    neighborhood: 'Ait Kdif',
    description: 'A grand traditional Moroccan restaurant situated right opposite the historic Taourirt Kasbah. Decorated beautifully with classic Moroccan zellige and arches, it serves authentic giant couscous.',
    pricePerPerson: 12,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Casual Dining', 'Sunset Views'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:00',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 480,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 480,
    theforkRating: 4.2,
    theforkReviewCount: 480,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 480,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Oasis+Ouarzazate',
    bestDishes: ['Oasis Chicken Couscous', 'Beef Tagine with Almonds', 'Traditional Harira Soup'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'Sit in the beautiful traditional Moroccan salons. Excellent choice for larger families or tourist groups wanting classic comfort after visiting the Kasbah.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'city',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'e-ouarzazate-17',
    city: 'ouarzazate',
    name: 'Restaurant Phoenix',
    neighborhood: 'Zone des Studios',
    description: 'A vibrant casual restaurant situated right near the famous Atlas Film Studios. Famed for catering to tourists and movie crews, it serves great Moroccan stews and crispy stone-baked pizzas.',
    pricePerPerson: 11,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Family Friendly', 'Wood-Fired Pizza'],
    foodStyles: ['Italian', 'Moroccan', 'Pizza'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:30',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 320,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 320,
    theforkRating: 4.3,
    theforkReviewCount: 320,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 320,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Phoenix+Ouarzazate',
    bestDishes: ['Stone-baked Four Cheese Pizza', 'Saffron Beef Tagine', 'Fresh Fruit Juices'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'A very popular spot for movie studio visitors. Their stone-baked pizzas are thin, crispy, and exceptionally satisfying.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'e-ouarzazate-18',
    city: 'ouarzazate',
    name: "Restaurant L'Étoile du Sud",
    neighborhood: 'Centre Ville',
    description: 'An evocative traditional restaurant decorated with grand Saharan tents and beautiful Berber carpets. Highly trusted for its authentic, slow-cooked couscous and tagines representing Southern Moroccan hospitality.',
    pricePerPerson: 13,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Casual Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Berber'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'seniors', 'large-groups'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:30',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 410,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 410,
    theforkRating: 4.2,
    theforkReviewCount: 410,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 410,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=L+Etoile+du+Sud+Ouarzazate',
    bestDishes: ['Southern Lamb Couscous', 'Spiced Berber Beef Tagine', 'Moroccan Mint Tea'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Perfect for travelers wanting to dine inside a traditional Nomad tent environment with live Berber lute notes on select nights.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },

  {
    id: 'e-ouarzazate-19',
    city: 'ouarzazate',
    name: 'Restaurant Bagdad Café',
    neighborhood: 'Ait Benhaddou',
    description: 'A stylish, highly popular hotel-restaurant located near the ancient Ksar of Ait Benhaddou. Heavily celebrated for its film-inspired retro decor, lovely poolside patio, and delicious Berber dishes.',
    pricePerPerson: 14,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch'],
    experienceTypes: ['Casual Dining', 'Sunset Views', 'Romantic Sunset'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Berber'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 650,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 650,
    theforkRating: 4.6,
    theforkReviewCount: 650,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 650,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Bagdad+Cafe+Ait+Benhaddou',
    bestDishes: ['Spiced Berber Egg Tagine', 'Traditional Chicken Tajine with Almonds', 'Fresh Melon Salad'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Famed for its artistic film-themed vibe. Sit by the pool to enjoy their legendary, spiced Berber egg tagine.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'mountain',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },

  {
    id: 'e-ouarzazate-20',
    city: 'ouarzazate',
    name: 'Restaurant Riad Ksar Ighnda',
    neighborhood: 'Ait Benhaddou',
    description: 'An opulent, high-end hotel restaurant set right on the edge of the desert valley. Offers exquisite, chef-elevated traditional Moroccan stews and international fusion plates inside a majestic, fortress-style castle.',
    pricePerPerson: 38,
    lifestyle: 'premium',
    mealTypes: ['breakfast', 'lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Traditional Dining', 'Romantic Sunset', 'Sunset Views'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Gourmet'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'seniors', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '07:30',
    closeTime: '23:30',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 220,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 220,
    theforkRating: 4.7,
    theforkReviewCount: 220,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 220,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    googleMapsUrl: 'https://maps.google.com/?q=Ksar+Ighnda+Ait+Benhaddou',
    bestDishes: ['Elevated Lamb Shoulder', 'Slow-cooked Saffron Chicken', 'Traditional Moroccan Salad Medley'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Perfect for a luxury dinner stop after exploring the ancient clay ruins of Ait Benhaddou. Highly romantic setting.',

    // ── NEW FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'mountain',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  }
];