import type { EatListing } from '../types';

export const ouarzazateEat: EatListing[] = [
  {
    id: 'e-ouarzazate-1',
    city: 'ouarzazate',
    name: 'La Kasbah des Sables',
    neighborhood: 'Ait Kdif',
    description: 'An extraordinary gourmet destination located in Ouarzazate\'s oldest neighborhood. Built like an opulent desert palace, it features distinct dining salons, a central plunge pool, and intricate Amazigh craftsmanship.',
    pricePerPerson: 32,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Traditional Dining', 'Romantic Sunset'],
    foodStyles: ['Moroccan', 'French', 'Mediterranean', 'Gourmet'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'seniors', 'large-groups'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    openTime: '12:00',
    closeTime: '23:30',
    badge: 'splurge',

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 850,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 920,
    theforkRating: 4.5,
    theforkReviewCount: 80,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 1056,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212524885428',
    googleMapsUrl: 'https://maps.google.com/?q=La+Kasbah+des+Sables+Ouarzazate',
    bestDishes: ['Argan-infused Lamb Tagine', 'Saffron Sea Bass', 'Pastilla with Almond Milk'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Sit around the central pool in the evening. The candlelit atmosphere is spectacular, and the French owner, Brigitte, offers wonderful service.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  ,
    tags: ["alcohol", "budget", "dinner", "fine", "medina", "palace", "pastilla", "sunset", "tagine", "wifi"]
  },

  {
    id: 'e-ouarzazate-2',
    city: 'ouarzazate',
    name: 'Chez Dimitri',
    neighborhood: 'Centre Ville',
    description: 'Ouarzazate\'s oldest and most legendary restaurant, operating since 1928. Originally a Foreign Legion post, it is decorated with decades of signed movie star photos, from Orson Welles and Ridley Scott to Michael Douglas.',
    pricePerPerson: 13,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Casual Dining', 'Traditional Dining', 'Local Gathering Spot'],
    foodStyles: ['Mediterranean', 'French', 'Moroccan', 'Italian'],
    // food-cuisine quiz question tags
    cuisineTags: ['international', 'moroccan-traditional'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    openTime: '11:30',
    closeTime: '00:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.0,
    googleReviewCount: 480,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 360,
    theforkRating: 4.0,
    theforkReviewCount: 90,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 650,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212524887346',
    googleMapsUrl: 'https://maps.google.com/?q=Chez+Dimitri+Ouarzazate',
    bestDishes: ['Classic French Steak Frites', 'Lamb Tagine with Prunes', 'Handmade Thin Crust Pizza'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Take some time to look at the vintage movie-set photos on the walls. It is a fantastic historical monument of the Moroccan film industry.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["alcohol", "budget", "dinner", "late-night", "tagine", "wifi"]
  },

  {
    id: 'e-ouarzazate-3',
    city: 'ouarzazate',
    name: 'Jardin des Arômes',
    neighborhood: 'Centre Ville',
    description: 'A stylish and refined French-Moroccan fusion restaurant. It offers an upscale dining experience with beautifully presented stews and modern steaks inside a chic Moroccan salon.',
    pricePerPerson: 21,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Upscale Lounge'],
    foodStyles: ['Moroccan', 'French', 'Mediterranean', 'Gourmet'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 450,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 510,
    theforkRating: 4.4,
    theforkReviewCount: 70,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 950,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212524885338',
    googleMapsUrl: 'https://maps.google.com/?q=Jardin+des+Aromes+Ouarzazate',
    bestDishes: ['Gourmet Chicken Pastilla', 'Slow-cooked Beef Tagine', 'Chocolate Fondant'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'One of the highest-end meals in the city center. Their modern chicken pastilla and wine pairings are outstanding.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["alcohol", "budget", "dinner", "fine", "pastilla", "sunset", "tagine", "wifi"]
  },

  {
    id: 'e-ouarzazate-4',
    city: 'ouarzazate',
    name: 'Le Relais de Saint-Exupéry',
    neighborhood: 'Centre Ville',
    description: 'A cozy French bistro celebrating the writer-aviator Antoine de Saint-Exupéry. Managed by a Bordeaux chef, it serves classic French delicacies and dromedary steak using demanding fresh local products.',
    pricePerPerson: 18,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Upscale Lounge'],
    foodStyles: ['French', 'Mediterranean', 'European'],
    // food-cuisine quiz question tags
    cuisineTags: ['international'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'seniors', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'hidden-gem',

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 180,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 140,
    theforkRating: 4.3,
    theforkReviewCount: 40,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 340,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212524887779',
    googleMapsUrl: 'https://maps.google.com/?q=Le+Relais+de+Saint-Exupery+Ouarzazate',
    bestDishes: ['Dromedary Meat with Mashed Vegetables', 'Fresh Herb Lemon Fish', 'Warm Apple Tarte Tatin'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Located at 13 Boulevard Moulay Abdellah. Features an extensive Moroccan wine list and intimate French-aviation nostalgia decor.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  ,
    tags: ["alcohol", "budget", "dinner", "fine", "sunset", "wifi"]
  },

  {
    id: 'e-ouarzazate-5',
    city: 'ouarzazate',
    name: 'El Bahja',
    neighborhood: 'Douar Cheums',
    description: 'The ultimate, no-frills local canteen in Ouarzazate. Always humming with locals and desert drivers, it serves excellent charcoal-grilled meats, rotisserie chicken, and hot, spiced bean stews.',
    pricePerPerson: 4.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Casual Dining', 'Local Gathering Spot'],
    foodStyles: ['Moroccan', 'Barbecue'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '11:00',
    closeTime: '22:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 450,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 210,
    theforkRating: 4.0,
    theforkReviewCount: 50,
    restaurantguruRating: 4.0,
    restaurantguruReviewCount: 807,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Bahja+Ouarzazate',
    bestDishes: ['Mixed Charcoal Grill Platter', 'Spiced Loubia (White Beans)', 'Rotisserie Chicken with Olives'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'closed',
    tip: 'Order their famous "loubia" (spiced white beans) to accompany your mixed charcoal meat plate. Very cheap and deeply satisfying.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["budget", "dinner", "dry"]
  },

  {
    id: 'e-ouarzazate-6',
    city: 'ouarzazate',
    name: 'Restaurant Douyria',
    neighborhood: 'Centre Ville',
    description: 'A cozy traditional Moroccan restaurant featuring beautiful Berber carpets and a scenic rooftop terrace overlooking Kasbah Taourirt. Trusted for Friday couscous and traditional clay-pot tagines.',
    pricePerPerson: 9.5,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Traditional Dining', 'Sunset Views'],
    foodStyles: ['Moroccan'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '11:30',
    closeTime: '22:30',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 820,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 360,
    theforkRating: 4.2,
    theforkReviewCount: 80,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 850,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212524885288',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Douyria+Ouarzazate',
    bestDishes: ['Dromedary Meat Tagine', 'Friday Seven-Vegetable Couscous', 'Pigeon Pastilla with Almonds'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Licensed to serve wine and beer. Dine on the upper terrace around sunset for a breezy view overlooking the square and Kasbah walls.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'rooftop'],
    viewType: 'city',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["alcohol", "budget", "couscous", "dinner", "pastilla", "rooftop", "sunset", "tagine", "terrace", "wifi"]
  },

  {
    id: 'e-ouarzazate-7',
    city: 'ouarzazate',
    name: 'The Full Sun',
    neighborhood: 'Zone Touristique',
    description: 'A contemporary, bright restaurant and cafe located in Ouarzazate\'s tourist zone near the Ibis Hotel. Offers fresh breakfasts, homemade pizzas, custom fresh salads, and Moroccan stews.',
    pricePerPerson: 8.5,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'flexible'],
    experienceTypes: ['Casual Dining', 'Family Friendly', 'People Watching'],
    foodStyles: ['Mediterranean', 'Italian', 'Moroccan', 'Cafe'],
    // food-cuisine quiz question tags
    cuisineTags: ['international', 'moroccan-traditional'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '07:30',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 2120,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 685,
    theforkRating: 4.7,
    theforkReviewCount: 110,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 2876,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212524885566',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+The+Full+Sun+Ouarzazate',
    bestDishes: ['Build-your-own Fresh Salad', 'Wood-fired Pizza Pepperoni', 'Chicken Tagine with Lemon'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Located at N° 706 Avenue Moulay Rachid. One of the highest-rated and cleanest stops in the city, accepting card payments and offering great AC.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dinner", "dry", "tagine", "terrace", "wifi"]
  },

  {
    id: 'e-ouarzazate-8',
    city: 'ouarzazate',
    name: 'Dar Chamaa Restaurant',
    neighborhood: 'Zone Touristique',
    description: 'A peaceful guesthouse restaurant offering poolside dining surrounded by olive trees in the Palmeraie de Tajda. Known for romantic evening dinners under the Saharan stars with Atlas views.',
    pricePerPerson: 18,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Garden restaurant with live music'],
    foodStyles: ['Moroccan', 'Mediterranean'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    openTime: '08:00',
    closeTime: '22:30',
    badge: 'hidden-gem',

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 480,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 934,
    theforkRating: 4.5,
    theforkReviewCount: 60,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 520,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212524854954',
    googleMapsUrl: 'https://maps.google.com/?q=Dar+Chamaa+Ouarzazate',
    bestDishes: ['Beef Tagine with Caramelized Prunes', 'Organic Saffron Rice with Vegetables', 'Moroccan Pastry Sampler'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Dine by the pool in the evening. Features a curated Moroccan wine and beer selection with tranquil mountain vistas.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["alcohol", "breakfast", "budget", "dinner", "fine", "live-music", "mountain", "quiet", "sunset", "tagine", "wifi"]
  },

  {
    id: 'e-ouarzazate-9',
    city: 'ouarzazate',
    name: 'Restaurant 3 Thés',
    neighborhood: 'Centre Ville',
    description: 'A traditional riad-style restaurant and art gallery on Avenue Moulay Rachid near the CTM station. Features authentic Moroccan salons serving generous set menus and fragrant teas.',
    pricePerPerson: 11,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Sunset Views', 'Traditional Dining'],
    foodStyles: ['Moroccan'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '11:30',
    closeTime: '22:30',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 260,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 140,
    theforkRating: 4.1,
    theforkReviewCount: 30,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 280,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212524886363',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+3+Thes+Ouarzazate',
    bestDishes: ['Berber Tagine with Vegetables', 'Chicken Pastilla', 'Assorted Moroccan Salads'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Located at 1 Avenue Moulay Rachid right behind the CTM terminal. Great stop for tea and tagine before or after bus travel.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["budget", "dinner", "dry", "pastilla", "riad", "sunset", "tagine", "terrace"]
  },

  {
    id: 'e-ouarzazate-10',
    city: 'ouarzazate',
    name: 'Kasbah Tafarnout',
    neighborhood: 'Centre Ville',
    description: 'A popular modern bakery, pastry shop, and cafe at 74 Avenue Mohammed V. Famed for freshly baked French croissants, traditional Moroccan almond sweets, and morning breakfast boards.',
    pricePerPerson: 5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'brunch', 'afternoon-tea', 'flexible'],
    experienceTypes: ['Bakery-Patisserie', 'Casual Dining', 'Traditional Breakfast Ritual'],
    foodStyles: ['Bakery', 'French', 'Moroccan', 'Cafe'],
    // food-cuisine quiz question tags
    cuisineTags: ['cafe-pastry', 'international', 'moroccan-traditional'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '06:30',
    closeTime: '22:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 370,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 180,
    theforkRating: 4.0,
    theforkReviewCount: 40,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 450,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    reservationContact: '+212524882800',
    googleMapsUrl: 'https://maps.google.com/?q=Kasbah+Tafarnout+Ouarzazate',
    bestDishes: ['Almond Croissant', 'Traditional Mint Tea with Cookies', 'Fresh Fruit Juice'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'The best spot in town to pick up traditional Moroccan cookies like Chebakia and Kaab el Ghazal, or grab a rapid espresso before visiting the studios.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dry", "juice", "pastry", "wifi"]
  },

  {
    id: 'e-ouarzazate-11',
    city: 'ouarzazate',
    name: 'Restaurant Sabrine',
    neighborhood: 'Centre Ville',
    description: 'A cozy family-run restaurant directly opposite the famous Kasbah Taourirt on Avenue Mohammed V. Features a sunny street terrace serving authentic, sizzling clay-pot Berber tagines and fresh salads.',
    pricePerPerson: 7.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Casual Dining', 'Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Berber'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '11:00',
    closeTime: '22:30',
    badge: 'local',

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 520,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 240,
    theforkRating: 4.6,
    theforkReviewCount: 50,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 584,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    reservationContact: '+212661948640',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Sabrine+Ouarzazate',
    bestDishes: ['Saffron Chicken Tagine', 'Kefta Egg Tagine', 'Fresh Fruit Salad'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Located right across from Kasbah Taourirt. Sizzling homemade tagines served with hot bread and friendly hospitality at budget prices.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: false,
    airConditioning: true,
    wheelchairAccessible: false
  ,
    tags: ["budget", "dinner", "dry", "tagine", "terrace"]
  },

  {
    id: 'e-ouarzazate-12',
    city: 'ouarzazate',
    name: 'La Terrasse Café & Restaurant',
    neighborhood: 'Centre Ville',
    description: 'A stylish rooftop cafe in the city center. Known for its breezy top terrace and wide selection of continental breakfasts, custom fresh juices, and light Italian pasta.',
    pricePerPerson: 6.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'brunch', 'flexible'],
    experienceTypes: ['Casual Dining', 'Sunset Views', 'People Watching'],
    foodStyles: ['Mediterranean', 'Italian', 'Cafe'],
    // food-cuisine quiz question tags
    cuisineTags: ['international', 'cafe-pastry'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '07:00',
    closeTime: '23:00',
    badge: 'local',

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 340,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 110,
    theforkRating: 4.2,
    theforkReviewCount: 30,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 427,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=La+Terrasse+Cafe+Ouarzazate',
    bestDishes: ['Fresh Avocado Almond Shake', 'Alfredo Penne Pasta', 'Continental Breakfast Board'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Sit on the terrace for excellent morning breeze. Their fresh avocado and almond shake is delicious.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dry", "juice", "rooftop", "sunset", "terrace", "wifi"]
  },

  {
    id: 'e-ouarzazate-13',
    city: 'ouarzazate',
    name: 'Afoulki Café Restaurant',
    neighborhood: 'Centre Ville',
    description: 'A bustling local cafe-restaurant on Avenue Mohammed V. Offers street-level shaded terrace seating, serving barbecue plates, pizzas, and paninis.',
    pricePerPerson: 6,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'flexible'],
    experienceTypes: ['Casual Dining', 'Family Friendly', 'Local Gathering Spot'],
    foodStyles: ['Moroccan', 'Italian', 'Barbecue'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international', 'cafe-pastry'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '08:00',
    closeTime: '23:30',
    badge: 'local',

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 310,
    tripadvisorRating: 3.8,
    tripadvisorReviewCount: 90,
    theforkRating: 3.9,
    theforkReviewCount: 20,
    restaurantguruRating: 4.0,
    restaurantguruReviewCount: 442,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Afoulki+Cafe+Ouarzazate',
    bestDishes: ['Spiced Charcoal Mixed Grill', 'Margherita Pizza', 'Msemen with honey'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Casual spot along the main avenue. Their charcoal mixed grill and cheese pizzas are dependable and quick.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dinner", "dry", "terrace"]
  },

  {
    id: 'e-ouarzazate-14',
    city: 'ouarzazate',
    name: 'Restaurant Habous',
    neighborhood: 'Centre Ville',
    description: 'A landmark cafe, bakery, and restaurant located on Place Al-Mouahidine. Renowned for its traditional Moroccan pastries, fresh fruit shakes, and classic tagines served on a breezy sidewalk terrace.',
    pricePerPerson: 5.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'afternoon-tea', 'flexible'],
    experienceTypes: ['Bakery-Patisserie', 'Casual Dining', 'People Watching'],
    foodStyles: ['Moroccan', 'Cafe', 'Bakery'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'cafe-pastry'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '07:00',
    closeTime: '22:00',
    badge: 'local',

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 1012,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 380,
    theforkRating: 4.1,
    theforkReviewCount: 60,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 1097,

    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    reservationContact: '+212524882525',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Cafe+Habous+Ouarzazate',
    bestDishes: ['Almond Ghriba Cookies', 'Sage Mint Tea', 'Kefta Tagine with Eggs'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Prime people-watching location on Place Al-Mouahidine. Pair a pot of hot mint tea with their almond pastries.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: true
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dry", "pastry", "tagine", "terrace"]
  },

  {
    id: 'e-ouarzazate-15',
    city: 'ouarzazate',
    name: 'Restaurant César',
    neighborhood: 'Centre Ville',
    description: 'A stylish, popular modern cafe and bistro on Boulevard Moulay Abdellah. Serves continental breakfasts, fresh mocktails, burgers, and Italian-inspired pasta in a clean, design-forward setting.',
    pricePerPerson: 8,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'flexible'],
    experienceTypes: ['Casual Dining', 'Modern Fusion Dining', 'People Watching'],
    foodStyles: ['Mediterranean', 'Italian', 'Cafe'],
    // food-cuisine quiz question tags
    cuisineTags: ['international', 'cafe-pastry'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '07:30',
    closeTime: '23:30',
    badge: 'local',

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 130,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 40,
    theforkRating: 4.0,
    theforkReviewCount: 15,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 125,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    reservationContact: '+212524884129',
    googleMapsUrl: 'https://maps.google.com/?q=Cesar+Cafe+Ouarzazate',
    bestDishes: ['Italian Double Espresso', 'Chicken Alfredo Pasta', 'Gourmet Beef Burger'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Comfortable modern setting on Boulevard Moulay Abdellah with reliable Wi-Fi and air conditioning.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dinner", "dry", "wifi"]
  },

  {
    id: 'e-ouarzazate-16',
    city: 'ouarzazate',
    name: 'Restaurant Oasis',
    neighborhood: 'Ait Kdif',
    description: 'A traditional Moroccan dining room situated near the historic Taourirt Kasbah. Decorated with classic Moroccan zellige and arches, it serves authentic tagines, pastillas, and couscous.',
    pricePerPerson: 12,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Casual Dining', 'Sunset Views'],
    foodStyles: ['Moroccan'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '11:00',
    closeTime: '22:30',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 260,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 120,
    theforkRating: 4.0,
    theforkReviewCount: 30,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 260,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Oasis+Ouarzazate',
    bestDishes: ['Chicken Couscous with Seven Vegetables', 'Beef Tagine with Almonds', 'Traditional Harira Soup'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'Good traditional choice for families and groups visiting the Taourirt Kasbah.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'city',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["budget", "couscous", "dinner", "dry", "medina", "pastilla", "sunset", "tagine", "wifi"]
  },

  {
    id: 'e-ouarzazate-17',
    city: 'ouarzazate',
    name: 'Restaurant Phoenix',
    neighborhood: 'Zone des Studios',
    description: 'A casual restaurant on Rue de l\'ONEP near the famous Atlas Film Studios. Known for catering to tourists and movie crews, it serves Moroccan stews and crispy stone-baked pizzas.',
    pricePerPerson: 11,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Family Friendly', 'Wood-Fired Pizza'],
    foodStyles: ['Italian', 'Moroccan', 'Pizza'],
    // food-cuisine quiz question tags
    cuisineTags: ['international', 'moroccan-traditional'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    openTime: '11:30',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 3.9,
    googleReviewCount: 160,
    tripadvisorRating: 3.8,
    tripadvisorReviewCount: 60,
    theforkRating: 3.9,
    theforkReviewCount: 20,
    restaurantguruRating: 3.9,
    restaurantguruReviewCount: 160,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212524888313',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Phoenix+Ouarzazate',
    bestDishes: ['Stone-baked Four Cheese Pizza', 'Saffron Beef Tagine', 'Fresh Fruit Juices'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'Convenient stop right near Atlas Film Studios. Offers an outdoor terrace with views over the valley.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["budget", "dinner", "dry", "juice", "mountain", "tagine", "terrace", "wifi"]
  },

  {
    id: 'e-ouarzazate-18',
    city: 'ouarzazate',
    name: "Restaurant L'Étoile du Sud",
    neighborhood: 'Centre Ville',
    description: 'An evocative traditional restaurant operating on Avenue Mohammed V since 1968. Decorated with caidal velvet tents and Berber carpets, serving classic couscous and tagines with licensed wine.',
    pricePerPerson: 13,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Casual Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Berber'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'seniors', 'large-groups'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:30',
    closeTime: '22:30',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.1,
    googleReviewCount: 310,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 180,
    theforkRating: 4.0,
    theforkReviewCount: 40,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 310,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=L+Etoile+du+Sud+Ouarzazate',
    bestDishes: ['Royal Lamb Couscous', 'Spiced Berber Beef Tagine', 'Warm Harira with Dates'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Dine under the caidal tent interior. The restaurant holds an alcohol license and serves local Moroccan wines.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  ,
    tags: ["alcohol", "budget", "couscous", "dinner", "tagine"]
  },

  {
    id: 'e-ouarzazate-19',
    city: 'ouarzazate',
    name: 'Restaurant Bagdad Café',
    neighborhood: 'Ait Benhaddou',
    description: 'A stylish, popular hotel-restaurant located near the ancient Ksar of Ait Benhaddou. Celebrated for its film-inspired retro decor, lovely poolside patio, and delicious Berber dishes.',
    pricePerPerson: 14,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch'],
    experienceTypes: ['Casual Dining', 'Sunset Views', 'Romantic Sunset'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Berber'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international', 'cafe-pastry'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    openTime: '08:00',
    closeTime: '23:00',
    badge: 'local-favorite',

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 520,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 609,
    theforkRating: 4.7,
    theforkReviewCount: 50,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 650,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212662771218',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Bagdad+Cafe+Ait+Benhaddou',
    bestDishes: ['Spiced Berber Egg Tagine', 'Traditional Chicken Tajine with Almonds', 'Fresh Melon Salad'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Famed for its artistic film-themed vibe. Sit by the pool to enjoy their spiced Berber egg tagine with cold beer or wine.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'mountain',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["alcohol", "breakfast", "budget", "cafe-pastry", "dinner", "mountain", "sunset", "tagine", "terrace", "wifi"]
  },

  {
    id: 'e-ouarzazate-20',
    city: 'ouarzazate',
    name: 'Restaurant Riad Ksar Ighnda',
    neighborhood: 'Ait Benhaddou',
    description: 'An opulent, high-end hotel restaurant set right on the edge of the desert valley in Douar Asfalou. Offers chef-elevated traditional Moroccan stews and international fusion plates inside a fortress-style castle.',
    pricePerPerson: 38,
    lifestyle: 'premium',
    mealTypes: ['breakfast', 'lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Traditional Dining', 'Romantic Sunset', 'Sunset Views'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Gourmet'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'seniors', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    openTime: '07:30',
    closeTime: '23:30',
    badge: 'splurge',

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 822,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 528,
    theforkRating: 4.6,
    theforkReviewCount: 80,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 822,

    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212524844111',
    googleMapsUrl: 'https://maps.google.com/?q=Ksar+Ighnda+Ait+Benhaddou',
    bestDishes: ['Slow-Cooked Lamb Shoulder', 'Saffron Braised Chicken', 'Traditional Moroccan Salad Medley'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Perfect for a luxury dinner stop after exploring the ancient clay ruins of Ait Benhaddou. Extensive cocktail and Moroccan wine list.',

    // ── PSYCHOLOGICAL UX FIELDS ──
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'mountain',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["alcohol", "breakfast", "budget", "dinner", "fine", "mountain", "quiet", "riad", "sunset", "terrace", "wifi"]
  }
];