import type { EatListing } from '../types';

/**
 * EAT LISTING TEMPLATE
 * {
 *   id: 'e-[city]-[name]',
 *   city: '[city]',
 *   name: '[Name]',
 *   neighborhood: '[Neighborhood]',
 *   description: '[Long description]',
 *   pricePerPerson: [number],
 *   lifestyle: 'lean' | 'balanced' | 'premium',
 *   mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'latenight', 'afternoon-tea', 'flexible'],
 *   experienceTypes: ['Fine Dining' | 'Waterfront Dining' | 'Romantic Sunset' | 'Beachfront Dining' | 'Garden restaurant with live music' | 'Fountain courtyard' | 'French-Moroccan fusion' | 'Casual Italian Dining' | 'Family Pizza Night' | 'Spanish Beach Lounge' | 'Paella & Tapas' | 'Live Music Terrace' | 'Upscale Romantic Dining' | 'Fine Seafood' | 'Classic Royal Ambiance' | '24/7 Brasserie' | 'People Watching' | 'Bakery-Patisserie' | 'Traditional Breakfast Ritual' | 'Local Gathering Spot' | 'Fishing Harbor Dining' | 'Gourmet Seafood' | 'French-Italian Fusion' | 'Authentic Berber Feast' | 'Traditional Dining' | 'Cozy casual family-run Moroccan eatery' | 'Amazigh-inspired decor' | 'Beachfront Grill' | 'Casual Dining' | 'Sunset Views' | 'Wood-Fired Pizza' | 'Family Friendly' | 'Leafy Tennis Oasis' | 'Tranquil Dining' | 'Upscale Lounge' | 'Modern Fusion Dining' | 'Unverified'],
 *   foodStyles: ['French' | 'Moroccan' | 'Seafood' | 'Mediterranean' | 'European' | 'International' | 'Italian' | 'Pizza' | 'Spanish' | 'Berber' | 'Barbecue' | 'Middle Eastern' | 'Healthy' | 'Cafe' | 'Bakery' | 'Patisserie' | 'Gourmet' | 'Fast Food'],
 *   crowdLevel: 'bustling' | 'balanced' | 'quiet',
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *   hasEnglishStaff: true | false,
 *   hasFrenchStaff: true | false,
 *   hasDelivery: true | false,
 *   hasParking: true | false,
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearCenter: true | false,
 *   isVegetarianFriendly: true | false,
 *   isHalal: true | false,
 *   openTime: 'HH:mm',
 *   closeTime: 'HH:mm',
 *   badge: 'local-favorite' | 'splurge' | 'hidden-gem' | 'local',
 *   fullMenu: { type: 'image' | 'text', content: 'https://...' },
 *   tip: '[Short tip]',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   reservationContact: '+212XXXXXXXXX',
 *   bestDishes: ['Dish 1', 'Dish 2'],
 *   alcoholPolicy: 'serves-alcohol' | 'dry',
 *   ramadanFriendly: 'serves-lunch' | 'special-ftour' | 'closed',
 *   bestTimeToVisit: 'Early evening around 18:30 for sunset' | 'Lunch around 13:00 for quiet' | 'Late evening after 20:00 for lively crowd' | 'Early morning for fresh baked goods' | 'Sunday morning for brunch peak',
 *   averageWaitMinutes: 0 | 5 | 10 | 15 | 20 | 30 | 45 | 60,
 *   seatingTypes: ['indoor'] | ['terrace'] | ['rooftop'] | ['garden'] | ['beachfront'] | ['indoor', 'terrace'] | ['indoor', 'garden'] | ['terrace', 'rooftop'],
 *   viewType: 'beach' | 'mountain' | 'city' | 'garden' | 'none',
 *   wiFi: true | false,
 *   airConditioning: true | false,
 *   wheelchairAccessible: true | false,
 *   website: 'https://...',
 *   instagram: '@handle' | 'https://instagram.com/...'
 * }
 */

export const rabatEat: EatListing[] = [
  {
    id: 'e-rabat-1',
    city: 'rabat',
    name: 'Dar Naji',
    neighborhood: 'Bab El Had / Centre Ville',
    description: 'A beloved traditional restaurant designed to mimic a classic Moroccan home. It is immensely popular for serving generous portions of authentic classics such as chicken tride, lamb tagines, and couscous.',
    pricePerPerson: 10,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Traditional Dining', 'Local Gathering Spot'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'bustling',
    groupTypes: ['family', 'friends', 'couple'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.4,
    googleReviewCount: 2500,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 4200,
    theforkRating: 4.4,
    theforkReviewCount: 4200,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 4200,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212537262626',
    googleMapsUrl: 'https://maps.google.com/?q=Dar+Naji+Rabat',
    bestDishes: ['Chicken Tride', 'Beef Tagine with Prunes', 'Friday Seven-Vegetable Couscous'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Famous for its high-altitude mint tea pouring show. Friday couscous is exceptional but gets crowded.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-rabat-2',
    city: 'rabat',
    name: 'Le Dhow',
    neighborhood: 'Bouregreg Marina',
    description: 'A distinctive floating restaurant and lounge on a three-masted wooden boat docked near the historic Kasbah of the Udayas. Specializes in French-Mediterranean bistro dishes and fresh seafood.',
    pricePerPerson: 32,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Waterfront Dining', 'Romantic Sunset'],
    foodStyles: ['French', 'Mediterranean', 'Seafood'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'solo'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '02:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.1,
    googleReviewCount: 2300,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 2300,
    theforkRating: 4.1,
    theforkReviewCount: 2300,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 2300,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    googleMapsUrl: 'https://maps.google.com/?q=Le+Dhow+Rabat',
    bestDishes: ['Grilled Atlantic Sea Bass', 'Fillet Mignon', 'Chocolate Lava Cake'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Try to book an outdoor deck table at sunset for stunning, unhindered views of the ancient Kasbah.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },
  {
    id: 'e-rabat-3',
    city: 'rabat',
    name: 'Dar El Medina',
    neighborhood: 'Medina',
    description: 'A charming, peaceful restaurant inside a beautifully restored riad patio in the old medina. It offers an escape from the busy market streets with delicious homestyle Moroccan cuisine.',
    pricePerPerson: 13,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Traditional Dining', 'Garden restaurant with live music'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.6,
    googleReviewCount: 890,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 890,
    theforkRating: 4.6,
    theforkReviewCount: 890,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 890,
    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Dar+El+Medina+Rabat',
    bestDishes: ['Lemon Chicken Tagine', 'Kefta Meatball Tagine', 'Moroccan Cooked Salads'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'A great respite after shopping in the Medina. Try their amazing lemon chicken tagine.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-rabat-4',
    city: 'rabat',
    name: 'Dar Zaki',
    neighborhood: 'Medina',
    description: 'Tucked deep within a quiet alley of Rabat\'s bustling medina, Dar Zaki is a beautifully designed, historic riad restaurant serving excellent Moroccan specialties with powdered-sugar pastillas and tagines.',
    pricePerPerson: 16,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Romantic Sunset', 'Fine Dining'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.7,
    googleReviewCount: 750,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 750,
    theforkRating: 4.7,
    theforkReviewCount: 750,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 750,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Dar+Zaki+Rabat',
    bestDishes: ['Pigeon Pastilla', 'Lamb Tagine with Caramelized Figs', 'Mint Tea and Moroccan Pastries'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Difficult to find on foot, so look out for the signages or ask locals for directions to the alleyway.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-rabat-5',
    city: 'rabat',
    name: 'Golden Fish',
    neighborhood: 'Souissi',
    description: 'A sophisticated seafood-centric fine dining restaurant situated in the lush park-like gardens of the five-star Sofitel Rabat Jardin des Roses. Merges premium Atlantic catches with exquisite French culinary techniques.',
    pricePerPerson: 49,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Fine Seafood', 'Romantic Sunset'],
    foodStyles: ['Seafood', 'French', 'Mediterranean', 'Gourmet'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'solo'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.6,
    googleReviewCount: 350,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 350,
    theforkRating: 4.6,
    theforkReviewCount: 350,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 350,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['online', 'phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Golden+Fish+Sofitel+Rabat',
    bestDishes: ['Atlantic Grilled Sea Bass', 'Seafood Risotto', 'Saint-Jacques Scallops'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Highly recommended to reserve an outdoor patio seat overlooking the eucalyptus gardens for a quiet lunch.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-rabat-6',
    city: 'rabat',
    name: 'Le Bistrot du Pietri',
    neighborhood: 'Hassan',
    description: 'A vibrant urban bistro operating within the boutique Pietri Urban Hotel. Celebrated for its fresh world/international menu, green garden courtyard seating, and bi-weekly live jazz and acoustic music performances.',
    pricePerPerson: 19,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Garden restaurant with live music', 'Cafe'],
    foodStyles: ['Mediterranean', 'French', 'International'],
    crowdLevel: 'bustling',
    groupTypes: ['friends', 'couple', 'solo'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.5,
    googleReviewCount: 1100,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 1100,
    theforkRating: 4.5,
    theforkReviewCount: 1100,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 1100,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Le+Bistrot+du+Pietri+Rabat',
    bestDishes: ['Duck Breast with Fig Sauce', 'Tapas Sharing Board', 'Daily Bistro Chef Special'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'A true local favorite for jazz lovers. Check their schedule in advance to book a table for live music evenings.',
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-rabat-7',
    city: 'rabat',
    name: 'El Tropic',
    neighborhood: 'Agdal',
    description: 'A hip, trendy, tropical-inspired bistro in Rabat\'s modern Agdal district. Widely loved for healthy brunch plates, organic bowls, and outstanding specialty coffee in an Instagram-ready setting.',
    pricePerPerson: 12,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'brunch'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Modern Fusion Dining'],
    foodStyles: ['Mediterranean', 'Healthy', 'Cafe'],
    crowdLevel: 'bustling',
    groupTypes: ['friends', 'solo', 'couple'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.4,
    googleReviewCount: 1300,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 1300,
    theforkRating: 4.4,
    theforkReviewCount: 1300,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 1300,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=El+Tropic+Rabat',
    bestDishes: ['Eggs Benedict on Brioche', 'Matcha Latte', 'Açai Smoothie Bowl'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Owned by Pepe, the owner of Sa Caleta. Their weekend breakfast and pancakes draw large, stylish local crowds.',
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-rabat-8',
    city: 'rabat',
    name: 'Yamal Acham',
    neighborhood: 'Agdal',
    description: 'Regarded as Rabat\'s absolute best Syrian restaurant. Extremely popular with locals for its incredibly authentic mezes, massive portions of shawarma, and flawlessly spiced Levantine mixed grills.',
    pricePerPerson: 8,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Local Gathering Spot'],
    foodStyles: ['Middle Eastern', 'Mediterranean'],
    crowdLevel: 'bustling',
    groupTypes: ['family', 'friends', 'solo'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:30',
    closeTime: '00:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.6,
    googleReviewCount: 3200,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 5400,
    theforkRating: 4.6,
    theforkReviewCount: 5400,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 5400,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Yamal+Acham+Rabat',
    bestDishes: ['Gourmet Syrian Shawarma', 'Creamy Hummus with Spiced Beef', 'Levantine Mixed Grill Skewers'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'It gets very crowded. Booking is highly advised, and make sure to start your feast with their incredible meze platters.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-rabat-9',
    city: 'rabat',
    name: 'Chez Bouchra',
    neighborhood: 'Medina',
    description: 'A highly famous, beloved street food stall in the heart of the Old Medina. Serving freshly-made authentic Moroccan griddle flatbreads, round batbouts, and comforting grain specialities.',
    pricePerPerson: 2.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast'],
    experienceTypes: ['Cozy casual family-run Moroccan eatery', 'Casual Dining', 'Local Gathering Spot'],
    foodStyles: ['Moroccan', 'Bakery'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '07:30',
    closeTime: '21:00',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.8,
    googleReviewCount: 150,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 150,
    theforkRating: 4.8,
    theforkReviewCount: 150,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 150,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Chez+Bouchra+Rabat+Medina',
    bestDishes: ['Rghaif (Stuffed Msemen)', 'Batbout with Kiri & Honey', 'Belboula (Barley Harcha)'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Order the rghaif (stuffed msemen with cheese or herbs) and a hot batbout spread with kiri and honey.',
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-rabat-10',
    city: 'rabat',
    name: 'Boho Café',
    neighborhood: 'Centre Ville',
    description: 'A brightly-lit, highly popular bohemian café and eatery in Rabat\'s city center. Renowned for its mix of healthy Western brunch staples and classic Moroccan breakfast options with great Wi-Fi.',
    pricePerPerson: 8.5,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Tranquil Dining'],
    foodStyles: ['Mediterranean', 'Healthy', 'Cafe'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'friends', 'couple'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:30',
    closeTime: '20:30',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.6,
    googleReviewCount: 310,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 310,
    theforkRating: 4.6,
    theforkReviewCount: 310,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 310,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Boho+Cafe+Rabat',
    bestDishes: ['Avocado Toast with Poached Eggs', 'Organic Açai Bowls', 'Waffles with Nutella'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'A phenomenal, quiet work-spot for digital nomads with plenty of power plugs and excellent acai bowls.',
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-rabat-11',
    city: 'rabat',
    name: 'Café Maure',
    neighborhood: 'Kasbah of the Udayas',
    description: 'Nestled beautifully within the historic stone fortress walls of the Kasbah, this famous open-air terrace café features blue and white tiled seating, traditional mint tea, and almond pastries with river views.',
    pricePerPerson: 4.5,
    lifestyle: 'lean',
    mealTypes: ['afternoon-tea'],
    experienceTypes: ['Cafe', 'Traditional Dining', 'Sunset Views'],
    foodStyles: ['Cafe', 'Moroccan', 'Bakery'],
    crowdLevel: 'bustling',
    groupTypes: ['couple', 'friends', 'solo', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '09:00',
    closeTime: '20:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.3,
    googleReviewCount: 3600,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 3600,
    theforkRating: 4.3,
    theforkReviewCount: 3600,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 3600,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Maure+Kasbah+Udayas+Rabat',
    bestDishes: ['Traditional Mint Tea', 'Kaab el Ghazal (Gazelle Horns)', 'Traditional Almond Ghriba'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Order your traditional pastries from the small cookie cart at the entrance before getting seated.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['terrace'],
    viewType: 'beach',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-rabat-12',
    city: 'rabat',
    name: 'Kasr Al Assil',
    neighborhood: 'Hassan',
    description: 'An elegant, highly-rated traditional restaurant in the Hassan district. It focuses strictly on serving perfectly prepared, authentic Moroccan staples like slow-simmered lamb tagines and Friday couscous.',
    pricePerPerson: 12,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Traditional Dining'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.4,
    googleReviewCount: 460,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 460,
    theforkRating: 4.4,
    theforkReviewCount: 460,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 460,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Kasr+Al+Assil+Rabat',
    bestDishes: ['Chicken Tagine with Olives & Lemon', 'Friday Beef Couscous', 'Moroccan Mixed Skewers'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Loved by locals for its small, focused menu which guarantees the utmost quality in every single tagine.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-rabat-13',
    city: 'rabat',
    name: 'Al Marsa',
    neighborhood: 'Bouregreg Marina',
    description: 'A highly sophisticated marina restaurant divided into two concepts sharing one name: one half serves outstanding Spanish seafood and paellas, and the other specializes in refined Japanese sushi.',
    pricePerPerson: 36,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Fine Seafood', 'Waterfront Dining'],
    foodStyles: ['Seafood', 'Spanish', 'Mediterranean'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:30',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.3,
    googleReviewCount: 1500,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 1500,
    theforkRating: 4.3,
    theforkReviewCount: 1500,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 1500,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Al+Marsa+Marina+Rabat',
    bestDishes: ['Seafood Paella', 'Fresh Sushi & Sashimi Boat', 'Salt-Baked Whole Fish'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Run by seafood wholesalers, guaranteeing exceptionally fresh ingredients. Grab outdoor terrace seating.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-rabat-14',
    city: 'rabat',
    name: 'Le Petit Beur',
    neighborhood: 'Centre Ville',
    description: 'Also known as Dar Tagine, this classic downtown institution marries authentic Moroccan gastronomy with French bistro details. Features pretty tiled walls, painted ceilings, and a long zellige bar.',
    pricePerPerson: 16,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Traditional Dining', 'Upscale Lounge'],
    foodStyles: ['Moroccan', 'French', 'Mediterranean'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'solo'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.4,
    googleReviewCount: 920,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 920,
    theforkRating: 4.4,
    theforkReviewCount: 920,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 920,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Le+Petit+Beur+Rabat',
    bestDishes: ['Seafood Pastilla', 'Harira Soup', 'Plum and Almond Lamb Tagine'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Their Seafood Pastilla is legendary in Rabat. Order it with a bowl of comforting Harira soup.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-rabat-15',
    city: 'rabat',
    name: 'Maison Sekouri',
    neighborhood: 'Medina / Central Market',
    description: 'A highly famous traditional Moroccan pastry shop founded in 1974, currently run by two sisters. Known for offering Rabat\'s absolute finest hand-baked chebakia, tartlets, and classic almond treats.',
    pricePerPerson: 5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'afternoon-tea', 'flexible'],
    experienceTypes: ['Cafe', 'Bakery-Patisserie', 'Traditional Breakfast Ritual'],
    foodStyles: ['Bakery', 'Moroccan', 'Patisserie'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '20:00',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.7,
    googleReviewCount: 180,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 180,
    theforkRating: 4.7,
    theforkReviewCount: 180,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 180,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Maison+Sekouri+Rabat',
    bestDishes: ['Handmade Chebakia', 'Savoury and Sweet Tartlets', 'Assorted Almond Pastries'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'An absolute must-visit during Ramadan or before leaving the country to buy gift boxes of handmade pastries.',
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: true,
    wheelchairAccessible: false
  },
  {
    id: 'e-rabat-16',
    city: 'rabat',
    name: 'Ty Potes',
    neighborhood: 'Hassan',
    description: 'A lovely, French-style garden café and restaurant located in the Hassan district. Highly regarded for its sweet crepes, buckwheat galettes, Sunday brunch, and an excellent European delicatessen.',
    pricePerPerson: 14,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'brunch'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Garden restaurant with live music'],
    foodStyles: ['French', 'European'],
    crowdLevel: 'balanced',
    groupTypes: ['friends', 'couple', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: false,
    openTime: '12:00',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.4,
    googleReviewCount: 980,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 980,
    theforkRating: 4.4,
    theforkReviewCount: 980,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 980,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Ty+Potes+Rabat',
    bestDishes: ['Salted Caramel Sweet Crepe', 'Savoyard Buckwheat Galette', 'European Cheese Board'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'The garden setting is extremely cozy. Perfect for a long, lazy Sunday brunch with friends.',
    bestTimeToVisit: 'Sunday morning for brunch peak',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-rabat-17',
    city: 'rabat',
    name: 'Al Warda',
    neighborhood: 'Souissi',
    description: 'The grand Moroccan fine-dining restaurant situated in the five-star Sofitel Rabat Jardin des Roses. Offers an inventive, refined take on classic Moroccan gastronomy in an opulent zellige-adorned dining room.',
    pricePerPerson: 48,
    lifestyle: 'premium',
    mealTypes: ['dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Upscale Lounge'],
    foodStyles: ['Moroccan', 'Gourmet'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '19:00',
    closeTime: '00:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.5,
    googleReviewCount: 410,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 410,
    theforkRating: 4.5,
    theforkReviewCount: 410,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 410,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['online', 'phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Al+Warda+Sofitel+Rabat',
    bestDishes: ['Marrakesh Lamb Tanjia', 'Royal Pigeon Pastilla', 'Fine Moroccan Salads'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Excellent service overseen by Chef Fatima Zohra. Ideal for a celebratory, candle-lit traditional Moroccan dinner.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 0,
    seatingTypes: ['indoor'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-rabat-18',
    city: 'rabat',
    name: 'Dar El Kebira',
    neighborhood: 'Medina / Rue des Consuls',
    description: 'A highly luxurious riad dining experience inside a masterfully restored Medina residence. Patrons enjoy traditional Moroccan dishes prepared with premium ingredients around a monumental fireplace.',
    pricePerPerson: 30,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Traditional Dining', 'Romantic Sunset'],
    foodStyles: ['Moroccan', 'Gourmet'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.6,
    googleReviewCount: 220,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 220,
    theforkRating: 4.6,
    theforkReviewCount: 220,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 220,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    googleMapsUrl: 'https://maps.google.com/?q=Dar+El+Kebira+Rabat',
    bestDishes: ['Chicken Rfissa with Tride', 'Royal Lamb Couscous', 'Sweet Almond Knafa'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Located near Rue des Consuls. An exceptional place to experience luxury homestyle cooking like lamb Rfissa.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },
  {
    id: 'e-rabat-19',
    city: 'rabat',
    name: 'Riad Kalaa Restaurant',
    neighborhood: 'Medina',
    description: 'Operating within a stunning arabo-andalusian noble riad built in 1815. It combines generous Moroccan hospitality with a refined selection of Moroccan-Mediterranean fusion dishes.',
    pricePerPerson: 25,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Traditional Dining'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Gourmet'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:30',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.5,
    googleReviewCount: 190,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 190,
    theforkRating: 4.5,
    theforkReviewCount: 190,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 190,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    googleMapsUrl: 'https://maps.google.com/?q=Riad+Kalaa+Rabat',
    bestDishes: ['Saffron Lamb Shank', 'Seafood Pastilla', 'Orange Cinnamon Salad'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    tip: 'Book a table in their beautiful orange tree patio or poolside courtyard to enjoy their creative dinner menu.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },
  {
    id: 'e-rabat-20',
    city: 'rabat',
    name: 'Restaurant La Libération',
    neighborhood: 'Medina',
    description: 'A long-running, highly authentic local diner in the old Medina. It does not offer complex decor, but it is highly trusted by locals for serving hot, fresh, and cheap bowls of harira, loubia (white beans), and tagines.',
    pricePerPerson: 3.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Traditional Dining', 'Local Gathering Spot'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:00',
    closeTime: '21:30',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.2,
    googleReviewCount: 280,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 280,
    theforkRating: 4.2,
    theforkReviewCount: 280,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 280,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+la+Liberation+Rabat',
    bestDishes: ['Moroccan Harira', 'Loubia (White Beans in Sauce)', 'Kefta Tagine'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'An absolute favorite for travelers looking for a completely honest, cheap homestyle meal. Harira is excellent.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  }
];