import type { EatListing } from '../types';

/**
 * EAT LISTING TEMPLATE
 * {
 *   id: 'e-[city]-[name]',
 *   city: '[city]',
 *   name: '[Name]',
 *   neighborhood: '[Neighborhood]',
 *   description: '[Long description]',
 *   pricePerPerson: [number],
 *   lifestyle: 'lean' | 'balanced' | 'premium',
 *   mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'latenight', 'afternoon-tea', 'flexible'],
 *   experienceTypes: ['Fine Dining' | 'Waterfront Dining' | 'Romantic Sunset' | 'Beachfront Dining' | 'Garden restaurant with live music' | 'Fountain courtyard' | 'French-Moroccan fusion' | 'Casual Italian Dining' | 'Family Pizza Night' | 'Spanish Beach Lounge' | 'Paella & Tapas' | 'Live Music Terrace' | 'Upscale Romantic Dining' | 'Fine Seafood' | 'Classic Royal Ambiance' | '24/7 Brasserie' | 'People Watching' | 'Bakery-Patisserie' | 'Traditional Breakfast Ritual' | 'Local Gathering Spot' | 'Fishing Harbor Dining' | 'Gourmet Seafood' | 'French-Italian Fusion' | 'Authentic Berber Feast' | 'Traditional Dining' | 'Cozy casual family-run Moroccan eatery' | 'Amazigh-inspired decor' | 'Beachfront Grill' | 'Casual Dining' | 'Sunset Views' | 'Wood-Fired Pizza' | 'Family Friendly' | 'Leafy Tennis Oasis' | 'Tranquil Dining' | 'Upscale Lounge' | 'Modern Fusion Dining' | 'Unverified'],
 *   foodStyles: ['French' | 'Moroccan' | 'Seafood' | 'Mediterranean' | 'European' | 'International' | 'Italian' | 'Pizza' | 'Spanish' | 'Berber' | 'Barbecue' | 'Middle Eastern' | 'Healthy' | 'Cafe' | 'Bakery' | 'Patisserie' | 'Gourmet' | 'Fast Food'],
 *   crowdLevel: 'bustling' | 'balanced' | 'quiet',
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *   hasEnglishStaff: true | false,
 *   hasFrenchStaff: true | false,
 *   hasDelivery: true | false,
 *   hasParking: true | false,
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearCenter: true | false,
 *   isVegetarianFriendly: true | false,
 *   isHalal: true | false,
 *   openTime: 'HH:mm',
 *   closeTime: 'HH:mm',
 *   badge: 'local-favorite' | 'splurge' | 'hidden-gem' | 'local',
 *   fullMenu: { type: 'image' | 'text', content: 'https://...' },
 *   tip: '[Short tip]',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   reservationContact: '+212XXXXXXXXX',
 *   bestDishes: ['Dish 1', 'Dish 2'],
 *   alcoholPolicy: 'serves-alcohol' | 'dry',
 *   ramadanFriendly: 'serves-lunch' | 'special-ftour' | 'closed',
 *   bestTimeToVisit: 'Early evening around 18:30 for sunset' | 'Lunch around 13:00 for quiet' | 'Late evening after 20:00 for lively crowd' | 'Early morning for fresh baked goods' | 'Sunday morning for brunch peak',
 *   averageWaitMinutes: 0 | 5 | 10 | 15 | 20 | 30 | 45 | 60,
 *   seatingTypes: ['indoor'] | ['terrace'] | ['rooftop'] | ['garden'] | ['beachfront'] | ['indoor', 'terrace'] | ['indoor', 'garden'] | ['terrace', 'rooftop'],
 *   viewType: 'beach' | 'mountain' | 'city' | 'garden' | 'none',
 *   wiFi: true | false,
 *   airConditioning: true | false,
 *   wheelchairAccessible: true | false,
 *   website: 'https://...',
 *   instagram: '@handle' | 'https://instagram.com/...'
 * }
 */

export const saidiaEat: EatListing[] = [
  {
    id: 'e-saidia-1',
    city: 'saidia',
    name: 'La Table du Green Teelal',
    neighborhood: 'Saidia Marina & Golf',
    description: 'An upscale golf-side lounge and restaurant offering breathtaking 360-degree panoramic views over the golf course greens and the Mediterranean sunset. Known for its elegant terraces, short but premium menu of meats and seafood, and high-vibe lounge music.',
    pricePerPerson: 35,
    lifestyle: 'premium',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch'],
    experienceTypes: ['Fine Dining', 'Upscale Lounge', 'Sunset Views'],
    foodStyles: ['International', 'Mediterranean', 'European'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:30',
    closeTime: '03:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 2.3,
    googleReviewCount: 10,
    tripadvisorRating: 2.3,
    tripadvisorReviewCount: 10,
    theforkRating: 2.3,
    theforkReviewCount: 10,
    restaurantguruRating: 2.3,
    restaurantguruReviewCount: 10,
    paymentMethods: ['card', 'cash'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212666525552',
    googleMapsUrl: 'https://maps.google.com/?q=La+Table+du+Green+Teelal+Saidia',
    bestDishes: ['Premium Ribeye Steak', 'Seafood Tapas Platter', 'Truffle Pasta'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Book a table on the panoramic sunset terrace around 19:30 for unmatched golf course and sea views.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-saidia-2',
    city: 'saidia',
    name: 'Samy Playa',
    neighborhood: 'Downtown Corniche',
    description: "A coastal favorite perched right on Saidia's golden beachfront. Famous for its generous portions of traditional Mediterranean baked sea bass tagines, seafood paella, and wood-fired pizzas.",
    pricePerPerson: 14,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Waterfront Dining', 'Beachfront Grill', 'Casual Dining'],
    foodStyles: ['Mediterranean', 'Moroccan', 'Pizza', 'Seafood'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly', 'large-groups'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '01:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.4,
    googleReviewCount: 10,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 10,
    theforkRating: 4.4,
    theforkReviewCount: 10,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 10,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Samy+Playa+Saidia',
    bestDishes: ['Sea Bass Tagine', 'Seafood Paella', 'Quattro Stagioni Pizza'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'The sea bass tagine with olives and potatoes cooked in a traditional clay pot is worth the wait.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'beachfront'],
    viewType: 'beach',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: true
  },
  {
    id: 'e-saidia-3',
    city: 'saidia',
    name: 'Nour : Restaurant de Poissons',
    neighborhood: 'Saidia Town Center',
    description: 'An authentic, no-frills local institution revered for serving the freshest Mediterranean fish catch. Highly renowned for its traditional grilled sardines, deep-fried squid, and classic Moroccan salads in a high-energy local setting.',
    pricePerPerson: 7.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Traditional Dining', 'Local Gathering Spot'],
    foodStyles: ['Seafood', 'Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'large-groups'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: false,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.3,
    googleReviewCount: 81,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 81,
    theforkRating: 4.3,
    theforkReviewCount: 81,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 81,
    paymentMethods: ['cash'],
    reservationMethod: ['phone', 'instagram'],
    reservationContact: '+212623306538',
    googleMapsUrl: 'https://maps.google.com/?q=Nour+Restaurant+de+Poissons+Saidia',
    bestDishes: ['Espadon (Swordfish) Skewers', 'Mixed Fish Friture', 'Seafood Soup'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'Go for the mixed friture platter (fried seafood combo) and order a side of traditional tomato-onion-pepper Moroccan salad.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-saidia-4',
    city: 'saidia',
    name: "L'Olivier Marina Saïdia",
    neighborhood: 'Marina de Saïdia',
    description: 'A delightful Mediterranean restaurant in the heart of Medina Mall Saïdia. Blends authentic French-Mediterranean bistro specialties with fresh local seafood, offering a peaceful terrace with panoramic marina harbor views.',
    pricePerPerson: 19,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'afternoon-tea'],
    experienceTypes: ['Waterfront Dining', 'Fine Dining', 'Casual Dining'],
    foodStyles: ['Mediterranean', 'French', 'Seafood'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'seniors', 'friends', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 3.8,
    googleReviewCount: 66,
    tripadvisorRating: 3.8,
    tripadvisorReviewCount: 66,
    theforkRating: 3.8,
    theforkReviewCount: 66,
    restaurantguruRating: 3.8,
    restaurantguruReviewCount: 66,
    paymentMethods: ['card', 'cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212536630230',
    googleMapsUrl: 'https://maps.google.com/?q=Olivier+Saidia+Marina',
    bestDishes: ['Grilled Seabream with Herbs', 'Olivier Beef Carpaccio', 'Warm Chocolate Fondant'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'Sit on the quiet, shaded terrace for a peaceful escape from the busy Marina shops. Their grilled sea bream with fresh herbs is excellent.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-saidia-5',
    city: 'saidia',
    name: 'Bravo Beach Club',
    neighborhood: 'Downtown Corniche',
    description: 'A massive, highly popular beachfront hub right on the sand of Saïdia Beach. Combines a lively pizzeria, seafood grill, and oceanfront cafe with upbeat vibes perfect for summer travelers.',
    pricePerPerson: 18,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Waterfront Dining', 'Beachfront Grill', 'Sunset Views'],
    foodStyles: ['Mediterranean', 'Italian', 'Moroccan', 'Pizza'],
    crowdLevel: 'bustling',
    groupTypes: ['family', 'kids-friendly', 'friends', 'couple'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '02:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 2.1,
    googleReviewCount: 17,
    tripadvisorRating: 2.1,
    tripadvisorReviewCount: 17,
    theforkRating: 2.1,
    theforkReviewCount: 17,
    restaurantguruRating: 2.1,
    restaurantguruReviewCount: 17,
    paymentMethods: ['card', 'cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Bravo+Beach+Club+Saidia',
    bestDishes: ['Seafood Pizza', 'Grilled Chicken Skewers', 'Mixed Seafood Friture'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'Perfect place for a long, lazy lunch on their grassy lawn in front of the beach. Try their wood-fired pizzas or gourmet burgers.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'beachfront', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-saidia-6',
    city: 'saidia',
    name: 'Small Fish Club',
    neighborhood: 'Downtown Corniche',
    description: 'A dynamic beachside eatery and family animation spot combined. Offers delicious local fish baskets, live family-friendly music in the evenings, and unpretentious beachfront dining with gorgeous views of the Mediterranean horizon.',
    pricePerPerson: 12,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Waterfront Dining', 'Family Friendly', 'Beachfront Grill'],
    foodStyles: ['Seafood', 'Mediterranean'],
    crowdLevel: 'bustling',
    groupTypes: ['family', 'kids-friendly', 'large-groups', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '01:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.3,
    googleReviewCount: 643,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 643,
    theforkRating: 4.3,
    theforkReviewCount: 643,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 643,
    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212662345678',
    googleMapsUrl: 'https://maps.google.com/?q=Small+Fish+Club+Saidia',
    bestDishes: ['Seafood Platter', 'Grilled Sole', 'Crispy Calamari Basket'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'Go in the late afternoon for their family animation shows. The fried calamari is a stellar snack.',
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'beachfront'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  },
  {
    id: 'e-saidia-7',
    city: 'saidia',
    name: 'La Corniche',
    neighborhood: 'Downtown Corniche',
    description: 'A spacious and lively establishment right on Boulevard Mohamed V. Known for its breezy panoramic windows facing the Mediterranean, delivering tasty Italian pastas, fresh grilled fish, and traditional Moroccan breakfast.',
    pricePerPerson: 9.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'flexible'],
    experienceTypes: ['Waterfront Dining', 'Casual Dining', 'Sunset Views'],
    foodStyles: ['Mediterranean', 'Italian', 'Moroccan'],
    crowdLevel: 'bustling',
    groupTypes: ['family', 'friends', 'kids-friendly', 'solo'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '23:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 3.9,
    googleReviewCount: 1316,
    tripadvisorRating: 3.9,
    tripadvisorReviewCount: 1316,
    theforkRating: 3.9,
    theforkReviewCount: 1316,
    restaurantguruRating: 3.9,
    restaurantguruReviewCount: 1316,
    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212536625141',
    googleMapsUrl: 'https://maps.google.com/?q=La+Corniche+Saidia',
    bestDishes: ['Spaghetti Frutti di Mare', 'Grilled Mediterranean Sardines', 'Classic Club Sandwich'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Great value-for-money spot. Order the fresh grilled Mediterranean sardines served with a cold glass of fresh juice.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-saidia-8',
    city: 'saidia',
    name: 'Tokyo Sushi Saïdia',
    neighborhood: 'Marina de Saïdia',
    description: 'A modern Asian-fusion destination in Saidia Marina. Frequented by summer crowds craving pristine sushi rolls, wok-fried noodles, and exotic fruit cocktails in a stylish, neon-lit seaside setting.',
    pricePerPerson: 19,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Modern Fusion Dining', 'Casual Dining'],
    foodStyles: ['International', 'Seafood'],
    crowdLevel: 'balanced',
    groupTypes: ['friends', 'couple', 'solo'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '13:00',
    closeTime: '01:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 3.1,
    googleReviewCount: 69,
    tripadvisorRating: 3.0,
    tripadvisorReviewCount: 2,
    theforkRating: 3.1,
    theforkReviewCount: 69,
    restaurantguruRating: 3.1,
    restaurantguruReviewCount: 69,
    paymentMethods: ['card', 'cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Tokyo+Sushi+Saidia',
    bestDishes: ['Dragon Roll', 'Beef Pad Thai', 'Shrimp Tempura'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Order their signature Dragon Rolls and Beef Pad Thai. Standard delivery is also available straight to your apartment or resort.',
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-saidia-9',
    city: 'saidia',
    name: 'Le Marbella',
    neighborhood: 'La Corniche',
    description: 'A legendary beachfront spot that beautifully blends Moroccan coast vibes with Andalusian style. Perfect for enjoying fresh grilled sardines, Mediterranean tapas, and sunset mocktails with front-row ocean wave views.',
    pricePerPerson: 14,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Waterfront Dining', 'Sunset Views', 'Beachfront Grill'],
    foodStyles: ['Spanish', 'Seafood', 'Mediterranean'],
    crowdLevel: 'bustling',
    groupTypes: ['friends', 'couple', 'solo'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:00',
    closeTime: '01:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.1,
    googleReviewCount: 220,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 26,
    theforkRating: 4.1,
    theforkReviewCount: 220,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 220,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212536625121',
    googleMapsUrl: 'https://maps.google.com/?q=Marbella+Saidia+La+Corniche',
    bestDishes: ['Grilled Sardines Marbella Style', 'Seafood Tapas Platter', 'Fresh Melon-Mint Cooler'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'Perfect for watching the sunset. Try their grilled sardines cooked Malaga-style on skewers near the beach sand.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'beachfront', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  },
  {
    id: 'e-saidia-10',
    city: 'saidia',
    name: 'Kim Club',
    neighborhood: 'Saidia Marina',
    description: 'A premium, stylish lounge and dining venue located close to the coastal hotel strip. Highly popular for its sophisticated Mediterranean food menu, live DJ sets, and evening cocktail culture.',
    pricePerPerson: 30,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Fine Dining', 'Upscale Lounge', 'Modern Fusion Dining'],
    foodStyles: ['Mediterranean', 'Seafood', 'European'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '13:00',
    closeTime: '03:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 3.6,
    googleReviewCount: 11,
    tripadvisorRating: 3.6,
    tripadvisorReviewCount: 11,
    theforkRating: 3.6,
    theforkReviewCount: 11,
    restaurantguruRating: 3.6,
    restaurantguruReviewCount: 11,
    paymentMethods: ['card', 'cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Kim+Club+Saidia',
    bestDishes: ['Lobster Thermidor', 'Premium Sushi Platters', 'Tenderloin Steak'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'The place truly wakes up after 22:00. Call in advance to reserve a table near the main pool area.',
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-saidia-11',
    city: 'saidia',
    name: 'Mardouma',
    neighborhood: 'Saidia Town Center',
    description: 'A unique and authentic local restaurant specializing in slow-cooked grilled meats cooked inside clay pits in the traditional "Mardouma" style of the Moroccan east, alongside authentic Oujda-style Tanjia.',
    pricePerPerson: 11,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Barbecue'],
    crowdLevel: 'balanced',
    groupTypes: ['family', 'friends', 'large-groups'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: false,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.0,
    googleReviewCount: 86,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 86,
    theforkRating: 4.0,
    theforkReviewCount: 86,
    restaurantguruRating: 4.0,
    restaurantguruReviewCount: 86,
    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Mardouma+Saidia',
    bestDishes: ['Mardouma Pit Roasted Lamb', 'Traditional Beef Tanjia', 'Eastern Mechoui'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Ask for their authentic slow-pit roasted lamb shoulder—the meat is so tender it falls right off the bone.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-saidia-12',
    city: 'saidia',
    name: 'Freshmed Eco 66',
    neighborhood: 'Marina de Saïdia',
    description: 'An eco-conscious restaurant focusing on fresh organic Mediterranean cooking. Uses clean, regionally sourced ingredients to design healthy options, fresh fish tagines, and hearty salads.',
    pricePerPerson: 15,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'brunch', 'lunch', 'dinner', 'afternoon-tea'],
    experienceTypes: ['Fine Dining', 'Waterfront Dining', 'Tranquil Dining'],
    foodStyles: ['Healthy', 'Mediterranean', 'Seafood'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'seniors', 'solo'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '09:00',
    closeTime: '22:30',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.5,
    googleReviewCount: 78,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 78,
    theforkRating: 4.5,
    theforkReviewCount: 78,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 78,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Freshmed+Eco+66+Saidia',
    bestDishes: ['Quinoa & Roasted Veggie Bowl', 'Organic Sea Bass Fillet', 'Cold-Pressed Green Juice'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'A superb spot for health-conscious diners. Try the organic sea bass fillet accompanied by a fresh green wellness juice.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-saidia-13',
    city: 'saidia',
    name: 'Venezia Ice Marina Saïdia',
    neighborhood: 'Marina de Saïdia',
    description: 'A famous Moroccan dessert and café franchise perched along the Saïdia Marina front. Known for its luxury artisanal ice creams, excellent crêpes, waffles, and scenic water views.',
    pricePerPerson: 8,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'brunch', 'afternoon-tea', 'latenight'],
    experienceTypes: ['Cafe', 'Waterfront Dining', 'Family Friendly'],
    foodStyles: ['Cafe', 'Italian', 'Bakery'],
    crowdLevel: 'bustling',
    groupTypes: ['family', 'kids-friendly', 'friends', 'couple'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '03:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 3.7,
    googleReviewCount: 550,
    tripadvisorRating: 3.7,
    tripadvisorReviewCount: 550,
    theforkRating: 3.7,
    theforkReviewCount: 550,
    restaurantguruRating: 3.7,
    restaurantguruReviewCount: 550,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Venezia+Ice+Marina+Saidia',
    bestDishes: ['Pistachio and Almond Waffles', 'Coppa Venezia Ice Cream Cup', 'Choc-Strawberry Crêpe'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'The outdoor seating on the Marina deck is unmatched. Grab a classic three-scoop sundae during the golden hour.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-saidia-14',
    city: 'saidia',
    name: 'Plaza',
    neighborhood: 'Saidia Marina',
    description: 'A modern, elegant café and restaurant inside the Medina Mall complex. Serves excellent Mediterranean pastas, grilled options, and elaborate coffee preparations in a cool air-conditioned environment.',
    pricePerPerson: 11,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'afternoon-tea'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Family Friendly'],
    foodStyles: ['Mediterranean', 'Italian', 'Cafe'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'friends', 'business-friendly', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '09:00',
    closeTime: '00:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 3.8,
    googleReviewCount: 72,
    tripadvisorRating: 3.8,
    tripadvisorReviewCount: 72,
    theforkRating: 3.8,
    theforkReviewCount: 72,
    restaurantguruRating: 3.8,
    restaurantguruReviewCount: 72,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Plaza+Medina+Mall+Saidia',
    bestDishes: ['Penne Alfredo', 'Gourmet Club Sandwich', 'Fresh Orange-Peach Smoothie'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Their breakfast sets are fantastic value and include fresh squeezed orange juice and organic olive oil.',
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-saidia-15',
    city: 'saidia',
    name: 'Snack Poisson Morad',
    neighborhood: 'Saidia Center',
    description: 'An incredibly popular, budget-friendly local street food stall in the old center. Known for lightning-fast fried calamari, grilled sardines, and spicy tomato dip at unbeatable prices.',
    pricePerPerson: 5.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Casual Dining', 'Quick Bites', 'Local Gathering Spot'],
    foodStyles: ['Seafood', 'Moroccan', 'Fast Food'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: false,
    isHalal: true,
    openTime: '11:00',
    closeTime: '22:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.4,
    googleReviewCount: 110,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 110,
    theforkRating: 4.4,
    theforkReviewCount: 110,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 110,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Snack+Poisson+Morad+Saidia',
    bestDishes: ['Crispy Fried Calamari', 'Grilled Sardine Filets', 'Moroccan Shada Salad'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Get the crispy fried calamari rings and request extra hot chili pepper oil on the side.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-saidia-16',
    city: 'saidia',
    name: 'Paloma Blanca',
    neighborhood: 'Saidia Center',
    description: 'A traditional, highly respected Moroccan restaurant offering classic family cuisine in the old central quarters. Serves perfect slow-cooked beef tagines, Friday couscous, and fresh Harira soup.',
    pricePerPerson: 10,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['family', 'couple', 'seniors', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:30',
    closeTime: '23:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 3.7,
    googleReviewCount: 6,
    tripadvisorRating: 3.7,
    tripadvisorReviewCount: 6,
    theforkRating: 3.7,
    theforkReviewCount: 6,
    restaurantguruRating: 3.7,
    restaurantguruReviewCount: 6,
    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Paloma+Blanca+Saidia',
    bestDishes: ['Seven Vegetable Couscous', 'Beef Tagine with Prunes', 'Harira Soup with Dates'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'This is the absolute best spot in town to eat traditional seven-vegetable couscous on a Friday.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-saidia-17',
    city: 'saidia',
    name: "O'Ptit Belge",
    neighborhood: 'Downtown Corniche',
    description: 'A relaxed, family-friendly Belgian-style quick bite parlor near the beach. Specializes in real hand-cut Belgian fries, sweet Liege waffles, crepes, and savory paninis.',
    pricePerPerson: 6,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'afternoon-tea', 'latenight'],
    experienceTypes: ['Casual Dining', 'Quick Bites', 'Family Friendly'],
    foodStyles: ['Fast Food', 'Bakery'],
    crowdLevel: 'bustling',
    groupTypes: ['kids-friendly', 'friends', 'solo', 'family'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:30',
    closeTime: '02:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.3,
    googleReviewCount: 112,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 112,
    theforkRating: 4.3,
    theforkReviewCount: 112,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 112,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=O+Ptit+Belge+Saidia',
    bestDishes: ['Liege Waffles with Cream', 'Authentic Belgian Fries with Samurai Sauce', 'Smoked Turkey Panini'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Get their fresh Liege waffle with hot chocolate sauce after a swim in the sea.',
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: true
  },
  {
    id: 'e-saidia-18',
    city: 'saidia',
    name: 'Beau Burger Saidia',
    neighborhood: 'Saidia Marina',
    description: 'An trendy shopper-friendly burger shop located inside Medina Mall. Popular with resort visitors and young crowds, offering gourmet smash burgers, thick onion rings, and creative milkshakes.',
    pricePerPerson: 9.5,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Casual Dining', 'Family Friendly'],
    foodStyles: ['International', 'Fast Food'],
    crowdLevel: 'balanced',
    groupTypes: ['friends', 'kids-friendly', 'solo'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '01:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 2.3,
    googleReviewCount: 275,
    tripadvisorRating: 2.3,
    tripadvisorReviewCount: 275,
    theforkRating: 2.3,
    theforkReviewCount: 275,
    restaurantguruRating: 2.3,
    restaurantguruReviewCount: 275,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Beau+Burger+Saidia',
    bestDishes: ['Double Smash Cheese Burger', 'Truffle Mayo Fries', 'Speculoos Milkshake'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'Their classic Cheese Smash Burger is very consistent and served on fresh brioche buns.',
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-saidia-19',
    city: 'saidia',
    name: 'Café Dubai',
    neighborhood: 'Downtown Corniche',
    description: 'A highly energetic café and lounge positioned close to the beachfront. Best known for hosting large sports-screening crowds, delicious fruit mocktails, and traditional Moroccan breakfast arrangements.',
    pricePerPerson: 7,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'afternoon-tea', 'flexible'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Local Gathering Spot'],
    foodStyles: ['Moroccan', 'Mediterranean', 'Cafe'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends', 'family'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '07:00',
    closeTime: '02:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.1,
    googleReviewCount: 145,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 145,
    theforkRating: 4.1,
    theforkReviewCount: 145,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 145,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Dubai+Saidia',
    bestDishes: ['Moroccan Avocado Milkshake', 'Creamy Crepe with Nutella', 'Mint Tea Pot'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'The outdoor terrace gets very busy during Champions League matches. Arrive early if you want a seat with a screen view.',
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'beach',
    wiFi: false,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-saidia-20',
    city: 'saidia',
    name: 'La Kasbah',
    neighborhood: 'Saidia Marina',
    description: 'A beautifully styled Moroccan concept restaurant situated in the Medina Mall of Saïdia. Blends upscale Moroccan interior aesthetics with high-quality tagines, royal pastillas, and spectacular warm hospitality.',
    pricePerPerson: 26,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Traditional Dining', 'Upscale Lounge'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'business-friendly', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.5,
    googleReviewCount: 88,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 88,
    theforkRating: 4.5,
    theforkReviewCount: 88,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 88,
    paymentMethods: ['card', 'cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=La+Kasbah+Medina+Mall+Saidia',
    bestDishes: ['Royal Pigeon Pastilla', 'Lamb Tagine with Apricots and Almonds', 'Seafood Pastilla'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'Their Royal Pigeon Pastilla is phenomenal and prepared with a perfect crunch and blend of sweet and savory spices.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  }
];