import type { EatListing } from '../types';

/**
 * EAT LISTING TEMPLATE
 * {
 *   id: 'e-[city]-[name]',
 *   city: '[city]',
 *   name: '[Name]',
 *   neighborhood: '[Neighborhood]',
 *   description: '[Long description]',
 *   pricePerPerson: [number],
 *   lifestyle: 'lean' | 'balanced' | 'premium',
 *   mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'latenight', 'afternoon-tea', 'flexible'],
 *   experienceTypes: ['Fine Dining' | 'Waterfront Dining' | 'Romantic Sunset' | 'Beachfront Dining' | 'Garden restaurant with live music' | 'Fountain courtyard' | 'French-Moroccan fusion' | 'Casual Italian Dining' | 'Family Pizza Night' | 'Spanish Beach Lounge' | 'Paella & Tapas' | 'Live Music Terrace' | 'Upscale Romantic Dining' | 'Fine Seafood' | 'Classic Royal Ambiance' | '24/7 Brasserie' | 'People Watching' | 'Bakery-Patisserie' | 'Traditional Breakfast Ritual' | 'Local Gathering Spot' | 'Fishing Harbor Dining' | 'Gourmet Seafood' | 'French-Italian Fusion' | 'Authentic Berber Feast' | 'Traditional Dining' | 'Cozy casual family-run Moroccan eatery' | 'Amazigh-inspired decor' | 'Beachfront Grill' | 'Casual Dining' | 'Sunset Views' | 'Wood-Fired Pizza' | 'Family Friendly' | 'Leafy Tennis Oasis' | 'Tranquil Dining' | 'Upscale Lounge' | 'Modern Fusion Dining' | 'Unverified'],
 *   foodStyles: ['French' | 'Moroccan' | 'Seafood' | 'Mediterranean' | 'European' | 'International' | 'Italian' | 'Pizza' | 'Spanish' | 'Berber' | 'Barbecue' | 'Middle Eastern' | 'Healthy' | 'Cafe' | 'Bakery' | 'Patisserie' | 'Gourmet' | 'Fast Food'],
 *   crowdLevel: 'bustling' | 'balanced' | 'quiet',
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *   hasEnglishStaff: true | false,
 *   hasFrenchStaff: true | false,
 *   hasDelivery: true | false,
 *   hasParking: true | false,
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearCenter: true | false,
 *   isVegetarianFriendly: true | false,
 *   isHalal: true | false,
 *   openTime: 'HH:mm',
 *   closeTime: 'HH:mm',
 *   badge: 'local-favorite' | 'splurge' | 'hidden-gem' | 'local',
 *   fullMenu: { type: 'image' | 'text', content: 'https://...' },
 *   tip: '[Short tip]',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   reservationContact: '+212XXXXXXXXX',
 *   bestDishes: ['Dish 1', 'Dish 2'],
 *   alcoholPolicy: 'serves-alcohol' | 'dry',
 *   ramadanFriendly: 'serves-lunch' | 'special-ftour' | 'closed',
 *   bestTimeToVisit: 'Early evening around 18:30 for sunset' | 'Lunch around 13:00 for quiet' | 'Late evening after 20:00 for lively crowd' | 'Early morning for fresh baked goods' | 'Sunday morning for brunch peak',
 *   averageWaitMinutes: 0 | 5 | 10 | 15 | 20 | 30 | 45 | 60,
 *   seatingTypes: ['indoor'] | ['terrace'] | ['rooftop'] | ['garden'] | ['beachfront'] | ['indoor', 'terrace'] | ['indoor', 'garden'] | ['terrace', 'rooftop'],
 *   viewType: 'beach' | 'mountain' | 'city' | 'garden' | 'none',
 *   wiFi: true | false,
 *   airConditioning: true | false,
 *   wheelchairAccessible: true | false,
 *   website: 'https://...',
 *   instagram: '@handle' | 'https://instagram.com/...'
 * }
 */

export const taghazoutEat: EatListing[] = [
  {
    id: 'e-taghazout-1',
    city: 'taghazout',
    name: 'World of Waves',
    neighborhood: 'Main Beachfront',
    description: 'An iconic beachfront boutique hotel restaurant directly overlooking Taghazout\'s main surf bay. Features sweeping ocean views, a lively atmosphere, and an international-Moroccan fusion menu.',
    pricePerPerson: 13,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'flexible'],
    experienceTypes: ['Waterfront Dining', 'Casual Dining', 'Beachfront Grill'],
    foodStyles: ['Mediterranean', 'Seafood', 'Moroccan'],
    crowdLevel: 'bustling',
    groupTypes: ['couple', 'friends', 'family', 'solo'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.4,
    googleReviewCount: 1850,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 1850,
    theforkRating: 4.4,
    theforkReviewCount: 1850,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 1850,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    googleMapsUrl: 'https://maps.google.com/?q=World+of+Waves+Taghazout',
    bestDishes: ['Shrimp Curry', 'Ocean Seafood Pasta', 'Moroccan Shakshuka Breakfast'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'One of the few spots in the main village that serves cold beer and wine. Excellent sunset terrace views.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  },
  {
    id: 'e-taghazout-2',
    city: 'taghazout',
    name: 'Teapot Cafe',
    neighborhood: 'Main Street',
    description: 'The premier daytime coworking and healthy brunch cafe in Taghazout. Highly popular with digital nomads, offering excellent specialty coffee, fresh juices, and colorful vegan-friendly smoothie bowls.',
    pricePerPerson: 9,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'brunch', 'flexible'],
    experienceTypes: ['Cafe', 'Casual Dining'],
    foodStyles: ['Mediterranean', 'Healthy', 'Cafe'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:30',
    closeTime: '20:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.5,
    googleReviewCount: 920,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 920,
    theforkRating: 4.5,
    theforkReviewCount: 920,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 920,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Teapot+Cafe+Taghazout',
    bestDishes: ['Avocado Poached Eggs on Toast', 'Açai Power Bowl', 'Iced Almond Latte'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'The upper-floor coworking loft has great natural light, robust Wi-Fi, and multiple power outlets—perfect for remote work.',
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  },
  {
    id: 'e-taghazout-3',
    city: 'taghazout',
    name: 'Chez Titrite',
    neighborhood: 'Main Street',
    description: 'A beloved traditional and international diner run by a local Moroccan female chef. Highly famous in town for preparing delicious homestyle stews, ramen, and gourmet burgers at incredible budget prices.',
    pricePerPerson: 7.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Mediterranean'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.8,
    googleReviewCount: 410,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 410,
    theforkRating: 4.8,
    theforkReviewCount: 410,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 410,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Chez+Titrite+Taghazout',
    bestDishes: ['Berber Plum Beef Tagine', 'Gourmet Lamb Burger', 'Authentic Ramen'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Chef Titrite travels the world to find unique spices for her dishes. Try her slow-cooked beef tagine or her amazing burgers with crispy local fries.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-taghazout-4',
    city: 'taghazout',
    name: 'Red Clay Cafe',
    neighborhood: 'Main Street',
    description: 'A fully vegan restaurant and specialty coffee shop run by a welcoming Moroccan-British couple. Serves delicious plant-based lunches, wholesome bowls, and outstanding oat milk flat whites.',
    pricePerPerson: 8.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'brunch', 'flexible'],
    experienceTypes: ['Cafe', 'Casual Dining'],
    foodStyles: ['Healthy', 'Mediterranean', 'Cafe'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:30',
    closeTime: '18:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.7,
    googleReviewCount: 380,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 380,
    theforkRating: 4.7,
    theforkReviewCount: 380,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 380,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Red+Clay+Cafe+Taghazout',
    bestDishes: ['Spiced Falafel Bowl', 'Oat Milk Flat White', 'Vegan Banana Bread'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'The best place in Taghazout for third-wave specialty coffee. They use fresh oat milk and make everything with immense passion.',
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  },
  {
    id: 'e-taghazout-5',
    city: 'taghazout',
    name: 'Le Spot',
    neighborhood: 'Main Street',
    description: 'The local go-to everyday bistro in Taghazout village. It offers an extensive, highly reliable menu of thin-crust Italian pizzas, fresh pastas, seafood plates, and sweet crêpes.',
    pricePerPerson: 9,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Casual Dining', 'Family Friendly', 'Wood-Fired Pizza'],
    foodStyles: ['Italian', 'Seafood', 'Moroccan', 'Pizza'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:30',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.4,
    googleReviewCount: 1100,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 1100,
    theforkRating: 4.4,
    theforkReviewCount: 1100,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 1100,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Le+Spot+Taghazout',
    bestDishes: ['Taghazout Seafood Pizza', 'Alfredo Chicken Penne', 'Sweet Nutella Crêpe'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Always busy and offers quick service. Their seafood pizza and savory crepes are perfect for refueling after a long day of surfing.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  },
  {
    id: 'e-taghazout-6',
    city: 'taghazout',
    name: "Munga's Kitchen",
    neighborhood: 'Main Street / Village Center',
    description: 'An award-winning, exceptionally cozy restaurant inside the artistic Munga Guesthouse. Decorated beautifully with driftwood and antique surfboards, it serves creative wood-fired sourdough pizzas, fresh salads, and local seafood.',
    pricePerPerson: 16,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Casual Dining', 'Wood-Fired Pizza'],
    foodStyles: ['Mediterranean', 'Seafood', 'Italian', 'Pizza'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.6,
    googleReviewCount: 750,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 750,
    theforkRating: 4.6,
    theforkReviewCount: 750,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 750,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Mungas+Kitchen+Taghazout',
    bestDishes: ['Sourdough Seafood Pizza', 'Seared Yellowfin Tuna', 'Warm Goat Cheese Salad'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Their sourdough pizzas are legendary in Taghazout Bay. The atmosphere is highly creative and relaxing.',
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },
  {
    id: 'e-taghazout-7',
    city: 'taghazout',
    name: 'Kitchen Club Taghazout',
    neighborhood: 'Taghazout Bay / Seaside',
    description: 'A gorgeous, upscale poolside restaurant and cocktail lounge situated in the Seaside Boutique Hotel. It merges clean Moroccan-Mediterranean gastronomy with stunning beachfront deck views and twinkly fairy lights.',
    pricePerPerson: 25,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner', 'brunch', 'flexible'],
    experienceTypes: ['Fine Dining', 'Waterfront Dining', 'Romantic Sunset', 'Upscale Lounge'],
    foodStyles: ['Mediterranean', 'Seafood', 'Moroccan', 'Gourmet'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '00:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.5,
    googleReviewCount: 310,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 310,
    theforkRating: 4.5,
    theforkReviewCount: 310,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 310,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['online', 'phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Kitchen+Club+Seaside+Taghazout',
    bestDishes: ['Mediterranean Mezze Board', 'Charcoal-Grilled Squid', 'Beef Ribeye Steak'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Perfect when you want to get dressed up for a special evening. Excellent tapas-style sharing platters and handcrafted sunset cocktails.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'beachfront', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-taghazout-8',
    city: 'taghazout',
    name: 'Amouage',
    neighborhood: 'Beachfront',
    description: 'The ultra-trendy beachfront restaurant and cocktail bar at Surf Maroc\'s flagship Amouage boutique hotel. Built around a stunning infinity pool, it serves creative fusion plates and sunset cocktails with ocean views.',
    pricePerPerson: 18,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'flexible'],
    experienceTypes: ['Waterfront Dining', 'Beachfront Grill', 'Sunset Views', 'Upscale Lounge'],
    foodStyles: ['Mediterranean', 'Seafood', 'Moroccan'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'friends', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '01:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.4,
    googleReviewCount: 1400,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 1400,
    theforkRating: 4.4,
    theforkReviewCount: 1400,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 1400,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    googleMapsUrl: 'https://maps.google.com/?q=Amouage+Taghazout',
    bestDishes: ['Spiced Lamb Chops', 'Grilled Sea Bass', 'Moroccan Night Buffet'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Don\'t miss their legendary Monday and Thursday evening pool-side BBQs and Moroccan Nights, which require prepaid reservations.',
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor', 'beachfront', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-taghazout-9',
    city: 'taghazout',
    name: 'Windy Bay',
    neighborhood: 'Main Beachfront',
    description: 'A beautifully relaxed, highly popular oceanfront café directly on the village promenade. Famed for its breezy beachfront terrace, excellent Italian pizzas, and classic continental breakfast boards.',
    pricePerPerson: 11,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'flexible'],
    experienceTypes: ['Cafe', 'Casual Dining', 'Waterfront Dining'],
    foodStyles: ['Mediterranean', 'Italian', 'Cafe'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.2,
    googleReviewCount: 1650,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 1650,
    theforkRating: 4.2,
    theforkReviewCount: 1650,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 1650,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Windy+Bay+Taghazout',
    bestDishes: ['Pizza Windy Bay', 'Healthy Fruit Smoothie Bowl', 'Smoked Salmon Eggs Benedict'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'Perfect spot for a lazy seaside breakfast. Sit on the lower deck to watch local fishermen and surfers directly in front of you.',
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'beachfront'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  },
  {
    id: 'e-taghazout-10',
    city: 'taghazout',
    name: 'Dar Josephine',
    neighborhood: 'Main Street / Village Center',
    description: 'An intimate, highly charming restaurant nestled in a peaceful, leafy garden patio. It specializes in offering a refined, quiet fusion of French bistro classics and traditional Moroccan slow-cooked stews.',
    pricePerPerson: 15,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Garden restaurant with live music'],
    foodStyles: ['French', 'Moroccan', 'Mediterranean'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.6,
    googleReviewCount: 520,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 520,
    theforkRating: 4.6,
    theforkReviewCount: 520,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 520,
    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Dar+Josephine+Taghazout',
    bestDishes: ['Slow-roasted Beef Pastilla', 'Classic French Beef Bourguignon', 'Goat Cheese and Olive Tart'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'The garden setting is incredibly quiet and romantic. Their slow-roasted beef pastilla and chocolate mousse are exceptional.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-taghazout-11',
    city: 'taghazout',
    name: 'Cafe Mouja',
    neighborhood: 'Anchor Point Road',
    description: 'A stylish, surf-inspired seaside café operated by Surf Maroc. Boasting great ocean views over Hash Point, it serves fantastic organic healthy wraps, cold-pressed juices, and healthy breakfasts.',
    pricePerPerson: 10,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'brunch', 'flexible'],
    experienceTypes: ['Cafe', 'Sunset Views', 'Casual Dining'],
    foodStyles: ['Mediterranean', 'Healthy', 'Cafe'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '20:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.4,
    googleReviewCount: 880,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 880,
    theforkRating: 4.4,
    theforkReviewCount: 880,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 880,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Mouja+Taghazout',
    bestDishes: ['Mighty Green Protein Bowl', 'Avocado Toast with Poached Egg', 'Cold-Pressed Ginger Turmeric Shot'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'A digital-nomad favorite. They have great Wi-Fi, healthy protein-rich bowls, and views directly over the surf.',
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  },
  {
    id: 'e-taghazout-12',
    city: 'taghazout',
    name: 'Bohemian Berber Bar',
    neighborhood: 'Ocean Rocks',
    description: 'An incredibly atmospheric sunset and tapas bar set directly on the jagged sea rocks of Taghazout. Guests sit on low lounge beds right at the water\'s edge, enjoying ocean breezes, meze, and drinks.',
    pricePerPerson: 16,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'latenight', 'flexible'],
    experienceTypes: ['Waterfront Dining', 'Sunset Views', 'Upscale Lounge'],
    foodStyles: ['Mediterranean', 'Seafood'],
    crowdLevel: 'bustling',
    groupTypes: ['couple', 'friends', 'solo'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '16:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.5,
    googleReviewCount: 480,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 480,
    theforkRating: 4.5,
    theforkReviewCount: 480,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 480,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Bohemian+Berber+Bar+Taghazout',
    bestDishes: ['Tapas Sharing Platter', 'Fried Calamari with Alioli', 'Taghazout Sunset Spritz'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'closed',
    tip: 'The ultimate sunset spot in Taghazout. Arrive around 5 PM to secure a couch directly on the rocks.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 15,
    seatingTypes: ['beachfront', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-taghazout-13',
    city: 'taghazout',
    name: 'Taghazout Tajine Palace',
    neighborhood: 'Main Street',
    description: 'An authentic, highly popular local Moroccan joint in the center of Taghazout village. It is deeply loved by locals and surfers for its honest, slow-cooked clay-pot tagines and fresh Moroccan bread.',
    pricePerPerson: 5.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Traditional Dining', 'Casual Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:30',
    closeTime: '23:30',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.6,
    googleReviewCount: 1300,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 1300,
    theforkRating: 4.6,
    theforkReviewCount: 1300,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 1300,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Taghazout+Tajine+Palace',
    bestDishes: ['Berber Beef and Prune Tagine', 'Lemon Chicken Tagine', 'Freshly Cooked Harira Soup'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Excellent and very cheap local Moroccan food. Grab a table outside and try their slow-simmered beef and prune tagine.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-taghazout-14',
    city: 'taghazout',
    name: 'Snack Ida Omahmod',
    neighborhood: 'Main Street',
    description: 'The most famous cheap eat and local Moroccan fast-food barbecue counter in Taghazout. Always buzzing with local surfers ordering freshly seared skewers and fries inside local bread.',
    pricePerPerson: 3.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Casual Dining', 'Quick Bites', 'Local Gathering Spot'],
    foodStyles: ['Moroccan', 'Fast Food'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: false,
    isHalal: true,
    openTime: '11:00',
    closeTime: '01:30',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.5,
    googleReviewCount: 380,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 380,
    theforkRating: 4.5,
    theforkReviewCount: 380,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 380,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Snack+Ida+Omahmod+Taghazout',
    bestDishes: ['Spiced Kofta Sandwich', 'Merguez Sausage Skewers', 'Fresh Fries Box'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Get the spiced kefta mixed sandwich with extra harissa. Unbelievably cheap, filling, and packed with local flavor.',
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-taghazout-15',
    city: 'taghazout',
    name: 'Sunset Burger',
    neighborhood: 'Anchor Point Road',
    description: 'A vibrant burger joint perched on the cliffs overlooking the Taghazout coastline. Offers incredible panoramas of the sea, serving delicious gourmet beef, chicken, and vegetarian burgers.',
    pricePerPerson: 8,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Casual Dining', 'Sunset Views'],
    foodStyles: ['Mediterranean', 'International', 'Fast Food'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.3,
    googleReviewCount: 650,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 650,
    theforkRating: 4.3,
    theforkReviewCount: 650,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 650,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Sunset+Burger+Taghazout',
    bestDishes: ['Classic Cheese Burger', 'Spicy Crispy Chicken Burger', 'Sweet Potato Fries'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'A great post-surf meal. Grab a window table around 6 PM to enjoy a massive craft burger while the sun sets over the ocean.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  },
  {
    id: 'e-taghazout-16',
    city: 'taghazout',
    name: 'Cafe Taliouine',
    neighborhood: 'Main Street / Village Center',
    description: 'A simple, highly authentic local café specializing in traditional clay-pot tagines and Moroccan cooked salads. Offers friendly local service and great street-side outdoor seating.',
    pricePerPerson: 6.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Traditional Dining', 'Local Gathering Spot'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:30',
    closeTime: '22:30',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.4,
    googleReviewCount: 420,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 420,
    theforkRating: 4.4,
    theforkReviewCount: 420,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 420,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Taliouine+Taghazout',
    bestDishes: ['Chicken Tagine with Olives & Lemon', 'Kefta Tagine with Egg', 'Moroccan Cooked Salads'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Very simple but exceptionally honest Moroccan cooking. Their slow-simmered chicken tagine with lemon and olives is highly satisfying.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-taghazout-17',
    city: 'taghazout',
    name: 'Taghazout Fish Market',
    neighborhood: 'Main Beachfront / Port',
    description: 'The ultimate seaside seafood experience in Taghazout. Select your fresh raw fish directly from local fishermen and have it grilled immediately on open coals right on the harbor promenade.',
    pricePerPerson: 10,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Fishing Harbor Dining', 'Casual Dining', 'Local Gathering Spot'],
    foodStyles: ['Seafood'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: false,
    isHalal: true,
    openTime: '11:00',
    closeTime: '21:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.5,
    googleReviewCount: 1200,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 1200,
    theforkRating: 4.5,
    theforkReviewCount: 1200,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 1200,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Taghazout+Fish+Market',
    bestDishes: ['Coal-Grilled Sardines', 'Grilled Jumbo Prawns', 'Crispy Squid Skewers'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    tip: 'Always ask to include local sardines, giant prawns, and squid in your mix. Negotiate your plate price before sitting down.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'beach',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: true
  },
  {
    id: 'e-taghazout-18',
    city: 'taghazout',
    name: 'La Favella',
    neighborhood: 'Main Street / Village Center',
    description: 'A funky, vibrant Italian-Moroccan pizzeria and bistro with a cozy rooftop terrace. Celebrated for its thin-crust wood-fired pizzas, hearty pasta bowls, and cozy Mediterranean design.',
    pricePerPerson: 11,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Italian Dining', 'Romantic Sunset', 'Wood-Fired Pizza'],
    foodStyles: ['Italian', 'Seafood', 'Mediterranean', 'Pizza'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.2,
    googleReviewCount: 650,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 650,
    theforkRating: 4.2,
    theforkReviewCount: 650,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 650,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=La+Favella+Taghazout',
    bestDishes: ['Pizza La Favella', 'Shrimp Spaghetti', 'Caprese Salad'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Their rooftop terrace is lovely and secluded, offering a peaceful dinner away from the bustling main street sounds.',
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'rooftop'],
    viewType: 'city',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-taghazout-19',
    city: 'taghazout',
    name: 'Paper Moon Taghazout',
    neighborhood: 'Taghazout Bay / Fairmont',
    description: 'A world-class, premium Italian culinary institution situated inside the five-star Fairmont Taghazout Bay. Offers an ultra-elegant, sophisticated dining experience with authentic Milanese dishes and panoramic ocean views.',
    pricePerPerson: 42,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Waterfront Dining'],
    foodStyles: ['Italian', 'Seafood', 'Mediterranean', 'Gourmet'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'seniors', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:30',
    closeTime: '23:30',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.6,
    googleReviewCount: 220,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 220,
    theforkRating: 4.6,
    theforkReviewCount: 220,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 220,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['online', 'phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Paper+Moon+Fairmont+Taghazout+Bay',
    bestDishes: ['Milanese Veal Cutlet', 'House-made Gnocchi', 'Paper Moon Tiramisu'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'The pinnacle of high-end Italian dining in Taghazout Bay. Dress strictly smart-casual and reserve a window table for sunset.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 0,
    seatingTypes: ['indoor'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-taghazout-20',
    city: 'taghazout',
    name: 'Beef and Reef',
    neighborhood: 'Taghazout Bay / Fairmont',
    description: 'The ultimate upscale outdoor steak and seafood restaurant at the Fairmont Taghazout Bay. Features poolside and oceanfront dining with premium charcoal-grilled meats and daily Atlantic ocean catches.',
    pricePerPerson: 38,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Waterfront Dining', 'Beachfront Grill'],
    foodStyles: ['Seafood', 'Mediterranean', 'European', 'Gourmet'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.5,
    googleReviewCount: 310,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 310,
    theforkRating: 4.5,
    theforkReviewCount: 310,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 310,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['online', 'phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Beef+and+Reef+Fairmont+Taghazout+Bay',
    bestDishes: ['Charcoal-grilled Wagyu Ribeye', 'Sea Bass in Salt Crust', 'Spiced Grilled Lobster'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Perfect poolside dining during the day. Try their exceptional Wagyu beef cuts or the sea bass in salt crust.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'beachfront', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  }
];