import type { EatListing } from '../types';

/**
 * EAT LISTING TEMPLATE
 * {
 *   id: 'e-[city]-[name]',
 *   city: '[city]',
 *   name: '[Name]',
 *   neighborhood: '[Neighborhood]',
 *   description: '[Long description]',
 *   pricePerPerson: [number],
 *   lifestyle: 'lean' | 'balanced' | 'premium',
 *   mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'latenight', 'afternoon-tea', 'flexible'],
 *   experienceTypes: ['Fine Dining' | 'Waterfront Dining' | 'Romantic Sunset' | 'Beachfront Dining' | 'Garden restaurant with live music' | 'Fountain courtyard' | 'French-Moroccan fusion' | 'Casual Italian Dining' | 'Family Pizza Night' | 'Spanish Beach Lounge' | 'Paella & Tapas' | 'Live Music Terrace' | 'Upscale Romantic Dining' | 'Fine Seafood' | 'Classic Royal Ambiance' | '24/7 Brasserie' | 'People Watching' | 'Bakery-Patisserie' | 'Traditional Breakfast Ritual' | 'Local Gathering Spot' | 'Fishing Harbor Dining' | 'Gourmet Seafood' | 'French-Italian Fusion' | 'Authentic Berber Feast' | 'Traditional Dining' | 'Cozy casual family-run Moroccan eatery' | 'Amazigh-inspired decor' | 'Beachfront Grill' | 'Casual Dining' | 'Sunset Views' | 'Wood-Fired Pizza' | 'Family Friendly' | 'Leafy Tennis Oasis' | 'Tranquil Dining' | 'Upscale Lounge' | 'Modern Fusion Dining' | 'Unverified'],
 *   foodStyles: ['French' | 'Moroccan' | 'Seafood' | 'Mediterranean' | 'European' | 'International' | 'Italian' | 'Pizza' | 'Spanish' | 'Berber' | 'Barbecue' | 'Middle Eastern' | 'Healthy' | 'Cafe' | 'Bakery' | 'Patisserie' | 'Gourmet' | 'Fast Food'],
 *   crowdLevel: 'bustling' | 'balanced' | 'quiet',
 *   groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors', 'kids-friendly', 'large-groups', 'business-friendly'],
 *   hasEnglishStaff: true | false,
 *   hasFrenchStaff: true | false,
 *   hasDelivery: true | false,
 *   hasParking: true | false,
 *   nearMedina: true | false,
 *   nearBeach: true | false,
 *   nearCenter: true | false,
 *   isVegetarianFriendly: true | false,
 *   isHalal: true | false,
 *   openTime: 'HH:mm',
 *   closeTime: 'HH:mm',
 *   badge: 'local-favorite' | 'splurge' | 'hidden-gem' | 'local',
 *   fullMenu: { type: 'image' | 'text', content: 'https://...' },
 *   tip: '[Short tip]',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   reservationContact: '+212XXXXXXXXX',
 *   bestDishes: ['Dish 1', 'Dish 2'],
 *   alcoholPolicy: 'serves-alcohol' | 'dry',
 *   ramadanFriendly: 'serves-lunch' | 'special-ftour' | 'closed',
 *   bestTimeToVisit: 'Early evening around 18:30 for sunset' | 'Lunch around 13:00 for quiet' | 'Late evening after 20:00 for lively crowd' | 'Early morning for fresh baked goods' | 'Sunday morning for brunch peak',
 *   averageWaitMinutes: 0 | 5 | 10 | 15 | 20 | 30 | 45 | 60,
 *   seatingTypes: ['indoor'] | ['terrace'] | ['rooftop'] | ['garden'] | ['beachfront'] | ['indoor', 'terrace'] | ['indoor', 'garden'] | ['terrace', 'rooftop'],
 *   viewType: 'beach' | 'mountain' | 'city' | 'garden' | 'none',
 *   wiFi: true | false,
 *   airConditioning: true | false,
 *   wheelchairAccessible: true | false,
 *   website: 'https://...',
 *   instagram: '@handle' | 'https://instagram.com/...'
 * }
 */

export const tangierEat: EatListing[] = [
  {
    id: 'e-tangier-1',
    city: 'tangier',
    name: 'Café Hafa',
    neighborhood: 'Marchan',
    description: 'A legendary clifftop café operating since 1921. Built on stepped stone terraces overlooking the Strait of Gibraltar, this historic cultural institution has hosted the Beatles, the Rolling Stones, and Paul Bowles.',
    pricePerPerson: 3,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'afternoon-tea', 'flexible'],
    experienceTypes: ['Cafe', 'Traditional Dining', 'Sunset Views'],
    foodStyles: ['Moroccan', 'Cafe'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'friends', 'family', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '09:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.4,
    googleReviewCount: 4800,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 4800,
    theforkRating: 4.4,
    theforkReviewCount: 4800,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 4800,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Hafa+Tangier',
    bestDishes: ['Maghrebi Mint Tea', 'Northern Bissara Soup', 'Harcha Bread with Honey'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Find a seat on the lower terraces at sunset, order a glass of sweet Northern mint tea, and try their traditional fava bean bissara soup.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'beach',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-tangier-2',
    city: 'tangier',
    name: 'Gran Café de Paris',
    neighborhood: 'Place de France',
    description: 'The ultimate literary coffeehouse in Tangier, situated right across from the French Consulate. Famous for its 1920s Art Deco interior, its status as a spy-gathering hub in WWII, and its cameo in The Bourne Ultimatum.',
    pricePerPerson: 4,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'afternoon-tea', 'flexible'],
    experienceTypes: ['Cafe', 'Traditional Dining', 'People Watching'],
    foodStyles: ['Cafe', 'French', 'Bakery'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '07:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.0,
    googleReviewCount: 3100,
    tripadvisorRating: 4.0,
    tripadvisorReviewCount: 3100,
    theforkRating: 4.0,
    theforkReviewCount: 3100,
    restaurantguruRating: 4.0,
    restaurantguruReviewCount: 3100,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Gran+Cafe+de+Paris+Tangier',
    bestDishes: ['Cafe au Lait', 'Croissant aux Amandes', 'Espresso Chamali'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Sit on the leather banquettes indoors or get a street-facing window seat to experience classic "people-watching," just as Paul Bowles and William S. Burroughs did.',
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-tangier-3',
    city: 'tangier',
    name: 'Café Baba',
    neighborhood: 'Kasbah',
    description: 'An iconic, cozy, and proudly rough-around-the-edges café located just inside the Kasbah walls. Visited by rock-and-roll legends and literary figures, it remains a relaxed place for locals and travelers.',
    pricePerPerson: 2.5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'afternoon-tea', 'flexible'],
    experienceTypes: ['Cafe', 'Traditional Dining', 'Local Gathering Spot'],
    foodStyles: ['Moroccan', 'Cafe'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '09:00',
    closeTime: '23:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.2,
    googleReviewCount: 1200,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 1200,
    theforkRating: 4.2,
    theforkReviewCount: 1200,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 1200,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Baba+Tangier',
    bestDishes: ['Maghrebi Mint Tea', 'Cafe Noir', 'Local Moroccan Pastries'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Look at the historic photos on the walls, including Keith Richards and Jimi Hendrix chilling right where you are sitting.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-tangier-4',
    city: 'tangier',
    name: 'Saveur de Poisson',
    neighborhood: 'Medina / Escalier Waller',
    description: 'An iconic, highly rustic dining tavern renowned for its fixed-price seafood menu. Guests are treated to fresh fish cooked in clay pots, traditional wood-fired grilled skewers, and unique local herbal juices.',
    pricePerPerson: 25,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Casual Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Seafood', 'Moroccan'],
    crowdLevel: 'bustling',
    groupTypes: ['couple', 'family', 'friends', 'large-groups'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: false,
    isHalal: true,
    openTime: '12:30',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.5,
    googleReviewCount: 2200,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 2200,
    theforkRating: 4.5,
    theforkReviewCount: 2200,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 2200,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Saveur+de+Poisson+Tangier',
    bestDishes: ['Herbal Fish Soup', 'Skewered Shark & Tuna', 'Clay-Pot Fish Tagine'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'There is no written menu; you sit down and get served a multi-course meal starting with dynamic fish soup and ending with a special honey-nut dessert.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 15,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-tangier-5',
    city: 'tangier',
    name: 'El Morocco Club',
    neighborhood: 'Kasbah',
    description: 'An upscale, elegant French-Moroccan bistro and piano bar in the historic Kasbah. Built around a beautiful centuries-old ficus tree, it offers a sophisticated menu, classy cocktails, and jazz music.',
    pricePerPerson: 38,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner', 'latenight'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Upscale Lounge'],
    foodStyles: ['French', 'Mediterranean', 'Moroccan', 'Gourmet'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '01:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.5,
    googleReviewCount: 1400,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 1400,
    theforkRating: 4.5,
    theforkReviewCount: 1400,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 1400,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212539913318',
    googleMapsUrl: 'https://maps.google.com/?q=El+Morocco+Club+Tangier',
    bestDishes: ['John Dory with Saffron Risotto', 'Slow-Cooked Duck Confit', 'Seared Octopus with Puree'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Book in advance for a dinner reservation upstairs, then head down to the cozy subterranean piano bar for a cocktail after 10 PM.',
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 0,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },
  {
    id: 'e-tangier-6',
    city: 'tangier',
    name: "Casa d'Italia",
    neighborhood: 'Marchan',
    description: "Located inside the magnificent Palace of Italian Institutions (Palais Moulay Hafid), this elegant restaurant features classical decor, a gorgeous private garden terrace, and top-tier Italian gastronomy.",
    pricePerPerson: 22,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Garden restaurant with live music', 'Romantic Sunset'],
    foodStyles: ['Italian', 'Seafood', 'Mediterranean', 'European'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'seniors', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: false,
    openTime: '12:30',
    closeTime: '23:00',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.4,
    googleReviewCount: 780,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 780,
    theforkRating: 4.4,
    theforkReviewCount: 780,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 780,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212539335020',
    googleMapsUrl: 'https://maps.google.com/?q=Casa+d+Italia+Tangier',
    bestDishes: ['Handmade Seafood Linguine', 'Wood-Fired Pizza Margherita', 'Classic Panna Cotta'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Stroll around the palace grounds before sitting down. Their house-made pastas and fresh seafood salads are favored heavily by local elites.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-tangier-7',
    city: 'tangier',
    name: 'Le Relais de Paris',
    neighborhood: 'Malabata / Beachfront',
    description: 'A superb waterfront French brasserie located near the bay. Highly popular for its elegant outdoor deck, exceptional Atlantic breezes, and premium cuts of steak served with a secret herb sauce.',
    pricePerPerson: 32,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Waterfront Dining', 'Romantic Sunset'],
    foodStyles: ['French', 'Mediterranean', 'Seafood', 'European'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'friends', 'family', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:30',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.3,
    googleReviewCount: 950,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 950,
    theforkRating: 4.3,
    theforkReviewCount: 950,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 950,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212539331819',
    googleMapsUrl: 'https://maps.google.com/?q=Le+Relais+de+Paris+Tangier',
    bestDishes: ['Steak Frites with Secret Herb Sauce', 'Spiced Red Tuna Steak', 'Warm Apple Tarte Tatin'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Book a table on the oceanfront terrace. Their signature beef tenderloin features an 18-herb secret brasserie sauce.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-tangier-8',
    city: 'tangier',
    name: 'Chez Hassan Bab Kasbah',
    neighborhood: 'Kasbah Entrance',
    description: 'An exceptionally popular, no-frills neighborhood diner right outside the Kasbah gates. Always packed with locals, it serves fresh grilled seafood, skewered brochettes, and typical Northern tagines.',
    pricePerPerson: 8.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Local Gathering Spot', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Seafood'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'friends', 'family', 'kids-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:30',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.6,
    googleReviewCount: 980,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 980,
    theforkRating: 4.6,
    theforkReviewCount: 980,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 980,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Chez+Hassan+Bab+Kasbah+Tangier',
    bestDishes: ['Grilled Calamari', 'Mixed Seafood Brochette Platter', 'Marinated Beef Skewers'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'They serve the finest complimentary house-marinated harissa olives in town. Don\'t miss the grilled calamari plate.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-tangier-9',
    city: 'tangier',
    name: 'Abou Tayssir (The Syrian)',
    neighborhood: 'Medina / Grand Socco',
    description: 'A legendary, pocket-sized eatery beloved by both students and travelers. Run by a welcoming Syrian exile, it is celebrated for serving the best falafel, creamy dips, and shawarma in Tangier.',
    pricePerPerson: 4,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'flexible'],
    experienceTypes: ['Casual Dining', 'Quick Bites', 'Local Gathering Spot'],
    foodStyles: ['Middle Eastern', 'Mediterranean'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends', 'couple'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:00',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.8,
    googleReviewCount: 1600,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 1600,
    theforkRating: 4.8,
    theforkReviewCount: 1600,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 1600,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Abou+Tayssir+Syrian+Tangier',
    bestDishes: ['Handmade Crispy Falafel', 'Syrian Chicken Shawarma', 'Mixed Dips with Lebanese Bread'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Order the mixed dip platter, which comes with freshly baked Lebanese flatbread, hummus, and two styles of baba ganoush.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-tangier-10',
    city: 'tangier',
    name: 'Restaurant Rif Kebdani',
    neighborhood: 'Medina',
    description: 'A cozy and highly-rated traditional restaurant nestled in the streets of the medina. It is highly praised for serving wonderfully balanced tagines and incredible Friday couscous.',
    pricePerPerson: 12,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Casual Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.6,
    googleReviewCount: 950,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 950,
    theforkRating: 4.6,
    theforkReviewCount: 950,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 950,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurante+Rif+Kebdani+Tangier',
    bestDishes: ['Swordfish Tagine', 'Seven-Vegetable Couscous', 'Traditional Harira Soup'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Perfect for travelers with dietary needs; they have excellent, carefully labeled gluten-free, vegetarian, and vegan options.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-tangier-11',
    city: 'tangier',
    name: 'The Dining Room at Villa Mabrouka',
    neighborhood: 'Medina / Marchan',
    description: 'A highly exclusive, premium restaurant set inside Yves Saint Laurent\'s former private clifftop villa. It features elegant, candle-lit, mirror-paneled dining spaces and serves exceptional French-Italian dishes.',
    pricePerPerson: 55,
    lifestyle: 'premium',
    mealTypes: ['breakfast', 'dinner'],
    experienceTypes: ['Fine Dining', 'Romantic Sunset', 'Upscale Lounge'],
    foodStyles: ['French', 'Italian', 'Mediterranean', 'Gourmet'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'seniors', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '19:00',
    closeTime: '23:30',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.7,
    googleReviewCount: 120,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 120,
    theforkRating: 4.7,
    theforkReviewCount: 120,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 120,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212666600488',
    googleMapsUrl: 'https://maps.google.com/?q=Villa+Mabrouka+Tangier',
    bestDishes: ['John Dory Goujons with Tartar Sauce', 'Risotto Primavera with Asparagus', 'Towering Vanilla Meringue Cake'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Children under 5 are not permitted. Dress strictly elegant and reserve well in advance for a magical, candlelit dinner in their historic gardens.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 0,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  },
  {
    id: 'e-tangier-12',
    city: 'tangier',
    name: 'Restaurant Bachir',
    neighborhood: 'Centre Ville / Boulevard Pasteur',
    description: 'A legendary local diner located just off Avenue Pasteur. Deeply loved by Tangier residents, it is packed at all hours and serves Northern Moroccan specialties, rotisserie chicken, and hot stews.',
    pricePerPerson: 6.5,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Casual Dining', 'Local Gathering Spot', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'family', 'friends', 'kids-friendly'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:00',
    closeTime: '23:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.5,
    googleReviewCount: 3400,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 3400,
    theforkRating: 4.5,
    theforkReviewCount: 3400,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 3400,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Bachir+Tangier',
    bestDishes: ['Spit-Roasted Rotisserie Chicken', 'Loubia (White Beans in Spiced Tomato)', 'Beef Tagine with Peas'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Perfect for an honest, extremely hearty local meal. Walk past the open cooking station at the entrance to see their famous spit-roasted chickens.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: true
  },
  {
    id: 'e-tangier-13',
    city: 'tangier',
    name: 'Café Tingis',
    neighborhood: 'Petit Socco',
    description: 'A historic literary café set in the Petit Socco, the lively historic heart of the old medina. It remains a legendary location for sipping tea, writing, and watching the daily flow of medina life.',
    pricePerPerson: 3,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'afternoon-tea', 'flexible'],
    experienceTypes: ['Cafe', 'Traditional Dining', 'People Watching'],
    foodStyles: ['Moroccan', 'Cafe', 'Bakery'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '06:00',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.1,
    googleReviewCount: 1500,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 1500,
    theforkRating: 4.1,
    theforkReviewCount: 1500,
    restaurantguruRating: 4.1,
    restaurantguruReviewCount: 1500,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Tingis+Tangier',
    bestDishes: ['Moroccan Cafe Nos-Nos', 'Sweet Mint Tea', 'Harcha Flatbread'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Try to secure a terrace seat facing the historic square. Order a "café nos-nos" (half milk, half coffee) and watch the vibrant daily life of the souks.',
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-tangier-14',
    city: 'tangier',
    name: 'Cinema Rif Café',
    neighborhood: 'Grand Socco / Place du 9 Avril',
    description: 'The cool artistic and cultural beating heart of Tangier. Located inside a beautifully restored 1930s Art Deco cinema, its café is a bustling hub for local artists, filmmakers, and digital nomads.',
    pricePerPerson: 5,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'afternoon-tea', 'flexible'],
    experienceTypes: ['Cafe', 'Casual Dining', 'People Watching'],
    foodStyles: ['Cafe', 'Mediterranean', 'Bakery'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '08:00',
    closeTime: '23:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.3,
    googleReviewCount: 2600,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 2600,
    theforkRating: 4.3,
    theforkReviewCount: 2600,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 2600,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Cinema+Rif+Tangier',
    bestDishes: ['Freshly Squeezed Orange Juice', 'Avocado Shake', 'Msemen with Cream Cheese'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Extremely laptop-friendly inside, while the bustling outdoor plaza seats offer excellent views of the historic Grand Socco gates.',
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-tangier-15',
    city: 'tangier',
    name: 'Restaurant Ahlen',
    neighborhood: 'Medina',
    description: 'A cozy, highly-authentic hidden gem inside the Medina. Known for its extremely heartwarming family service, it specializes in serving fresh local seafood tajines and fish soup.',
    pricePerPerson: 9,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Cozy casual family-run Moroccan eatery'],
    foodStyles: ['Moroccan', 'Seafood'],
    crowdLevel: 'quiet',
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '22:00',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.7,
    googleReviewCount: 320,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 320,
    theforkRating: 4.7,
    theforkReviewCount: 320,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 320,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Ahlen+Tangier',
    bestDishes: ['Northern Fish Soup', 'Spiced Seafood Tajine', 'Lamb Kefta with Tomatoes'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Tucked away in a quiet alley. The seafood tajine is loaded with fresh herbs, olives, and preserves, offering a lighter Northern taste.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-tangier-16',
    city: 'tangier',
    name: "Dall'Italiano",
    neighborhood: 'Boulevard Mohamed VI',
    description: 'A highly-rated beachfront restaurant serving authentic Italian pizzas, fresh seafood risottos, and handmade pastas. Celebrated for its stylish contemporary space and beach views.',
    pricePerPerson: 16,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Waterfront Dining', 'Casual Italian Dining', 'Family Friendly'],
    foodStyles: ['Italian', 'Seafood', 'Mediterranean', 'Pizza'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'kids-friendly', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.4,
    googleReviewCount: 810,
    tripadvisorRating: 4.4,
    tripadvisorReviewCount: 810,
    theforkRating: 4.4,
    theforkReviewCount: 810,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 810,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Dall+Italiano+Tangier',
    bestDishes: ['Seafood Risotto', 'Prosciutto wood-fired Pizza', 'Handmade Ravioli with Spinach'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Perfect for families. Their wood-fired pizzas feature fresh buffalo mozzarella and authentic, imported Italian flour.',
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-tangier-17',
    city: 'tangier',
    name: 'Restaurant Hammadi',
    neighborhood: 'Rue de la Kasbah',
    description: 'An established traditional Moroccan palace-style restaurant. Decorated beautifully with detailed wood and mosaic work, it offers authentic cuisine and live classical Moroccan music.',
    pricePerPerson: 18,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Live Music Terrace', 'Fine Dining'],
    foodStyles: ['Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'seniors', 'large-groups'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '11:30',
    closeTime: '23:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.2,
    googleReviewCount: 1600,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 1600,
    theforkRating: 4.2,
    theforkReviewCount: 1600,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 1600,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Hammadi+Tangier',
    bestDishes: ['Royal Pigeon Pastilla', 'Lamb Tagine with Caramelized Apricots', 'Harira Soup'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Popular with tour groups but still highly valued by locals for the consistency of their sweet lamb tagines and the authentic Andalusian music played during dinner.',
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-tangier-18',
    city: 'tangier',
    name: 'El Tangerino',
    neighborhood: 'Boulevard Mohamed VI',
    description: 'One of the city\'s best-established Spanish-style seafood restaurants. Known for serving exceptional, ultra-fresh catches, tapas, and classic Spanish paella directly facing the beach.',
    pricePerPerson: 28,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Waterfront Dining', 'Fine Seafood', 'Fine Dining'],
    foodStyles: ['Seafood', 'Spanish', 'Mediterranean'],
    crowdLevel: 'balanced',
    groupTypes: ['couple', 'family', 'friends', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: true,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '12:00',
    closeTime: '23:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.3,
    googleReviewCount: 1100,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 1100,
    theforkRating: 4.3,
    theforkReviewCount: 1100,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 1100,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=El+Tangerino+Tangier',
    bestDishes: ['Spanish Seafood Paella', 'Grilled Calamari', 'Salt-Baked Whole Sea Bass'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'serves-lunch',
    tip: 'Perfect for seafood lovers who appreciate Spanish cooking. Their grilled squid and baked sea bass are cooked to perfection.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'beach',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  },
  {
    id: 'e-tangier-19',
    city: 'tangier',
    name: 'La Terrasse - Dar El Kasbah (Kasbart)',
    neighborhood: 'Kasbah / Rue de la Kasbah',
    description: 'A beautifully designed, highly artistic rooftop garden restaurant located inside an Andalusian riad. Serves fresh, organic Moroccan salads, healthy breakfast sandwiches, and fresh juices.',
    pricePerPerson: 11,
    lifestyle: 'balanced',
    mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'afternoon-tea'],
    experienceTypes: ['Sunset Views', 'Scenic Views', 'Cafe'],
    foodStyles: ['Mediterranean', 'Moroccan', 'Healthy'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'friends', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '10:00',
    closeTime: '22:00',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.6,
    googleReviewCount: 290,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 290,
    theforkRating: 4.6,
    theforkReviewCount: 290,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 290,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    googleMapsUrl: 'https://maps.google.com/?q=Dar+El+Kasbah+Kasbart+Tangier',
    bestDishes: ['Tangier Spiced Lamb Tagine', 'Assorted Moroccan Dips', 'Fresh Avocado Orange Juice'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Check out their small artisanal shop selling handcrafted clothing and bags downstairs before heading up to the tranquil rooftop.',
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'rooftop'],
    viewType: 'city',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: false
  },
  {
    id: 'e-tangier-20',
    city: 'tangier',
    name: 'Snack Hassan',
    neighborhood: 'Grand Socco',
    description: 'A legendary and fast-paced Northern Moroccan street-food sandwich bar (bocadillo counter) located near the historic gates. Famed for serving rich, extremely cheap stuffed baguettes.',
    pricePerPerson: 3,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner', 'latenight', 'flexible'],
    experienceTypes: ['Casual Dining', 'Quick Bites', 'Local Gathering Spot'],
    foodStyles: ['Moroccan', 'Fast Food'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: true,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    openTime: '10:00',
    closeTime: '02:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",
    googleRating: 4.5,
    googleReviewCount: 850,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 850,
    theforkRating: 4.5,
    theforkReviewCount: 850,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 850,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    googleMapsUrl: 'https://maps.google.com/?q=Snack+Hassan+Grand+Socco+Tangier',
    bestDishes: ['Spicy Tuna Bocadillo', 'Kefta and Fries Wrap', 'Northern Harissa Chicken Sandwich'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    tip: 'Perfect for a rapid, satisfying street bite. Order their custom tuna bocadillo with egg, olives, fries, and spicy northern harissa sauce stuffed inside.',
    bestTimeToVisit: 'Late evening after 20:00 for lively crowd',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: false
  }
];