import type { EatListing } from '../types';

/**
 * EAT LISTING TEMPLATE
 * {
 *   id: 'e-[city]-[name]',
 *   city: 'taroudant_tafraoute',
 *   name: '[Name]',
 *   neighborhood: '[Neighborhood]',
 *   description: '[Long description]',
 *   pricePerPerson: [number],
 *   lifestyle: 'lean' | 'balanced' | 'premium',
 *   mealTypes: ['breakfast', 'lunch', 'dinner', 'brunch', 'latenight', 'afternoon-tea', 'flexible'],
 *   experienceTypes: ['Fine Dining' | 'Waterfront Dining' | 'Romantic Sunset' | 'Garden restaurant with live music' | 'Fountain courtyard' | 'Authentic Berber Feast' | 'Traditional Dining' | 'Cozy casual family-run Moroccan eatery' | 'Casual Dining' | 'Sunset Views' | 'Family Friendly' | 'Tranquil Dining' | 'Modern Fusion Dining'],
 *   foodStyles: ['French' | 'Moroccan' | 'Mediterranean' | 'European' | 'Berber' | 'Barbecue' | 'Healthy' | 'Cafe' | 'Bakery' | 'Patisserie'],
 *   crowdLevel: 'bustling' | 'balanced' | 'quiet',
 *   groupTypes: ['solo' | 'couple' | 'family' | 'friends' | 'seniors' | 'kids-friendly' | 'large-groups' | 'business-friendly'],
 *   hasEnglishStaff: true | false,
 *   hasFrenchStaff: true | false,
 *   hasDelivery: true | false,
 *   hasParking: true | false,
 *   nearMedina: true | false,
 *   nearBeach: false,
 *   nearCenter: true | false,
 *   isVegetarianFriendly: true | false,
 *   isHalal: true | false,
 *   halalStatus: 'likely-halal-food' | 'halal-certified' | 'unknown',
 *   verificationStatus: 'verified',
 *   openTime: 'HH:mm',
 *   closeTime: 'HH:mm',
 *   badge: 'local-favorite' | 'splurge' | 'hidden-gem' | 'local',
 *   googleRating: [4.x],
 *   googleReviewCount: [number],
 *   tripadvisorRating: [4.x],
 *   tripadvisorReviewCount: [number],
 *   theforkRating: [4.x],
 *   theforkReviewCount: [number],
 *   restaurantguruRating: [4.x],
 *   restaurantguruReviewCount: [number],
 *   tip: '[Short tip]',
 *   archetypeAffinity: [...],
 *   vibeTags: [...],
 *   isHiddenGem: true | false,
 *   paymentMethods: ['cash'] | ['cash', 'card'],
 *   reservationMethod: ['none'] | ['phone'] | ['phone', 'online'],
 *   reservationContact: '+212XXXXXXXXX',
 *   googleMapsUrl: 'https://maps.google.com/?q=[Name]+[City]',
 *   bestDishes: ['Dish 1', 'Dish 2'],
 *   alcoholPolicy: 'serves-alcohol' | 'dry',
 *   ramadanFriendly: 'serves-lunch' | 'special-ftour' | 'closed',
 *   customStory: '[Rich contextual story]',
 *   languagesSpoken: ['Arabic/Darija', 'French', 'English', 'Tachelhit/Berber'],
 *   exactAddressAndCoordinates: { address: '...', lat: 0.0, lng: 0.0 },
 *   pros: [...],
 *   cons: [...],
 *   bestTimeToVisit: '...',
 *   averageWaitMinutes: 5,
 *   seatingTypes: ['indoor', 'garden', 'terrace', 'rooftop'],
 *   viewType: 'garden' | 'mountain' | 'city' | 'none',
 *   wiFi: true | false,
 *   airConditioning: true | false,
 *   wheelchairAccessible: true | false
 * }
 */

export const taroudant_tafraouteEat: EatListing[] = [
  // ── 1. RIAD MARYAM (TAROUDANT MEDINA) ──
  {
    id: 'e-taroudant-1',
    city: 'taroudant_tafraoute',
    name: 'Restaurant Riad Maryam',
    neighborhood: 'Medina',
    description: 'A celebrated family-run riad dining room tucked inside the historic red-mud ramparts of Taroudant Medina. Famed for exquisite home-style Souss valley cuisine, fragrant chicken pastilla with roasted almonds, slow-cooked lamb tagines, and their signature dessert "Pastilla au Lait" served in a tranquil orange-tree patio courtyard.',
    pricePerPerson: 22,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fountain courtyard', 'Authentic Berber Feast', 'Traditional Dining'],
    foodStyles: ['Moroccan', 'Berber'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'family', 'friends', 'seniors'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '12:30',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.8,
    googleReviewCount: 350,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 280,
    theforkRating: 4.8,
    theforkReviewCount: 350,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 350,

    tip: 'Reservation in advance is recommended for dinner to ensure freshly prepared pastilla warka pastry. Save room for their delicate orange-blossom milk pastilla.',
    archetypeAffinity: ['culture-seeker', 'romantic-getaway', 'heritage-seeker'],
    vibeTags: ['riad-patio', 'orange-trees', 'fountain-courtyard', 'souss-hospitality'],
    isHiddenGem: true,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212528852270',
    googleMapsUrl: 'https://maps.google.com/?q=Riad+Maryam+Taroudant',
    bestDishes: ['Chicken Pastilla with Almonds & Cinnamon', 'Pastilla au Lait Dessert', 'Tajine de Veau aux Pruneaux'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    customStory: 'Built within a century-old traditional Roudani home near the Kasbah walls, Riad Maryam preserves authentic southern Moroccan domestic hospitality. Dining tables sit surrounded by whispering orange trees and terracotta fountains, where the matriarchal kitchen prepares slow-simmered dishes flavored with genuine Taliouine saffron.',
    languagesSpoken: ['French', 'English', 'Arabic/Darija', 'Tachelhit/Berber'],
    exactAddressAndCoordinates: {
      address: 'Derb Riad, Quartier Kasbah, Taroudant 83000, Morocco',
      lat: 30.47280,
      lng: -8.87410
    },
    pros: [
      'Peaceful courtyard garden with mature citrus trees and soothing fountains.',
      'Superb artisanal pastilla cooked fresh with delicate crispy layers.',
      'Attentive, warm family-run service with genuine Souss Valley charm.'
    ],
    cons: [
      'Tucked inside pedestrian alleyways; luggage/walk from Bab Kasbah needed.',
      'Dinner pastilla orders should ideally be placed a few hours in advance.'
    ],
    bestTimeToVisit: 'Dinner around 19:30 for atmospheric courtyard lighting',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'garden'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["budget", "dinner", "dry", "medina", "pastilla", "quiet", "riad", "tagine", "terrace", "wifi"]
  },

  // ── 2. DAR ZITOUNE (TAROUDANT COUNTRYSIDE) ──
  {
    id: 'e-taroudant-2',
    city: 'taroudant_tafraoute',
    name: 'Dar Zitoune Restaurant',
    neighborhood: 'Taroudant Countryside',
    description: 'An elegant garden oasis restaurant set amongst centenary olive groves and bougainvillea just outside Taroudant walls. Offers refined French-Moroccan Mediterranean cuisine, organic salads harvested from their private estate garden, and succulent charcoal grills.',
    pricePerPerson: 30,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Fine Dining', 'Tranquil Dining', 'Garden restaurant with live music'],
    foodStyles: ['French', 'Moroccan', 'Mediterranean'],
    // food-cuisine quiz question tags
    cuisineTags: ['international', 'moroccan-traditional'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'seniors', 'business-friendly'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '22:30',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 220,
    tripadvisorRating: 4.6,
    tripadvisorReviewCount: 190,
    theforkRating: 4.7,
    theforkReviewCount: 220,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 220,

    tip: 'A peaceful retreat from the heat of the medina—great for a relaxing long lunch by the gardens with chilled Moroccan Gris wine.',
    archetypeAffinity: ['luxury-traveler', 'romantic-getaway', 'nature-lover'],
    vibeTags: ['olive-groves', 'garden-estate', 'fine-dining', 'countryside-retreat'],
    isHiddenGem: false,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212528551140',
    googleMapsUrl: 'https://maps.google.com/?q=Dar+Zitoune+Taroudant',
    bestDishes: ['Organic Garden Salad Supreme', 'Souss Valley Roast Lamb Mechoui', 'Crème Brûlée Orange Blossom'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    customStory: 'Nestled on an estate carpeted in mature olive trees ("Dar Zitoune" means House of Olives), this upscale haven offers respite from the dusty plains of the Souss. Diners savor French culinary flair fused with southern spices, accompanied by vintage Moroccan wines under thatched gazebos.',
    languagesSpoken: ['French', 'English', 'Arabic/Darija'],
    exactAddressAndCoordinates: {
      address: 'Route de Taliouine, Km 3, Taroudant 83000, Morocco',
      lat: 30.48510,
      lng: -8.84530
    },
    pros: [
      'Idyllic landscaped garden estate with swimming pool and private dining gazebos.',
      'Full wine and cocktail license with Moroccan and international labels.',
      'Farm-to-table organic vegetables grown directly on the property.'
    ],
    cons: [
      'Located 3 km outside the city walls; short taxi ride required.',
      'High-tier pricing matching its boutique resort status.'
    ],
    bestTimeToVisit: 'Lunch around 13:00 under the palm shading',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'garden', 'terrace'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["alcohol", "budget", "dinner", "fine", "live-music", "quiet", "terrace", "wifi"]
  },

  // ── 3. JNANE SOUSSIA (TAROUDANT OUTSKIRTS) ──
  {
    id: 'e-taroudant-3',
    city: 'taroudant_tafraoute',
    name: 'Jnane Soussia',
    neighborhood: 'Taroudant City Outskirts',
    description: 'A beloved outdoor garden restaurant featuring traditional caïdal tents set in lush palm gardens. Celebrated by Moroccan families for authentic Berber mechoui, savory briouates, couscous, and live Gnawa and Berber folk music on weekends.',
    pricePerPerson: 15,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Authentic Berber Feast', 'Family Friendly', 'Live Music Terrace'],
    foodStyles: ['Moroccan', 'Berber', 'Barbecue'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'international'],
    crowdLevel: 'bustling',
    groupTypes: ['family', 'large-groups', 'friends'],
    hasEnglishStaff: false,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 410,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 150,
    theforkRating: 4.6,
    theforkReviewCount: 410,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 410,

    tip: 'Ideal for large family gatherings and experiencing dining under traditional caïdal tents. Don\'t miss their whole slow-braised lamb shoulder.',
    archetypeAffinity: ['family', 'culture-seeker', 'meat-enthusiast'],
    vibeTags: ['caidal-tents', 'gnawa-music', 'mechoui-feast', 'shaded-gardens'],
    isHiddenGem: false,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212528854980',
    googleMapsUrl: 'https://maps.google.com/?q=Jnane+Soussia+Taroudant',
    bestDishes: ['Slow-Roasted Lamb Mechoui', 'Assorted Crispy Briouates', 'Friday Seven-Vegetable Couscous'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    customStory: 'Sprawling across a lush palm grove just outside the monumental walls, Jnane Soussia recreates the festive spirit of southern Moroccan moussems. Guests recline on embroidered cushions beneath embroidered tribal tents while communal platters of crackling mechoui and steaming couscous arrive on brass tables.',
    languagesSpoken: ['Arabic/Darija', 'French', 'Tachelhit/Berber'],
    exactAddressAndCoordinates: {
      address: 'Route des Ramparts, Bab Ouled Bounouna, Taroudant 83000, Morocco',
      lat: 30.46520,
      lng: -8.86190
    },
    pros: [
      'Atmospheric caïdal tent dining immersed in palm and eucalyptus gardens.',
      'Tender slow-roasted wood-fired mechoui lamb seasoned with cumin and salt.',
      'Spacious play area and garden pathways well-suited for traveling families.'
    ],
    cons: [
      'Gets very lively and crowded on weekend afternoons.',
      'No air conditioning under the open-sided tents in midsummer heat.'
    ],
    bestTimeToVisit: 'Sunday lunch around 13:30',
    averageWaitMinutes: 10,
    seatingTypes: ['garden', 'terrace'],
    viewType: 'garden',
    wiFi: false,
    airConditioning: false,
    wheelchairAccessible: true
  ,
    tags: ["budget", "couscous", "dinner", "dry", "live-music", "terrace"]
  },

  // ── 4. RESTAURANT CHEZ NADIA (TAROUDANT MEDINA) ──
  {
    id: 'e-taroudant-4',
    city: 'taroudant_tafraoute',
    name: 'Restaurant Chez Nadia',
    neighborhood: 'Medina',
    description: 'An intimate, cozy local medina restaurant celebrated for home-style Roudani cooking. Nadia and her team prepare authentic Berber tagines, crisp pastillas, and warm semolina bread baked fresh in the neighborhood clay oven.',
    pricePerPerson: 9,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Cozy casual family-run Moroccan eatery', 'Authentic Berber Feast'],
    foodStyles: ['Moroccan', 'Berber'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '11:30',
    closeTime: '22:00',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.7,
    googleReviewCount: 290,
    tripadvisorRating: 4.7,
    tripadvisorReviewCount: 160,
    theforkRating: 4.7,
    theforkReviewCount: 290,
    restaurantguruRating: 4.7,
    restaurantguruReviewCount: 290,

    tip: 'Nadia makes one of the best vegetarian tagines in the region with sweet caramelized onions and local raisins. Finish with her homemade mint tea.',
    archetypeAffinity: ['budget-conscious', 'vegan-friendly', 'solo-traveler'],
    vibeTags: ['home-cooked', 'family-hospitality', 'medina-gem', 'saffron-scented'],
    isHiddenGem: true,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    reservationContact: '+212671239844',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Chez+Nadia+Taroudant',
    bestDishes: ['Chicken Tagine with Preserved Lemon & Olives', 'Vegetarian Souss Tagine', 'Fresh Seasonal Fruit Salad with Orange Blossom'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    customStory: 'Opening her cozy dining space to share the recipes taught by her Roudani grandmother, Nadia has turned this simple medina venue into a traveler favorite. Everything is cooked to order using produce sourced from the nearby Souk Jnane al-Jaami.',
    languagesSpoken: ['Arabic/Darija', 'French', 'English'],
    exactAddressAndCoordinates: {
      address: 'Derb El Kasbah, Medina, Taroudant 83000, Morocco',
      lat: 30.47150,
      lng: -8.87320
    },
    pros: [
      'Genuinely authentic domestic home-style cooking at very modest prices.',
      'Extremely friendly, heartfelt personal service from Nadia and her staff.',
      'Exceptional vegetarian tagine with seasonal vegetables and golden raisins.'
    ],
    cons: [
      'Compact dining space with limited tables; can fill up quickly around 19:30.',
      'Cash only payment.'
    ],
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor'],
    viewType: 'none',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  ,
    tags: ["budget", "dinner", "dry", "medina", "pastilla", "tagine", "wifi"]
  },

  // ── 5. RESTAURANT ATLAS (PLACE ASSARAG, TAROUDANT) ──
  {
    id: 'e-taroudant-5',
    city: 'taroudant_tafraoute',
    name: 'Restaurant Atlas',
    neighborhood: 'Place Assarag',
    description: 'A classic, long-standing brass bistro and terrace on the vibrant edge of Place Assarag. Famous for front-row people-watching, rich Souss harira soup, spit-roasted chicken with olives, and affordable daily set menus.',
    pricePerPerson: 7,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'People Watching', 'Casual Dining'],
    foodStyles: ['Moroccan', 'Berber', 'Cafe'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'friends', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '07:00',
    closeTime: '23:00',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.3,
    googleReviewCount: 520,
    tripadvisorRating: 4.2,
    tripadvisorReviewCount: 240,
    theforkRating: 4.3,
    theforkReviewCount: 520,
    restaurantguruRating: 4.3,
    restaurantguruReviewCount: 520,

    tip: 'Grab an outdoor terrace table facing Place Assarag in late afternoon. Order a hot pot of mint tea with a plate of chebakia honey sweets.',
    archetypeAffinity: ['budget-conscious', 'people-watcher', 'culture-seeker'],
    vibeTags: ['place-assarag', 'busy-terrace', 'street-theatre', 'spiced-harira'],
    isHiddenGem: false,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    reservationContact: '+212528852314',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Atlas+Place+Assarag+Taroudant',
    bestDishes: ['Spiced Souss Harira with Dates', 'Rotisserie Lemon Chicken & Fries', 'Minced Beef Kefta Tagine with Egg'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    customStory: 'For decades, Restaurant Atlas has occupied prime real estate on Place Assarag—the lively beating heart of Taroudant. From early morning espresso to late-night mint tea, merchants, farmers from the Anti-Atlas valleys, and foreign wanderers mingle here while watching acrobats and musicians.',
    languagesSpoken: ['Arabic/Darija', 'French', 'English'],
    exactAddressAndCoordinates: {
      address: 'Place Assarag, Taroudant 83000, Morocco',
      lat: 30.47080,
      lng: -8.87740
    },
    pros: [
      'Premier vantage point overlooking the bustling spectacle of Place Assarag.',
      'Very speedy service and rock-bottom prices under 70 MAD for full menus.',
      'Open early morning until late evening 7 days a week.'
    ],
    cons: [
      'Street vendors and snake charmers occasionally pass by terrace tables.',
      'Cash only payment.'
    ],
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dinner", "dry", "medina", "tagine", "terrace", "wifi"]
  },

  // ── 6. CAFE RESTAURANT LES ARCADES (PLACE TALMOKLATE, TAROUDANT) ──
  {
    id: 'e-taroudant-6',
    city: 'taroudant_tafraoute',
    name: 'Café Restaurant Les Arcades',
    neighborhood: 'Place Talmoklate',
    description: 'An iconic colonial-era cafe and terrace situated beneath the graceful whitewashed archways of Place Talmoklate. Serves freshly squeezed Taroudant citrus juices, Moroccan breakfast platters with amlou, and light medina lunches.',
    pricePerPerson: 6,
    lifestyle: 'lean',
    mealTypes: ['breakfast', 'lunch', 'afternoon-tea'],
    experienceTypes: ['People Watching', 'Cafe', 'Traditional Dining'],
    foodStyles: ['Cafe', 'Moroccan', 'Breakfast'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional', 'cafe-pastry'],
    crowdLevel: 'bustling',
    groupTypes: ['solo', 'couple', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: false,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '06:30',
    closeTime: '22:30',
    badge: 'local',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.2,
    googleReviewCount: 460,
    tripadvisorRating: 4.1,
    tripadvisorReviewCount: 195,
    theforkRating: 4.2,
    theforkReviewCount: 460,
    restaurantguruRating: 4.2,
    restaurantguruReviewCount: 460,

    tip: 'Order the traditional Roudani breakfast: fresh warm msemen flatbread with wild thyme honey, goat butter, and nutty argan amlou paste.',
    archetypeAffinity: ['budget-conscious', 'digital-nomad', 'solo-traveler'],
    vibeTags: ['colonial-arcades', 'amlou-breakfast', 'people-watching', 'citrus-press'],
    isHiddenGem: false,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    reservationContact: '+212528851490',
    googleMapsUrl: 'https://maps.google.com/?q=Cafe+Les+Arcades+Place+Talmoklate+Taroudant',
    bestDishes: ['Fresh Taroudant Orange Juice', 'Berber Breakfast with Amlou & Honey', 'Tagine of Kefta & Tomato'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'serves-lunch',
    customStory: 'Built during the French protectorate under the grand shaded colonnades of Place Talmoklate, Les Arcades has witnessed nearly a century of Taroudant’s social life. In the morning light, local artisans sip cafe noir before rolling up the wooden shutters of the adjacent leather and silver souks.',
    languagesSpoken: ['Arabic/Darija', 'French', 'English'],
    exactAddressAndCoordinates: {
      address: 'Place Talmoklate, Medina, Taroudant 83000, Morocco',
      lat: 30.47210,
      lng: -8.87890
    },
    pros: [
      'Shaded outdoor arcade terrace providing respite from the desert sun.',
      'Luscious fresh-squeezed citrus juices sourced from neighboring Souss orchards.',
      'Prime location linking the two major public squares of the Medina.'
    ],
    cons: [
      'Basic menu offerings focused primarily on breakfasts and casual lunch plates.',
      'Cash only payment.'
    ],
    bestTimeToVisit: 'Early morning for fresh baked goods',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  ,
    tags: ["breakfast", "budget", "cafe-pastry", "dry", "juice", "medina", "tagine", "terrace", "wifi"]
  },

  // ── 7. RESTAURANT LE PALAIS SALAM (TAROUDANT KASBAH) ──
  {
    id: 'e-taroudant-7',
    city: 'taroudant_tafraoute',
    name: 'Le Palais Salam Restaurant',
    neighborhood: 'Kasbah Ramparts',
    description: 'Set within the monumental 19th-century palace of the former Pasha of Taroudant along the ancient mud-brick ramparts. Features dining across lush subtropical gardens filled with banana plants and centuries-old bougainvillea, serving classic royal Moroccan banquets.',
    pricePerPerson: 25,
    lifestyle: 'premium',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Historical Ambience', 'Fine Dining', 'Fountain courtyard'],
    foodStyles: ['Moroccan', 'French', 'Mediterranean'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'seniors', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '22:30',
    badge: 'splurge',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.4,
    googleReviewCount: 380,
    tripadvisorRating: 4.3,
    tripadvisorReviewCount: 220,
    theforkRating: 4.4,
    theforkReviewCount: 380,
    restaurantguruRating: 4.4,
    restaurantguruReviewCount: 380,

    tip: 'Take a brief stroll through the historic palace courtyards before dinner. They serve licensed wines and beers on the garden terrace.',
    archetypeAffinity: ['luxury-traveler', 'history-buff', 'romantic-getaway'],
    vibeTags: ['pashas-palace', 'subtropical-gardens', 'kasbah-walls', 'historic-splendor'],
    isHiddenGem: false,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone', 'online'],
    reservationContact: '+212528852312',
    googleMapsUrl: 'https://maps.google.com/?q=Palais+Salam+Restaurant+Taroudant',
    bestDishes: ['Royal Pigeon & Almond Pastilla', 'Slow-Simmered Lamb Tagine with Figs & Walnuts', 'Orange Carpaccio with Cinnamon'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    customStory: 'Constructed directly into the monumental pisé city ramparts in the late 1800s for Pasha El Glaoui, Le Palais Salam boasts historic grandeur with its crenellated watchtowers and emerald tiled pools. Dining in its lantern-lit courtyards evokes the romantic splendor of the pre-modern Sahara trade routes.',
    languagesSpoken: ['French', 'English', 'Arabic/Darija'],
    exactAddressAndCoordinates: {
      address: 'Avenue Moulay Ismail, Kasbah, Taroudant 83000, Morocco',
      lat: 30.47010,
      lng: -8.87150
    },
    pros: [
      'Magnificent 19th-century Pasha\'s palace architecture integrated into the city ramparts.',
      'Full alcohol service available in both the bar lounge and shaded garden dining patio.',
      'Lush tropical greenery and atmospheric mosaic courtyards.'
    ],
    cons: [
      'Menu is relatively traditional without avant-garde culinary updates.',
      'Service pace is leisurely and relaxed; not suited for quick meals.'
    ],
    bestTimeToVisit: 'Dinner around 19:30 for atmospheric courtyard lighting',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'garden', 'terrace'],
    viewType: 'garden',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: false
  ,
    tags: ["alcohol", "budget", "dinner", "fine", "medina", "palace", "pastilla", "quiet", "tagine", "terrace", "wifi"]
  },

  // ── 8. RESTAURANT AL HASSAN (TAROUDANT BAB KASBAH) ──
  {
    id: 'e-taroudant-8',
    city: 'taroudant_tafraoute',
    name: 'Restaurant Al Hassan',
    neighborhood: 'Bab Kasbah',
    description: 'A welcoming, family-run eatery right outside the monumental Bab Kasbah archway. Known for clay-pot beef and prune tagines, freshly prepared seasonal Moroccan salad medleys, and courteous hospitality.',
    pricePerPerson: 10,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Traditional Dining', 'Casual Dining'],
    foodStyles: ['Moroccan', 'Berber'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'balanced',
    groupTypes: ['solo', 'couple', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: true,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '11:00',
    closeTime: '22:30',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 310,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 140,
    theforkRating: 4.5,
    theforkReviewCount: 310,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 310,

    tip: 'Their spiced vegetable soup and wood-grilled beef skewers are always freshly grilled on charcoal outside the door.',
    archetypeAffinity: ['budget-conscious', 'culture-seeker', 'meat-enthusiast'],
    vibeTags: ['bab-kasbah', 'charcoal-skewers', 'friendly-host', 'authentic-flavors'],
    isHiddenGem: true,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    reservationContact: '+212668903344',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+Al+Hassan+Bab+Kasbah+Taroudant',
    bestDishes: ['Charcoal-Grilled Kefta Skewers', 'Beef & Prune Tagine with Roasted Almonds', 'Cooked Zaalouk and Taktouka Salad Duo'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    customStory: 'Situated beside the towering ochre mud bastions of Bab Kasbah, Hassan’s welcoming restaurant has been a staple for travelers arriving from Ouarzazate and Marrakech. The smell of smoking olive charcoal and sizzling brochettes draws diners into a cozy, family-friendly salon.',
    languagesSpoken: ['Arabic/Darija', 'French', 'English'],
    exactAddressAndCoordinates: {
      address: 'Avenue de la Kasbah, Bab Kasbah, Taroudant 83000, Morocco',
      lat: 30.47350,
      lng: -8.87100
    },
    pros: [
      'Very close to the main Kasbah parking and monumental gate.',
      'Sizzling skewers prepared fresh on traditional open-air charcoal grills.',
      'Attentive, warm Berber hospitality with complimentary mint tea.'
    ],
    cons: [
      'Cash only payment.',
      'Dining room is modest and traditional without luxury finishes.'
    ],
    bestTimeToVisit: 'Lunch around 13:00 for quiet',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'city',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  ,
    tags: ["budget", "dinner", "dry", "medina", "tagine", "terrace", "wifi"]
  },

  // ── 9. L'ETOILE DU SUD (TAFRAOUTE TOWN CENTER) ──
  {
    id: 'e-tafraoute-9',
    city: 'taroudant_tafraoute',
    name: "L'Étoile du Sud",
    neighborhood: 'Tafraoute Center',
    description: 'Established in 1968 amidst the striking pink granite boulders of the Anti-Atlas mountains. Serving hearty, traditional Anti-Atlas almond-and-prune lamb tagines, fresh Berber couscous, and mint tea inside a carpeted Berber dining room with panoramic valley terraces.',
    pricePerPerson: 14,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Authentic Berber Feast', 'Historical Ambience', 'Sunset Views'],
    foodStyles: ['Berber', 'Moroccan'],
    crowdLevel: 'balanced',
    groupTypes: ['family', 'friends', 'seniors', 'couple'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '11:30',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.5,
    googleReviewCount: 380,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 190,
    theforkRating: 4.5,
    theforkReviewCount: 380,
    restaurantguruRating: 4.5,
    restaurantguruReviewCount: 380,

    tip: 'Try the local Amlou (almond, argan oil & honey paste) served with warm oven bread as a starter. They also offer cold beers on their outdoor terrace.',
    archetypeAffinity: ['mountain-explorer', 'culture-seeker', 'traditional-flavor'],
    vibeTags: ['pink-granite', 'anti-atlas', 'berber-carpets', 'historic-tavern'],
    isHiddenGem: false,
    paymentMethods: ['cash', 'card'],
    reservationMethod: ['phone'],
    reservationContact: '+212528861217',
    googleMapsUrl: 'https://maps.google.com/?q=Etoile+du+Sud+Tafraoute',
    bestDishes: ['Tafraoute Almond Lamb Tagine', 'Berber Couscous Royal', 'Organic Amlou Dip with Fresh Bread'],
    alcoholPolicy: 'serves-alcohol',
    ramadanFriendly: 'special-ftour',
    customStory: 'Opening its doors in 1968 as the very first hospitality landmark in Tafraoute, L\'Étoile du Sud is surrounded by the surreal cyclopean granite peaks of Jebel Lekst. Inside, walls are hung with vibrant handmade Berber kilims and brass lamps, welcoming generations of mountaineers and geologists.',
    languagesSpoken: ['French', 'English', 'Arabic/Darija', 'Tachelhit/Berber'],
    exactAddressAndCoordinates: {
      address: 'Centre Ville, Avenue Hassan II, Tafraoute 85000, Morocco',
      lat: 29.72120,
      lng: -8.97480
    },
    pros: [
      'Pioneering historic dining institution in Tafraoute since the late 1960s.',
      'Card payments accepted and cold licensed beer available.',
      'Spectacular views of the surrounding pink granite mountain crests.'
    ],
    cons: [
      'Tour groups occasionally book sections for lunch during peak hiking seasons.',
      'Interior decor is classic and nostalgic rather than sleek modern.'
    ],
    bestTimeToVisit: 'Dinner around 19:30 after exploring Napoleon\'s Hat granite formations',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'mountain',
    wiFi: true,
    airConditioning: true,
    wheelchairAccessible: true
  ,
    tags: ["alcohol", "budget", "couscous", "dinner", "mountain", "sunset", "tagine", "terrace", "wifi"]
  },

  // ── 10. CHEZ SABIR (TAFRAOUTE CENTER) ──
  {
    id: 'e-tafraoute-10',
    city: 'taroudant_tafraoute',
    name: 'Chez Sabir',
    neighborhood: 'Tafraoute Center',
    description: 'A charming, ultra-welcoming family-run restaurant in central Tafraoute. Known for delicious home-cooked set menus featuring hearty harira, caramelized prune-and-almond beef tagines, and complimentary fresh mint tea with local Anti-Atlas dates.',
    pricePerPerson: 10,
    lifestyle: 'lean',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Cozy casual family-run Moroccan eatery', 'Authentic Berber Feast'],
    foodStyles: ['Moroccan', 'Berber'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'solo', 'family', 'friends'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: true,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: false,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '21:30',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.8,
    googleReviewCount: 190,
    tripadvisorRating: 4.9,
    tripadvisorReviewCount: 110,
    theforkRating: 4.8,
    theforkReviewCount: 190,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 190,

    tip: 'Exceptionally warm hospitality—Sabir and his family make every guest feel like a personal house guest. Try their savory goat tagine with local almonds.',
    archetypeAffinity: ['budget-conscious', 'hidden-gem-hunter', 'family-run-lover'],
    vibeTags: ['family-warmth', 'home-cooking', 'anti-atlas-dates', 'mountain-hospitality'],
    isHiddenGem: true,
    paymentMethods: ['cash'],
    reservationMethod: ['none'],
    reservationContact: '+212672338810',
    googleMapsUrl: 'https://maps.google.com/?q=Chez+Sabir+Tafraoute',
    bestDishes: ['Homemade Harira Soup', 'Tagine of Beef with Caramelized Prunes & Almonds', 'Vegetable Tagine Soussia'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    customStory: 'Sabir greeted his first foreign visitors with warm oven bread and argan oil decades ago and has maintained that authentic Berber tradition ever since. In this cozy street-corner sanctuary, every pot of tagine is simmered slowly over embers with vegetables harvested from family garden terraces.',
    languagesSpoken: ['Arabic/Darija', 'French', 'English', 'Tachelhit/Berber'],
    exactAddressAndCoordinates: {
      address: 'Rue de la Poste, Centre Ville, Tafraoute 85000, Morocco',
      lat: 29.72250,
      lng: -8.97560
    },
    pros: [
      'Warmest personal hospitality in town with Sabir himself greeting each table.',
      'Incredible value set menu including soup, tagine, dessert, and fresh mint tea.',
      'Tender meat and fresh mountainous herbs cooked with genuine care.'
    ],
    cons: [
      'Intimate dining room with modest seating; can fill quickly after 19:00.',
      'Cash only payment.'
    ],
    bestTimeToVisit: 'Dinner around 19:00',
    averageWaitMinutes: 5,
    seatingTypes: ['indoor'],
    viewType: 'mountain',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  ,
    tags: ["budget", "dinner", "dry", "mountain", "quiet", "tagine", "wifi"]
  },

  // ── 11. RESTAURANT LA KASBAH (TAFRAOUTE) ──
  {
    id: 'e-tafraoute-11',
    city: 'taroudant_tafraoute',
    name: 'Restaurant La Kasbah',
    neighborhood: 'Tafraoute Outskirts',
    description: 'Perched on the mountain slopes of Tafraoute, this converted Berber stronghold features a panoramic open-air terrace looking across to the famous Lion\'s Face granite peak. Serves robust mountain fare including spiced goat tagines, lentil stews, and roasted chicken.',
    pricePerPerson: 12,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Sunset Views', 'Authentic Berber Feast', 'Traditional Dining'],
    foodStyles: ['Berber', 'Moroccan'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'balanced',
    groupTypes: ['family', 'friends', 'couple'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    halalStatus: 'halal-certified',
    verificationStatus: 'verified',
    openTime: '11:00',
    closeTime: '22:00',
    badge: 'local-favorite',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.6,
    googleReviewCount: 260,
    tripadvisorRating: 4.5,
    tripadvisorReviewCount: 130,
    theforkRating: 4.6,
    theforkReviewCount: 260,
    restaurantguruRating: 4.6,
    restaurantguruReviewCount: 260,

    tip: 'Arrive 45 minutes before sunset to witness the pink granite boulders of the valley turn deep crimson while you sip fresh mint tea on the upper deck.',
    archetypeAffinity: ['sunset-seeker', 'mountain-explorer', 'photographer'],
    vibeTags: ['lions-face-view', 'granite-peaks', 'sunset-terrace', 'mountain-tagine'],
    isHiddenGem: false,
    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212528861545',
    googleMapsUrl: 'https://maps.google.com/?q=Restaurant+La+Kasbah+Tafraoute',
    bestDishes: ['Spiced Mountain Goat Tagine', 'Berber Couscous with Turnips & Pumpkin', 'Warm Msemen with Pure Mountain Honey'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    customStory: 'Constructed from native Anti-Atlas stone to resemble a fortified agadir (communal granary), Restaurant La Kasbah occupies a breathtaking vantage point above Tafraoute. The kitchen specializes in authentic highland Amazigh cooking, honoring centuries of mountain harvest traditions.',
    languagesSpoken: ['Arabic/Darija', 'French', 'English', 'Tachelhit/Berber'],
    exactAddressAndCoordinates: {
      address: 'Route d\'Agadir, Haut Tafraoute, Tafraoute 85000, Morocco',
      lat: 29.72890,
      lng: -8.96980
    },
    pros: [
      'Unrivaled panoramic vistas overlooking the Tafraoute basin and granite cliffs.',
      'Generous hearty portions after a full day of trekking or mountain biking.',
      'Charming traditional mud-and-stone architectural aesthetic.'
    ],
    cons: [
      'Situated on an uphill slope from the village center; walk or vehicle needed.',
      'Terrace can feel breezy in winter evenings; bring a warm jacket.'
    ],
    bestTimeToVisit: 'Early evening around 18:30 for sunset',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace'],
    viewType: 'mountain',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  ,
    tags: ["budget", "couscous", "dinner", "dry", "mountain", "sunset", "tagine", "terrace", "wifi"]
  },

  // ── 12. RESTAURANT MAISON TISSALINE (TAFRAOUTE / AMELN VALLEY) ──
  {
    id: 'e-tafraoute-12',
    city: 'taroudant_tafraoute',
    name: 'Maison Tissaline',
    neighborhood: 'Ameln Valley',
    description: 'An enchanting, tranquil mountain guesthouse restaurant situated in the lush Ameln Valley beneath the sheer cliffs of Jebel Lekst. Specializes in home-pressed pure argan oil dishes, tender lamb with mountain wild herbs, and organic seasonal fruit tarts.',
    pricePerPerson: 16,
    lifestyle: 'balanced',
    mealTypes: ['lunch', 'dinner'],
    experienceTypes: ['Tranquil Dining', 'Authentic Berber Feast', 'Scenic Views'],
    foodStyles: ['Berber', 'Moroccan', 'Healthy'],
    // food-cuisine quiz question tags
    cuisineTags: ['moroccan-traditional'],
    crowdLevel: 'quiet',
    groupTypes: ['couple', 'seniors', 'nature-lover', 'family'],
    hasEnglishStaff: true,
    hasFrenchStaff: true,
    hasDelivery: false,
    hasParking: true,
    nearMedina: false,
    nearBeach: false,
    nearCenter: false,
    isVegetarianFriendly: true,
    isHalal: true,
    servesAlcohol: true,
    halalStatus: 'likely-halal-food',
    verificationStatus: 'verified',
    openTime: '12:00',
    closeTime: '21:30',
    badge: 'hidden-gem',
    // googlePlaceId: "PLACE_ID_HERE",

    // ── RATINGS ──
    googleRating: 4.8,
    googleReviewCount: 180,
    tripadvisorRating: 4.8,
    tripadvisorReviewCount: 95,
    theforkRating: 4.8,
    theforkReviewCount: 180,
    restaurantguruRating: 4.8,
    restaurantguruReviewCount: 180,

    tip: 'Take an easy stroll through the traditional mud-stone village of Oumesnat nearby before settling down for lunch on the scenic garden terrace.',
    archetypeAffinity: ['nature-lover', 'hiking-enthusiast', 'peace-seeker'],
    vibeTags: ['ameln-valley', 'argan-groves', 'jebel-lekst', 'peaceful-orchards'],
    isHiddenGem: true,
    paymentMethods: ['cash'],
    reservationMethod: ['phone'],
    reservationContact: '+212661849202',
    googleMapsUrl: 'https://maps.google.com/?q=Maison+Tissaline+Ameln+Valley+Tafraoute',
    bestDishes: ['Slow-Cooked Lamb with Wild Thyme & Figs', 'Ameln Garden Salad with Cold-Pressed Argan Oil', 'Fresh Fig & Almond Crumble Tart'],
    alcoholPolicy: 'dry',
    ramadanFriendly: 'special-ftour',
    customStory: 'Settled in the verdant Ameln Valley where water springs bubble between palm trees and ancient almond orchards, Maison Tissaline is run with meticulous love. The owners prepare meals using extra virgin argan oil harvested directly from the family’s centenary trees.',
    languagesSpoken: ['French', 'English', 'Arabic/Darija', 'Tachelhit/Berber'],
    exactAddressAndCoordinates: {
      address: 'Douar Oumesnat, Vallée des Ameln, Tafraoute 85000, Morocco',
      lat: 29.74850,
      lng: -8.95620
    },
    pros: [
      'Serene pastoral setting surrounded by ancient almond groves and spring-fed canals.',
      'Exceptional quality pure argan oil and farm-fresh valley ingredients.',
      'Refined yet homely presentation with delicate wild herb seasonings.'
    ],
    cons: [
      'Located 6 km north of Tafraoute town; accessible by car or taxi.',
      'Advance notice recommended for lunch to ensure personalized preparation.'
    ],
    bestTimeToVisit: 'Lunch around 13:00 under the palm shading',
    averageWaitMinutes: 10,
    seatingTypes: ['indoor', 'terrace', 'garden'],
    viewType: 'mountain',
    wiFi: true,
    airConditioning: false,
    wheelchairAccessible: true
  ,
    tags: ["budget", "dinner", "dry", "mountain", "quiet", "terrace", "wifi"]
  }
];
